### ISSUE TITLE
Error: Illegal mix of collations when using `asExpression` property with MariaDB

### ISSUE THREAD

**Issue by PanSzelescik** [typeorm/typeorm#10002]
### Issue description

Illegal mix of collations when using `asExpression` property with MariaDB.

### Expected Behavior

Add virtual column for easier extracting values from stored json in another column in the same table

### Actual Behavior

Error and app crash:
```
18:28:13.612 ERROR [db:error] Error in query: SELECT `t`.*, `v`.`check_option` FROM `typeorm_metadata` `t` INNER JOIN `information_schema`.`views` `v` ON `v`.`table_schema` = `t`.`schema` AND `v`.`table_name` = `t`.`name` WHERE `t`.`type` = 'VIEW'
18:28:13.612 ERROR Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_polish_ci,IMPLICIT) for operation '='
{"code":"ER_CANT_AGGREGATE_2COLLATIONS","errno":1267,"sqlState":"HY000","sqlMessage":"Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_polish_ci,IMPLICIT) for operation '='","sql":"SELECT `t`.*, `v`.`check_option` FROM `typeorm_metadata` `t` INNER JOIN `information_schema`.`views` `v` ON `v`.`table_schema` = `t`.`schema` AND `v`.`table_name` = `t`.`name` WHERE `t`.`type` = 'VIEW' "}
Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_polish_ci,IMPLICIT) for operation '='
    at Packet.asError (C:\Git\bot\node_modules\mysql2\lib\packets\packet.js:728:17)
    at Query.execute (C:\Git\bot\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Git\bot\node_modules\mysql2\lib\connection.js:489:32)
    at PacketParser.onPacket (C:\Git\bot\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (C:\Git\bot\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Git\bot\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)

C:\Git\bot\src\driver\mysql\MysqlQueryRunner.ts:222
                                new QueryFailedError(query, parameters, err),
                                ^
QueryFailedError: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_polish_ci,IMPLICIT) for operation '='
    at Query.onResult (C:\Git\bot\src\driver\mysql\MysqlQueryRunner.ts:222:33)
    at Query.execute (C:\Git\bot\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (C:\Git\bot\node_modules\mysql2\lib\connection.js:489:32)
    at PacketParser.onPacket (C:\Git\bot\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (C:\Git\bot\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Git\bot\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)```

### Steps to reproduce

1. Create simple entity with column with `asExpression` property and register it:
```ts
@Entity()
export default class SimpleEntity {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column('json', {nullable: false})
    result!: object;

    @Column({
        type: 'varchar',
        asExpression: "JSON_UNQUOTE(JSON_EXTRACT(`result`, '$.name'))"
    })
    name!: string;
}
```
2. Crash when initializing.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Debian 10    |
| Node.js version     | 18.16.0  |
| Typescript version  | 4.8.4 |
| TypeORM version     | 0.3.15  |
| mysql2 version | 3.2.4 |
| MariaDB version     | 10.3.38-MariaDB-0+deb10u1 - Debian 10  |

### Additional Context

I'm using mysql2 driver, not mysql2, but it's not on the list with MariaDB

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by PanSzelescik** [comment]
Idk why I add this twice, check #10003
