### ISSUE TITLE
Cant update entity with relation

### ISSUE THREAD

**Issue by GabrielHK97** [typeorm/typeorm#10046]
### Issue description

when calling the update method from a repository, it cant update an entity with a relation

### Expected Behavior

it should update the field inside the related entity

### Actual Behavior

It does not update the related entity field. I suspect it is because the forEach des not check it the entity has a relationship with another entity.

### Steps to reproduce

```
import { TypeORMConstants } from 'src/contants/typeorm.constants';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity({name: TypeORMConstants.personTable})
export class Person {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'bigint', unique: true})
  cpf: number;

  @Column({ type: 'varchar', length: 255 })
  name: string;

  @Column({ type: 'varchar', length: 50 })
  surname: string;

  @Column({ type: 'date' })
  birthdate: Date;
}
```

```
import { TypeORMConstants } from 'src/contants/typeorm.constants';
import { Person } from 'src/objects/persons/entities/person.entity';
import { Store } from 'src/objects/stores/entities/store.entity';
import {
  Column,
  Entity,
  JoinColumn,
  OneToMany,
  OneToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity({ name: TypeORMConstants.ownerTable })
export class Owner {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 50, unique: true })
  username: string;

  @Column({ type: 'varchar', length: 50 })
  password: string;

  @OneToOne(() => Person,{ cascade: true, eager: true })
  @JoinColumn()
  person: Person;

  @OneToMany(() => Store, (store) => store.owner)
  stores: Store[];
}
```

```
import { Inject, Injectable } from '@nestjs/common';
import { ServiceData } from 'src/serviceData/classes/serviceData.class';
import { Repository } from 'typeorm';
import { CreateOwnerDto } from './dto/create-owner.dto';
import { UpdateOwnerDto } from './dto/update-owner.dto';
import { Owner } from './entities/owner.entity';

@Injectable()
export class OwnersService {
  constructor(@Inject('OWNER_REPOSITORY') private ownerRepository: Repository<Owner>) {}

  create(createOwnerDto: CreateOwnerDto): ServiceData {
    const serviceData = new ServiceData();
    try {
      serviceData.setStatusCode(200);
      serviceData.setMessage('Created with success!');
      const owner = this.ownerRepository.create(createOwnerDto);
      this.ownerRepository.save(owner);
    } catch(e) {
      serviceData.setStatusCode(500);
      serviceData.setMessage('Error while creating owner!');
    }
    return serviceData;
  }

  findAll() {
    return `This action returns all owners`;
  }

  async findOne(id: number) {
    const serviceData = new ServiceData();
    try {
      const owner = await this.ownerRepository.findOneBy({id});
      serviceData.setStatusCode(200);
      serviceData.setMessage('Found with success!');
      serviceData.setData(owner);
    } catch (e) {
      serviceData.setStatusCode(500);
      serviceData.setMessage('Error while updating owner!');
    }
    return serviceData;
  }

  update(id: number, updateOwnerDto: UpdateOwnerDto) {
    const serviceData = new ServiceData();
    try {
      serviceData.setStatusCode(200);
      serviceData.setMessage('Updated with success!');
      const owner = this.ownerRepository.create(updateOwnerDto);
      this.ownerRepository.update({id}, owner);
    } catch(e) {
      serviceData.setStatusCode(500);
      serviceData.setMessage('Error while updating owner!');
    }
    return serviceData;
  }

  remove(id: number) {
    return `This action removes a #${id} owner`;
  }
}
```

It gives the following error:
```
/Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/UpdateQueryBuilder.ts:493
            this.createPropertyPath(metadata, valuesSetNormalized).forEach(
                                                                   ^
EntityPropertyNotFoundError: Property "person.name" was not found in "Owner". Make sure your query is correct.
    at /Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/UpdateQueryBuilder.ts:500:31
    at Array.forEach (<anonymous>)
    at UpdateQueryBuilder.createUpdateExpression (/Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/UpdateQueryBuilder.ts:493:68)
    at UpdateQueryBuilder.getQuery (/Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/UpdateQueryBuilder.ts:53:21)
    at UpdateQueryBuilder.getQueryAndParameters (/Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/QueryBuilder.ts:507:28)
    at UpdateQueryBuilder.execute (/Users/gabrielhk97/Documents/kwode.in/pocketo/backend/src/query-builder/UpdateQueryBuilder.ts:142:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | x.y.zzz  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by juliengbt** [comment]
It is the expected behavior. If you need to update the person entity you need to use the person repository.
However you can perform cascade updates with the `.save()` method instead of `.update()`
