### ISSUE TITLE
The connectTimeout setting ignored for CLI

### ISSUE THREAD

**Issue by pro100kryto** [typeorm/typeorm#10073]
### Issue description

The connectTimeout setting ignored for CLI

### Expected Behavior

My database connection response is longer than 10sec. When i set value for `connectTimeout` attribute into my DataSource, it should change the connection timeout when I use CLI.

### Actual Behavior

Error: Handshake inactivity timeout
    at Handshake.<anonymous> (project_path\node_modules\mysql\lib\protocol\Protocol.js:160:17)
    at Handshake.emit (node:events:513:28)
    at Handshake.emit (node:domain:489:12)
    at Handshake._onTimeout (project_path\node_modules\mysql\lib\protocol\sequences\Sequence.js:124:8)
    at Timer._onTimeout (project_path\node_modules\mysql\lib\protocol\Timer.js:32:23)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
    --------------------
    at Protocol._enqueue (project_path\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (project_path\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (project_path\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (project_path\node_modules\mysql\lib\Pool.js:48:16)
    at project_path\src\driver\mysql\MysqlDriver.ts:1265:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (project_path\src\driver\mysql\MysqlDriver.ts:1262:16)
    at MysqlDriver.connect (project_path\src\driver\mysql\MysqlDriver.ts:400:36)
    at DataSource.initialize (project_path\src\data-source\DataSource.ts:249:27)
    at Object.handler (project_path\src\commands\MigrationGenerateCommand.ts:82:30) {
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000
}

### Steps to reproduce

package.json
`"scripts": {
 ...
 "typeorm": "typeorm-ts-node-commonjs"
}`

cli-data-source.js
`{
 ...
 connectTimeout: 25000,
}`

command: `npm run typeorm migration:generate -- new -d dist\cli-data-source.js`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 10  |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pro100kryto** [comment]
I found that there is `acquireTimeout` property that i need to set.
