### ISSUE TITLE
Tree entity Materialized Path error when run if exist data in database

### ISSUE THREAD

**Issue by lequangkhanh2901** [typeorm/typeorm#10078]
### Issue description

Tree entity Materialized Path error when run if exist data in database

### Expected Behavior

No error

### Actual Behavior

I have a `Tree Entity` with `@Tree('materialized-path')`

Ex: 

```
import { Column, Entity, PrimaryGeneratedColumn, Tree, TreeChildren, TreeParent } from 'typeorm'

@Entity()
@Tree('materialized-path')
export default class Category {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column()
  name: string

  @TreeChildren()
  children: Category[]

  @TreeParent()
  parent: Category
}
```

AppDataSource: 

```
import 'reflect-metadata'
import { DataSource } from 'typeorm'
import Category from './entity/Category'

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: 'localhost',
  username: 'root',
  password: '',
  database: 'type_orm_tree_entity',
  synchronize: true,
  logging: false,
  entities: [Category],
  migrations: [],
  subscribers: [],
})
```

index.ts:

```
AppDataSource.initialize()
  .then(async () => {
    console.log('connected')
  })
  .catch((error) => console.log(error))
```

Every thing are ok when first initialize, create data and save to database.
But when initialize with existing data(There are some row in `Category` table) in database: 

```
QueryFailedError: Duplicate entry '' for key 'PRIMARY'
    at Query.onResult (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.execute (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:490:32)
    at PacketParser.onPacket (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:95:12)
    at PacketParser.executeStart (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:102:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  query: 'ALTER TABLE `category` ADD `id` varchar(36) NOT NULL PRIMARY KEY',
  parameters: undefined,
  driverError: Error: Duplicate entry '' for key 'PRIMARY'
      at Packet.asError (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:490:32)
      at PacketParser.onPacket (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:95:12)
      at PacketParser.executeStart (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/home/khanh/WorkSpace/express/typeOrm/typeorm-tree-entity/node_modules/mysql2/lib/connection.js:102:25)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry '' for key 'PRIMARY'",
    sql: 'ALTER TABLE `category` ADD `id` varchar(36) NOT NULL PRIMARY KEY'
  },
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '' for key 'PRIMARY'",
  sql: 'ALTER TABLE `category` ADD `id` varchar(36) NOT NULL PRIMARY KEY'
}
```

### Steps to reproduce

Categoty entity: 
```
import { Column, Entity, PrimaryGeneratedColumn, Tree, TreeChildren, TreeParent } from 'typeorm'

@Entity()
@Tree('materialized-path')
export default class Category {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column()
  name: string

  @TreeChildren()
  children: Category[]

  @TreeParent()
  parent: Category
}
```

AppDataSource:
```
import 'reflect-metadata'
import { DataSource } from 'typeorm'
import Category from './entity/Category'

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: 'localhost',
  username: 'root',
  password: '',
  database: 'type_orm_tree_entity',
  synchronize: true,
  logging: false,
  entities: [Category],
  migrations: [],
  subscribers: [],
})
```

index.ts:
```
import { AppDataSource } from './data-source'
import Category from './entity/Category'
import Express, { Application, Request, Response } from 'express'

AppDataSource.initialize()
  .then(async () => {
    console.log('connected')
  })
  .catch((error) => console.log(error))

const app: Application = Express()

app.get('/create', async (req: Request, res: Response) => {
  try {
    const categoryRepository = AppDataSource.manager.getTreeRepository(Category)

    const cateparent1 = new Category()
    cateparent1.name = 'cate parent 1'
    await categoryRepository.save(cateparent1)

    const cateparent2 = new Category()
    cateparent2.name = 'cate parent 2'
    await categoryRepository.save(cateparent2)

    const catechild1 = new Category()
    catechild1.name = 'cate child 1'
    catechild1.parent = cateparent1
    await categoryRepository.save(catechild1)

    const catechild2 = new Category()
    catechild2.name = 'cate child 2'
    catechild2.parent = cateparent1
    await categoryRepository.save(catechild2)

    const catechild3 = new Category()
    catechild3.name = 'cate child 3'
    catechild3.parent = catechild1
    await categoryRepository.save(catechild3)

    return res.send('ok')
  } catch (error) {
    console.log(error)
    return res.send('fail')
  }
})

app.get('/', async (req: Request, res: Response) => {
  try {
    const categoryRepository = AppDataSource.getTreeRepository(Category)

    const categories = await categoryRepository.findTrees()

    console.log(categories)

    return res.json({ categories })
  } catch (error) {
    console.log(error)

    return res.send('fail')
  }
})

app.listen(3002)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System   | ubuntu 20.04 |
| Node.js version     | 16.20.0 |
| Typescript version  | 4.5.2  |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by lequangkhanh2901** [comment]
`Closure table` is same

**Comment by lequangkhanh2901** [comment]
After some test, `uuid` cause this bug.
