### ISSUE TITLE
Bug introduced for UpdateQueryBuilder in 0.3.14

### ISSUE THREAD

**Issue by oceanofmaya** [typeorm/typeorm#10157]
### Issue description

The QueryBuilder performance optimizations (#9914) (12e9db0) introduced in 0.3.14 replaces non-alias text in query breaking functionality by changing the query when run.

### Expected Behavior

When a COALESCE statement is using in an UpdateQueryBuilder to append to a jsonb column, it works when a valid JSON is used and the value/data that is passed along is persisted without alteration.

### Actual Behavior

The data passed to the COALESCE statement is altered and content in it is getting replaced by alias names that not only alters data but also results in invalid json input causing the query to fail to execute. It works perfectly in version <= 0.3.13

### Steps to reproduce

I have altered the code a bit to remove org specific information.

Here is my entity 

```
@Entity('some_svc.recipient')
class Recipient {
  @PrimaryColumn({ type: 'integer', name: 'recipient_email_key' })
  recipientEmailKey: number;

  @PrimaryColumn({ type: 'uuid', name: 'email_uuid' })
  emailUuid: string;

  @ManyToOne(/* istanbul ignore next */ () => Email, /* istanbul ignore next */ (email) => email.recipients)
  @JoinColumn({ name: 'email_uuid', referencedColumnName: 'emailUuid' })
  email: Email;

  @Column({ type: 'varchar', length: 100, name: 'recipient_email_address', nullable: false })
  recipientEmailAddress: string;

  @Column({ type: 'jsonb', name: 'delivery_status_json', nullable: true })
  deliveryStatusJson: Record<string, unknown> | Record<string, unknown>[];

  @Column({ type: 'varchar', length: 50, name: 'message_id', nullable: true })
  messageId: string;

  @Column({ type: 'timestamp with time zone', name: 'email_delivery_status_ts', nullable: true })
  emailDeliveryStatusTs: string;
}
```

Here is my code that does the update where the `delivery_status_json` is appended with whatever was received by AWS SES

```
   // sanitize it using stringify and escape any single quotes
    const sanitizedDeliveryStatusJson = JSON.stringify(emailStatusUpdateRequest.deliveryStatusJson).replace(/'/g, "''");

    const concatDeliveryStatusJsonQuery = `COALESCE (delivery_status_json, '[]'::jsonb) || '${sanitizedDeliveryStatusJson}'::jsonb`;
    console.debug(concatDeliveryStatusJsonQuery', concatDeliveryStatusJsonQuery);

    await dataSource
      .createQueryBuilder()
      .update(Recipient)
      .set({
        emailDeliveryStatusTs: emailStatusUpdateRequest.emailDeliveryStatusTs,
        deliveryStatusJson: /* istanbul ignore next */ () => concatDeliveryStatusJsonQuery,
      })
      .where('recipient.message_id = :messageId', {
        messageId: emailStatusUpdateRequest.messageId,
      })
      .andWhere('recipient.recipient_email_address IN (:...recipientEmailAddresses)', {
        recipientEmailAddresses: emailStatusUpdateRequest.recipientEmailAddresses,
      })
      .execute();
  }
  ```
  
 Here is an example of the deliveryStatusJson that was extracted from SES notification
 
 ```
 {
  "messageId": "01000188dd65b5f5-804ecf85-5888-4929-b3d0-8e205553fb9d-000000",
  "deliveryStatusJson": {
    "feedbackId": "01000188f8c1cd0c-b4e26e78-c6d5-47c3-a9a6-ecb864a017e4-000000",
    "bounceType": "Permanent",
    "bounceSubType": "General",
    "bouncedRecipients": [
      {
        "emailAddress": "tosayiw600@extemer.com",
        "action": "failed",
        "status": "5.1.1",
        "diagnosticCode": "smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient's email address for typos or\n550-5.1.1 unnecessary spaces."
      }
    ],
    "timestamp": "2023-06-21T10:00:11.098Z",
    "reportingMTA": "dns; a49-192.smtp-out.amazonses.com"
  },
  "recipientEmailAddresses": [
    "tosayiw600@extemer.com"
  ],
  "emailDeliveryStatusTs": "2023-06-26T17:37:50.525Z"
}
 ```
 
 Here is what the `concatDeliveryStatusJsonQuery` debug prints and that looks correct.
 ```
 COALESCE (delivery_status_json, '[]'::jsonb) || '{"feedbackId":"01000188f8c1cd0c-b4e26e78-c6d5-47c3-a9a6-ecb864a017e4-000000","bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"tosayiw600@extemer.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient''s email address for typos or\n550-5.1.1 unnecessary spaces."}],"timestamp":"2023-06-21T10:00:11.098Z","reportingMTA":"dns; a49-192.smtp-out.amazonses.com"}'::jsonb
 ```
 
 But in >= 0.3.14 when that is fed into the query any text in `concatDeliveryStatusJsonQuery` that has the word `email` is getting replaced by `"email_uuid"` an that results in the following error
 
 ```
 INFO query failed: UPDATE "some_svc"."recipient" SET "email_delivery_status_ts" = $1, "delivery_status_json" = COALESCE ("delivery_status_json", '[]'::jsonb) || '{"feedbackId":"01000188f8c1cd0c-b4e26e78-c6d5-47c3-a9a6-ecb864a017e4-000000","bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"tosayiw600@extemer.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550-5.1.1 The "email_uuid" account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient''s "email_uuid" address for typos or\n550-5.1.1 unnecessary spaces."}],"timestamp":"2023-06-21T10:00:11.098Z","reportingMTA":"dns; a49-192.smtp-out.amazonses.com"}'::jsonb WHERE recipient.message_id = $2 AND recipient.recipient_email_address IN ($3) -- PARAMETERS: ["2023-06-27T02:04:33.740Z","01000188dd65b5f5-804ecf85-5888-4929-b3d0-8e205553fb9d-000000","tosayiw600@extemer.com"]

{
  "errorType": "R3",
  "errorMessage": "invalid input syntax for type json",
  "code": "22P02",
  "query": "UPDATE \"some_svc\".\"recipient\" SET \"email_delivery_status_ts\" = $1, \"delivery_status_json\" = COALESCE (\"delivery_status_json\", '[]'::jsonb) || '{\"feedbackId\":\"01000188f8c1cd0c-b4e26e78-c6d5-47c3-a9a6-ecb864a017e4-000000\",\"bounceType\":\"Permanent\",\"bounceSubType\":\"General\",\"bouncedRecipients\":[{\"emailAddress\":\"tosayiw600@extemer.com\",\"action\":\"failed\",\"status\":\"5.1.1\",\"diagnosticCode\":\"smtp; 550-5.1.1 The \"email_uuid\" account that you tried to reach does not exist. Please try\\n550-5.1.1 double-checking the recipient''s \"email_uuid\" address for typos or\\n550-5.1.1 unnecessary spaces. Learn more at\\n550 5.1.1  https://support.google.com/mail/?p=NoSuchUser u5-20020a05622a198500b003f6b218debbsi76433qtc.372 - gsmtp\"}],\"timestamp\":\"2023-06-21T10:00:11.098Z\",\"reportingMTA\":\"dns; a49-192.smtp-out.amazonses.com\"}'::jsonb WHERE recipient.message_id = $2 AND recipient.recipient_email_address IN ($3)",
  "parameters": [
    "2023-06-27T02:04:33.740Z",
    "01000188dd65b5f5-804ecf85-5888-4929-b3d0-8e205553fb9d-000000",
    "tosayiw600@extemer.com"
  ],
  "driverError": {
    "errorType": "error",
    "errorMessage": "invalid input syntax for type json",
    "code": "22P02",
    "length": 213,
    "name": "error",
    "severity": "ERROR",
    "detail": "Token \"email_uuid\" is invalid.",
    "position": "144",
    "where": "JSON data, line 1: ...\"diagnosticCode\":\"smtp; 550-5.1.1 The \"email_uuid...",
    "file": "jsonfuncs.c",
    "line": "625",
    "routine": "json_ereport_error",
    "stack": [
      "error: invalid input syntax for type json",
      "    at U4.parseErrorMessage (/var/task/index.js:50:45043)",
      "    at U4.handlePacket (/var/task/index.js:50:41702)",
      "    at U4.parse (/var/task/index.js:50:40332)",
      "    at TLSSocket.<anonymous> (/var/task/index.js:50:45740)",
      "    at TLSSocket.emit (node:events:513:28)",
      "    at addChunk (node:internal/streams/readable:324:12)",
      "    at readableAddChunk (node:internal/streams/readable:297:9)",
      "    at Readable.push (node:internal/streams/readable:234:10)",
      "    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"
    ]
  },
  "length": 213,
  "severity": "ERROR",
  "detail": "Token \"email_uuid\" is invalid.",
  "position": "144",
  "where": "JSON data, line 1: ...\"diagnosticCode\":\"smtp; 550-5.1.1 The \"email_uuid...",
  "file": "jsonfuncs.c",
  "line": "625",
  "routine": "json_ereport_error",
  "stack": [
    "R3: invalid input syntax for type json",
    "    at JH.query (/var/task/index.js:146:27282)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async oj.execute (/var/task/index.js:153:11457)",
    "    at async wU.updateRecipients (/var/task/index.js:161:71927)",
    "    at async wU.updateEmailDeliveryStatus (/var/task/index.js:161:71102)",
    "    at async Runtime.OJt [as handler] (/var/task/index.js:161:72470)"
  ]
}
 ```
 
 In <= 0.3.13 version when I log the query executed I see this, which is accurate
 ```
 INFO query: UPDATE "some_svc"."recipient" SET "email_delivery_status_ts" = $1, "delivery_status_json" = COALESCE (delivery_status_json, '[]'::jsonb) || '{"feedbackId":"01000188f8c1cd0c-b4e26e78-c6d5-47c3-a9a6-ecb864a017e4-000000","bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"tosayiw600@extemer.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient''s email address for typos or\n550-5.1.1 unnecessary spaces."}],"timestamp":"2023-06-21T10:00:11.098Z","reportingMTA":"dns; a49-192.smtp-out.amazonses.com"}'::jsonb WHERE recipient.message_id = $2 AND recipient.recipient_email_address IN ($3) -- PARAMETERS: ["2023-06-27T02:15:01.912Z","01000188dd65b5f5-804ecf85-5888-4929-b3d0-8e205553fb9d-000000","tosayiw600@extemer.com"]
 ```

### My Environment

| Dependency        | Version |
| ---                 | ---      |
| Operating System    |    amazonlinux (lambda)      |
| Node.js version     | v18.16.0  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.17  |

### Additional Context

I also tried using `dataSource.manager.update` and was met with the same behavior in >= 0.3.14

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by oceanofmaya** [comment]
Here is a screenshot highlighting the replacement of text in query at the time of running from the example above
![image](https://github.com/typeorm/typeorm/assets/33257049/d741ed10-d0f7-4be0-8782-8c6cebf6d41d)

**Comment by oceanofmaya** [comment]
In my example since I had the below in the entity, when the optimization that was introduced in 0.3.14 executed it replaced  the word `email` in multiple places with `email_uuid` but it did it for something it shouldn't have done and ended up altering the value I was trying to add using the COALESCE statement. 

```
 @ManyToOne(/* istanbul ignore next */ () => Email, /* istanbul ignore next */ (email) => email.recipients)
 @JoinColumn({ name: 'email_uuid', referencedColumnName: 'emailUuid' })
  email: Email;
```

**Comment by Yuuki-Sakura** [comment]
change you query builder to
```
   // sanitize it using stringify and escape any single quotes
    await dataSource
      .createQueryBuilder()
      .update(Recipient)
      .set({
        emailDeliveryStatusTs: emailStatusUpdateRequest.emailDeliveryStatusTs,
        deliveryStatusJson: /* istanbul ignore next */ () => `COALESCE (delivery_status_json, '[]'::jsonb) || :sanitizedDeliveryStatusJson::jsonb`,
      })
      .setParameter('sanitizedDeliveryStatusJson', JSON.stringify(emailStatusUpdateRequest.deliveryStatusJson))
      .where('recipient.message_id = :messageId', {
        messageId: emailStatusUpdateRequest.messageId,
      })
      .andWhere('recipient.recipient_email_address IN (:...recipientEmailAddresses)', {
        recipientEmailAddresses: emailStatusUpdateRequest.recipientEmailAddresses,
      })
      .execute();
  }
```

**Comment by oceanofmaya** [comment]
@Yuuki-Sakura Thank you for the response. Excellent suggestion. I will try this out in the next few days and see if that resolves the issue and update this ticket. I expect it to work as parametrizing should prevent the optimization to run on the data itself. I had not considered using the parameter as I was using the function that took a string for coalescing.

**Comment by oceanofmaya** [comment]
@Yuuki-Sakura I tried it out and it worked. Thank you.
