### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'driver')

### ISSUE THREAD

**Issue by ulvimemmeedov** [typeorm/typeorm#10164]
### Issue description

when i use query runner for transaction i get this error

### Expected Behavior

transaction work

### Actual Behavior
error line my code
`
 setQueryRunner({ createQueryRunner }: DataSource) {
        this.queryRunner = createQueryRunner('master');
    }
`
error 
`
[Nest] 48095  - 06/28/2023, 3:05:26 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'driver')
TypeError: Cannot read properties of undefined (reading 'driver')
    at createQueryRunner (/Users/username/Desktop/projects/folder/task_rider/foldername/server/src/data-source/DataSource.ts:590:34)
`

### Steps to reproduce

[Nest] 48095  - 06/28/2023, 3:05:26 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'driver')
TypeError: Cannot read properties of undefined (reading 'driver')
    at createQueryRunner (/Users/user/Desktop/projects/folder/projectfolder/api/server/src/data-source/DataSource.ts:590:34)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     osx    |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.0.0  |
| TypeORM version     | 9.0.1  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ulvimemmeedov** [comment]
i fixed the problem.
change this line setQueryRunner({ createQueryRunner }: DataSource) { this.queryRunner = createQueryRunner('master'); }
to setQueryRunner(dataSource: DataSource) { this.queryRunner = createQueryRunner('master'); }
