### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by nizalsha** [typeorm/typeorm#10173]
I get this error when i used with typescript.

ERROR TypeError: Cannot read properties of undefined (reading 'type')
    at EntityManagerFactory.create (EntityManagerFactory.js:12:39)
    at DataSource.createEntityManager (DataSource.js:398:43)
    at new DataSource (DataSource.js:51:29)
    at AppComponent.ngOnInit (app.component.ts:18:27)
    at callHook (core.mjs:2498:22)
    at callHooks (core.mjs:2467:17)
    at executeInitAndCheckHooks (core.mjs:2418:9)
    at refreshView (core.mjs:12026:21)
    at detectChangesInternal (core.mjs:13229:9)
    at RootViewRef.detectChanges (core.mjs:13741:9)

And my declarations are as following

`import { Component } from '@angular/core';
import "reflect-metadata";
import { DataSource } from "typeorm";
import { Post } from "../entity/Post"
import { Category } from "../entity/Category"
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ezpharmacy';

  constructor() {}

  ngOnInit(): void {
    const AppDataSource = new DataSource({
      type: "mssql",
      host: "swmenadb4.c9y34o1ascfe.me-south-1.rds.amazonaws.com",
      port: 1433,
      username: "swapi",
      password: "api2019",
      database: "Ezb_MarkabahPartsAdb",
      synchronize: true,
      logging: true,
      entities: [Post, Category],
      subscribers: [],
      migrations: [],
    });
    AppDataSource.initialize()
    .then(() => {
        console.log("Data Source has been initialized!")
    })
    .catch((err) => {
        console.error("Error during Data Source initialization", err)
    })
  }
}
`
I dont know what is wrong in here because it shows no error when served( ng serve)

**Comment by WRCoding** [comment]
Hello, have you solved this problem？

**Comment by saficool** [comment]
I also having similar issue
