### ISSUE TITLE
Parameters in comments are escaped

### ISSUE THREAD

**Issue by smcgivern** [typeorm/typeorm#10207]
### Issue description

When adding a query comment containing a colon followed by letters, it's treated as a parameter

### Expected Behavior

The comment should be un-mangled and we should not add a parameter to the parameter list.

### Actual Behavior

Parameter replacement applies to the whole query, including comments, and we then send the wrong number of parameters to the database driver (because the DB will ignore comments and therefore not see the 'parameter' in there).

### Steps to reproduce

This failing test demonstrates the issue:

```diff
diff --git a/test/functional/query-builder/parameters/query-builder-parameters.ts b/test/functional/query-builder/parameters/query-builder-parameters.ts
index 76b24d374..2cf97c667 100644
--- a/test/functional/query-builder/parameters/query-builder-parameters.ts
+++ b/test/functional/query-builder/parameters/query-builder-parameters.ts
@@ -31,9 +31,10 @@ describe("query builder > parameters", () => {
                     .createQueryBuilder()
                     .setParameter("foo", "bar")
                     .where("example.id = :foo")
-                    .getOne()
+                    .comment(':foo')
 
-                expect(example?.id).to.be.equal("bar")
+                console.log(example.getQueryAndParameters())
+                expect((await example.getOne())?.id).to.be.equal("bar")
             }),
         ))
 
```

The output is:

```
  query builder > parameters
[
  '/* ? */ SELECT "Example"."id" AS "Example_id" FROM "example" "Example" WHERE example.id = ?',
  [ 'bar', 'bar' ]
]
    1) should replace basic parameters when executing


  0 passing (34ms)
  1 failing

  1) query builder > parameters
       should replace basic parameters when executing:
     QueryFailedError: SQLITE_RANGE: column index out of range
      at Statement.handler (src/driver/sqlite/SqliteQueryRunner.ts:113:26)
      at Statement.replacement (node_modules/sqlite3/lib/trace.js:25:27)
      at Statement.replacement (node_modules/sqlite3/lib/trace.js:25:27)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     macOS Ventura   |
| Node.js version     | 18.15.0  |
| Typescript version  | 9.5.0  |
| TypeORM version     | `master` branch  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by smcgivern** [comment]
This also applies inside string literals 🙀 

```js
.where("example.id = :foo AND ':foo' = ':foo'")
```

Creates:

```sql
SELECT "Example"."id" AS "Example_id" FROM "example" "Example" WHERE example.id = ? AND '?' = '?'
```

**Comment by smcgivern** [comment]
Still valid, has a test case, but I'm not sure it's easy to fix or that important?
