### ISSUE TITLE
Key declaration time generates inconsistent database with `better-sqlite3-multiple-ciphers`

### ISSUE THREAD

**Issue by maximelafarie** [typeorm/typeorm#10230]
### Issue description

Depending on where the encryption key is declared (in the `DataSource` configuration or with `PRAGMA`), the generated database is only readable with one or the other, even if the key is the same.

### Expected Behavior

The database can't be read if the db.pragma("key='secret-key'") is declared with the `key` option or in the `prepareDatabase` hook.

### Actual Behavior

Make the database consistent independently of the way of declaring `db.pragma("key='secret-key'")`.

### Steps to reproduce

Let's say we create the database with the following configuration: 

```ts
export const AppDataSource = new DataSource({
    type: 'better-sqlite3',
    database: 'database',
    driver: require('better-sqlite3-multiple-ciphers'),
    key: 'secret-key',
    synchronize: false,
    entities: [
        //...
    ],
    migrations: [
        //...
    ],
    subscribers: [],
    prepareDatabase: db => {
        db.pragma(`cipher='sqlcipher'`);
        db.pragma(`legacy=4`);
    }
});
```
If you start the app, all works fine, the database is created and you can add data into it.
⚠️ Note: in this way, it is impossible to open the database in DB Browser for SQLite !

Now, without deleting the database, modify the `DataSource` configuration like this:
```ts
export const AppDataSource = new DataSource({
    type: 'better-sqlite3',
    database: 'database',
    driver: require('better-sqlite3-multiple-ciphers'),
    synchronize: false,
    entities: [
        //...
    ],
    migrations: [
        //...
    ],
    subscribers: [],
    prepareDatabase: db => {
        db.pragma(`cipher='sqlcipher'`);
        db.pragma(`legacy=4`);
        db.pragma("key='secret-key'"); // <----- this changed and the 'key' prop above is removed
    }
});
```

If you try to restart the app, you'll get the following error:
```sh
SqliteError: file is not a database
    at Database.prepare (/usr/app/node_modules/better-sqlite3-multiple-ciphers/lib/methods/wrappers.js:5:21)
    at BetterSqlite3QueryRunner.getStmt (/usr/app/src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts:44:43)
    at BetterSqlite3QueryRunner.query (/usr/app/src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts:89:22)
    at BetterSqlite3QueryRunner.hasTable (/usr/app/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts:227:24)
    at MigrationExecutor.createMigrationsTableIfNotExist (/usr/app/src/migration/MigrationExecutor.ts:503:28)
    at MigrationExecutor.executePendingMigrations (/usr/app/src/migration/MigrationExecutor.ts:195:9)
    at DataSource.runMigrations (/usr/app/src/data-source/DataSource.ts:397:13)
    at DataSource.initialize (/usr/app/src/data-source/DataSource.ts:268:17) {
  code: 'SQLITE_NOTADB'
}
```
⚠️ Note: in this way, if you remove the previously generated database, and recreate one with this configuration, **it is readable** by DB Browser for SQLite.

**WHY AM I ASKING THIS**
I previously generated my DB the first way I showed you in this example. But the @m4heshd [example](https://github.com/m4heshd/better-sqlite3-multiple-ciphers#encryption) on how to configure the DB to be readable by DB Browser for SQLite made my first conf incompatible.

I was assuming that the `key` option used [here](https://github.com/typeorm/typeorm/blob/master/src/driver/better-sqlite3/BetterSqlite3Driver.ts#L150) what already calling `db.pragma("key='secret-key'")` before anything, but it seems it generates a different database "encryption order" making it incompatible to be read if it is done in the `prepareDatabase` hook.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macOS Ventura 13.4     |
| Node.js version     | LTS (16)  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.15  |
| better-sqlite3 version     | 8.3.0  |
| better-sqlite3-multiple-ciphers version   | 8.3.0  |
| DB Browser for SQLite version   | 3.12.2  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [X] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by maximelafarie** [comment]
Very clear, thank you.
I definitely need to use the `key` pragma in `prepareDatabase` instead of the `key` attribute.
What's more, I want to take advantage of `sqlcipher` 4 instead of sqleet, and it also lets me read my database in DB4S.
🖖
