### ISSUE TITLE
.:AFTER BUILD EXEC:. EntityMetadataNotFoundError: No metadata for "x" was found. Node, Fastify

### ISSUE THREAD

**Issue by ArthurFakhouri** [typeorm/typeorm#10235]
### Issue description

When an entity is consulted, it throws the following error: EntityMetadataNotFoundError

### Expected Behavior

Any Entity be accessed without problems after build the application. When is executed on development mode, it works perfectly.

### Actual Behavior

When the application request a route on server and the server tries to access a Repository, it gives me error trying to access the Entity, see example below: 
EntityMetadataNotFoundError: No metadata for "x" was found.
    at DataSource.getMetadata (__dirname\server\node_modules\typeorm\data-source\DataSource.js:288:19)
    at get metadata [as metadata] (__dirname\server\node_modules\typeorm\repository\Repository.js:23:40)
    at Repository.save (__dirname\server\node_modules\typeorm\repository\Repository.js:76:39)
    at Object.<anonymous> (__dirname\server\build\server.js:3338:73)

### Steps to reproduce

No Steps.

### My Environment

| Dependency                    | Version  |
| Operating System            |     Windows    |
| Node.js version               | 18.15.0  |
| Typescript version            | 5.1.6  |
| TypeORM version               | 0.3.17  |

### Additional Context

export const typeorm = new DataSource({
      type: "oracle",
      host: process.env.DB_HOST,
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      port,
      sid: process.env.DB_SID,
      synchronize: true,
      logging: false,
      entities: [process.env.NODE_ENV === "production" ?
          `${__dirname}/../**/build/db/entities/*.{ts,js}`
          : `${__dirname}/../**/src/db/entities/*.{ts,js}`],
      migrations: [process.env.NODE_ENV === "production" ?
          `${__dirname}/../**/build/db/migrations/*.{ts,js}`
          : `${__dirname}/../**/src/db/migrations/*.{ts,js}`]
})

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [X] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by ArthurFakhouri** [comment]
Weak Solution: when GetRepository is called, I'm giving as parameter, the string of Entity
Example: 
instead of use: getRepository(User)
I'll use: getRepository("User")
it works, but I'll try to find why class is not matching.

The Problem:
When I request a "getRepository" function, it will call another function called "findMetadata(target)" and in the first condition it will compare (metadata.target === target), in other words, the class Entity generated by constructor of DataSource comparing with the Entity that I'm giving as parameter, as result in development side it works perfectly but in production mode it does not

Probably there is something wrong when I'm generating build, version of target idk, I'll try to find the problem...

**Comment by ArthurFakhouri** [comment]
After some looking, I realized tsup was the problem, probably there is some config to set to work perfectly but I preferred to use tsc and it works perfectly
