### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by IfyNdu** [typeorm/typeorm#10293]
### Issue description

Failure to a establish a connection with postgres db when a connection string is provided.

### Expected Behavior

Ability to successfully connect to postgres db through connection string.

### Actual Behavior

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at parse (/Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/pg/node_modules/pg-connection-string/index.js:29:14)
    at new ConnectionParameters (/Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/pg/lib/connection-parameters.js:56:42)
    at new Client (/Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/pg/lib/client.js:18:33)
    at BoundPool.newClient (/Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/pg-pool/index.js:218:20)
    at BoundPool.connect (/Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/pg-pool/index.js:212:10)
    at /Users/ify/Developer/JS/climate-risk-services/CRS.WebPlatform/node_modules/typeorm/driver/postgres/PostgresDriver.js:1163:18
    at new Promise (<anonymous>) {
  input: 'postgresql://user:password@host:5432/db',
  code: 'ERR_INVALID_URL'
}
```

### Steps to reproduce

```ts
export const dataSourceOptions: DataSourceOptions = {
    database: process.env.DB_NAME,
    entities,
    url: process.env.DB_CONN_URL // postgresql://user:password@host:5432/db,
    migrations: ['packages/enterprise-api/migrations/typeorm/*.js'],
    type: 'postgres',
};
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Mac OS Ventura        |
| Node.js version     | 16.16.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.12  |

### Additional Context

Exact connection string works as expected with 3rd party DBMS.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by MiichaelJose** [comment]
No parametro "url: process.env.DB_CONN_URL" coloque apenas "postgresql://"
