### ISSUE TITLE
new DataSource creates  

### ISSUE THREAD

**Issue by aymeric75** [typeorm/typeorm#10318]
### Issue description

instanciating DataSource creates an error

### Expected Behavior

no error

### Actual Behavior

In the console, it creates this error:
```

Uncaught (in promise) TypeError: connection.driver.options is undefined
create webpack://dev/../../../node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js?:19
    createEntityManager webpack://dev/../../../node_modules/typeorm/browser/data-source/DataSource.js?:417
    DataSource webpack://dev/../../../node_modules/typeorm/browser/data-source/DataSource.js?:70
    handleTextUpdated webpack://dev/./src/components/MainText.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]:31
    handleTextUpdated webpack://dev/./src/components/MainComponent.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]:17
    callWithErrorHandling webpack://dev/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:296
    callWithAsyncErrorHandling webpack://dev/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:304
    emit webpack://dev/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:800
    logValue webpack://dev/./src/components/InputArea.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]:12
    1 webpack://dev/./src/components/InputArea.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[4]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]:39
    callWithErrorHandling webpack://dev/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:296
    callWithAsyncErrorHandling webpack://dev/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:304
    invoker webpack://dev/./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js?:437

```

### Steps to reproduce

In one of my Vue component, I have this code:

```

import { DataSource } from "typeorm";



export default {
  name: 'MainText',
  components: {
    ResultRow
  },

  methods: {

    async handleTextUpdated(newText) {


      const MysqlDataSource = new DataSource({
        type: "mysql",
        host: "127.0.0.1",
        port: "",
        username: "prestauser",
        password: "password",
        database: "presta_h2s",
      });
      console.log(MysqlDataSource);

....
```

And when I press a button that executes **handleTextUpdated** , I get the error described above

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      Mint
| Node.js version     | 20.5.7
| Typescript version  | 4.5.5
| TypeORM version     |  0.3.17

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by jomalix** [comment]
Hello!
I have the Same problème with sqlite/angular

**Comment by akash07k** [comment]
I too have kinda same issue with sqlite and Vite

**Comment by faribauc** [comment]
I'm also having a similar problem using pg/angular.

```bash
ERROR TypeError: Cannot read properties of undefined (reading 'type')
    at EntityManagerFactory.create (EntityManagerFactory.js:12:39)
    at DataSource.createEntityManager (DataSource.js:403:43)
    at new DataSource (DataSource.js:54:29)
    at new _AppComponent (app.component.ts:17:27)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:32:3)
    at getNodeInjectable (core.mjs:6965:44)
    at createRootComponent (core.mjs:16724:35)
    at ComponentFactory.create (core.mjs:16588:25)
    at _ApplicationRef.bootstrap (core.mjs:32366:42)
    at core.mjs:34868:32
```

```typescript
const AppDataSource = new DataSource({
      type: 'postgres',
      host: 'host.docker.internal',
      port: 15432,
      username: 'postgres',
      password: '<password>',
      database: 'exmar',
      synchronize: true,
      logging: true,
      entities: [],
      subscribers: [],
      migrations: [],
    });
```
    
I created a repo with a base Angular setup and TypeORM. It was created with the following commands and ONLY those. Nothing else was done:

```bash
ng new angular-typeorm
cd angular-typeorm
npm install typeorm --save
npm install reflect-metadata --save
npm install @types/node --save-dev
npm install pg --save
```

Typescript: 5.3.2
Node.js: 18.17.1
Angular: 17.2.0
TypeORM: 0.3.20
