### ISSUE TITLE
Wrong column used when have multiple JoinColumn

### ISSUE THREAD

**Issue by xyyaya** [typeorm/typeorm#10332]
### Issue description

Join tables used wrong column

### Expected Behavior

return without error

### Actual Behavior
```
QueryFailedError: Unknown column 'B__B_d.otherDId' in 'on clause'
    at Query.onResult (D:\projects\typeorm-test\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:158:37)
    at Query.execute (D:\projects\typeorm-test\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\projects\typeorm-test\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  query: 'SELECT `B`.`bId` AS `B_bId`, `B`.`aId` AS `B_aId`, `B`.`dId` AS `B_dId`, `B__B_a`.`aId` AS `B__B_a_aId`, `B__B_a`.`otherDId` AS `B__B_a_otherDId`, `B__B_d`.`id` AS `B__B_d_id` FROM `b` `B` LEFT JOIN `a` `B__B_a` ON `B__B_a`.`aId`=`B`.`aId` AND `B__B_a`.`otherDId`=`B`.`dId`  LEFT JOIN `d` `B__B_d` ON B__B_d.otherDId=`B`.`dId`',
  parameters: [],
  driverError: Error: Unknown column 'B__B_d.otherDId' in 'on clause'
      at Packet.asError (D:\projects\typeorm-test\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (D:\projects\typeorm-test\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (D:\projects\typeorm-test\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\projects\typeorm-test\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'B__B_d.otherDId' in 'on clause'",
    sql: 'SELECT `B`.`bId` AS `B_bId`, `B`.`aId` AS `B_aId`, `B`.`dId` AS `B_dId`, `B__B_a`.`aId` AS `B__B_a_aId`, `B__B_a`.`otherDId` AS `B__B_a_otherDId`, `B__B_d`.`id` AS `B__B_d_id` FROM `b` `B` LEFT JOIN `a` `B__B_a` ON `B__B_a`.`aId`=`B`.`aId` AND `B__B_a`.`otherDId`=`B`.`dId`  LEFT JOIN `d` `B__B_d` ON B__B_d.otherDId=`B`.`dId`'
  },
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'B__B_d.otherDId' in 'on clause'",
  sql: 'SELECT `B`.`bId` AS `B_bId`, `B`.`aId` AS `B_aId`, `B`.`dId` AS `B_dId`, `B__B_a`.`aId` AS `B__B_a_aId`, `B__B_a`.`otherDId` AS `B__B_a_otherDId`, `B__B_d`.`id` AS `B__B_d_id` FROM `b` `B` LEFT JOIN `a` `B__B_a` ON `B__B_a`.`aId`=`B`.`aId` AND `B__B_a`.`otherDId`=`B`.`dId`  LEFT JOIN `d` `B__B_d` ON B__B_d.otherDId=`B`.`dId`'
}
```
### Steps to reproduce

```
import {DataSource} from 'typeorm';
import {Column, Entity, JoinColumn, ManyToOne, PrimaryColumn} from 'typeorm';

@Entity()
export class D {
  @PrimaryColumn()
  id!: number;
}

@Entity()
export class A {
  @PrimaryColumn()
  aId!: number;

  @PrimaryColumn()
  otherDId!: number
}

@Entity()
export class B {
  @PrimaryColumn()
  bId!: number;

  @Column()
  aId!: number;

  @Column()
  dId!: number;

  @ManyToOne(() => D)
  @JoinColumn({name: 'dId', referencedColumnName: 'id'})
  d?: D;

  @ManyToOne(() => A)
  @JoinColumn([{name: 'aId', referencedColumnName: 'aId'}, {name: 'dId', referencedColumnName: 'otherDId'}])
  a?: A;
}

const dataSource = new DataSource({
  name: 'test',
  synchronize: true,
  logging: true,
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "root",
  password: "root",
  database: "test",
  entities: [A, B, D],
});

dataSource.initialize().then(async () => {
  const result = await dataSource.manager.find(B, {
    relations: {
      a: true,
      d: true,
    }
  });

  console.log(result);
})


```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by ahmedrawdan** [comment]
you are referencing the `dId` column twice once at the relationship with the `D` entity and once with the `A` entity
this is not correct the correct code should be

import {
  Column,
  DataSource,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from "typeorm";

@Entity()
export class D {
  @PrimaryColumn()
  id!: number;
}

@Entity()
export class A {
  @PrimaryColumn()
  aId!: number;

  @PrimaryColumn()
  otherDId!: number;
}

@Entity()
export class B {
  @PrimaryColumn()
  bId!: number;

  @Column()
  aId!: number;

  @Column()
  otherDId!: number; // added aditional column

  @Column()
  dId!: number;

  @ManyToOne(() => D)
  @JoinColumn({ name: "dId", referencedColumnName: "id" })
  d?: D; 

  @ManyToOne(() => A)
  @JoinColumn([
    { name: "aId", referencedColumnName: "aId" },
    { name: "otherDId", referencedColumnName: "otherDId" }, //changed the name of the column from `dId` to `otherDId` because `dId` is refranced twice
  ])
  a?: A;
}

const dataSource = new DataSource({
  name: "test",
  synchronize: true,
  logging: false,
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "root",
  password: "root",
  database: "typeorm-test",
  entities: [A, B, D],
});

dataSource.initialize().then(async () => {
  const result = await dataSource.manager.find(B, {
    relations: {
      a: true,
      d: true,
    },
  });

  console.log(result);
});

**Comment by DevAhmedRadwan** [comment]
you are referencing the `dId` column twice once at the relationship with the `D` entity and once with the `A` entity
this is not correct the correct code should be
```

import {
  Column,
  DataSource,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from "typeorm";

@Entity()
export class D {
  @PrimaryColumn()
  id!: number;
}

@Entity()
export class A {
  @PrimaryColumn()
  aId!: number;

  @PrimaryColumn()
  otherDId!: number;
}

@Entity()
export class B {
  @PrimaryColumn()
  bId!: number;

  @Column()
  aId!: number;

  @Column()
  otherDId!: number; // added aditional column

  @Column()
  dId!: number;

  @ManyToOne(() => D)
  @JoinColumn({ name: "dId", referencedColumnName: "id" })
  d?: D; 

  @ManyToOne(() => A)
  @JoinColumn([
    { name: "aId", referencedColumnName: "aId" },
    { name: "otherDId", referencedColumnName: "otherDId" }, //changed the name of the column from `dId` to `otherDId` because `dId` is refranced twice
  ])
  a?: A;
}

const dataSource = new DataSource({
  name: "test",
  synchronize: true,
  logging: false,
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "root",
  password: "root",
  database: "typeorm-test",
  entities: [A, B, D],
});

dataSource.initialize().then(async () => {
  const result = await dataSource.manager.find(B, {
    relations: {
      a: true,
      d: true,
    },
  });

  console.log(result);
});


```

**Comment by romadomma** [comment]
I'm having the same problem.

@DevAhmedRadwan
Why do I have to duplicate columns? Having different referenced columns for a join column in other tables does not contradict anything. It's an surprising(in a bad way) limitation of typeorm. Typeorm just appends the last encountered reference column to the relationMetadata.

**Comment by xyyaya** [comment]
I don't think add duplicate column is the correct way to solve the problem. In the database, they refer to the same thing, so it is only natural to use the same column. I'm curious about what design caused this issue.

**Comment by romadomma** [comment]
@xyyaya seems to be a deep problem when forming relationMetadata. 

`joinColumns` consists of `ColumnMetadata` instances, each of which has a `referencedColumn` field (and this is also a `ColumnMetadata` instance). In this structure, there is room for only one `referencedColumn` (the last referenced сolumn encountered)

For example:

```typescript
class Foo {
  // has a `ColumnMetadata`
  // there is a `referencedColumn` field with a instance of `ColumnMetadata` of field `A.otherDId` (last of the two)
  @Column()
  dId!: number;

  // has `RelationMetadata`
  // there is a `joinColumns` array with a instance of `ColumnMetadata` of field `Foo.dId`
  @ManyToOne(() => D)
  @JoinColumn({ name: "dId", referencedColumnName: "id" })
  d?: D; 

  // has `RelationMetadata`
  // there is a `joinColumns` array with a instance of `ColumnMetadata` of field `Foo.dId`
  @ManyToOne(() => A)
  @JoinColumn({ name: "dId", referencedColumnName: "otherDId" })
  a?: A;
}
```

**Comment by xyyaya** [comment]
I see, it seems that there is no simple fix, and any modification would involve a significant amount of code changes.

**Comment by Tokiham** [comment]
How to use the constructor to execute the relation query
