### ISSUE TITLE
SpannerQueryRunner.query results in syntax error at or near "`"

### ISSUE THREAD

**Issue by jillxuu** [typeorm/typeorm#10368]
### Issue description

The query contains "`" like query: 'DELETE FROM \`users\` WHERE true' but it was not understood by the sql query syntax.

### Expected Behavior

should be: 
query: 'DELETE FROM users WHERE true'

instead it was :
query: 'DELETE FROM \`users\` WHERE true'

### Actual Behavior

```

QueryFailedError: 3 INVALID_ARGUMENT: [ERROR] syntax error at or near "`"
    at SpannerQueryRunner.query (xxx/node_modules/.pnpm/typeorm@0.3.17_@google-cloud+spanner@5.18.0_ts-node@10.7.0/src/driver/spanner/SpannerQueryRunner.ts:243:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SpannerQueryRunner.clearTable (xxx/node_modules/.pnpm/typeorm@0.3.17_@google-cloud+spanner@5.18.0_ts-node@10.7.0/src/driver/spanner/SpannerQueryRunner.ts:1402:9)
    at async EntityManager.clear (xxx/node_modules/.pnpm/typeorm@0.3.17_@google-cloud+spanner@5.18.0_ts-node@10.7.0/src/entity-manager/EntityManager.ts:1291:20) {
  query: 'DELETE FROM `users` WHERE true',
  parameters: undefined,
  driverError: Error: 3 INVALID_ARGUMENT: [ERROR] syntax error at or near "`"
      at Object.callErrorFromStatus (xxx/node_modules/.pnpm/@grpc+grpc-js@1.6.12/node_modules/@grpc/grpc-js/src/call.ts:81:17)
      at Object.onReceiveStatus (xxx/node_modules/.pnpm/@grpc+grpc-js@1.6.12/node_modules/@grpc/grpc-js/src/client.ts:596:32)
      at xxx/node_modules/.pnpm/@grpc+grpc-js@1.6.12/node_modules/@grpc/grpc-js/src/call-stream.ts:206:27
......
      at StreamProxy.setStream (xxx/node_modules/.pnpm/google-gax@2.30.5/node_modules/google-gax/src/streamingCalls/streaming.ts:181:29)
      at StreamingApiCaller.call (xxx/node_modules/.pnpm/google-gax@2.30.5/node_modules/google-gax/src/streamingCalls/streamingApiCaller.ts:88:12) {
    code: 3,
    details: '[ERROR] syntax error at or near "`"',
    metadata: Metadata { internalRepr: [Map], options: {} }
  },
  code: 3,
  details: '[ERROR] syntax error at or near "`"',
  metadata: Metadata {
    internalRepr: Map(2) {
      'endpoint-load-metrics-bin' => [Array],
      'grpc-server-stats-bin' => [Array]
    },
    options: {}
  }
}
```

### Steps to reproduce

1. `typeorm init --name typeorm --database spanner`
2. `npm i`
3. `npm run start`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v20.3.1 |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [X] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by nickbetsworth** [comment]
Is there any workaround or resolution for this? Unable to even get a simple Select query working.

**Comment by alumni** [comment]
@nickbetsworth @jillxuu table name escaping is done in `SpannerQueryRunner.escapePath` - all queries produced by TypeORM **MUST** use quoted identifiers.

In ANSI SQL (and in most SQL dialects), quoted identifiers must be within double quotes (`"`).

In MySQL and in Google Cloud Spanner, the quotation character is a backtick ( `` ` `` ). So this should be correct:

```sql
DELETE FROM `users` WHERE ...
```

See more here: https://cloud.google.com/spanner/docs/reference/standard-sql/lexical#quoted_identifiers

**Comment by nickbetsworth** [comment]
> Table name escaping is done in `SpannerQueryRunner.escapePath` - all queries produced by TypeORM **MUST** use quoted identifiers.
> 
> In ANSI SQL (and in most SQL dialects, e.g. Postgres), quoted identifiers must be within double quotes (`"`).
> 
> In MySQL and in Google Cloud Spanner, the quotation character is a backtick ( `` ` `` ). So this should be correct:
> 
> DELETE FROM `users` WHERE ...
> See more here: https://cloud.google.com/spanner/docs/reference/standard-sql/lexical#quoted_identifiers
> 
> [@nickbetsworth](https://github.com/nickbetsworth) [@jillxuu](https://github.com/jillxuu) are you by any chance using Postgres within Spanner?

Hi @alumni ,

Many thanks for the quick response.

I've just noticed that our setup seems to be using https://cloud.google.com/spanner/docs/postgresql-interface which presumably would only allow the postgres syntax, hence the error I'm seeing.

I've noticed if I paste the generated query (with backticks) into Spanner Studio, it does not like it until replaced with Postgres syntax.

Is there any way to configure connectivity to spanner with postgres syntax?

Many thanks

**Comment by alumni** [comment]
Honestly, I don't work with Spanner at all, but I see they have a PGAdapter: https://cloud.google.com/spanner/docs/psql-connect

In that case, you could try to use the regular `postgres` driver, check if it works.

Otherwise, probably what you need would be a combination between the `spanner` and the `postgres` drivers. TypeORM checks the driver type in a lot of places and it assumes there's a single SQL dialect per driver (for Spanner, the GoogleSQL dialect is used, but you need the PostgreSQL dialect).

**Comment by nickbetsworth** [comment]
Thanks very much

I was looking into some of the implementation details in `SpannerQueryRunner`, and it looks like it's calling into the driver to escape column names etc. It seems `SpannerQueryRunner.escapePath` is just used for the table name.

**Comment by alumni** [comment]
As mentioned before, there might be a lot more things than just escaping.

For AWS, There are 2 drivers: `aurora-mysql` and `aurora-postgres`. Probably there's rather a need for a new driver, `spanner-postgres`, in addition to the existing `spanner` driver that uses GoogleSQL.
