### ISSUE TITLE
ionic cordova build --prod android not working

### ISSUE THREAD

**Issue by santu-git** [typeorm/typeorm#1044]
`ionic cordova build --prod android` show following error

```
Error: chunk vendor [entry]
[name].js
Module /Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/typeorm/browser/index.js has no static exports true
Error: Module /Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/typeorm/browser/index.js has no static exports true
    at HarmonyImportSpecifierDependencyConcatenatedTemplate.apply (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/optimize/ConcatenatedModule.js:488:10)
    at NormalModule.sourceDependency (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/NormalModule.js:321:12)
    at block.dependencies.forEach (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/NormalModule.js:387:51)
    at Array.forEach (native)
    at NormalModule.sourceBlock (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/NormalModule.js:387:22)
    at NormalModule.source (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/NormalModule.js:486:8)
    at modulesWithInfo.forEach.info (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/optimize/ConcatenatedModule.js:310:21)
    at Array.forEach (native)
    at ConcatenatedModule.source (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/optimize/ConcatenatedModule.js:308:19)
    at ModuleTemplate.render (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/ModuleTemplate.js:14:31)
    at new BuildError (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/@ionic/app-scripts/dist/webpack.js:119:28)
    at emitRecords.err (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules/webpack/lib/Compiler.js:365:9)
```

**Comment by daniel-lang** [comment]
What version of ionic and typeorm are you using?
You find that out by running `ionic info` and `./node_modules/typeorm/cli.js -v`

**Comment by AlexMesser** [comment]
btw `typeorm version` also provides you info about locally and globally installed versions of typeorm

**Comment by santu-git** [comment]
@daniel-lang 
cli packages: (/Users/santu/MyWorkspace/Ionic/sm3-client/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0 windows 5.0.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.10 
    Node              : v7.8.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.0 Build version 8A218a 

Misc:

    backend : legacy

**Typeorm version : 0.1.0**

**Comment by daniel-lang** [comment]
@santu-git I updated my ionic test project to reflect your version but I don't get this error. So is must be specific to your setup.
Which step of the build process outputs this error? Is is just the production build or does the error also exist in the "normal"/dev build?

**Comment by santu-git** [comment]
@daniel-lang only exist in production build.

**Comment by daniel-lang** [comment]
Sorry for the long delay. Did you find a solution to your problem?

**Comment by santu-git** [comment]
@daniel-lang I could not manage time to make fresh checkout and build.

**Comment by santu-git** [comment]
Came back after a long vacation. Last issue has been resolved after reinstallig node modules now I found following Proble


My Observation is if there is any relation between 2 entities then this problem happening. 
```
TypeError: Cannot read property 'kind' of undefined
    at nodeCanBeDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7805:35)
    at nodeIsDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7825:16)
    at Object.nodeOrChildIsDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7829:16)
    at isDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51668:23)
    at isInstanceDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51659:20)
    at Object.filter (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:1645:31)
    at getDecoratedClassElements (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51641:23)
    at generateClassElementDecorationExpressions (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51815:27)
    at addClassElementDecorationStatements (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51804:44)
    at visitClassDeclaration (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51131:13)
```


activity.entity.js

import { Result } from './result.entity';
import { Entity, Column, PrimaryColumn, ManyToOne, OneToMany, JoinColumn } from 'typeorm';

@Entity('activity')
export class Activity {
  
  /* Columns */
  @PrimaryColumn()
  id: string;

  @Column()
  name: string;

  @Column({nullable: true})
  note: string;
  ...............
  
  /* :has_many relations */
  @OneToMany(type=> Result, result=>result.activity,{
    cascadeInsert: true,
    cascadeUpdate: true,
  })
  results: Result[] = [];
}

result.entity.ts
import { Activity } from './activity.entity';
//import { Catalog } from './catalog.entity';
import { Entity, Column, PrimaryColumn, ManyToOne, JoinColumn } from 'typeorm';

@Entity('result')
export class Result {

  @PrimaryColumn()
  id: string;

  @Column()
  name: string;

  @Column({ nullable: true })
  value: string;

  
  
  /* Relations */
  /* :belongs_to relations */
  @ManyToOne(type=>Activity, activity=> activity.results)
  @JoinColumn({name: "activity_id"})
  activity: Activity;
}

**Comment by MoustafaElkady** [comment]
did you solved it?
