### ISSUE TITLE
Indexes are not working with mongodb

### ISSUE THREAD

**Issue by fahadsubzwari924** [typeorm/typeorm#10495]
### Issue description

Indexes are not working with mongodb

### Expected Behavior

I have nest app with mogodb database. I am trying to add indexes on few columns in my `Customer` and `Product` entities.

customer.entity.ts

    @Entity('customers')
    export class Customer extends BaseEntity {
     @PrimaryGeneratedColumn()
     id: number;

     @Index('customerNameIdx', { sparse: true })
     @Column({
         nullable: true,
        length: 100,
     })
    fullName: string;

    @Column()
    age: number;

    @Column()
    country: string;

    @Column({
        nullable: false,
    })
    city: string;

    @Column({
        nullable: false,
    })
    address: string;

    @Index('customerContactIdx', { sparse: true })
    @Column({
        nullable: false,
    })
    contactNumber: string;

    @OneToMany(() => Order, (order) => order.customer)
    orders: Order[];

    @CreateDateColumn()
    createdAt: Date;

     @UpdateDateColumn()
     updatedAt: Date;
    }
    
    product.entity.ts
    
    
     @Entity()
     export class Product extends BaseEntity {
       @PrimaryGeneratedColumn()
       id: number;

      @Index('productNameIdx', { sparse: false })
      @Column({
         unique: true,
         length: 200,
        nullable: false,
     })
     name: string;

     @Column()
     description: string;

     @CreateDateColumn()
     createdAt: Date;
    }

Now, when i start the server, so indexes should be created for mentioned fields and server should be connected with Mongodb database. 

### Actual Behavior

But, when i start the server so, server is throwing an error like this

`[Nest] 72088  - 11/17/2023, 9:28:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
MongoServerError: Error in specification { name: "IDX_48b9e74eeee6b785fa81fecf7b", unique: false, sparse: null, background: null, key: {} } :: caused by :: The field 'sparse has value sparse: null, which is not convertible to bool
    at Connection.onMessage (/Users/fahadsubzwari924/Documents/sideProjects/cwc/nest-server/node_modules/mongodb/src/cmap/connection.ts:413:18)
    at MessageStream.<anonymous> (/Users/fahadsubzwari924/Documents/sideProjects/cwc/nest-server/node_modules/mongodb/src/cmap/connection.ts:243:56)
    at MessageStream.emit (node:events:512:28)
    at processIncomingData (/Users/fahadsubzwari924/Documents/sideProjects/cwc/nest-server/node_modules/mongodb/src/cmap/message_stream.ts:193:12)
    at MessageStream._write (/Users/fahadsubzwari924/Documents/sideProjects/cwc/nest-server/node_modules/mongodb/src/cmap/message_stream.ts:74:5)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at MessageStream.Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:512:28)`

### Steps to reproduce

- Create an entity with typeorm decorators
- Add indexes for any field with or without options of index provided
- Have syncronization boolean true in mongo configuration
- Start the server. You will get the error.

### My Environment

| Mongodb          | 5.9.1  |
| ---                 | ---      |
| MacOS 12.3 (21E230)    |          |
| Node.js version     | 19.6.0  |
| Typescript version  | 4.7.4  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Neosoulink** [comment]
Is there any update on this one?

**Comment by Soapiane** [comment]
I encountered the same problem and this is what I did :

I first noticed that the problem appeared after I added the " project.entity.ts " file

There was this code snippet :

```typescript
  @ManyToMany(() => User, user => user.teams)
  @JoinTable()
  members: User[];
``` 

That I simply replaced with 
```typescript
  @ManyToMany(() => User, user => user.teams)
  members: User[];
``` 
And it worked well.

**Comment by vaibhavdwivedi-git** [comment]
Any updates??
