### ISSUE TITLE
Build Error in Vite 5.0.5

### ISSUE THREAD

**Issue by okamototomoyuki** [typeorm/typeorm#10541]
### Issue description

An error occurs during the build process when running yarn build.

### Expected Behavior

The build should successfully complete, and files should be generated in the build folder.

### Actual Behavior

The following error is encountered:
```
"pathToFileURL" is not exported by "__vite-browser-external", imported by "node_modules/typeorm/browser/util/ImportUtils.js".
file: D:/repository/monitor/node_modules/typeorm/browser/util/ImportUtils.js:3:9
1: import fs from "fs";
2: import path from "path";
3: import { pathToFileURL } from "url";
            ^
4: export async function importOrRequireFile(filePath) {
5:     const tryToImport = async () => {
[vite-plugin-sveltekit-compile] "pathToFileURL" is not exported by "__vite-browser-external", imported by "node_modules/typeorm/browser/util/ImportUtils.js".
file: D:/repository/monitor/node_modules/typeorm/browser/util/ImportUtils.js:3:9
1: import fs from "fs";
2: import path from "path";
3: import { pathToFileURL } from "url";
            ^
4: export async function importOrRequireFile(filePath) {
5:     const tryToImport = async () => {
✓ built in 17.52s
error during build:
RollupError: "pathToFileURL" is not exported by "__vite-browser-external", imported by "node_modules/typeorm/browser/util/ImportUtils.js".
    at error (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:12738:16)
    at Module.traceVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13175:29)
    at ModuleScope.findVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:11592:39)
    at FunctionScope.findVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5897:38)
    at FunctionBodyScope.findVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5897:38)
    at ReturnValueScope.findVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5897:38)
    at FunctionBodyScope.findVariable (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5897:38)
    at Identifier.bind (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7179:40)
    at CallExpression.bind (file:///D:/repository/monitor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:4625:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Steps to reproduce

Build with `yarn build`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows Server 2019 |
| Node.js version     | 18.8.0|
| Typescript version  | 5.3.2 |
| TypeORM version     | 0.3.17 |

### Additional Context

This error does not occur with vite 4.5.1.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [X] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by OSA413** [comment]
Hi, can you please provide a minimal reproducible example repository of with error?
