### ISSUE TITLE
ArrayContains and ArrayContainedBy cannot be used in sql.js database

### ISSUE THREAD

**Issue by Weredok** [typeorm/typeorm#10610]
### Issue description

Hi! I can't solve my case using just database. I need fetch all entities and filter them, but it eats too many RAM

### Expected Behavior

My datasource file is:
```ts
import { DataSource, Entity, PrimaryColumn, Column } from "typeorm";
import { Messages } from "./models/Messages.js";
import { Voice } from "./models/Voice.js";
import { Invite } from "./models/Invite.js";

const AppDataSource = new DataSource({
    type: "sqljs",
    synchronize: true,
    location: "./datasource.sql",
    autoSave: true,
    entities: [Messages, Voice, Invite]
});

await AppDataSource.initialize()

export { AppDataSource }
```

and model, what i used for it 
```ts
@Entity()
export class Invite {
  @PrimaryColumn("text")
  code: string;

  @Column("text")
  user: string;

  @Column("simple-array")
  leaved: InvitedUser[];

  @Column("simple-array")
  fake: InvitedUser[];

  @Column("simple-array")
  invites: InvitedUser[];

  @Column("numeric")
  unknown: number;
};
```

just number, string and array is not supported for sqljs. I don't know fucking why, i need use that same types.

### Actual Behavior

So, my code is:
```ts
const invite = await AppDataSource.getRepository(Invite).findOneBy({
    invites: ArrayContains(["an string]),
  });
```

and error is
```ts
node:events:492
      throw er; // Unhandled 'error' event
      ^

QueryFailedError: unrecognized token: "@"
    at SqljsQueryRunner.query (/workspaces/monorepo/node_modules/typeorm/driver/sqljs/SqljsQueryRunner.js:109:19)
    at SelectQueryBuilder.loadRawResults (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:43)
    at SelectQueryBuilder.executeEntitiesAndRawResults (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:37)
    at SelectQueryBuilder.getRawAndEntities (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:40)
    at SelectQueryBuilder.getOne (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:36)
    at SqljsEntityManager.findOneBy (/workspaces/monorepo/node_modules/typeorm/entity-manager/EntityManager.js:610:14)
    at Repository.findOneBy (/workspaces/monorepo/node_modules/typeorm/repository/Repository.js:246:29)
    at Client.<anonymous> (/workspaces/monorepo/apps/analytics/index.ts:240:60)
    at Client.emit (node:events:514:28)
    at Client.emit (node:domain:489:12)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:397:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  query: 'SELECT "Invite"."code" AS "Invite_code", "Invite"."user" AS "Invite_user", "Invite"."leaved" AS "Invite_leaved", "Invite"."fake" AS "Invite_fake", "Invite"."invites" AS "Invite_invites", "Invite"."unknown" AS "Invite_unknown" FROM "invite" "Invite" WHERE ("Invite"."invites" @> ?) LIMIT 1',
  parameters: [ [ '818537726738432020' ] ],
  driverError: Error: unrecognized token: "@"
      at f.f.handleError (/workspaces/monorepo/node_modules/sql.js/dist/sql-wasm.js:91:290)
      at f.f.prepare (/workspaces/monorepo/node_modules/sql.js/dist/sql-wasm.js:90:46)
      at SqljsQueryRunner.query (/workspaces/monorepo/node_modules/typeorm/driver/sqljs/SqljsQueryRunner.js:73:44)
      at SelectQueryBuilder.loadRawResults (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:43)
      at SelectQueryBuilder.executeEntitiesAndRawResults (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:37)
      at SelectQueryBuilder.getRawAndEntities (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:40)
      at SelectQueryBuilder.getOne (/workspaces/monorepo/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:36)
      at SqljsEntityManager.findOneBy (/workspaces/monorepo/node_modules/typeorm/entity-manager/EntityManager.js:610:14)
      at Repository.findOneBy (/workspaces/monorepo/node_modules/typeorm/repository/Repository.js:246:29)
      at Client.<anonymous> (/workspaces/monorepo/apps/analytics/index.ts:240:60)
}

Node.js v20.6.1
```

### Steps to reproduce

1. Create an datasource with sql.js driver.
2. Create an entity, what contains array column
3. Just try use ArrayContains or ArrayContainedBy

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows 8.1      |
| Node.js version     | 20.6.1  |
| Typescript version  | Latest  |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [X] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Weredok** [comment]
rn i need use this solution, btw it's poor
![image](https://github.com/typeorm/typeorm/assets/93865249/7ac99858-59a3-4dcf-8e27-46bb3b59d7e7)

**Comment by mohit-761** [comment]
please create manual query in my case skills was an array of string like skills: string[] and following query worked for me
skills: Raw((alias) =>  `JSON_CONTAINS(${alias}, '${JSON.stringify(skills)}')`)
