### ISSUE TITLE
PRAGMA must run under query method in Capacitor sqlite

### ISSUE THREAD

**Issue by rkreutzer** [typeorm/typeorm#10687]
### Issue description

Pull request 10273 moved PRAGMA requests to the run method in v 0.3.20, and they now fail

### Expected Behavior

PRAGMA requests should use the query method in Capacitor sqlite, so they execute correctly. [https://github.com/typeorm/typeorm/pull/10273](https://github.com/typeorm/typeorm/pull/10273), which was merged in version 0.3.20, moved it to the run method.

The owner of Capacitor sqlite repo has verified this in [https://github.com/capacitor-community/sqlite/issues/512](https://github.com/capacitor-community/sqlite/issues/512). Also, sqlite, sqlite-abstract and better-sqlite3 all execute PRAGMA requests under the query method.

### Actual Behavior

Executing PRAGMA table_info(...) in v 0.3.20 fails with a result 100 error. See [https://github.com/typeorm/typeorm/pull/10273#issuecomment-1880975903](https://github.com/typeorm/typeorm/pull/10273#issuecomment-1880975903) for a screenshot.

### Steps to reproduce

Execute "PRAGMA table_info('user')" 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Android & iOS      |
| Node.js version     | 18.7.1  |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by jepiqueau** [comment]
i am the owner of @capacitor-community/sqlite, someone has modified the capacitor driver without understanding it. PRAGMA must be removed from 
```ts
            else if (["INSERT", "UPDATE", "DELETE", "PRAGMA"].indexOf(command) !== -1) {
                raw = await databaseConnection.run(query, parameters, false);
            }
```
the right code is 
```ts
            else if (["INSERT", "UPDATE", "DELETE"].indexOf(command) !== -1) {
                raw = await databaseConnection.run(query, parameters, false);
            }
```
i someone from the typeOrm team can fix that quickly i will appreciate it

**Comment by BARNZ** [comment]
Have created a simple MR #10774 to fix this issue by undoing just the breaking changes made in the original MR

**Comment by jepiqueau** [comment]
@BARNZ i am the owner of the @capacitor-community/sqlite the method to use for PRAMA is neither run or query it must be execute method to use.  This has to be changed in CapacitorQueryRunner and as well in CapacitorDriver files

**Comment by jepiqueau** [comment]
@BARNZ this will be added to the doc `API.md` of @capacitor-community/sqlite
```
## SQLite Commands Within the Plugin

 - SQLite Data Definition Language commands (such as CREATE, ALTER, DROP) should be executed using the `execute` plugin method.

 - SQLite Transaction Control commands (including BEGIN TRANSACTION, COMMIT, ROLLBACK) should also be executed using the `execute` plugin method.

 - SQLite Data Manipulation Language commands (like INSERT, UPDATE, DELETE, REPLACE) should use the `run` plugin method if they involve bind values. They can utilize either the `execute` or `run` plugin methods if no bind values are involved.

 - SQLite Data Query Language commands (SELECT) should be executed using the `query` plugin method.

 - SQLite Special commands (PRAGMA) should be executed using the `execute` plugin method.
 ```

**Comment by SaintPepsi** [comment]
When I Apply the patch to use `.execute` I get the following error:

`Error: Execute: unknown error: Queries cannot be performed using execSQL(), use query() instead.`

My `CapacitoryQueryRunner.js:`

```
if ([
                "BEGIN",
                "ROLLBACK",
                "COMMIT",
                "CREATE",
                "ALTER",
                "DROP",
              	"PRAGMA"
            ].indexOf(command) !== -1) {
                console.log('query', query);
                raw = await databaseConnection.execute(query, false);
            }
            ```
            
            Any ideas on how to fix this? it's driving me crazy, I don't know enough about SQL to fully dive into the root problem.

**Comment by jepiqueau** [comment]
@SaintPepsi  the script i run is 

```js
const fs = require('fs');

/* Moddify CapacitorQueryRunner.js */
let filePath = './node_modules/typeorm/driver/capacitor/CapacitorQueryRunner.js';
const correctBugInCapacitorQueryRunner = (file) => {
  if (fs.existsSync(file)) {
    fs.readFile(file, 'utf8', function (err, data) {
        if (err) {
            return console.error(err);
        }

        const index = `"DROP",`
        if (index === -1) {
            console.warn('Line not found. Package probably fixed.');
            return;
        }

        var result = data.replace(
          `    "DROP",`,
          `    "DROP",
               "PRAGMA"`

        );
        result = result.replace(
            'else if (["INSERT", "UPDATE", "DELETE", "PRAGMA"].indexOf(command) !== -1) {',
            'else if (["INSERT", "UPDATE", "DELETE"].indexOf(command) !== -1) {'
        );

        fs.writeFile(file, result, 'utf8', function (err) {
            if (err) return console.error(err);
        });
    });
  } else {
      utils.warn(`Couldn't find file ${file}`);
  }

}
/* Moddify CapacitorDriver.js */
const correctBugInCapacitorDriver = (file) => {
  if (fs.existsSync(file)) {
      fs.readFile(file, 'utf8', function (err, data) {
          if (err) {
              return console.error(err);
          }

          const index = data.indexOf('await connection.run(`PRAGMA foreign_keys = ON`);');
          if (index === -1) {
              console.warn('Line not found. Package probably fixed.');
              return;
          }

          var result = data.replace(
              'await connection.run(`PRAGMA foreign_keys = ON`);',
              'await connection.execute(`PRAGMA foreign_keys = ON`, false);'
          );
          result = result.replace(
              'await connection.run(`PRAGMA journal_mode = ${this.options.journalMode}`);',
              'await connection.execute(`PRAGMA journal_mode = ${this.options.journalMode}`, false);'
          );

          fs.writeFile(file, result, 'utf8', function (err) {
              if (err) return console.error(err);
          });
      });
  } else {
      utils.warn(`Couldn't find file ${file}`);
  }
}
correctBugInCapacitorQueryRunner('./node_modules/typeorm/driver/capacitor/CapacitorQueryRunner.js');
correctBugInCapacitorQueryRunner('./node_modules/typeorm/browser/driver/capacitor/CapacitorQueryRunner.js');
correctBugInCapacitorDriver('./node_modules/typeorm/driver/capacitor/CapacitorDriver.js');
correctBugInCapacitorDriver('./node_modules/typeorm/browser/driver/capacitor/CapacitorDriver.js');


/*
const modTypeOrmCapacitor = (filePath, lineToModify, replacementText) => {
  fs.readFile(filePath, 'utf8', (err, data) => {
    if (err) {
      console.error('Error reading file:', err);
      return;
    }
  
    // Split data by line
    const lines = data.split('\n');
  
    // Modify the specific line
    if (lines.length >= lineToModify) {
      lines[lineToModify - 1] = replacementText; // Line numbers are 1-based
    } else {
      console.error('Line number to modify is out of range.');
      return;
    }
  
    // Join lines back together
    const modifiedData = lines.join('\n');
  
    // Write the modified data back to the file
    fs.writeFile(filePath, modifiedData, 'utf8', (err) => {
      if (err) {
        console.error('Error writing file:', err);
        return;
      }
     
      console.log('File modified successfully.');
    });
  });
}

let filePath = './node_modules/typeorm/driver/capacitor/CapacitorQueryRunner.js';
let lineToModify = 61;
let replacementText = '    else if (["INSERT", "UPDATE", "DELETE"].indexOf(command) !== -1) {';
*/
```
here is an example of a vite.config.js with react 
```js
import legacy from '@vitejs/plugin-legacy'
import react from '@vitejs/plugin-react'
import swc from 'unplugin-swc'; // Support using decorators without explicitly set ``types`` in ``TypeORM``
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    legacy(),
    swc.vite({
      exclude: [], //Default would exclude all file from ``node_modules``
      jsc: {
        minify: {
          compress: true,
          mangle: true,
          //Suggested by ``capacitor-sqlite``
          keep_classnames: true,
          keep_fnames: true,
        },
      },
    }),

  ],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.ts',
  }
})
```

**Comment by SaintPepsi** [comment]
Thanks for posting this @jepiqueau unfortunately still getting the same error with this:

```
initialiseDatabase.ts:47 QueryFailedError: Execute: unknown error: Queries cannot be performed using execSQL(), use query() instead.
    at CapacitorQueryRunner.query (CapacitorQueryRunner.js:81:19)
    at async Promise.all (introduction/index 0)
    at async AbstractSqliteQueryRunner.js:911:42
    at async Promise.all (introduction/index 0)
    at async CapacitorQueryRunner.getCachedTable (BaseQueryRunner.js:176:15)
    at async CapacitorQueryRunner.createForeignKeys (AbstractSqliteQueryRunner.js:685:15)
    at async MasterSeed0000000000001.up (MasterSeed.ts:117:13)
    at async MigrationExecutor.executePendingMigrations (MigrationExecutor.js:220:46)
    at async DataSource.runMigrations (DataSource.js:263:16)
    at async Zr (initialiseDatabase.ts:33:30)
```

I'm trying to have a look at the source files but I'm just getting into a dead end where the file i'm trying to look at is just this:
![image](https://github.com/typeorm/typeorm/assets/16056759/1df46d12-0d2e-4eff-be8c-363bbab26a5c)

I don't understand where I need to be looking 🤔

**Comment by SaintPepsi** [comment]
Okay, I just noticed that if I don't use `queryRunner.createForeignKeys` it works!
Instead I have to add `foreignKeys` to the `new Table` options

```
await queryRunner.createTable(
    new Table({
        name: 'Goal'
        columns: ....
        foreignKeys: [ ... foreign key data ] // <- this works!! 
    })
)
```

**Comment by SaintPepsi** [comment]
I think the culprite is `src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts` at 
[`1367` -> `loadPragmaRecords`](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1367-L1369)

Because it goes:
1. [`AbstractSqliteQueryRunner` -> `createForeignKeys`](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1030-L1044)
2. [`await this.getCachedTable(tableOrName)`](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1036) because i'm passing the table name as a string
3. [`BaseQueryRunner.ts` -> `await this.loadTables([tableName])`](https://github.com/typeorm/typeorm/blob/master/src/query-runner/BaseQueryRunner.ts#L273)
4. `AbstractSqliteQueryRunner` -> 
```
await Promise.all([
    this.loadPragmaRecords(tablePath, `table_xinfo`),
    this.loadPragmaRecords(tablePath, `index_list`),
    this.loadPragmaRecords(tablePath, `foreign_key_list`),
])
``` [link](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1367-L1369)

And because they are all being executed in parallel they fail if i'm correct because in the capacitor driver it's using execute which can't be run in parallel? 🕵️‍♂️

**Comment by SaintPepsi** [comment]
Looks like you can only use `queryrunner.query` most other methods fail, I had `queryRunner.dropTable('Tablename');`which caused the same error:

```
query failed:  PRAGMA table_xinfo("CalendarEntry")
```
```
error:  Error: Execute: unknown error: Queries cannot be performed using execSQL(), use query() instead.
```

**Comment by jepiqueau** [comment]
@SaintPepsi i thing for vue the vite.config.js should be something like this even if i have not tested it 
```js
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import legacy from '@vitejs/plugin-legacy';
import swc from 'unplugin-swc';
import { resolve } from 'path';

export default defineConfig({
  plugins: [
    vue(),
    legacy(),
    swc.vite({
      exclude: [], // Default would exclude all files from `node_modules`
      jsc: {
        minify: {
          compress: true,
          mangle: true,
          // Suggested by `capacitor-sqlite`
          keep_classnames: true,
          keep_fnames: true,
        },
      },
    }),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
});
```
Can you share your example on github so i can have a look

**Comment by jepiqueau** [comment]
@SaintPepsi when you said `Also, sqlite, sqlite-abstract and better-sqlite3 all execute PRAGMA requests under the query method.` can you show me where i can found example of this. if it is true i may reconsider it and allow PRAGMA on the query  method of the capacitor plugin

**Comment by SaintPepsi** [comment]
@jepiqueau I'm not quite sure what you mean? are you able to elaborate?

**Comment by lthamm** [comment]
@jepiqueau I recently upgraded typeorm from 0.3.6 to 0.3.20 (so I can run a build with vite, which previously was not possible) and since then typeorm doesnt fully work anymore. I applied the script plus the vite config suggested here, but it still does not work.

The error I get is:
`dbColumns.map is not a function`. This comes from calling ` await connection.initialize();` in `main.ts`. The interesting part (at least for me) is that this only happens after running ` await connection.runMigrations();` once. So the first app start always works.

**Comment by lthamm** [comment]
Yes. I needed to turn of synchronize: True and write migrations. That seems to work. Am 08.05.2025 um 12:26 schrieb Alex Azartsev ***@***.***>:﻿
AlexAzartsev left a comment (typeorm/typeorm#10687)
@lthamm I have same issue now, have you figure out how to solve it ? :)

**Comment by AlexAzartsev** [comment]
@lthamm , thx for answer, didn't help for me, ended up with creating a pr to fix these bugs. #11467 , maybe it will be merged, if not at least will help those who will face this issue after me :)
