### ISSUE TITLE
error generating migrations

### ISSUE THREAD

**Issue by dberardo-com** [typeorm/typeorm#10749]
### Issue description

Error during migration generation: TypeError: Cannot read properties of undefined (reading 'constructor')     at C:\Users\danie\code\tecnojest\vivo-management-api\node_modules\typeorm\decorator\columns\PrimaryGeneratedColumn.js:45:28

### Expected Behavior

following documentation for a very simple entity: https://orkhan.gitbook.io/typeorm/docs/migrations#datasource-option

### Actual Behavior

get this error: Error during migration generation: TypeError: Cannot read properties of undefined (reading 'constructor')    ....\node_modules\typeorm\decorator\columns\PrimaryGeneratedColumn.js:45:28

### Steps to reproduce

follow the doc using node 16 or 18 or 20

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | see above  |
| TypeORM version     | 0.3.20 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by forrestwilkins** [comment]
I'm getting a similar error with `"typeorm": "^0.3.20"` and Node `v22.11.0`, but for creating the entity itself. For me, I get the error as soon as it get's to the line with `PrimaryGeneratedColumn`.

Here's my error output:
```
TypeError: Cannot read properties of undefined (reading 'constructor')
    at <anonymous> (/Users/myname/proj/code/rhizome/node_modules/typeorm/decorator/src/decorator/columns/PrimaryGeneratedColumn.ts:106:28)
    at __decorateElement (file:///Users/myname/proj/code/rhizome/src/users/user.entity.ts:1:2161)
    at <anonymous> (/Users/myname/proj/code/rhizome/src/users/user.entity.ts:6:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
```

**Comment by augusto-chaching** [comment]
I started seeing this error with an entity that has a constructor. It seems that the issue is that the code that creates the migrations calls the constructor with no parameters. If the body of the constructor uses the parameters (e.g. tries to get an attribute), the migration fails.

This is example of an entity that fails
```
type Data = {
  name: string
};

@Entity('my_entity')
export class my_entity {
  constructor(data: Data) {
    this.name = data.name; // this line throws the error as data is undefined.
  }
  @PrimaryColumn('uuid')
  id: string;

  @Column()
  name: string;
}
```

The following change works, as there's nothing that expects the parameter to be undefined.
```
  constructor(name:string) {
    this.name = name; // name is undefined, but since it's JS, all is good.
  }
```

Not sure if the generation code can avoid instantiating the class to introspect the decorators.

**Comment by boriswilliams** [comment]
This is still happening following the docs https://typeorm.io/docs/getting-started/
