### ISSUE TITLE
`TypeError: Cannot call a class constructor without |new|` on bun

### ISSUE THREAD

**Issue by glyh** [typeorm/typeorm#10761]
### Issue description

`TypeError: Cannot call a class constructor without |new|` on bun

### Expected Behavior

No error

### Actual Behavior

```
407 |                         ? entityTarget
408 |                         : undefined,
409 |                     subQuery: isSubquery ? entityTarget : undefined,
410 |                 });
411 |             }
412 |             const subQueryBuilder = entityTarget(this.subQuery());
                          ^
TypeError: Cannot call a class constructor without |new|
      at GenreAlias (:1:21)
      at createFromAlias (/home/lyh/Documents/CS/tools/jmetav/node_modules/typeorm/query-builder/QueryBuilder.js:412:37)
      at from (/home/lyh/Documents/CS/tools/jmetav/node_modules/typeorm/query-builder/SelectQueryBuilder.js:166:27)
      at /home/lyh/Documents/CS/tools/jmetav/src/info.ts:19:9
      at sanitizeGenres (/home/lyh/Documents/CS/tools/jmetav/src/info.ts:12:38)
      at /home/lyh/Documents/CS/tools/jmetav/src/info.ts:58:22
      at sanitizeMovie (/home/lyh/Documents/CS/tools/jmetav/src/info.ts:54:3)
      at /home/lyh/Documents/CS/tools/jmetav/src/index.ts:79:23
      at /home/lyh/Documents/CS/tools/jmetav/src/index.ts:75:64
```

### Steps to reproduce

Install typeorm orm on Bun and write some demoes with a query builder. 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | x.y.zzz  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by angelxmoreno** [comment]
it would be helpful to post your package.json and tsconfig.json since those configurations have a direct impact on anyone's ability to assist.
