### ISSUE TITLE
I can't run yarn typeorm migration:generate src/database/migrations/<NAME> -d src/database/datasource -p

### ISSUE THREAD

**Issue by eder-abbvie** [typeorm/typeorm#10773]
### Issue description

Path issue in W11

### Expected Behavior

After run the same command in mac it does not fails. I'm currently trying to use it in Windows 11. It is expecteded to generate a migration based in the new entity.

### Actual Behavior

`yarn typeorm migration:generate src/database/migrations/Tier -d src/database/datasource -p
yarn run v1.22.19
$ ts-node-dev -r dotenv/config -r tsconfig-paths/register ./node_modules/.bin/typeorm migration:generate src/database/migrations/Tier -d src/database/datasource -p
[INFO] 15:41:18 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.5)
C:\Users\vasqu\Documents\allergan\alle-backend-pricing\services\graphql\node_modules\.bin\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._compile (C:\Users\vasqu\Documents\allergan\alle-backend-pricing\node_modules\source-map-support\source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at require.extensions..jsx.require.extensions..js (C:\Users\vasqu\AppData\Local\Temp\ts-node-dev-hook-5600909666791201.js:114:20)
    at Object.nodeDevHook [as .js] (C:\Users\vasqu\Documents\allergan\alle-backend-pricing\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
[ERROR] 15:41:19 SyntaxError: missing ) after argument list`

### Steps to reproduce

1. Create Entity
2. Add Entity to Entities Array
3. Run yarn typeorm migration:generate src/database/migrations/<NAME> -d src/database/datasource -p

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 11   |
| Node.js version     | 18.19.1  |
| Typescript version  | ^4.9.5  |
| TypeORM version     | ^0.3.20 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by OSA413** [comment]
Hi, is this issue still relevant? I'm successfully generating new migrations on Windows 11.
