### ISSUE TITLE
SyntaxError: Unexpected token import at createScript (vm.js:53:10)

### ISSUE THREAD

**Issue by celestale** [typeorm/typeorm#1078]
```
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.PlatformTools.load (C:\Users\xxx\Documents\projects\xxx\node_modules\typeorm\platform\PlatformTools.js:33:20)
```

Unexpected syntaxError when attemping to run `postgres `in an Angular app.

root folder: ormconfig.json
```
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "postgres",
  "password": "admin",
  "database": "test",
  "synchronize": true,
  "logging": false,
  "entities": [
    "src/app/entity/**/*.ts"
  ]
}
```
src/app/entity/User.ts
```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

}


```

pg.component.ts
```
import { Component, OnInit } from '@angular/core';
import { createConnection } from 'typeorm';
import { User } from './../entity/User';

createConnection().then(async connection => {

      console.log('Inserting a new user into the database...');

      const user = new User();
      user.firstName = 'Timber';
      user.lastName = 'Saw';
      user.age = 25;
      await connection.manager.save(user);
      console.log('Saved a new user with id: ' + user.id);

      console.log('Loading users from the database...');
      const users = await connection.manager.find(User);
      console.log('Loaded users: ', users);

      console.log('Here you can setup and run express/koa/any other framework.');
      connection.close();
    }).catch((error) => { console.log(error);  });

```

**Comment by pleerock** [comment]
```
  "entities": [
    "src/app/entity/**/*.ts"
  ]
```

If you are executing your .js file then try to specify path to `.js` files instead of `.ts`

**Comment by celestale** [comment]
I compiled `tsc user.ts` file into `.js `and changed the path to `.js` and started my postgre server with this error

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): DataTypeNotSupportedError: Data type "undefined" in "User.firstName" is not supported by "postgres" database.
DataTypeNotSupportedError: Data type "undefined" in "User.firstName" is not supported by "postgres" database.
```

I have also checked that my postgre `database=test` and `user table(id, firstName, lastName, age)` exist.

user.js
```
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
exports.__esModule = true;
var typeorm_1 = require("typeorm");
var User = (function () {
    function User() {
    }
    __decorate([
        typeorm_1.PrimaryGeneratedColumn()
    ], User.prototype, "id");
    __decorate([
        typeorm_1.Column()
    ], User.prototype, "firstName");
    __decorate([
        typeorm_1.Column()
    ], User.prototype, "lastName");
    __decorate([
        typeorm_1.Column()
    ], User.prototype, "age");
    User = __decorate([
        typeorm_1.Entity()
    ], User);
    return User;
}());
exports.User = User;
```

postgre.component.ts
```
import { Component, OnInit } from '@angular/core';
import { createConnection } from 'typeorm';
import { User } from './../entity/User';

@Component({
  selector: 'app-postgre',
  templateUrl: './postgre.component.html'
})
export class PostgreComponent implements OnInit {
  constructor() { }

  ngOnInit() {
  }

  startConnection() {
    createConnection().then(async connection => {

      console.log('Inserting a new user into the database...');
      const user = new User();
      user.firstName = 'Timber';
      user.lastName = 'Saw';
      user.age = 25;
      await connection.manager.save(user);
      console.log('Saved a new user with id: ' + user.id);;

      console.log('Loading users from the database...');
      const users = await connection.manager.find(User);
      console.log('Loaded users: ', users);

      console.log('Here you can setup and run express/koa/any other framework.');
      connection.close();
    }).catch((error) => { console.log(error);});
  }

}
```

**Comment by pleerock** [comment]
Are you running app in the browser? Can you create a demo repo with your issue without angular or any other third party dependencies

**Comment by sierranevadan** [comment]
I was also seeing this error while making my way through the express example:

```
(node:7223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "undefined" in "User.firstName" is not supported by "postgres" database.
(node:7223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error starting app
{ QueryFailedError: type "undefined" does not exist
    at new QueryFailedError (/Users/r629541/Documents/user/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/Users/r629541/Documents/user/src/driver/postgres/PostgresQueryRunner.ts:216:26)
    at Query.handleError (/Users/r629541/Documents/user/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/r629541/Documents/user/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/Users/r629541/Documents/user/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  name: 'QueryFailedError',
  length: 92,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '257',
  routine: 'typenameType',
  query: 'ALTER TABLE "public"."user" ALTER COLUMN "firstName" TYPE undefined',
  parameters: [] }
```

I then specified types for the columns in `entity/User.ts` and it appears to work now. For example:

```javascript
@Column("varchar", { length: 200 })
    firstName: string
```

**Comment by pleerock** [comment]
Its a common user mistake when they forgot to enable needed compiler options (as readme says) or they do not include reflect-metadata or include it in a wrong place (it must be included before you start working with typeorm or entities)

**Comment by pleerock** [comment]
If someone is doubt about my point, please checkout demo repository and make a fork which breaks its behaviour and let me know.
