### ISSUE TITLE
TypeORM error with webpack

### ISSUE THREAD

**Issue by shisui0711** [typeorm/typeorm#10906]
### Issue description

Uncaught TypeError: Cannot read properties of undefined (reading 'type')

### Expected Behavior

Check driver, driver.options, driver.options.type != undefined

### Actual Behavior

Raise error type is undefined

### Steps to reproduce

Use webpack with ts-loader

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 20.12.2  |
| Typescript version  | 5.1.6  |
| TypeORM version     | 0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by shisui0711** [comment]
class Gt {
            create(e, t) {
                return "mongodb" === e.driver.options.type ? new ut(e) : "sqljs" === e.driver.options.type ? new zt(e,t) : new Ht(e,t)
            }
        }

**Comment by alumni** [comment]
The error description doesn't seem to be enough to replicate the issue. A reproducible example would be great.

However, I would not bother enabling code minification in webpack, at least for backend projects. Not only it takes more time to build the project, but it also makes it more difficult to debug (or to understand the logged errors).

**Comment by niklas-simon** [comment]
This happened to me as well when trying to use TypeORMAdapter in Auth.js. I managed to reproduce this issue in a new project like so:
- `npx webpack init`:  
  ```
? Which of the following JS solutions do you want to use? Typescript
? Do you want to use webpack-dev-server? Yes
? Do you want to simplify the creation of HTML files for your bundle? Yes
? Do you want to add PWA support? No
? Which of the following CSS solutions do you want to use? CSS only
? Will you be using PostCSS in your project? No
? Do you want to extract CSS for every file? Only for Production
? Do you like to install prettier to format generated configuration? No
? Pick a package manager: npm
  ```
- `npm i typeorm`
- index.ts:  
  ```
console.log("Hello World!");

import { DataSource } from "../node_modules/typeorm/index";

new DataSource({
    type: "mariadb",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "4817",
    database: "auth-js"
}).initialize().then(() => console.log("success")).catch(e => console.error(e));
  ```
- `npm run serve`
- -> Error shown under `http://localhost:8080`:
  ```
Compiled with problems:
ERROR
connection.driver.options is undefined
create@webpack://my-webpack-project/./node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js?:19:13
createEntityManager@webpack://my-webpack-project/./node_modules/typeorm/browser/data-source/DataSource.js?:423:109
DataSource@webpack://my-webpack-project/./node_modules/typeorm/browser/data-source/DataSource.js?:74:29
@webpack://my-webpack-project/./src/index.ts?:5:1
./src/index.ts@http://localhost:8080/main.js:257:1
__webpack_require__@http://localhost:8080/main.js:4117:32
@http://localhost:8080/main.js:5187:56
@http://localhost:8080/main.js:5189:12
WARNING in ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js 715:50-88
Module not found: Error: Can't resolve 'react-native-sqlite-storage' in 'A:\testing\webpack-ts-loader-typeorm\node_modules\typeorm\browser\driver\react-native'
  ```

**Comment by niklas-simon** [comment]
Or you can build it with `npm run build:dev`, navigate to `dist` and do `node main.js` to let node throw the original Error posted in this issue:
```
Hello World!
webpack://my-webpack-project/./node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js?:19
        if (connection.driver.options.type === "mongodb")
                                      ^

TypeError: Cannot read properties of undefined (reading 'type')
    at EntityManagerFactory.create (webpack://my-webpack-project/./node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js?:19:39)
    at DataSource.createEntityManager (webpack://my-webpack-project/./node_modules/typeorm/browser/data-source/DataSource.js?:423:109)
    at new DataSource (webpack://my-webpack-project/./node_modules/typeorm/browser/data-source/DataSource.js?:74:29)
    at eval (webpack://my-webpack-project/./src/index.ts?:5:1)
    at ./src/index.ts (A:\testing\webpack-ts-loader-typeorm\dist\main.js:191:1)
    at __webpack_require__ (A:\testing\webpack-ts-loader-typeorm\dist\main.js:3833:42)
    at A:\testing\webpack-ts-loader-typeorm\dist\main.js:3897:37
    at Object.<anonymous> (A:\testing\webpack-ts-loader-typeorm\dist\main.js:3899:12)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.4
```

**Comment by Damato** [comment]
Stumbled upon the exact same issue.

Found that the EntityManagerFactory has no options set when creating the DataSource.
It tries to determine is it needs to use a specific EntityManager in the create function.

For this it checks:

if (connection.driver.options.type === "mongodb")

However, options are not set, so they type property cannot be read.
I am yet to find a solution for this, and hope to revert with an answer.
