### ISSUE TITLE
RollupError: Unexpected character '@'

### ISSUE THREAD

**Issue by kerwinxu** [typeorm/typeorm#10918]
### Issue description

RollupError: Unexpected character '@'

### Expected Behavior

ok

### Actual Behavior

npm run build

> vue3-vite-electron-quick-start@0.0.0 build
> vite build

vite v4.4.8 building for production...
✓ 15 modules transformed.
✓ built in 2.75s
Unexpected character '@'
file: E:/onedrive/project/vue/mysql_demo/src/Entity/StocklotInformationEntiry.js:3:0
1: import {Entity, Column, PrimaryColumn} from 'typeorm'
2:
3: @Entity()
   ^
4: export class StocklotInformation{
error during build:
RollupError: Unexpected character '@'
    at error (file:///E:/onedrive/project/vue/mysql_demo/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///E:/onedrive/project/vue/mysql_demo/node_modules/rollup/dist/es/shared/node-entry.js:13674:16)
    at Module.tryParse (file:///E:/onedrive/project/vue/mysql_demo/node_modules/rollup/dist/es/shared/node-entry.js:14405:25)
    at Module.setSource (file:///E:/onedrive/project/vue/mysql_demo/node_modules/rollup/dist/es/shared/node-entry.js:14006:39)
    at ModuleLoader.addModuleSource (file:///E:/onedrive/project/vue/mysql_demo/node_modules/rollup/dist/es/shared/node-entry.js:24523:20)

### Steps to reproduce

code
```
import {Entity, Column, PrimaryColumn} from 'typeorm'

@Entity()
export class StocklotInformation{

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    win10     |
| Node.js version     | 9.8.1  |
| javascript version  | 20.6.1 |
| TypeORM version     | 0.3.20 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by OSA413** [comment]
Hi, can you please provide a repository where the problem is reproducible?

**Comment by jovanadjuric** [comment]
It appears that you're trying to use decorators in JavaScript, which doesn't support them yet. You can switch to TS or refer to [the docs](https://typeorm.io/usage-with-javascript) on how to use TypeORM with JS

**Comment by jovanadjuric** [comment]
Since I strongly suspect that this issue is caused by a user error, I'm going to close it.

Feel free to reopen it and provide the reproduction steps if this is not the case.
