### ISSUE TITLE
updateById broken since 0.1.1

### ISSUE THREAD

**Issue by dlindenkreuz** [typeorm/typeorm#1097]
Demo entity:

```ts
@Entity()
export class User {
  @PrimaryGeneratedColumn() public id: number

  @Column() public firstName: string
  @Column() public lastName: string
  @Column() public email: string
  // + some other columns, no relations though
}
```

This updater func doesn't work in typeorm 0.1.1 but worked in 0.1.0:

```ts
async function update(id: string, attr: Partial<User>) {
  await getRepository(User).updateById(id, attr)
  return await getRepository(User).findOneById(id)
}
```

Workaround using `Object.assign()` and `Repository.save`:
```ts
async function update(id: string, attr: Partial<User>) {
  const user = await getRepository(User).findOneById(id)
  if (user == null) {
    return null
  }
  Object.assign(user, attr)
  return await getRepository(User).save(user)
}
```

<details>
<summary><strong>No SQL (Postgres 9.6) is executed. This is the error I get:</strong></summary>

```
Error: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify inserted values.
    at UpdateQueryBuilder.getValueSet (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:179:15)
    at UpdateQueryBuilder.createUpdateExpression (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:137:30)
    at UpdateQueryBuilder.getQuery (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:37:24)
    at UpdateQueryBuilder.QueryBuilder.getQueryAndParameters (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:233:70)
    at UpdateQueryBuilder.<anonymous> (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:244:35)
    at step (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:32:23)
    at Object.next (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:13:53)
    at /Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:3:12)
    at UpdateQueryBuilder.QueryBuilder.execute (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/query-builder/QueryBuilder.js:239:16)
    at EntityManager.<anonymous> (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:407:30)
    at step (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:32:23)
    at Object.next (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:13:53)
    at /Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:3:12)
    at EntityManager.updateById (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/entity-manager/EntityManager.js:397:16)
    at Repository.<anonymous> (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/repository/Repository.js:152:52)
    at step (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/repository/Repository.js:32:23)
    at Object.next (/Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/repository/Repository.js:13:53)
    at /Users/daniel/Documents/Code/Excellence/External/[snip]/node_modules/typeorm/repository/Repository.js:7:71
```

</details>

**Comment by shabith** [comment]
Thanks @dlindenkreuz for the workaround. 
Any development on this issue?

**Comment by pleerock** [comment]
@shabith do you have this issue on 0.1.2 as well?

**Comment by shabith** [comment]
@pleerock Yes I can confirm that I have this issue in 0.1.2

**Comment by pleerock** [comment]
@shabith can you please provide your code example, so I can test it and check what is the issue?

**Comment by shabith** [comment]
@pleerock I was following [this](https://medium.com/@govorov/creating-graphql-api-with-koa-and-typeorm-8ec0ce2eaadc) tutorial when I encounter this issue. You can use this repo to recreate that. https://github.com/govorov/graphql-typeorm-koa-workshop with the version in the repo - ` "^0.1.0-alpha.50"` it works fine. however when you installed the latest version it starts to break.

**Comment by pleerock** [comment]
@shabith I checkout your repo however I dont see one step way to reproduce issue. Please provide a clean repository or short code example how can I reproduce issue

**Comment by pleerock** [comment]
Closing as no answer from reporter.
