### ISSUE TITLE
TypeOrm version >= 0.3.18  : Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by atjchen** [typeorm/typeorm#11009]
### Issue description

Upgrade TypeOrm to >= 0.3.18, i have the error log : {     "errorType": "TypeError",     "errorMessage": "Class extends value undefined is not a constructor or null",     "stack": [         "TypeError: Class extends value undefined is not a constructor or null",         "    at Object.<anonymous> (/opt/nodejs/node_modules/path-scurry/dist/commonjs/index.js:124:40)",         "    at Module._compile (node:internal/modules/cjs/loader:1364:14)",         "    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)",         "    at Module.load (node:internal/modules/cjs/loader:1203:32)",         "    at Module._load (node:internal/modules/cjs/loader:1019:12)",         "    at Module.require (node:internal/modules/cjs/loader:1231:19)",         "    at Hook.Module.require (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)",         "    at require (node:internal/modules/helpers:177:18)",         "    at Object.<anonymous> (/opt/nodejs/node_modules/glob/dist/commonjs/glob.js:6:23)",         "    at Module._compile (node:internal/modules/cjs/loader:1364:14)"     ] } 

### Expected Behavior

i can use typeOrm >= 0.3.18 without error

### Actual Behavior

When i upgrade typeorm to 0.3.18 or 0.3.19 or 0.3.20 , every execution of my lambda writes this error:
this error dispears when i downgrade to 0.3.17.

```typescript
	{
    "errorType": "TypeError",
    "errorMessage": "Class extends value undefined is not a constructor or null",
    "stack": [
        "TypeError: Class extends value undefined is not a constructor or null",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/path-scurry/dist/commonjs/index.js:124:40)",
        "    at Module._compile (node:internal/modules/cjs/loader:1364:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1203:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1019:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1231:19)",
        "    at Hook.Module.require (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)",
        "    at require (node:internal/modules/helpers:177:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/glob/dist/commonjs/glob.js:6:23)",
        "    at Module._compile (node:internal/modules/cjs/loader:1364:14)"
    ]
} 
``` 

I see the dependance of path scurry is introduced since 0.3.18. with glob dependancy upgrade.
 

### Steps to reproduce

Start a lambda aws with typeorm in a layer

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    AWS Lambda      |
| Node.js version     | 18.x |
| Typescript version  |^5.0.0  |
| TypeORM version     | >= 0.3.18  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

**Comment by chow5566** [comment]
Thanks for the feedback, I lowered the version to 0.3.17 without any issues.

**Comment by atjchen** [comment]
> Thanks for the feedback, I lowered the version to 0.3.17 without any issues.

Hello u have the same error? What is your environment?

**Comment by randomjack34** [comment]
Same when downgraded to `0.3.17`, previously `0.3.20`

I ran into this issue building an Electron app, whenever I import `typeorm`, it told me `Class extends value undefined is not a constructor or null` when starting `packed` app(by electron-builder`. But working good in dev env.


Windows11 x64 with Node.js v22.13.1

This is my deps when hitting this err
```json
  "dependencies": {
    "@electron-toolkit/preload": "^3.0.1",
    "@electron-toolkit/utils": "^3.0.0",
    "@kobalte/core": "^0.13.7",
    "@solid-primitives/i18n": "^2.2.0",
    "@solidjs/router": "^0.15.2",
    "@swc/core": "^1.10.9",
    "axios": "^1.7.9",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "lucide-solid": "^0.473.0",
    "mobx": "^6.13.5",
    "reflect-metadata": "^0.2.2",
    "sqlite3": "^5.1.7",
    "tailwind-merge": "^2.6.0",
    "tailwindcss-animate": "^1.0.7",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@electron-toolkit/eslint-config-prettier": "^2.0.0",
    "@electron-toolkit/eslint-config-ts": "^2.0.0",
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@types/node": "^20.14.8",
    "autoprefixer": "^10.4.20",
    "electron": "^31.0.2",
    "electron-builder": "^24.13.3",
    "electron-vite": "^2.3.0",
    "eslint": "^8.57.0",
    "eslint-plugin-solid": "^0.14.1",
    "postcss": "^8.4.49",
    "prettier": "^3.3.2",
    "solid-js": "^1.8.17",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.5.2",
    "vite": "^5.3.1",
    "vite-plugin-solid": "^2.10.2"
  },
```

Thanks to OP btw :)

**Comment by atjchen** [comment]
Hello, some news: my problem is more related to a dependency conflict between TypeORM and another library that pulls an older version of lru-cache. The bug is not in TypeORM itself.
