### ISSUE TITLE
ReferenceError: __dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by nikhilverma-xorsafe-0** [typeorm/typeorm#11034]
### Issue description

TypeORM not compatible with angular v18?

### Expected Behavior

After migrating my angular application to v18 from v17, my DataSource Started throwing the following error:

ReferenceError: __dirname is not defined in ES module scope
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/server.mjs:125:31117
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/chunk-H4UZCO6D.mjs:2:1082
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/server.mjs:125:81328
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/chunk-H4UZCO6D.mjs:2:1082
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/server.mjs:228:22433
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/chunk-H4UZCO6D.mjs:2:1082
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/server.mjs:228:56725
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/chunk-H4UZCO6D.mjs:2:1082
    at file:///Users/nikhilverma/Work/Projects/Programming/typeorm-ng/dist/typeorm-ng/server/server.mjs:236:5133
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)

### Actual Behavior

My DataSource should connect to the database (assuming the credentials are correct) and I should be able to perform additional operations on it. Instead trying to connect to my datasource crashes the server terminally.

### Steps to reproduce

1. Create a new angular v18 project 
2. Integrate TypeORM as described in the official documentation
3. Build the project using ```ng run build```
4. Run the project using ```ng run serve:ssr:<project-name>``` where <project-name> should be replaced by your project's name. (Check your package.json for the correct script, for v18 this should be the default)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS Sonoma 14.6.1        |
| Node.js version     | 20.12.2  |
| Angular version     | ^18.1.0  |
| Typescript version  | ~5.5.2  |
| TypeORM version     | ^0.3.20  |
| Postgres version     | ^8.12.0  |
| Reflect-metadata version     | ^0.2.2  |

### Additional Context

I am also being bombarded with warnings about several typeorm dependencies being CommonJS and not ESM (Like dayjs being one of them). I think the issue is related to those warnings.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by elias-ik** [comment]
I have the same issue, have found a workaround / solution @nikhilverma-xorsafe-0

**Comment by OSA413** [comment]
Hi! Can you share a Minimal Reproducible Example repository please?
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by elias-ik** [comment]
https://github.com/elias-ik/my-angular-ssr-app-with-typeorm

**Comment by synthet1c** [comment]
@nikhilverma-xorsafe-0 Did you have any luck with this?

I've attempted to user the `@angular-builders/custom-webpack:browser` builder shimming `__dirname` with an alias or a custom webpack plugin, but not having any luck configuring custom-webpack with angular 19 hybrid/ssr.

The issue is that typeorm relies on a commonjs module `app-root-path` which uses `__dirname` to get the path of a project which has since been replaced with:

```typescript
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```

The code uses `app-root-path` in these locations.
* `src/connection/ConnectionOptionsReader.ts:1`
* `src/logger/FileLogger.ts:3`
* `test/functional/multi-database/multi-database-basic-functionality/multi-database-basic-functionality.ts:18`
* `test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts:18`
* `test/github-issues/3302/issue-3302.ts:2`
* `test/github-issues/3302/subscriber/PostSubscriber.ts:8`
* `test/github-issues/4410/issue-4410.ts:1`
* `package.json:226`

**Comment by detobel36** [comment]
Hello,

Temporary fix for me is to apply this: https://github.com/inxilpro/node-app-root-path/issues/56#issuecomment-1918059243
In app-root-path module.
