### ISSUE TITLE
Unhandled rejection from TypeORM hangs the application

### ISSUE THREAD

**Issue by scr4bble** [typeorm/typeorm#11054]
### Issue description

SQL error results into unhandled exception and takes down the app

### Expected Behavior

I would expect the exception to be returned properly so our command is able to properly propagate it through the app into request exception handler.

```
repo
          .createQueryBuilder()
          .insert()
          .values(inserts)
          .orUpdate(
            getColumnsToUpdate(
              repo.metadata.ownColumns,
              'databaseName',
              orUpdateFields, // only update the columns that were provided in the insert
            ),
          )
          .updateEntity(false)
          .execute();
```

### Actual Behavior

The exception seems to hang our app so it stop processing new requests and stays in a hanged state until restarted.

```
error: Error: Out of range value for column 'number_pax' at row 11

APP_ROOT/src/driver/mysql/MysqlQueryRunner.ts:246
                                new QueryFailedError(query, parameters, err),
                                ^
QueryFailedError: Out of range value for column 'number_pax' at row 11
    at Query.onResult (APP_ROOT/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (APP_ROOT/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (APP_ROOT/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (APP_ROOT/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (APP_ROOT/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (APP_ROOT/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:43940: read: connection reset by peer
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:43954: read: connection reset by peer
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:43958: read: connection reset by peer
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:43978: read: connection reset by peer
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:44772: read: connection reset by peer
2024/09/05 15:47:52 [DATABASE] connection aborted - error reading from client: read tcp [::1]:12345->[::1]:43948: read: connection reset by peer

```

### Steps to reproduce

I am not able to share the codebase with you but I am happy to help with debugging or providing more information if requested. I will try to respond as quickly as I can.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |Fedora 39|
| Node.js version     | v20.12.2  |
| Typescript version  | 5.3.3  |
| TypeORM version     | 0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by alumni** [comment]
Looks like a normal SQL error that is not being caught.

**Comment by JingYeoh** [comment]
```
 return await this.dataSource.transaction(async (manager) => {
            let newSetting = manager.create(TransactionSignalSettingBuyEntity, {
                wallet: {id: wallet.id},
                signal_source: signalSource,
            })
            newSetting = await manager.save(TransactionSignalSettingBuyEntity, newSetting)
            this.logger.debug(`initSignalBuySetting done`, newSetting)
            return newSetting
        }).catch(error => {
            this.logger.error('initSignalBuySetting failed', error)
            throw error
        })
```
@alumni This is my code, i use await, and catch the error, but this execution has no error, when i do next action, this error happened.

**Comment by JingYeoh** [comment]
```
  "query": "UPDATE `blockchain_transaction_signal_setting_buy` SET `walletId` = ?, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` = ?",
  "parameters": [
    null,
    75
  ],
  "driverError": {
    "code": "ER_BAD_NULL_ERROR",
    "errno": 1048,
    "sqlState": "23000",
    "sqlMessage": "Column 'walletId' cannot be null",
    "sql": "UPDATE `blockchain_transaction_signal_setting_buy` SET `walletId` = NULL, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` = 75"
  },
  "code": "ER_BAD_NULL_ERROR",
  "errno": 1048,
  "sqlState": "23000",
  "sqlMessage": "Column 'walletId' cannot be null",
  "sql": "UPDATE `blockchain_transaction_signal_setting_buy` SET `walletId` = NULL, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` = 75",
  "stack": "QueryFailedError: Column 'walletId' cannot be null\n    at Query.onResult (/Users/workspace/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:246:33)\n    at Query.execute (/Users/workspace/node_modules/mysql2/lib/commands/command.js:36:14)\n    at PoolConnection.handlePacket (/Users/workspace/node_modules/mysql2/lib/connection.js:481:34)\n    at PacketParser.onPacket (/Users/workspace/node_modules/mysql2/lib/connection.js:97:12)\n    at PacketParser.executeStart (/Users/workspace/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/Users/workspace/node_modules/mysql2/lib/connection.js:104:25)\n    at Socket.emit (node:events:507:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)"
```

This is error, and I'm sure the data is inserted to the table, i use sql query, the walletId is inserted and not null, and this issue blocked my server, i have to restart server and db connection
