### ISSUE TITLE
ManyToMany Update Inverts ID Columns

### ISSUE THREAD

**Issue by gthole** [typeorm/typeorm#11060]
### Issue description

When updating a many to many relationship, the Insert to the M2M table has the ID column inverted

### Expected Behavior

Saving a relationship should correctly insert the ManyToMany table relationship.

Example:
```
  client_id = 1
  group_id = 2
  query: 'INSERT INTO "client_groups"("group_id", "client_id") VALUES ($1, $2)',
  parameters: [ 2, 1 ],
  ```

### Actual Behavior

Saving a relationship inverts the ids, resulting in an incorrect assignment or a foreign key constraint error.

(Note the parameters: [1, 2] compared to the expected [2, 1] in the "Expected Behavior")
  ```
  QueryFailedError: insert or update on table "client_groups" violates foreign key constraint "FK_bdeafcc8fdf8a163af93b58ab6a"
    at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:140:21)
    at async run (/app/lib/src/index.js:29:5) {
  query: 'INSERT INTO "client_groups"("group_id", "client_id") VALUES ($1, $2)',
  parameters: [ 1, 2 ],
  driverError: error: insert or update on table "client_groups" violates foreign key constraint "FK_bdeafcc8fdf8a163af93b58ab6a"
```

### Steps to reproduce

A fully working example of the issue with a command to run it is here:
https://gist.github.com/gthole/b86f60fc5a885301f5ca883d9b8dddfe

### My Environment

| Dependency            | Version  |
| ---                            | ---         |
| Operating System   |               |
| Node.js version       | 18.20.3  |
| Typescript version  | 5.6.2      |
| TypeORM version   | 0.3.20    |
| Postgres                  | 16          |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by gthole** [comment]
This turned out to be a wrong decorator argument.

I was putting the following in:
```
    @ManyToMany(() => Client, (client) => client.groups)
    @JoinTable({
        name: 'client_groups',
        joinColumn: {
            name: 'group_id',
            referencedColumnName: 'id'
        },
        inverseJoinColumn: {
            name: 'client_id',
            referencedColumnName: 'id'
        }
    })
    clients: Client[];
```

But that `(client) => client.groups`, which is standard in `OneToMany` and `ManyToOne`, but apparently not correct for `ManyToMany`. TIL.
