### ISSUE TITLE
Unable to open dataSource.ts

### ISSUE THREAD

**Issue by SteffenHF** [typeorm/typeorm#11090]
### Issue description

Unable to open dataSource.ts because require() of ES Module file:///workspaces/hfs_sales/node_modules/typeorm/index.mjs not supported.

### Expected Behavior

Running `npm run typeorm -- migration:run` to migrate my database.

### Actual Behavior

```bash
node ➜ /workspaces/hfs_sales (main) $ npm run typeorm -- migration:run

> hfs-sales@0.0.1 typeorm
> typeorm-ts-node-commonjs -d src/lib/db/dataSource.ts migration:run

Error during migration run:
Error: Unable to open file: "/workspaces/hfs_sales/src/lib/db/dataSource.ts". require() of ES Module file:///workspaces/hfs_sales/node_modules/typeorm/index.mjs not supported.
Instead change the require of file:///workspaces/hfs_sales/node_modules/typeorm/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Function.loadDataSource (/workspaces/hfs_sales/node_modules/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (/workspaces/hfs_sales/node_modules/src/commands/MigrationRunCommand.ts:42:26)
```

### Steps to reproduce

1. create a new next.js project using ``
2. Follow [installation steps](https://typeorm.io/#installation)
  1. `npm install typeorm --save`
  2. `npm install reflect-metadata --save`
  3. Add `import "reflect-metadata"` to `next.config.js`
  4. `npm install @types/node --save-dev`
  5. `npm install mysql2 --save`
  6. Add the following lines to tsconfig.json
  ```
  "emitDecoratorMetadata": true,
  "experimentalDecorators": true,
  ```
3. Create some migrations `npm run typeorm -- migration:create ...`
4. Run `npm run typeorm -- migration:run`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     debian     |
| Node.js version     | 22.9.0 |
| Typescript version  | 5.6.2  |
| TypeORM version     | 0.3.20  |

### Additional Context

I already tried changing the script to `typeorm-ts-node-esm`.

**package.json**
```json
{
  "name": "hfs-sales",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "eslint . --ext .ts,.tsx -c .eslintrc.json --fix",
    "typeorm": "typeorm-ts-node-commonjs -d src/lib/db/dataSource.ts"
  },
  "dependencies": {
    "@nextui-org/button": "2.0.38",
    "@nextui-org/code": "2.0.33",
    "@nextui-org/input": "2.2.5",
    "@nextui-org/kbd": "2.0.34",
    "@nextui-org/link": "2.0.35",
    "@nextui-org/listbox": "2.1.27",
    "@nextui-org/navbar": "2.0.37",
    "@nextui-org/snippet": "2.0.43",
    "@nextui-org/switch": "2.0.34",
    "@nextui-org/system": "2.2.6",
    "@nextui-org/theme": "2.2.11",
    "@react-aria/ssr": "3.9.4",
    "@react-aria/visually-hidden": "3.8.12",
    "axios": "^1.7.7",
    "bcrypt-ts": "^5.0.2",
    "class-validator": "^0.14.1",
    "clsx": "2.1.1",
    "framer-motion": "~11.1.1",
    "intl-messageformat": "^10.5.0",
    "jose": "^5.9.3",
    "mysql2": "^3.11.3",
    "next": "14.2.4",
    "next-themes": "^0.2.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "reflect-metadata": "^0.2.2",
    "ts-results": "^3.3.0",
    "typeorm": "^0.3.20",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "^20.5.7",
    "@types/react": "18.3.3",
    "@types/react-dom": "18.3.0",
    "@typescript-eslint/eslint-plugin": "7.2.0",
    "@typescript-eslint/parser": "7.2.0",
    "autoprefixer": "10.4.19",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.1",
    "eslint-config-prettier": "^8.2.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-unused-imports": "^3.2.0",
    "postcss": "8.4.38",
    "tailwind-variants": "0.1.20",
    "tailwindcss": "3.4.3",
    "ts-node": "^10.9.2",
    "typescript": "5.0.4"
  }
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "ts-node": {
    "esm": true
  },
  "type": "module",
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**dataSource.ts**
```ts
/**
 * The data source is the main entry point for the TypeORM library.
 */

import { DataSource } from "typeorm";

import { dbConfig } from "@/config/db";

export let AppDataSource = new DataSource({
  type: "mysql",
  host: dbConfig.dbConnection.host,
  port: dbConfig.dbConnection.port,
  database: dbConfig.dbConnection.database,
  username: dbConfig.dbCredentials.username,
  password: dbConfig.dbCredentials.password,
  synchronize: true,
  logging: true,
  entities: [__dirname + "/models/entities/**/*.{ts,js}"],
  migrations: [__dirname + "/migrations/**/*.{ts,js}"],
});

AppDataSource.initialize().then(() => {
  console.log("Database connected successfully!");
});
```

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ConnysCode** [comment]
Hey guys, to me, it seems like this issue is connected to TS `v5.6.x`.

Output with TS 5.5.x: (Correctly reaches connection check)
<img width="669" alt="image" src="https://github.com/user-attachments/assets/5688166b-2a76-461a-ac73-cd00cf549e21">

Output with TS 5.6.x: (Fails before connection check)
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/1226b811-6666-4a0e-a09e-0544da092300">

Strangely - i can not reproduce this issue locally - only inside of Docker. (`node:22-slim`)

_typeorm version is identical to OP's config_

**Comment by isimmons** [comment]
I'm having a similar issue. In a vite/react/ts project. 

Running command
```bash
 npm run  typeorm migration:generate CreateUsersTable --  -d src/data-source.ts
```

```bash
Error: Unable to open file: "C:\Users\isimm\code\React\comp-test-ground\src\data-source.ts". exports is not defined in ES module scope
```

package.json script

```json
"typeorm": "typeorm-ts-node-esm"
```

data-source.ts
```ts
import { DataSource } from 'typeorm'
import { User } from './entities/User'

export const AppDataSource = new DataSource({
  type: 'sqlite',
  database: 'database.sqlite',
  entities: [User],
  synchronize: true,
})

AppDataSource.initialize()
  .then(() => {
    console.log('Data Source has been initialized!')
  })
  .catch((err) => {
    console.error('Error during Data Source initialization', err)
  })
```

tsconfig.app.json
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",

    /* TypeOrm */
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,

    /* Paths */
    "baseUrl": "./",
    "paths": {
      "~/*": ["src/*"]
    }
  },
  "include": ["src"]
}
```

tsconfig.node.json
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["vite.config.ts"]
}
```
Other than the "typeorm" section and "alias" in tsconfig.app.json, these are the default for the react-ts template.

**Comment by JulienB37** [comment]
Hi, 

Same issue for me with TypeORM command "migration:generate" with typescript 5.6+.
With typescript 5.5, no problem.

**Comment by JulienB37** [comment]
solution here : https://github.com/typeorm/typeorm/issues/5087#issuecomment-627743159
