### ISSUE TITLE
Test environment has been torn down when DataSource.initialize() in ESM project

### ISSUE THREAD

**Issue by suehiro24** [typeorm/typeorm#11095]
### Issue description

My project has some test files for running jest, but when run npm run test, only the test cases in first test file is success, and other file cases are failure by the test env torn down error.

### Expected Behavior

All test cases run successfully, no torndown the test environment.
The DB should be rolled back before and after each test case, and each test file should connect to the DB correctly.

### Actual Behavior

When `npm run test`, an error occors.
The log is below.
```
> test-ts-esm-typeorm-jest@1.0.0 test /workspaces/test-ts-esm-typeorm-jest
> node --experimental-vm-modules ./node_modules/jest/bin/jest.js

(node:13541) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  tests/get-user.test.ts
 FAIL  tests/create-user.test.ts
  ● Test suite failed to run

    Test environment has been torn down

      18 | })
      19 |
    > 20 | await AppDataSource.initialize()
         | ^
      21 | export {AppDataSource}

      at invariant (node_modules/.pnpm/jest-util@29.7.0/node_modules/jest-util/build/invariant.js:16:11)
          at async Promise.all (index 0)
      at src/data-source.ts:20:1

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.696 s, estimated 3 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```

### Steps to reproduce

The Project is shown this repository.
https://github.com/suehiro24/esm-typerom-jest-torndown-reproduction

You can reproduce this by starting devcontaier and doing npm test.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 22.04.4 |
| Node.js version     | v22.5.1 |
| Typescript version  | 5.6.3 |
| TypeORM version     | 0.3.20 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ebettenga** [comment]
I will solve this with a PR if I knew more about what was wrong.

**Comment by sbassin** [comment]
I'm running into this same issue on Node 22.15.1 as I try to convert my current CommonJS project to ES Modules.

**Comment by felix-gohla** [comment]
We have the same problem in one of our projects. After some debugging, changing the following code that imports the models to just a plain `await import(filePath)` (in the compiled output) instead of doing magic eval-foo fixes the issue:

https://github.com/typeorm/typeorm/blob/d4f7b44fdf592a5e8c629d633691543a784e45e6/src/util/ImportUtils.ts#L13-L17

Of course, due to transpilation, it is not possible to write the `import` directly in the source code.
