### ISSUE TITLE
Wrong discriminator value for single table inheritance saved in DB

### ISSUE THREAD

**Issue by eduardoweiland** [typeorm/typeorm#111]
When using single table inheritance, the child classes are saved in the database with the same type as the parent, so there is no way to distinguish between them.

I have forked the typescript-example [here](https://github.com/eduardoweiland/typescript-example/) and added a new entity to reproduce this behavior. Running the app should create a Post and a Draft in the DB (Draft is marked as SingleTableChild of Post). Both entities are saved, but the draft has type = "Device" instead of "Draft". I have tested with MySQL, if this makes some difference.

Relevant TypeScript code
```ts
const post = new Post();
post.title = "Control flow based type analysis";
post.text = `TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters.`;
post.categories = [category1, category2];

const draft = new Draft();
draft.title = "Not published post";
draft.text = "This post will be published soon...";
draft.categories = [category1];
draft.revisionNotes = "Maybe add category Programming to this post too?"

const postRepository = connection.getRepository(Post);
await postRepository.persist(post);
await postRepository.persist(draft);
```

Result in database

```
-- select id, title, type from post;
+----+----------------------------------+------+
| id | title                            | type |
+----+----------------------------------+------+
|  1 | Control flow based type analysis | Post |
|  2 | Not published post               | Post |
+----+----------------------------------+------+
```

Also, when running this code with authSchemaSync, the following error occurs while creating the schema, but the tables are correctly created in the database:

```
Error:  { Error: ER_CANT_CREATE_TABLE: Can't create table `testdb`.`#sql-106f_c` (errno: 121 "Duplicate key on write or update")
    at Query.Sequence._packetToError (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/eduardo/typescript-example/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/home/eduardo/typescript-example/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/home/eduardo/typescript-example/node_modules/mysql/lib/Connection.js:214:25)
    at Promise (/home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:134:48)
    at MysqlQueryRunner.query (/home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:133:16)
    at foreignKeys.map.foreignKey (/home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:378:29)
    at Array.map (native)
    at MysqlQueryRunner.<anonymous> (/home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:370:42)
    at next (native)
    at /home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:7:65
    at __awaiter (/home/eduardo/typescript-example/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:3:12)
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlState: 'HY000',
  index: 0 }
```

**Comment by pleerock** [comment]
In your example you have:

```typescript
const postRepository = connection.getRepository(Post);
await postRepository.persist(post);
await postRepository.persist(draft);
```

you have error. To save a draft you should not use `postRepository`, instead you should do `const draftRepository = connection.getRepository(Draft);` and use `draftRepository`.

**Comment by eduardoweiland** [comment]
I have tried this in my project, but I get this error:

```
    at new RepositoryNotFoundError (/home/eduardo/Projetos/expin/server/node_modules/typeorm/connection/error/RepositoryNotFoundError.js:12:22)
    at Connection.findRepositoryAggregator (/home/eduardo/Projetos/expin/server/node_modules/typeorm/connection/Connection.js:294:19)
    at Connection.getRepository (/home/eduardo/Projetos/expin/server/node_modules/typeorm/connection/Connection.js:255:21)
    at /home/eduardo/Projetos/expin/server/build/app.js:37:28
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

I could not reproduce this error using the forked repository, it only happens in my project. When I manage to reproduce it again, I will post here.

**Comment by pleerock** [comment]
I need source code of your entities, minimal code to reproduce error and error itself to see and reproduce your error on my own

**Comment by eduardoweiland** [comment]
I updated the repo with new entities to better reflect my problem. It seems that this error happens when using more than one level of inheritance. I have the following hierarchy: `TemperatureSensor extends SensorDevice` and `SensorDevice extends Device`. SensorDevice is used to share some common columns and methods between the models. I tried adding `@AbstractTable` in SensorDevice, but it made no difference.

If you run the code, you can see that the child class (TemperatureSensor in this case) does not have a repository, that's why I was using the parent repository to persist the object. The output for me is:

```
Error with TemperatureSensor repository: { Error
    at new RepositoryNotFoundError (/home/eduardo/typescript-example/node_modules/typeorm/connection/error/RepositoryNotFoundError.js:12:22)
    at Connection.findRepositoryAggregator (/home/eduardo/typescript-example/node_modules/typeorm/connection/Connection.js:284:19)
    at Connection.getRepository (/home/eduardo/typescript-example/node_modules/typeorm/connection/Connection.js:245:21)
    at Object.<anonymous> (/home/eduardo/typescript-example/src/index.js:36:56)
    at next (native)
    at /home/eduardo/typescript-example/src/index.js:7:65
    at __awaiter (/home/eduardo/typescript-example/src/index.js:3:12)
    at typeorm_1.createConnection.then (/home/eduardo/typescript-example/src/index.js:30:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'RepositoryNotFoundError',
  message: 'No repository for "TemperatureSensor" was found. Looks like this entity is not registered in current "default" connection?' }
Error with SensorDevice repository: { Error
    at new RepositoryNotFoundError (/home/eduardo/typescript-example/node_modules/typeorm/connection/error/RepositoryNotFoundError.js:12:22)
    at Connection.findRepositoryAggregator (/home/eduardo/typescript-example/node_modules/typeorm/connection/Connection.js:284:19)
    at Connection.getRepository (/home/eduardo/typescript-example/node_modules/typeorm/connection/Connection.js:245:21)
    at Object.<anonymous> (/home/eduardo/typescript-example/src/index.js:44:51)
    at next (native)
    at /home/eduardo/typescript-example/src/index.js:7:65
    at __awaiter (/home/eduardo/typescript-example/src/index.js:3:12)
    at typeorm_1.createConnection.then (/home/eduardo/typescript-example/src/index.js:30:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'RepositoryNotFoundError',
  message: 'No repository for "SensorDevice" was found. Looks like this entity is not registered in current "default" connection?' }
Created with Device repository: TemperatureSensor { name: 'Room', temperature: 24, status: 'ok', id: 4 }
```

**Comment by pleerock** [comment]
Such "deep inheritance" is not supported by class table and single table inheritance. Deep inheritance is supported only by simple inheritance using `@AbstractTable` decorator. Its support probably wont come in the nearest feature because of complexity over value in brings. Class-table/single table inheritance strategies makes your much complex, so I recommend to avoid its usage as much as possible.

**Comment by eduardoweiland** [comment]
OK. I will try to implement this using interfaces for the middle classes. I will need to duplicate some code, but at least it should work. Thanks.
