### ISSUE TITLE
Error on upsert: Cannot update entity because entity id is not set in the entity.

### ISSUE THREAD

**Issue by szcrow** [typeorm/typeorm#11193]
### Issue description

When performing an `UPSERT` operation on a composite primary key, the error `Cannot update entity because entity id is not set in the entity.` occurs.

### Expected Behavior

The query should update only the `key` column if there is a conflict on `lang` and `templateId`, without modifying the `id` field, which is auto-generated.

The `id` field should not be relevant at all, since we know which row we are updating (the one with the conflict).

### Actual Behavior

TypeORM throws the error `Cannot update entity because entity id is not set in the entity.`, even though the `id` field should remain unaffected during the conflict resolution.

### Steps to reproduce

Here is my entity. We have a composite primary key of `lang`, `id` and `templateId`.

```ts
@Entity()
@Index(['templateId', 'lang'], { unique: true })
export class FileEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  @Column({ nullable: false, type: 'varchar', primary: true })
  lang: LanguageKeys;

  @Column({ nullable: false, primary: true })
  templateId: number;

  @Column({ length: 100, nullable: false })
  key: string;
}
```

Trying either method for upserting does not work:

```ts
// insert + on conflict update
await this.fileRepository
        .createQueryBuilder()
        .insert()
        .values({
          templateId,
          lang,
          key: fileKey,
        })
        .orUpdate(['key'], ['templateId', 'lang'], {
          skipUpdateIfNoValuesChanged: true,
          upsertType: 'on-duplicate-key-update', // no upsertType works
        })
        .execute();

// upsert
await this.fileRepository.upsert(
        {
          templateId,
          lang,
          // i think we should just store the filename here
          // the fileKey can be constructed from the prefix + templateId + lang + filename
          // we always have the templateId and the language so it's a bit redundant
          key: fileKey,
        },
        {
          conflictPaths: {
            templateId: true,
            lang: true,
          },
          skipUpdateIfNoValuesChanged: true,
          upsertType: 'on-duplicate-key-update',
        },
      );
```

Note that on both, I am defining the conflict columns to be `lang` and `templateId`.

Funnily, this works perfectly if I just run a raw query (with the sql generated by either of the two previous query builders):

```ts
await this.fileRepository.query(
        `
        INSERT INTO template_file (lang, template_id, \`key\`, created_at, updated_at, deleted_at)
        VALUES (?, ?, ?, DEFAULT, DEFAULT, DEFAULT)
        ON DUPLICATE KEY UPDATE \`key\` = VALUES(\`key\`) 
        `,
        [lang, templateId, fileKey],
      );
```

I believe this should not happen, SQL allows this just fine, but TypeOrm is preventing the query from running based on a "missing" (but unneeded) column.

### My Environment

| Dependency          | Version  |
|---|---|
|  NestJS                | 9     |
| Operating System    |    Windows 11      |
| Node.js version     | 20  |
| Typescript version  | 4.9.5  |
| TypeORM version     |  0.3.12 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by jason-hwang** [comment]
@szcrow 
I think the problem should be fixed. to solve this problem temporary, I utilize the `updateEntity` option. 

```diff
await dataSource
    .createQueryBuilder()
    .insert()
    .into(...)
    .values({ ... })
    .orIgnore()
++  .updateEntity(false)
    .execute();
```

**Comment by jason-hwang** [comment]
> @jason-hwang which PR fixed this issue?

I'm not sure if the `.insert().into(...)` syntax should always guarantee an `update entity`.

However, if you need to use the `.insert().into(...)` syntax directly, use it through a transactionManager and the above issue will not be reproduced.

**Comment by bytelucas** [comment]
## Solution ✅ - Race Condition Issue with TypeORM upsert()

I encountered this issue with **TypeORM 0.3.20** on **MySQL** and identified the root cause.

### Error Message
<details><summary>Error message details</summary>
<p>

[Nest] 1 - 09/10/2025, 4:07:54 PM ERROR [WsExceptionsHandler] Cannot update entity because entity id is not set in the entity.
TypeORMError: Cannot update entity because entity id is not set in the entity.
at /usr/src/app/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:120:27
at Array.map (<anonymous>)
at ReturningResultsEntityUpdator.insert (/usr/src/app/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:114:40)
at InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:113:53)

</p>
</details>

### Root Cause: Race Condition
This error occurs specifically when **multiple concurrent requests** hit the same `upsert()` operation simultaneously (e.g., spamming requests). Here's what happens:

**Timeline of the Race Condition:**
1. **Request A**: Checks if record exists → Not found → Prepares INSERT
2. **Request B**: Checks if record exists → Not found → Prepares INSERT  
3. **Request A**: Executes INSERT → Success, gets new ID
4. **Request B**: Executes INSERT → **Constraint violation!** → Falls back to UPDATE
5. **TypeORM (Request B)**: Expects ID for UPDATE operation but has none
6. **Crash**: "Cannot update entity because entity id is not set"

### Failing Code ❌
```typescript
const upsertBody: QueryDeepPartialEntity<OnlineUserEntity> = {
  userId,
  role: EOrderRole.SELLER,
  screenName: EOnlineUserScreenName.ORDER_MANAGEMENT,
  socketId: client.id,
  isActive: true,
  lastActive: new Date(),
};

// This fails under concurrent requests
await this.onlineUserRepository.upsert(upsertBody, {
  conflictPaths: ['userId', 'screenName'], // used unique constraint, not primary key
});
```

### Replacement Code ✅
```typescript
await this.onlineUserRepository.query(
  `
  INSERT INTO \`database_name\`.\`table_name\` (user_id, screen_name, socket_id, is_active, last_active, role, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, NOW(), NOW())
  ON DUPLICATE KEY UPDATE 
    socket_id = VALUES(socket_id),
    is_active = VALUES(is_active),
    last_active = VALUES(last_active),
    updated_at = NOW()
  `,
  [userId, screenName, client.id, 1, new Date(), role],
);
```

**Comment by pxson2903** [comment]
You just made my day. I can solve my issue now. Thanks a lot @bytelucas .
