### ISSUE TITLE
Error launch basic sample for test with MongoDb

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#1119]
Hello,

I have get the projet with the command line : 
`typeorm init --name MyProject --database mongodb --express`

After I change in ormconfig : 
`"host": "192.168.1.82",
   "port": 27017,`

And start  : npm start and obtain :

`> ts-node src/index.ts

TypeError: Cannot read property 'createValueMap' of undefined
    at MongoQueryRunner.<anonymous> (/Users/far-paul/Sites/lucy/crous78-back-mongodb/src/driver/mongodb/MongoQueryRunner.ts:407:89)
    at step (/Users/far-paul/Sites/lucy/crous78-back-mongodb/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:32:23)
    at Object.next (/Users/far-paul/Sites/lucy/crous78-back-mongodb/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:13:53)
    at fulfilled (/Users/far-paul/Sites/lucy/crous78-back-mongodb/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

Help please.

Thanks

**Comment by pleerock** [comment]
Thank you for the report, I'll check this issue. Meanwhile you can try to checkout and try [this example repository with monogdb ](https://github.com/typeorm/typeorm-typescript-mongo-example)

**Comment by pleerock** [comment]
This was fixed in `0.1.4`
