### ISSUE TITLE
Error when using Repository.delete by column which has value transformer

### ISSUE THREAD

**Issue by nandaoshihuanjue** [typeorm/typeorm#11208]
### Issue description

Error when using Repository.delete by Column which has value transformer

### Expected Behavior

I have an entity like below. 

```
@Entity()
export class MyEntity {
  @PrimaryColumn({
    type: 'binary',
    length: 16,
    generated: false,
    transformer: uuidTransformer,
  })
  colA: string;

  ...other fields, doesn't matter for this issue
}
```

Because I am using BINARY(16) to store UUID, so I have a uuidTransformer for the column. Here is the uuidTransformer function
```
export const uuidTransformer = {
  to: (uuid: string | undefined): Buffer | undefined => {
    console.log(uuid); // Log it for debugging purpose. Will show the value later
    return uuid ? Buffer.from(uuid.replace(/-/g, ''), 'hex') : undefined;
  },
  from: (bin: Buffer | undefined): string | undefined => {
    ...... // this function doesn't matter for this issue.
  },
};
```

Here is what I do for deleting entities by `colA`

```
// colAValues are strings in UUID format
async deleteByColA(colAValues: string[]) {
  this.repository.delete({
      colA: In(colAValues),
  });
}
```

I expect it to delete successfully.

### Actual Behavior

It throws error

```
TypeError: uuid.replace is not a function
    at Object.to (/Users/abab/Documents/example-codebase/src/utils/uuid-transformer.ts:4:36)
    at Function.transformTo (/Users/abab/Documents/example-codebase/node_modules/.pnpm/typeorm@0.3.20_mysql2@3.11.4_ts-node@10.9.2/node_modules/typeorm/util/src/util/ApplyValueTransformers.ts:28:28)
    at ColumnMetadata.getEntityValue (/Users/abab/Documents/example-codebase/node_modules/.pnpm/typeorm@0.3.20_mysql2@3.11.4_ts-node@10.9.2/node_modules/typeorm/metadata/src/metadata/ColumnMetadata.ts:843:44)
    at DeleteQueryBuilder.getPredicates (/Users/abab/Documents/example-codebase/node_modules/.pnpm/typeorm@0.3.20_mysql2@3.11.4_ts-node@10.9.2/node_modules/typeorm/query-builder/src/query-builder/QueryBuilder.ts:1486:51)
    at getPredicates.next (<anonymous>)
    at DeleteQueryBuilder.getWhereCondition (/Users/abab/Documents/example-codebase/node_modules/.pnpm/typeorm@0.3.20_mysql2@3.11.4_ts-node@10.9.2/node_modules/typeorm/query-builder/src/query-builder/QueryBuilder.ts:1647:50)
    at DeleteQueryBuilder.where (/Users/abab/Documents/example-codebase/node_modules/.pnpm/typeorm@0.3.20_mysql2@3.11.4_ts-node@10.9.2/node_modules/typeorm/query-builder/src/query-builder/DeleteQueryBuilder.ts:147:32)
```

And here is the output of `console.log` from `uuidTransformer` function which I expect it to be a UUID string, but instead, it is an FindOperator object.
```
FindOperator {
  '@instanceof': Symbol(FindOperator),
  _type: 'in',
  _value: [ 'c533dad0-16c1-4634-b08b-a91a116ab694' ],
  _useParameter: true,
  _multipleParameters: true,
  _getSql: undefined,
  _objectLiteralParameters: undefined
}
```

For other operations like `repository.find` and `repository.update`, the uuidTransformer works just fine, and output of `console.log` is just a UUID like string.

### Steps to reproduce

Create an entity like what I wrote above, use a uuidTransformer function for the column to delete by. And use `repository.delete` to delete by that column.

I can provide the full uuidTransformer function if reproduction is needed.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   MacOs 15.1.1    |
| Node.js version     | 20.18.0 |
| Typescript version  | 5.6.3 |
| TypeORM version     | 10.0.2 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by nandaoshihuanjue** [comment]
Ok, after some debugging, I found a weird place in the source code, specifically, in the `src/query-builder/QueryBuilder.ts` file `*getPredicates()` function. Here is the source code 

```
    protected *getPredicates(where: ObjectLiteral) {
        if (this.expressionMap.mainAlias!.hasMetadata) {
            const propertyPaths = this.createPropertyPath(
                this.expressionMap.mainAlias!.metadata,
                where,
            )

            for (const propertyPath of propertyPaths) {
                const [alias, aliasPropertyPath, columns] =
                    this.findColumnsForPropertyPath(propertyPath)

                for (const column of columns) {
                    let containedWhere = where

                    for (const part of aliasPropertyPath) {
                        if (!containedWhere || !(part in containedWhere)) {
                            containedWhere = {}
                            break
                        }

                        containedWhere = containedWhere[part]
                    }

                    // Use the correct alias & the property path from the column
                    const aliasPath = this.expressionMap
                        .aliasNamePrefixingEnabled
                        ? `${alias.name}.${column.propertyPath}`
                        : column.propertyPath

                    const parameterValue = column.getEntityValue(
                        containedWhere,
                        true,
                    )

                    yield [aliasPath, parameterValue]
                }
            }
        } else {
            for (const key of Object.keys(where)) {
                const parameterValue = where[key]
                const aliasPath = this.expressionMap.aliasNamePrefixingEnabled
                    ? `${this.alias}.${key}`
                    : key

                yield [aliasPath, parameterValue]
            }
        }
    }
```

The weird place to me are these few lines
```
                    const parameterValue = column.getEntityValue(
                        containedWhere,
                        true,
                    )
```

where `containedWhere` is an object of where clause, which in my case is an object like below.
```
{
  colA: In(colAValues)
}
```
In the QueryBuilder.getPredicates, it calls `column.getEntityValue` to get the parameter value? Shouldn't the first argument of `column.getEntityValue` be an entity? Or maybe there is something I missed. 

I mimic how the `where` object is used in SelectQueryBuilder and modify these few lines to be like below
```
                    // my clumsy imitation of how where object is used in SelectQueryBuilder.ts
                    let parameterValue = containedWhere[propertyPath];
                    if (column.transformer) {
                        parameterValue instanceof FindOperator
                            ? parameterValue.transformValue(column.transformer)
                            : (parameterValue =
                                  ApplyValueTransformers.transformTo(
                                      column.transformer,
                                      parameterValue,
                                  ))
                    }
                    // comment out the original few lines
                    // const parameterValue = column.getEntityValue(
                    //     containedWhere,
                    //     true,
                    // )
```
Now it works at least for my simple case. But I am too new to this codebase and have no idea what should be the proper fix. 

Can anyone help me with it? What should I do next? How should I bypass the potential bug to still get my entity deleted by column values? Thanks!
