### ISSUE TITLE
AWS Beanstalk - node version issue or something else?

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1122]
Hi,

I am using typeorm locally without any issues. I am on node v6.11.3.
I am trying to publish my app to AWS Beanstalk but getting the following error. One notable difference is that it's trying to run node v6.11.1. There's also this bit too - `sh: /tmp/deployment/application/node_modules/.bin/opencollective: Permission denied`

Any thoughts? Thanks!

```
Application update failed at 2017-10-31T15:25:47Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.

+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install

> typeorm@0.1.0 postinstall /tmp/deployment/application/node_modules/typeorm
> opencollective postinstall

sh: /tmp/deployment/application/node_modules/.bin/opencollective: Permission denied

npm ERR! Linux 4.9.43-17.39.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm" "--production" "rebuild"
npm ERR! node v6.11.1
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! typeorm@0.1.0 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the typeorm@0.1.0 postinstall script 'opencollective postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typeorm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! opencollective postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs typeorm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls typeorm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/deployment/application/npm-debug.log
Running npm install: /opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1.
```

**Comment by pleerock** [comment]
Can you try `0.1.1` ?

**Comment by theigor** [comment]
0.1.1 worked. Thanks for the quick response!

**Comment by venkatreddyputhana7** [comment]
hi @pleerock ,
it works locally without any issues. I am on node v.8.9.4 and npm v.5.5.1
I am trying to publish my app to AWS Beanstalk but getting the following error. One notable difference is that it's trying to run node v.6.0.0 and npm v.3.86

https://user-images.githubusercontent.com/736710/35530651-bb442ca8-055a-11e8-98e0-0e126f58132f.png

**Comment by venkatreddyputhana7** [comment]
HI @pleerock ,
it works locally without any issues - I am on node v.8.9.4 and npm v.5.5.1
aws runs node v.6.0.0 and npm v.3.86

https://user-images.githubusercontent.com/736710/35530651-bb442ca8-055a-11e8-98e0-0e126f58132f.png

**Comment by venkatreddyputhana7** [comment]
Hi @pleerock ,
it works locally without any issues - I am on node v.8.9.4 and npm v.5.5.1
aws runs node v.6.0.0 and npm v.3.86

![image](https://user-images.githubusercontent.com/736710/35531976-a4184d26-055e-11e8-96b1-4dfa47b8f9cb.png)

**Comment by theigor** [comment]
@venkatreddyputhana7 - this error doesn't look like it has anything to do with typeorm - look at the error - it's about a missing script "start:dev". Looks like you have a package.json issue.
