### ISSUE TITLE
Problem with Index manipulation upon startup

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#113]
Version 0.0.4
MySQL

When starting up the server I receive the following problem when TORM tries to manipulate the indexes. My thought is that it has something to do with the ordering of how the statements get ordered. 

Even though I'm getting an exception here, this is still the best ORM tool I've come across.

Cheers

Paisti

> executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'xxx'
> executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'xxx'
> executing query: SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'xxx' AND INDEX_NAME != 'PRIMARY'
> executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'xxx' AND REFERENCED_COLUMN_NAME IS NOT NULL
> executing query: SHOW INDEX FROM `eligibility_category` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `eligibility_category_race_meet_categories_race_meet_category_id` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `grade_list` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `licence` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `licence_category` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `licence_type` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `nomination` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `organisation` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `organisation_payment_card_token` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `race` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `race_meet` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `race_meet_category` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `race_meet_category_standard_categories_standard_category_id` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `race_meet_type` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `rider_entry` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `standard_category` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `standard_category_licence_categories_licence_category_id` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `tokenised_organisation_payment_card` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `tokenised_user_payment_card` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `user` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `user_group` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `user_payment_card_token` WHERE Key_name = 'PRIMARY'
> executing query: SHOW INDEX FROM `user_user_groups_user_group_id` WHERE Key_name = 'PRIMARY'
> executing query: START TRANSACTION
> executing query: ALTER TABLE `user_user_groups_user_group_id` DROP INDEX `ind_43265aa419ab4e56ccf8b04ea71b0307929127b6`
> executing query: ALTER TABLE `user_user_groups_user_group_id` DROP INDEX `ind_11586c7528252838835e9047458958c4429d0cdd`
> executing query: CREATE INDEX `ind_43265aa419ab4e56ccf8b04ea71` ON `user_user_groups_user_group_id`(`userId`)
> executing query: CREATE INDEX `ind_11586c7528252838835e9047458` ON `user_user_groups_user_group_id`(`userGroupId`)
> executing query: ALTER TABLE `standard_category_licence_categories_licence_category_id` DROP INDEX `ind_783912fc9b1d2e94335beae5c85e6d5180c9b803`
> executing query: ALTER TABLE `standard_category_licence_categories_licence_category_id` DROP INDEX `ind_a31b451eab068ae6fa86d517e30341a4c17f0841`
> executing query: CREATE INDEX `ind_783912fc9b1d2e94335beae5c85` ON `standard_category_licence_categories_licence_category_id`(`standardCategoryId`)
> executing query: CREATE INDEX `ind_a31b451eab068ae6fa86d517e30` ON `standard_category_licence_categories_licence_category_id`(`licenceCategoryId`)
> executing query: ALTER TABLE `race_meet_category_standard_categories_standard_category_id` DROP INDEX `ind_2aaf3ee3974b2effb94927353496bd80a384e948`
> executing query: ALTER TABLE `race_meet_category_standard_categories_standard_category_id` DROP INDEX `ind_0a9c62bada8285ee17ef9797682903b07ca4a030`
> executing query: CREATE INDEX `ind_2aaf3ee3974b2effb9492735349` ON `race_meet_category_standard_categories_standard_category_id`(`raceMeetCategoryId`)
> executing query: CREATE INDEX `ind_0a9c62bada8285ee17ef9797682` ON `race_meet_category_standard_categories_standard_category_id`(`standardCategoryId`)
> executing query: ALTER TABLE `eligibility_category_race_meet_categories_race_meet_category_id` DROP INDEX `ind_eea4f3ef94458717f032e0d24e67edbf698d262d`
> executing query: ALTER TABLE `eligibility_category_race_meet_categories_race_meet_category_id` DROP INDEX `ind_f1657c8e87cc890a3f52cb47c29c9a4e8aed498b`
> executing query: CREATE INDEX `ind_eea4f3ef94458717f032e0d24e6` ON `eligibility_category_race_meet_categories_race_meet_category_id`(`eligibilityCategoryId`)
> executing query: CREATE INDEX `ind_f1657c8e87cc890a3f52cb47c29` ON `eligibility_category_race_meet_categories_race_meet_category_id`(`raceMeetCategoryId`)
> query failed: ALTER TABLE `user_user_groups_user_group_id` DROP INDEX `ind_11586c7528252838835e9047458958c4429d0cdd`
> error during executing query:Error: ER_DROP_INDEX_FK: Cannot drop index 'ind_11586c7528252838835e9047458958c4429d0cdd': needed in a foreign key constraint
> executing query: ROLLBACK
> query failed: ALTER TABLE `standard_category_licence_categories_licence_category_id` DROP INDEX `ind_a31b451eab068ae6fa86d517e30341a4c17f0841`
> error during executing query:Error: ER_DROP_INDEX_FK: Cannot drop index 'ind_a31b451eab068ae6fa86d517e30341a4c17f0841': needed in a foreign key constraint
> query failed: ALTER TABLE `race_meet_category_standard_categories_standard_category_id` DROP INDEX `ind_0a9c62bada8285ee17ef9797682903b07ca4a030`
> error during executing query:Error: ER_DROP_INDEX_FK: Cannot drop index 'ind_0a9c62bada8285ee17ef9797682903b07ca4a030': needed in a foreign key constraint
> query failed: ALTER TABLE `eligibility_category_race_meet_categories_race_meet_category_id` DROP INDEX `ind_f1657c8e87cc890a3f52cb47c29c9a4e8aed498b`
> error during executing query:Error: ER_DROP_INDEX_FK: Cannot drop index 'ind_f1657c8e87cc890a3f52cb47c29c9a4e8aed498b': needed in a foreign key constraint
> Error: ER_DROP_INDEX_FK: Cannot drop index 'ind_11586c7528252838835e9047458958c4429d0cdd': needed in a foreign key constraint
>     at Query.Sequence._packetToError (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
>     at Query.ErrorPacket (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
>     at Protocol._parsePacket (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/Protocol.js:280:23)
>     at Parser.write (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/Parser.js:74:12)
>     at Protocol.write (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/Connection.js:109:28)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:543:20)
>     --------------------
>     at Protocol._enqueue (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/protocol/Protocol.js:141:48)
>     at PoolConnection.query (/home/Documents/workspace/api.xxx/node_modules/mysql/lib/Connection.js:214:25)
>     at /home/Documents/workspace/api.xxx/src/driver/mysql/MysqlQueryRunner.ts:147:48
>     at MysqlQueryRunner.query (/home/Documents/workspace/api.xxx/src/driver/mysql/MysqlQueryRunner.ts:146:16)
>     at MysqlQueryRunner.<anonymous> (/home/Documents/workspace/api.xxx/src/driver/mysql/MysqlQueryRunner.ts:459:20)
>     at step (/home/Documents/workspace/api.xxx/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
>     at Object.next (/home/Documents/workspace/api.xxx/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
>     at /home/Documents/workspace/api.xxx/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:7:65
>     at __awaiter (/home/Documents/workspace/api.xxx/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:3:12)
>     at MysqlQueryRunner.dropIndex (/home/Documents/workspace/api.xxx/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:638:16)

**Comment by paistipoikka** [comment]
I dropped the schema and recreated a new empty schema. Restarted and TORM started up without an issue.
