### ISSUE TITLE
ColumnType Timestamp not supported by MySQL/MariaDB driver

### ISSUE THREAD

**Issue by cserron** [typeorm/typeorm#1134]
Inside [TypeORM's documentation](http://typeorm.io/#/entities/column-types) it says `timestamp` is one of the supported types for `mysql/mariadb`. Nevertheless, when I create a column of such type inside my entity, I get the following error:

```
executing query: ROLLBACK
{ DataTypeNotSupportedByDriverError: Specified type (timestamp) is not supported by MySQL/MariaDB driver.
    at DataTypeNotSupportedByDriverError.Error (native)
    at new DataTypeNotSupportedByDriverError (/api/src/driver/error/DataTypeNotSupportedByDriverError.ts:8:9)
    at MysqlQueryRunner.normalizeType (/api/src/driver/mysql/MysqlQueryRunner.ts:736:15)
    at /api/src/schema-builder/SchemaBuilder.ts:439:73
    at Array.map (native)
    at SchemaBuilder.metadataColumnsToColumnSchemas (/api/src/schema-builder/SchemaBuilder.ts:438:24)
    at SchemaBuilder.<anonymous> (/api/src/schema-builder/SchemaBuilder.ts:150:75)
    at step (/api/node_modules/typeorm/schema-builder/SchemaBuilder.js:32:23)
    at Object.next (/api/node_modules/typeorm/schema-builder/SchemaBuilder.js:13:53)
    at /api/node_modules/typeorm/schema-builder/SchemaBuilder.js:7:71
  name: 'DataTypeNotSupportedByDriverError',
  message: 'Specified type (timestamp) is not supported by MySQL/MariaDB driver.' }
```

This is how I'm creating my column inside the entity:

```
@Column('timestamp')
initTime: number;
```
Thanks.

**Comment by cserron** [comment]
You're absolutely right @pleerock, this was fixed in version `0.1.1`.
Closing this issue now.

Thanks.
