### ISSUE TITLE
run typeorm on node with sqlite3 installed as global

### ISSUE THREAD

**Issue by vecernik** [typeorm/typeorm#1136]
In my project all ts files gets compiled using webpack to a single es6 file (with all deps included using ts-loader). 
Otherwise I get following error 
```
  Error: { DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
      at new DriverPackageNotInstalledError (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:26060:28)
      at SqliteDriver.loadDependencies (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:119899:19)
      at new SqliteDriver (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:119825:15)
      at DriverFactory.create (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:177217:24)
      at new Connection (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:116877:59)
      at ConnectionManager.create (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:116777:26)
      at Object.<anonymous> (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:17558:70)
      at step (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:17383:23)
      at Object.next (/Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:17364:53)
      at /Volumes/Larder/Projects/tmp/rplayer-box.bundle.js:17358:71
```

Creating package.json with only sqlite3 and typeorm doesn't help.
Is there a way to force typeorm (PlatformTools) to use sqlite3 node module installed globally?

**Comment by daniel-lang** [comment]
This might be for a totally different reason. Right now, we assume you work on a web project when TypeORM is used with webpack. This is to ease web and mobile development. But in your case makes TypeORM unusable as Node.js `require` calls get "redirected/blocked".

Could you check your bundled file for a class called `PlatformTools` and see if it's `load()` method includes a `require` call or just the exception?

**Comment by pleerock** [comment]
@vecernik any updates on this issue?

**Comment by vecernik** [comment]
On the end, I can't use sqlite3. I intended to build a single runnable js file with dependencies for a server, but sqlite3 has a binary dependency, which complicated things a bit, so I replace that with MariaDB.

**Comment by pleerock** [comment]
Then I guess this can be closed. Let us know if you have something to add.
