### ISSUE TITLE
Can not be parsed correctly the URL of pg.

### ISSUE THREAD

**Issue by mingyang91** [typeorm/typeorm#114]
DATABASE_URL: postgres://username@ooo.xxx.com.cn:5432/database

```afterBase -> '/database1'``` **```preBase.substr(secondSlash) + 1 ```Here are some strange**
```afterBase.split("/")[0] -> ''``` **is correct?**

ERROR stack:
```
/Users/famer.me/Repository/vein/node_modules/typeorm/driver/postgres/PostgresDriver.js:70
            throw new DriverOptionNotSetError_1.DriverOptionNotSetError("database");
            ^
DriverOptionNotSetError: Driver option (database) is not set. Please set it to perform connection to the database.
    at new DriverOptionNotSetError (/Users/famer.me/Repository/vein/node_modules/typeorm/driver/error/DriverOptionNotSetError.js:13:28)
    at new PostgresDriver (/Users/famer.me/Repository/vein/node_modules/typeorm/driver/postgres/PostgresDriver.js:70:19)
    at ConnectionManager.createDriver (/Users/famer.me/Repository/vein/node_modules/typeorm/connection/ConnectionManager.js:361:24)
    at ConnectionManager.create (/Users/famer.me/Repository/vein/node_modules/typeorm/connection/ConnectionManager.js:94:27)
    at Object.<anonymous> (/Users/famer.me/Repository/vein/dist/entity/index.js:38:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
https://github.com/typeorm/typeorm/blob/master/src/driver/DriverUtils.ts#L67

**Comment by pleerock** [comment]
released in `0.0.6`
