### ISSUE TITLE
Many-to-many tags with unique tag string

### ISSUE THREAD

**Issue by Shplorf** [typeorm/typeorm#1162]
Hi, first of all this is a really awesome project, thanks for maintaining it!

I am trying to implement a test_case table where each test case can have tags. I want there to be a join table to maintain the relationship between test cases and tags, where multiple test cases point to a tag ID and then that ID is mapped to a name in the tag table. I want the tag names to be unique, and be able to update a tag's name so that all of the test cases that reference it point to the newly re-named tag.

So the way I tried to implement this is as follows:

```
@Entity()
export class TestCase {

  @PrimaryGeneratedColumn()
  public id: number;

  @ManyToMany(() => Tag, (tag: Tag) => tag.testCases, {
    cascadeInsert: true,
    cascadeUpdate: true,
  })
  public tags: Tag[];

}
```

```
@Entity()
export class Tag {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column('character varying', {
    unique: true,
  })
  public name: string;

  @ManyToMany(() => TestCase, (testCase: TestCase) => testCase.tags)
  @JoinTable()
  public testCases: TestCase[];
}
```

However if I then attempt to insert two test cases with the same tags, I get a "duplicate key value violates unique constraint" error. If I don't put the unique constraint there, I just get a bunch of tags with the same name but different IDs, which I don't want.

Am I missing something? Is there a way to make this work? Sorry if this is a stupid question, I spent a bunch of time looking at all of the examples and didn't come up with anything that worked. The SQL output for creating the two test cases with overlapping tags is below:
```
executing query:  START TRANSACTION
executing query:  INSERT INTO "test_case"("name", "description", "steps") VALUES ($1,$2,$3)  RETURNING "id" -- PARAMETERS: ["Test Case 1","Test 1 description","#1 Step 1 #2 Step 2"]
executing query:  INSERT INTO "tag"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["tag_a"]
executing query:  INSERT INTO "tag"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["tag_b"]
executing query:  INSERT INTO "tag_test_cases_test_case"("tagId", "testCaseId") VALUES ($1,$2)  -- PARAMETERS: [1,1]
executing query:  INSERT INTO "tag_test_cases_test_case"("tagId", "testCaseId") VALUES ($1,$2)  -- PARAMETERS: [2,1]
executing query:  COMMIT
executing query:  START TRANSACTION
executing query:  INSERT INTO "test_case"("name", "description", "steps", "cohort") VALUES ($1,$2,$3,$4)  RETURNING "id" -- PARAMETERS: ["Test Case 2","Test 2 description","#1 Step 1 #2 Step 2 #3 Step 3","default"]
executing query:  INSERT INTO "tag"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["tag_b"]
executing query:  INSERT INTO "tag"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["tag_c"]
query failed:  INSERT INTO "tag"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["tag_b"]
error:  { error: duplicate key value violates unique constraint "uk_tag_name"
```

**Comment by pleerock** [comment]
I guess this is problem with cascades we have. Can you please try to install `next` version and reproduce this issue there, `npm i typeorm@next` - lot of cascades issues were fixed there.

**Comment by Shplorf** [comment]
Still seeing the same behavior on 0.2.0-alpha.6

**Comment by pleerock** [comment]
can you post logs on `0.2.0-alpha.6` ? It must be different. Also send me a code which does actual saving (minimal issue reproduction code)

**Comment by Shplorf** [comment]
Sure thing. I'm using the latest Postgres. Logs from 0.2.0-alpha.6:
```sql
executing query: START TRANSACTION
executing query: SELECT * FROM current_schema()
executing query: SELECT * FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'tag' OR table_schema = 'public' AND table_name = 'test_case' OR table_schema = 'public' AND table_name = 'tag_test_cases_test_case'
executing query: SELECT * FROM information_schema.columns WHERE table_schema IN ('public')
executing query: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name, ix.indisunique AS is_unique, a.attnum, ix.indkey FROM pg_class t, pg_class i, pg_index ix, pg_attribute a, pg_namespace ns
WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ('tag', 'test_case', 'tag_test_cases_test_case') AND t.relnamespace = ns.OID AND ns.nspname IN ('public') ORDER BY t.relname, i.relname
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_schema IN ('public') AND constraint_type = 'FOREIGN KEY'
executing query: SELECT * FROM information_schema.table_constraints WHERE table_schema IN ('public') AND constraint_type = 'UNIQUE'
executing query: SELECT c.column_name, tc.table_name, tc.constraint_name FROM information_schema.table_constraints tc
JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name)
JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema AND tc.table_name = c.table_name AND ccu.column_name = c.column_name
where constraint_type = 'PRIMARY KEY' AND c.table_schema IN ('public')
executing query: CREATE TABLE "tag" ("id" SERIAL NOT NULL, "name" character varying(256) NOT NULL, CONSTRAINT "uk_tag_name" UNIQUE ("name"), PRIMARY KEY("id"))
executing query: CREATE TABLE "test_case" ("id" SERIAL NOT NULL, "name" character varying(256) NOT NULL, "description" character varying, "steps" character varying NOT NULL, "cohort" character varying(64), "epic" character varying(32), "story" character varying(32), PRIMARY KEY("id"))
executing query: CREATE TABLE "tag_test_cases_test_case" ("tagId" integer NOT NULL, "testCaseId" integer NOT NULL, PRIMARY KEY("tagId", "testCaseId"))
executing query: CREATE INDEX "ind_203b3074cf9b84867e6e5935ef" ON "tag_test_cases_test_case"("tagId")
executing query: CREATE INDEX "ind_5b1ab51b90e6f015cf6e0e5b4d" ON "tag_test_cases_test_case"("testCaseId")
executing query: ALTER TABLE "tag_test_cases_test_case" ADD CONSTRAINT "fk_b887d2c4a0fb610ca07893ab8e7" FOREIGN KEY ("tagId") REFERENCES "tag"("id")
executing query: ALTER TABLE "tag_test_cases_test_case" ADD CONSTRAINT "fk_57c71494bb486481d2fe7efc17f" FOREIGN KEY ("testCaseId") REFERENCES "test_case"("id")
executing query: COMMIT
executing query: START TRANSACTION
executing query: INSERT INTO "test_case"("name", "description", "steps", "cohort", "epic", "story") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT) RETURNING "id" -- PARAMETERS: ["Test Case 1","Test 1 description","#1 Step 1 #2 Step 2"]
executing query: INSERT INTO "tag"("name") VALUES ($1), ($2) RETURNING "id" -- PARAMETERS: ["tag_a","tag_b"]
executing query: INSERT INTO "tag_test_cases_test_case"("tagId", "testCaseId") VALUES ($1, $2), ($3, $4) -- PARAMETERS: [1,1,2,1]
executing query: COMMIT
executing query: START TRANSACTION
executing query: INSERT INTO "test_case"("name", "description", "steps", "cohort", "epic", "story") VALUES ($1, $2, $3, $4, DEFAULT, DEFAULT) RETURNING "id" -- PARAMETERS: ["Test Case 2","Test 2 description","#1 Step 1 #2 Step 2 #3 Step 3","default"]
executing query: INSERT INTO "tag"("name") VALUES ($1), ($2) RETURNING "id" -- PARAMETERS: ["tag_b","tag_c"]
query failed: INSERT INTO "tag"("name") VALUES ($1), ($2) RETURNING "id" -- PARAMETERS: ["tag_b","tag_c"]
error: { error: duplicate key value violates unique constraint "uk_tag_name"
    at Connection.parseE (/Users/greg.malkov/trinetx/test-case-mgmt/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/greg.malkov/trinetx/test-case-mgmt/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/greg.malkov/trinetx/test-case-mgmt/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 186,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (name)=(tag_b) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'tag',
  column: undefined,
  dataType: undefined,
  constraint: 'uk_tag_name',
  file: 'nbtinsert.c',
  line: '434',
  routine: '_bt_check_unique' }
executing query: ROLLBACK
```

Reproduction code:
```typescript
// tslint:disable-next-line
import 'reflect-metadata';
import {createKoaServer, Delete, Get, JsonController, Param, Post, Put} from 'routing-controllers';
import {Column, createConnection, DeleteResult, Entity, getConnectionManager, JoinTable, ManyToMany,
  PrimaryGeneratedColumn, Repository} from 'typeorm';
import {EntityFromBody} from 'typeorm-routing-controllers-extensions';

@Entity()
class Tag {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column('character varying', {
    length: 256,
    unique: true,
  })
  public name: string;

  @ManyToMany(() => TestCase, (testCase: TestCase) => testCase.tags)
  @JoinTable()
  public testCases: TestCase[];
}

@Entity()
class TestCase {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column('character varying', {
    length: 256,
  })
  public name: string;

  @Column('character varying', {
    nullable: true,
  })
  public description: string;

  @Column('character varying')
  public steps: string;

  @Column('character varying', {
    length: 64,
    nullable: true,
  })
  public cohort: string;

  @Column('character varying', {
    length: 32,
    nullable: true,
  })
  public epic: string;

  @Column('character varying', {
    length: 32,
    nullable: true,
  })
  public story: string;

  @ManyToMany(() => Tag, (tag: Tag) => tag.testCases, {
    cascadeInsert: true,
    cascadeUpdate: true,
  })
  public tags: Tag[];
}

@JsonController()
class TestCaseController {

  private testCaseRepository: Repository<TestCase>;

  constructor() {
    this.testCaseRepository = getConnectionManager().get().getRepository(TestCase);
  }

  @Get('/testCases')
  public getAll() {
    return this.testCaseRepository.find({relations: ['tags']});
  }

  @Get('/testCases/:id')
  public getOne(@Param('id') id: number) {
    return this.testCaseRepository.find({where: {id: id}, relations: ['tags']});
  }

  @Post('/testCases')
  public save(@EntityFromBody() testCase: TestCase) {
    return this.testCaseRepository.save(testCase);
  }

  @Put('/testCases/:id')
  public async put(@Param('id') id: number, @EntityFromBody() testCase: TestCase) {
    await this.testCaseRepository.update(id, testCase);

    return this.testCaseRepository.find({where: {id: id}, relations: ['tags']});
  }

  @Delete('/testCases/:id')
  public remove(@Param('id') id: number): Promise<DeleteResult> {
    return this.testCaseRepository.delete(id);
  }

}

createConnection({
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'password',
  database: 'postgres',
  entities: [
    Tag,
    TestCase,
  ],
  synchronize: true,
  logging: true,
}).then(() => {

  createKoaServer({
    controllers: [TestCaseController],
  }).listen(3000);

// tslint:disable-next-line
}).catch(error => console.log(error));
```

API calls:
```bash
curl -X POST \
  http://localhost:3000/testCases \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 6ff390cf-b608-acbd-d569-3dd53265047f' \
  -d '{
  "name": "Test Case 1",
  "description": "Test 1 description",
  "steps": "#1 Step 1 #2 Step 2",
  "tags": [{"name": "tag_a"}, {"name": "tag_b"}]
}'
```
```bash
curl -X POST \
  http://localhost:3000/testCases \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 032cc3b0-83be-4717-e238-41c399f87e56' \
  -d '{
  "name": "Test Case 2",
  "description": "Test 2 description",
  "steps": "#1 Step 1 #2 Step 2 #3 Step 3",
  "cohort": "default",
  "tags": [{"name": "tag_b"}, {"name": "tag_c"}]
}'
```

**Comment by pleerock** [comment]
Okay, so everything looks correct. You have this error only on a second request because when you send:

```json
{
  "name": "Test Case 2",
  "description": "Test 2 description",
  "steps": "#1 Step 1 #2 Step 2 #3 Step 3",
  "cohort": "default",
  "tags": [{"name": "tag_b"}, {"name": "tag_c"}]
}
```

It tries to insert two new tags: {"name": "tag_b"} and {"name": "tag_c"}. And since you already have tags with such names in the database it gives you error that unique constraint violated.

Why it tries to insert? Because cascades are set. Why it tries to insert instead of performing updation? Because the only criteria for updation are primary keys, so you need to pass primary keys within your tags, e.g. `{"id": 2, "name": "tag_b"}, {"id": 3, "name": "tag_c"}`.

You can even strip "name" from sent objects if you don't want to update them (orm will update if you pass id and change name since cascade updates are set).

What alternative solution you have? You can make name column primary and don't use auto-increment primary column.

**Comment by Shplorf** [comment]
Ah yes that explains it. Works after updating the controller code to the following:

```typescript
@Post('/testCases')
  public async save(@Body() testCases: TestCase[]) {
    try {
        for ( let testCase of testCases ) {
          for (const index of testCase.tags.keys()) {
            const tag: Tag = await this.tagRepository.findOne({name: testCase.tags[index].name});
            if (tag !== undefined) {
              testCase.tags[index] = tag;
            }
          }

          testCase = await this.testCaseRepository.save(testCase);
        }

      return testCases;
    } catch (e) {
      throw new BadRequestError(e.message);
    }
  }
```

Thanks for taking the time to look at this and thanks again for maintaining this great project!

**Comment by JohnnyB9991** [comment]
This solution doesn't work when using save on arrays with overlapping tags - like when you want to save two new objects that both have the same new.
Any ideas how to solve this?
