### ISSUE TITLE
[question] Transactional test case with repositories

### ISSUE THREAD

**Issue by szkumorowski** [typeorm/typeorm#1204]
What is a right way of implementing the e2e tests ?

In current solution I test database in mysql server - this allow me to test exactly the same state of database as in usuall way with enviroments and migrations. I tried to use sqlite as in memory database - but it fails due to differences in sql syntax.

In application I'm using repositories with `connection.getRepository(entityClass)`

Actually I want to achive the reset of database state per each test case. Is there any confirmed solution which will work or a right way of doing it ?

With this solution internal transaction used by repository is finally committed.

The test case looks:

`
import "mocha";
import * as request from 'supertest';
import {getConnection} from "typeorm";

describe('ControllerE2E', function () {

    const server;// server initialization where connection is bootstrapped
    
    beforeEach(async () => {

        this.connection = getConnection();
        this.queryRunner = this.connection.driver.createQueryRunner("master");
        await this.queryRunner.startTransaction();

    });

    afterEach(async () => {
        await this.queryRunner.rollbackTransaction();
        await this.queryRunner.release();
    });

    it(`return 200`, async () => {

        const entityRepository = this.connection.getRepository(Entity);
        const entity = new Entity();

        Object.assign(entity, {
            value1: 1,
            value2: '2',
            value3: '3'
        });

        await entityRepository.save(entity);

        return request(server)
            .post('/api/endpoint')
            .expect(200)
        
});
`

**Comment by pleerock** [comment]
complete testing strategy and guidelines are not implemented yet, however I recommend you to use separate connection with separate database and clear database after each test run,  something like this:

```ts
import "mocha";
import * as request from 'supertest';
import {getConnection} from "typeorm";

describe('ControllerE2E', function () {

    const server; /* server initialization where connection is bootstrapped */
    
    beforeEach(async () => {
        this.connection = createConnection({ separate configuration for testing });
    });

    afterEach(async () => {
        await this.connection.clearDatabase();
    });

    it(`return 200`, async () => {

        const entityRepository = this.connection.getRepository(Entity);
        const entity = new Entity();

        Object.assign(entity, {
            value1: 1,
            value2: '2',
            value3: '3'
        });

        await entityRepository.save(entity);

        return request(server)
            .post('/api/endpoint')
            .expect(200)
        
});
```

**Comment by ilvsx** [comment]
@pleerock

run the test will return:

`  2) "after each" hook for "return 200":
     TypeError: this.connection.clearDatabase is not a function
      at Object.<anonymous> (src/test/test.ts:24:27)
      at Generator.next (<anonymous>)
      at src/test/test.ts:7:71
      at new Promise (<anonymous>)
      at __awaiter (src/test/test.ts:3:12)
      at Context.afterEach (src/test/test.ts:21:17)`

**Comment by pleerock** [comment]
@ilvsx sorry its called `dropDatabase`

**Comment by ilvsx** [comment]
@pleerock  Thanks, My mistake

**Comment by szkumorowski** [comment]
@pleerock 
Do you think is somehow possible to run each test in transaction now ?
Mostly I mean the way how I described it in similar other topic: https://github.com/typeorm/typeorm/issues/1267#issuecomment-377047784

**Comment by Kurry** [comment]
@pleerock can you add an example for a `POST` test? and how you would think about the app connection and the test connection, to validate the new resource was created.
