### ISSUE TITLE
0.1.6 migration:generate fails trying to remove index of manytomany

### ISSUE THREAD

**Issue by MrGekko** [typeorm/typeorm#1251]
When I try to generate a migration it tries to remove indexes.
```
typeorm migrations:generate -n test
Error during migration generation:
{ QueryFailedError: ER_DROP_INDEX_FK: Cannot drop index 'ind_2fc849c21c29db9e04511a210d': needed in a foreign key constraint
    at new QueryFailedError (/usr/local/lib/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query._callback (/usr/local/lib/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:207:45)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sqlMessage: 'Cannot drop index \'ind_2fc849c21c29db9e04511a210d\': needed in a foreign key constraint',
  sqlState: 'HY000',
  index: 0,
  sql: 'ALTER TABLE `user_groups_group` DROP INDEX `ind_2fc849c21c29db9e04511a210d`',
  name: 'QueryFailedError',
  query: 'ALTER TABLE `user_groups_group` DROP INDEX `ind_2fc849c21c29db9e04511a210d`',
  parameters: [] }
```
There are no issues on 1.5. Even when I have the server on 1.6 but cli on 1.5.
This only happens with cli on 1.6.

**Comment by pleerock** [comment]
It should not be related to 0.1.5 or 0.1.6 since we didn't make any changes there. Can you investigate your problem further and find a reason why it does so?

**Comment by MrGekko** [comment]
I have been trying to find the source of the error. But I cant find it. I'll try again with 0.2
