### ISSUE TITLE
How to specify reflect-metadata?

### ISSUE THREAD

**Issue by seanchenca** [typeorm/typeorm#1284]
I have two one-to-one relation classes:

```
@Entity('presentationimage')
class PresentationImage extends EntBase {

  @Column({ type: 'varchar', length: 128 })
  image: string

  @OneToOne(type => PresentationImagePopup)
  @JoinColumn()
  popup: PresentationImagePopup
}

@Entity('popupimage')
class PresentationImagePopup extends EntBase {

  @Column({ type: 'varchar', length: 128 })
  image: string

  @OneToOne(type => PresentationImage)
  presentationImage: PresentationImage
}
```
when I use the following query to load PresentationImagePopup:
```
  getConnection()
    .createQueryBuilder()
    .relation(PresentationImagePopup, 'presentationImage')
    .loadMany();
```
I got:
```
TypeError: Cannot read property 'entityMetadata' of undefined
[Node]     at RelationLoader.loadOneToManyOrOneToOneNotOwner (/Users/sean/PG/Apps/DVA/backend-node/node_modules/typeorm/query-builder/RelationLoader.js:70:43)
at RelationLoader.load (/Users/sean/PG/Apps/DVA/backend-node/node_modules/typeorm/query-builder/RelationLoader.js:25:25)
[Node]     at RelationQueryBuilder.<anonymous> (/Users/sean/PG/Apps/DVA/backend-node/node_modules/typeorm/query-builder/RelationQueryBuilder.js:207:54)
[Node]     at step (/Users/sean/PG/Apps/DVA/backend-node/node_modules/typeorm/query-builder/RelationQueryBuilder.js:42:23)
...
```
I guess the problem is that I haven't specify reflect-metadata properly, but not sure how do I do that? I have already set:
```
    "emitDecoratorMetadata": true,
```
in my` tsconfig.json`. could anybody shed some light on this?

**Comment by pleerock** [comment]
no, your problem is that you did not specify inverse relation of your "presentationImage" property. Change code to:

```ts
@Entity('presentationimage')
class PresentationImage extends EntBase {

  @Column({ type: 'varchar', length: 128 })
  image: string

  @OneToOne(type => PresentationImagePopup, popup => popup.presentationImage)  // add this
  @JoinColumn()
  popup: PresentationImagePopup
}

@Entity('popupimage')
class PresentationImagePopup extends EntBase {

  @Column({ type: 'varchar', length: 128 })
  image: string

  @OneToOne(type => PresentationImage, image => image.popup) // add this
  presentationImage: PresentationImage
}
```

**Comment by seanchenca** [comment]
thanks for the quick response @pleerock, much appreciated, after adding the inverse relation it works now, however I have to change my query to:

```
  getRepository(PresentationImagePopup)
    .createQueryBuilder('imagePopup')
    .leftJoinAndSelect('imagePopup.presentationImage',
                       'prImage')
    .getMany()
    .then(imagePopups => {
      // here imagePopup is correctly populated
    });
```
if I use the original query I posted above:
```
  getConnection()
    .createQueryBuilder()
    .relation(PresentationImagePopup, 'presentationImage')
    .loadMany()
    .then(imagePopups => {
      // here imagePopup is null
    });
```
no record is return. Is there something wrong with this query or this is just not the correct query to use? what's the essential different between these two query? Is there a rule of thumb which query should be preferable in certain scenario?

**Comment by pleerock** [comment]
You need to specify of which object you are loading relation using `of` method. See [examples here.](https://github.com/pleerock/typeorm/blob/44af27ffdb0e79872025adb8282e97b8da3e7f29/test/functional/query-builder/relational/with-many/query-builder-relational-load-many.ts)

**Comment by seanchenca** [comment]
I see, so `relation()` is to be used with `of()` to populate the related property. Thanks for the explanation.
