### ISSUE TITLE
Reuse existing connection instead of creating new / typeorm/commands API from node

### ISSUE THREAD

**Issue by unlight** [typeorm/typeorm#1304]
And I'm trying to use typeorm/commands API. For example:
```ts
import { MigrationGenerateCommand } from 'typeorm/commands/MigrationGenerateCommand';

async run(argv: Arguments) {
    const command = new MigrationGenerateCommand();
    const options = { dir: config.databaseMigrations };
    await command.handler(options);
}

run();
```
Throws error:
```
 Error
    at new AlreadyHasActiveConnectionError (D:\My\Dev\nest-typescript-starter\src\error\AlreadyHasActiveConnectionError.ts:11:22)
    at ConnectionManager.create (D:\My\Dev\nest-typescript-starter\src\connection\ConnectionManager.ts:57:23)
    at Object.<anonymous> (D:\My\Dev\nest-typescript-starter\src\index.ts:186:35)
    at step (D:\My\Dev\nest-typescript-starter\node_modules\typeorm\index.js:32:23)
    at Object.next (D:\My\Dev\nest-typescript-starter\node_modules\typeorm\index.js:13:53)
    at D:\My\Dev\nest-typescript-starter\node_modules\typeorm\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\My\Dev\nest-typescript-starter\node_modules\typeorm\index.js:3:12)
    at Object.createConnection (D:\My\Dev\nest-typescript-starter\node_modules\typeorm\index.js:198:12)
    at MigrationGenerateCommand.<anonymous> (D:\My\Dev\nest-typescript-starter\src\commands\MigrationGenerateCommand.ts:63:32)
  name: 'AlreadyHasActiveConnectionError',
  message: 'Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.' }
```
```
typeorm@0.1.7
node v8.9.0 Win8.1
```

**Comment by pleerock** [comment]
I don't think you should use command for this purpose. Solution to your problem is to refactor command and extract its code generation logic into separate class and use it it command (send connection instance via command) and you can use this class in your app and send your connection instance into it.

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.
