### ISSUE TITLE
Cannot use concrete table inheritance following the example https://typeorm.github.io/tables-and-columns.html#table-inheritance

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#136]
Trying to follow: https://typeorm.github.io/tables-and-columns.html#table-inheritance

```typescript
@AbstractTable()
export class BaseEntry {
    @PrimaryGeneratedColumn() id: number
    @Column({type: "decimal", precision: 2, nullable: false}) val: Number
}

@Table()
export class TestEntry extends BaseEntry {
    @Column() foo: Number
}
```
gives the following error:
```
 MissingPrimaryColumnError: Entity "TestEntry" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
    at MissingPrimaryColumnError.Error (native)
    at new MissingPrimaryColumnError (/Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/error/MissingPrimaryColumnError.js:12:28)
    at EntityMetadataValidator.validate (/Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:36:19)
    at /Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:27:74
    at Array.forEach (native)
    at EntityMetadataValidator.validateMany (/Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:27:25)
    at EntityMetadataBuilder.build (/Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:388:85)
    at EntityMetadataBuilder.buildFromMetadataArgsStorage (/Users/max/development/macrofit/backend/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:151:21)
    at Connection.buildMetadatas (/Users/max/development/macrofit/backend/node_modules/typeorm/connection/Connection.js:484:18)
    at Connection.<anonymous> (/Users/max/development/macrofit/backend/node_modules/typeorm/connection/Connection.js:163:30)
  name: 'MissingPrimaryColumnError',
  message: 'Entity "TestEntry" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.' }
```

And potentially helpful debugging info:
![image](https://cloud.githubusercontent.com/assets/646732/21327952/66ad97e2-c5e6-11e6-8363-68bed0040045.png)

**Comment by pleerock** [comment]
hmmm it should work, I personally use it everyday.

**Comment by pleerock** [comment]
what is your node version?

**Comment by maxcan** [comment]
6.2.2

**Comment by maxcan** [comment]
I'll experiment with other node versions and let you know

**Comment by maxcan** [comment]
same behavior on 7.2.1

**Comment by maxcan** [comment]
I'm on sqlite, but I can't imagine that that is the cause.  also, typescript 2.1.4

**Comment by maxcan** [comment]
@pleerock figured it out.. I needed to include the abstract table `BaseEntry` in the `entities` field of the connection options which I wasn't doing.  

Thanks! by the way, i love the library.  Good work.

Max
