### ISSUE TITLE
createConnection does not register connection with ConnectionManager

### ISSUE THREAD

**Issue by johnbendi** [typeorm/typeorm#146]
I have tried calling `createConnection` but when I call `getConnectionManager().get()` it returns connection not found. And the doc says that `ConnectionManager` is a singleton.

Also it would be good if you can write a sample of how to use typeorm in a real application.

**Comment by eduardoweiland** [comment]
@johnbendi Are you waiting for the `createConnection()` promise to resolve before calling `getConnectionManager().get()`? I use this in my app and it should be working.

**Comment by johnbendi** [comment]
@eduardoweiland please as an aside what tsconfig setting are you using for server side development and with what node version. I am suddenly getting a 
```
(function (exports, require, module, __filename, __dirname) { import {
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at allFiles.filter.map.file (/home/johnbendi/projects/f1town/f1town-backend-typescript/node_modules/typeorm/util/DirectoryExportedClassesLoader.js:27:22)
    at Array.map (native)
```
 I have tried almost every tsconfig setting I can find I still keep getting this error.

**Comment by pleerock** [comment]
Use `"target": es5`. it works with node 4+. If you have latest versions of node you can use `"target": es6` with `"module": "commonjs"` for example. Checkout [typescript-example](https://github.com/typeorm/typescript-example)

**Comment by johnbendi** [comment]
@pleerock thanks for the `typescript-example` you linked to. I was able to also solve another issue I opened. I think I can close this now.
