### ISSUE TITLE
TypeError: Cannot read property 'isReleased' of undefined

### ISSUE THREAD

**Issue by jwaldrip** [typeorm/typeorm#1481]
I am getting the following error when trying to run migrations. Is there an error in the pg driver?

```
$ typeorm migrations:run
0 migrations are already loaded in the database.
11 migrations were found in the source code.
11 migrations are new migrations that needs to be executed.
Error during migration run:
TypeError: Cannot read property 'isReleased' of undefined
    at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:193:18)
    at EnableUUIDExtension1516245488433.up (/app/build/db/migrations/1516245488433-EnableUUIDExtension.js:5:9)
    at /app/node_modules/typeorm/migration/MigrationExecutor.js:112:59
    at /app/node_modules/typeorm/util/PromiseUtils.js:17:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is my migration:

```typescript
import {MigrationInterface, QueryRunner} from "typeorm";

export class EnableUUIDExtension1516245488433 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<any> {
		await queryRunner.query(`
			CREATE EXTENSION "uuid-ossp";
		`);
	}

	public async down(queryRunner: QueryRunner): Promise<any> {
		await queryRunner.query(`
			DROP EXTENSION "uuid-ossp";
		`);
	}
}
```

**Comment by pleerock** [comment]
I just checked it and it works fine. Are you able to create a minimal reproduction git repo for this issue?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
