### ISSUE TITLE
TypeError: Cannot read property 'columns' of undefined

### ISSUE THREAD

**Issue by errorx666** [typeorm/typeorm#158]
I'm getting an error in https://github.com/typeorm/typeorm/blob/08634b5c083bc76b38617109914b5db6f0d1bec3/src/repository/SpecificRepository.ts.

```ts
    /**
     * Finds all relation ids in the given entities.
     */
    async findRelationIds(relationOrName: RelationMetadata|string|((...args: any[]) => any), entityOrEntities: Entity[]|Entity|any|any[], inIds?: any[], notInIds?: any[]): Promise<any[]> {

        const relation = this.convertMixedRelationToMetadata(relationOrName);
        if (!(entityOrEntities instanceof Array)) entityOrEntities = [entityOrEntities];

        const entityReferencedColumn = relation.isOwning ? relation.joinTable.referencedColumn : relation.inverseRelation.joinTable.inverseReferencedColumn;
        const ownerEntityColumn = relation.isOwning ? relation.junctionEntityMetadata.columns[0] : relation.junctionEntityMetadata.columns[1];
        const inverseEntityColumn = relation.isOwning ? relation.junctionEntityMetadata.columns[1] : relation.junctionEntityMetadata.columns[0];
```

`relation.junctionEntityMetadata` is undefined, and throws an Error.

![image](https://cloud.githubusercontent.com/assets/1048542/21550700/9a3afac2-cdc1-11e6-9b21-479322b6b252.png)

```
TypeError: Cannot read property 'columns' of undefined
    at SpecificRepository.<anonymous> (C:\Users\error\Documents\src\working\r3\src\repository\SpecificRepository.ts:438:131)
    at step (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\repository\SpecificRepository.js:32:23)
    at Object.next (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\repository\SpecificRepository.js:13:53)
    at C:\Users\error\Documents\src\working\r3\node_modules\typeorm\repository\SpecificRepository.js:7:65
    at __awaiter (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\repository\SpecificRepository.js:3:12)
    at SpecificRepository.findRelationIds (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\repository\SpecificRepository.js:430:16)
    at SubjectBuilder.<anonymous> (C:\Users\error\Documents\src\working\r3\src\persistence\SubjectBuilder.ts:733:26)
    at step (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\persistence\SubjectBuilder.js:32:23)
    at Object.next (C:\Users\error\Documents\src\working\r3\node_modules\typeorm\persistence\SubjectBuilder.js:13:53)
    at C:\Users\error\Documents\src\working\r3\node_modules\typeorm\persistence\SubjectBuilder.js:7:65
```

My entity class is here: https://github.com/errorx666/r3/blob/wip/server/ts/entities/session.ts

**Comment by pleerock** [comment]
Please provide a minimal reproduction code, e.g. how do you use this method with your model, so I can test it.

**Comment by errorx666** [comment]
I was missing the second parameter to my `ManyToMany` decorator.  My fault, but I would expect this to throw a much less cryptic error and sooner.
