### ISSUE TITLE
Postgres: QueryBuilder insert array type bug

### ISSUE THREAD

**Issue by gutenye** [typeorm/typeorm#1600]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given

```ts
@Entity()
class Post extends BaseEntity {
  @Column()
  title: string

  @Column('text', { isArray: true })
  tags: string[]
}

Post.createQueryBuilder()
  .insert()
  .values([
    { title: 'title', tags: [ 'a', 'b' ] }
  ])
 .execute()
```

Got

```
query failed:  INSERT INTO "post"("title","tags") VALUES ($1) -- PARAMETERS: ["title","a","b"]
error:  { error: INSERT has more expressions than target columns
    at Connection.parseE (/Users/guten/env/learn/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/guten/env/learn/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/guten/env/learn/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 115,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '97',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'analyze.c',
  line: '921',
  routine: 'transformInsertRow' }
```

**Comment by pleerock** [comment]
Fix for this issue will bring a breaking things, so it will be resolved in 0.2.0

**Comment by pleerock** [comment]
Was fixed in `0.2.0-alpha.19`. You can install next version by running `npm i typeorm@next`.

**Comment by Akmaljon571** [comment]
Enitity.query('INSERT INTO table(name, arr) values( $1, $2 )', [ 'jon', [ 'a', 'b' ] ]);
