### ISSUE TITLE
Typescript error: 'order' does not exists in type 'DeepPartial<>'

### ISSUE THREAD

**Issue by mjarmoc** [typeorm/typeorm#1603]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12` 

I have a method: 

```
public async readManyForEvent(eventId: number, amount: number, page: number, isPublic?: boolean): Promise<Moment[] | undefined> {
    return this.momentRepository.find({
      where: {
        eventId: eventId,
        active: true,
        public: isPublic
      },
      order: {
        'createdAt': 'asc'
      },
      take: amount,
      skip: page * amount
    });
  }
```
which is correctly build based on docs. During compillation, I get an error: 
```
Argument of type '{ where: { eventId: number; active: boolean; public: boolean | undefined; }; order: { 'createdAt'...' is not assignable to parameter of type 'DeepPartial<Moment> | undefined'.
  Object literal may only specify known properties, and 'where' does not exist in type 'DeepPartial<Moment> | undefined'. (2345)
    at getOutput (F:\snapParty\api\node_modules\ts-node\src\index.ts:307:15)
    at F:\snapParty\api\node_modules\ts-node\src\index.ts:336:16
    at Object.compile (F:\snapParty\api\node_modules\ts-node\src\index.ts:498:11)
    at Module.m._compile (F:\snapParty\api\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (F:\snapParty\api\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
```

**Comment by mjarmoc** [comment]
My mistake, order options is case sensitive, so ASC is working.
