### ISSUE TITLE
Sqlite in-memory database support

### ISSUE THREAD

**Issue by yhpark** [typeorm/typeorm#1604]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Setting the sqlite ormconfig `{ database: ':memory:' }` does not work as intended, as it gets converted to `(full path to working directory)/:memory:`.

This issue had already been brought up #1381 but later he closed the issue saying it's already supported, but I don't see how. Is there a way to make it work?

**Comment by pleerock** [comment]
just checked it on both latest and next, works as expected. Can you check once again? Maybe something your environment-specific? This issue needs more info.

**Comment by amitport** [comment]
possibly related, for me running `typeorm init --name MyProject --database sqlite` produces
```
{ EntityMetadataNotFound: No metadata for "User" was found.
    at new EntityMetadataNotFound (..\packages\MyProject\src\error\EntityMetadataNotFound.ts:7:9)
    at Connection.getMetadata (..\packages\MyProject\src\connection\Connection.ts:297:19)
    at EntityManager.<anonymous> (..\packages\MyProject\src\entity-manager\EntityManager.ts:310:54)
    at step (..\packages\MyProject\node_modules\typeorm\entity-manager\EntityManager.js:32:23)
    at Object.next (..\packages\MyProject\node_modules\typeorm\entity-manager\EntityManager.js:13:53)
    at ..\packages\MyProject\node_modules\typeorm\entity-manager\EntityManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (..\packages\MyProject\node_modules\typeorm\entity-manager\EntityManager.js:3:12)
    at ..\packages\MyProject\src\entity-manager\EntityManager.ts:280:39
    at <anonymous>
  name: 'EntityMetadataNotFound',
  message: 'No metadata for "User" was found.' }
```

**Comment by yhpark** [comment]
This issue is caused from `ConnectionOptionsReader` so it only occurs when reading a config from `ormconfig.js` file. Directly giving the config object into `createConnection` would work fine. I believe @amitport's issue is also related..
