### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by proprogrammer2015** [typeorm/typeorm#1632]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Link to the repository with issue replication code: [https://github.com/proprogrammer2015/example-of-typeorm-custom-repository-error](https://github.com/proprogrammer2015/example-of-typeorm-custom-repository-error)

Funny thing is that when I rollback commented out code in TypeConnectionManager.ts, all tests pass.

I have created custom repository and I have tested it out, but while running unit tests following issue is thrown:
```
/home/twz/projects/example-of-typeorm-custom-repository-error/node_modules/typeorm/entity-manager/MongoEntityManager.js:7
        extendStatics(d, b);
        ^

TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (/home/twz/projects/example-of-typeorm-custom-repository-error/node_modules/typeorm/entity-manager/MongoEntityManager.js:7:9)
    at /home/twz/projects/example-of-typeorm-custom-repository-error/src/entity-manager/MongoEntityManager.ts:52:41
    at Object.<anonymous> (/home/twz/projects/example-of-typeorm-custom-repository-error/src/entity-manager/MongoEntityManager.ts:52:1)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at extensions.(anonymous function) (/home/twz/projects/example-of-typeorm-custom-repository-error/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/twz/projects/example-of-typeorm-custom-repository-error/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/twz/projects/example-of-typeorm-custom-repository-error/src/connection/Connection.ts:18:1)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)

  1 exception

  ✖ TypeConnectionManager.test.js exited with a non-zero exit code: 1
```

**Comment by proprogrammer2015** [comment]
Update: Moving entity (Type.ts) import before EntityManger import resolves the issue. (Repository with example code is updated accordingly)

So having following import order throws error:

`
import { EntityManager } from 'typeorm/entity-manager/EntityManager';
import { Type } from './Type';
`

Below one, complishes with success:

`
import { Type } from './Type';
import { EntityManager } from 'typeorm/entity-manager/EntityManager';
`
Please investigate why import order has significant impact in this case.

**Comment by pleerock** [comment]
I'll need a minimal reproduction git repo to check this problem, I have never faced such issue.

**Comment by proprogrammer2015** [comment]
Sure, on this repo is fully reproducible:  https://github.com/proprogrammer2015/example-of-typeorm-custom-repository-error

**Comment by pleerock** [comment]
I don't see a clear way how to reproduce your issue. I run `npm test` but all tests are passing.

**Comment by proprogrammer2015** [comment]
Try to move Type import after EntityManager import

**Comment by pleerock** [comment]
If you import it this (proper) way:

```ts
import { EntityManager } from 'typeorm';
```

issue will be fixed.

**Comment by proprogrammer2015** [comment]
You are right. This is the proper way of doing an import. My IDE (vs code) tried to be smarter ;)

Thanks a lot for help!

**Comment by pongsak8832** [comment]
test
