### ISSUE TITLE
select() error occured when without registring entity...

### ISSUE THREAD

**Issue by yunseop-kim** [typeorm/typeorm#1634]
**Issue type:**

[v] question
[v] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[v] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[v] `0.1.10` (or put your version here)

Hello. I have a question.

I want to query the following without registering Entity.

The following code snippet shows the expected results for the first request, after which a QueryFailedError is raised and no results are returned.

This is considered an error in the from () method.

```typescript
getManager().createQueryBuilder()
  .select()
  .from("msg_queue", "q")
  .where("q.mseq = :objectId", { objectId })
  .getRawOne();
```

The logs are:

```
// this is first request...
executing query:  SELECT * FROM `msg_queue` `q` WHERE q.mseq = ? -- PARAMETERS: ["10"]
GET /api/text/10 200 55.288 ms - 1315

// this is the second request. and subsequent requests have the same error occured.
executing query:  SELECT * FROM  WHERE q.mseq = ? -- PARAMETERS: ["10"]
query failed:  SELECT * FROM  WHERE q.mseq = ? -- PARAMETERS: ["10"]
error:  { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE q.mseq = '10'' at line 1
    at Query.Sequence._packetToError (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    --------------------
    at Protocol._enqueue (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/yunseopkim/messaging-service/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (/Users/yunseopkim/messaging-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:198:44)
    at step (/Users/yunseopkim/messaging-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/Users/yunseopkim/messaging-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at fulfilled (/Users/yunseopkim/messaging-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE q.mseq = \'10\'\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'SELECT * FROM  WHERE q.mseq = \'10\'' }

```

**Comment by pleerock** [comment]
Sounds like something impossible. I need a reproduction code example.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
