### ISSUE TITLE
Error saving entity with lazy relations

### ISSUE THREAD

**Issue by monofuel** [typeorm/typeorm#1643]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I've ran into a really strange error case that happens when saving objects, and it seems to only happen when lazy-loading relations. We are also using composite primary keys for one of the entities, not sure if that affects the issue.

Repository to reproduce the problem: https://github.com/monofuel/typeorm-relation-issue

error message when saving:
```
{ QueryFailedError: invalid input syntax for uuid: "{}"
    at new QueryFailedError (/home/monofuel/src/typeorm-relation-issue/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.callback (/home/monofuel/src/typeorm-relation-issue/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:38)
    at Query.handleError (/home/monofuel/src/typeorm-relation-issue/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/monofuel/src/typeorm-relation-issue/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/home/monofuel/src/typeorm-relation-issue/node_modules/pg/lib/connection.js:117:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  message: 'invalid input syntax for uuid: "{}"',
  name: 'QueryFailedError',
  length: 85,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'uuid.c',
  line: '129',
  routine: 'string_to_uuid',
  query: 'SELECT "subject"."id" AS "subject_id", "subject"."itemId" AS "subject_itemId" FROM "test1" "subject" WHERE "subject"."id"=$1 AND "subject"."itemId"=$2',
  parameters: [ 1234, { id: undefined } ] }

```

These are the example entities, with the primary column being filled by the application before saving:
```
@Entity()
export class Test1 {
    @PrimaryColumn()
    id: number;

    @ManyToOne(type => Test2, test2 => test2.items, {
        primary: true,
        nullable: false
    })
    item: Promise<Test2>;
}
```

```
import {Entity, OneToMany, PrimaryColumn} from "typeorm";
import { Test1 } from './test1';

@Entity()
export class Test2 {

    /*
    @PrimaryColumn()
    id: string; // works, saves correctly
    // */
    
    // does not work (produces attached error)
    @PrimaryColumn({
        type: 'uuid'
      })
    id: string;
    // */
    /*
    // does not work either (different error)
    @PrimaryColumn()
    id: number;
    // */

    @OneToMany(type => Test1, test1 => test1.item)
    items: Promise<Test1[]>;
}
```

**Comment by pleerock** [comment]
This looks like fixed in `@next`. Upgrade using `npm i typeorm@next`

**Comment by monofuel** [comment]
confirmed fixed in next, thanks!
