### ISSUE TITLE
Problem with getMongoRepository

### ISSUE THREAD

**Issue by bsdunx** [typeorm/typeorm#1760]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)
<--
I''m having a problem getting a repository connection here. I've also tried call `getMongoRepository` directly

`node:19940) UnhandledPromiseRejectionWarning: Error
    at new RepositoryNotFoundError (/mnt/data/ebola/Projects/ChaosRPG/src/error/RepositoryNotFoundError.ts:12:22)
    at MongoEntityManager.EntityManager.getRepository (/mnt/data/ebola/Projects/ChaosRPG/src/entity-manager/EntityManager.ts:769:19)
    at Connection.getMongoRepository (/mnt/data/ebola/Projects/ChaosRPG/src/connection/Connection.ts:325:29)
    at Object.getMongoRepository (/mnt/data/ebola/Projects/ChaosRPG/src/index.ts:257:55)
    at GameDb.getSettings (/mnt/data/ebola/Projects/ChaosRPG/src/db.ts:49:36)
    at Game.init (/mnt/data/ebola/Projects/ChaosRPG/src/game.ts:201:46)
`
```ts
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm'
import { ISettings } from '../interfaces'

@Entity()
export class Settings implements ISettings {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    next_account_id: number

    @Column()
    next_unit_id: number

    @Column()
    next_item_id: number

    @Column()
    guilds: string[]
}
```

```ts
class GameDb {
    public connection: Connection
    private config: IDbHostConfig

    public async connect(): Promise<void> {
        console.log('GameDb.connect')
        this.connection = await createConnection()
    }
    
    public async getSettings(): Promise<ISettings> {
        const settingsRepo = this.connection.getMongoRepository(Settings)

        const settings = await settingsRepo.findOne({id: 0})
        console.log(settings)
        return settings
    }
```

**Comment by bsdunx** [comment]
Solved, I neglected to update the configuration file after changing directory structure of my project.
