### ISSUE TITLE
syncSchema attempts to sync schema multiple times

### ISSUE THREAD

**Issue by jon-walton** [typeorm/typeorm#18]
Hi,

I've just starting toying with typeorm and so far it's working better then *other* js orms I've tried. So thanks for the work you're putting in!

I've come across an issue where if I reuse the same connection, I'm seeing strange behavior with `syncSchema` attempting to create the tables x number of times (where x is the number of times `syncSchema` has been called on this connection).

As a use case, the flow of my tests is as follows (no public code yet, apologies)

1. array of `ConnectionOptions` is defined (for mysql and postgres)
2. forEach item in the array, do:
  1. create the connection and `syncSchema`
  2. perform tests
  3. close the connection

If I create a new connection with a different connectionName, I don't see this behavior.

In addition to this, it would be good if we have the ability to remove connections from ConnectionManager.

Thanks!

**Comment by pleerock** [comment]
hi @jon-walton 
sorry for late response, was very busy last week.

I need at least a code snippet to understand how do you use connections.
For now what I get is that you are trying to create multiple connections with the same name.
If so, then you should not.

**Comment by jon-walton** [comment]
Hi @pleerock 

Sorry, yep, I should have provided some repro code.

```typescript
import 'reflect-metadata';

import { Connection, createConnection, ConnectionOptions, getConnectionManager } from 'typeorm';
import { Table } from 'typeorm/tables';
import { PrimaryColumn, Column } from 'typeorm/columns';

@Table('testTable')
export class TestTable {

  @PrimaryColumn('int', { generated: true })
  public id: number;

  @Column()
  public name: string;
}

const mysqlOptions: ConnectionOptions = {
  connectionName: `mysql`,
  driver: {
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'libCore',
    password: 'libCore',
    database: 'libCoreTest',
    logging: {
      logger: (message: string, level: string) => console.log(level, message),
      logQueries: true,
      logFailedQueryError: true,
    },
  },
  autoSchemaCreate: false,
  dropSchemaOnConnection: false,
  entities: [TestTable],
};

async function test(): Promise<Connection> {
  let connection: Connection;
  try {
    connection = getConnectionManager().get(mysqlOptions.connectionName);
    console.log('got existing connection');
  } catch (err) {
    console.log('creating connection');
    connection = await createConnection(mysqlOptions);
  }

  if (!connection.isConnected) {
    console.log('connecting...');
    await connection.connect();
  }

  console.log('sync - dropBeforeSync = true');
  await connection.syncSchema(true);

  console.log('finished test suit, cleanup');

  console.log('dropping database');
  await connection.dropDatabase();

  console.log('disconnecting');
  await connection.close();

  return connection;
}

test()
  .then(() => console.log('finished test 1\n\n'))

  .then(() => test())
  .then(() => console.log('finished test 2\n\n'));
```

outputs the following

```text
creating connection
sync - dropBeforeSync = true
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: DROP TABLE IF EXISTS testTable;
log executing query: SET FOREIGN_KEY_CHECKS = 1;
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND CONSTRAINT_TYPE = 'UNIQUE'
log executing query: SHOW INDEX FROM testTable
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
finished test suit, cleanup
dropping database
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: DROP TABLE IF EXISTS testTable;
log executing query: SET FOREIGN_KEY_CHECKS = 1;
disconnecting
finished test 1


got existing connection
connecting...
sync - dropBeforeSync = true
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: SET FOREIGN_KEY_CHECKS = 1;
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
error query failed: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
error error during executing query:
error { Error: ER_TABLE_EXISTS_ERROR: Table 'testTable' already exists
    at Query.Sequence._packetToError (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\sequences\Sequence.js:51:14)
    at Query.ErrorPacket (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\sequences\Query.js:83:18)
    at Protocol._parsePacket (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    --------------------
    at Protocol._enqueue (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Connection.query (C:\Users\jonwa\Documents\gitlab\core\node_modules\mysql\lib\Connection.js:214:25)
    at Promise (C:\Users\jonwa\Documents\gitlab\core\node_modules\typeorm\driver\driver\MysqlDriver.ts:143:66)
    at MysqlDriver.query (C:\Users\jonwa\Documents\gitlab\core\node_modules\typeorm\driver\driver\MysqlDriver.ts:143:16)
    at MysqlSchemaBuilder.query (C:\Users\jonwa\Documents\gitlab\core\node_modules\typeorm\schema-builder\schema-builder\MysqlSchemaBuilder.ts:153:28)
    at MysqlSchemaBuilder.createTableQuery (C:\Users\jonwa\Documents\gitlab\core\node_modules\typeorm\schema-builder\schema-builder\MysqlSchemaBuilder.ts:145:21)
    at schemaBuilder.checkIfTableExist.then.exist (C:\Users\jonwa\Documents\gitlab\core\node_modules\typeorm\schema-creator\schema-creator\SchemaCreator.ts:114:43)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  index: 0 }
```


If the connection already exists, it is reused. When calling `syncSchema` on an existing connection, it attempts to create the schema multiple times

```text
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
error query failed: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
```

**Comment by jon-walton** [comment]
A quick update, I just noticed that this works as expected (re-use existing connection, call createSchema()) if the connection is not closed.

```text
creating connection
sync - dropBeforeSync = true
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: DROP TABLE IF EXISTS testTable;
log executing query: SET FOREIGN_KEY_CHECKS = 1;
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND CONSTRAINT_TYPE = 'UNIQUE'
log executing query: SHOW INDEX FROM testTable
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
finished test suit, cleanup
dropping database
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: DROP TABLE IF EXISTS testTable;
log executing query: SET FOREIGN_KEY_CHECKS = 1;
finished test 1


got existing connection
sync - dropBeforeSync = true
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: SET FOREIGN_KEY_CHECKS = 1;
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: CREATE TABLE `testTable` (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, name varchar(255) NOT NULL) ENGINE=InnoDB;
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'libCoreTest' AND TABLE_NAME = 'testTable'
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
log executing query: SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND CONSTRAINT_TYPE = 'UNIQUE'
log executing query: SHOW INDEX FROM testTable
log executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "libCoreTest" AND TABLE_NAME = "testTable" AND REFERENCED_COLUMN_NAME IS NOT NULL
finished test suit, cleanup
dropping database
log executing query: SET FOREIGN_KEY_CHECKS = 0;
log executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS q FROM information_schema.tables WHERE table_schema = 'libCoreTest';
log executing query: DROP TABLE IF EXISTS testTable;
log executing query: SET FOREIGN_KEY_CHECKS = 1;
finished test 2
```

**Comment by pleerock** [comment]
👍

**Comment by pleerock** [comment]
i guess it can be closed

**Comment by jon-walton** [comment]
@pleerock I disagree that this should be closed. This is still an issue that needs resolving

The core library within my project will either connect to 1 backend database, or be used in a desktop application where it can open different sqlite databases. The user works on 1 file at a time and can load(connect)/close/create databases.

If, after loading a few databases, they then create a new one, the schema has to be synced, but at that point typeorm will try to sync it multiple times.

If I have time at the weekend, I'll take a look at what is causing this, but I do think it's something that isn't working as intended.

**Comment by jon-walton** [comment]
this may be fixed in 0.0.2-alpha.62

**Comment by pleerock** [comment]
@jon-walton please confirm if its working, if not reopen this issue

**Comment by Freysi21** [comment]
Think i found my answer here.
This can be closed.
https://github.com/typeorm/typeorm/issues/1861
