### ISSUE TITLE
QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by gbreeze** [typeorm/typeorm#1803]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/gbreeze/typeorm-test

Hello guys,

everything is fine on the first start and on saving the item(s). The database looks also good. But on an app restart I get the following error: 

```javascript
executing query:  BEGIN TRANSACTION
executing query:  SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('track', 'artist', 'album', 'playlist', 'artist_albums_album', 'artist_tracks_track')
executing query:  PRAGMA table_info("artist")
executing query:  PRAGMA index_list("artist")
executing query:  PRAGMA foreign_key_list("artist")
executing query:  PRAGMA table_info("album")
executing query:  PRAGMA index_list("album")
executing query:  PRAGMA foreign_key_list("album")
executing query:  PRAGMA table_info("playlist")
executing query:  PRAGMA index_list("playlist")
executing query:  PRAGMA foreign_key_list("playlist")
executing query:  PRAGMA table_info("track")
executing query:  PRAGMA index_list("track")
executing query:  PRAGMA foreign_key_list("track")
executing query:  PRAGMA table_info("artist_albums_album")
executing query:  PRAGMA index_list("artist_albums_album")
executing query:  PRAGMA foreign_key_list("artist_albums_album")
executing query:  PRAGMA table_info("artist_tracks_track")
executing query:  PRAGMA index_list("artist_tracks_track")
executing query:  PRAGMA foreign_key_list("artist_tracks_track")
executing query:  PRAGMA index_info("sqlite_autoindex_album_2")
executing query:  PRAGMA index_info("sqlite_autoindex_album_1")
executing query:  PRAGMA index_info("sqlite_autoindex_artist_2")
executing query:  PRAGMA index_info("sqlite_autoindex_artist_1")
executing query:  PRAGMA index_info("sqlite_autoindex_track_2")
executing query:  PRAGMA index_info("sqlite_autoindex_track_1")
executing query:  PRAGMA index_info("sqlite_autoindex_artist_tracks_track_1")
executing query:  PRAGMA index_info("sqlite_autoindex_artist_albums_album_1")
executing query:  CREATE TABLE "temporary_track" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hash" varchar NOT NULL UNIQUE, "title" varchar NOT NULL, "duration" integer NOT NULL, "fileSize" integer, "disc" integer, "number" integer, "filePath" varchar NOT NULL UNIQUE, "coverArt" varchar, "releaseDate" datetime, "genre" varchar, "bitrate" integer, "rating" integer, "marked" boolean, "albumId" integer, FOREIGN KEY("albumId") REFERENCES "album"("id"))
executing query:  INSERT INTO "temporary_track"("id", "hash", "title", "duration", "fileSize", "disc", "number", "filePath", "coverArt", "releaseDate", "genre", "bitrate", "rating", "marked", "albumId") SELECT "id", "hash", "title", "duration", "fileSize", "disc", "number", "filePath", "coverArt", "releaseDate", "genre", "bitrate", "rating", "marked", "albumId" FROM "track"
executing query:  DROP TABLE "track"
query failed:  DROP TABLE "track"
error:  { Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed errno: 19, code: 'SQLITE_CONSTRAINT' }
executing query:  ROLLBACK
Database connection failed { QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at new QueryFailedError (C:\GIT\styrit-audio-indexer\node_modules\typeorm\error\QueryFailedError.js:27:28)
    at Statement.<anonymous> (C:\GIT\styrit-audio-indexer\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:95:38)
    at Statement.replacement (C:\GIT\styrit-audio-indexer\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.replacement (C:\GIT\styrit-audio-indexer\node_modules\sqlite3\lib\trace.js:19:31)
  message: 'SQLITE_CONSTRAINT: FOREIGN KEY constraint failed',
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  name: 'QueryFailedError',
  query: 'DROP TABLE "track"',
  parameters: [] }
```

Thanks,
George

**Comment by pleerock** [comment]
please checkout latest `@next`, this issue is already fixed in there.

**Comment by AlexMesser** [comment]
already fixed in `next` version. You can try it via `npm i typeorm@next`.
