### ISSUE TITLE
An enum column with an enum value of 0 throws a 'null value' error

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#182]
I may have found a possible bug with Enum support.  I have the following code:

```
@Column()
status: BillingPlanStatus
```

Where BillingPlanStatus is:

```
export enum BillingPlanStatus {
    Active = 0,
    Archived = 1
}
```

When I try to insert a record with a status == 0 (BillingPlanStatus.Active), TypeOrm throws 

```
{ error: column "status" contains null values
[1]     at Connection.parseE (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:554:11)
[1]     at Connection.parseMessage (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:381:17)
[1]     at Socket.<anonymous> (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:117:22)
[1]     at emitOne (events.js:96:13)
[1]     at Socket.emit (events.js:188:7)
[1]     at readableAddChunk (_stream_readable.js:176:18)
[1]     at Socket.Readable.push (_stream_readable.js:134:10)
[1]     at TCP.onread (net.js:551:20)
```

If I change my code to allow nullable values as below, then it works correctly. 

```
@Column({ nullable: true })
status: BillingPlanStatus
```

Nullable: true isn't really ideal, as it is a mandatory field in my schema. A workaround would be to never use 0 as an enum value. But, that requires the schema designer to change their schema, which may not work for those migrating an existing app to TypeORM.

**Comment by pleerock** [comment]
I cannot reproduce your issue. Take a look on my test and take a look that its reproducing what you were described, however it passes.

**Comment by dcworldwide** [comment]
You're right. I apologise. This isn't an issue with the lib, but an issue with my test harness. Will try and write a test in https://github.com/typeorm/typeorm/blob/master/test/functional next time first.
