### ISSUE TITLE
MySQL Driver adds multiple event listeners to a single connection

### ISSUE THREAD

**Issue by m1cr0man** [typeorm/typeorm#1833]
**Issue type:**

[X] bug report

**Database system/driver:**

[X] `mysql` / `mariadb`

**TypeORM version:**

[X] `latest`

**Steps to reproduce or a small repository showing the problem:**

[index.ts](https://gist.github.com/m1cr0man/e70c066c6b8c3009d2bed61d37e10632) (Instructions at the top)

Every time a connection is pulled from the pool, the MySQL driver [adds a listener](https://github.com/typeorm/typeorm/blame/6df6c0f2321bcbd37450658ecde4f6186f88252c/src/driver/mysql/MysqlDriver.ts#L573) to catch and log connection errors.

In the case of a single instance of MySQL (and possibly for clusters too) the connection returned by [pool.getConnection](https://github.com/typeorm/typeorm/blame/6df6c0f2321bcbd37450658ecde4f6186f88252c/src/driver/mysql/MysqlDriver.ts#L466) is always the same object, and so the error listener is added multiple times to it.

After around 9 transactions, TypeORM produces this error:
```
(node:9054) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:224:19)
    at PoolConnection.addListener (events.js:241:10)
    at MysqlDriver.prepareDbConnection (.../node_modules/typeorm/driver/mysql/MysqlDriver.js:535:20)
    at .../node_modules/typeorm/driver/mysql/MysqlDriver.js:439:48
    at Ping.onOperationComplete [as _callback] (.../node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
```
Increasing max listeners would not be the best solution here - it's important to ensure that only one error listener is added to each database connection.

**Comment by m1cr0man** [comment]
I'm going to create a PR for this now - at a glance the issue is pretty simple to solve, however I'd like feedback on whether this will be the best solution.
