### ISSUE TITLE
Single file @Table definition order is important

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#186]
It is worth nothing, that if you define all of your Entities (i.e. @Table classes) in a single file, that the order is important. If you reference a Entity as part of a relation (i.e. @OneToOne) before that referenced Entity is defined, you'll receive an error like below:

```
/Users/Danijel/projects/am/am-api/lib/model/model.js:175
[1]     __metadata("design:type", StoreBillingPlan)
[1]                               ^
[1]
[1] ReferenceError: StoreBillingPlan is not defined
[1]     at Object.<anonymous> (/Users/x/projects/am/am-api/lib/model/model.js:175:31)
[1]     at Module._compile (module.js:571:32)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:488:32)
[1]     at tryModuleLoad (module.js:447:12)
[1]     at Function.Module._load (module.js:439:3)
[1]     at Module.require (module.js:498:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/Users/x/projects/am/am-api/lib/services/auth.js:10:17)
[1]     at Module._compile (module.js:571:32)
```

In my case, defining StoreBillingPlan before the above code was run solved my issue.  Is it possible to make order not important? 

Note: For those splitting Entities across files this shouldn't be an issue.

**Comment by pleerock** [comment]
No, its not possible. It is a language limitation and can't be avoided. Thats a dynamic nature of javascript. Its basically the same as:


```typescript
console.log(b); // will not work because b is not defined at this time
let a = 1;
let b = 2;
console.log(a); // everything is fine because a is defined
```

Same rules applies to classes.

**Comment by dcworldwide** [comment]
Yeah I figured as much. Happy to modularise my code.
