### ISSUE TITLE
Synchronization error with default value

### ISSUE THREAD

**Issue by RDeluxe** [typeorm/typeorm#1883]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Here is my entity : 

```ts
@Entity()
@Index(['alliance', 'user'], { unique: true })
export class AlliancePendingEntity extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id: string

  @JoinColumn({ name: 'userId' })
  @ManyToOne(type => UserEntity)
  public user: UserEntity

  @JoinColumn({ name: 'allianceId' })
  @ManyToOne(type => AllianceEntity)
  public alliance: AllianceEntity

  @Column('enum', { enum: PendingStatuses, default: PendingStatuses[PendingStatuses.Applicant] })
  public status: PendingStatuses
}
```

If I have no schema created, everything is fine (well, not totally, there is still the problem of non-string enum but that's another opened issue). However, if I relaunch the server I encounter an error : 

```bash
[1] ci-server     | query: ALTER TABLE "user_entity" ALTER COLUMN "avatarId" SET DEFAULT 'AgileHooligan1_1'
[1] ci-server     | query: ALTER TYPE "alliance_pending_entity_status_enum" RENAME TO "alliance_pending_entity_status_enum_old"
[1] ci-server     | query: CREATE TYPE "alliance_pending_entity_status_enum" AS ENUM('Invited', 'Applicant', '0', '1')
[1] ci-server     | query: ALTER TABLE "alliance_pending_entity" ALTER COLUMN "status" TYPE "alliance_pending_entity_status_enum" USING "status"::"text"::"alliance_pending_entity_status_enum"
[1] ci-db-new     | ERROR:  default for column "status" cannot be cast automatically to type alliance_pending_entity_status_enum
[1] ci-db-new     | STATEMENT:  ALTER TABLE "alliance_pending_entity" ALTER COLUMN "status" TYPE "alliance_pending_entity_status_enum" USING "status"::"text"::"alliance_pending_entity_status_enum"
[1] ci-server     |  query failed: ALTER TABLE "alliance_pending_entity" ALTER COLUMN "status" TYPE "alliance_pending_entity_status_enum" USING "status"::"text"::"alliance_pending_entity_status_enum"
[1] ci-server     | error: { error: default for column "status" cannot be cast automatically to type alliance_pending_entity_status_enum
[1] ci-server     |     at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:546:11)
[1] ci-server     |     at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:371:19)
[1] ci-server     |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:114:22)
[1] ci-server     |     at Socket.emit (events.js:127:13)
[1] ci-server     |     at Socket.emit (domain.js:421:20)
[1] ci-server     |     at addChunk (_stream_readable.js:269:12)
[1] ci-server     |     at readableAddChunk (_stream_readable.js:256:11)
[1] ci-server     |     at Socket.Readable.push (_stream_readable.js:213:10)
[1] ci-server     |     at TCP.onread (net.js:590:20)
[1] ci-server     |   name: 'error',
[1] ci-server     |   length: 170,
[1] ci-server     |   severity: 'ERROR',
[1] ci-server     |   code: '42804',
[1] ci-server     |   detail: undefined,
[1] ci-server     |   hint: undefined,
[1] ci-server     |   position: undefined,
[1] ci-server     |   internalPosition: undefined,
[1] ci-server     |   internalQuery: undefined,
[1] ci-server     |   where: undefined,
[1] ci-server     |   schema: undefined,
[1] ci-server     |   table: undefined,
[1] ci-server     |   column: undefined,
[1] ci-server     |   dataType: undefined,
[1] ci-server     |   constraint: undefined,
[1] ci-server     |   file: 'tablecmds.c',
[1] ci-server     |   line: '8238',
[1] ci-server     |   routine: 'ATExecAlterColumnType' }
[1] ci-server     | query: ROLLBACK
[1] ci-server     | { QueryFailedError: default for column "status" cannot be cast automatically to type alliance_pending_entity_status_enum
[1] ci-server     |     at new QueryFailedError (/home/node/app/src/error/QueryFailedError.ts:7:9)
[1] ci-server     |     at Query.callback (/home/node/app/src/driver/postgres/PostgresQueryRunner.ts:171:26)
[1] ci-server     |     at Query.handleError (/home/node/app/node_modules/pg/lib/query.js:143:17)
[1] ci-server     |     at Connection.connectedErrorHandler (/home/node/app/node_modules/pg/lib/client.js:132:26)
[1] ci-server     |     at Connection.emit (events.js:127:13)
[1] ci-server     |     at Connection.emit (domain.js:421:20)
[1] ci-server     |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:118:12)
[1] ci-server     |     at Socket.emit (events.js:127:13)
[1] ci-server     |     at Socket.emit (domain.js:421:20)
[1] ci-server     |     at addChunk (_stream_readable.js:269:12)
[1] ci-server     |   message: 'default for column "status" cannot be cast automatically to type alliance_pending_entity_status_enum',
[1] ci-server     |   name: 'QueryFailedError',
[1] ci-server     |   length: 170,
[1] ci-server     |   severity: 'ERROR',
[1] ci-server     |   code: '42804',
[1] ci-server     |   detail: undefined,
[1] ci-server     |   hint: undefined,
[1] ci-server     |   position: undefined,
[1] ci-server     |   internalPosition: undefined,
[1] ci-server     |   internalQuery: undefined,
[1] ci-server     |   where: undefined,
[1] ci-server     |   schema: undefined,
[1] ci-server     |   table: undefined,
[1] ci-server     |   column: undefined,
[1] ci-server     |   dataType: undefined,
[1] ci-server     |   constraint: undefined,
[1] ci-server     |   file: 'tablecmds.c',
[1] ci-server     |   line: '8238',
[1] ci-server     |   routine: 'ATExecAlterColumnType',
[1] ci-server     |   query: 'ALTER TABLE "alliance_pending_entity" ALTER COLUMN "status" TYPE "alliance_pending_entity_status_enum" USING "status"::"text"::"alliance_pending_entity_status_enum"',
[1] ci-server     |   parameters: [] }
```

I'm not 100% sure of what is happening here, is the default value changed before the column type ?

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.45`. You can try it via `npm i typeorm@next`.

**Comment by phoenisx** [comment]
I am using `"typeorm": "^0.3.17"`, but facing this same issue on synchronization.
Am I missing something here?

I am getting the same error as OPs', and my column's default is not getting set to the updated ENUM type, with new values.

Let me know if any specific details are required.

> P.S.: I haven't shared the error logs cause they are exactly the same as OPs', just with column and enum name changes.

**Comment by phoenisx** [comment]
I am really confused now. I thought there might be something wrong in my code, so:

- I dropped and recreated the entire "public" schema, to get a restart.
- Restarted my server with default value for the column set to `foo8`.
- Typeorm create a ENUM with `foo8` present

Since I didn't want to keep my default value set to `foo8`, I dropped the schema again and redo the above steps again but setting my column default to `foo1`.
- I dropped and recreated the entire "public" schema, to get a restart.
- Restarted my server with default value for the column set to `foo1`.
- Typeorm doesn't create enum with `foo8` present.


Does TypeORM keeps a cache somewhere in the DB, that I need to clear for this to work?

**Comment by phoenisx** [comment]
Not sure why, deleting `/build` directory as per this https://github.com/typeorm/typeorm/issues/2712#issuecomment-533506830 fixed the issue.

Do we keep a cache somewhere in the dist folder for typeorm migrations? I didn't find a metadata table that keeps a check on what changes have been synchronised with DB on local.

Is this the query for typeorm metadata?
```
SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
```
but the above results with 0 rows.
