### ISSUE TITLE
Model with two ManyToOne relations errors with "Multiple primary key defined"

### ISSUE THREAD

**Issue by Kxze** [typeorm/typeorm#1971]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
// User.ts
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, ManyToMany, JoinTable, OneToOne, JoinColumn, OneToMany } from "typeorm";
import { Song, Listen } from "./index";

@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        default: () => "NOW()"
    })
    createdAt: Date;

    @OneToMany(type => Listen, listen => listen.song)
    listens: Listen[];

    async updateProfile(profile: Profile) {
        await profile.save();
        this.profile = profile;
        await this.save();
    }

    async addListen(song: Song) {
        const listen = new Listen();
        listen.song = song;
        listen.user = this;

        await listen.save();
    }

}
```

```ts
// Song.ts
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, ManyToMany, JoinTable, OneToMany } from "typeorm";
import { Listen } from "./index";

@Entity()
export class Song extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Listen, listen => listen.user)
    listeners: User[];

}
```

```ts
// Listen.ts
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, ManyToOne } from "typeorm";
import { Song, User } from "./index";

@Entity()
export class Listen extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Song, song => song, {
        cascadeAll: true
    })
    song: Song;

    @ManyToOne(type => User, user => user, {
        cascadeAll: true
    })
    user: User;

    @Column({
        default: () => "NOW()"
    })
    createdAt: Date;

}
```

This gives me the following error:
```
{ QueryFailedError: ER_MULTIPLE_PRI_KEY: Multiple primary key defined
[1]     at new QueryFailedError (/repos/Virtua/node_modules/typeorm/error/QueryFailedError.js:27:28)
[1]     at Query._callback (/repos/Virtua/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:207:45)
[1]     at Query.Sequence.end (/repos/Virtua/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
[1]     at Query.ErrorPacket (/repos/Virtua/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
[1]     at Protocol._parsePacket (/repos/Virtua/node_modules/mysql/lib/protocol/Protocol.js:279:23)
[1]     at Parser.write (/repos/Virtua/node_modules/mysql/lib/protocol/Parser.js:76:12)
[1]     at Protocol.write (/repos/Virtua/node_modules/mysql/lib/protocol/Protocol.js:39:16)
[1]     at Socket.<anonymous> (/repos/Virtua/node_modules/mysql/lib/Connection.js:103:28)
[1]     at emitOne (events.js:116:13)
[1]     at Socket.emit (events.js:211:7)
[1]   message: 'ER_MULTIPLE_PRI_KEY: Multiple primary key defined',
[1]   code: 'ER_MULTIPLE_PRI_KEY',
[1]   errno: 1068,
[1]   sqlMessage: 'Multiple primary key defined',
[1]   sqlState: '42000',
[1]   index: 0,
[1]   sql: 'ALTER TABLE `virtua`.`listen` ADD `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT',
[1]   name: 'QueryFailedError',
[1]   query: 'ALTER TABLE `virtua`.`listen` ADD `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT',
[1]   parameters: [] }
```

**Comment by Kxze** [comment]
Fixed by changing `Listen.ts` to:

```ts
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, ManyToOne } from "typeorm";
import { Song, User } from "./index";

@Entity()
export class Listen extends BaseEntity {

    @ManyToOne(type => Song, song => song.id, {
        primary: true,
        cascadeInsert: true,
        nullable: false,
    })
    song: Song;

    @ManyToOne(type => User, user => user.id, {
        primary: true,
        cascadeInsert: true,
        nullable: false,
    })
    user: User;

    @Column({
        default: () => "NOW()"
    })
    createdAt: Date;

}
```
