### ISSUE TITLE
Invalid input syntax for type uuid with typeorm@0.2.0 and postgres

### ISSUE THREAD

**Issue by lednhatkhanh** [typeorm/typeorm#1985]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] ^0.2.0

**Steps to reproduce or a small repository showing the problem:**

Code:

```typescript
import { Repository } from "typeorm";

export const queryBatchFunction = <T extends { id: string }>(repository: Repository<T>) => async (
  keys: string[],
): Promise<(T | null)[]> => {
  const docs = await repository
    .createQueryBuilder("TableName")
    .where(`TableName.id IN (:keys)`, { keys })
    .getMany();

  return keys.map(k => docs.find(d => d.id === k) || null);
};
```

Log:

```
query failed: SELECT "TableName"."id" AS "TableName_id", "TableName"."name" AS "TableName_name", "TableName"."email" AS "TableName_email", "TableName"."password" AS "TableName_password", "TableName"."versionKey" AS "TableName_versionKey", "TableName"."createdAt" AS "TableName_createdAt", "TableName"."updatedAt" AS "TableName_updatedAt" FROM "users" "TableName" WHERE "TableName"."id" IN ($1) -- PARAMETERS: [["f9aeae36-39f0-4063-9866-75b8504c754e","bc7d42bc-3f7f-4502-8e23-751bf5c191b0","950514f5-0f82-4575-bbe9-88d52e99019b","5ad3603c-4db9-463d-9176-9f01a96cf6e4","3997e43a-50ee-423d-a16a-42fd5615f6c2","c5d3f0fe-0cef-4a29-951c-c869ce345e6e","054135f8-14bd-41b9-accb-f0426ede3278"]]
```

Error message:

```
error: { error: invalid input syntax for type uuid: "{"f9aeae36-39f0-4063-9866-75b8504c754e","bc7d42bc-3f7f-4502-8e23-751bf5c191b0","950514f5-0f82-4575-bbe9-88d52e99019b","5ad3603c-4db9-463d-9176-9f01a96cf6e4","3997e43a-50ee-423d-a16a-42fd5615f6c2","c5d3f0fe-0cef-4a29-951c-c869ce345e6e","054135f8-14bd-41b9-accb-f0426ede3278"}"
    at Connection.parseE (C:\Users\klnhat\workspace\my-hackernews-server\node_modules\pg\lib\connection.js:545:11)
    at Connection.parseMessage (C:\Users\klnhat\workspace\my-hackernews-server\node_modules\pg\lib\connection.js:370:19)
    at Socket.<anonymous> (C:\Users\klnhat\workspace\my-hackernews-server\node_modules\pg\lib\connection.js:113:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
  name: 'error',
  length: 369,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'uuid.c',
  line: '137',
  routine: 'string_to_uuid' }
```

It used to work fine with older version, but when I updated typeorm to 0.2.0, the problem occurs.

**Comment by lednhatkhanh** [comment]
I found the solution:

```typescript
export const queryBatchFunction = <T extends { id: string }>(repository: Repository<T>) => async (
  keys: string[],
): Promise<(T | null)[]> => {
  const docs = await repository
    .createQueryBuilder("TableName")
    .where(`TableName.id IN (:...keys)`, { keys })
    .getMany();

  return keys.map(k => docs.find(d => d.id === k) || null);
};
```

Note the `:...key` thing, but I don't see this's being mentioned anywhere in the changelog... Am I missing anything?

**Comment by dcworldwide** [comment]
I remember seeing it in the cl

**Comment by pleerock** [comment]
This change was required to support native postgres arrays. From changelog:

> breaking change on how array parameters work in queries - now instead of (:param) new syntax must be used (:...param).

**Comment by lednhatkhanh** [comment]
So then I'm going to close this issued now
