### ISSUE TITLE
SQL server 2012 update query not working

### ISSUE THREAD

**Issue by samikroy-work** [typeorm/typeorm#199]
Generated update query getting   syntax error  from SQL server.
**CODE:** 
let qb=this.entityManager.getRepository(this.elementObjectType)
            .createQueryBuilder("g")
            .update({
                locked: flag?1:0,
                locked_by:"",
                locked_on:new Date()
            })
            .andWhereInIds(ids);
        console.log(qb.getSqlWithParameters());
        return qb.execute();

**Log:**
[ 'UPDATE client "g" SET locked=@0,locked_by=@1,locked_on=@2 WHERE "g"."client_id"=@3',
  [ 1, '', 2017-01-14T07:34:00.309Z, 1 ] ]
13:04:00.643 ERROR HttpStatuscodeMessageProducer {"name":"RequestError","message":"Incorrect syntax near 'g'.","code":"EREQUEST","number":102,"lineNumber":1,"state":1,"class":15,"serverName":"SAMIK-PC","procName":"","precedingErrors":[]}
13:04:00.643 ERROR HttpStatuscodeMessageProducer {"name":"RequestError","message":"Incorrect syntax near 'g'.","code":"EREQUEST","number":102,"lineNumber":1,"state":1,"class":15,"serverName":"SAMIK-PC","procName":"","precedingErrors":[]}
InternalServerError: Internal Server Error
    at InternalServerError.Error (native)
    at InternalServerError.HttpError [as constructor] (E:\ui-dev\node-project\ProRelevent\codebase\node_modules\typescript-rest\release\lib\server-types.js:26:28)
    at new InternalServerError (E:\ui-dev\node-project\XXX\codebase\node_modules\typescript-rest\release\lib\server-errors.js:101:28)
    at Function.fromCustomError (E:\ui-dev\node-project\XXX\codebase\src\rest-services\util\HttpStatuscodeMessageProducer.js:22:20)
    at clientBusiness.lockOrUnlockCliens.then.e (E:\ui-dev\node-project\XXX\codebase\src\rest-services\ClientController.js:55:90)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by pleerock** [comment]
In recent versions (0.1.0-alpha.24) update works for all platforms including mssql, there are tests that prove it. If you still have problems with update in latest versions please let me know.
