### ISSUE TITLE
Enum type not working in postgres

### ISSUE THREAD

**Issue by PavanBahuguni** [typeorm/typeorm#1997]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
type Action =
    'add' |
    'update' |
    'delete';
@Entity()
export class DatasourceAction {

    @PrimaryColumn()
    id: string;

    @Column({ name: 'name', type: 'text', unique: true })
    name: string;

    @Column({ name: 'action', type: 'enum', enum: ['add', 'update', 'delete'] })
    action: Action;
}
```
The SQL quarries executed are as follows
```
CREATE TYPE "test"."datasource_action_action_enum" AS ENUM('add', 'update', 'delete')
ALTER TABLE "test"."datasource_action" ADD "action" "datasource_action_action_enum" NOT NUL
```
and it errors with type "datasource_action_action_enum" does not exist

I think the the ALTER TABLE query should have been as follows.
ALTER TABLE "test"."datasource_action" ADD "action" "test"."datasource_action_action_enum" NOT NUL

**Comment by nolazybits** [comment]
I hit the same problem
```
    @Column({
        type: "enum",
        enum: Gender,
        default: Gender.NotAvailable,
    })
    public gender!: Gender;
```

Gender enum class
```
export enum Gender
{
    Male = "male",
    Female = "female",
    Other = "other",
    NotAvailable = "n/a",
}
```

**Comment by DR-BoneZ** [comment]
status?

**Comment by irissoftworks** [comment]
+1, hitting the same. I think the original poster is spot on. It doesn't seem to be using the correct schema on the query.

**Comment by darioblanco** [comment]
Same problem here. For a schema called `int_location`

```
console.log node_modules/typeorm/platform/PlatformTools.js:212
query failed: CREATE TABLE "int_location"."auth" (
  "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), 
  "role" "auth_role_enum"NOT NULL,
...
```

```
console.log node_modules/typeorm/platform/PlatformTools.js:212
      error: { error: type "auth_role_enum" does not exist
...
```

I guess the schema has to be appended as well to `auth_role_enum`.


Happening with `synchronize` and `dropBeforeSync` set to `true`

**Comment by vtsatskin** [comment]
This also seems to happen for enums mapped to integers when syncing the Entities to the database. 

For example, if we take the following enum:

```
enum Position {
    LEFT = 1,
    MIDDLE = 2,
    RIGHT = 3
}
```

Then add an enum type field with a default value to an Entity:
```
  @Column("enum", {
    enum: Position,
    default: Position[Position.LEFT]
  })
  position: Position;
```

This leads to the following error:

```
(node:23088) UnhandledPromiseRejectionWarning: QueryFailedError: invalid input value for enum user_position_enum: "LEFT"
```

If we adjust the default to the integer value:
```
  @Column("enum", {
    enum: Position,
    default: Position.LEFT
  })
  position: Position;
```

We still get an error:
```
(node:23198) UnhandledPromiseRejectionWarning: QueryFailedError: column "position" is of type user_position_enum but default expression is of type integer
```

**Comment by abcd-ca** [comment]
**RolesEnum.ts**
```
export enum RolesEnum {
  Admin = 'admin',
  Caregiver = 'caregiver'
}
```

**User.ts** entity
```
@Column({type: 'enum', enum: RolesEnum})
  role: string;
```

Worked for me as of version `^0.2.7` FYI

**Comment by tonyxiao** [comment]
fwiw I've been using string enum with check 

```ts

export function CheckEnum(tableName: string, fieldName: string, enumValue: any) {
  // Hash enum value and put it as part of constraint name so we can
  // force typeorm to generate migration for enum changes.
  const hash = crypto
    .createHash('sha1')
    .update(Object.values(enumValue).join(''))
    .digest('hex')
  return Check(
    // https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes
    `cke_${tableName}_${fieldName}_${hash}`.slice(0, 63),
    `${fieldName} in (${Object.values(enumValue).map(t => `'${t}'`)})`,
  )
}
```

And use it like so
```
@CheckEnum('user', 'status', UserStatus)
export class User extends TimestampableUUIDEntity {
```

**Comment by evik42** [comment]
@abcd-ca it works if you are not using schemas
this does not work:
```
export enum Status {
  ACTIVE = "active",
  INACTIVE = "inactive",
}

@Entity({schema: "admin"})
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("enum", { enum: Status, default: Status.ACTIVE })
  status: Status;
}
```
Generated SQL
```
CREATE TYPE "admin"."user_status_enum" AS ENUM('active', 'inactive');
CREATE TABLE "admin"."user" ("id" SERIAL NOT NULL, "status" "user_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_a28028ba709cd7e5053a86857b4" PRIMARY KEY ("id"));
```
The enum is correctly created in the schema but the create table does not reference it correctly.

Fixing the migration for creating the table is easy, but because of this bug any further automatic migration generation breaks because it cannot find the enum in the database as it does not search for it in the schema.

```
$ npx typeorm migration:generate -n test
Error during migration generation:
{ QueryFailedError: type "user_status_enum" does not exist
    at new QueryFailedError (/Users/evik/etheal/doklist-data-backend/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.<anonymous> (/Users/evik/etheal/doklist-data-backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:212:38)
    at Query.handleError (/Users/evik/etheal/doklist-data-backend/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/evik/etheal/doklist-data-backend/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/evik/etheal/doklist-data-backend/node_modules/pg/lib/connection.js:123:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
  message: 'type "user_status_enum" does not exist',
  name: 'QueryFailedError',
  length: 102,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '797',
  routine: 'parseTypeString',
  query:
   'SELECT *, "udt_name"::"regtype" AS "regtype" FROM "information_schema"."columns" WHERE ("table_schema" = \'frontend\' AND "table_name" = \'address\') OR ("table_schema" = \'frontend\' AND "table_name" = \'contact\') OR ("table_schema" = \'frontend\' AND "table_name" = \'contact_text\') OR ("table_schema" = \'frontend\' AND "table_name" = \'currency\') OR ("table_schema" = \'frontend\' AND "table_name" = \'entity\') OR ("table_schema" = \'frontend\' AND "table_name" = \'entity_hierarchy\') OR ("table_schema" = \'frontend\' AND "table_name" = \'entity_hierarchy_contact\') OR ("table_schema" = \'frontend\' AND "table_name" = \'entity_language\') OR ("table_schema" = \'frontend\' AND "table_name" = \'entity_text\') OR ("table_schema" = \'frontend\' AND "table_name" = \'image\') OR ("table_schema" = \'frontend\' AND "table_name" = \'image_tag\') OR ("table_schema" = \'frontend\' AND "table_name" = \'language\') OR ("table_schema" = \'frontend\' AND "table_name" = \'list\') OR ("table_schema" = \'frontend\' AND "table_name" = \'list_entity_hierarchy\') OR ("table_schema" = \'frontend\' AND "table_name" = \'list_entity_hierarchy_price\') OR ("table_schema" = \'frontend\' AND "table_name" = \'list_hierarchy\') OR ("table_schema" = \'frontend\' AND "table_name" = \'list_text\') OR ("table_schema" = \'frontend\' AND "table_name" = \'location\') OR ("table_schema" = \'frontend\' AND "table_name" = \'location_hierarchy\') OR ("table_schema" = \'frontend\' AND "table_name" = \'location_text\') OR ("table_schema" = \'frontend\' AND "table_name" = \'opening_hour\') OR ("table_schema" = \'frontend\' AND "table_name" = \'placeholder\') OR ("table_schema" = \'frontend\' AND "table_name" = \'review\') OR ("table_schema" = \'frontend\' AND "table_name" = \'review_log\') OR ("table_schema" = \'frontend\' AND "table_name" = \'review_tag\') OR ("table_schema" = \'frontend\' AND "table_name" = \'static\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'inquiry_log\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'invoice\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'invoice_data\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'model\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'model_text\') OR ("table_schema" = \'businessModel\' AND "table_name" = \'transaction_log\') OR ("table_schema" = \'admin\' AND "table_name" = \'entity_login\') OR ("table_schema" = \'admin\' AND "table_name" = \'entity_role\') OR ("table_schema" = \'admin\' AND "table_name" = \'user\')',
  parameters: [] }
```

**Comment by Kononnable** [comment]
@pleerock planned to release 0.2.8 and merge some PR's this weekend. Not sure if that will be merged today, but we're planning to slowly merge them all.

**Comment by pleerock** [comment]
can somebody test @evik42 's changes to make sure everything is right and we can merge it?

**Comment by evik42** [comment]
@pleerock I added all the previous enum tests with external schema as part of the PR, I also used this by manually patching typeorm in prod, let me know how I can assist to move this forward.

**Comment by evik42** [comment]
@Arlevoy you can checkout the last released tag of typeorm, merge the branch manually (there is no merge conflicts) and build the result with `npm compile` or `npm package`.
Alternatively you can patch the installed typeorm, you only need to do the changes in `PostgresQueryRunner.js` at three places as you can see in the PR diff, take care of properly escaping the quotes in strings.
Hopefully @pleerock will check it with the tests when he has time.

**Comment by pleerock** [comment]
this long-expected bug was fixed by @evik42 ! Will be released in `@rc` soon.

**Comment by andreechristian** [comment]
May i know when could i see this issue fixed on master?

**Comment by pleerock** [comment]
changes were already published
