### ISSUE TITLE
Error: Persistence entity is not set for the given subject.

### ISSUE THREAD

**Issue by peteryhwong** [typeorm/typeorm#2003]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.21` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Unfortunately it is not possible to efficiently create a reproduction case that can be pasted here.

I have the following error when executing `Repository.save(entities);` where `entities` is an array of entities to be updated and I am unsure what I might have done incorrectly. 

```
Error: Persistence entity is not set for the given subject.
    at Subject.get [as entity] (/node_modules/typeorm/persistence/Subject.js:76:23)
    at SubjectBuilder.buildCascadeUpdateAndInsertOperateSubjects (/node_modules/typeorm/persistence/SubjectBuilder.js:205:53)
    at SubjectBuilder.<anonymous> (/node_modules/typeorm/persistence/SubjectBuilder.js:130:30)
    at step (/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at /node_modules/typeorm/persistence/SubjectBuilder.js:7:71
    at Promise (<anonymous>)\n    at __awaiter (/node_modules/typeorm/persistence/SubjectBuilder.js:3:12)
    at SubjectBuilder.persist (/node_modules/typeorm/persistence/SubjectBuilder.js:118:16)
    at EntityManager.<anonymous> (/node_modules/typeorm/entity-manager/EntityManager.js:261:87)
```

**Comment by pleerock** [comment]
This error mean you setup / save something wrongly, and if you want help you need to provide a minimal reproduction git repo. Also there is no such error in 0.2.0 so you better to update to 0.2.0 first.

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
