### ISSUE TITLE
Boolean columns are being set to false after saving the entity

### ISSUE THREAD

**Issue by asvetliakov** [typeorm/typeorm#2005]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repro:

```ts

@Entity()
class User {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column({
        type: "tinyint",
        transformer: {
            from: val => !!val,
            to: val => val,
        },
    })
    activated: boolean;
}

const u = new User();
u.activated = true;

await db.manager.save(u);
u.activated; // false

const u2 = db.manager.findOne(User, u.id);
u2.activated; // true
```

**Comment by asvetliakov** [comment]
Please check this repo:
https://github.com/asvetliakov/typeorm-bugs/tree/master/2005

For some reason the test in typeorm repo itself passes.

**Comment by aasmpro** [comment]
same issue, Entity:
```
@Entity({ name: 'devices' })
export class Device {
	// other columns ...
	@Column({ name: 'haveWhy', default: 0, transformer: new NumberToBooleanTransformer() })
	haveWhy!: boolean;
}
```
transformer: 
```
export class NumberToBooleanTransformer implements ValueTransformer {
    from (value: number): boolean {
        console.log('sssssssssssssssssssssss',value, typeof value)
        if(value === 1){
            return true
        } else {
            return false
        }
    }

    to (value: boolean): number {
        console.log('xxxxxxxxxxxxxxxxxxxxxxx',value,  typeof value)
        if(value === true){
            return 1
        } else {
            return 0
        }
    }
}
```
my test:
```
it('test null value', async () => {
    await deviceRepository.clear();
    await deviceRepository.save({
        id: 1,
        haveWhy: true,
    });

    const device: Device | undefined = await deviceRepository.findOne(1);

    await expect(device!.serialNumber).toBe(null)
    await expect(device!.touchpointTypeId).toBe(1)
    await expect(device!.haveWhy).toBe(true) // this line fails
    });
```
test output:
```
 FAIL  src/entities/device.spec.ts
  ● Console

    console.log src/config/connection.ts:25
      /home/aasmpro/dev/digital-connection/src/config../**/*.entity{.ts,.js}
    console.log src/entities/transformers.ts:14
      xxxxxxxxxxxxxxxxxxxxxxx true boolean
    console.log src/entities/transformers.ts:5
      sssssssssssssssssssssss false boolean
    console.log src/entities/transformers.ts:5
      sssssssssssssssssssssss false boolean
    console.log src/entities/transformers.ts:5
      sssssssssssssssssssssss false boolean

  ● Device Entity › test null value

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      35 |     await expect(device!.touchpointTypeId).toBe(1)
      36 |     await expect(typeof device!.haveWhy).toBe('boolean')
    > 37 |     await expect(device!.haveWhy).toBe(true)
         |                                   ^
      38 |     });
      39 | });
      40 | 

      at Object.<anonymous> (entities/device.spec.ts:37:35)
      at fulfilled (entities/device.spec.ts:4:58)
```
in `from (value: number): boolean` value must be `number` but it is `boolean`.
any idea?
