### ISSUE TITLE
postgres fails to use @CreatedDateColumn and @UpdateDateColumn

### ISSUE THREAD

**Issue by et** [typeorm/typeorm#2020]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.1` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```js
import {
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Entity,
  PrimaryGeneratedColumn
} from 'typeorm';
import {
  IsNotEmpty,
  IsUUID
} from 'class-validator';

@Entity('applications')
export class Application {
  @PrimaryGeneratedColumn()
  readonly id!: number;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp' })
  updatedAt: Date;
}
```

```
saving entity failed { QueryFailedError: null value in column "created_at" violates not-null constraint
    at new QueryFailedError (/Users/et/code/NeatCapitalOrg/finicity-service/src/error/QueryFailedError.ts:7:9)
    at Query.<anonymous> (/Users/et/code/NeatCapitalOrg/finicity-service/src/driver/postgres/PostgresQueryRunner.ts:170:26)
    at Query.handleError (/Users/et/code/NeatCapitalOrg/finicity-service/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/et/code/NeatCapitalOrg/finicity-service/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/Users/et/code/NeatCapitalOrg/finicity-service/node_modules/pg/lib/connection.js:117:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
  message: 'null value in column "created_at" violates not-null constraint',
  name: 'QueryFailedError',
  length: 237,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (65, b03e832d-3862-43cb-8e6f-4984378a31a9, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'applications',
  column: 'created_at',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '2008',
  routine: 'ExecConstraints',
  query: 'INSERT INTO "applications"("nc_uuid", "created_at", "updated_at") VALUES ($1, DEFAULT, DEFAULT) RETURNING "id", "created_at", "updated_at"',
  parameters: [ 'b03e832d-3862-43cb-8e6f-4984378a31a9' ] }
Could not run seed QueryFailedError: null value in column "created_at" violates not-null constraint
```

**Comment by rclayton-the-terrible** [comment]
I'm experiencing the exact same issue, but not just with `@ CreateDateColumn` and `@UpdateDateColumn`, but also `@PrimaryGeneratedColumn('uuid')`.

This is my entity:

```
@Entity({ name: 'requirements' })
class Requirement implements RequirementInterface {
    @PrimaryGeneratedColumn('uuid')
    id: string

    @Column()
    type: string

    @Column({ name: 'restricted_action' })
    restrictedAction: string

    @Column({ name: 'entity_id' })
    entityId: string

    @Column({ name: 'entity_type' })
    entityType: string

    @Column({ type: 'enum', enum: RequirementStatuses})
    status: RequirementStatuses

    @Column('jsonb')
    context: { [p: string]: any }

    @Column('timestamp with time zone')
    expires: Date | null

    @CreateDateColumn({ name: 'created_at', type: 'timestamp with time zone' })
    createdAt: Date

    @UpdateDateColumn({ name: 'updated_at', type: 'timestamp with time zone' })
    updatedAt: Date
}
```

And I configure the connection as follows:

```
const manager = getConnectionManager()
const connection = manager.create({
  type: 'postgres',
  name: 'corev2',
  logger: new TypeORMLogger('corev2', logger),
  host: config.DB_COREV2_HOST,
  port: config.DB_COREV2_PORT,
  username: config.DB_COREV2_USERNAME,
  password: config.DB_COREV2_PASSWORD,
  database: config.DB_COREV2_DBNAME,
  schema: config.DB_COREV2_SCHEMA,
  entities: [Requirement]
})
await connection.connect()
```

And I attempted to create an instance of the entity:

```
// This is a method in one of my classes
async createRequirement(params: CreateRequirementParams): Promise<RequirementInterface> {
  // this.repository was retrieved from the connection directly injected into the Repository
  // this.repository = this.connection.getRepository(Requirement)
  const requirement = this.repository.create(params)
  return await this.repository.save(toBeCreated)
  // I've even tried:
  // return await this.connection.manager.save(toBeCreated)
}
```

I keep getting the error: `QueryFailedError: null value in column "id" violates not-null constraint` when attempting to insert a record without the ID.

Of course, I can add these properties to the requirement object prior to creating and the insert will work.

**Comment by pleerock** [comment]
In 0.2.0 create and update date decorators now are using SQL's `DEFAULT` to generate a date for those columns. Looks like you don't have DEFAULTs in sync - create and update date columns must have DEFAULT value set in the database.

**Comment by EduardsE** [comment]
@pleerock What's the point of the decorator then?

**Comment by pleerock** [comment]
decorators add those "defaults" to your columns

**Comment by EduardsE** [comment]
@pleerock Oh, we don' t use the syncing thing if I understood you correctly.

**Comment by rclayton-the-terrible** [comment]
@pleerock - OK, so if we don't use sync we need to ensure the table is created with the appropriate defaults.  Is that an accurate statement?  Also, how does this affect the behavior of `@UpdateDateColumn`?  Will TypeORM perform the update?  Or do we need to employ triggers?

**Comment by rclayton-the-terrible** [comment]
Verified it works with adequate defaults set.  My PG table now looks like this:

```
-- Auto generate UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.requirements
(
    id "uuid" PRIMARY KEY DEFAULT uuid_generate_v4(),
    type varchar(256),
    restricted_action varchar(256) NOT NULL,
    entity_id varchar(256) NOT NULL,
    entity_type varchar(256) NOT NULL,
    status varchar(256) DEFAULT 'pending' NOT NULL,
    context jsonb,
    expires timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
```

**Comment by et** [comment]
Thanks for checking that @rclayton-the-terrible. I confirmed the same results.
Since this is a breaking change, it should be emphasized that people using these decorators need to create a migration to properly set the default to `NOW()`.

```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddDefaultToTimestamps1524669290077 implements MigrationInterface {

  async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('ALTER TABLE applications ALTER COLUMN created_at SET DEFAULT NOW()');
    await queryRunner.query('ALTER TABLE applications ALTER COLUMN updated_at SET DEFAULT NOW()');
  }

  async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('ALTER TABLE applications ALTER COLUMN created_at DROP DEFAULT;');
    await queryRunner.query('ALTER TABLE applications ALTER COLUMN created_at DROP DEFAULT;');
  }
}
```

**Comment by pleerock** [comment]
Correct its one of the breaking change we did in 0.2.0 and we its documented in the changelog. I think this issue can be closed now.

**Comment by wnasich** [comment]
@mrsauravsahu posted a good solution: 
https://github.com/typeorm/typeorm/issues/2080#issuecomment-646064408 

```
@CreateDateColumn({ default: () => 'NOW()' })
createdAt: Date
```
to be used in your entity

**Comment by vanduc1102** [comment]
Could someone help to update the doc here : https://github.com/typeorm/typeorm/blob/master/docs/entities.md#special-columns

**Comment by zarelit** [comment]
I just spent something like 6 hours to figure out that my problem was related to an issue close in 2018. Is there an issue to track the documentation update?

**Comment by pratikjain04** [comment]
Updating my Column Type in the database helped me solve this issue.
`ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NOW()`

`@UpdateDateColumn `works fine for me, when the row is updated (and not created).

```

    @CreateDateColumn({type: 'timestamp', default: () => 'NOW()' })
    created_at: Date

    @UpdateDateColumn({ type: 'timestamp', default: () => 'NOW()' })
    updated_at: Date

```
