### ISSUE TITLE
bulk insert，Duplicate entry..primary key, createQueryBuilder

### ISSUE THREAD

**Issue by JingMo** [typeorm/typeorm#2035]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**

import {getConnection} from "typeorm";

await getConnection()
    .createQueryBuilder()
    .insert()
    .into(User)
    .values([
        { id: 1, firstName: "Timber", lastName: "Saw" }, 
        { id: 2, firstName: "Phantom", lastName: "Lancer" }
     ])
    .execute();

tips: id is primary key

question:  If id exists without inserting， how to write？

Thanks！

**Comment by pleerock** [comment]
use `update` ?

**Comment by pleerock** [comment]
in typeorm you use `save` and save your models, you don't need to care about insert ignore query.

**Comment by JingMo** [comment]
An error occurs: duplicate primarykey
I want:
    If exists, update or ignore
    If not exists, insert
@pleerock

**Comment by JingMo** [comment]
I use save, it does not like ‘If it exists - it updates it. If it does not exist it inserts a new row’
error：
{ Error: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
    at Query.Sequence._packetToError (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\DemoProjects\Demo\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at PoolConnection.query (E:\DemoProjects\Demo\node_modules\mysql\lib\Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (E:\DemoProjects\Demo\src\driver\mysql\MysqlQueryRunner.ts:146:36)
    at step (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:42:23)
    at Object.next (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:23:53)
    at fulfilled (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:14:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  message: 'ER_DUP_ENTRY: Duplicate entry \'1\' for key \'PRIMARY\'',
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: 'Duplicate entry \'1\' for key \'PRIMARY\'',
  sqlState: '23000',
  index: 0,
  sql: 'INSERT INTO `user_test`(`id`, `user_name`) VALUES (1, \'Sawst\')',
  name: 'QueryFailedError',
  query: 'INSERT INTO `user_test`(`id`, `user_name`) VALUES (?, ?)',
  parameters: [ 1, 'Sawst' ] }
@pleerock

**Comment by JingMo** [comment]
I use save, it does not like ‘If it exists - it updates it. If it does not exist it inserts a new row’

await connection.manager.save(connection.manager.create(User_test, {
        id: 1,
        user_name: "Sawst"
 }));

error：
{ Error: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
at Query.Sequence._packetToError (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
at Query.ErrorPacket (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
at Protocol._parsePacket (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:279:23)
at Parser.write (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Parser.js:76:12)
at Protocol.write (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:39:16)
at Socket. (E:\DemoProjects\Demo\node_modules\mysql\lib\Connection.js:103:28)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
--------------------
at Protocol._enqueue (E:\DemoProjects\Demo\node_modules\mysql\lib\protocol\Protocol.js:145:48)
at PoolConnection.query (E:\DemoProjects\Demo\node_modules\mysql\lib\Connection.js:208:25)
at MysqlQueryRunner. (E:\DemoProjects\Demo\src\driver\mysql\MysqlQueryRunner.ts:146:36)
at step (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:42:23)
at Object.next (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:23:53)
at fulfilled (E:\DemoProjects\Demo\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:14:58)
at process._tickDomainCallback (internal/process/next_tick.js:135:7)
message: 'ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'',
code: 'ER_DUP_ENTRY',
errno: 1062,
sqlMessage: 'Duplicate entry '1' for key 'PRIMARY'',
sqlState: '23000',
index: 0,
sql: 'INSERT INTO user_test(id, user_name) VALUES (1, 'Sawst')',
name: 'QueryFailedError',
query: 'INSERT INTO user_test(id, user_name) VALUES (?, ?)',
parameters: [ 1, 'Sawst' ] }
@pleerock

**Comment by pleerock** [comment]
show me your entity.

**Comment by JingMo** [comment]
I resolve，thanks!

**Comment by darkyelox** [comment]
I hate when people solve problems and don't share how

**Comment by RobinFalko** [comment]
In my case I had accidentally set a wrong relation annotation

```
Transaction
@OneToOne(type => Account, account => account.transactions) //<-- Fix @ManyToOne (of course)
@JoinColumn()
account: Account

Account
@OneToMany(type => Transaction, transactions => transactions.account)
transactions: Transaction[]
```

**Comment by alaj** [comment]
In my case, the type of  primary key is int, but I use a string to update it. Use the right type can fix it.

**Comment by heshaShawky** [comment]
So what the solution for this?!!!!!, I can't find a way on the internet to ignore the duplication and continue adding the rest of the array!! 

I have an array of objects, I need to ignore the duplicate exist object and insert what doesn't, instead of stoping all the insert ?!! ( save )

my code 
```javascript
        return this.articleRepository
            .save(articles);
```

**Comment by qathom** [comment]
Hello,

@heshaShawky 
I'd like to share my approach.
Hope it can help someone.

```ts
function notUnique<Entity>(entityA: Entity, entityB: Entity, tableUnique: (keyof Entity)[]): boolean {
  return tableUnique.reduce((acc, key) => {
    if (entityA[key] === entityB[key]) {
      acc += 1;
    }
    return acc;
  }, 0) === tableUnique.length;
}

/**
 * 
 * @param repository - The entity repository
 * @param entities - The list of entities to save
 * @param tableUnique - The unique constraint argument such as @Unique(['field1', 'field2'])
 */
async function saveAndIgnoreOnDuplicate<Entity>(repository: Repository<Entity>, entities: Entity[], tableUnique: (keyof Entity)[] = []): Promise<Entity[]> {
  try {
    const dbEntities = await repository.find();
    const pushEntities: Entity[] = entities
      // [1] Database duplicates
      .filter((entity) => dbEntities.findIndex(dbEntity => notUnique(entity, dbEntity, tableUnique)) === -1)
      // [2] Same transaction duplicates
      .filter((entity, index, self) => self.findIndex((item) => notUnique(item, entity, tableUnique)) === index);

    return await repository.save(pushEntities);
  } catch (err) {
    if (err.code !== 'ER_DUP_ENTRY') {
      // Throw exception only if it is something else than duplicate entry
      throw err;
    }
  }

  return [];
}

// Usage
import { getRepository } from 'typeorm';

const repository = getRepository(MyEntity);
const items = [
  repository.create({ name: 'Name 1' }),
  repository.create({ name: 'Name 2' }),
  // Duplicate!
  repository.create({ name: 'Name 1' }),
];

// Third parameter must match the table unique constraint, here name is unique
const savedItems = await saveAndIgnoreOnDuplicate<MyEntity>(repository, items, ['name']);

console.log(`Passing ${items.length} to save, new not duplicated items saved: ${savedItems.length}`);
```

**Comment by tripleW1989** [comment]
> In my case, the type of primary key is int, but I use a string to update it. Use the right type can fix it.

Thank U
