### ISSUE TITLE
Cannot save to closure table if schema is used in postgres 

### ISSUE THREAD

**Issue by josephktcheung** [typeorm/typeorm#2043]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Reproduction branch https://github.com/josephktcheung/test-typeorm/tree/feature/closure_table_schema

Here's my ormconfig:
```json
{
  "type": "postgres",
  "host": "localhost",
  "database": "test",
  "port": 5432,
  "synchronize": true,
  "logging": true,
  "schema": "test",
  "entities": [
    "src/entity/**/*.ts"
  ],
  "migrations": [
    "src/migration/**/*.ts"
  ],
  "cli": {
    "migrationsDir": "src/migration"
  }
}
```

My category entity using closure table:
```ts
import { Entity, PrimaryGeneratedColumn, Column, Tree, OneToMany, ManyToOne, TreeChildren, TreeParent } from 'typeorm';

@Entity()
@Tree('closure-table')
export class Category {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;

  // @OneToMany(() => Category, category => category.parent)
  @TreeChildren()
  children: [Category];

  // @ManyToOne(() => Category, category => category.children)
  @TreeParent()
  parent: Category
}
```

My index.ts:
```ts
import 'reflect-metadata';
import { createConnection } from 'typeorm'
import { Category } from './entity/Category';

createConnection().then(async connection => {
  const manager = connection.manager;

  const a1 = new Category();
  a1.name = "a1";
  await manager.save(a1);

  const a11 = new Category();
  a11.name = "a11";
  a11.parent = a1;
  await manager.save(a11);

  const a12 = new Category();
  a12.name = "a12";
  a12.parent = a1;
  await manager.save(a12);

  const a111 = new Category();
  a111.name = "a111";
  a111.parent = a11;
  await manager.save(a111);

  const a112 = new Category();
  a112.name = "a112";
  a112.parent = a11;
  await manager.save(a112);

  const trees = await manager.getTreeRepository(Category).findTrees();

  console.log('trees?', JSON.stringify(trees, null, 2));

});
```

Run index.ts, failed with following error:
```sql
query: INSERT INTO "test"."category"("name", "parentId") VALUES ($1, $2) RETURNING "id" -- PARAMETERS: ["a11",3]
query: INSERT INTO "test"."category_closure"("id_ancestor", "id_descendant") VALUES ($1, $2) -- PARAMETERS: [4,4]
query: INSERT INTO "test.category_closure" ("id_ancestor", "id_descendant") SELECT "id_ancestor", $1 FROM "test.category_closure" WHERE "id_descendant" = $2 -- PARAMETERS: [4,3]
query failed: INSERT INTO "test.category_closure" ("id_ancestor", "id_descendant") SELECT "id_ancestor", $1 FROM "test.category_closure" WHERE "id_descendant" = $2 -- PARAMETERS: [4,3]
error: { error: relation "test.category_closure" does not exist
    at Connection.parseE (/Users/josephcheung/workspace/zeep/repos/test-typeorm/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/josephcheung/workspace/zeep/repos/test-typeorm/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/josephcheung/workspace/zeep/repos/test-typeorm/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 120,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable' }
query: ROLLBACK
```
Last sql statement omitted 2 double quotes in `"test.category_closure"`, should be `"test"."category_closure"`, hence it cannot find the correct table to insert.

**Comment by pleerock** [comment]
what is your typeorm version?

**Comment by josephktcheung** [comment]
Sorry, missed the info. It's 0.2.3

**Comment by pleerock** [comment]
fix will be released in 0.2.4
