### ISSUE TITLE
Foreign Key Contraints

### ISSUE THREAD

**Issue by ShadabFaiz** [typeorm/typeorm#2073]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.1.9`

These are my Entities:
``` typescript
@Entity()
export class EvaluationResponse {

    @PrimaryGeneratedColumn()
    responseId: number;

    @OneToOne(type=>UserTestEvaluation)
    @JoinColumn()
    evaluation: UserTestEvaluation;

    @OneToOne(type=>Question)
    @JoinColumn()
    question: Question;
}

@Entity()
export class Question extends AuditedModel{

    @PrimaryColumn("int")
    questionId: number;

    @PrimaryColumn("int")
    langId: number;

    @OneToOne(type => OptionType, {eager: true})
    @JoinColumn()
    Column3: OptionType;
}
```
This is my config
``` typescript
"type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "root",
    "password": "mysqlPassword4!",
    "database": "mmcnew",
    "synchronize": true,
    "logging": true,
    "entities": [
        "src/entity/**/*.ts"
    ],
    "migrations": [
        "src/migration/**/*.ts"
    ],
    "subscribers": [
        "src/subscriber/**/*.ts"
    ],
    "cli": {
        "entitiesDir": "src/entity",
        "migrationsDir": "src/migration",
        "subscribersDir": "src/subscriber"
    }
```
**Expected behavior:**   
When i start my server, the foreign key should be created without any problem.
**Actual behavior thats occuring:**
Getting Foreign KEy Contraints error.
``` typescript
executing query:  ALTER TABLE `mmcnew`.`evaluation_response` DROP FOREIGN KEY `fk_74e9b2ea9edcea47af52698d876`
query failed:  ALTER TABLE `mmcnew`.`evaluation_response` DROP FOREIGN KEY `fk_74e9b2ea9edcea47af52698d876`
error:  { Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'fk_74e9b2ea9edcea47af52698d876'; check that column/key exists
    at Query.Sequence._packetToError (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (/home/Faiz/Git-Repos/MMC/Server/src/driver/mysql/MysqlQueryRunner.ts:191:36)
    at step (/home/Faiz/Git-Repos/MMC/Server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/home/Faiz/Git-Repos/MMC/Server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at fulfilled (/home/Faiz/Git-Repos/MMC/Server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlMessage: 'Can\'t DROP \'fk_74e9b2ea9edcea47af52698d876\'; check that column/key exists',
  sqlState: '42000',
  index: 0,
  sql: 'ALTER TABLE `mmcnew`.`evaluation_response` DROP FOREIGN KEY `fk_74e9b2ea9edcea47af52698d876`' }
executing query:  ROLLBACK
(node:12566) UnhandledPromiseRejectionWarning: QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'fk_74e9b2ea9edcea4
    at new QueryFailedError (/home/Faiz/Git-Repos/MMC/Server/src/error/QueryFailedError.ts:7:9)
    at Query._callback (/home/Faiz/Git-Repos/MMC/Server/src/driver/mysql/MysqlQueryRunner.ts:202:37)
    at Query.Sequence.end (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/Faiz/Git-Repos/MMC/Server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```
However, if i change my `Question` entity to have an alias name like this:
``` typescript
@Entity("Question")
export class Question extends AuditedModel{
```
then, i don't get any error.
But, on using `OneToMany` relation with the below entity, doesn't give any error.
``` typescript
@Entity()
export class MMCTest {
    @PrimaryColumn("int")
    testId: number;

    @CreateDateColumn()
    createdDate: Date;

    @UpdateDateColumn()
    updatedDate: Date;

    @OneToMany(type => Question, question => question.test)
    questions: Question[];
}
```
Does `OneToOne` relation needs the associated entity to have alias name? If so, then why the [the doc here](http://typeorm.io/#/one-to-one-relations) doesn't say anything about it.

**Comment by ShadabFaiz** [comment]
By "Reproduction Repository", you mean i should create a new repository containing the project?

**Comment by pleerock** [comment]
not your project, minimal reproduction git repository that reproducing issue you are talking about.

**Comment by ShadabFaiz** [comment]
After some experimentation, this is my conclusion on this matter.
I start my server for the 1st time, and enter store data for some entity in the database.
Then, i changed the structure for my entity ( lets says i added some columns or changed the relations between 2 entities ). After that, i start my server for 2nd time, but since the schema for the entity got changed, a new foreign key is needed to created, but since i have already stored some data in the database for this entity. the foreign key cannot be dropped without the emptying the table. Thus the problem.

**Comment by ShadabFaiz** [comment]
Thanks for your time.

**Comment by chinanderm** [comment]
@ShadabFaiz What was the conclusion to the issue here?

**Comment by OluwapelZ** [comment]
> @ShadabFaiz What was the resolution to the issue here?

Co-ask @ShadabFaiz
