### ISSUE TITLE
One-to-One relation, parent.save() -> parent.relationID undefined

### ISSUE THREAD

**Issue by andrewexton373** [typeorm/typeorm#2119]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I might be misunderstanding the use of One-to-One relations, but I've tried to stick as close as possible to this [one-to-one example](https://github.com/typeorm/typeorm/tree/master/sample/sample2-one-to-one) repository, but not having any luck getting the entity to save the relation attribute. Any help would be great! I tried looking through existing issues, but wasn't having any luck as they resembled the example repository.

**Steps to reproduce or a small repository showing the problem:**

## User.ts
```ts
import { Entity, Column, BaseEntity, PrimaryColumn, BeforeInsert, OneToOne, JoinColumn } from "typeorm";
import { Profile } from "./Profile";
import * as uuidv4 from "uuid/v4";

@Entity("users")
export class User extends BaseEntity {
  @PrimaryColumn("uuid") id: string;

  @Column("varchar", { length: 255 })
  email: string;

  @Column("text") password: string;

  @Column("boolean", { default: false })
  confirmed: boolean;

  @OneToOne(() => Profile, {
    cascade: ["update"]
  })
  @JoinColumn()
  profile: Profile;

  @BeforeInsert()
  addId() {
    this.id = uuidv4();
  }
}
```

##Profile.ts
```ts
import { Entity, Column, BaseEntity, PrimaryGeneratedColumn, OneToOne } from "typeorm";
import { User } from "./User";

@Entity("profiles")
export class Profile extends BaseEntity {
    @PrimaryGeneratedColumn() id: number;

    @Column("varchar", { nullable: true, length: 255 })
    displayName: string;

    @OneToOne(() => User, user => user.profile, {
        cascade: true
    })
    user: User;
}
```

## Code that creates a user, should link the profile?
```ts
const profile = Profile.create({displayName: "TEST"});
      await profile.save();

      console.log(profile);

      const hashedPassword = await bcrypt.hash(password, 10);
      const user = User.create({
        email,
        password: hashedPassword,
        profile
      });

      console.log(profile);

      await user.save();

      console.log(user);
```

##Test case output, user.profile is undefined after user.save()?
```bash
    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      63 |     expect(user.email).toEqual(email2);
      64 |     expect(user.password).not.toEqual(password);
    > 65 |     expect(user.profile).toBeDefined();
      66 |
      67 |     const profiles = await Profile.find({ where: { uid: user.id }});
      68 |     expect(profiles).toHaveLength(1);

      at Object.<anonymous> (src/modules/register/register.test.ts:65:26)
      at fulfilled (src/modules/register/register.test.ts:4:56)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 skipped, 5 total
Snapshots:   0 total
Time:        0.935s, estimated 1s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.query: SELECT "Profile"."id" AS "Profile_id", "Profile"."displayName" AS "Profile_displayName" FROM "profiles" "Profile" WHERE ("Profile"."id" = $1) -- PARAMETERS: [1]
query: START TRANSACTION
query: INSERT INTO "users"("id", "email", "password", "confirmed", "profileId") VALUES ($1, $2, $3, DEFAULT, $4) RETURNING "confirmed" -- PARAMETERS: ["9f276ac3-f076-4f03-9534-5b3f5478eed3","tom2@bob.com","$2a$10$p9OcUUF6cjCb5D1OhJ0BQOs/V/84olIeeex16dyT89AB/vnnO./RO",1]
query: COMMIT
User {
  email: 'tom2@bob.com',
  password: '$2a$10$p9OcUUF6cjCb5D1OhJ0BQOs/V/84olIeeex16dyT89AB/vnnO./RO',
  profile: Profile { id: 1, displayName: 'TEST' },
  id: '9f276ac3-f076-4f03-9534-5b3f5478eed3',
  confirmed: false }
  console.log node_modules/typeorm/platform/PlatformTools.js:209
    query: SELECT "User"."id" AS "User_id", "User"."email" AS "User_email", "User"."password" AS "User_password", "User"."confirmed" AS "User_confirmed", "User"."profileId" AS "User_profileId" FROM "users" "User" WHERE "User"."email" = $1 -- PARAMETERS: ["tom2@bob.com"]

  console.log src/modules/register/register.test.ts:62
    User {
      id: '9f276ac3-f076-4f03-9534-5b3f5478eed3',
      email: 'tom2@bob.com',
      password: '$2a$10$p9OcUUF6cjCb5D1OhJ0BQOs/V/84olIeeex16dyT89AB/vnnO./RO',
      confirmed: false }
```

**Comment by pleerock** [comment]
There is one small issue here: 

```ts
  @OneToOne(() => Profile, {
    cascade: ["update"]
  })
  @JoinColumn()
  profile: Profile;
```
you need to specify inverse side: 

```ts
  @OneToOne(() => Profile, profile => profile.user, { ... })
```

But it isn't an issue. Probably issue with `User.create`, try to manually assign profile:

```ts
const user = Object.assign(User.create(), {
        email,
        password: hashedPassword,
        profile
      });
```

**Comment by andrewexton373** [comment]
I appreciate your quick response! I tried those changes, but still no success..

## User.ts w/ Inverse Side
```ts
@OneToOne(() => Profile, profile => profile.user, {
    cascade: ["update"]
  })
  @JoinColumn()
  profile: Profile;
```

## Profile.ts
```ts
@OneToOne(() => User, user => user.profile, {
        cascade: true
    })
    user: User;
```

## With Object.assign()
```ts
const profile = Profile.create({displayName: "TEST"});
      await profile.save();

      console.log(profile);

      const hashedPassword = await bcrypt.hash(password, 10);
      const user = Object.assign(User.create(), {
        email,
        password: hashedPassword,
        profile
      });

      await user.save();

      console.log(user);
```

## Test output
```bash
query: SELECT "Profile"."id" AS "Profile_id", "Profile"."displayName" AS "Profile_displayName" FROM "profiles" "Profile" WHERE ("Profile"."id" = $1) -- PARAMETERS: [1]
query: START TRANSACTION
query: INSERT INTO "users"("id", "email", "password", "confirmed", "profileId") VALUES ($1, $2, $3, DEFAULT, $4) RETURNING "confirmed" -- PARAMETERS: ["3799a7e7-27b1-4327-afc4-2028c80cf00c","tom2@bob.com","$2a$10$So0mFH6u1X/0SN4pC9PpTO90NgOMlfBDUIXANqKiX5G/V4qRyf/Rm",1]
query: COMMIT
User {
  email: 'tom2@bob.com',
  password: '$2a$10$So0mFH6u1X/0SN4pC9PpTO90NgOMlfBDUIXANqKiX5G/V4qRyf/Rm',
  profile: Profile { displayName: 'TEST', id: 1 },
  id: '3799a7e7-27b1-4327-afc4-2028c80cf00c',
  confirmed: false }
  console.log node_modules/typeorm/platform/PlatformTools.js:209
    query: SELECT "User"."id" AS "User_id", "User"."email" AS "User_email", "User"."password" AS "User_password", "User"."confirmed" AS "User_confirmed", "User"."profileId" AS "User_profileId" FROM "users" "User" WHERE "User"."email" = $1 -- PARAMETERS: ["tom2@bob.com"]

  console.log src/modules/register/register.test.ts:62
    User {
      id: '3799a7e7-27b1-4327-afc4-2028c80cf00c',
      email: 'tom2@bob.com',
      password: '$2a$10$So0mFH6u1X/0SN4pC9PpTO90NgOMlfBDUIXANqKiX5G/V4qRyf/Rm',
      confirmed: false }
```

**Comment by pleerock** [comment]
> query: INSERT INTO "users"("id", "email", "password", "confirmed", "profileId") VALUES ($1, $2, $3, DEFAULT, $4) RETURNING "confirmed" -- PARAMETERS: ["3799a7e7-27b1-4327-afc4-2028c80cf00c","tom2@bob.com","$2a$10$So0mFH6u1X/0SN4pC9PpTO90NgOMlfBDUIXANqKiX5G/V4qRyf/Rm",1]


from your log it does link the profile. Where your select comes from? Did you join your profile on that select (looks like no)

**Comment by andrewexton373** [comment]
How could I have missed that?? Thanks!!!

For anyone else that may stumble upon this silly mistake,

```ts
const user = await User.findOne(userID, {relations: ["profile"]});
expect(user).toBeDefined();
expect(user!.email).toEqual(email2);
expect(user!.password).not.toEqual(password);
expect(user!.profile).toBeDefined();
```
