### ISSUE TITLE
Repository.findOne

### ISSUE THREAD

**Issue by JingMo** [typeorm/typeorm#2140]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**

``
```
    try {
      let conditions = {  id: 2000 };
      let result = await this.vendorRepository.findOne(conditions);
      return result;
    } catch (e) {
      console.log(e)
      return { errCode: -1, errorMsg: 'query error' };
    }
```
if '2000' is non-existing id, error occurred:

Error
    at NotFoundError.HttpError [as constructor] (E:\Projects\suppier-management-api\node_modules\routing-controllers\http-error\HttpError.js:27:23)
    at new NotFoundError (E:\Projects\suppier-management-api\node_modules\routing-controllers\http-error\NotFoundError.js:20:28)
    at ExpressDriver.handleSuccess (E:\Projects\suppier-management-api\node_modules\routing-controllers\driver\express\ExpressDriver.js:289:23)
    at E:\Projects\suppier-management-api\node_modules\routing-controllers\RoutingControllers.js:128:61
    at process._tickCallback (internal/process/next_tick.js:109:7)

I think that it should return {}, but no.
otherwise, it does not go catch branch.

need help, thanks!

**Comment by pleerock** [comment]
Everything is expected. If object not found then result will be equal to `undefined`. If you want it to throw an error use `findOneOrFail` method instead

**Comment by JingMo** [comment]
thanks! @pleerock
