### ISSUE TITLE
SQLite. Migration. QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: roles.id

### ISSUE THREAD

**Issue by vadim-shilov** [typeorm/typeorm#2152]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello!
It seems that the ID generation for sqlite doesn't work when starting the migration. I use sqlite v2.9.2.
For postgres it's OK.
Maybe I'm doing something wrong?

My code:
```
// entity
@Entity('roles')
export class Role {
  @PrimaryGeneratedColumn()
  @IsOptional()
  @IsInt()
  @IsPositive()
  id: number;

  @Column({ length: 50, unique: true })
  @IsEnum(UserRoles)
  @IsNotEmpty()
  @MaxLength(255, { message: 'name is too long (max length is 50)' })
  name: string;

  @Column({ length: 255 })
  @IsString()
  @MaxLength(255, { message: 'description is too long (max length is 255)' })
  description: string;
}

// migration
public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createTable(new Table({
      name: 'users',
      columns: [
        {
          name: 'id',
          type: 'int',
          isPrimary: true,
          isGenerated: true,
        },
        {
          name: 'name',
          type: 'varchar',
          length: '255',
        },
        {
          name: 'email',
          type: 'varchar',
          length: '255',
          isUnique: true,
        },
        {
          name: 'password',
          type: 'varchar',
          length: '255',
        },
        {
          name: 'status',
          type: 'varchar',
          length: '25',
        },
        {
          name: 'created_at',
          type: 'timestamp',
          default: 'CURRENT_TIMESTAMP',
        },
        {
          name: 'updated_at',
          type: 'timestamp',
          default: 'CURRENT_TIMESTAMP',
        },
      ],
    }), true);

    await queryRunner.createIndex('users', new TableIndex({
      name: 'IDX_USER_EMAIL',
      columnNames: ['email'],
    }));

    await queryRunner.createTable(new Table({
      name: 'roles',
      columns: [
        {
          name: 'id',
          type: 'int',
          isPrimary: true,
          isGenerated: true,
        },
        {
          name: 'name',
          type: 'varchar',
          length: '50',
          isUnique: true,
        },
        {
          name: 'description',
          type: 'varchar',
          length: '255',
        },
      ],
    }), true);

    await queryRunner.createTable(new Table({
      name: 'users_and_roles',
      columns: [
        {
          name: 'user_id',
          type: 'int',
          isPrimary: true,
        },
        {
          name: 'role_id',
          type: 'int',
          isPrimary: true,
        },
      ],
    }), true);

    await queryRunner.createForeignKey('users_and_roles', new TableForeignKey({
      columnNames: ['user_id'],
      referencedColumnNames: ['id'],
      referencedTableName: 'users',
      onDelete: 'CASCADE',
    }));

    await queryRunner.createForeignKey('users_and_roles', new TableForeignKey({
      columnNames: ['role_id'],
      referencedColumnNames: ['id'],
      referencedTableName: 'roles',
      onDelete: 'CASCADE',
    }));

    let adminRole = new Role();
    adminRole.name = UserRoles.ADMIN;
    adminRole.description = 'An admin user';
    adminRole = await queryRunner.manager.save(adminRole);

    const individualRole = new Role();
    individualRole.name = UserRoles.INDIVIDUAL;
    individualRole.description = 'An individual user';
    await queryRunner.manager.save(individualRole);

    const corporateRole = new Role();
    corporateRole.name = UserRoles.CORPORATE;
    corporateRole.description = 'A corporate user';
    await queryRunner.manager.save(corporateRole);

    const admin = new User();
    const salt = await genSalt();
    admin.name = 'Administrator';
    admin.email = 'example@gmail.com';
    admin.password = await hash('Some_password', salt);
    admin.status = UserStatuses.ACTIVE;
    admin.roles = [adminRole];
    await queryRunner.manager.save(admin);
  }

Error log:
Error: Command failed: ts-node ./node_modules/typeorm/cli.js migration:run
{ QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: roles.id
    at new QueryFailedError (---/src/error/QueryFailedError.ts:7:9)
    at Statement.handler (---/src/driver/sqlite/SqliteQueryRunner.ts:53:26)
  message: 'SQLITE_CONSTRAINT: NOT NULL constraint failed: roles.id',
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  name: 'QueryFailedError',
  query: 'INSERT INTO "roles"("name", "description") VALUES (?, ?)',
  parameters: [ 'admin', 'An admin user' ] }
```

**Comment by pleerock** [comment]
Try to specify a generation strategy please:

```ts
 columns: [
        {
          name: 'id',
          type: 'int',
          isPrimary: true,
          isGenerated: true,
          generationStrategy: "increment",
```

**Comment by vadim-shilov** [comment]
Thank you! Now it works!
