### ISSUE TITLE
ormconfig.json does not work with db other than Test (db name and user ignoring) 

### ISSUE THREAD

**Issue by Antibioticvz** [typeorm/typeorm#2171]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`
Postgres app 10 v 2.1.4

**TypeORM version:**
 `0.2.5` 

I use macOS Sierra 10.12.5
**Steps to reproduce:**
```
typeorm init --name TestDB --database postgres
cd testdb
yarn
createdb testdb
createuser testuser
```
ormconfig.json
```
{
   "type": "postgres",
   "host": "localhost",
   "port": 5432,
   "username": "testuser",
   "password": "",
   "database": "testdb",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}

```
`npm start`
If Test db and Test user does not exist I have this error
```
{ error: database "test" does not exist
    at Connection.parseE (/Users/ninjamate/Documents/projects/TestDB/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/ninjamate/Documents/projects/TestDB/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/ninjamate/Documents/projects/TestDB/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 89,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '846',
  routine: 'InitPostgres' }
```
Otherwise I can normally use the Test db even if the ormconfig.json looks like this.
```
"username": "testuser",
   "password": "",
   "database": "testdb",
```
works with Test db
```
Inserting a new user into the database...
Saved a new user with id: 1
Loading users from the database...
Loaded users:  [ User { id: 1, firstName: 'Timber', lastName: 'Saw', age: 25 } ]
Here you can setup and run express/koa/any other framework.
```

**Comment by pleerock** [comment]
the name and user are not ignored. Problem is from your side, check your settings, check if you created everything correctly, etc.

**Comment by Antibioticvz** [comment]
@pleerock Visual Studio Code was a problem some how. Tried to restart it, does not work but when I opened this project in Jetbrain phpstorm and after that all work. Now all work on any ide.
