### ISSUE TITLE
ambiguous column name error with left join

### ISSUE THREAD

**Issue by marceloverdijk** [typeorm/typeorm#2219]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 2 simple entities (`Continent` and `Country`) like:

```
@Entity("continent", {
    orderBy: {
        id: "ASC"
    }
})
export class Continent {

    @PrimaryColumn({ name: "id" })
    public id?: string;

    @Column({ name: "code" })
    public code?: string;

    @Column({ name: "name" })
    public name?: string;

    @Column({ name: "demonym" })
    public demonym?: string;
}

@Entity("country", {
    orderBy: {
        id: "ASC"
    }
})
export class Country extends BaseEntity {

    @PrimaryColumn({ name: "id" })
    public id?: string;

    @Column({ name: "alpha2_code" })
    public alpha2Code?: string;

    @Column({ name: "alpha3_code" })
    public alpha3Code?: string;

    @Column({ name: "name" })
    public name?: string;

    @Column({ name: "demonym" })
    public demonym?: string;

    @JoinColumn({ name: "continent_id" })
    @ManyToOne(type => Continent, { eager: true })
    public continent?: Continent;
}
```

Note the `@ManyToOne` and `@JoinColumn` decorators on the `Country.continent` field (fetching the continent relation eagerly).

Now when I do:

```
const repository = getRepository(Country);
await repository.findOne("belgium");
```

the country is fetched successfully including the continent.

The query generated by typeorm looked like:

```
SELECT "country"."id"                AS "Country_id", 
       "country"."alpha2_code"       AS "Country_alpha2_code", 
       "country"."alpha3_code"       AS "Country_alpha3_code", 
       "country"."name"              AS "Country_name", 
       "country"."demonym"           AS "Country_demonym", 
       "country"."continent_id"      AS "Country_continent_id", 
       "Country_continent"."id"      AS "Country_continent_id", 
       "Country_continent"."code"    AS "Country_continent_code", 
       "Country_continent"."name"    AS "Country_continent_name", 
       "Country_continent"."demonym" AS "Country_continent_demonym" 
FROM   "country" "Country" 
       LEFT JOIN "continent" "Country_continent" 
              ON "Country_continent"."id" = "country"."continent_id" 
WHERE  "country"."id" = ? 
ORDER  BY "country"."id" ASC 
```

Note the `AS "Country_continent_id", ` is twice in `SELECT` part but it gives no problems.

Executing the following:

```
const repository = getRepository(Country);
await repository.find();
```

gives the error:

```
error: { Error: SQLITE_ERROR: ambiguous column name: Country_continent.id errno: 1, code: 'SQLITE_ERROR' }
QueryFailedError: SQLITE_ERROR: ambiguous column name: Country_continent.id
    at new QueryFailedError (/Users/marceloverdijk/workspace/myapp/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at handler (/Users/marceloverdijk/workspace/myapp/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:92:38)
    at replacement (/Users/marceloverdijk/workspace/myapp/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/marceloverdijk/workspace/myapp/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

Looking at the query generated:

```
SELECT "country"."id"                AS "Country_id", 
       "country"."alpha2_code"       AS "Country_alpha2_code", 
       "country"."alpha3_code"       AS "Country_alpha3_code", 
       "country"."name"              AS "Country_name", 
       "country"."demonym"           AS "Country_demonym", 
       "country"."continent_id"      AS "Country_continent_id", 
       "Country_continent"."id"      AS "Country_continent_id", 
       "Country_continent"."code"    AS "Country_continent_code", 
       "Country_continent"."name"    AS "Country_continent_name", 
       "Country_continent"."demonym" AS "Country_continent_demonym", 
       "Country_continent"."id"      AS "Country_continent_id", 
       "Country_continent"."code"    AS "Country_continent_code", 
       "Country_continent"."name"    AS "Country_continent_name", 
       "Country_continent"."demonym" AS "Country_continent_demonym", 
       country_continent 
FROM   "country" "Country" 
       LEFT JOIN "continent" "Country_continent" 
              ON "Country_continent"."id" = "country"."continent_id" 
       LEFT JOIN "continent" "Country_continent" 
              ON "Country_continent"."id" = "country"."continent_id" 
ORDER  BY "country"."id" ASC 
```

Here the `AS "Country_continent_id"` is even three time in the `SELECT` part and the `LEFT JOIN` on continent two times.
And in this query sqlite seems not to be happy anymore.

Is this a bug or am I doming something wrong here?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by marceloverdijk** [comment]
There was something wrong with my build output directory causing this issue.
