### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined in PostgresQueryRunner.createEnumTypeSql

### ISSUE THREAD

**Issue by lorenzleutgeb** [typeorm/typeorm#2233]
**Issue type:** bug report

**Database system/driver:** `postgres`

**TypeORM version:** `0.2.6` as reported by
```
$ typeorm version
Local installed version: 0.2.6
Global installed TypeORM version: 0.2.6
```

**Steps to reproduce or a small repository showing the problem:**

The cause seems to be this entity:

```ts
enum State {
    Running = 0,
    Completed = 1,
}

@Entity('presence_list_item')
export class Presence {
    @PrimaryGeneratedColumn('uuid')
    public id!: string

    @Column('enum', {nullable: false})
    public state!: State
}
```

And TypeORM dies when I attempt to sync the schema:

```
$ typeorm schema:sync         
query: START TRANSACTION
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE ...
query: SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "cnst"."conname" AS "constraint_name", "cnst"."consrc" AS "expression", CASE "cnst"."contype" WHEN 'p' THEN 'PRIMARY' WHEN 'u' THEN 'UNIQUE' WHEN 'c' THEN 'CHECK' END AS "constraint_type", "a"."attname" AS "column_name" FROM "pg_constraint" "cnst" INNER JOIN "pg_class" "t" ON "t"."oid" = "cnst"."conrelid" INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "cnst"."connamespace" INNER JOIN "pg_attribute" "a" ON "a"."attrelid" = "cnst"."conrelid" AND "a"."attnum" = ANY ("cnst"."conkey") WHERE ...
query: SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "i"."relname" AS "constraint_name", "a"."attname" AS "column_name", CASE "ix"."indisunique" WHEN 't' THEN 'TRUE' ELSE'FALSE' END AS "is_unique", pg_get_expr("ix"."indpred", "ix"."indrelid") AS "condition" FROM "pg_class" "t" INNER JOIN "pg_index" "ix" ON "ix"."indrelid" = "t"."oid" INNER JOIN "pg_attribute" "a" ON "a"."attrelid" = "t"."oid"  AND "a"."attnum" = ANY ("ix"."indkey") INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "t"."relnamespace" INNER JOIN "pg_class" "i" ON "i"."oid" = "ix"."indexrelid" LEFT JOIN "pg_constraint" "cnst" ON "cnst"."conname" = "i"."relname" WHERE ...
query: SELECT "con"."conname" AS "constraint_name", "con"."nspname" AS "table_schema", "con"."relname" AS "table_name", "att2"."attname" AS "column_name", "ns"."nspname" AS "referenced_table_schema", "cl"."relname" AS "referenced_table_name", "att"."attname" AS "referenced_column_name", "con"."confdeltype" AS "on_delete", "con"."confupdtype" AS "on_update" FROM ( SELECT UNNEST ("con1"."conkey") AS "parent", UNNEST ("con1"."confkey") AS "child", "con1"."confrelid", "con1"."conrelid", "con1"."conname", "con1"."contype", "ns"."nspname", "cl"."relname", CASE "con1"."confdeltype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confdeltype", CASE "con1"."confupdtype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confupdtype" FROM "pg_class" "cl" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_constraint" "con1" ON "con1"."conrelid" = "cl"."oid" WHERE ...
...
creating a new table: presence_list_item
query: SELECT "n"."nspname", "t"."typname" FROM "pg_type" "t" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "t"."typnamespace" WHERE "n"."nspname" = current_schema() AND "t"."typname" = 'presence_list_item_state_enum'
query: ROLLBACK
Error during schema synchronization:
TypeError: Cannot read property 'map' of undefined
    at PostgresQueryRunner.createEnumTypeSql (~/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:2046:38)
    at PostgresQueryRunner.<anonymous> (~/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:447:69)
    at step (~/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:42:23)
    at Object.next (~/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:23:53)
    at fulfilled (~/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by pleerock** [comment]
you have to provide enum this way:

```ts
    @Column('enum', { nullable: false, enum: State })
    public state!: State
```

**Comment by lorenzleutgeb** [comment]
Oh, I see. Sorry then. Maybe you could detect this error and inform users like me with a nicer error message? That would be super nice.

**Comment by pleerock** [comment]
yes you are right, we'll do that. thank you

**Comment by GitStorageOne** [comment]
Same error happen when Enum used as primary key with Tree decorator:
```typescript

export enum EnumPermission {
  test = 'test'
}

@Entity()
@Tree('materialized-path')
export class Permission extends BaseEntity {

  @PrimaryColumn('enum', { name: 'id', enum: EnumPermission })
  id: EnumPermission;

  // tested also with EnumPermission.
  @Column('varchar', { name: 'parentId', nullable: true })
  parentId: string | null;

  @TreeParent()
  parent: Permission;

  @TreeChildren()
  children: Permission[];

}
```

**Comment by smonv** [comment]
Any update on this issue? I got the same error with @GitStorageOne

**Comment by aaronryden** [comment]
@smonv i was able to fix like this

```

export enum EUserRole {
  CREATOR = "creator",
  MANAGER = "manager",
}

... inside Entity()

@Column({
    name: 'user_role',
    type: 'enum',
    enum: EUserRole,
    default: EUserRole.CREATOR,
  })
  role: EUserRole;

```

**Comment by lorenzleutgeb** [comment]
> @smonv i was able to fix like this

**Comment by smonv** [comment]
@aaronryden Thanks for the fix. I'll try again

**Comment by alex88** [comment]
I've tried to make the enum column a primary key and I'm getting this error, so basically
```
  @Column({
    type: 'enum',
    enum: NotificationTypeCode,
    nullable: false,
    unique: true
  })
  type: NotificationTypeCode;
```
works fine however
```
  @PrimaryColumn({
    type: 'enum',
    enum: NotificationTypeCode,
    nullable: false
  })
  type: NotificationTypeCode;
```
and
```
  @Column({
    type: 'enum',
    enum: NotificationTypeCode,
    nullable: false,
    primary: true
  })
  type: NotificationTypeCode;
```
do not

**Comment by nantoniazzi** [comment]
Same issue with primary key too. Any update on this?

**Comment by williamdes** [comment]
This can also trigger the error "at PostgresQueryRunner.createEnumTypeSql" (removing the enum type):
```diff
    @Column({
        type: 'enum',
-       enum: TaxesRateEnum,
    })
    taxesRate: TaxesRateEnum;
```

**Comment by jldillman** [comment]
I had this same problem and was able to resolve it by making sure I defined the TypeScript enum in the same file as the entity definition that uses it, instead of trying to import the TypeScript enum from an external file.

**Comment by brahn** [comment]
Same experience as @jldillman -- any idea why the location of the enum declaration would matter?

**Comment by dadooda** [comment]
Guys, are there any known solutions for this? This kind of cr%p definitely hits scalability badly. I've hit the case when I have a generic `State` enum type which is shared across several entities, there is no "single file", where the enum can be put to next to the entity using it.

**Comment by suyamasrc** [comment]
I tried to `migrate:generate` and encountered the same problem.
I inserted debugging code in `createEnumTypeSql` function and found what Enum definition caused the error.
I cleaned `dist` folder and I resolved it!

**Comment by piosystems** [comment]
This issue is back after update to the current typeorm version 0.2.32. The solution indicated by @jldillman  (i.e. define the enum in the same entity) works but it is certainly not the best where the same enum definition has to be used in several different modules.

**Comment by glothos** [comment]
If someone else is facing this issue using Nest.js, remove dist folder generated when you run the Nest application.  This should erase any other migrations generated when typeorm module has synchronization set to true.

**Comment by gopricy** [comment]
this issue should reopen

**Comment by st3v3y** [comment]
> If someone else is facing this issue using Nest.js, remove dist folder generated when you run the Nest application. This should erase any other migrations generated when typeorm module has synchronization set to true.

I am facing this issue with Nest.js on my staging server (locally it works) when running 'npm run schema:sync'. Erasing the dist folder didn't solve it. :/

**Comment by imnotjames** [comment]
Given we had supposedly fixed this and the original issue is from 2018 - should you believe this has happened again after we merged in this code please open a new issue with new reproduction information.
