### ISSUE TITLE
Error closing connection when usePool: false

### ISSUE THREAD

**Issue by benny-medflyt** [typeorm/typeorm#224]
Pretty sure this is a genuine bug this time:

``` typescript
import "reflect-metadata";
import { createConnection } from "typeorm";
import { Table, PrimaryGeneratedColumn } from "typeorm";

@Table()
export class Photo {
    @PrimaryGeneratedColumn()
    id: number;
}

createConnection({
    driver: {
        type: "postgres",
        usePool: false, // No bug when set to true
        host: "localhost",
        port: 5432,
        database: "mydb",
        username: "dbuser",
        password: "mypassword"
    },
    entities: [Photo],
    autoSchemaSync: true
}).then(async (connection) => {
    console.log('hello');
    await connection.close();
    return;
}).catch((error) => {
    console.error('Error: ', error, error.stack);
});
```

```
hello
Error:  [TypeError: Cannot read property 'end' of undefined] TypeError: Cannot read property 'end' of undefined
    at /Users/benny/proj/node_modules/typeorm/driver/postgres/PostgresDriver.js:129:27
    at PostgresDriver.disconnect (/Users/benny/proj/node_modules/typeorm/driver/postgres/PostgresDriver.js:117:16)
    at Connection.<anonymous> (/Users/benny/proj/node_modules/typeorm/connection/Connection.js:193:58)
    at step (/Users/benny/proj/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/Users/benny/proj/node_modules/typeorm/connection/Connection.js:13:53)
    at /Users/benny/proj/node_modules/typeorm/connection/Connection.js:7:65
    at __awaiter (/Users/benny/proj/node_modules/typeorm/connection/Connection.js:3:12)
    at Connection.close (/Users/benny/proj/node_modules/typeorm/connection/Connection.js:187:16)
    at Object.<anonymous> (/Users/benny/proj/_build/bug_test.js:47:22)
    at next (native)
```

**Comment by pleerock** [comment]
I'll try to test it and reproduce this issue, however why do you want to have pool disabled? In what case it does make sense for you?

**Comment by benny-medflyt** [comment]
I found the bug. It is in in `PostgresDriver` `disconnect` method:

<https://github.com/typeorm/typeorm/blob/b995b7ca2a09559b03cb301ecf3e0b9448bf4eb9/src/driver/postgres/PostgresDriver.ts#L169>

This is the offending conditional:

```typescript
            if (this.databaseConnectionPool) {
```

When `usePool` is false, the value of this member variable during disconnect is `[]` (which makes sense). But in JavaScript the empty array evaluates to true. The fix is to change the conditional to:

```typescript
            if (this.pool) {
```

**Comment by pleerock** [comment]
do you want to make a PR for this change?

**Comment by pleerock** [comment]
Thank you!
