### ISSUE TITLE
clsesAndStrings.filter is not a function

### ISSUE THREAD

**Issue by luozhihua** [typeorm/typeorm#2275]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Connection configs
```ts
const DB_CONNECTION = {
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'colin',
    password: 'xxxxxx',
    database: 'xxxxxx',
    synchronize: true,
    logging: false,
    cache: true,
    entities: path.join(__dirname, '../orm/entity/**/*.js'),
    migrations: path.join(__dirname, '../orm/migration/**/*.js'),
    subscribers: path.join(__dirname, '../orm/subscriber/**/*.js')
};

createConnection(DB_CONNECTION)
  .then(async () => {
     // ...
  })
```

Error:
```
TypeError: clsesAndStrings.filter is not a function
    at Function.OrmUtils.splitClassesAndStrings (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/util/OrmUtils.js:19:31)
    at ConnectionMetadataBuilder.buildSubscribers (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:35:38)
    at Connection.buildMetadatas (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/Connection.js:506:53)
    at Connection.<anonymous> (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/Connection.js:162:30)
    at step (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/Connection.js:13:53)
    at fulfilled (/Users/colin/Projects/fengwo/fengwocms/server/node_modules/typeorm/connection/Connection.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by pleerock** [comment]
```ts
    entities: path.join(__dirname, '../orm/entity/**/*.js'),
    migrations: path.join(__dirname, '../orm/migration/**/*.js'),
    subscribers: path.join(__dirname, '../orm/subscriber/**/*.js')
```

must be:

```ts
    entities: [path.join(__dirname, '../orm/entity/**/*.js')],
    migrations: [path.join(__dirname, '../orm/migration/**/*.js')],
    subscribers: [path.join(__dirname, '../orm/subscriber/**/*.js')]
```

e.g. you should use arrays

**Comment by luozhihua** [comment]
Thanks, works now.
