### ISSUE TITLE
getRepository in migration does not respect schema

### ISSUE THREAD

**Issue by ffittschen** [typeorm/typeorm#2321]
## Issue type:

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

## Database system/driver:

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

## TypeORM version:

[x] `latest`
[ ] `@next`
[x] `0.2.6` (or put your version here)

## Steps to reproduce or a small repository showing the problem:

Note: The postgres db uses the default `public` schema

#### Expected Results
- getRepository(User) should generate a query that reflects the schema
```sql
SELECT "users"."id" AS "users_id", "users"."email" AS "users_email", "users"."surname" AS "users_surname", "users"."givenname" AS "users_givenname", "users"."createdDate" AS "users_createdDate", "users"."updatedDate" AS "users_updatedDate", "users"."isAdmin" AS "users_isAdmin" FROM "public"."user" "users" WHERE id not in ('31C65AAA-E6F3-4D3B-9D11-FEB41F8602B7', 'B04E5E00-B6EC-4D6F-911C-97243A318901', '4A23F320-16DC-4F9C-8D33-23ABE5A25820', '3D1E1C6D-4287-4AC3-9C23-A85C626BEA35')
```

#### Actual Results
- getRepository(User) is not using the schema
```sql
SELECT "users"."id" AS "users_id", "users"."email" AS "users_email", "users"."surname" AS "users_surname", "users"."givenname" AS "users_givenname", "users"."createdDate" AS "users_createdDate", "users"."updatedDate" AS "users_updatedDate", "users"."isAdmin" AS "users_isAdmin" FROM "user" "users" WHERE id not in ('31C65AAA-E6F3-4D3B-9D11-FEB41F8602B7', 'B04E5E00-B6EC-4D6F-911C-97243A318901', '4A23F320-16DC-4F9C-8D33-23ABE5A25820', '3D1E1C6D-4287-4AC3-9C23-A85C626BEA35')
```

#### Migration script

```ts
import { MigrationInterface, QueryRunner } from "typeorm";
import { User } from "../entities/User";

export class SetGeneratedNameForUsersMigration1515003957747 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        const usersRepository = queryRunner.connection.getRepository(User);

        const users = await usersRepository.createQueryBuilder("users").select().where("id not in ('31C65AAA-E6F3-4D3B-9D11-FEB41F8602B7', 'B04E5E00-B6EC-4D6F-911C-97243A318901', '4A23F320-16DC-4F9C-8D33-23ABE5A25820', '3D1E1C6D-4287-4AC3-9C23-A85C626BEA35')").getMany();

        // ...
    }
}
```

#### Error

```
error: { error: relation "user" does not exist
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'error',
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '284',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable' }
query: ROLLBACK
TypeORM connection error:  { QueryFailedError: relation "user" does not exist
    at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.callback (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:212:38)
    at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/usr/src/app/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:123:12)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
  message: 'relation "user" does not exist',
  name: 'QueryFailedError',
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '284',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable',
  query: 'SELECT "users"."id" AS "users_id", "users"."email" AS "users_email", "users"."surname" AS "users_surname", "users"."givenname" AS "users_givenname", "users"."createdDate" AS "users_createdDate", "users"."updatedDate" AS "users_updatedDate", "users"."isAdmin" AS "users_isAdmin" FROM "user" "users" WHERE id not in (\'31C65AAA-E6F3-4D3B-9D11-FEB41F8602B7\', \'B04E5E00-B6EC-4D6F-911C-97243A318901\', \'4A23F320-16DC-4F9C-8D33-23ABE5A25820\', \'3D1E1C6D-4287-4AC3-9C23-A85C626BEA35\')',
  parameters: [] }
```

**Comment by pleerock** [comment]
What is your schema defined in your ormconfig?

**Comment by ffittschen** [comment]
> Note: The postgres db uses the default `public` schema

There is no explicit schema defined in my `ormconfig.json`. But after this error occured, I also tried to explicitly set the schema to `public`, which resulted in the same error

**Comment by pleerock** [comment]
> There is no explicit schema defined in my ormconfig.json

if there is no explicit schema defined then it simply uses your default schema, e.g. `public`. Default schema is not used in queries, there is no reason to put it into queries while it will be used anyway.

**Comment by alterthecmcdeveloper26** [comment]
Wait how to solve this guys? Why there is no solution!

**Comment by alterthecmcdeveloper26** [comment]
Hi if anyone is running into this, this is the right syntax:
` await queryRunner.manager.getRepository('role').save(roleInfo);`
