### ISSUE TITLE
updating geometry Point type doesn't support "POINT(x y)" format unlike inserting

### ISSUE THREAD

**Issue by ingun37** [typeorm/typeorm#2329]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a property defined as 
```ts
@Column("point")
    geo: string
```
Updating value using "Point(x y)" format to this raises ER_CANT_CREATE_GEOMETRY_OBJECT (Inserting is fine)
e.g)
```ts
repository.create({"geo":"POINT(1 0)"}) //OK
repository.create({"geo":"POINT(0 0)"}) //OK
let a = repository.findOne(1)
a.geo = "POINT(1 0)"
repository.save(a) //ERROR
updateQueryBuilder.set({"geo":"POINT(0 0)"}).where("id = 1").execute() //ERROR
updateQueryBuilder.set({"geo":"POINT(1 0)"}).where("id = 1").execute() //ERROR
```

thank you

**Comment by pleerock** [comment]
I need help from you and debug this thing. What query builder produces you when you do `updateQueryBuilder.set({"geo":"POINT(1 0)"}).where("id = 1").execute()` checkout SQL logs. Second, please provide SQL query that actually works if you run it directly in the database.

**Comment by ingun37** [comment]
Here is a raw SQL query that works, production tested
```
UPDATE store SET geo=ST_GeomFromText('${geoRaw}') WHERE id=${storeid}
```
Heres output queryBuilder produced
```
(node:32729) UnhandledPromiseRejectionWarning: QueryFailedError: ER_CANT_CREATE_GEOMETRY_OBJECT: Cannot get geometry object from data you send to the GEOMETRY field
    at new QueryFailedError (/Users/ingun/Desktop/youngmoney/server/src/error/QueryFailedError.ts:7:9)
    at Query._callback (/Users/ingun/Desktop/youngmoney/server/src/driver/mysql/MysqlQueryRunner.ts:157:37)
    at Query.Sequence.end (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/ingun/Desktop/youngmoney/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
(node:32729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I couldn't get the SQL log right now. I'll post it later asap
Thank you

**Comment by pleerock** [comment]
`UPDATE store SET geo=ST_GeomFromText('${geoRaw}') WHERE id=${storeid}`

you need to escape parameters otherwise you can have an injection if you are using user output.

**Comment by ingun37** [comment]
Thank you for your concern.
Heres the sql log. I'm not sure if its what you needed. Please tell me if theres any other information you need.
```
query: UPDATE `store` SET `address` = ?, `geo` = ? WHERE `id` = ? -- PARAMETERS: ["Tokyo somewhere","POINT(127.0585214 37.4800022)","2"]
query failed: UPDATE `store` SET `address` = ?, `geo` = ? WHERE `id` = ? -- PARAMETERS: ["Tokyo somewhere","POINT(127.0585214 37.4800022)","2"]
error: { Error: ER_CANT_CREATE_GEOMETRY_OBJECT: Cannot get geometry object from data you send to the GEOMETRY field
    at Query.Sequence._packetToError (...server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (...server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (...server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (...server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (...server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (...server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (...server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (...server/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (...server/src/driver/mysql/MysqlQueryRunner.ts:146:36)
    at step (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)
    at Object.next (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:23:53)
    at fulfilled (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 'ER_CANT_CREATE_GEOMETRY_OBJECT',
  errno: 1416,
  sqlMessage: 'Cannot get geometry object from data you send to the GEOMETRY field',
  sqlState: '22003',
  index: 0,
  sql: 'UPDATE `store` SET `address` = \'Tokyo somewhere\', `geo` = \'POINT(127.0585214 37.4800022)\' WHERE `id` = \'2\'' }
(node:33374) UnhandledPromiseRejectionWarning: QueryFailedError: ER_CANT_CREATE_GEOMETRY_OBJECT: Cannot get geometry object from data you send to the GEOMETRY field
    at new QueryFailedError (...server/src/error/QueryFailedError.ts:7:9)
    at Query._callback (...server/src/driver/mysql/MysqlQueryRunner.ts:157:37)
    at Query.Sequence.end (...server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (...server/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (...server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (...server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (...server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (...server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
(node:33374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ingun37** [comment]
Here's SQL log when INSERT using same format "POINT(x y)" which works fine
```
query: INSERT INTO `store`(`name`, `address`, `geo`) VALUES (DEFAULT, DEFAULT, GeomFromText(?)) -- PARAMETERS: ["POINT(1 0)"]
```

**Comment by dreamersp** [comment]
Hello everyone, we had this issue as well and needed to be fixed ASAP, so we fixed it in this pull request: https://github.com/typeorm/typeorm/pull/2449
If it gets approved everyone would enjoy the solution.
Cheers!

**Comment by pleerock** [comment]
Thanks for the fix, this will be released in the next version

**Comment by murielsilveira** [comment]
hey @pleerock :)
when do you plan to release the next `next` version with this fix?
thanks
