### ISSUE TITLE
loadRelationCountAndMap fails when primary key is string

### ISSUE THREAD

**Issue by ingun37** [typeorm/typeorm#2338]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

loadRelationCountAndMap fails when the primary key is string

```
query: SELECT `tag`.`name` AS `tag_name` FROM `tag` `tag`
query: SELECT `tag_stores_rc`.`tagName` AS `parentId`, COUNT(`store`.`id`) AS `cnt` FROM `store` `store` INNER JOIN `tag_stores_store` `tag_stores_rc` ON `tag_stores_rc`.`tagName` IN (t1) AND `tag_stores_rc`.`storeId` = `store`.`id` GROUP BY `tag_stores_rc`.`tagName`
query failed: SELECT `tag_stores_rc`.`tagName` AS `parentId`, COUNT(`store`.`id`) AS `cnt` FROM `store` `store` INNER JOIN `tag_stores_store` `tag_stores_rc` ON `tag_stores_rc`.`tagName` IN (t1) AND `tag_stores_rc`.`storeId` = `store`.`id` GROUP BY `tag_stores_rc`.`tagName`
error: { Error: ER_BAD_FIELD_ERROR: Unknown column 't1' in 'on clause'
    at Query.Sequence._packetToError (...server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (...server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (...server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (...server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (...server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (...server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (...server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (...server/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (...server/src/driver/mysql/MysqlQueryRunner.ts:146:36)
    at step (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)
    at Object.next (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:23:53)
    at fulfilled (...server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'t1\' in \'on clause\'',
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT `tag_stores_rc`.`tagName` AS `parentId`, COUNT(`store`.`id`) AS `cnt` FROM `store` `store` INNER JOIN `tag_stores_store` `tag_stores_rc` ON `tag_stores_rc`.`tagName` IN (t1) AND `tag_stores_rc`.`storeId` = `store`.`id` GROUP
```
thank you

**Comment by pleerock** [comment]
don't use `loadRelationCountAndMap` - it was experimental function and will be removed in the future. Consider executing a separate query.

**Comment by ingun37** [comment]
would you give me an example?

**Comment by ingun37** [comment]
Is there a recommended way to get count of relational datas?

**Comment by pleerock** [comment]
Just think how you would do it in sql and execute a raw query, orm takes care about your models and mapping them into entities, if you need something else like count you need to execute query and get a result.
