### ISSUE TITLE
Remove() -> Cannot read property 'tableName' of undefined

### ISSUE THREAD

**Issue by mrnagydavid** [typeorm/typeorm#2347]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[] `latest`
[ ] `@next`
[0.2.7] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an Entity that "isOwning":

```
@Entity()
export class User extends Base {
	@Column()
	name: string;

	@Index({ unique: true })
	@Column()
	email: string;

	// ...

	@OneToMany(() => Footprint, (footprint: Footprint) => footprint.creator, { nullable: true })
	createdFootprints?: Footprint[];

	// ...
}
```
There are two more nullable one-to-many relations and one many-to-many. Since I am only testing the User entities, all relations are empty, and only the own fields of the User are filled out.

In my test:
```
it('should work', async () => {
      const user = // ... fill out fields
      await user.save(); // tested and works well
      await user.remove(); // throws error
      expect(user).toBe....
});
```

The error is:

```
    TypeError: Cannot read property 'tableName' of undefined

      at RelationIdLoader.<anonymous> (src/query-builder/relation-id/RelationIdLoader.ts:117:158)
      at step (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)
      at Object.next (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:13:53)
      at node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:7:71
      at Object.<anonymous>.__awaiter (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:3:12)
      at src/query-builder/relation-id/RelationIdLoader.ts:26:76
          at Array.map (<anonymous>)
      at RelationIdLoader.<anonymous> (src/query-builder/relation-id/RelationIdLoader.ts:26:52)
      at step (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)
      at Object.next (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:13:53)
      at node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:7:71
      at Object.<anonymous>.__awaiter (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:3:12)
      at RelationIdLoader.Object.<anonymous>.RelationIdLoader.load (node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:53:16)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:1823:65)
      at step (node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
      at Object.next (node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
      at fulfilled (node_modules/typeorm/query-builder/SelectQueryBuilder.js:14:58)
```

The same happens if I do ```User.remove(user);```

At src/query-builder/relation-id/RelationIdLoader.ts:117:158 there are non-null assertion operators, but it seems that the property is undefined after all.

Thanks!

**Comment by pleerock** [comment]
Would be great if you can contribute and create a PR with a failing test, so we can quickly fix issue if it is an issue.

**Comment by Avejack** [comment]
Is there a work-around? I am having the same issue :/

**Comment by Avejack** [comment]
I don't know about your case but i have solved the issue... It wasn't an issue with this Masterpiece of a library! It actually was my own fault... I had those relations in my "file" object:

    @ManyToMany(type => User, user => user.image)
    public users: User[];

    @ManyToMany(type => Employee, employee => employee.image)
    public employees: Employee[];

But they had to be "OneToMany" relations instead of "ManyToMany" relations! That was it.
I can't say it enough: This Library is awesome. Especially in combination with @pleerock's class-validator library!

**Comment by Kononnable** [comment]
Closing as no answer from original reporter.

**Comment by dimitrinicolas** [comment]
I encountered the same issue and I solved it by adding this line:

```diff
  @ManyToMany(type => User, user => user.image)
+ @JoinTable()
  public users: User[];
```

More information can be found on this page: [github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md](https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md).

I wanted to reply to this closed issue in case another person encounters this mistake.

**Comment by fynnay** [comment]
I hope it's ok to piggyback on this issue since my symptoms are very similar. None of the solution provided in this thread have worked for me so far. I'd be greatful for any ideas or input.

### Background Info

Database system/driver: [sqlite]

TypeORM version: [^0.2.25]

### The Problem

I have the following `@ManyToOne` / `@OneToMany` related Entities:

<details><summary>Entities</summary>
<p>

**Info.ts**:

```typescript
@Entity()
export class Info extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => AssetType, assetType => assetType.infos)
    @IsDefined()
    assetType: AssetType;

    static async deleteUnused () {
        const infos = await this.find();
        for (const info of infos) {
            // FIXME: this.remove throws TypeError: Cannot read property 'tableName' of undefined
            await this.remove(info)
        }
    }
```

**AssetType.ts**:

```typescript
@Entity()
export class AssetType extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @OneToMany(type => Info, info => info.assetType)
    infos: Info[];
}
```

</p>
</details>

When I call `Info.deleteUnused` `this.remove` throws the following error: `TypeError: Cannot read property 'tableName' of undefined`

<details><summary>Full Trace</summary>
<p>

```prolog
(node:464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tableName' of undefined
    at RelationIdLoader.<anonymous> (C:\Users\fynn\Documents\Development\github\AZid-server\src\query-builder\relation-id\RelationIdLoader.ts:126:158)
    at step (C:\Users\fynn\Documents\Development\github\AZid-server\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\fynn\Documents\Development\github\AZid-server\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at C:\Users\fynn\Documents\Development\github\AZid-server\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\fynn\Documents\Development\github\AZid-server\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at C:\Users\fynn\Documents\Development\github\AZid-server\src\query-builder\relation-id\RelationIdLoader.ts:25:76
    at Array.map (<anonymous>)
    at RelationIdLoader.<anonymous> (C:\Users\fynn\Documents\Development\github\AZid-server\src\query-builder\relation-id\RelationIdLoader.ts:25:52)
    at step (C:\Users\fynn\Documents\Development\github\AZid-server\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
(node:464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

</p>
</details>

### The Workaround

The only workaround I've found is to use `.delete(<id>)` instead.

I would however prefer to use `remove` because I may want to implement cascades and Entity listeners - metioned in [this comment](https://stackoverflow.com/a/54246681)
