### ISSUE TITLE
TypeORM doesn't read in environment variables in AWS ElasticBeanstalk

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#2366]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've deployed a NestJS application with TypeORM to AWS ElasticBeanstalk. I love the feature for TypeORM where if no configuration is found, TypeORM will instead look for environment variables set, e.g. `TYPEORM_HOST` or `TYPEORM_PORT`.

I have several environment variables set in AWS ElasticBeanstalk (via their `eb setenv` directive) and all of them are read in properly with my ConfigService (using dotenv). However, none of the `TYPEORM_*` environment variables are read in by TypeORM when the module is loaded. It works fine when testing locally (e.g. exporting `TYPEORM_*` vars in `~/.bash_profile` works great). But it does not work in AWS ElasticBeanstalk. This makes me think that perhaps TypeORM is loading environment variable slightly differently than tools like dotenv.

How does TypeORM load environment variables? Is there a reason why this would work fine on one machine and not another?

From "using-ormconfig.md":  
> On production you can set all these values in real ENVIRONMENT VARIABLES.

Even with the environment variables set in AWS, TypeORM can't seem to find them and instead loads defaults:

```
[Nest] 6904   - 2018-6-20 01:22:24   [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
 1: node::Abort() [node]
 2: 0x11e8359 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0xb7a9ac [node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x97ba25042fd```

**Comment by kodayashi** [comment]
I think the issue here was me not realizing:

^ You can't mix variables in ormconfig.json and in ENV so you have to define all your variables either in ormconfig.json either in environment variables.

I'll retry with everything as ENV vars and report back.

**Comment by kodayashi** [comment]
Yep that was the issue, closing.
