### ISSUE TITLE
Problem using @Tree decorator with my own custom decorator

### ISSUE THREAD

**Issue by Slessi** [typeorm/typeorm#2380]
**Issue type:** [x] question
**Database system/driver:** [x] `mysql`
**TypeORM version:** [x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I have the following custom decorator:

```ts
interface SoftDelete {
    recStatus: number;
}

const SoftDelete = <T extends { new (...args: any[]): any }>(constructor: T) => {
    class Decorated extends constructor implements SoftDelete {
        @Column({ name: "rec_status", default: 1, nullable: false, type: "tinyint" })
        public recStatus!: number;
    }

    return Decorated;
};
```

When applying to a class which only has `@Entity`, its fine:

```ts
@Entity()
@SoftDelete
export class SomeEntity implements SoftDelete {
    @PrimaryGeneratedColumn({})
    public id!: number;

    public recStatus!: number;
}
```

But if the class *also* has `@Tree`, like so:

```ts

@Entity()
@Tree("closure-table")
@SoftDelete
export class SomeTreeEntity implements SoftDelete {
    @PrimaryGeneratedColumn({})
    public id!: number;

    @TreeChildren()
    public children!: SomeTreeEntity[];

    @TreeParent()
    public parent!: SomeTreeEntity;

    @TreeLevelColumn()
    public level!: number;

    // SoftDelete
    public recStatus!: number;
}
```

I receive the following when generating a migration:

```
yarn run v1.7.0
$ ts-node $(npm bin)/typeorm migration:generate -n InitialEntities
Error during migration generation:
Error: Entity metadata for Decorated#children was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at /Users/edward/Projects/talexio-hr-api/src/metadata-builder/EntityMetadataBuilder.ts:562:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (/Users/edward/Projects/talexio-hr-api/src/metadata-builder/EntityMetadataBuilder.ts:557:34)
    at /Users/edward/Projects/talexio-hr-api/src/metadata-builder/EntityMetadataBuilder.ts:112:56
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/Users/edward/Projects/talexio-hr-api/src/metadata-builder/EntityMetadataBuilder.ts:112:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/edward/Projects/talexio-hr-api/src/connection/ConnectionMetadataBuilder.ts:66:111)
    at Connection.buildMetadatas (/Users/edward/Projects/talexio-hr-api/src/connection/Connection.ts:485:59)
    at Connection.<anonymous> (/Users/edward/Projects/talexio-hr-api/src/connection/Connection.ts:186:18)
    at step (/Users/edward/Projects/talexio-hr-api/node_modules/typeorm/connection/Connection.js:32:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Removing `@SoftDelete` resolves the problem, how can I overcome this? Have I written my decorator wrong? Or is there a better way to implement a re-useable column for soft delete?

**Comment by pleerock** [comment]
with your decorator this:

```ts
class SomeEntity
```

actually becomes this:

```ts
class Decorated
```

and even for this:

```ts
class AnotherEntity
```

actually becomes this:

```ts
class Decorated
```

so... it will be source of hundred of problems and simply won't work. Think deeply if its really not worth adding additional code in your entities even if you have bunch of them.

**Comment by Slessi** [comment]
Indeed, I have noticed these problems already :(

Guess I'll repeat the fields
