### ISSUE TITLE
ER_CANT_DROP_FIELD_OR_KEY on start when there is a unique index

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#244]
I'm getting ER_CANT_DROP_FIELD_OR_KEY on start when there is a unique column in table `user`. The problem is gone only when the unique key is deleted. I also tried putting `index()` at the top of the class like this:

`@Index("unique_user_twitter_id", (post: UserData) => [post.twitter_id], { unique: true }) `

but the problem still occurs. I have seen several posts on this. My problem only occurs when there is an unique index in the following table. The column `twitter_id` isn't linked as foreign keys to other table

````
@Entity()
export class User {
    @PrimaryGeneratedColumn({type:'int'})
    user_id: number;

    @Column({type:'string',length:255})
    user_name: string;

    @Column({type:'string',length:25})
    @Index({unique:true})
    twitter_id: string;
}
````

Error:
````
{ Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'twitter_id'; check that column/key exists
    at Query.Sequence._packetToError (/home/website/node/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/website/node/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/website/node/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/website/node/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/website/node/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/website/node/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/home/website/node/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/home/website/node/node_modules/mysql/lib/Connection.js:208:25)
    at /build/compiled/src/driver/mysql/MysqlQueryRunner.ts:150:48
    at MysqlQueryRunner.query (/build/compiled/src/driver/mysql/MysqlQueryRunner.ts:149:16)
    at MysqlQueryRunner.<anonymous> (/build/compiled/src/driver/mysql/MysqlQueryRunner.ts:499:24)
    at step (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at /home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:7:65
    at __awaiter (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:3:12)
    at MysqlQueryRunner.changeColumn (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:584:16)
    at MysqlQueryRunner.<anonymous> (/build/compiled/src/driver/mysql/MysqlQueryRunner.ts:512:25)
    at step (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at /home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:7:65
    at __awaiter (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:3:12)
    at /build/compiled/src/driver/mysql/MysqlQueryRunner.ts:511:70
    at Array.map (native)
    at MysqlQueryRunner.<anonymous> (/build/compiled/src/driver/mysql/MysqlQueryRunner.ts:511:47)
    at step (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at /home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:7:65
    at __awaiter (/home/website/node/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:3:12)
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlState: '42000',
  index: 0 }
````

**Comment by pleerock** [comment]
@iz-iznogood can you please take a look this one as well?

**Comment by iz-iznogood** [comment]
Hi,

this issue is actually the same as @549. 
The index on mysql marks the column as unique thus creating a mismatch with TORM's metadata.
You can just mark the column as unique and get rid of the index. The system will create it and maintain it automatically

This works but the fundamental issue that we can not distinguish between columns with unique constraints and unique indices in MySQL remains.

If this solution is good for you maybe this issue can be closed

**Comment by pleerock** [comment]
fixed by @iz-iznogood , fix will be released in next version
