### ISSUE TITLE
bug report -  MissingPrimaryColumnError: Entity "Provider" does not have a primary column.

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2452]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have these two entities:

```js
'use strict';

import {Column, Entity, Index, PrimaryColumn, PrimaryGeneratedColumn} from "typeorm";

@Entity()
@Index(["emailPrimary"], { unique: true })
@Index(["emailSecondary"], { unique: true })
@Index(["companyName"], { unique: true })
export class Provider {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  companyName: string;

  @Column()
  pin: string;  // 6 digit pin

  @Column()
  emailPrimary: string;

  @Column()
  emailSecondary: string;

  @Column()
  phonePrimary: string;

  @Column()
  phoneSecondary: string;

}

//////////////////////////////////////////////////////////
'use strict';

import {Column, Entity, Index, JoinColumn, OneToOne, PrimaryGeneratedColumn} from "typeorm";
import {Provider} from "./provider";

@Entity()
@Index(["phone"], { unique: true })
export class ProviderHardwarePhoneNumbers {

  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(t => Provider)
  @JoinColumn()
  provider: Provider;

  @Column()
  phone: string;  // 6 digit pin

}
````

if I run my project with `synchronize:true`

```
(node:28701) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:28701) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
unhandledRejection { MissingPrimaryColumnError: Entity "Provider" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
    at new MissingPrimaryColumnError (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/error/MissingPrimaryColumnError.js:18:28)
    at EntityMetadataValidator.validate (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:51:19)
    at /home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:25)
    at Connection.buildMetadatas (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/connection/Connection.js:515:33)
    at Connection.<anonymous> (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/connection/Connection.js:162:30)
    at step (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/connection/Connection.js:13:53)
    at fulfilled (/home/oleg/WebstormProjects/moove/moove-api-mariadb/node_modules/typeorm/connection/Connection.js:4:58)
  name: 'MissingPrimaryColumnError',
  message:
   'Entity "Provider" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.' }
```

here is my project's config:

```js
module.exports = {
  type: "mariadb",
  host: process.env.moove_db_host,
  port: process.env.moove_db_port,
  username: process.env.moove_db_username,
  password: process.env.moove_db_password,
  database: process.env.moove_database_name,
  synchronize: true,
  logging: false,
  entities: [
    "dist/entity/**/*.js"
  ],
  migrations: [
    "dist/migration/**/*.js"
  ],
  subscribers: [
    "dist/subscriber/**/*.js"
  ],
  cli: {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
};
```

**Comment by pleerock** [comment]
can you create a reproduction for this issue?

**Comment by ORESoftware** [comment]
@pleerock here is the project, it's 

https://github.com/ORESoftware/typeorm-bug-temp

you can use these env variables to get it running with a local mariadb instance:

```
export moove_api_server_port="3010";
export moove_db_host="localhost";
export moove_db_port="3306";
export moove_db_username="root";
export moove_db_password="moove";
export moove_database_name="moove_db";
```

this seems to be an actually issue. I haven't tried dropping the database, but that would be my next step since nothing else seems to work.

**Comment by pleerock** [comment]
too complicated repo. Fork https://github.com/typeorm/typescript-example and create reproduction based on it. Or better provide a PR with a failing test.

**Comment by ORESoftware** [comment]
@pleerock np, I made a simpler repro and the problem didn't exist. What was happening is I had an old .js file in the target directory.

`rm -rf dist/* && tsc`

solved it...annoying problem, but has to do with tsc

**Comment by ORESoftware** [comment]
@pleerock by the way, random fun fact, in the typescript-example project you have this:

```
  "scripts": {
    "start": "tsc && node src/index.js",
    "typeorm": "./node_modules/.bin/typeorm "
  }
```

`npm run typeorm` will put   node_modules/.bin on the PATH

so it will look like:

```bash
PATH="node_modules/.bin":"$PATH" ./node_modules/.bin/typeorm
```
but that can be reduced to

`
```bash
PATH="node_modules/.bin":"$PATH" typeorm
```
just a fun fact about NPM scripts, so scripts can look like:
```bash
 "scripts": {
    "start": "tsc && node src/index.js",
    "typeorm": "typeorm"
  }
```

**Comment by pleerock** [comment]
mmm does it work same across all platforms including windows?

**Comment by ORESoftware** [comment]
It should, it's an NPM thing, it was just a fun fact, not that useful

**Comment by cleivson** [comment]
> @pleerock np, I made a simpler repro and the problem didn't exist. What was happening is I had an old `.js` file in the target directory.
> 
> `rm -rf dist/* && tsc`
> 
> solved it...annoying problem, but has to do with tsc not typeorm. the problem happens when you create/delete/rename .ts files.

For people who come here with the same problem, that solved for me. I've deleted the 'dist' folder and ran ```npm run build```.

After that, it worked again.
