### ISSUE TITLE
The database can not be updated

### ISSUE THREAD

**Issue by andrzejpakula** [typeorm/typeorm#2469]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ 0.2.7] `0.x.x` (or put your version here)

Hi. I do not know why I can not update my database.For commands that work with the database, throws an exception:

Error during schema sync: 
project/test/src/entity/User.ts:1
(function (exports, require, module, __filename, __dirname) { import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by pleerock** [comment]
you have a very basic error. You need to compile your typescript. Use https://github.com/typeorm/typescript-example starter repository if you have issues.
