### ISSUE TITLE
Issue setting default value in mysql simple-array / simple-json @Column({default: ''})

### ISSUE THREAD

**Issue by Tyler-V** [typeorm/typeorm#2493]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an Entity where I am trying to store user roles, I believe simple-array is the best option for mysql.

```
    @Column({ type: 'simple-array', select: false, default: 'User' })
    roles: string[];
```

This results in:

```
[Nest] 179516   - 2018-7-9 17:44:32   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3001ms
QueryFailedError: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'roles' can't have a default value
    at new QueryFailedError (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\src\error\QueryFailedError.ts:7:9)
    at Query._callback (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\src\driver\mysql\MysqlQueryRunner.ts:157:37)
    at Query.Sequence.end (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query.ErrorPacket (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Tyler\Documents\GitHub\tribot-stats\api\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

I have searched similar issues for simple-json (tried this first) and saw the same issue.

 `simple-json maps to string in the database and default is sql's DEFAULT value, so you need to set a string, e.g. default: "{}"`

Is it not possible to set a default value for simple-array or simple-json or am I doing something wrong?

Thanks

**Comment by Tyler-V** [comment]
Related https://github.com/typeorm/typeorm/issues/1849

**Comment by Tyler-V** [comment]
Also noticed the simple-array column-type which is probably more appropriate.

I'm unable to set a default column type on this column either, tried in many different formats. Any clarification?

**Comment by Tyler-V** [comment]
For now, I am using

```
    @Column({ type: 'simple-array', select: false })
    roles: string[];
```

And inserting a user with roles: ['User'] in my user.service which is a completely fine workaround but unnecessary if I can control default role logic in the column itself.

**Comment by pleerock** [comment]
simple-array uses `text` column type underlying and you can't set DEFAULT for `text` column in mssql, so its a database limitation. btw what will be if you simply do `roles: []` ?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.

**Comment by bahtiyara** [comment]
I am also facing this issue, any solution?

**Comment by bahtiyara** [comment]
[https://github.com/typeorm/typeorm/issues/1849#issuecomment-759932141](url)

The solution is here if anyone needs it.
