### ISSUE TITLE
One-to-many relation with entity schema

### ISSUE THREAD

**Issue by marekbrainhub** [typeorm/typeorm#2503]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.16` (or put your version here)

I'm using entitySchema to make one-to-many relation between `user` and `post`.

```js
module.exports = {
  name: 'user',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    name: { type: 'varchar' },
  },
  relations: {
    posts: {
      type: 'one-to-many',
      target: 'post',
    },
  },
};
```

```js
module.exports = {
  name: 'post',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    title: { type: 'varchar' },
    content: { type: 'varchar' },
    date: { type: 'timestamp' },
  },
  relations: {
    user: {
      type: 'many-to-one',
      target: 'user',
      joinColumn: true,
    },
  },
};
```

```js
        const user = await userRepository.createQueryBuilder()
          .leftJoinAndSelect('user.posts', 'post')
          .getOne();
```

This results in

```
TypeError: Cannot read property 'joinColumns' of undefined
    at /Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:959:58
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:935:55)
    at SelectQueryBuilder.getQuery (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:85:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/QueryBuilder.js:231:70)
    at SelectQueryBuilder.<anonymous> (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1387:35)
    at step (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next (/Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
    at /Users/justinian/nodejs/hadron-tutorial/node_modules/@brainhubeu/hadron-typeorm/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
    at new Promise (<anonymous>)
```

What should I put into the entity schema to make the relation work?

**Comment by ikito** [comment]
Perhaps...
`joinColumn: "id,`

**Comment by ikito** [comment]
```
module.exports = {
  name: 'post',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    title: { type: 'varchar' },
    content: { type: 'varchar' },
    date: { type: 'timestamp' },
  },
  relations: {
    user: {
      type: 'many-to-one',
      target: 'user',
      joinColumn: true,
     **inverseSide: "posts",**
    },
  },
};
```
Ok, i think you need inverseSide on many-to-one. Try it.

**Comment by marekbrainhub** [comment]
Seems like this solves my problem.

```js
module.exports = {
  name: 'user',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    name: { type: 'varchar' },
  },
  relations: {
    posts: {
      type: 'one-to-many',
      target: 'post',
      inverseSide: 'user',
    },
  },
};
```

```js
module.exports = {
  name: 'post',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    title: { type: 'varchar' },
    content: { type: 'varchar' },
    date: { type: 'timestamp' },
  },
  relations: {
    user: {
      type: 'many-to-one',
      target: 'user',
      joinColumn: true,
    },
  },
};
```

```js
        const user = await userRepository.findOne({ id: userid, relations: ['posts'] });
```
