### ISSUE TITLE
MongoDB _id string type 

### ISSUE THREAD

**Issue by isman-usoh** [typeorm/typeorm#2530]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

Example
```ts
// Not work
@Entity()
export class UserCase0 {
    @ObjectIdColumn()
    id: string;

    @BeforeInsert()
    onBeforeInsert() {
        this.id = shortid.generate();
    }
}

// Not work
@Entity()
export class UserCase1 {
    @PrimaryColumn({ name: '_id' })
    id: string;

    @BeforeInsert()
    onBeforeInsert() {
        this.id = shortid.generate();
    }
}

// Not work
@Entity()
export class UserCase2 {
    @ObjectIdColumn({ name: '_id', type: 'stirng' })
    id: string;

    @BeforeInsert()
    onBeforeInsert() {
        this.id = shortid.generate();
    }
}
```

Error
```
TypeError: Cannot read property 'createValueMap' of undefined
    at MongoDriver.createGeneratedMap (/Users/iamsman/typeorm-mongo-id-string/src/driver/mongodb/MongoDriver.ts:323:41)
    at /Users/iamsman/typeorm-mongo-id-string/src/entity-manager/MongoEntityManager.ts:189:66
    at Array.forEach (<anonymous>)
    at MongoEntityManager.<anonymous> (/Users/iamsman/typeorm-mongo-id-string/src/entity-manager/MongoEntityManager.ts:187:49)
    at step (/Users/iamsman/typeorm-mongo-id-string/node_modules/typeorm/entity-manager/MongoEntityManager.js:42:23)
    at Object.next (/Users/iamsman/typeorm-mongo-id-string/node_modules/typeorm/entity-manager/MongoEntityManager.js:23:53)
    at fulfilled (/Users/iamsman/typeorm-mongo-id-string/node_modules/typeorm/entity-manager/MongoEntityManager.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by pleerock** [comment]
I think here problem not in `@PrimaryColumn` but in the fact that author wants an id (object id) to be a string. Its not possible since ObjectId in mongodb is a type of ObjectId.

I think this issue can be closed.

**Comment by vlapo** [comment]
Sure ObjectId cant be string ... but _id can be whatever we want. From mongodb documentation:

> Documents have the following restrictions on field names:
>  - The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.

Ref: https://docs.mongodb.com/manual/core/document/#field-names

So maybe something like this should work (did not test it):
```typescript
@Column({ name: '_id' })
id: string;
```
User just need to create entity with unique id.

**Comment by renatogbp** [comment]
> So maybe something like this should work (did not test it):
> 
> ```ts
> @Column({ name: '_id' })
> id: string;
> ```
> 
> User just need to create entity with unique id.

I wanted to use uuid instead of ObjectId for my id and tried your suggestion. But I got the following error:

    TypeError: Cannot read property 'propertyName' of undefined
    at /Users/renatogbp/Desktop/project/src/entity-manager/MongoEntityManager.ts:148:52
    at Array.map (<anonymous>)
    at MongoEntityManager.<anonymous> (/Users/renatogbp/Desktop/project/src/entity-manager/MongoEntityManager.ts:144:22)
    at step (/Users/renatogbp/Desktop/project/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/renatogbp/Desktop/project/node_modules/tslib/tslib.js:114:57)
    at /Users/renatogbp/Desktop/project/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/renatogbp/Desktop/project/node_modules/tslib/tslib.js:103:16)
    at MongoEntityManager.findByIds (/Users/renatogbp/Desktop/project/node_modules/typeorm/entity-manager/MongoEntityManager.js:111:24)
    at MongoRepository.findByIds (/Users/renatogbp/Desktop/project/src/repository/MongoRepository.ts:94:29)

any suggestion on how to accomplish this?

**Comment by evilive3000** [comment]
any workaround? I need a custom type for mongodb primary column.

```
  @PrimaryColumn()
  id: string;
``` 
does not work. throws exception `[ExceptionsHandler] Cannot read property 'createValueMap' of undefine`

**Comment by rustamwin** [comment]
any issue labels ? @vlapo @pleerock

**Comment by steedos** [comment]
+1

**Comment by Gary-Ascuy** [comment]
this library has a lot of problems with mongo, is there a way to solve this ? I think this is common use case

**Comment by egoarka** [comment]
any progress on this?

**Comment by egoarka** [comment]
Finally, I managed to create custom `_id`, you need to provide your `_id` explicitly when saving

```
export class FooBar extends BaseEntity {
  @ObjectIdColumn({
    name: '_id',
    type: 'string',
  })
  id!: string;
  
  @Column()
  name!: string;
}

...

FooBar.save({
  _id: 'my-custom-id',
  name: 'foo-bar'
})
```

**Comment by renatogbp** [comment]
Thank you a lot @egoarka, it worked!
I am curious about what's the exclamation mark for?

**Comment by egoarka** [comment]
@renatogbp more on this you can read [here](https://devblogs.microsoft.com/typescript/announcing-typescript-2-7/)

**Comment by elias-garcia** [comment]
is this planned to be fixed?

**Comment by nmsn** [comment]
> Sure ObjectId cant be string ... but _id can be whatever we want. From mongodb documentation:
> 
> > Documents have the following restrictions on field names:
> > 
> > * The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.
> 
> Ref: https://docs.mongodb.com/manual/core/document/#field-names
> 
> So maybe something like this should work (did not test it):
> 
> ```ts
> @Column({ name: '_id' })
> id: string;
> ```
> 
> User just need to create entity with unique id.

i tried it,when it show me 
> (node:23876) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'propertyName' of undefined
    at F:\Code\nest-test\node_modules\typeorm\entity-manager\MongoEntityManager.js:123:67

**Comment by imsergiobernal** [comment]
I'm using entity schema and having the same issue as well.

As you @pleerock mentioned, _id could be anything, even a nested object as well

**Comment by DazChong** [comment]
I thought I found a good ORM library, until I hit this issue. Overall experience too much overhead 🙁, switching back to ts-mongoose.

**Comment by emmanuelnk** [comment]
What worked for me:

```ts
export class FooUser {
    @ObjectIdColumn()
    _id!: string // Note: primary key MUST BE '_id' with the underscore

    lean() {
        this.id = this._id
        delete this._id
        return this
    }
}

FooUser.save({
    _id: 'my-custom-id', // always save with _id else it wont work. id will create another document or fail
    name: 'foo-bar'
})

const user = (await FooUser.findOne({_id: 'my-custom-id'})).lean()
// user.id to return to client or other parts of the program
```

`user.id` will be the only id present on the returned document. I found this way to be more portable than configuring a `@column` name alias for `_id` in the FooUser class.

**Comment by dmitrye** [comment]
While the proposed solution by @olehdevua works in terms of Mongo behavior, it's absolutely incorrect in terms of an ORM which is supposed to be DB independent. If you have a model/entity, that model should be defined the same regardless of Mongo or PGSQL or any other DB. Example would be a project that has both SQL and NoSQL (Mongo) data stores for different needs. But if you want to share an entity between the two you now have to bring Mongo specific "_id" nomenclature into the architecture. 

There has to be a fix or way to have the attribute as "id: String" and through datastore specific annotations let TypeORM know that it could be represented as "_id" if the DataStore/Repository is of type Mongo instead of PGSQL or MSSQL as an example. Just annotating without DB specific instructions would fail in the multi-datastore scenario. 

If all you have is a single Mongo datastore then the above works - but is still a hack.

**Comment by johnjaider1000** [comment]
Hi, I leave this in case nothing has worked for any of you so far.

```ts
import {
  AfterInsert,
  AfterLoad,
  AfterRemove,
  AfterUpdate,
  Column,
  Entity,
  ObjectIdColumn,
  PrimaryColumn,
} from 'typeorm';

@Entity()
export class User {
  @ObjectIdColumn({ name: '_id' })
  _id: string;

  @PrimaryColumn()
  @ObjectIdColumn()
  id: string;

  @Column()
  firstName: string;
  
 /**
 * With the following annotations in the following method I obtain the _id and assign it to the id that is what I want to use 
 * because if you like me it gives you an embarrassment to see that _id in your models 
 **/ 
  @AfterLoad()
  @AfterInsert()
  @AfterUpdate()
  @AfterRemove()
  assingIdFromObjectId() {
    this.id = this._id.toString();
  }
}

```

## Search by id:
```ts
import { ObjectId } from 'mongodb';
/** On the other hand I had some problems searching by _id for my records, I have managed to perform the search this way: **/
findOne(id: string) {
    const objectId: any = new ObjectId(id);
    return this.userRepository.findOneBy({ _id: objectId });
}
```

**Comment by 3hson** [comment]
this is what worked for me 

```ts
export class MyEntity {
  @ObjectIdColumn()
  _id: string;

  constructor() {
    this._id = UuidV4();
  }
}
```
