### ISSUE TITLE
Simple Postgres timestamp transformer is munging the value before transformer.to()

### ISSUE THREAD

**Issue by yang** [typeorm/typeorm#2557]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

With the following simple test case trying to use luxon.DateTime as a timestamp column:

```ts
import {DateTime} from "luxon";

...

@Entity()
export class Dummy {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('timestamp', {transformer: {from: (d: Date) => DateTime.fromJSDate(d), to: (d: DateTime) => d.toJSDate()}})
  date: DateTime;
}

...

createConnection().then(async connection => {
  const dummy = new Dummy();
  dummy.date = DateTime.local();
  connection.manager.save(dummy);
})
```

I get:

```
(node:73270) UnhandledPromiseRejectionWarning: QueryFailedError: invalid input syntax for type timestamp: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"
    at new QueryFailedError (/Users/yang/proj/lastmileai/web/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/Users/yang/proj/lastmileai/web/src/driver/postgres/PostgresQueryRunner.ts:171:30)
    at Query.handleError (/Users/yang/proj/lastmileai/web/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/yang/proj/lastmileai/web/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/Users/yang/proj/lastmileai/web/node_modules/pg/lib/connection.js:123:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by pleerock** [comment]
what do you mean `munging the value`? Can you provide an example? Also please provide a code without any third-party library

**Comment by yang** [comment]
The DateTime object being passed into the transformer is not the same instance as the DateTime object - TypeORM is doing something to the value, which AFAIK is not documented.

Here's a simpler example involving just a plain JS object:

```ts
@Entity()
export class Foo {
  @PrimaryColumn("uuid") id: string;

  @Column("timestamp", {
    transformer: {
      from: (x: any) => {
        console.log(x);
        return x;
      },
      to: (x: any) => {
        console.log(x, (global as any).foo.foo === x); // <-- PRINTS FALSE
        return x;
      }
    }
  })
  foo: any;
}

...

    const connection = await createConnection();
    connection.transaction(async em => {
      const foo = em.create(Foo, {
        id: uuid(),
        foo: { x: 1 } as any
      });
      (global as any).foo = foo;
      console.log(foo.foo);
      await em.save(foo);
    });
```

The luxon example is more interesting because whatever TypeORM is doing is changing the DateTime object into an invalid DateTime.

**Comment by pleerock** [comment]
please check it once 0.2.9 is released
