### ISSUE TITLE
Concrete table inheritance caused error if the classes are put in separate files.

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#259]
I have run into this bug `TypeError: Class constructor BasedItem cannot be invoked without 'new'` when invoking a class that extends a base class.

Example:

BaseItem.ts
````
@AbstractEntity()
export class BasedItem{
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    brand:string
}
````

Item.ts
````
@Entity()
export class Item extends BasedItem{
   @Column()
   info:string
}
````

SisterItem.ts

````
@Entity()
export class SisterItem extends BasedItem{
    @Column()
    user:number
}
````

When I instantiate `SisterItem`,I'm getting this error:
````
TypeError: Class constructor BasedItemInfo cannot be invoked without 'new'
   at new SubmitItem (/home/base/node/type_src/entity/SisterItem.js:25:18)
   at TestRoutes._callee$ (/home/base/node/type_src/routes/TestRoutes.js.js:28:22)
   at tryCatch (/home/base/node/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:64:40)
   at Generator.invoke [as _invoke] (/home/base/node/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:355:22)
   at Generator.prototype.(anonymous function) [as next] (/home/base/node/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:116:21)
   at /home/base/node/type_src/routes/TestRoutes.js.js:16:71
   at __awaiter (/home/base/node/type_src/routes/TestRoutes.js.js:12:12)
   at TestRoutes.getTest (/home/base/node/type_src/routes/TestRoutes.js.js:25:16)
   at ActionMetadata.executeAction (/home/base/node/src/metadata/ActionMetadata.ts:250:62)
   at /home/base/node/src/RoutingControllerExecutor.ts:92:35
   at process._tickCallback (internal/process/next_tick.js:103:7)
````

When instantiating `Item` and `SisterItem` classes together
````
let i = new Item();
let s = new SisterItem();
````
No problem with `Item`, but the `SisterItem` causes the same error above.

My workaround is putting `BaseItem`,`Item` and `SisterItem` together in the same ts file. Can you figure out what's the cause of it?

**Comment by pleerock** [comment]
What is `BasedItemInfo` here?

**Comment by stonecold123** [comment]
A typo. It should be `BaseItem`.

**Comment by pleerock** [comment]
does not look like its typeorm error. You have some problem somewhere else I believe.

**Comment by stonecold123** [comment]
Probably. I clone the classes as other names and it works fine. Weird.

**Comment by stonecold123** [comment]
To be more accurate, the name of the abstract class `BasedItemInfo` is causing all the trouble.
