### ISSUE TITLE
parameters not substituted in sql when inserting into a many-to-many relationship 

### ISSUE THREAD

**Issue by iamwindy** [typeorm/typeorm#2612]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello!

There is a many to many connection between two entities, like this (only the relevant code is there):

```
@Entity('coupons')
export class Coupon {
@PrimaryGeneratedColumn()
  couponId: number
@ManyToMany(type => Collection, item => item.coupons)
  @JoinTable({
    name: 'coupons_collections_rel'
  })
  collections: Collection[]
@RelationId((item: Coupon) => item.collections)
  collectionIds: number[]
}

@Entity('collections')
export class Collection {
@PrimaryGeneratedColumn()
  collectionId: number
@ManyToMany(type => Coupon, item => item.collections)
  coupons: Coupon[]
}

```

Lets say there is an existing row in the collections table, with collectionId = 1
and i want to create a coupon and connect them with the relation table
the implementation currently looks like this:

```
async createEntity(entity: Coupon): Promise<DbResult> {
    const result = await getConnection()
      .createQueryBuilder()
      .insert()
      .into(Coupon)
      .values([entity])
      .execute()

    const couponId = (result.raw as DbResult).insertId
    console.log(couponId, entity.collectionIds)
    try {
      if (entity.collectionIds && entity.collectionIds.length > 0) {
        await getConnection()
            .createQueryBuilder()
            .relation(Coupon, 'collections')
            .of(couponId)
            .add(entity.collectionIds[0])
      }
    } catch (e) {
      console.log(e)
    }
  return result.raw
}
```

the DbResult is only an interface to be typesafe inside the project, dont worry about that.
The coupon is created, and the couponId declared is the generated Id by mysql, and when i try to add an array of collectionIds (collectionIds is [ 1 ]) an error is catched, like this:

```
{ QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'coupons_coupon_id' doesn't have a default value
    at new QueryFailedError (/.../src/error/QueryFailedError.ts:7:9)
    at Query._callback (/.../src/driver/mysql/MysqlQueryRunner.ts:161:37)
    at Query.Sequence.end (/.../node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (.../node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/.../node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/.../node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/.../node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
  message: 'ER_NO_DEFAULT_FOR_FIELD: Field \'coupons_coupon_id\' doesn\'t have a default value',
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: 'Field \'coupons_coupon_id\' doesn\'t have a default value',
  sqlState: 'HY000',
  index: 0,
  sql: 'INSERT INTO `coupons_collections_rel`(`coupons_coupon_id`, `collections_collection_id`) VALUES (DEFAULT, DEFAULT)',
  name: 'QueryFailedError',
  query: 'INSERT INTO `coupons_collections_rel`(`coupons_coupon_id`, `collections_collection_id`) VALUES (DEFAULT, DEFAULT)',
  parameters: [] }
```
am i missing something i didnt implement? i tried to use the code in your test files to match, but i have no success so far. i am guessing the parameters somehow is not passed into the function, can you guys help me out a bit? thanks in advance

**Comment by iamwindy** [comment]
also, im using custom naming strategy, maybe that might could be a source of bug?

the naming strategy is the following:
```
export class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {

  tableName(targetName: string, userSpecifiedName: string): string {
    return userSpecifiedName ? userSpecifiedName : snakeCase(targetName)
  }

  columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
    return snakeCase(embeddedPrefixes.concat(customName ? customName : propertyName).join('_'))
  }

  columnNameCustomized(customName: string): string {
    return customName
  }

  relationName(propertyName: string): string {
    return snakeCase(propertyName)
  }

}

```

**Comment by iamwindy** [comment]
another remark: the deletion works very well, the parameters are bound to the sql query even with arrays too, for example:

```
DELETE FROM `coupons_collections_collections` WHERE (coupons_coupon_id = ? AND collections_collection_id = ?) OR (coupons_coupon_id = ? AND collections_collection_id = ?) OR (coupons_coupon_id = ? AND collections_collection_id = ?) -- PARAMETERS: [1,1,2,1,3,1]

```

**Comment by jorenl** [comment]
I'm new to typeorm, but I ran into what looks like this exact issue today, and stepped through the typeorm code in a debugger to figure out where the DEFAULT values are being set. 

Importantly, I believe this issue only occurs **when you also have an Entity defined for the join table specified with `@JoinTable`** . Removing this entity fixed this issue for me.

In particular, this line returns an `undefined` value when the insert query is being built for the join table, which gets turned into `DEFAULT` in the query:
https://github.com/typeorm/typeorm/blob/master/src/query-builder/InsertQueryBuilder.ts#L744
