### ISSUE TITLE
Webpack + HMR. Error on entity change. No repository was found.

### ISSUE THREAD

**Issue by ph55** [typeorm/typeorm#2616]
I've configured HMR and it works fine.
There was some limitations that you have to import each entity manually in connection, without glob pattern.
So I did and it works until some of entities changed/edited. Then error thrown.

If I change `Config` entity for example:

```js
[Nest] 10524   - 2018-8-1 13:10:45   [ExceptionHandler] No repository for "Config" was found. Looks like this entity is not registered in current "default" connection?
RepositoryNotFoundError: No repository for "Config" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (C:\Users\alex\Documents\_dev\apps_node\node_modules\typeorm\error\RepositoryNotFoundError.js:20:28)
    at EntityManager.getRepository (C:\Users\alex\Documents\_dev\apps_node\node_modules\typeorm\entity-manager\EntityManager.js:580:19)
    at Connection.getRepository (C:\Users\alex\Documents\_dev\apps_node\node_modules\typeorm\connection\Connection.js:358:29)
    at getRepository (C:\Users\alex\Documents\_dev\apps_node\node_modules\@nestjs\typeorm\dist\typeorm.providers.js:13:26)
    at Object.useFactory [as metatype] (C:\Users\alex\Documents\_dev\apps_node\node_modules\@nestjs\typeorm\dist\typeorm.providers.js:22:20)
    at resolveConstructorParams (C:\Users\alex\Documents\_dev\apps_node\node_modules\@nestjs\core\injector\injector.js:67:55)
    at Injector.resolveConstructorParams (C:\Users\alex\Documents\_dev\apps_node\node_modules\@nestjs\core\injector\injector.js:86:30)
    at <anonymous>
 1: std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >
 2: v8::internal::CompilerDispatcherTracer::Estimate
 3: v8::internal::CompilerDispatcher::RemoveJob
 4: v8::internal::CompilerDispatcher::RemoveJob
 5: v8::internal::CompilerDispatcher::RemoveJob
 6: 0000037D4CA847A1
```

HMR output:
```
[HMR] Updated modules:
[HMR]  - ./src/@core/config/config.entity.ts
[HMR]  - ./src/@core/config/config.service.ts
[HMR]  - ./src/@core/config/config.module.ts
[HMR]  - ./src/app-one/db/entities.ts
[HMR]  - ./src/app-one/db/db.module.ts
[HMR]  - ./src/app-one/main.module.ts
[HMR]  - ./src sync recursive ^\.\/.*\/main\.module$
[HMR]  - ./src/app.module.ts
[HMR]  - ./src/main.ts
[HMR]  - ./src/app-one/common/common.module.ts
[HMR]  - ./src/@core/config/config.resolver.ts
[HMR] Update applied.
```

Any ideas or hints why it's happening ?

**Comment by minextu** [comment]
I'm having the same issue. Where you able to solve it, or find a workaround?

**Comment by vlapo** [comment]
I think this should be problem of configuration. I think HMR will use ts-node and path to entities could be different for ts-node and classical js compiled from TS. So typeorm cannot find and register entities.

Try define `entities` property in configuration different way. E.g. 
```
entities: [__dirname + '/../**/**.entity{.ts,.js}'],
```
This is configuration from our project and I think it is ok with ts-node and js too. 
I will try test it in our nestjs app. But cannot promise.

**Comment by plashenkov** [comment]
> Im not sure how this is related to typeorm. Can someone point where is there typeorm's problem?

@pleerock TypeORM doesn't provide a way to handle this quite common situation. Currently we have to deal with hacky solutions similar to this:

```ts
async function updateConnectionOptions(connection: Connection, options: ConnectionOptions): Promise<Connection> {
  // @ts-ignore
  connection.options = options;
  // @ts-ignore
  connection.buildMetadatas();
  await connection.synchronize();
  return connection;
}

function ensureConnection(name: string = 'default'): Promise<Connection> {
  const options = {
    default: {
      type: 'mysql',
      url: process.env.DATABASE_URL,
      synchronize: process.env.NODE_ENV !== 'production',
      entities: [
        // entities...
      ],
    },
  };

  const connectionManager = getConnectionManager();

  if (connectionManager.has(name)) {
    const connection = connectionManager.get(name);

    if (process.env.NODE_ENV !== 'production') {
      await updateConnectionOptions(connection, { name, ...options[name] });
    }

    return connection;
  }

  return await connectionManager.create({ name, ...options[name] }).connect();
}
```

I am not even sure this `updateConnectionOptions()` implementation is totally correct. We patch private property here as well as call a protected method. And maybe miss something important. I believe something proved and out of the box should be included in TypeORM — for example:
```ts
connection.updateOptions(options);
```
