### ISSUE TITLE
Migrations fail if database name include dots

### ISSUE THREAD

**Issue by eddieajau** [typeorm/typeorm#2675]
**Issue type:**

[X] bug report

**Database system/driver:**

[X] `mysql` / `mariadb`

**TypeORM version:**

[X] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. CREATE a database name like "mumba.cloud".
1. RUN any migration.
1. OBSERVE an SQL error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`cloud`.`__typeorm` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT N' at line 1
```

The root cause is that while database names with dots are permitted by MySQL, TypeORM is not escaping it. See:

```js
    MysqlDriver.prototype.buildTableName = function (tableName, schema, database) {
        return database ? database + "." + tableName : tableName;
    };
```

The result is that the value `migrationsTableName` in `MigrationExecutor` will end up being something like "mumba.cloud.__typeorm".

That name is obviously escaped later in the process to be, I suspect looking at the error "\`mumba\`.\`cloud\`.\`__typeorm\`" instead of "\`mumba.cloud\`.\`__typeorm\`".

Thoughts on how this can be fixed? Thanks in advance.

**Comment by DomenicoCasillo** [comment]
I have the same issue as @eddieajau . My database name is 'test.mydomain.net' and when trying to run migrations for the first time, it fails trying to create the migration table as the dots in the name are not escaped.

`query failed: CREATE TABLE `test`.`mydomain`.`net`.`migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB`

**Comment by eddieajau** [comment]
@DomenicoCasillo we ended up renaming our databases, replacing dot with underscore, to work around the issue.

**Comment by DomenicoCasillo** [comment]
> @DomenicoCasillo we ended up renaming our databases, replacing dot with underscore, to work around the issue.

Thank You, I did exactly the same to workaround the issue.

**Comment by nbraquart** [comment]
Hello,
This problem affects the synchronize behaviour as well as relations creation:

```
creating a foreign keys: FK_1249e773babb17585f898bf38c4 on table "ad"
query: ALTER TABLE `ad` ADD CONSTRAINT `FK_1249e773babb17585f898bf38c4` FOREIGN KEY (`propertyId`) REFERENCES `test-1`.`0`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
query failed: ALTER TABLE `ad` ADD CONSTRAINT `FK_1249e773babb17585f898bf38c4` FOREIGN KEY (`propertyId`) REFERENCES `test-1`.`0`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
error: Error: Can't create table `test-1.0`.`ad` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Packet.asError (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/nbraquart/Projects/test/api/node_modules/mysql2/lib/connection.js:92:25)
```

**Comment by jovanadjuric** [comment]
Closing as not planned. @LeoFeilke had already tried to implement this, but he changed his mind as this would require a major rewrite of some core methods: https://github.com/typeorm/typeorm/pull/8926#issuecomment-1273218382

Using dots in identifier names isn't a good idea because they are used in some SQL dialects for separating different logical units (e.g. `database.schema.table`), and the ORM would need to wrap them with [] or "" in the right way, depending on many factors. Too much effort for too little benefit in my opinion
