### ISSUE TITLE
TypeORM test save() with a mock repository?

### ISSUE THREAD

**Issue by kheob** [typeorm/typeorm#2697]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to write a test to test the creation of a `User` object and saving it to a database.

user.service.spec.ts
```typescript
describe('UserService', () => {
  let service: UserService;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UserService,
        {
          provide: getRepositoryToken(User),
          useClass: UserRepository,
        },
      ],
    }).compile();
    service = module.get<UserService>(UserService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  it('can create a user', async () => {
    const userDto = new UserDto();
    userDto.email = 'test@test.com';
    userDto.password = 'password123';
    const user = await service.create(userDto);
    expect(user.username).toEqual(userDto.email);
  });
});
```

user.service.ts
```typescript
@Injectable()
export class UserService {
  constructor(
    @InjectRepository(User) private readonly userRepository: UserRepository,
  ) {}

  async create(userDto: UserDto): Promise<User> {
    const user = new User();
    user.username = userDto.email;
    user.password = userDto.password; // TODO: Need to hash this later
    return await this.userRepository.save(user);
  }
}
```

However it throws an error when trying to `save()` - How can I properly test this?

The error is:
```
 FAIL  src/user/user.service.spec.ts
  ● UserService › can create a user

    TypeError: Cannot read property 'save' of undefined

      at UserRepository.Object.<anonymous>.Repository.save (repository/Repository.ts:138:29)
      at UserService.<anonymous> (user/user.service.ts:17:38)
          at Generator.next (<anonymous>)
      at user/user.service.ts:19:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (user/user.service.ts:15:12)
      at UserService.create (user/user.service.ts:33:16)
      at Object.<anonymous> (user/user.service.spec.ts:32:32)
          at Generator.next (<anonymous>)
      at user/user.service.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (user/user.service.spec.ts:3:12)
      at Object.it (user/user.service.spec.ts:28:38)
          at new Promise (<anonymous>)
      at process._tickCallback (../internal/process/next_tick.js:68:7)
```

**Comment by jeffrey-kor** [comment]
How does this solved ? I have same issue
