### ISSUE TITLE
Query Issue with Oracle

### ISSUE THREAD

**Issue by ramsharma4** [typeorm/typeorm#2742]
**Issue type:**

[ ] question
[* ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[*] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

let firstUser: appuser = await getRepository(appuser)
    .createQueryBuilder("appuser")
    .select("username").addSelect("password")
    .where("appuser.username = :username", { username: username })
    .andWhere("appuser.password = :password", { password: encryptedPassword })
    .andWhere("appuser.enabled = :enabled", { enabled: 1 })
    .andWhere("appuser.account_expired = :account_expired", {
      account_expired: 0
    }) .getOne();

Above command produces SQL query as below.

SELECT username, password FROM "dbo"."appuser" "appuser" WHERE "appuser"."username" = :username AND "appuser"."password" = :password AND "appuser"."enabled" = :enabled AND "appuser"."account_expired" = :account_expired

**But this query is fails in Oracle. Why TypeORM appends "dbo" before appuser. Also I believe this double quote syntex "dbo"."appuser" "appuser" not works in oracle.**

When I try to execute code below I get error from typeorm

(node:14524) UnhandledPromiseRejectionWarning: QueryFailedError: ORA-00942: table or view does not exist
    at new QueryFailedError (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\src\error\QueryFailedError.ts:7:9)
    at handler (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\src\driver\oracle\OracleQueryRunner.ts:167:37)
    at custExecuteCb (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\node_modules\oracledb\lib\connection.js:157:7)

**Comment by gintsgints** [comment]
@ramsharma4 can you pls give your Entity source?

**Comment by ramsharma4** [comment]
[appuser.zip](https://github.com/typeorm/typeorm/files/2336608/appuser.zip)

**Comment by ramsharma4** [comment]
This is working well with SQL server but issue with Oracle.

**Comment by gintsgints** [comment]
You probably have @Entity() before entity yes (do not have in your attached source)?
Some options there?

**Comment by ramsharma4** [comment]
Yes, it was there like below.

@Entity("appuser",{schema:"dbo"})

I removed {schema:"dbo"} from above to avoid dbo in sql query.
but still table name and alias in double quote not working in oracle.

SELECT username, password FROM "appuser" "appuser" WHERE "appuser"."username" = :username AND "appuser"."password" = :password AND "appuser"."enabled" = :enabled AND "appuser"."account_expired" = :account_expired AND "appuser"."account_locked" = :account_locked AND "appuser"."credentials_expired" = :credentials_expired -- PARAMETERS: ["test","536c0b339345616c1b33caf454454d8b8a190d6c",1,0,0,0]
{ [Error: ORA-00942: table or view does not exist] errorNum: 942, offset: 31 }
3772) UnhandledPromiseRejectionWarning: QueryFailedError: ORA-00942: table or view does not exist
new QueryFailedError (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\src\error\QueryFailedError.ts:7:9)
handler (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\src\driver\oracle\OracleQueryRunner.ts:167:37)
custExecuteCb (E:\eMessaging_Trunks\2018\Trunk\NodeApp\Report_API_NodeJS\node_modules\oracledb\lib\connection.js:157:7)

**Comment by gintsgints** [comment]
This select

```
SELECT RV_DOMAIN, RV_LOW_VALUE
FROM "CG_REF_CODES" "appuser" WHERE "appuser"."RV_DOMAIN" = 'FIN_FINANCE_YEAR_BUDGETING_STATUSES'
```

Works fine for me with double quotes. Pls check your field name. password is oracle reserved word.

**Comment by gintsgints** [comment]
Oh... I see what you mean. 
this:
```
SELECT RV_DOMAIN, RV_LOW_VALUE
FROM "cg_ref_codes" "appuser"
```
Will not work if you have table with big letters. How about you put in Entity options "APPUSER" ?

**Comment by ramsharma4** [comment]
Yes, this was the issue. 

 Entity options "APPUSER" worked for me. 

Thanks for prompt help :)

**Comment by ramsharma4** [comment]
Do we have some option on TypeORM to avoid double quotes around column name in generated SQL.
Iit is also causing issue in Oracle.
ORA-00904: "APPUSER"."secret_question_id": invalid identifier] errorNum: 904, offset: 1167 }

without "" query works fine in SQL Developer.

**Comment by gintsgints** [comment]
Do not think so. Quote usage is imho managed by driver. But it should work fine if you are consistent with big small letter usage.

**Comment by cgers** [comment]
> Do we have some option on TypeORM to avoid double quotes around column name in generated SQL.
> Iit is also causing issue in Oracle.
> ORA-00904: "APPUSER"."secret_question_id": invalid identifier] errorNum: 904, offset: 1167 }
> 
> without "" query works fine in SQL Developer.

I have the same issue. This is the query that is generated:
query: 

> SELECT "TITLE"."TITLEID" AS "TITLE_TITLEID", "TITLE"."NAME" AS "TITLE_NAME", "TITLE"."CREATEDON" AS "TITLE_CREATEDON" FROM "XXtitle" "TITLE"

query failed: 

> SELECT "TITLE"."TITLEID" AS "TITLE_TITLEID", "TITLE"."NAME" AS "TITLE_NAME", "TITLE"."CREATEDON" AS "TITLE_CREATEDON" FROM "XXtitle" "TITLE"

error: { [Error: ORA-00942: table or view does not exist] errorNum: 942, offset: 123 }

If you run this query in SQL Developer for Oracle you get this same error. If I remove the double quotes, the query executes correctly => 

> SELECT TITLE.TITLEID AS TITLE_TITLEID, TITLE.NAME AS TITLE_NAME, TITLE.CREATEDON AS TITLE_CREATEDON FROM XXtitle TITLE

![query](https://user-images.githubusercontent.com/14121781/52482910-704c6400-2baa-11e9-9384-a4868df4d814.PNG)

**Comment by shad0xfox** [comment]
@cgers 
It might be your table name setting problem, it should be uppercase of your table name and column name.
String in double quote is case sensitive, and might cause some problem.

@entity('XXXTITLE') can fix this IMO.
