### ISSUE TITLE
Query using inner-join, orderby and take from entity that include other embedded entity

### ISSUE THREAD

**Issue by dungnguyen2703** [typeorm/typeorm#2771]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!> 

Hi,

I 've got error when query using combine inner-join, orderby and take embedded entity

Description:

- Profile: column firstname, lastname
- Doctor: column id, Profile (embedded entity)
- Package: column id
- Doctor have many Package

Query
return this.manager.createQueryBuilder(Doctor, "d")
          .innerJoin("d.packages", "p")
          .orderBy({
              "d.profile.firstname": "ASC",
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

Error
{
    "name": "TypeError",
    "message": "Cannot read property 'databaseName' of undefined",
    "stack": "TypeError: Cannot read property 'databaseName' of undefined\n    at E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1852:114\n    at Array.map (<anonymous>)\n    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1847:14)\n    at SelectQueryBuilder.<anonymous> (E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1765:46)\n    at step (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:42:23)\n    at Object.next (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:23:53)\n    at E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:17:71\n    at new Promise (<anonymous>)\n    at __awaiter (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:13:12)\n    at SelectQueryBuilder.executeEntitiesAndRawResults (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:1344:16)"
}

But if I query

return this.manager.createQueryBuilder(Doctor, "d")
          .innerJoin("d.packages", "p")
          .orderBy({
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

=> Work well

or 

return this.manager.createQueryBuilder(Doctor, "d")
          .orderBy({
              "d.profile.firstname": "ASC",
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

=> Work well

Please review

**Comment by dungnguyen2703** [comment]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!> 

Hi,


I 've got error when query using combine inner-join, orderby and take embedded entity

Description:

- Profile: column firstname, lastname
- Doctor: column id, Profile (embedded entity)
- Package: column id
- Doctor have many Package

Query
return this.manager.createQueryBuilder(Doctor, "d")
          .innerJoin("d.packages", "p")
          .orderBy({
              "d.profile.firstname": "ASC",
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

Error
{
    "name": "TypeError",
    "message": "Cannot read property 'databaseName' of undefined",
    "stack": "TypeError: Cannot read property 'databaseName' of undefined\n    at E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1852:114\n    at Array.map (<anonymous>)\n    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1847:14)\n    at SelectQueryBuilder.<anonymous> (E:\\Git\\cloud273\\mcs\\mcs-server\\src\\query-builder\\SelectQueryBuilder.ts:1765:46)\n    at step (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:42:23)\n    at Object.next (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:23:53)\n    at E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:17:71\n    at new Promise (<anonymous>)\n    at __awaiter (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:13:12)\n    at SelectQueryBuilder.executeEntitiesAndRawResults (E:\\Git\\cloud273\\mcs\\mcs-server\\node_modules\\typeorm\\query-builder\\SelectQueryBuilder.js:1344:16)"
}

But if I query

return this.manager.createQueryBuilder(Doctor, "d")
          .innerJoin("d.packages", "p")
          .orderBy({
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

=> Work well

or 

return this.manager.createQueryBuilder(Doctor, "d")
          .orderBy({
              "d.profile.firstname": "ASC",
              "d.id": "ASC"
          })
          .take(limit)
          .getMany()

=> Work well

Please review 
[type-orm issue.txt](https://github.com/typeorm/typeorm/files/2351831/type-orm.issue.txt)
