### ISSUE TITLE
sql.js package has not been found installed (ionic)

### ISSUE THREAD

**Issue by Jasemalsadi** [typeorm/typeorm#2788]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am new to typeorm and I am following **exactly** this [ionic example](https://github.com/typeorm/ionic-example) . 
I added webpack config as ionic repo written. And I added this code in app.component.ts :  
```
      if(platform.is('cordova')) {
        await createConnection({
          type: 'cordova',
          database: 'sqljs',
          location: 'default',
          logging: ['error', 'query', 'schema'],
          synchronize: true,
          entities: [Star]
        })
      } else {
        await createConnection({
          type: 'sqljs',
          autoSave: true,
          location: 'browser',
          logging: ['error', 'query', 'schema'],
          synchronize: true,
          entities: [Star]
        })


      }
```
So sql.js will work in browser and the cordova-sqlite in emulator , I am using typeorm like this in one of the component: 
```

   let star: Star = new Star(22, userStaticContent, rankingDetails, socialLinks);
    let  manager = getManager();
    manager.save(star);

```

However, it stills give me the this error(in browser ) and it crash in emulator or real device : 

```
Error: Uncaught (in promise): DriverPackageNotInstalledError: sql.js package has not been found installed. Try to install it: npm install sql.js --save
DriverPackageNotInstalledError: sql.js package has not been found installed. Try to install it: npm install sql.js --save
    at new DriverPackageNotInstalledError (http://localhost:8100/build/vendor.js:43808:28)
    at SqljsDriver.loadDependencies (http://localhost:8100/build/vendor.js:62568:23)
    at new SqljsDriver (http://localhost:8100/build/vendor.js:62319:15)
    at DriverFactory.create (http://localhost:8100/build/vendor.js:232368:24)
    at new Connection (http://localhost:8100/build/vendor.js:124729:59)
    at ConnectionManager.create (http://localhost:8100/build/vendor.js:124625:26)
    at http://localhost:8100/build/vendor.js:25089:66
    at step (http://localhost:8100/build/vendor.js:24891:23)
    at Object.next (http://localhost:8100/build/vendor.js:24872:53)
    at http://localhost:8100/build/vendor.js:24866:71
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at new t (http://localhost:8100/build/polyfills.js:3:21532)
    at __awaiter (http://localhost:8100/build/vendor.js:24862:12)
    at createConnection (http://localhost:8100/build/vendor.js:25074:12)
    at http://localhost:8100/build/main.js:3715:83
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
```
I tried re install all necessary plugins but nothing seems working for me :(

**Any help :)**

**Comment by jondediego** [comment]
Hi,
Have you installed sql.js library?
 npm install sql.js
If you have, trye requiring it first: (<any>window).SQL = require('sql.js');

**Comment by Jasemalsadi** [comment]
@jondediego  Yes it's installed.

**Comment by Jasemalsadi** [comment]
Fixed by installing sql.js on dev only.
