### ISSUE TITLE
Entity Example in Docs Results in Error.

### ISSUE THREAD

**Issue by gpresland** [typeorm/typeorm#2797]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using TypeScript 3.0, _README_ documentation for creating an entity results in a TypeScript error:
```
Property <name> has no initializer and is not definitely assigned in the constructor.
```

Documentation should state upfront that either:

A) "strictPropertyInitialization": false` must be added to _tsconfig.json_.

or

B) Use the !/exclamation/bang:

```typescript
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column()
    firstName!: string;

    @Column()
    lastName!: string;

    @Column()
    age!: number;

}
```

**Comment by dominicdesu** [comment]
Could you add a link to the documentation which should be updated? This would make it easier for the maintainers to fix this issue.

**Comment by Kononnable** [comment]
If I remember correctly sometimes typeorm returned only some properties filled in entity object - when using partial selection. Not sure if it was changed later, but (if not changed) correct form would be `firstName: string | undefined;`. `!` tells compiler, that property is always initialized which isn't the case.
The solution for typeorm to be compatible with this strict flag would be to return Partial<User> in such cases, but it could be a breaking change.

**Comment by dominicdesu** [comment]
@bcherny thanks for pointing out the problem, I thought it was an issue when using e.g. the create() method of the repository.
The partial select which @Kononnable mentioned is described here: http://typeorm.io/#/select-query-builder/partial-selection. But even if typeorm would return a Partial, you would still need to use one of the three solutions, wouldn't you? Or was your intention to say that with the Partial it would be fine to use `!`  ?

Anyway, for now it's probably the best to mention all three solutions/workarounds in the documentation and update the examples to user `string | undefined`?.

**Comment by Kononnable** [comment]
If typeorm would return Partial<T> then no changes to the entity model would be necessary to be compatible with strictPropertyInitialization flag.
Partial of type T means that every property in type T can be set as undefined - so it is `firstName: string | undefined` but without actually writing such code. Some  methods always return every column in entity so in such cases it's safe to return type T.

It's the best solution I can think of right now(we are sure when entity object contains data for every column - has every property initialized and we tell that to compiler), but a lot of changes would be required in user code if they want to make theirs existing app ready for strictPropertyInitialization flag(but it's their choice if they want to enable the flag). 
There still will be solution to disable that flag only for typeorm(use `!` or `| undefined` in models) - some people might choose that instead of changing theirs code but I would advice against it - it's better to disable flag entirely..

e.g. following code would be wrong - we would have to use partial
```typescript
  let user = new User();
  user.firstName = 'a';
  user.lastName = 'b';
  user.age = 1;
  await con.getRepository(User).save(user);
```

I think that subject should be really discussed before changing something in that area. For now we may point out in docs that typeorm isn't strictPropertyInitialization flag compatible and put info about workaround(but people should be aware that it is just disabling that flag for typeorm entities, not fixing the problem)

**Comment by n8sabes** [comment]
Any progress toward a real solution on this issue that doesn't subvert the benefits of TypeScript?

1. Setting `strictPropertyInitialization = false` in tsconfig.json seems like a really bad workaround.
2. Using `!` or `| undefined` seems less bad.

```
    @Column()
    name!: string;
```

I'm using this workaround for now, but, uncertain the best way(s) to ensure bugs don't wiggle into the codebase:
```
    @Column()
    name: string | undefined;
```

**Comment by adamwdennis** [comment]
What is the ideal solution here?

**Comment by gsusI** [comment]
In **tsconfig.json** file under **compilerOptions**, add `"strictPropertyInitialization": false`:

```json
{
  "compilerOptions": {
    ...
    "strictPropertyInitialization": false"
```

**Comment by 1valdis** [comment]
@gsusI I don't want to disable `strictPropertyInitialization` only for the sake of typeorm entities working. Any other solution?

**Comment by adamwdennis** [comment]
@1valdis I am now using explicit `!` for required and `?` for optional, and it seems to have resolved the issue for me.

**Comment by sirrodgepodge** [comment]
I actually think this is a kinda elegant way of mapping "required" and "optional" relationships.  The unfortunate part is that "required" is not actually enforced (maybe there are benefits to this while constructing record, would be nice to enforce for say for the `save()` operation).  I imagine this is a bit of a typescript puzzle to get that working though.

**Comment by evamass** [comment]
@imnotjames can that update of TypeScript 4.0 help us something with that problem?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#class-property-inference-from-constructors

**Comment by athyuttamre** [comment]
My ideal solution would be that TypeORM _require_ that developers write constructors that take in all required params and manually set them on the model.

Consider the following code that we would write today:

```
import {Entity, PrimaryGeneratedColumn, Column, BaseEntity} from "typeorm";

@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column()
    firstName!: string;

    @Column()
    lastName!: string;

    @Column()
    age!: number;

}

const user = new User();
user.firstName = "Timber";
user.lastName = "Saw";
user.age = 25;
await user.save();
```

In this code, if you forget to set a required value, TypeORM will throw a runtime error, but not a compile time one. Ideally, we should get a compile time error.

Instead, if TypeORM required us to set these values in the constructor, then we wouldn't need to use `!` or disable `strictPropertyInitialization`. The code becomes:

```
import {Entity, PrimaryGeneratedColumn, Column, BaseEntity} from "typeorm";

@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

    constructor(props: {firstName: string, lastName: string}) {
        super();
        this.firstName = props.firstName;
        this.lastName = props.lastName;
    }
}

const user = new User({firstName: "Timber", lastName: "Saw"});
await user.save();
```

If we try to do this today, we get a TypeScript error in the depths of `createConnection`.

```
TypeError: Cannot read property 'firstName' of undefined
    at new User (/Users/athyuttamre/Work/github/test/server/models/User.ts:30:23)
    at EntityMetadata.create (/Users/athyuttamre/Work/github/test/server/src/metadata/EntityMetadata.ts:525:19)
    at EntityMetadataValidator.validate (/Users/athyuttamre/Work/github/test/server/src/metadata-builder/EntityMetadataValidator.ts:115:47)
    at /Users/athyuttamre/Work/github/test/server/src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/athyuttamre/Work/github/test/server/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/Users/athyuttamre/Work/github/test/server/src/connection/Connection.ts:527:33)
    at Connection.<anonymous> (/Users/athyuttamre/Work/github/test/server/src/connection/Connection.ts:193:18)
    at step (/Users/athyuttamre/Work/github/test/server/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/athyuttamre/Work/github/test/server/node_modules/tslib/tslib.js:122:57)
```

IMO until creation is type safe and does not allow not-setting-required-values, we're not at full type safety.

**Comment by gitDylanHub** [comment]
You can read inside of the documentation on [Extending Schemas](https://typeorm.io/#/separating-entity-definition/extending-schemas).  If you read the paragraph right above this link and the samples below it should be helpful for understanding my proposed solution.  

Instead of updating TypeORM why not use the built-in feature for making your entity type-safe.  Implementing this you don't have to sacrifice your TypeScript implementation against your project and/or implement the bang("!") on the class definition.

A bit new to TypeORM so maybe not as clean as I am assuming here but I think this helps bypass the default value of your entity instead of dropping it in a class, as the class would look for the constructor or default value.  And a default value on the entity is considered a bad practice due to the danger it proposes. 

For Example: 
```javascript
import { EntitySchema } from 'typeorm';

export interface User { 
    id: number;
    firstName: string;
    lastName: string;
    age: number;
}

export const UserEntity = new EntitySchema<User>({
    name: 'user',
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true
        },
        firstName: {
            type: String
        },
        lastName: {
            type: String
        },
        age: {
            type: Number
        }
    }
});
```

**Comment by MichaelMitchellM** [comment]
@gitDylanHub How would this work if you're also using the entity to define a TypeGraphQL Object?

**Comment by gitDylanHub** [comment]
> @gitDylanHub How would this work if you're also using the entity to define a TypeGraphQL Object?

Not sure @MichaelMitchellM. Depending on what your Model looks like I would think it would be similar.  However, I am not familiar with GraphQL's implementation.  I've used it very little.

**Comment by kirkdave** [comment]
I've got around this by putting my entity definitions into a separate lib that I can import using `paths` property in `tsconfig.json`. I can then create a child `tsconfig.json` file for the entities lib that extends the parent `tsconfig.json` but sets the `strictPropertyInitialization` property to `false`.

This means I don't get that error / warning on my TypeORM entities but the rest of my project is still covered by `strictPropertyInitialization`

**Comment by developerasun** [comment]
this is a working example I'm using for my side project. 

needed to compile first, and then start migration.

I changed `entities` and `migrations` options in data source config from `.ts` to `.js`  with target directory is `dist`.

deps in package.json

```json
"ts-node": "^10.9.1",
"tsconfig-paths": "^4.2.0",
"typeorm": "^0.3.20",
"npm-run-all": "^4.1.5",
```

command in package.json

```json
"build:dev": "nest build",
"_typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js",
"orm:_run": "pnpm _typeorm -d ./src/database/source.config.ts migration:run",
"orm:run": "run-s build:dev orm:_run"
```

```ts
// source.config.ts
export default new DataSource({
  type: 'mysql',
  host: process.env.MYSQLHOST!,
  port: +process.env.MYSQLPORT!,
  username: process.env.MYSQLUSER!,
  password: process.env.MYSQL_ROOT_PASSWORD!,
  database: process.env.MYSQL_DATABASE!,
  synchronize: false,
  entities: ['dist/database/entity/*.js'],
  migrations: ['dist/database/migrations/*-target.js'],
  migrationsTableName: 'migrations',
})
```

run `orm:run` with your package manager.

Hope it helps! :)
