### ISSUE TITLE
Running npm test only executes 11 tests?

### ISSUE THREAD

**Issue by dominicdesu** [typeorm/typeorm#2807]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi I am trying to run all tests with the sqlite database enabled.
However, it seems like only 11 tests are being executed, and no error message is displayed either. This is the output:

```
PS C:\Projects\typeorm> npm test

> typeorm@0.2.7 test C:\Projects\typeorm
> tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 30000  ./build/compiled/test



  benchmark > bulk-save > case1
    √ testing bulk save of 10.000 objects

  benchmark > bulk-save > case2
    √ testing bulk save of 10000 objects

  cascades > should insert by cascades from both sides (#57)
    √ should insert by cascades from owner side (47ms)

  columns > embedded columns
    √ should insert / update / remove entity with embedded correctly (49ms)
    √ should properly generate column names

  columns > getters and setters
    √ should not update columns marked with readonly property

  columns > no-selection functionality
    √ should not select columns marked with select: false option
    √ should not select columns with QueryBuilder marked with select: false option
    √ should select columns with select: false even columns were implicitly selected

  columns > readonly functionality
    √ should not update columns marked with readonly property

  columns > value-transformer functionality
    √ should marshal data using the provided value-transformer

  Connection
    before connection is established

  11 passing (678ms)

      1) "before all" hook
      2) "after all" hook
```

It seems to stop when it would execute an mysql test, but mysql is disabled in my ormconfig.json:

```
[
  {
    "skip": true,
    "name": "mysql",
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "test",
    "password": "test",
    "database": "test",
    "logging": false
  },
  {
    "skip": true,
    "name": "mariadb",
    "type": "mariadb",
    "host": "localhost",
    "port": 3307,
    "username": "test",
    "password": "test",
    "database": "test",
    "logging": false
  },
  {
    "skip": false,
    "name": "sqlite",
    "type": "sqlite",
    "database": "temp/sqlitedb.db",
    "logging": false
  },
  {
    "skip": true,
    "name": "postgres",
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "test",
    "password": "test",
    "database": "test",
    "logging": false
  },
  {
    "skip": true,
    "name": "mssql",
    "type": "mssql",
    "host": "localhost",
    "username": "sa",
    "password": "Admin12345",
    "database": "tempdb",
    "logging": false
  },
  {
    "skip": true,
    "name": "oracle",
    "type": "oracle",
    "host": "localhost",
    "username": "system",
    "password": "oracle",
    "port": 1521,
    "sid": "xe.oracle.docker",
    "logging": false
  },
  {
    "skip": true,
    "disabledIfNotEnabledImplicitly": true,
    "name": "mongodb",
    "type": "mongodb",
    "database": "test",
    "logging": false
  },
  {
    "skip": true,
    "name": "sqljs",
    "type": "sqljs",
    "logging": false
  }
]
```

What am I doing wrong?

**Comment by elthrasher** [comment]
The `--bail` argument means the tests will abort on the first failure. Looks like something is failing. Edit your `package.json` to remove that and at least you should see all the tests run.

**Comment by elthrasher** [comment]
Another thing I just noticed. `ormconfig.travis.json` and `ormconfig.json.dist` have different values. Looks like some of the tests expect the travis values. Try running tests with those values.

**Comment by dominicdesu** [comment]
@elthrasher Thanks for the reply, I'll try to apply your suggestions and report back here!

**Comment by dominicdesu** [comment]
As it seems there are some tests which rely on the mysql database which I don't have installed. Even though I've disabled mysql in the ormconfig.json, the tests are still executed:
```
 1) Connection
       before connection is established
         "before all" hook:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Suite.<anonymous> (test\functional\connection\connection.ts:29:56)
      at step (build\compiled\test\functional\connection\connection.js:32:23)
      at Object.next (build\compiled\test\functional\connection\connection.js:13:53)
      at C:\Projects\typeorm\build\compiled\test\functional\connection\connection.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\functional\connection\connection.js:3:12)
      at Context.<anonymous> (test\functional\connection\connection.ts:28:16)

  2) Connection
       before connection is established
         "after all" hook:
     TypeError: Cannot read property 'isConnected' of undefined
      at Context.<anonymous> (test\functional\connection\connection.ts:35:28)

  3) ConnectionManager
       create
         should create a mysql connection when mysql driver is specified:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\functional\connection-manager\connection-manager.ts:32:48)

  4) ConnectionManager
       get
         should give connection with a requested name:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\functional\connection-manager\connection-manager.ts:90:48)

  5) ConnectionManager
       get
         should throw an error if connection with the given name was not found:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\functional\connection-manager\connection-manager.ts:101:48)

  6) ConnectionManager
       create connection options
         should not drop the database if dropSchema was not specified:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Suite.<anonymous> (test\functional\connection-manager\connection-manager.ts:116:48)
      at step (build\compiled\test\functional\connection-manager\connection-manager.js:41:23)
      at Object.next (build\compiled\test\functional\connection-manager\connection-manager.js:22:53)
      at C:\Projects\typeorm\build\compiled\test\functional\connection-manager\connection-manager.js:16:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\functional\connection-manager\connection-manager.js:12:12)
      at Context.<anonymous> (test\functional\connection-manager\connection-manager.ts:115:76)

  7) ConnectionManager
       create connection options
         should drop the database if dropSchema was set to true (mysql):
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Suite.<anonymous> (test\functional\connection-manager\connection-manager.ts:138:48)
      at step (build\compiled\test\functional\connection-manager\connection-manager.js:41:23)
      at Object.next (build\compiled\test\functional\connection-manager\connection-manager.js:22:53)
      at C:\Projects\typeorm\build\compiled\test\functional\connection-manager\connection-manager.js:16:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\functional\connection-manager\connection-manager.js:12:12)
      at Context.<anonymous> (test\functional\connection-manager\connection-manager.ts:137:78)

  8) persistence > custom-column-names
       "before all" hook:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\utils\test-utils.ts:279:33)

  9) persistence > custom-column-names
       "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test\functional\persistence\custom-column-names\persistence-custom-column-names.ts:19:28)

  10) github issues > #1656 Wrong repository order with multiple TransactionRepository inside a Transaction decorator
       should set TransactionRepository arguments in order:
     ConnectionNotFoundError: Connection "mysql" was not found.
      at new ConnectionNotFoundError (src\error\ConnectionNotFoundError.ts:8:9)
      at ConnectionManager.get (src\connection\ConnectionManager.ts:40:19)
      at Object.getConnection (src\index.ts:241:35)
      at Controller.descriptor.value [as t] (src\decorator\transaction\Transaction.ts:98:24)
      at Object.<anonymous> (test\github-issues\1656\issue-1656.ts:22:50)
      at step (build\compiled\test\github-issues\1656\issue-1656.js:32:23)
      at Object.next (build\compiled\test\github-issues\1656\issue-1656.js:13:53)
      at C:\Projects\typeorm\build\compiled\test\github-issues\1656\issue-1656.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\github-issues\1656\issue-1656.js:3:12)
      at C:\Projects\typeorm\test\github-issues\1656\issue-1656.ts:21:113
      at Array.map (<anonymous>)
      at Context.<anonymous> (test\github-issues\1656\issue-1656.ts:21:93)
      at <anonymous>

  11) one-to-one
       "before all" hook:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\integration\sample2-one-to-one.ts:24:45)
      at step (build\compiled\test\integration\sample2-one-to-one.js:32:23)
      at Object.next (build\compiled\test\integration\sample2-one-to-one.js:13:53)
      at C:\Projects\typeorm\build\compiled\test\integration\sample2-one-to-one.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\integration\sample2-one-to-one.js:3:12)
      at Context.<anonymous> (build\compiled\test\integration\sample2-one-to-one.js:56:16)

  12) one-to-one
       "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test\integration\sample2-one-to-one.ts:29:28)

  13) many-to-one
       "before all" hook:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\integration\sample3-many-to-one.ts:24:45)
      at step (build\compiled\test\integration\sample3-many-to-one.js:32:23)
      at Object.next (build\compiled\test\integration\sample3-many-to-one.js:13:53)
      at C:\Projects\typeorm\build\compiled\test\integration\sample3-many-to-one.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\integration\sample3-many-to-one.js:3:12)
      at Context.<anonymous> (build\compiled\test\integration\sample3-many-to-one.js:56:16)

  14) many-to-one
       "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test\integration\sample3-many-to-one.ts:29:28)

  15) many-to-many
       "before all" hook:
     Error: Unable to run tests because connection options for "mysql" are not set.
      at Object.setupSingleTestingConnection (test\utils\test-utils.ts:144:15)
      at Context.<anonymous> (test\integration\sample4-many-to-many.ts:22:45)
      at step (build\compiled\test\integration\sample4-many-to-many.js:32:23)
      at Object.next (build\compiled\test\integration\sample4-many-to-many.js:13:53)
      at C:\Projects\typeorm\build\compiled\test\integration\sample4-many-to-many.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build\compiled\test\integration\sample4-many-to-many.js:3:12)
      at Context.<anonymous> (build\compiled\test\integration\sample4-many-to-many.js:54:16)

  16) many-to-many
       "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test\integration\sample4-many-to-many.ts:27:28)

```

Would be nice if these tests wouldn't rely on mysql explicitly or would be ignored if I don't have mysql configured.

**Comment by imnotjames** [comment]
Currently we should be all set here.  Dev deps have been included & I often run tests without a specific server running for a disabled driver.
