### ISSUE TITLE
SelectQueryBuilder with joins and IFNULL inside orderBy

### ISSUE THREAD

**Issue by Slessi** [typeorm/typeorm#2817]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql` 

**TypeORM version:**

[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

```ts
const query = dbConn
    .getRepository(ChangeRequest)
    .createQueryBuilder("cr")
    .innerJoinAndSelect("cr.requester", "req")
    .leftJoinAndSelect("cr.approver", "app")
    .leftJoinAndSelect("cr.rejecter", "rej")
    .where("cr.requestedBy = :id", { id })
    .orderBy("IFNULL(cr.approvedOn, IFNULL(cr.rejectedOn, cr.requestedOn))", "DESC")
    .take(6);

console.log(query.getSql());

const activity = await query.getMany();
```

Logs the following (which works when executed manually):

```sql
SELECT
    -- fieldList (omitted)
FROM
    `change_requests` `cr`
    -- joinList (omitted)
WHERE
    `cr`.`requested_by` = ?
ORDER BY
    IFNULL(
        `cr`.`approved_on`,
        IFNULL(`cr`.`rejected_on`, `cr`.`requested_on`)
    ) DESC

-- LIMIT not present for some reason? Appears if I remove joins
```

However, when `query.getMany()` runs, I receive the following:

```
Error: "IFNULL(cr" alias was not found. Maybe you forgot to join it?
    at QueryExpressionMap.findAliasByName (/<proj_dir>/node_modules/typeorm/query-builder/QueryExpressionMap.js:215:19)
    at /<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1459:49
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1456:14)
    at SelectQueryBuilder.<anonymous> (/<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1367:35)
    at step (/<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next (/<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
    at /<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/<proj_dir>/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
```

If I remove the joins or the `take`, the error goes away.

**Comment by victorschinaider** [comment]
Same problem with `SQL SERVER` here.

**Comment by havenchyk** [comment]
@victorschinaider do you use 0.2.9 version?

**Comment by victorschinaider** [comment]
Yes, i'm using the latest version (0.2.9)

**Comment by mateusgabriel3** [comment]
Same issue here.

**Comment by vlapo** [comment]
Did y try change `cr` into `"cr"`?

**Comment by Slessi** [comment]
@vlapo not sure what you mean?

**Comment by vlapo** [comment]
Sry. I mean add `"` (double quote) Sometimes I have some weird issues like this.

```ts
const query = dbConn
    .getRepository(ChangeRequest)
    .createQueryBuilder('cr')
    .innerJoinAndSelect('"cr"."requester"', 'req')
    .leftJoinAndSelect('"cr"."approver"', 'app')
    .leftJoinAndSelect('"cr"."rejecter"', 'rej')
    .where('"cr"."requestedBy" = :id', { id })
    .orderBy('IFNULL("cr".approvedOn, IFNULL("cr"."rejectedOn", "cr"."requestedOn"))', 'DESC')
    .take(6);

console.log(query.getSql());

const activity = await query.getMany();
```

**Comment by Slessi** [comment]
@vlapo unsurprisingly, it made no difference

```
// This one is because createQueryBuilder('cr') has to be createQueryBuilder('"cr"')
error: ""cr"" alias was not found. Maybe you forgot to join it?

// This one is because "cr"."requester" has to be "cr".requester
error: Relation with property path "requester" in entity was not found.

// And this one is the original error, still not resolved
error: "IFNULL("cr"" alias was not found. Maybe you forgot to join it?
```

**Comment by B0ER** [comment]
same issue

**Comment by LahmerIlyas** [comment]
Same issue

**Comment by djabif** [comment]
Hey @Slessi, did you solve this?

**Comment by Slessi** [comment]
yea, i stopped using typeORM

**Comment by djabif** [comment]
😂

> yea, i stopped using typeORM

**Comment by Ska1er** [comment]
same issue, any updates?
