### ISSUE TITLE
[CLI] Please do not immobilize the ormconfig location

### ISSUE THREAD

**Issue by jnst** [typeorm/typeorm#2876]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Problem:**

```typescript
new ConnectionOptionsReader({ root: process.cwd(), configName: argv.config });
```

* https://github.com/typeorm/typeorm/blob/master/src/commands/MigrationRunCommand.ts#L38

I want to specify `root` option. Because I want to load a different configuration file for each environment.

```
config
└── typeorm
    ├── development.yml
    ├── production.yml
    ├── staging.yml
    └── test.yml
```

Allow to specify the full path of config file by `--config` option, or add `--configRoot` option.

```typescript
const path = require('path');
const configPath = argv.config;   // e.g. 'config/typeorm/development.yml'
new ConnectionOptionsReader({ root: `${process.cwd()}/${path.dirname(configPath)}`, configName: path.basename(configPath) });
```
or
```typescript
new ConnectionOptionsReader({ root: `${process.cwd()}/${argv.configRoot}`, configName: argv.config });
```

**Comment by jnst** [comment]
@ssalka 
Thanks for response. It not works in my environment.

```
$ node_modules/.bin/typeorm -v
0.2.7
```

```
.
├── config
│   └── typeorm
│       ├── development.js
│       ├── production.js
│       ├── staging.js
│       └── test.js
├── package.json
├── src
└── yarn.lock
```

Unless there is ormconfig in the root directory of the project, an error will occur.

```
$ node_modules/.bin/typeorm migration:run --config config/typeorm/test.js
Error during migration run:
Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/Users/jnst/go/src/github.com/Translimit/park-server/node_modules/typeorm/connection/ConnectionOptionsReader.js:68:35)
    at step (/Users/jnst/go/src/github.com/Translimit/park-server/node_modules/typeorm/connection/ConnectionOptionsReader.js:32:23)
    at Object.next (/Users/jnst/go/src/github.com/Translimit/park-server/node_modules/typeorm/connection/ConnectionOptionsReader.js:13:53)
    at fulfilled (/Users/jnst/go/src/github.com/Translimit/park-server/node_modules/typeorm/connection/ConnectionOptionsReader.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

**Comment by jnst** [comment]
test.js

```javascript
module.exports = [{
  name: 'default',
  type: 'mysql',
  host: '127.0.0.1',
  port: 3306,
  username: 'root',
  password: 'root',
  database: 'test',
  synchronize: false,
  logging: true,
  entities: ['src/**/*.entity.ts'],
  migrations: ['src/migrations/**/*.ts'],
  cli: {
    migrationsDir: 'src/migrations',
  },
}];
```

**Comment by ssalka** [comment]
Try omitting `.js` from the path provided to `--config`. It seems that the `ConnectionOptionsReader` [assumes](https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L84) that only a file name (_not_ including file extension) will be passed. Was only able to determine this from inspecting the source code.

**Comment by jnst** [comment]
Ahh! Is that so! 😓
It worked properly. Thank you very much.
