### ISSUE TITLE
Migrations run error

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#288]
I tried run migration and got this
```
TypeError: optionsArray.filter is not a function
    at ConnectionManager.<anonymous> (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:308:55)
    at step (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:32:23)
    at Object.next (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:13:53)
    at C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:7:71
    at __awaiter (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:3:12)
    at ConnectionManager.createFromConfigAndConnect (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:302:16)
    at ConnectionManager.<anonymous> (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:147:48)
    at step (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:32:23)
    at Object.next (C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:13:53)
    at C:\Users\Ivan\AppData\Roaming\npm\node_modules\typeorm\connection\ConnectionManager.js:7:71
(node:4724) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: optionsArray.filter is not a function
```
migration code:
```typescript
public async up(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {

        {
            const idColumn = new ColumnSchema("id");
            idColumn.type = "int";
            idColumn.isGenerated = true;
            idColumn.isPrimary = true;

            const emailColumn = new ColumnSchema("email");
            emailColumn.type = "string";
            emailColumn.isUnique = true;

            const passwordColumn = new ColumnSchema("password");
            passwordColumn.type = "string";

            const firstNameColumn = new ColumnSchema("first_name");
            firstNameColumn.type = "string";

            const lastNameColumn = new ColumnSchema("last_name");
            lastNameColumn.type = "string";

            const patronymicColumn = new ColumnSchema("patronymic");
            patronymicColumn.type = "string";

            const birthdayColumn = new ColumnSchema("birthday");
            birthdayColumn.type = "datetime";
            birthdayColumn.isNullable = true;
            birthdayColumn.default = null;

            const phone1Column = new ColumnSchema("phone1");
            phone1Column.type = "string";

            const phone2Column = new ColumnSchema("phone2");
            phone2Column.type = "string";

            const blockedColumn = new ColumnSchema("blocked");
            blockedColumn.type = "datetime";
            blockedColumn.isNullable = true;
            blockedColumn.default = null;

            const roleColumn = new ColumnSchema("role");
            roleColumn.type = "smallint";
            roleColumn.default = ROLE_GUEST;

            const statusColumn = new ColumnSchema("status");
            statusColumn.type = "smallint";
            statusColumn.default = STATUS_NEW;

            const commentColumn = new ColumnSchema("comment");
            commentColumn.type = "text";
            commentColumn.isNullable = true;
            commentColumn.default = null;

            const userSchema = new TableSchema("user");
            userSchema.addColumns([
                idColumn,
                emailColumn,
                passwordColumn,
                firstNameColumn,
                lastNameColumn,
                patronymicColumn,
                birthdayColumn,
                phone1Column,
                phone2Column,
                blockedColumn,
                roleColumn,
                statusColumn,
                commentColumn
            ]);

            await queryRunner.createTable(userSchema);
        }
        {
            const tokenColumn = new ColumnSchema("token");
            tokenColumn.type = "string";
            tokenColumn.isUnique = true;

            const userColumn = new ColumnSchema("user");
            userColumn.type = "int";

            const tokenSchema = new TableSchema("token");
            tokenSchema.addColumns([
                tokenColumn,
                userColumn
            ]);

            await queryRunner.createTable(tokenSchema);
        }
    };
```

I use PostgreSQL

**Comment by pleerock** [comment]
right now migrations work better if you use raw sql. You can create table the way you did, and its actually better then writing raw sql, however this api wasn't designed to be user-friendly because its used mostly internally. Try to debug whats your issue and if you arent succeed use raw sql for now, until I implement a better interface for users to create migration queries

**Comment by Spoki4** [comment]
Okay, thanks you for answer.
