### ISSUE TITLE
CLI migrations run errors

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#297]
When I start migrations from CLI, I got this:
```
(function (exports, require, module, __filename, __dirname) { import {Connection, EntityManager, MigrationInterface, QueryRunner, ColumnSchema, TableSchema} from "typeorm";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.PlatformTools.load (C:\Users\Asia\AppData\Roaming\npm\node_modules\typeorm\platform\PlatformTools.js:25:20)
    at C:\Users\Asia\AppData\Roaming\npm\node_modules\typeorm\util\DirectoryExportedClassesLoader.js:28:69
(node:8460) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token import
```
How can I run migrations with TypeScript transpiler from CLI?

**Comment by pleerock** [comment]
I think you have wrong tsconfig configuration. Try to set `"module": "commonjs",` in there

**Comment by Spoki4** [comment]
my tsconfig:
```json
{
  "compilerOptions": {
    "outDir": "./build/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es6",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "lib": ["es6", "dom", "es2015", "es2015.promise"],
    "allowJs": true,
    "typeRoots" : ["typings"]
  },
  "include": [
    "./src/**/*",
    "./tests/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```
and ormconfig:
```json
[
  {
    "name": "default",
    "driver": {
      "type": "mysql",
      "host": "localhost",
      "port": 3306,
      "username": "palport",
      "password": "123123",
      "database": "palport"
    },
    "cli": {
      "entitiesDir": "./src/server/database/entities",
      "migrationsDir": "./src/server/database/migrations"
    }
  }
]
```

**Comment by pleerock** [comment]
can you provide a git repo which I can clone and reproduce your issue?

**Comment by Spoki4** [comment]
[git repo for yours tests](https://github.com/Spoki4/simple-for-typeorm-error)

**Comment by pleerock** [comment]
You have your issue because you are running typeorm not under ts-node and typeorm tries to load ts files instead of js which are missing in specified directories. Solution is to run typeorm via ts-node like this:

```ts-node node_modules/.bin/typeorm migrations:run```

**Comment by KhramtsovMaksim** [comment]
Hello @pleerock ,

then I run `ts-node node_modules/.bin/typeorm schema:sync`
get error 
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```
I think ts-node parse .bin/typeorm file and throw error.
How can we avoid this problem? For example provide you test project.
Could you please look at [my test project](https://github.com/KhraksMamtsov/bKooker).
Many thanks!

**Comment by pleerock** [comment]
@KhramtsovMaksim are you on windows? Try to install and use typeorm globally then
