### ISSUE TITLE
addColumn in migration does not work as expected

### ISSUE THREAD

**Issue by WimWidgets** [typeorm/typeorm#2980]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8`

I have a migration to add a new column to an existing table (with data in it) using the following code:
```ts
async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.addColumn('myTable', new TableColumn({
        name: 'my_new_column_name',
        type: 'varchar',
        isNullable: true
    });
}
```
My expectation was that this code would be transformed to an `ALTER TABLE` query in the background. When logging all database activity, I saw it actually tried to create a temporary table and drop the actual table. This seems weird to me and it also gave me an error because there was already a foreign key constraint on another column in this table. So the migration didn't work. I fixed it by manually putting in an `ALTER TABLE` query, but shouldn't `addColumn` already do that?

**Comment by lili21** [comment]
@WimWidgets How did you fix it ?

**Comment by WimWidgets** [comment]
@lili21 As I said in the last line: _I fixed it by manually putting in an `ALTER TABLE` query, [...]_

So not a real structural fix, but at least I got it working.
```typescript
await queryRunner.query(`ALTER TABLE "myTable" ADD COLUMN "my_new_column_name" VARCHAR(255) DEFAULT NULL`);
```

**Comment by colthreepv** [comment]
I share your concern that this is a weird approach.
Since my table has also foreign keys, **it could not be dropped.**  
I was not able to write a working migration until I went your way and written an `ALTER TABLE` construct

**Comment by gruckion** [comment]
No update on this issue since May?

**Comment by snolangps** [comment]
I am still getting this error

```
query failed: ALTER TABLE `someTable` ADD `Status` enum NOT NULL
error: { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL' at line 1
    at Query.Sequence._packetToError (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    --------------------
    at Protocol._enqueue (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/some/site/node_modules/.pnpm/registry.npmjs.org/mysql/2.17.1/node_modules/mysql/lib/Connection.js:201:25)
    at MysqlQueryRunner.<anonymous> (/some/site/node_modules/.pnpm/registry.npmjs.org/typeorm/0.2.20/src/driver/mysql/MysqlQueryRunner.ts:156:36)
    at step (/some/site/node_modules/.pnpm/registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:136:27)
    at Object.next (/some/site/node_modules/.pnpm/registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/some/site/node_modules/.pnpm/registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'NOT NULL\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'ALTER TABLE `someTable` ADD `Status` enum NOT NULL' }
```

**Comment by andrewdhazlett** [comment]
I was able to fix a similar issue (on postgres) by wrapping my default value in single quotes: 
![image](https://user-images.githubusercontent.com/2836999/73193905-ef56e700-40f0-11ea-9b47-1a1452245f30.png)

Previously I was getting the error `column "open" does not exist`:
![image](https://user-images.githubusercontent.com/2836999/73193995-12819680-40f1-11ea-9228-fc4711e155fd.png)

This is downright baffling behavior.
