### ISSUE TITLE
Can't run with ts-node

### ISSUE THREAD

**Issue by rico345100** [typeorm/typeorm#2981]
**Issue type:**

[ ] question
[o] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[o] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[o] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is my index.ts:

```ts
import "reflect-metadata";
import * as Koa from 'koa';
// @ts-ignore
import * as logger from 'koa-log';
import * as bodyParser from 'koa-bodyparser';

...
```

However when I run this:

```
$ npx ts-node src/index.ts
```

It fails with this error message:

> /Users/rico345100/Desktop/development/simple-memo-application/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { import "reflect-metadata";
                                                                     ^^^^^^^^^^^^^^^^^^

Versions I used are:
- Node.js@8.9.2 and @11.0.0 -> Just updated to latest stable build, but doesn't work either
- ts-node@3.3.0
- sqlite3@4.0.2
- typescript@3.1.3
- typeorm@0.2.8

Funny thing is I have another MacOS laptop in my office, and that works, however MacOS in my home doesn't.

Here's the package.json I have:

```json
{
  "name": "simple-memo-application",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "ts-node src/index.ts",
    "start:client": "webpack-dev-server --mode development --open --progress --inline"
  },
  "keywords": [
    "memo",
    "sqlite",
    "typeorm",
    "koa",
    "rxjs",
    "web components"
  ],
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/rico345100/simple-memo-application"
  },
  "dependencies": {
    "@types/koa-router": "^7.0.32",
    "@types/node": "^8.0.29",
    "apollo-server-koa": "^2.1.0",
    "graphql": "^14.0.2",
    "koa": "^2.5.3",
    "koa-bodyparser": "^4.2.1",
    "koa-log": "^2.1.0",
    "koa-router": "^7.4.0",
    "reflect-metadata": "^0.1.12",
    "sqlite3": "^4.0.2",
    "ts-node": "3.3.0",
    "typeorm": "^0.2.8",
    "typescript": "^3.1.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-typescript": "^7.1.0",
    "apollo-boost": "^0.1.16",
    "apollo-client": "^2.4.3",
    "babel-loader": "^8.0.4",
    "clean-webpack-plugin": "^0.1.19",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.1.0",
    "mini-css-extract-plugin": "^0.4.0",
    "raw-loader": "^0.5.1",
    "rxjs": "^6.3.3",
    "ts-loader": "^5.2.2",
    "url-loader": "^1.1.2",
    "webpack": "^4.4.1",
    "webpack-bundle-analyzer": "^3.0.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.1"
  }
}

```

Or you can just run this project from this repo: [https://github.com/rico345100/simple-memo-application](https://github.com/rico345100/simple-memo-application)

**Comment by timothyvanderaerden** [comment]
This is not an issue with TypeORM. But I'm going answer so this can be closed. Looking at your project you should change the following in `tsconfig.json`.

```json
"module": "es6",
```
to:
```json
"module": "commonjs",
```

**Comment by rico345100** [comment]
Thanks to reply. So I just changed module to "commonjs", however now I have these bunch of error messages:

```bash
rico345100ui-MacBook-Pro:simple-memo-application rico345100$ npx ts-node src/index.ts 
/Users/rico345100/Desktop/development/simple-memo-application/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { import "reflect-metadata";
                                                                     ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module.m._compile (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
rico345100ui-MacBook-Pro:simple-memo-application rico345100$ npm install typeorm -g
/usr/local/bin/typeorm -> /usr/local/lib/node_modules/typeorm/cli.js
+ typeorm@0.2.8
added 106 packages from 378 contributors in 4.916s
rico345100ui-MacBook-Pro:simple-memo-application rico345100$ npx ts-node src/index.ts 
/Users/rico345100/Desktop/development/simple-memo-application/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { import "reflect-metadata";
                                                                     ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module.m._compile (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/ts-node/src/index.ts:395:12)
rico345100ui-MacBook-Pro:simple-memo-application rico345100$ npx ts-node src/index.ts 
Apollo Server with Koa is running on port 3000...
GraphQL Path: /graphql
(node:16476) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Users/rico345100/Desktop/development/simple-memo-application/src/error/DriverPackageNotInstalledError.ts:8:9)
    at SqliteDriver.loadDependencies (/Users/rico345100/Desktop/development/simple-memo-application/src/driver/sqlite/SqliteDriver.ts:120:19)
    at new SqliteDriver (/Users/rico345100/Desktop/development/simple-memo-application/src/driver/sqlite/SqliteDriver.ts:46:14)
    at DriverFactory.create (/Users/rico345100/Desktop/development/simple-memo-application/src/driver/DriverFactory.ts:34:24)
    at new Connection (/Users/rico345100/Desktop/development/simple-memo-application/src/connection/Connection.ts:122:43)
    at ConnectionManager.create (/Users/rico345100/Desktop/development/simple-memo-application/src/connection/ConnectionManager.ts:64:28)
    at Object.<anonymous> (/Users/rico345100/Desktop/development/simple-memo-application/src/index.ts:219:35)
    at step (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/typeorm/index.js:32:23)
    at Object.next (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/typeorm/index.js:13:53)
    at fulfilled (/Users/rico345100/Desktop/development/simple-memo-application/node_modules/typeorm/index.js:4:58)
(node:16476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by havenchyk** [comment]
@rico345100 you're doing something wrong. I just cloned your project and changed the `module` value to `commonjs`. An app is able to start. With `module` in `es6` you have to push node.js to understand `import/export` syntax.

**Comment by rico345100** [comment]
Seems like there's something wrong in old NPM. I just cloned my repo and try npm install but it fails, so I updated NPM to latest version and now it works.

Thank you.
