### ISSUE TITLE
Cannot read property 'constructor' of undefined if use getCustomRepository inside other CustomRepository

### ISSUE THREAD

**Issue by valeriy-devpronet** [typeorm/typeorm#301]
```typescript
import { User, UserRole, UserStatus } from './../';
import { UserProfileRepository } from './../repositories';

@EntityRepository(User)
export class UserRepository extends Repository<User>
{
  async updateProfile(userId: number, data: any)
  {
    const user = await this.createQueryBuilder('user')
      .leftJoinAndSelect('user.profile', 'profile')
      .where('user.id = :userId', { userId })
      .getOne();

    if (!isUndefined(data.profile)) {
      user.profile = await this.connection
        .getCustomRepository(UserProfileRepository)
        .updateProfile(user, data);
    }

    return await this.setProfileToUser(user);
  }
}
```

```typescript
import { Repository, EntityRepository } from 'typeorm';
import { User, UserProfile, Education, ChildrenInHome } from './../';
import { Gender, MaritalStatus, AnnualIncome, Ethnicity, EmploymentStatus } from './../';
import { isUndefined } from 'lodash';

@EntityRepository(UserProfile)
export class UserProfileRepository extends Repository<UserProfile>
{
  async updateProfile(user: User, data): Promise<UserProfile>
  {
    // some code here
  }
}
```

All this code produces the error
```
TypeError: Cannot read property 'constructor' of undefined
    at /work/nodejs/koajs/node_modules/typeorm/connection/Connection.js:450:117
    at Array.find (native)
    at Connection.getCustomRepository (/work/nodejs/koajs/node_modules/typeorm/connection/Connection.js:449:106)
    at EntityManager.BaseEntityManager.getCustomRepository (/work/nodejs/koajs/node_modules/typeorm/entity-manager/BaseEntityManager.js:108:32)
```

If call UserProfileRepository outside UserRepository than it works as expected.

Thanks.

**Comment by pleerock** [comment]
it should work until there are some circular reference issues there. Does it it work if you call it outside of another entity repository? Also try to replace this code:

```typescript
    if (!isUndefined(data.profile)) {
      user.profile = await this.connection
        .getCustomRepository(UserProfileRepository)
        .updateProfile(user, data);
    }
```

with: 

```typescript
    if (!isUndefined(data.profile)) {
      user.profile = new UserProfile();
      console.log(user.profile); // check if this will output
      user.profile = await this.connection
        .getCustomRepository(UserProfileRepository)
        .updateProfile(user, data); // and check if this will fail but output is okay
    }
```

**Comment by valeriy-devpronet** [comment]
Thanks for your reply. After your reply I've accidentally done next:

```typescript
import { User, UserRole, UserStatus } from './../';
import { UserProfileRepository } from './../repositories/UserProfileRepository'; // <-this fixed an issue

@EntityRepository(User)
export class UserRepository extends Repository<User>
{
  async updateProfile(userId: number, data: any)
  {
    const user = await this.createQueryBuilder('user')
      .leftJoinAndSelect('user.profile', 'profile')
      .where('user.id = :userId', { userId })
      .getOne();

    if (!isUndefined(data.profile)) {
      user.profile = await this.connection
        .getCustomRepository(UserProfileRepository)
        .updateProfile(user, data);
    }

    return await this.setProfileToUser(user);
  }
}
```
and this fixed an issue... 
Inside directory `repositories` I have `index.ts` which looks like

```typescript
export * from './UserRepository';
export * from './UserProfileRepository';
```
and If I do

```
import { UserProfileRepository } from './UserProfileRepository';
//  or 
import { UserProfileRepository } from './../repositories/UserProfileRepository';
```

everything works as expected but with

```
import { UserProfileRepository } from './';
// or
import { UserProfileRepository } from './../repositories';
```

it does not and produces an error which I've described. If this my fault, then I'll close the issue.

Thanks

**Comment by pleerock** [comment]
you reopened this issue, so what is resolution here?

**Comment by valeriy-devpronet** [comment]
Sorry my bad. Issue with importing from my side. As I said if I'm doing explicitly call of repository than it works. I doubt that this is issue with TypeOrm. 

Thanks
