### ISSUE TITLE
ManyToOne column can not be added to entity

### ISSUE THREAD

**Issue by huaying** [typeorm/typeorm#3045]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I tried to add a ManyToOne column `selectedChannel` to entity `User`, but it keeps showing this error.

```
[Node] file:///Users/huaying/Project/slashs/dist/entity/user.js:45
[Node]         __metadata("design:type", Channel)
[Node] 
[Node] ReferenceError: Channel is not defined
[Node]     at file:///Users/huaying/Project/slashs/dist/entity/user.js:45:41
[Node]     at Object.<anonymous> (file:///Users/huaying/Project/slashs/dist/entity/user.js:51:2)
[Node]     at Generator.next (<anonymous>)
```

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  BaseEntity,
  ManyToMany,
  JoinTable,
  ManyToOne
} from 'typeorm';
import { Channel } from './channel';

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  username: string;

  @ManyToMany(type => Channel, channel => channel.members)
  @JoinTable()
  channels: Channel[];

  @ManyToOne(type => Channel)
  selectedChannel: Channel;
}
```

It works if I change to: 
```ts
 @ManyToOne(type => Channel)
  selectedChannel: number;
```
It's not an official way though.

The genereated js is below:

```js
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    }
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, ManyToMany, JoinTable, ManyToOne } from 'typeorm';
import { Channel } from './channel';
var User = /** @class */ (function (_super) {
    __extends(User, _super);
    function User() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    __decorate([
        PrimaryGeneratedColumn(),
        __metadata("design:type", Number)
    ], User.prototype, "id", void 0);
    __decorate([
        Column(),
        __metadata("design:type", String)
    ], User.prototype, "username", void 0);
    __decorate([
        ManyToMany(function (type) { return Channel; }, function (channel) { return channel.members; }),
        JoinTable(),
        __metadata("design:type", Array)
    ], User.prototype, "channels", void 0);
    __decorate([
        ManyToOne(function (type) { return Channel; }),
        __metadata("design:type", Channel)   // <--- It seems the problem happened here.
    ], User.prototype, "selectedChannel", void 0);
    User = __decorate([
        Entity()
    ], User);
    return User;
}(BaseEntity));
export { User };
//# sourceMappingURL=user.js.map
```

**Comment by havenchyk** [comment]
Did you check docs? https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md

```
 @ManyToMany(type => Channel, channel => channel.members)
  @JoinTable()
  channels: Channel[];
```

Seems to be wrong in terms of relations in db.

Also, do you have OneToMany specified in your `Channel` entity?

**Comment by btxtiger** [comment]
I guess it should be `@ManyToMany` on both sides
```ts
@Entity()
export class Channel 
{
    @ManyToMany(type => Member, member => member.channels)
    @JoinColumn()
    members: Member[];
}
```

```ts
@Entity()
export class Member // (or User) 
{
    @ManyToMany(type => Channel, channel => channel.members)
    channels: Channel[];
}
```

**Comment by huaying** [comment]
The error seems to happen in `selectedChannel` which is `ManyToOne`

The Channel entity is like 
```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  BaseEntity,
  Column,
  ManyToMany,
  OneToMany
} from 'typeorm';
import { User } from './user';
import { Message } from './message';

@Entity()
export class Channel extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(type => Message, message => message.channel)
  messages: Message[];

  @ManyToMany(type => User, user => user.channels)
  members: User[];
}
```

**Comment by imnotjames** [comment]
Could be you're having trouble with circular imports.  However, that's unrelated to TypeORM directly.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
