### ISSUE TITLE
Broken migration mechanism

### ISSUE THREAD

**Issue by NiKlimenko** [typeorm/typeorm#3093]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since the migration mechanism depends on the entity scheme (migrations don't work without specifying the entity path in ormconfig), in some situations we have desynchronization between early migration scripts and the actual entity.

We have the first version of our entity:
```
@Entity('users')
class UsersEntity {
  @Column('text', { unique: true })
  email;
}
```
And first migration:

**Comment by matomesc** [comment]
I have the same issue. The workaround suggested doesn't work for me - fails with the following error:

```
TypeError: this.subQuery is not a function
    at InsertQueryBuilder.QueryBuilder.createFromAlias (/Users/m/dev/projects/ting/server/src/query-builder/QueryBuilder.ts:528:131)
    at InsertQueryBuilder.into (/Users/m/dev/projects/ting/server/src/query-builder/InsertQueryBuilder.ts:144:32)
    at Currency1552915206334.up (/Users/m/dev/projects/ting/server/src/migration/1552915206334-Currency.ts:14:8)
    at /Users/m/dev/projects/ting/server/src/migration/MigrationExecutor.ts:113:44
    at /Users/m/dev/projects/ting/server/src/util/PromiseUtils.ts:34:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I wrote this script to checkout any commits that added migrations and run the migrations. This only works for a migrations that haven't been modified after committed:

```bash
#!/bin/bash

revlist="$(git rev-list --reverse HEAD)"
(
  for rev in $revlist
  do
    files="$(git log -1 --pretty="format:" --name-only $rev)"
    revName="$(git log -1 --pretty="%h %s" $rev)"
    hasMigrations="f"

    for file in $files
    do
      if [[ $file == *"migration"* ]]; then
        if [[ $hasMigrations == "f" ]]; then
          echo $revName
          hasMigrations="t"
        fi
        echo $file
      fi
    done

    if [[ $hasMigrations == "t" ]]; then
      git checkout $rev
      yarn install && typeorm migration:run
    fi
  done
) > migrations_out
```

**Comment by phvictorino** [comment]
i change the path of entities from dynamic:
`import { User } from "../src/entitys/user.entity";`

to static:
`import { User } from "src/entitys/user.entity";`

it worked for me

**Comment by lapanoid** [comment]
@matomesc have the same error as yours. Currently I prebuild ts to js to avoid this.
@phvictorino solution did not helped.

**Comment by rijad992** [comment]
Hello, 
I've used this repository as a reference for setting up migrations config and so far it seems like its doing a job very well.

https://github.com/ambroiseRabier/typeorm-nestjs-migration-example

**Comment by sladg** [comment]
Syntax with `.into()` stopped working for me on the newest version.

```connection.createQueryBuilder().insert().into(Commitee).values(insertions).onConflict(onConflictQuery).execute()```

Returning:
```(node:3664) UnhandledPromiseRejectionWarning: TypeError: this.subQuery is not a function```

**Comment by cris-ech** [comment]
> Syntax with `.into()` stopped working for me on the newest version.
> 
> `connection.createQueryBuilder().insert().into(Commitee).values(insertions).onConflict(onConflictQuery).execute()`
> 
> Returning:
> `(node:3664) UnhandledPromiseRejectionWarning: TypeError: this.subQuery is not a function`
> 
> Using Postgres also.

Same problem here, I start to use into in a function and then the same error occurs.

did you find a solution?

**Comment by dgoemans** [comment]
I ran into this recently, and found this [issue](https://github.com/w3tecch/typeorm-seeding/issues/53). Turns out the problem was exactly that:
```
The error TypeError: this.subQuery is not a function is because typeorm could not find any entities.

Please check your paths in your config file
```

**Comment by hirasaki1985** [comment]
I have same error.

and I tried to write table name directly (table name is user).

```
    await connection
      .createQueryBuilder()
      .insert()
      .into("user")
      .values([
        {
          id: 10,
          email: "test@test.co.jp",
          name: "test user10"
        },
      ])
      .execute();
```

It worked for me.
