### ISSUE TITLE
Error with cascading saves using EntityManager in a transaction

### ISSUE THREAD

**Issue by ajxs** [typeorm/typeorm#3105]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I've encountered this issue attempting to update an entity's one-to-many relations. I'm attempting to create a new collection of relations on the 'many' via the use of a cascade save.
I'd expect the new children to be persisted with the correct parent id, but it seems like the commands are being executed in an incorrect order.
Here's a minimal verifiable example which reproduces the issue.
Is there something I've overlooked here? Let me know if there's more information I can provide.
The issue seems to also be present in `@next`.

```sql
-- Example schema
CREATE TABLE example.test_parent (
	id SERIAL PRIMARY KEY NOT NULL
);


CREATE TABLE example.test_child (
	id SERIAL PRIMARY KEY NOT NULL,
	parent_id INTEGER NOT NULL REFERENCES example.test_parent(id),
	data INTEGER NOT NULL
);

```

```typescript
// Example script.
@Entity("test_parent")
class TestParent {
	@PrimaryGeneratedColumn({
		name: "id",
		type: "int"
	})
	public id:number;

	@OneToMany(type => TestChild, child => child.parent, {
		eager: true,
		cascade: true
	})
	public children:TestChild[];

}


@Entity("test_child")
class TestChild {
	@PrimaryGeneratedColumn({
		name: "id",
		type: "int"
	})
	public id:number;

	@Column({
		name: "parent_id",
		type: "int"
	})
	public parentId:number;

	@ManyToOne(type => TestParent, parent => parent.children)
	@JoinColumn({
		name: "parent_id",
		referencedColumnName: "id"
	})
	public parent:TestParent;

	@Column({
		name: "data",
		type: "int"
	})
	public data:number;


	constructor(_data:number) {
		this.data = _data;
	}
}

await getManager().transaction(async (transactionalEntityManager:EntityManager) => {
	const parent = new TestParent();
	parent.children = [new TestChild(1), new TestChild(2)];

	let newParent = await transactionalEntityManager.save(parent);

	newParent.children = [new TestChild(4), new TestChild(5)];
	newParent = await transactionalEntityManager.save(parent);
});
```

Logging output:
```
query: START TRANSACTION
query: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
query: INSERT INTO "example"."test_parent" DEFAULT VALUES RETURNING "id"
query: INSERT INTO "example"."test_child"("parent_id", "data") VALUES ($1, $2), ($3, $4) RETURNING "id" -- PARAMETERS: [3,1,3,2]
query: SELECT "testParent"."id" AS "testParent_id" FROM "example"."test_parent" "testParent" WHERE ("testParent"."id" = $1) -- PARAMETERS: [3]
query: SELECT "test_child"."id" AS "id", "test_child"."parent_id" AS "parent_id" FROM "example"."test_child" "test_child" WHERE (("test_child"."parent_id" = $1)) -- PARAMETERS: [3]
query: INSERT INTO "example"."test_child"("parent_id", "data") VALUES ($1, $2), ($3, $4) RETURNING "id" -- PARAMETERS: [3,4,3,5]
query: UPDATE "example"."test_child" SET "parent_id" = $2 WHERE "id" = $1 -- PARAMETERS: [7,null]
query: UPDATE "example"."test_child" SET "parent_id" = $2 WHERE "id" = $1 -- PARAMETERS: [8,null]
query failed: UPDATE "example"."test_child" SET "parent_id" = $2 WHERE "id" = $1 -- PARAMETERS: [7,null]
error: { error: null value in column "parent_id" violates not-null constraint
    at Connection.parseE (/home/ajxs/otest/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/ajxs/otest/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/ajxs/otest/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
  name: 'error',
  length: 192,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (7, null, 1).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'example',
  table: 'test_child',
  column: 'parent_id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '2008',
  routine: 'ExecConstraints' }
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ajxs** [comment]
Does anyone have any insight here? It would be great if we were able to use this feature as intended.

**Comment by dhritzkiv** [comment]
Possibly related to #2758.

I am experiencing the same when saving a relation's parent (which has references to the relation) while inside of a transaction.

**Comment by havenchyk** [comment]
@ajxs you can just create a PR with the failing test like this https://github.com/typeorm/typeorm/pull/3247

**Comment by mcrawshaw** [comment]
Same for me.  Rather than being in the wrong order, I think the last 2 UPDATE statements are superfluous:
```sql
INSERT INTO "example"."test_child"("parent_id", "data") VALUES ($1, $2), ($3, $4) RETURNING "id" -- PARAMETERS: [3,4,3,5]
UPDATE "example"."test_child" SET "parent_id" = $2 WHERE "id" = $1 -- PARAMETERS: [7,null]
UPDATE "example"."test_child" SET "parent_id" = $2 WHERE "id" = $1 -- PARAMETERS: [8,null]```

**Comment by ajxs** [comment]
@havenchyk My apologies for being slow with creating the PR. I'll get that done ASAP.
@mcrawshaw This is bad practice, making the `parent_id` FKEY nullable removes the constraints that enforce referential integrity. A well formed database schema should never have a NULL functional dependency. Not everyone would have that kind of control over the database schema either.

**Comment by pleerock** [comment]
The default behaviour shouldn't be to deleting the records :) Relation is just attaching one object to another. In some business cases in your app you want your children to be removed in some not.

In your case I guess you need to set `onDelete: "CASCADE"` in your relation options.

**Comment by ajxs** [comment]
I can see your point that I am making a big assumption in expecting the ORM to understand my intentions in deleting those relations, but I'm sure you can see why I would make this assumption.
If I am removing the parent->child relation in a one-to-many relation with a `NOT NULL` constraint I'm not sure what other behaviour could possibly be implied. Deleting the child entities is the only option.

**Comment by pleerock** [comment]
@ajxs I understood your concern, but having this behaviour by default can bring lot of questions for people who won't expect such behaviour. And I'm sure there will be lot of people who won't expect it - regular save to remove their database rows. Solution as I pointed above is to explicitly set what you want to do with a row when referenced row is removed.

**Comment by ajxs** [comment]
The big issue I have with this behaviour is that it violates the concept of how *persistence* in DDD using repositories ideally works.
The ideal scenario is that all business logic is performed on the entities themselves via their own methods, and *then* the repository methods are only used to handle the entity persistence.
The constraint you're proposing prevents using this kind of behaviour, I agree that this behaviour may one day catch someone unwary and have bad results, but I still maintain that this is a very reasonable and common scenario.
Your proposal of `onDelete: "CASCADE"` does not resolve the issue either.
How else would you propose we accomplish this business case? We've gotten around this limitation by using repository methods to delete and add the child entities manually, but this is not ideal.

**Comment by pleerock** [comment]
> the concept of how persistence in DDD using repositories ideally works.

DDD doesn't describe ideal way of persistence using repositories. I understand it is ideal way in your use case. I suggest to manually remove children you need before you do this operation. Right, it's more verbose, but at the same time it's more explicit. In my personal experience any cascade magic lead into different issues across project and your team.

**Comment by alumni** [comment]
Reopening because we have a test that references this issue
