### ISSUE TITLE
MissingPrimaryColumnError in javascript + babel

### ISSUE THREAD

**Issue by kalmndo** [typeorm/typeorm#3116]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

got this error! i'm using javascript + babel

```js
MissingPrimaryColumnError: Entity "User" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
    at new MissingPrimaryColumnError (/home/kalmndo/Project/nuo/src/error/MissingPrimaryColumnError.ts:9:9)
    at EntityMetadataValidator.validate (/home/kalmndo/Project/nuo/src/metadata-builder/EntityMetadataValidator.ts:56:19)
    at /home/kalmndo/Project/nuo/src/metadata-builder/EntityMetadataValidator.ts:44:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/kalmndo/Project/nuo/src/metadata-builder/EntityMetadataValidator.ts:44:25)
    at Connection.buildMetadatas (/home/kalmndo/Project/nuo/src/connection/Connection.ts:494:33)
    at Connection.<anonymous> (/home/kalmndo/Project/nuo/src/connection/Connection.ts:187:18)
    at step (/home/kalmndo/Project/nuo/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/home/kalmndo/Project/nuo/node_modules/typeorm/connection/Connection.js:13:53)
    at fulfilled (/home/kalmndo/Project/nuo/node_modules/typeorm/connection/Connection.js:4:58)

```
here is my entity file
```js
// @flow
import {
  Entity,
  Column,
  PrimaryColumn,
  BeforeInsert,
  BaseEntity,
} from 'typeorm';
import * as uuidv4 from 'uuid/v4';

@Entity('users')
export class User extends BaseEntity {
  @PrimaryColumn('uuid') id: string;

  @Column('varchar', { length: 255 })
  email: string;

  @Column('text') password: string;

  @BeforeInsert()
  addId() {
    this.id = uuidv4();
  }
}
```

and this, in babel.config.js
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    ['@babel/preset-stage-2', { decoratorsLegacy: true }],
    '@babel/preset-flow',
    '@babel/preset-react',
  ],
  plugins: ['transform-class-properties'],
  ignore: ['node_modules', 'build'],
};

```
but i also import the reflect metada

**Comment by kalmndo** [comment]
edit my babel config
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    ['@babel/preset-stage-2', { decoratorsLegacy: true }],
    '@babel/preset-flow',
    '@babel/preset-react',
  ],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
  ],
  ignore: ['node_modules', 'build'],
};

```
