### ISSUE TITLE
EntityMetadataNotFound - EntityManager not able to get metadata from connection

### ISSUE THREAD

**Issue by ambiguities** [typeorm/typeorm#3134]
**Issue type:**

[x] question
[?] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create a new cli by running: ```npx oclif multi mynewcli```
2. Update packages and install:
```json
"dependencies": {
  "@oclif/command": "^1.5.6",
  "@oclif/config": "^1.9.0",
  "@oclif/errors": "^1.2.2",
  "@oclif/plugin-help": "^2.1.4",
  "reflect-metadata": "^0.1.12",
  "sqlite3": "^4.0.4",
  "tslib": "^1.9.3",
  "typeorm": "^0.2.9"
},
"devDependencies": {
  "@oclif/dev-cli": "^1.19.4",
  "@oclif/tslint": "^3.1.1",
  "@types/node": "^10.12.9",
  "ts-node": "^7.0.1",
  "tslint": "^5.11.0",
  "typescript": "^3.1.6"
},
```
3. update bin/run to: 
```js
#!/usr/bin/env node

require('../lib')
```
4. Update src/index.ts to:
```ts
import "reflect-metadata"

import {ConnectionOptions, createConnection, getConnection} from 'typeorm'

import {User} from './entity/user'

const config: ConnectionOptions = {
  type: 'sqlite',
  name: 'default',
  database: 'db.sqlite3',
  entities: [
    User
  ],
  synchronize: true
}

export default (async function() {
  createConnection(config).then(async (): Promise<void> => {

    const conn = await getConnection()
    const repo = await conn.manager.find(User)
    console.log(repo)

    require('@oclif/command').run()
      .then(require('@oclif/command/flush'))
      .catch(require('@oclif/errors/handle'))
  })
})()
``` 
5. Add a simple test entity to src/entity/
```ts
import {BaseEntity, Column, Entity, PrimaryColumn} from 'typeorm'

@Entity()
export class User extends BaseEntity {
  @PrimaryColumn({
    type: 'int',
    nullable: false
  })
  id!: number

  @Column({
    type: 'text',
    nullable: false
  })
  name!: string
}
```
6. Update the default src/commands/hello.ts command to:
```ts
import {Command} from '@oclif/command'
import {getConnection} from 'typeorm'
import {User} from '../entity/user'

export default class Hello extends Command {
  async run() {
    const conn = await getConnection()
    const repo = await conn.manager.find(User)
    console.log(repo)
  }
}
```
7. build the CLI either by running ```npm run prepack`` or using ```tsc --watch```
8. run the command ```node bin/run```

**Result:**
```text
EntityMetadataNotFound: No metadata for "User" was found.
    at new EntityMetadataNotFoundError (/tmp/broken-demo/src/error/EntityMetadataNotFoundError.ts:9:9)
    at Connection.getMetadata (/tmp/broken-demo/src/connection/Connection.ts:314:19)
    at EntityManager.<anonymous> (/tmp/broken-demo/src/entity-manager/EntityManager.ts:493:42)
    at step (/tmp/broken-demo/node_modules/typeorm/entity-manager/EntityManager.js:32:23)
    at Object.next (/tmp/broken-demo/node_modules/typeorm/entity-manager/EntityManager.js:13:53)
    at /tmp/broken-demo/node_modules/typeorm/entity-manager/EntityManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/broken-demo/node_modules/typeorm/entity-manager/EntityManager.js:3:12)
    at EntityManager.find (/tmp/broken-demo/node_modules/typeorm/entity-manager/EntityManager.js:384:16)
    at Hello.run (/tmp/broken-demo/src/commands/hello.ts:8:37)
```

**Reflection**
You will notice that the entity is found in ```src/index.ts```, but in ```src/commands/hello.ts``` it is not. 
If you inspect the connection from inside the hello.ts class method, it clearly shows that the entity and the metadata exist. Why does this occur? This is a complete roadblock for me.

**Comment by ambiguities** [comment]
Okay so there has been no response to this so I created a repo for ease of testing.

https://github.com/ambiguities/typeorm-oclif-entitymetadatanotfound
