### ISSUE TITLE
EntityMetadata not found when using custom paths

### ISSUE THREAD

**Issue by PapsOu** [typeorm/typeorm#3137]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [ ] `mysql` / `mariadb`
- [ ] `oracle`
- [x] `postgres`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [ ] `latest`
- [ ] `@next`
- [x] `0.2.8`

**Steps to reproduce or a small repository showing the problem:**

Related to https://github.com/typeorm/typeorm/issues/420#issuecomment-440614269

Using custom path to normalize all application imports (see `tsconfig.json` file bellow), defining a relation between two entities of the same module fails with this error message when trying to generate a migration : `rm -rf ./dist/* && npm run build && npm run typeorm -- migration:generate -n registration`

```log
Error: Entity metadata for Registration#user was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at <PROJECT_DIR>/src/metadata-builder/EntityMetadataBuilder.ts:562:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (<PROJECT_DIR>/src/metadata-builder/EntityMetadataBuilder.ts:557:34)
    at <PROJECT_DIR>/src/metadata-builder/EntityMetadataBuilder.ts:112:56
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (<PROJECT_DIR>/src/metadata-builder/EntityMetadataBuilder.ts:112:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (<PROJECT_DIR>/src/connection/ConnectionMetadataBuilder.ts:66:111)
    at Connection.buildMetadatas (<PROJECT_DIR>/src/connection/Connection.ts:485:59)
    at Connection.<anonymous> (<PROJECT_DIR>/src/connection/Connection.ts:186:18)
    at step (<PROJECT_DIR>/node_modules/typeorm/connection/Connection.js:32:23)
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "paths": {
      "@user/*": [
        "src/user/*"
      ],
      "@common/*": [
        "src/common/*"
      ],
    }
  },
}
```

This one does not work :

```ts
import { User } from "@user/entity/user.entity";

@Entity()
export class Registration extends Resource {
  @OneToOne(type => User)
  @JoinColumn()
  user: User
}
```

This one works...

```ts
import { User } from "./user.entity";

@Entity()
export class Registration extends Resource {
  @OneToOne(type => User)
  @JoinColumn()
  user: User
}
```

The `user.module` (a nestjs module) declares the entities with the custom path : 

```ts
import { Registration } from '@user/entity/registration.entity';
import { User } from '@user/entity/user.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Registration,
      User
    ])
  ],
})
export class UserModule { }
```

I've tried debugging like @tomkroening did, and I've found something strange. I've added `console.log(m.target, relation.type); ` in `computeInverseProperties` method:

<PROJECT_DIR>/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:498
```js
EntityMetadataBuilder.prototype.computeInverseProperties = function (entityMetadata, entityMetadatas) {
  entityMetadata.relations.forEach(function (relation) {
    // compute inverse side (related) entity metadatas for all relation metadatas
    var inverseEntityMetadata = entityMetadatas.find(function (m) { console.log(m.target, relation.type); return m.target === relation.type || (typeof relation.type === "string" && m.targetName === relation.type); });
    if (!inverseEntityMetadata)
        throw new Error("Entity metadata for " + entityMetadata.name + "#" + relation.propertyPath + " was not found. Check if you specified a correct entity object and if it's connected in the connection options.");
    relation.inverseEntityMetadata = inverseEntityMetadata;
    relation.inverseSidePropertyPath = relation.buildInverseSidePropertyPath();
    // and compute inverse relation and mark if it has such
    relation.inverseRelation = inverseEntityMetadata.relations.find(function (foundRelation) { return foundRelation.propertyPath === relation.inverseSidePropertyPath; });
  });
};
```

When using the custom path import `@user/entity/user.entity`, the method seems to be called twice :

```log
[Function: Registration] [Function: User]
[Function: User] [Function: User]
Error during migration generation:
Error: Entity metadata for Registration#user was not found. [...]
```

When using the standard relative path import `./user.entity`, the method is called once :

```log
[Function: User] [Function: User]
Migration <PROJECT_DIR>/src/migrations/1542804671645-registration.ts has been generated successfully.
```

**Comment by elderapo** [comment]
Both of them do work but you have to use the same "convention" across all imports.

**Comment by PapsOu** [comment]
I'm already using the same convention everywhere in my project :

![20181121-160425](https://user-images.githubusercontent.com/5792207/48849695-3045c400-eda7-11e8-985f-e495ab978425.png)

Maybe, for typeorm, importing an entity with a non relative path is considered to importing an external entity, so it is detected and handled as a new entity.

**Comment by elderapo** [comment]
```ts
import * as path from "path";
import { ConnectionOptions } from "typeorm";

const options: ConnectionOptions = {
  type: "mysql",
  host: "database",
  extra: { connectionLimit: 100 }, // not sure - default is 10
  username: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
  synchronize: true,
  logging: false,
  maxQueryExecutionTime: 500, // log long running queries
  entities: [path.join(__dirname, "src/entities/*.ts")],
  migrations: [path.join(__dirname, "src/migrations/*.ts")],
  subscribers: [path.join(__dirname, "src/subscribers/*.ts")],
  cli: {
    entitiesDir: path.join("src/entities"),
    migrationsDir: path.join("src/migrations"),
    subscribersDir: path.join("src/subscribers")
  }
};

module.exports = options; // for CLI to work
```

Try out these connection options.

**Comment by PapsOu** [comment]
Here's my generated config : 

```json
{
    "type": "postgres",
    "host": "127.0.0.1",
    "port": "5432",
    "username": "user",
    "password": "pass",
    "database": "project",
    "synchronize": false,
    "keepConnectionAlive": false,
    "entityPrefix": "nest_",
    "entities": [
        "<PROJECT_DIR>/src/common/config/../../../dist/**/*.entity.js"
    ],
    "migrationsTableName": "nest_migrations",
    "migrations": [
        "dist/migrations/*.js"
    ],
    "cli": {
        "migrationsDir": "src/migrations"
    },
    "logging": false
}
```

In fact I'm defining typeorm configuration in a Nest service that generates an `ormconfig.json` file for the CLI usage only

```ts
import * as fs from 'fs';
import * as clc from 'cli-color';

import { Injectable } from "@nestjs/common";
import { TypeOrmModuleOptions, TypeOrmOptionsFactory } from "@nestjs/typeorm";

import { ConfigService, Config } from "@common/config/config.service";

@Injectable()
export class TypeORMConfigService implements TypeOrmOptionsFactory {

  private env: string = 'dev'

  constructor(
    private readonly configService: ConfigService
  ) {
    this.env = process.env.NODE_ENV || 'dev'
  }

  /**
   * Builds and gets the TypeORM configuration object
   * 
   * @param forConfigFile 
   */
  public getConfiguration(forConfigFile: boolean = false): TypeOrmModuleOptions {
    const config = {
      type: this.configService.get(Config.DATABASE_DRIVER) as any,
      host: this.configService.get(Config.DATABASE_HOST),
      port: this.configService.get(Config.DATABASE_PORT),
      username: this.configService.get(Config.DATABASE_USER),
      password: this.configService.get(Config.DATABASE_PASSWORD),
      database: this.configService.get(Config.DATABASE_NAME),
      synchronize: false,
      keepConnectionAlive: false,
      entityPrefix: this.configService.get(Config.DATABASE_TABLE_PREFIX),
      entities: [
        forConfigFile ?
          this.configService.getRootDir() + '/dist/**/*.entity.js' :
          this.configService.getSrcDir() + '/**/*.entity.ts'
      ],
      migrationsTableName: this.configService.get(Config.DATABASE_TABLE_PREFIX) + "migrations",
      migrations: ["dist/migrations/*.js"],
      cli: {
        "migrationsDir": "src/migrations"
      },
      logging: this.env === 'dev' ? true : false
    }

    return config
  }

  /**
   * Writes to the FS the TypeORM configuration as json
   * 
   * @param targetFilename 
   */
  public writeConfigurationFile(targetFilename: string): void {
    fs.writeFile(
      targetFilename,
      JSON.stringify(this.getConfiguration(true)),
      (err) => {
        // Omitted for brevity
      }
    )
  }
}
```

**Comment by elderapo** [comment]
My config `ormconfig.ts` works with CLI too. Just place it above `src` folder next to `package.json`.

**Comment by PapsOu** [comment]
Thanks to your suggestion (using your configuration file), I've spotted that I was missing a stupid thing :

```ts
  public getConfiguration(): TypeOrmModuleOptions {
    const config = {
      type: this.configService.get(Config.DATABASE_DRIVER) as any,
      host: this.configService.get(Config.DATABASE_HOST),
      port: this.configService.get(Config.DATABASE_PORT),
      username: this.configService.get(Config.DATABASE_USER),
      password: this.configService.get(Config.DATABASE_PASSWORD),
      database: this.configService.get(Config.DATABASE_NAME),
      synchronize: false,
      keepConnectionAlive: false,
      entityPrefix: this.configService.get(Config.DATABASE_TABLE_PREFIX),
      entities: [
          this.configService.getSrcDir() + '/**/*.entity.ts'
      ],
      migrationsTableName: this.configService.get(Config.DATABASE_TABLE_PREFIX) + "migrations",
      migrations: ["dist/migrations/*.js"],
      cli: {
        "entitiesDir": "src",
        "migrationsDir": "src/migrations"
      },
      logging: this.env === 'dev' ? true : false
    }

    return config
  }
```

Adding the `cli` part with the simple `src` dir fixes the issue

Now I've other issues (related to path resolving that fails after transpiling).

**Comment by PapsOu** [comment]
Thank you @elderapo
