### ISSUE TITLE
Cannot run sync a second time

### ISSUE THREAD

**Issue by Abrissirba** [typeorm/typeorm#3158]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/Abrissirba/typeorm-sync-bug

Created a small reproduction repo. 

1. run npm install
2. add an mssql database
3. edit ormconfig
4. run ts-node db/index
     SUCCESS
5. run ts-node db/index again
    query failed: CREATE UNIQUE INDEX "REL_61af3fdb55795d62a71525c62b" ON "SessionSettings"("id") WHERE "id" IS NOT NULL
error: { RequestError: The operation failed because an index or statistics with name 'REL_61af3fdb55795d62a71525c62b' already exists on table 'SessionSettings'.
    at handleError (C:\Projects\typeorm-bug\node_modules\mssql\lib\tedious.js:551:15)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Parser.<anonymous> (C:\Projects\typeorm-bug\node_modules\tedious\lib\connection.js:618:16)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at Parser.<anonymous> (C:\Projects\typeorm-bug\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at addChunk (C:\Projects\typeorm-bug\node_modules\readable-stream\lib\_stream_readable.js:291:12)

**Comment by ahaw** [comment]
same issue here
