### ISSUE TITLE
Cannot read property `<relation name>` of undefined

### ISSUE THREAD

**Issue by abhishekkumarjha** [typeorm/typeorm#3165]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repository: https://github.com/abhishekkumarjha/typeorm-issue1

**What it is**
The repository contains a simplified replication of an issue I am facing in a private project while upgrading the typeorm version from 0.1.19 to 0.2.9.

The repo throws an error when using the latest version of typeorm while it works fine with an older version (0.1.19).

**Error**

```
 TypeError: Cannot read property 'profile' of undefined
    at RelationMetadata.getEntityValue (C:\<path-to-repo>\src\metadata\RelationMetadata.ts:368:26)
    at OneToOneInverseSideSubjectBuilder.buildForSubjectRelation (C:\<path-to-repo>\src\persistence\subject-builder\OneToOneInverseSideSubjectBuilder.ts:68:58)
    at C:\<path-to-repo>\src\persistence\subject-builder\OneToOneInverseSideSubjectBuilder.ts:42:22
    at Array.forEach (<anonymous>)
    at C:\<path-to-repo>\src\persistence\subject-builder\OneToOneInverseSideSubjectBuilder.ts:35:48
    at Array.forEach (<anonymous>)
    at OneToOneInverseSideSubjectBuilder.build (C:\<path-to-repo>\src\persistence\subject-builder\OneToOneInverseSideSubjectBuilder.ts:34:23)
    at EntityPersistExecutor.<anonymous> (C:\<path-to-repo>\src\persistence\EntityPersistExecutor.ts:105:73)
    at step (C:\<path-to-repo>\node_modules\typeorm\persistence\EntityPersistExecutor.js:32:23)
    at Object.next (C:\<path-to-repo>\node_modules\typeorm\persistence\EntityPersistExecutor.js:13:53)
```

**Comment by havenchyk** [comment]
@abhishekkumarjha and if you first upgrade to 0.2.0, does it have the same issue?

**Comment by abhishekkumarjha** [comment]
@havenchyk Yes, I see the issue even with version 0.2.0.

I have created another branch to replicate it.
https://github.com/abhishekkumarjha/typeorm-issue1/tree/typeorm-v-0.2.0

**Comment by abhishekkumarjha** [comment]
Hi @havenchyk 
Is there some update to it? I am not familiar with the codebase, is there somewhere I can take a look to understand more about the issue?

Thanks

**Comment by pleerock** [comment]
I checked provided git repo and running npm start doesn't give me any error.

**Comment by Kononnable** [comment]
Closing as no response from the author.
