### ISSUE TITLE
Developer environment not working

### ISSUE THREAD

**Issue by victorschinaider** [typeorm/typeorm#3169]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to setup environment of typeorm.
I did what `DEVELOPER.md` file says, but tests are failing in first test (Bulk-save), and are not giving details of what is wrong.

**Comment by havenchyk** [comment]
@victorschinaider what steps did you try and what's the output?

**Comment by victorschinaider** [comment]
Now, i retry steps, and stops at  third test.

First, my environment: 
I'm using `nvm`, with:
- node v8.11.4 (npm v5.6.0)

So, i folllowed exactly what is said in `DEVELOPER.md`.

First i forked TypeORM and clone in my machine. (https://github.com/victorschinaider/typeorm)
 Then i setup upstream. Then i installed the dependencies. After that, i execute `docker-compose up -d` in terminal to setup databases. I copy and renamed `ormconfig.json.dist` to `ormconfig.json`.
So, i finally execute : `npm test`, and the output is:

```
> typeorm@0.2.9 test /home/schinaider/Documentos/typeorm
> rimraf ./build && tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 30000  ./build/compiled/test



  benchmark > bulk-save > case1
    ✓ testing bulk save of 10.000 objects (742ms)

  benchmark > bulk-save > case2
    ✓ testing bulk save of 10000 objects (1077ms)

  cascades > should insert by cascades from both sides (#57)
writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!
tedious deprecated The `IntN` data type is internal and will be removed. node_modules/mssql/lib/tedious.js:63:20
tedious deprecated The `BitN` data type is internal and will be removed. node_modules/mssql/lib/tedious.js:71:40
    ✓ should insert by cascades from owner side (153ms)

  columns > embedded columns
    1) should insert / update / remove entity with embedded correctly


  3 passing (9s)
  1 failing

  1) columns > embedded columns
       should insert / update / remove entity with embedded correctly:
     QueryFailedError: Error: Invalid usage of the option NEXT in the FETCH statement.
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at /home/schinaider/Documentos/typeorm/src/driver/sqlserver/SqlServerQueryRunner.ts:221:37
      at _query (node_modules/mssql/lib/base.js:1253:25)
      at Request.tds.Request.err [as userCallback] (node_modules/mssql/lib/tedious.js:620:15)
      at Request._this.callback (node_modules/tedious/lib/request.js:60:27)
      at Connection.endOfMessageMarkerReceived (node_modules/tedious/lib/connection.js:1777:20)
      at Connection.dispatchEvent (node_modules/tedious/lib/connection.js:863:38)
      at Parser.<anonymous> (node_modules/tedious/lib/connection.js:684:18)
      at Parser.<anonymous> (node_modules/tedious/lib/token/token-stream-parser.js:54:15)
      at addChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Parser.Readable.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Parser.Transform.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at Parser.afterTransform (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:91:10)
      at Parser._transform (node_modules/tedious/lib/token/stream-parser.js:69:9)
      at Parser.Transform._read (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at Parser.Transform._write (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:172:83)
      at doWrite (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:418:64)
      at writeOrBuffer (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:407:5)
      at Parser.Writable.write (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Parser.addEndOfMessageMarker (node_modules/tedious/lib/token/token-stream-parser.js:80:26)
      at Connection.message (node_modules/tedious/lib/connection.js:1768:32)
      at Connection.dispatchEvent (node_modules/tedious/lib/connection.js:863:38)
      at MessageIO.<anonymous> (node_modules/tedious/lib/connection.js:757:18)
      at ReadablePacketStream.<anonymous> (node_modules/tedious/lib/message-io.js:102:16)
      at addChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at ReadablePacketStream.Readable.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at ReadablePacketStream.Transform.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at ReadablePacketStream._transform (node_modules/tedious/lib/message-io.js:70:16)
      at ReadablePacketStream.Transform._read (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at ReadablePacketStream.Transform._write (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:172:83)
      at doWrite (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:418:64)
      at writeOrBuffer (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:407:5)
      at ReadablePacketStream.Writable.write (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Socket.ondata (_stream_readable.js:639:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)



npm ERR! Test failed.  See above for more details.
```

**Comment by havenchyk** [comment]
Confirmed, it's broken to me as well

**Comment by BrainMaestro** [comment]
I had the same problem. It's somehow related to `mssql`. Disabling it makes the issue go away.

**Comment by victorschinaider** [comment]
Indeed, if i skip `mssql` database, tests work as expected. What happened that `mssql` is not being tested?

**Comment by vlapo** [comment]
I think there are two/three issues: 

1. `QueryFailedError: Error: Invalid usage of the option NEXT in the FETCH statement.` fix coming in https://github.com/typeorm/typeorm/pull/3162

2. `ormconfig.json.dist` file has wrong user/pass for `mariadb` It should be same as for `mysql`

3. I have also issue with mssql `rowversion` column type check test. It seems that `rowversion` is just an alias for `timestamp` and returning column type `timestamp` is valid behaviour. So we need to fix a test.

**Comment by vlapo** [comment]
All issues mentioned in my previous comment should be resolved.

@victorschinaider @havenchyk @BrainMaestro Could you please confirm it on latest `master` branch and enabled all drivers except `oracle` ?

**Comment by victorschinaider** [comment]
I didn't test with mssql driver disabled. I'll try and give a feedback. But all other drivers are ok here, in latest master.

**Comment by victorschinaider** [comment]
apparently everything ok.
