### ISSUE TITLE
Start CLI under ts-node errors

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#317]
```
D:\Repositories\palport>ts-node node_modules/.bin/typeorm migrations:revert
D:\Repositories\palport\node_modules\.bin\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Ivan\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:400:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (C:\Users\Ivan\AppData\Roaming\npm\node_modules\ts-node\src\_bin.ts:182:12)
    at Module._compile (module.js:570:32)
```
I use Windows 10. Node.js 6.10.0, typeorm 0.0.8

**Comment by pleerock** [comment]
It does work on macos/linux. I think this issue either related to ts-node either node using on windows. Try to install any other cli package and run it with ts-node and you most probably will have same issues. I think you should seek for advice on ts-node package community.

**Comment by Ionaru** [comment]
For anyone coming across this issue: change `node_modules/.bin/typeorm` to `node_modules/typeorm/cli.js`.

**Comment by tomasignacioc** [comment]
> For anyone coming across this issue: change `node_modules/.bin/typeorm` to `node_modules/typeorm/cli.js`.

DUDE THANKS A LOT!!!!

**Comment by IRCraziestTaxi** [comment]
I still want to know why typeorm was the only package giving me this issue... other packages have no issue using the `node_modules/.bin/<package-name>` approach because I suppose npm uses the cmd file as opposed to the bash file. However, I did have to change `node_modules/.bin/typeorm` to `node_modules/typeorm/cli.js` to avoid this error.
