### ISSUE TITLE
STI and Relations

### ISSUE THREAD

**Issue by ygorlazaro** [typeorm/typeorm#3221]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, folks,

I am having a problem using STI and trying to make an One-To-Many relationship from the main entity to another non-related entity.

I am always receiving this message:

```

/mnt/sda3/projects/api-node/src/entities/Video.ts:11
export class Video extends LearningObject {
                           ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/mnt/sda3/projects/api-node/src/entities/Video.ts:11:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (/mnt/sda3/projects/api-node/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/sda3/projects/api-node/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I don't know what else I can do. I also tried typeorm@next. My Mysql is 8.0 on my machine, Ubuntu 18.10, but also it doesn't work using Ubuntu 16.04 LTS Server on Mysql 5.7

**Comment by ygorlazaro** [comment]
Is there someone with any idea? I am lost :(

**Comment by havenchyk** [comment]
@ygorlazaro it would be nice if you could provide a small example repo

**Comment by ygorlazaro** [comment]
I have this definitions:

```
import { Column, Entity, OneToMany, TableInheritance } from 'typeorm';
import { BaseModel } from '../shared/BaseModel';
import { LearningObjectFavorite } from './LearningObjectFavorite';

@Entity('model_objects')
@TableInheritance({ column: { type: 'varchar', name: 'type', select: true }, pattern: 'STI' })
export class ModelObject extends BaseModel {
    @Column({
        type: 'varchar',
        nullable: false,
        length: 100,
        name: 'code',
        transformer: {
            to: (code: string) => code.toUpperCase(),
            from: (code: string) => code
        }
    })
    public code!: string;

    public type!: string;

    //TODO: with this notation, the API compilation fails
    @OneToMany(() => ObjectFavorite, (favorite) => favorite.modelObject, { nullable: true })
    public favorites!: ObjectFavorite[];
}
```

```


 // this is one of my STI child:

import { ChildEntity, Column, JoinColumn, ManyToOne } from 'typeorm';
import { ModelObject } from './ModelObject';

@ChildEntity()
export class ConcreteObject extends ModelObject {
    @Column('varchar', { nullable: false, length: 100 })
    public title!: string;
}

```

and running this, outputs:

 ```
/***
 * 
 * output
 * 
 * 
 * export class ConcreteObject extends ModelObject {
 *                            ^
 * TypeError: Class extends value undefined is not a constructor or null
 *     at Object.<anonymous> (/src/entities/ConcreteObject.ts:11:28)
 *     at Module._compile (internal/modules/cjs/loader.js:688:30)
 *     at Module.m._compile (/node_modules/ts-node/src/index.ts:439:23)
 *     at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
 *     at Object.require.extensions.(anonymous function) [as .ts] (/node_modules/ts-node/src/index.ts:442:12)
 *     at Module.load (internal/modules/cjs/loader.js:598:32)
 *     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
 *     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
 *     at Module.require (internal/modules/cjs/loader.js:636:17)
 *     at require (internal/modules/cjs/helpers.js:20:18)
 * 
 */
```

**Comment by aroff** [comment]
This also happens with me

**Comment by pleerock** [comment]
@havenchyk since you marked this one as a bug, I need to know if you could reproduce this issue as well.

**Comment by pleerock** [comment]
The error author has is usually result of circular dependencies that can't be properly handled by JavaScript. 

@ygorlazaro can you add a `console.log` and check what is `LearningObject` before `export class Video extends LearningObject`? e.g.

```ts
console.log(LearningObject)
export class Video extends LearningObject {
```

If console.log will print `undefined` then its because of circular dependencies.

**Comment by pleerock** [comment]
I really think issue is in circular dependencies, so worth checking if it is first

**Comment by pleerock** [comment]
I think this issue can be closed since there is no respond from author.
