### ISSUE TITLE
Bug on Remove

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#326]
I'm getting an error when trying to remove() a record:

```
    let id = parseInt(req.params.id);
    let modelRepo: Repository<DTOModel> = this.conn.getRepository(DTOModel);
    let item: DTOModel = await modelRepo.findOneById(id);
    
    if (!item) {
      console.error(`Item: ${id} Not Found`);
      res.status(404);
      return res.send('NOT FOUND');
    }
    
    try {
      let shell = await modelRepo.remove(item);
      res.status(200);
      return res.send('OK');
    } catch (e) {
      console.error(e);
      res.status(500);
      return res.send('ERROR');
    }
```

Message:
```
Error: Database entity is not set for the given subject.
    at Subject.get [as databaseEntity] (/Users/jmurphy/projects/business/api/src/persistence/Subject.ts:198:19)
    at SubjectOperationExecutor.<anonymous> (/Users/jmurphy/projects/business/api/src/persistence/SubjectOperationExecutor.ts:765:117)
    at step (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)
    at Object.next (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)
    at /Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71
    at __awaiter (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)
    at SubjectOperationExecutor.remove (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:755:16)
    at SubjectOperationExecutor.<anonymous> (/Users/jmurphy/projects/business/api/src/persistence/SubjectOperationExecutor.ts:745:91)
    at step (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)
    at Object.next (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)
    at /Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71
    at __awaiter (/Users/jmurphy/projects/business/api/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)
    at /Users/jmurphy/projects/business/api/src/persistence/SubjectOperationExecutor.ts:745:76
    at /Users/jmurphy/projects/business/api/src/util/PromiseUtils.ts:14:24
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Postgres Logs:

```
LOG:  statement: SET search_path TO 'public', 'public';
LOG:  execute <unnamed>: SELECT "operateSubject"."id" AS "operateSubject_id", "operateSubject"."createdAt" AS "operateSubject_createdAt", "operateSubject"."madeWithModifiers" AS "operateSubject_madeWithModifiers", "operateSubject"."burnInRate" AS "operateSubject_burnInRate", "operateSubject"."optimization" AS "operateSubject_optimization", "operateSubject"."numIteration" AS "operateSubject_numIteration", "operateSubject"."numberOfTopics" AS "operateSubject_numberOfTopics", "operateSubject"."isCompleted" AS "operateSubject_isCompleted", "operateSubject"."isFailed" AS "operateSubject_isFailed", "operateSubject"."topics" AS "operateSubject_topics", "operateSubject"."topDocumentIds" AS "operateSubject_topDocumentIds", "operateSubject"."topicWeights" AS "operateSubject_topicWeights", "operateSubject"."parentLens" AS "operateSubject_parentLens", "operateSubject"."parentModel" AS "operateSubject_parentModel", "operateSubject"."attributes" AS "operateSubject_attributes", "operateSubject"."source" AS "operateSubject_source" FROM "d_t_o_model" "operateSubject" WHERE "operateSubject"."id"=$1
DETAIL:  parameters: $1 = '10'
LOG:  statement: START TRANSACTION
LOG:  execute <unnamed>: DELETE FROM "d_t_o_model" WHERE "id"=$1
DETAIL:  parameters: $1 = '10'
LOG:  statement: ROLLBACK
LOG:  execute <unnamed>: SET extra_float_digits = 3
LOG:  execute <unnamed>: set search_path = "public"
```

Row Command Works:

`DELETE FROM "d_t_o_model" WHERE "id"=10;`

**Comment by pleerock** [comment]
Thats sounds really strange. You can have this error if entity from db already has been removed. Can you show your model? Can you remove cascades if you are using them? Can you setup a very simple repository that reproduces this issue?

**Comment by aloysius-tim** [comment]
Same issue here! With a very simple repository without any cascade !

**Comment by pleerock** [comment]
@aloysius-tim please provide a complete short example

**Comment by pleerock** [comment]
I can't help you guys if you won't provide me a code examples.

**Comment by emorris00** [comment]
In case someone googles this error, this error can happen if you try to delete an entity using an id that is a string instead of a number

```
repository.remove({ id: '1' }) // doesn't work
repository.remove({ id: 1 }) // works

**Comment by et** [comment]
We also experienced this error but it was because we were saving the wrong record (basically trying to do the equivalent of ActiveRecord's [find_or_create_by](https://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by)).

```js
return this.applicationRespository.findOne({ ncUuid: applicationUuid }).then(application => {
  if (application) {
    return application;
  }

  const newApplication = new Application();
  newApplication.ncUuid = applicationUuid;
  return this.applicationRespository.save(application); <---- Error, it should be saving `newApplication`
}
```

Tracking this down was a huge pain especially since our unit tests use a mocked repo. Thankfully we had integration tests to help us deduce the problem.

Needless to say though, the error provided by typeorm is very unclear and the stacktrace never had any line references to actual application code (only typeorm code).

@pleerock - can I help here on this one? Do you have a template to fill out for bug tickets like this?

**Comment by pleerock** [comment]
@et I didn't understand your issue, what exactly your problem is?

**Comment by et** [comment]
@pleerock - when you call `repo.save(undefined)`, you get the error that original OP posted: `Error: Database entity is not set for the given subject.`.

**Comment by pleerock** [comment]
@et so as I understood your request is to throw a better error if user does `save(undefined)`? If yes, then it is already implemented in `@next` version.
