### ISSUE TITLE
Cannot read property 'ownerColumns' of undefined

### ISSUE THREAD

**Issue by aequasi** [typeorm/typeorm#3294]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 
Problems listed below. Trying to save this causes the issue mentioned in the title

```ts
// Report.ts
import {BaseEntity, Column, Entity, Index, ManyToMany, PrimaryGeneratedColumn} from 'typeorm';
import ReportCategoryEnum from '../ReportCategory';
import User from './User';



@Entity('Report')
export default class Report extends BaseEntity {
    @PrimaryGeneratedColumn()
    public Id: number;

    @ManyToMany(type => User)
    public Reporter: User;

    @Column() @Index('category', ['Category'])
    public Category: ReportCategoryEnum;

    @Column({type: 'text'})
    public Reason: string;

    @Column({type: 'bigint'}) @Index('guild', ['GuildId'])
    public GuildId?: string;

    @Column({type: 'simple-array'})
    public MessageIds: string[] = [];

    @Column({type: 'simple-array'})
    public Links: string[];

    @ManyToMany(type => User)
    public ReportedUsers: User[];

    @ManyToMany(type => User)
    public ConfirmationUsers: User[];

    @Column({type: 'datetime'}) @Index('insert_date', ['InsertDate'])
    public InsertDate: Date = new Date;

    @Column({type: 'datetime'}) @Index('update_date', ['UpdateDate'])
    public UpdateDate: Date = new Date;
}

// User.ts
import {BaseEntity, Column, Entity, Index, ManyToMany, PrimaryColumn, PrimaryGeneratedColumn, Table} from 'typeorm';
import Report from './Report';

@Entity('User')
export default class User extends BaseEntity {
    @Column({type: 'bigint'}) @Index('user_id', ['UserId'])
    @PrimaryColumn()
    public Id: string;

    @Column({type: 'datetime'}) @Index('insert_date', ['InsertDate'])
    public InsertDate: Date = new Date;

    constructor(id: string) {
        super();

        this.Id = id;
    }
}

// Code calling this

const report    = new Report();
report.Reporter = await repo.findOne(body.Reporter) || new User(body.Reporter);
report.Category = body.Category;
report.Reason   = body.Reason;
report.GuildId  = body.GuildId;

const promises: Promise<any>[] = [];
for (const x of body.ReportedUsers) {
    const user = await repo.findOne(x) || new User(x);
    if (!report.ReportedUsers) {
        report.ReportedUsers = [];
    }

    report.ReportedUsers.push(user);
    promises.push(user.save())
}

await Promise.all([...promises, report.save()]);
```

**Comment by aequasi** [comment]
Full Stack: 

```
TypeError: Cannot read property 'ownerColumns' of undefined
    at /Users/aaron/projects/hotline/api/src/persistence/subject-builder/ManyToManySubjectBuilder.ts:171:46
    at Array.forEach (<anonymous>)
    at ManyToManySubjectBuilder.buildForSubjectRelation (/Users/aaron/projects/hotline/api/src/persistence/subject-builder/ManyToManySubjectBuilder.ts:117:25)
    at /Users/aaron/projects/hotline/api/src/persistence/subject-builder/ManyToManySubjectBuilder.ts:45:22
    at Array.forEach (<anonymous>)
    at /Users/aaron/projects/hotline/api/src/persistence/subject-builder/ManyToManySubjectBuilder.ts:39:50
    at Array.forEach (<anonymous>)
    at ManyToManySubjectBuilder.build (/Users/aaron/projects/hotline/api/src/persistence/subject-builder/ManyToManySubjectBuilder.ts:32:23)
    at EntityPersistExecutor.<anonymous> (/Users/aaron/projects/hotline/api/src/persistence/EntityPersistExecutor.ts:106:64)
    at step (/Users/aaron/projects/hotline/api/node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)

```

**Comment by pleerock** [comment]
I guess its because you have missed `@JoinTable` decorator on your `ManyToMany` relations.

**Comment by aequasi** [comment]
Its a uni-directional relation. Ive also tried WITH a JoinTable, and it does it too

**Comment by pleerock** [comment]
it doesn't matter if it is uni or not, JoinTable is required for owner side. I guess you missed some of your relations. Try to add JoinTable to all your many to many relations.

**Comment by aequasi** [comment]
```
import {BaseEntity, Column, Entity, Index, JoinColumn, ManyToMany, ManyToOne, PrimaryGeneratedColumn} from 'typeorm';
import ReportCategoryEnum from '../ReportCategory';
import User from './User';



@Entity('Report')
export default class Report extends BaseEntity {
    @PrimaryGeneratedColumn()
    public Id: number;

    @ManyToOne(type => User)
    @JoinColumn()
    public Reporter: User;

    @Column() @Index('category', ['Category'])
    public Category: ReportCategoryEnum;

    @Column({type: 'text'})
    public Reason: string;

    @Column({type: 'bigint'}) @Index('guild', ['GuildId'])
    public GuildId?: string;

    @Column({type: 'simple-array'})
    public MessageIds: string[] = [];

    @Column({type: 'simple-array'})
    public Links: string[];

    @ManyToMany(type => User)
    @JoinColumn()
    public ReportedUsers: User[];

    @ManyToMany(type => User)
    @JoinColumn()
    public ConfirmationUsers: User[];

    @Column({type: 'datetime'}) @Index('insert_date', ['InsertDate'])
    public InsertDate: Date = new Date;

    @Column({type: 'datetime'}) @Index('update_date', ['UpdateDate'])
    public UpdateDate: Date = new Date;
}

```

Even with this, i'm still getting it. Where am i missing the @JoinColumn annotation?

**Comment by pleerock** [comment]
I was talking about `@JoinTable`, not `@JoinColumn`.

**Comment by aequasi** [comment]
Oy. That was in. My mistake. Thank you!

**Comment by pleerock** [comment]
YW.

Answering people questions takes time and lot of efforts. Contribute to the [future of TypeORM](https://github.com/typeorm/typeorm/issues/3267) and support the project!

**Comment by kakoma** [comment]
Besides not having the `@JoinTable` annotation, the other reason this would happen is if you try to do the creation from the entity that does NOT own the relation. 

For example, if you have a Question and a Category, and the Question is the owning side of the relation, the new entry is created like this:

```
const question = new Question()
question.title = "dogs"
question.text = "who let the dogs out?"
question.categories = [category1, category2]
await dataSource.manager.save(question)
```

If you try to do it the other way round (create a category while setting the questions in that category), this `Cannot read property 'ownerColumns' of undefined` will be generated.
