### ISSUE TITLE
Order By Joined column errorMissingRTE (Cannot be referenced from this part of the query)

### ISSUE THREAD

**Issue by DrewImm** [typeorm/typeorm#3343]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres` Postgres 10
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
`npm v0.2.9` (not on github?)

[x] `latest` 
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Cannot order-by joined column.

Users have ChatMessages, ChatMessages can `getMany()` ordered by user ID, but not by username

Much of the code has been simplified:
https://github.com/DrewImm/typeorm-bug

```ts
		await connection.manager
			.getRepository(ChatMessage)
			.createQueryBuilder('obj')
			.select()
			.leftJoinAndSelect('obj.fromUser', 'fromUser')
			.leftJoinAndSelect('obj.toUser', 'toUser')
			.addOrderBy('fromUser.username', 'DESC')
			.getMany()
			.then((result) => {
				console.log('Ordered by Username: ', result);
			})
			.catch((error) => console.error(error));
```

From the actual code:

```
[12/28/2018 17:55:31] { QueryFailedError: invalid reference to FROM-clause entry for table "from"
    at new QueryFailedError ([REDACTED]\node_modules\typeorm\error\QueryFailedError.js:28:28)
    at Query.callback ([REDACTED]\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:233:38)
    at Query.handleError ([REDACTED]\node_modules\pg\lib\query.js:142:17)
    at Connection.connectedErrorMessageHandler ([REDACTED]\node_modules\pg\lib\client.js:160:17)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> ([REDACTED]\node_modules\pg\lib\connection.js:124:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
  message: 'invalid reference to FROM-clause entry for table "from"',
  name: 'QueryFailedError',
  length: 224,
  severity: 'ERROR',
  code: NaN,
  detail: undefined,
  hint:
   'There is an entry for table "from", but it cannot be referenced from this part of the query.',
  position: '1523',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3233',
  routine: 'errorMissingRTE',
  query:
   'SELECT "obj"."id" AS "obj_id", "obj"."timeCreated" AS "obj_timeCreated", "obj"."timeUpdated" AS "obj_timeUpdated", "obj"."body" AS "obj_body", "obj"."fromStatus" AS "obj_fromStatus", "obj"."toStatus" AS "obj_toStatus", "from"."id" AS "from_id", "from"."timeCreated" AS "from_timeCreated", "from"."timeUpdated" AS "from_timeUpdated", "from"."token" AS "from_token", "from"."username" AS "from_username", "from"."fname" AS "from_fname", "from"."lname" AS "from_lname", "from"."email" AS "from_email", "from"."tempEmail" AS "from_tempEmail", "from"."password" AS "from_password", "from"."tempPassword" AS "from_tempPassword", "from"."role" AS "from_role", "from"."status" AS "from_status", "from"."biography" AS "from_biography", "from"."location" AS "from_location", "from"."thumbnail" AS "from_thumbnail", "to"."id" AS "to_id", "to"."timeCreated" AS "to_timeCreated", "to"."timeUpdated" AS "to_timeUpdated", "to"."token" AS "to_token", "to"."username" AS "to_username", "to"."fname" AS "to_fname", "to"."lname" AS "to_lname", "to"."email" AS "to_email", "to"."tempEmail" AS "to_tempEmail", "to"."password" AS "to_password", "to"."tempPassword" AS "to_tempPassword", "to"."role" AS "to_role", "to"."status" AS "to_status", "to"."biography" AS "to_biography", "to"."location" AS "to_location", "to"."thumbnail" AS "to_thumbnail", "obj"."fromId", "obj"."toId" FROM "ChatMessage" "obj" LEFT JOIN "User" "from" ON "from"."id"="obj"."fromId"  LEFT JOIN "User" "to" ON "to"."id"="obj"."toId" WHERE ("obj"."body" LIKE $1) ORDER BY obj.from.username ASC',
  parameters: [ '%%' ] }
```

**Comment by DrewImm** [comment]
Resolved: Order by statement should not contain the object alias "obj"

`ORDER BY obj.from.username ASC` should be `ORDER BY from.username ASC`

Fixed in user-space, thank you.  Hope everyone's holidays and new year are happy and healthy
