### ISSUE TITLE
Support ORDER BY IS NULL breaks typeorm when .take/.skip are used with JOIN

### ISSUE THREAD

**Issue by atomicus** [typeorm/typeorm#3356]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Following advice in 
https://github.com/typeorm/typeorm/issues/1412

I was trying to add this to my querry, but error (given at end) occured.

Steps to reproduce.

Take simple query:
```await typeorm.getManager().getRepository(Player).createQueryBuilder("player")
    .take(10)
    .skip(10)
    .addOrderBy("player.id IS NOT NULL","DESC")
    .getMany();```

This works.

Add join to it (1to1):
```await typeorm.getManager().getRepository(Player).createQueryBuilder("player")
    .leftJoinAndSelect("player.ranking","player_ranking")
    .take(10)
    .skip(10)
    .addOrderBy("player.id IS NOT NULL","DESC")
    .getMany();```

And error will appear.
What's more, removing take/skip like this:
```await typeorm.getManager().getRepository(Player).createQueryBuilder("player")
    .leftJoinAndSelect("player.ranking","player_ranking")
    .addOrderBy("player.id IS NOT NULL","DESC")
    .getMany();```

Will work correctly.
This applies to getMany, getOne, getManyAndCount (checked by my).

Error produced is:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'databaseName' of undefined
    at {...}/query-builder/SelectQueryBuilder.ts:1866:114
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression ({...}/query-builder/SelectQueryBuilder.ts:1861:14)
    at SelectQueryBuilder.<anonymous> (/{...}/query-builder/SelectQueryBuilder.ts:1779:46)
    at step ({...}/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next ({...}/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
    at {...}/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/atom/Projekty/atom/107/dcs-api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
    at SelectQueryBuilder.executeEntitiesAndRawResults ({...}/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1377:16)
(node:26326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:26326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by atomicus** [comment]
Note: order by withou "IS NULL" / "IS NOT NULL" works.

**Comment by ajxs** [comment]
I'm having the same issue, it doesn't have to be `ORDER BY IS NULL`. any `ORDER BY ` clause will create the same result. I've experiencing the issue on Postgres 10.

**Comment by Kononnable** [comment]
@atomicus @ajxs 
Could you prepare failing test/reproduction repo?

**Comment by jagabs** [comment]
having the same issue without join.

this.getRepository()
	.createQueryBuilder("p")
	.select()
	.where("p.tenant_id = :tenantId", { tenantId: userDTO.tenantId })
        .andWhere("p.status" = :s, {s: s})
	.skip(readInput.skip)
	.take(readInput.take)
        .addOrderBy("p.project_name")
	.getManyAndCount()

**Comment by jtushman** [comment]
@jagabs my gut is your .addOrderBy needs to refer the name of the relation on the entity not the column name.  Try that

**Comment by ibrahimahmed443** [comment]
Facing the same issue. Is there an update on this?

**Comment by Kononnable** [comment]
There won't be any progress until there is enough info to reproduce the issue. We can't just come up with solution for something we don't even know how to reproduce.

**Comment by Clowning** [comment]
I've this issue to... Very problematic..

**Comment by sebastiendan** [comment]
@Kononnable I have the same issue: two entities, a ManyToOne-OneToMany simple relation, a query builder with a leftJoinAndSelect and pagination (orderBy on main entity or relation entity field - both won't work - and a take).

Do you have any working example of (pagination + orderBy + JOIN)?

```
this.topicRepository
        .createQueryBuilder('topic')
        .leftJoinAndSelect('topic.wishes', 'wish')
        .where('topic.name like :name', {
          name: `%${query.name ? query.name : ''}%`,
        })
        .orderBy({
          'wish.upVote': 'DESC', // OR {'topic.createdAt': 'DESC'}, both won't work
        })
        .take(10) // NOT WORKING! => nasty way for now (pagination in controller)
        .getMany()
```

**Comment by Darkein** [comment]
I have the same issue, with a request like @sebastiendan 's request, but with a many-to-many relation.
@Kononnable what do you need exactly ? Theses exemples seems enough to reproduce the issue

**Comment by Kononnable** [comment]
There is still no entity definition here, so we have to guess how does it look like, how exactly is this relation declared.
First step in such cases is always checking entity declaration - if none of the decorators are missing etc.

>Edit: not working as in only 6 results show up while there are 7 of them.

Is a disappearing row a duplicate(two same rows should be return while it only returns one)?

**Comment by AlexDerbenew** [comment]
The problem is here. https://github.com/typeorm/typeorm/blob/a858de1f195d41aaffdeb8c10faa538dc1a15f5c/src/query-builder/SelectQueryBuilder.ts#L1875
Typeorm does not support complex ORDER BY expressions for innerJoined table values. It just parses your expression using `.split(".")`. Then, of course `column` have wrong value inside.
For **example**, if we have expression `joinedTable.someColumn is not null`, variable `column` will have ` someColumn is not null` value.
This is where this bug takes a start.
The **workaround** is to use custom selection inside of query. In example case i could make something like this:
1) add selection like this 
query.addSelect(`case when (joinedTable.someColumn = :someValue) then 1 else 0 end`, 'customOrderField')
case when (o.region_id = :sortmap_region_id) then 0.8 else 0 end
2) add sort by customOrderField like this
query.addOrderBy(`customOrderField`,`DESC`,`NULLS LAST`)

**Comment by zhenronghua** [comment]
When QueryBuilder is used to query, all fields must be entity attributes, not database table field names, such as: createTime(entity property name), not create_time(table field name);

**Comment by juanfernandoe** [comment]
I confirm it should be an entity field and not a database field but the error message has nothing to do with the problem so could be nice to have a more descriptive error to point you in the right direction to a solution.

**Comment by khongchi** [comment]
Facing the same issue too. TT

**Comment by d337** [comment]
I had the same problem and I selected with ```IFNULL(filed1,filed2) AS someFiled ``` then used it as ```qb.orderBy(someFiled, 'DESC');```.

P.S.: I was using ```take & skip``` , ```getMany()```

**Comment by royi-frontegg** [comment]
Any progress on this issue ?

**Comment by InsOpDe** [comment]
Problem exists with mssql, too

**Comment by diavrank** [comment]
Hi, any newness here? I have the same problem using nestjs.
