### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#35]
Hi,

I'm using postgres as my backend and I have a simple entity that I am trying to create. To keep it simple I have removed all of my relationships. 

```
import {Table, PrimaryColumn, Column} from 'typeorm';

@Table("USER")
export class UserDB {

    @PrimaryColumn('int', { generated: true })
    id: number;

    @Column('string', {name: 'USERNAME', length: '50'})
    username: string;

    @Column('string', {name: 'PASSWORD', length: '50'})
    password: string;

    @Column('string', {name: 'LAST_NAME', length: '50'})
    lastName: string;

    @Column('string', {name: 'FIRST_NAME', length: '50'})
    firstName: string;

    @Column('string', {name: 'EMAIL', length: '250'})
    email: string;

    @Column('string', {name: 'PHONE_NUMBER', length: '20'})
    phoneNumber: string;

}
```
I seem to be connecting to the server OK using this code: 
```
let dbHost = process.env.DB_HOST || 'localhost'
        let dbPort = process.env.DB_PORT || 5432;
        let dbName = process.env.DB_NAME || 'TEST_DB';
        let dbUserName = process.env.DB_PASS || 'testuser';
        let dbPassword = process.env.DB_USER || 'testpw';

        const options: ConnectionOptions = {
            driver: {
                type: 'postgres', // specify driver type here.
                host: dbHost,
                port: dbPort,
                username: dbUserName,
                password: dbPassword,
                database: dbName
            },
            autoSchemaCreate: true,
            entities: [UserDB],
            logging: {
                logQueries: true,
                logSchemaCreation: true
            }
            // entityDirectories: ['./server/model/**/{*.ts,*.js}'],
            // subscriberDirectories: ['./server/subscriber/**/{*.ts,*.js}']
        };

        createConnection(options).then(connection => {

            // at this point you are connected to the database, and you can
            // perform queries

        }).catch(error => console.log('Error during connection to the db: ', error));
```
After running this I receive the following error. 
```
/Users/jt/Documents/workspace/tester/node_modules/typeorm/metadata/types/ColumnTypes.js:64
        return type.name.toLowerCase();
                   ^

TypeError: Cannot read property 'name' of undefined
    at Function.typeToString (/Users/jt/Documents/workspace/tester/node_modules/typeorm/metadata/types/ColumnTypes.js:64:20)
    at /Users/jt/Documents/workspace/tester/node_modules/typeorm/decorator/columns/PrimaryColumn.js:20:57
    at DecoratePropertyWithoutDescriptor (/Users/jt/Documents/workspace/tester/node_modules/reflect-metadata/Reflect.js:555:13)
    at Object.decorate (/Users/jt/Documents/workspace/tester/node_modules/reflect-metadata/Reflect.js:108:20)
    at __decorate (/Users/jt/Documents/workspace/tester/src/server/model/user.db.js:4:92)
    at /Users/jt/Documents/workspace/tester/src/server/model/user.db.js:12:5
    at Object.<anonymous> (/Users/jt/Documents/workspace/tester/src/server/model/user.db.js:37:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

Is this an issue or have I configured things incorrectly? Is there a workaround?

Many thanks

JT

**Comment by pleerock** [comment]
you need to add following lines in your **tsconfig.json**:
```
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
```

**Comment by paistipoikka** [comment]
Thanks Umed, Yes, I already have these two values set to `true`.

**Comment by pleerock** [comment]
np, btw there are some issue right now related to custom column names, so I recommend not to use them yet, until I fix all the issues. More details [here](https://github.com/typeorm/typeorm/issues/32)

**Comment by paistipoikka** [comment]
Even without custom column names this throws up the same error. 

From what I can see, the fixes you have implemented relate to the primary column only. Is this correct?

**Comment by pleerock** [comment]
I thought you added these lines and it helped, isnt it?

```
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
```

If not, then did you add reflect-metadata shim? Like [here](https://github.com/typeorm/typeorm/blob/master/sample/sample1-simple-entity/app.ts#L1) ?

**Comment by paistipoikka** [comment]
```
"emitDecoratorMetadata": true,
 "experimentalDecorators": true,
```

These lines were already in the tsconfig file. 

Yes, `import "reflect-metadata";` is at the top of my **server.ts** file It gets called there only. But not in my entities.

**Comment by pleerock** [comment]
Can you provide complete contents of the  server.ts file?

**Comment by pleerock** [comment]
this looks like your node version issue. what node version are you using?

**Comment by paistipoikka** [comment]
```
/// <reference path='../typings/index.d.ts' />
import * as http from 'http';
import * as morgan from 'morgan';
import 'reflect-metadata';
import 'es6-shim';
import * as express from 'express';
import * as path from 'path';
import * as graphql from 'graphql';
import LOGIN_ROUTER from './server/contollers/routes';
import {createConnection, ConnectionOptions} from 'typeorm';
import {UserDB} from './server/model/user.db';

let bodyParser = require('body-parser');
let cookieParser = require('cookie-parser');


/**
 * The server.
 *
 * @class Server
 */
class Server {

    app: express.Application;

    /**
     * Bootstrap the application.
     *
     * @class Server
     * @method bootstrap
     * @static
     */
    public static bootstrap(): Server {
        return new Server();
    }

    /**
     * Constructor.
     *
     * @class Server
     * @constructor
     */
    constructor() {
        this.app = express();
        this.serverConfig(this.app);
        this.routesConfig(this.app);
        this.dbConfig(this.app);

    }

    /**
     * Configure application
     *
     * @class Server
     * @method config
     * @return void
     */
    private serverConfig(app: express.Application) {
        /**************************************
         * set up the server
         **************************************/
        app.locals.pretty = true;
        app.set('port', process.env.PORT || 4200);
        app.set('views', path.join(__dirname, 'server/views'));
        app.set('view engine', 'pug');
        app.use(morgan('short'));
        app.use(cookieParser());
        app.use(bodyParser.json());
        app.use(bodyParser.urlencoded({extended: true}));
        app.use(express.static(path.join(__dirname, 'public')));

        // catch 404 and forward to error handler
        app.use(function (err: any, req: express.Request, res: express.Response, next: express.NextFunction) {
            err.status = 404;
            next(err);
        });
    }

    /**
     * Configure routes
     *
     * @class Server
     * @method routes
     * @return void
     */
    private routesConfig(app: express.Application) {
        //use router middleware
        app.use(LOGIN_ROUTER);
    }

    /**
     * Configure db
     */
    private dbConfig(app: express.Application) {
       

        let dbHost = process.env.DB_HOST || 'localhost'
        let dbPort = process.env.DB_PORT || 5432;
        let dbName = process.env.DB_NAME || 'RACELOOP';
        let dbUserName = process.env.DB_PASS || 'jordan';
        let dbPassword = process.env.DB_USER || 'jordan';

        const options: ConnectionOptions = {
            driver: {
                type: 'postgres', // specify driver type here.
                host: dbHost,
                port: dbPort,
                username: dbUserName,
                password: dbPassword,
                database: dbName
            },
            autoSchemaCreate: true,
            entities: [UserDB],
            logging: {
                logQueries: true,
                logSchemaCreation: true
            }
            //entityDirectories: ['./server/model/**/{*.ts,*.js}']
            // subscriberDirectories: ['./server/subscriber/**/{*.ts,*.js}']
        };

        createConnection(options).then(connection => {

            // at this point you are connected to the database, and you can
            // perform queries

        }).catch(error => console.log('Error during connection to the db: ', error));
    }
}

let server = Server.bootstrap();
module.exports = server.app;


```

**Comment by paistipoikka** [comment]
node 6.5.0

**Comment by pleerock** [comment]
if its a latest node . what is reflect-metadata version you have installed? Can you take a look exact version in `node_modules/reflect-metadata/package.json` ?

**Comment by paistipoikka** [comment]
Reflect-Metadata v. 0.1.8

**Comment by pleerock** [comment]
thats very very strange. Can you provide both files without other (express, etc.) stuff (or put into git), I'll copy as it is and try to run on my machine

**Comment by paistipoikka** [comment]
OK, clone this. I've pulled out the two classes so it should work. All that's left is the server

https://github.com/paistipoikka/typeOrmTest

Requires a postgres DB called TEST_DB

testuser
testpw

**Comment by pleerock** [comment]
here is what I have: `node ./src/server.js`:
```
executing query: SELECT * FROM information_schema.tables WHERE table_catalog = 'test' AND table_schema = 'public'
executing query: SELECT * FROM information_schema.columns WHERE table_catalog = 'test' AND table_schema = 'public'
executing query: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name
                                FROM pg_class t, pg_class i, pg_index ix, pg_attribute a
                                WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
                                AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ('USER')
                                ORDER BY t.relname, i.relname
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_catalog = 'test' AND constraint_type = 'FOREIGN KEY'
executing query: SELECT * FROM information_schema.table_constraints WHERE table_catalog = 'test' AND constraint_type = 'UNIQUE'
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_catalog = 'test' AND constraint_type = 'PRIMARY KEY'
executing query: START TRANSACTION
executing query: CREATE TABLE "USER" ("id" SERIAL NOT NULL PRIMARY KEY, "username" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phoneNumber" character varying(255) NOT NULL)
executing query: COMMIT
```
thats all, no errors. Do you have same log, and error after it, or before it?

**Comment by paistipoikka** [comment]
yes, I still get this problem...

```
/Users/jt/Documents/workspace/typeOrmTest/node_modules/typeorm/metadata/types/ColumnTypes.js:64
        return type.name.toLowerCase();
                   ^

TypeError: Cannot read property 'name' of undefined
    at Function.typeToString (/Users/jt/Documents/workspace/typeOrmTest/node_modules/typeorm/metadata/types/ColumnTypes.js:64:20)
    at /Users/jt/Documents/workspace/typeOrmTest/node_modules/typeorm/decorator/columns/PrimaryColumn.js:20:57
    at DecoratePropertyWithoutDescriptor (/Users/jt/Documents/workspace/typeOrmTest/node_modules/reflect-metadata/Reflect.js:555:13)
    at Object.decorate (/Users/jt/Documents/workspace/typeOrmTest/node_modules/reflect-metadata/Reflect.js:108:20)
    at __decorate (/Users/jt/Documents/workspace/typeOrmTest/src/server/model/user.db.js:4:92)
    at /Users/jt/Documents/workspace/typeOrmTest/src/server/model/user.db.js:12:5
    at Object.<anonymous> (/Users/jt/Documents/workspace/typeOrmTest/src/server/model/user.db.js:37:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

Did you try to run it directly from the cloned sources from git? I tried cloning the sources from github then npm install and typings install. That gave me the error above. 

The package.json in the repo is the same file I am using. 

So it all went OK for you?

**Comment by pleerock** [comment]
I only removed import LOGIN_ROUTER from './server/contollers/routes'; line because it was complaining that directory does not exist + changed     `"module": "es6"`, to     `"module": "commonjs"` in tsconfig.json

**Comment by pleerock** [comment]
just made upgrade to latest node v6.6.0 - still works

**Comment by pleerock** [comment]
what is your typescript compiler version?

**Comment by paistipoikka** [comment]
TSC 2.0.2

**Comment by pleerock** [comment]
just installed same version, still works. Can you try to change "module": "es6", to "module": "commonjs" and check it?

**Comment by paistipoikka** [comment]
Yes, just tried commonjs and that gives the same error. 

Can you please point me to a repo that I can try this with? Maybe I have a problem with a global library or something....

**Comment by paistipoikka** [comment]
What command are you using to run TSC?

**Comment by pleerock** [comment]
simply `tsc`

**Comment by pleerock** [comment]
try to clone [this repo](https://github.com/typeorm/typescript-example) and try

**Comment by paistipoikka** [comment]
OK, that worked.

I am guessing that this may be some sort of problem with a library conflict or something. 

I will try to refactor the project structure. I'll come back when that's done.

**Comment by paistipoikka** [comment]
BTW, did you get some sort of error when trying to persist the object from your repo? I can connect but I get:

```
Error:  Error: Insert operation for [object Object] was not found.
    at PersistOperationExecutor.insertJunctions (/Users/jt/Documents/workspace/typescript-example/node_modules/typeorm/persistment/PersistOperationExecutor.js:451:23)
    at Promise.all.persistOperation.junctionInserts.map.junctionOperation (/Users/jt/Documents/workspace/typescript-example/node_modules/typeorm/persistment/PersistOperationExecutor.js:157:25)
    at Array.map (native)
    at PersistOperationExecutor.executeInsertJunctionsOperations (/Users/jt/Documents/workspace/typescript-example/node_modules/typeorm/persistment/PersistOperationExecutor.js:156:61)
    at Promise.resolve.then.then.then.then.then.then (/Users/jt/Documents/workspace/typescript-example/node_modules/typeorm/persistment/PersistOperationExecutor.js:35:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by pleerock** [comment]
I have updated it, forgot to add cascade options

**Comment by paistipoikka** [comment]
OK, so this was a problem with the configuration of my project. It appears that in my package.json I was specifying the entry point (`tsc ./src/server.ts`) which caused the tsconfig.json to be ignored. As soon as I changed it, it started working. Typescript can be pretty frustrating....

**Comment by pleerock** [comment]
good to hear
