### ISSUE TITLE
Postgres quote issue while saving

### ISSUE THREAD

**Issue by saachinsiva** [typeorm/typeorm#3521]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have two simple entities User and Account with many to many associations.

```
import { AccountEntity } from '@account/dao/entities/account.entity';
import { Column, Entity, JoinTable, ManyToMany, OneToMany, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class UserEntity {
    @PrimaryGeneratedColumn({ name: 'user_id', type: 'int' })
    userId: number;

    @Column({ name: 'login_id', type: 'date' })
    loginId: string;

    @Column({ name: 'first_name', type: 'date' })
    firstName: string;

    @Column({ name: 'middle_name', type: 'date' })
    middleName: string;

    @Column({ name: 'last_name', type: 'date' })
    lastName: string;

    @ManyToMany(type => AccountEntity, acct => acct.userEntities, { cascade: true })
    @JoinTable({
        name: 'account_user_asn',
        joinColumn: {
            name: 'user_id',
            referencedColumnName: 'userId'
        },
        inverseJoinColumn: {
            name: 'acct_number',
            referencedColumnName: 'accountNumber'
        }
    })
    accountEntities: AccountEntity[];

}

import { UserEntity } from '@user/dao/entities/user.entity';
import {
    Column,
    Entity,
    JoinColumn,
    JoinTable,
    ManyToMany,
    ManyToOne,
    OneToMany,
    OneToOne,
    PrimaryGeneratedColumn,
} from 'typeorm';


@Entity('account')
export class AccountEntity {
    @PrimaryGeneratedColumn({ name: 'acct_number', type: 'int' })
    accountNumber: number;

    @Column({ name: 'acct_name', type: 'varchar', length: 100 })
    acctName: string;

    @ManyToMany(userEntity => UserEntity, userEnt => userEnt.accountEntities)
    userEntities: UserEntity[];
}
```
When I try to save the user ,it tries to select rows from acct_user_asn table but the query is using inconsistent quotes and this is a problem especially with pg. As you can see below the double quote is missing in the columns and db is throwing an error as given below.

> query failed: SELECT **UserEntity_accountEntities_rid**.acct_number AS "acct_number", **UserEntity_accountEntities_rid**.user_id AS "user_id" FROM "account" "account" INNER JOIN "account_user_asn" "UserEntity_accountEntities_rid" ON (**UserEntity_accountEntities_rid**.user_id = $1 AND **UserEntity_accountEntities_rid**.acct_number = "account"."acct_number") ORDER BY **UserEntity_accountEntities_rid**.acct_number ASC, **UserEntity_accountEntities_rid**.user_id ASC -- PARAMETERS: [1]

> error: { error: missing FROM-clause entry for table "userentity_accountentities_rid"
>     at Connection.parseE (C:\Repos\STEP\server\node_modules\pg\lib\connection.js:554:11)
>     at Connection.parseMessage (C:\Repos\STEP\server\node_modules\pg\lib\connection.js:379:19)
>     at TLSSocket.<anonymous> (C:\Repos\STEP\server\node_modules\pg\lib\connection.js:119:22)
>     at TLSSocket.emit (events.js:182:13)
>     at TLSSocket.EventEmitter.emit (domain.js:441:20)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at TLSSocket.Readable.push (_stream_readable.js:219:10)
>     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by dorianhost** [comment]
Have the same problem. It's happens because of using custom column names in many-to-many relation table and specifying this names in  `joinColumn` and `inverseJoinColumn` properties of `@JoinTable` decorator.  If column names left default (`entityId`) - everything works fine. 
Nevertheless, fix need...

**Comment by timtkachenko** [comment]
I also have the same problem.

**Comment by zsylvia** [comment]
Having the same issue, just as @dorianhost described

**Comment by coopers98** [comment]
Same problem here

**Comment by dimuska139** [comment]
A little temporary workaround:
```js
let post = new Post();
post.slug = slug;
post.title = dto.title;
...
const categories = await this.categoriesRepository.findByIds(dto.categoriesIds);
await this.connection.transaction(async manager => {
      post = await manager.save(post);
      if (categories.length > 0) {
        const parts = [];
        for (const category of categories) {
          parts.push("(" + post.id + "," + category.id + ")");
        }

        const insCategoriesSql = "INSERT INTO posts_categories(post_id, category_id) VALUES ";
        await manager.query(insCategoriesSql + parts.join());
      }
});
```

**Comment by khuongphp** [comment]
@saachinsiva Change your table name from `account_user_asn` to `accountUserAsn` (Snake case to Camel case) resolved my problem. You also change other table name, column name if need
```
    @ManyToMany(type => AccountEntity, acct => acct.userEntities, { cascade: true })
    @JoinTable({
        name: 'accountUserAsn', // change this
        joinColumn: {
            name: 'user_id',
            referencedColumnName: 'userId'
        },
        inverseJoinColumn: {
            name: 'acct_number',
            referencedColumnName: 'accountNumber'
        }
    })
```
