### ISSUE TITLE
RegExp.prototype.source getter called on non-RegExp object

### ISSUE THREAD

**Issue by consense** [typeorm/typeorm#3534]
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X ] `typeorm@0.2.9` (or put your version here)

Error doesnt appear in typeorm@0.2.8 and is thrown in versions typeorm@0.2.9 through to typeorm@0.2.12

**Steps to reproduce or a small repository showing the problem:**

```
     TypeError: RegExp.prototype.source getter called on non-RegExp object
      at RegExp.get source [as source] (<anonymous>)
      at RegExp.toString (<anonymous>)
      at isNaN (<anonymous>)
      at Function.OrmUtils.compare2Objects (src\util\OrmUtils.ts:171:13)
      at Function.OrmUtils.compare2Objects (src\util\OrmUtils.ts:236:31)
      at Function.OrmUtils.compare2Objects (src\util\OrmUtils.ts:236:31)
      at Function.OrmUtils.compare2Objects (src\util\OrmUtils.ts:236:31)
      at Function.OrmUtils.deepCompare (src\util\OrmUtils.ts:118:23)
      at Function.EntityMetadata.compareIds (src\metadata\EntityMetadata.ts:723:25)
      at EntityMetadata.compareEntities (src\metadata\EntityMetadata.ts:590:31)
      at \src\persistence\SubjectDatabaseEntityLoader.ts:126:81
      at Array.filter (<anonymous>)
      at SubjectDatabaseEntityLoader.findByPersistEntityLike (src\persistence\SubjectDatabaseEntityLoader.ts:119:30)
      at \src\persistence\SubjectDatabaseEntityLoader.ts:96:39
      at Array.forEach (<anonymous>)
      at SubjectDatabaseEntityLoader.<anonymous> (src\persistence\SubjectDatabaseEntityLoader.ts:95:22)
      at step (node_modules\typeorm\persistence\SubjectDatabaseEntityLoader.js:32:23)
      at Object.next (node_modules\typeorm\persistence\SubjectDatabaseEntityLoader.js:13:53)
      at fulfilled (node_modules\typeorm\persistence\SubjectDatabaseEntityLoader.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Gladly tell me if you'd need more info - tbh I would be hard pressed to produce a minimal reproduction repo, but if you have any specific questions just shoot :-)

**Comment by Kononnable** [comment]
Yeah, I think we would need some way to reproduce that :)
Right now we know when bug was introduced(1 month period) but without way to reproduce it we won't be able to confirm any fixes or even if bug is in typeorm code.

**Comment by sam-hunt** [comment]
Just had this throw in `typeorm@0.2.18`. Also as yet unsure of the cause.

**Comment by tobyhinloopen** [comment]
@Kononnable I found a way to reproduce the error: Try to persist an object with a RegExp in one of the columns. Note that I do use a transformer!

```ts
import { Entity, PrimaryGeneratedColumn } from "typeorm";
import { RegExpColumn } from "../../src/RegExpColumn";

@Entity()
export class Thing {
  @PrimaryGeneratedColumn()
  public id: number;

  @RegExpColumn()
  public foo: RegExp;
}
```

```ts
import { Column, ColumnOptions } from "typeorm";
import { RegExpStringTransformer } from "./RegExpStringTransformer";

export function RegExpColumn(opts: ColumnOptions = {}) {
  opts.type = String;
  opts.transformer = RegExpStringTransformer;
  return Column(opts)
}
```

```ts
export namespace RegExpStringTransformer {
  export function to(value: RegExp): string {
    return value.toString();
  }

  export function from(value: string): RegExp {
    const match = value.match(/^\/(.*)\/(.*)$/);
    if (match) {
      const [, pattern, flags] = match;
      return new RegExp(pattern, flags);
    } else {
      throw new Error(`"${value}" is not a regular expression`);
    }
  }
}
```

Repo (exact commit): https://github.com/tobyhinloopen/bonaroo-reg-exp-column/tree/65f591bffe62cbf9bdabd84cf4fc6352a5ae6eb5

**Comment by tobyhinloopen** [comment]
Found the origin: `OrmUtils.mergeDeep` clones RegExp (and possibly other JS objects) incorrectly.

**Comment by tobyhinloopen** [comment]
@consense here you go: https://github.com/typeorm/typeorm/pull/5182
