### ISSUE TITLE
using cli to run migration failed with cache offline

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3559]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have config `cache` in `ormconfig.json`.

There is no and shall not use cache when running migration.

```log
> ts-node --files ./node_modules/.bin/typeorm migration:run "-c" "staging"

query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'migrations'
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache cache:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Error during migration run:
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/Users/Diluka/parsec/nestjs-pre-start/node_modules/ioredis/built/redis/event_handler.js:95:37)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at TCP._handle.close (net.js:600:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nestjs-pre-start@0.0.0 typeorm:migration:run: `ts-node --files ./node_modules/.bin/typeorm migration:run "-c" "staging"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nestjs-pre-start@0.0.0 typeorm:migration:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Diluka/.npm/_logs/2019-02-02T07_29_29_503Z-debug.log
```

**Comment by pleerock** [comment]
Yes. We need to think if there are no cases when we need cache in the cli commands, and if there are no, then we can probably fix it by just overriding `cache` directly in cli commands.
