### ISSUE TITLE
Cannot find module defined as moduleNameMapper

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3645]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

use cli `ts-node ./node_modules/.bin/typeorm migration:generate -n Init`

```
{ Error: Cannot find module '@app/shared'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Diluka/parsec/nestjs-pre-start/src/entity/drop-table.entity.ts:36:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Users/Diluka/parsec/nestjs-pre-start/node_modules/ts-node/src/index.ts:413:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/Diluka/parsec/nestjs-pre-start/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.PlatformTools.load (/Users/Diluka/parsec/nestjs-pre-start/src/platform/PlatformTools.ts:129:28)
    at /Users/Diluka/parsec/nestjs-pre-start/src/util/DirectoryExportedClassesLoader.ts:32:36 code: 'MODULE_NOT_FOUND' }
```

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "outDir": "./dist",
    "importHelpers": true,
    "baseUrl": "./",
    "typeRoots": [
      "node_modules/@types"
    ],
    "paths": {
      "@app/auth": [
        "libs/auth/src"
      ],
      "@app/auth/*": [
        "libs/auth/src/*"
      ],
      "@app/shared": [
        "libs/shared/src"
      ],
      "@app/shared/*": [
        "libs/shared/src/*"
      ]
    }
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Diluka** [comment]
I found the same issue in https://github.com/nestjs/nest/issues/986

according to https://github.com/nestjs/nest/issues/986#issuecomment-414610484
use [tsconfig-paths](https://github.com/dividab/tsconfig-paths) to resolve paths in `tsconfig.json`
