### ISSUE TITLE
Brackets syntax failed when use where with object literal

### ISSUE THREAD

**Issue by vietthang** [typeorm/typeorm#3685]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I use Brackets syntax with object literal as below:

```ts
const generatedSql = entityManager
    .createQueryBuilder()
    .from(Product, 'Product')
    .where(new Brackets(qb => qb.where({ id: 1 })))
```

I got exception:

```
(node:97360) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasMetadata' of undefined
    at SelectQueryBuilder.QueryBuilder.computeWhereParameter (/Users/thangnv/Develop/typeorm-report/src/query-builder/QueryBuilder.ts:763:47)
    at SelectQueryBuilder.where (/Users/thangnv/Develop/typeorm-report/src/query-builder/SelectQueryBuilder.ts:690:32)
    at Brackets.entityManager.createQueryBuilder.from.where.typeorm_1.Brackets.qb [as whereFactory] (/Users/thangnv/Develop/typeorm-report/src/test.ts:27:34)
    at SelectQueryBuilder.QueryBuilder.computeWhereParameter (/Users/thangnv/Develop/typeorm-report/src/query-builder/QueryBuilder.ts:750:19)
    at SelectQueryBuilder.where (/Users/thangnv/Develop/typeorm-report/src/query-builder/SelectQueryBuilder.ts:690:32)
    at test (/Users/thangnv/Develop/typeorm-report/src/test.ts:27:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

From my quick research, the issue come from this line:

```ts
if (this.expressionMap.mainAlias!.hasMetadata) {
```

Seem like omit null check in `mainAlias` causes this issue.

Thanks,

**Comment by pie6k** [comment]
I have this issue too

**Comment by AndKiel** [comment]
Encountered the same thing today.
Any news on this?

**Comment by lucashsilva** [comment]
Same problem

**Comment by abstractmatter** [comment]
Same here with `0.2.17`

**Comment by viczam** [comment]
And news on this?

**Comment by lucasbemol** [comment]
I have the same problem

**Comment by guilhermetelles** [comment]
Any news on this?

**Comment by serhiisol** [comment]
Having the same problem with `"typeorm": "0.2.21"`

**Comment by pleerock** [comment]
@Kononnable people keep using `.where({ ... })` syntax when its supposed to be internal functionality used by ORM itself and thus have some bugs. We'll need to figure out query builder refactoring to prevent this unintended usage.

**Comment by kevindashgit** [comment]
> @Kononnable people keep using `.where({ ... })` syntax when its supposed to be internal functionality used by ORM itself and thus have some bugs. We'll need to figure out query builder refactoring to prevent this unintended usage.

...and what's the intended usage?

**Comment by serg06** [comment]
@kevindashgit I believe this is the intended usage:

```ts
.where('id = :id', {id});
```
