### ISSUE TITLE
Entity save fails after lazy loading relations

### ISSUE THREAD

**Issue by AnderoKoplus** [typeorm/typeorm#3689]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.12` and `0.2.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts 
import { Entity, JoinTable, ManyToMany, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class FooBar {
    @PrimaryGeneratedColumn()
    public id!: number;

    @ManyToMany((type) => FooBar, (fooBar) => fooBar.competitors)
    @JoinTable()
    public competitors!: Promise<FooBar[]>;
}

    const fooBar = await getManager().getRepository(FooBar).findOne(1);
    const c = await fooBar.competitors; // lazy loading causes ORM to fail
    const a = await getManager().getRepository(FooBar).save(fooBar);

TypeError: Cannot read property 'find' of undefined
    at persistence\subject-builder\ManyToManySubjectBuilder.ts:152:75
    at Array.forEach (<anonymous>)
    at ManyToManySubjectBuilder.buildForSubjectRelation (persistence\subject-builder\ManyToManySubjectBuilder.ts:117:25)
    at persistence\subject-builder\ManyToManySubjectBuilder.ts:45:22
    at Array.forEach (<anonymous>)
    at persistence\subject-builder\ManyToManySubjectBuilder.ts:39:50
    at Array.forEach (<anonymous>)
    at ManyToManySubjectBuilder.build (persistence\subject-builder\ManyToManySubjectBuilder.ts:32:23)
    at EntityPersistExecutor.<anonymous> (persistence\EntityPersistExecutor.ts:106:64)
    at step (node_modules\tslib\tslib.js:133:27)

```
it works with 0.2.11

**Comment by 720degreeLotus** [comment]
Lazy-Loading with Promises was abandonded in the end of 2018. There sadly will be no further support and i also do have mny problems with Lazy-Loading, which seem to be never solved.
See this comment as ref:
https://github.com/typeorm/typeorm/pull/2902#issuecomment-433624122

**Comment by johannesschobel** [comment]
Wait.. do you say, that `lazy-loading` of relationships is deprecated? :scream:

**Comment by 720degreeLotus** [comment]
It's not that simple, i now know...
https://github.com/typeorm/typeorm/issues/3703

**Comment by johannesschobel** [comment]
hm, good to know.. i come from the "Laravel universe" and relationships are 99% lazy-loaded - except if you explicitly load them eager.. So this was the "go to strategy" in Laravel - and therefore i am quite familiar with it.. I know, lazy loading has several downsides, for example, it may result in a lot of extra queries (e.g., for complex, deeply nested structures) which may be easier to get / load if you query it eagerly (e.g., everything is get within one single but more complex query)

Thanks for linking to the other issue!
