### ISSUE TITLE
Self referencing error

### ISSUE THREAD

**Issue by SPAHI4** [typeorm/typeorm#376]
typeorm 0.0.11, babel 7.0.0@alpha-3

User
```
import {
	Entity,
	Column,
	PrimaryGeneratedColumn,
	ManyToOne,
	OneToMany,
	CreateDateColumn,
	Index,
	ManyToMany,
	JoinTable,
} from "typeorm";

@Entity('user')
export class User {
	@PrimaryGeneratedColumn('int')
	id = undefined;	

	@ManyToMany(type => User, user => user.friendsInvitesSent, {
		cascadeInsert: true,
		cascadeUpdate: true,
	})
	@JoinTable()
	friendsInvites = undefined;

	@ManyToMany(type => User, user => user.friendsInvites, {
		cascadeInsert: true,
		cascadeUpdate: true,
		cascadeRemove: true,
	})
	friendsInvitesSent = undefined;


	@ManyToMany(type => User, user => user.friendsInverse, {
		cascadeInsert: true,
		cascadeUpdate: true,
	})
	@JoinTable()
	friends = undefined;

	@ManyToMany(type => User, user => user.friends, {
		cascadeInsert: true,
		cascadeUpdate: true,
		cascadeRemove: true,
	})
	friendsInverse = undefined;

}
```

my function
```
			const currentUser = await userRepository.findOneById(ctx.state.user.id, {
				alias: "user",
				leftJoinAndSelect: {
					"friends": "user.friends",
					"friendsInverse": "user.friendsInverse",
					"friendsInvites": "user.friendsInvites",
					"friendsInvitesSent": "user.friendsInvitesSent"
				}
			});

			const friend = await userRepository.findOneById(id, {
				alias: "user",
				leftJoinAndSelect: {
					"friends": "user.friends",
					"friendsInverse": "user.friendsInverse",
					"friendsInvites": "user.friendsInvites",
					"friendsInvitesSent": "user.friendsInvitesSent"
				}
			});

			currentUser.friendsInvitesSent.push(friend); // friend.friendsInvites.push(currentUser) doesn't work too
			return userRepository.persist(currentUser);
```

error
```
TypeError: Cannot read property 'joinColumnName' of undefined
    at SubjectBuilder.<anonymous> (/Users/spahi4/WebstormProjects/Fadi M/posts-app/src/persistence/SubjectBuilder.ts:551:109)
    at step (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at /Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:7:71
    at __awaiter (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:3:12)
    at /Users/spahi4/WebstormProjects/Fadi M/posts-app/src/persistence/SubjectBuilder.ts:289:71
    at Array.map (native)
    at SubjectBuilder.<anonymous> (/Users/spahi4/WebstormProjects/Fadi M/posts-app/src/persistence/SubjectBuilder.ts:289:53)
    at step (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at /Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:7:71
    at __awaiter (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:3:12)
    at SubjectBuilder.buildCascadeRemovedAndRelationUpdateOperateSubjects (/Users/spahi4/WebstormProjects/Fadi M/posts-app/node_modules/typeorm/persistence/SubjectBuilder.js:332:16)
    at /Users/spahi4/WebstormProjects/Fadi M/posts-app/src/persistence/SubjectBuilder.ts:110:25
    at Array.map (native)
    at SubjectBuilder.<anonymous> (/Users/spahi4/WebstormProjects/Fadi M/posts-app/src/persistence/SubjectBuilder.ts:109:63)
```

**Comment by pleerock** [comment]
are you able to test same with typescript? (to understand is it babel-specific issue or not)

**Comment by SPAHI4** [comment]
I'm sorry for the long reply. I'm not able to do this because I'm not familiar in typescript.
