### ISSUE TITLE
Geography column insert data

### ISSUE THREAD

**Issue by abhyuditjain** [typeorm/typeorm#3767]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is the location entity.

```
import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    JoinColumn,
    ManyToOne,
} from 'typeorm';

import { TripEntity } from '../trip/trip.entity';

@Entity('trip_locations')
export class LocationEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: 'geography', srid: 4326 })
    location: string;

    @CreateDateColumn({ type: 'timestamptz' })
    createdAt: Date;

    @ManyToOne(type => TripEntity, trip => trip.locations)
    @JoinColumn()
    trip: TripEntity;
}
```

And I am inserting the geojson like this:

```
await this.locationRepository.insert({
            trip,
            location: {
                type: 'Point',
                coordinates: [data.longitude, data.latitude]
            },
        });
```

It gives me error:

```
src/location/location.service.ts(92,63): error TS2345: Argument of type '{ trip: any; location: { type: string; coordinates: number[]; }; }' is not assignable to parameter of type 'QueryPartialEntity<LocationEntity> | QueryPartialEntity<LocationEntity>[]'.
  Type '{ trip: any; location: { type: string; coordinates: number[]; }; }' is not assignable to type 'QueryPartialEntity<LocationEntity>'.
    Types of property 'location' are incompatible.
      Type '{ type: string; coordinates: number[]; }' is not assignable to type 'string | (() => string)'.
        Type '{ type: string; coordinates: number[]; }' is not assignable to type '() => string'.
          Type '{ type: string; coordinates: number[]; }' provides no match for the signature '(): string'.
```

**Comment by abhyuditjain** [comment]
I get this error when I use `JSON.stringify()`:

```
query failed: INSERT INTO "trip_locations"("location", "createdAt", "tripId") VALUES (ST_SetSRID(ST_GeomFromGeoJSON($1), 4326)::geography, DEFAULT, $2) RETURNING "id", "createdAt" -- PARAMETERS: ["\"{\\\"type\\\":\\\"Point\\\",\\\"coordinates\\\":[77,27]}\"","670732b059f047194371"]
error: { error: unknown GeoJSON type
    at Connection.parseE (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 76,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'lwgeom_pg.c',
  line: '128',
  routine: 'pg_error' }
[Nest] 7481   - 3/6/2019, 1:16:21 PM   [ExceptionsHandler] unknown GeoJSON type +45ms
QueryFailedError: unknown GeoJSON type
    at new QueryFailedError (/home/abhyuditjain/Code/Roadzen/telematics/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/home/abhyuditjain/Code/Roadzen/telematics/src/driver/postgres/PostgresQueryRunner.ts:176:30)
    at Query.handleError (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/client.js:160:17)
    at Connection.emit (events.js:189:13)
    at Connection.EventEmitter.emit (domain.js:441:20)
    at Socket.<anonymous> (/home/abhyuditjain/Code/Roadzen/telematics/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
```

**Comment by Kononnable** [comment]
You marked it as question, yet I don't see any question in here :)

GeoJSON is PostGIS type, do you have PostGIS installed on your db?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by hussainwali74** [comment]
@Kononnable  sir I have PostGis installed I am still getting the error unkown geojson.

this is my column:

  @ApiProperty({
    type: String,
    title: 'current_location',
    example: 'POINT(39.807222,-76.984722)',
  })
  @Index({ spatial: true })
  @Column({
    type: 'geometry',
    srid: 4326,
    nullable: true,
    spatialFeatureType: 'Point',
  })
  current_location: string;

please help

**Comment by alexphamhp** [comment]
Guys, I think the error comes from 
`@Column({
type: 'geometry
})`

If you guys try with `@Column("geometry)`, it works
