### ISSUE TITLE
Saving joined entity with relations fails

### ISSUE THREAD

**Issue by adamalfredsson** [typeorm/typeorm#3801]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have these two entities:

```
@Entity()
export class Author extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @OneToMany(() => AuthorBook, (authorBook) => authorBook.author)
  public authorBooks: AuthorBook[];
}

@Entity()
export class AuthorBook extends BaseEntity {
    @PrimaryColumn('uuid')
    public authorId: string;

    @PrimaryColumn('uuid')
    public bookId: string;

    @ManyToOne(() => Author, (author) => author.authorBooks, { onDelete: 'CASCADE' })
    public author: Author;
}
```

1) I query an author and join its related `authorBooks`, and receive an author with an array of `AuthorBook`.

2) I save the author.

```
const author = await getRepository(Author)
    .createQueryBuilder('a')
    .where('a.id = :id', { id })
    .leftJoinAndSelect('a.authorBooks', 'ab')
    .getOne();
await author.save();
```

3) Exception is thrown:

> "null value in column \"authorId\" violates not-null constraint"

```
"exception": {
        "code": "23502"
        "column": "authorId"
        "detail": "Failing row contains (8679c737-4559-441e-87aa-97849b9b3f01, null)."
        "file": "execMain.c"
        "length": 244
        "line": "2042"
        "message": "null value in column \"authorId\" violates not-null constraint"
        "name": "QueryFailedError"
        "parameters": [
          "8679c737-4559-441e-87aa-97849b9b3f01"
          "a56d0433-5dba-4ee9-8287-b40ec6d276a7"
          [null]
        ]
        "query": "UPDATE \"authorBook\" SET \"authorId\" = $3 WHERE \"bookId\" = $1 AND \"authorId\" = $2"
        "routine": "ExecConstraints"
        "schema": "public"
        "severity": "ERROR"
}
```

**Comment by echoskydev** [comment]
I have a problem like this too.

categoryId is null value on insert new value 

```
@Entity() 
export class Category {
@PrimaryGeneratedColumn()
id: number;

@Column()
name: string;

@OneToMany(type => ProductTypes, producttypes => producttypes.category)
producttypes: ProductTypes[];
}


@Entity() 
export class ProductTypes {
@PrimaryGeneratedColumn()
id: number;

@Column()
name: string;

@ManyToOne(type => Category, category => category.producttypes, {cascade: ["insert"]})
category: Category;

}

```

**Comment by Kononnable** [comment]
Guys could you make a reproduction repo/failing test? I'm not able to reproduce the issue.

**Comment by nomadoda** [comment]
> Guys could you make a reproduction repo/failing test? I'm not able to reproduce the issue.

I think it is related to this issue: https://github.com/typeorm/typeorm/issues/3095

I didn't manage to reproduce the `null value` error at the moment, instead exception `duplicate key` is thrown. Created a minimal reproduction here:
 
https://github.com/nomadoda/typeorm-one-to-many-bug

**Comment by GitStorageOne** [comment]
Exception from first message related to #1761.   
More info here: https://github.com/typeorm/typeorm/issues/1913#issuecomment-380419861

When you saved `Author` with `authorBooks` and then try to remove some of `authorBooks` you get error   
`null value in column \"authorId\"`. Currently it's opened issue for milestone 3.0.0.  

With postgresql you can implement custom RULE, when TypeORM try to update row with `authorId=null` that mean, row must be deleted.

Something like that:
```
CREATE OR REPLACE RULE delete_row_with_null_author_id AS ON UPDATE TO AuthorBook
    WHERE new.authorId IS NULL
    DO INSTEAD (DELETE FROM AuthorBook WHERE authorId = old.authorId AND bookId = new.bookId)
```

**Comment by nomadoda** [comment]
Could possibly be related, but I never intended to remove any `authorBook` in my example.

**Comment by jagabs** [comment]
in my case i get this:

query: UPDATE "occupied_room" SET "folio_id" = $1, "version" = "version" + 1, "modified_datetime" = CURRENT_TIMESTAMP WHERE "occupied_room_id" IS NULL -- PARAMETERS: [85]
query: UPDATE "occupied_room" SET "folio_id" = $1, "version" = "version" + 1, "modified_datetime" = CURRENT_TIMESTAMP WHERE "occupied_room_id" IS NULL -- PARAMETERS: [85]

**WHERE "occupied_room_id" IS NULL** i think this should be the foreign key instead of the primary key

**Comment by bestickley** [comment]
Has the cascade property been considered in this discussion?
See [here](https://stackoverflow.com/questions/54965381/how-to-insert-an-entity-with-onetomany-relation-in-nestjs)

**Comment by majorhayes** [comment]
I'm getting this issue also. my expection is for TypeORM to delete the old records and insert the new ones, but it's trying update the old records with a null foreign key instead.  I have `@OneToMany({ cascade: true })` set on the parent model and `@ManyToOne(() => User, user => user.children, { primary: true }` set on the child entity.

**Comment by jcrben** [comment]
for anyone else who runs into this `null value in column \"X\" violates not-null constraint` when saving - in my case the issue there is https://github.com/typeorm/typeorm/issues/2121 and it can be fixed by the new `orphanedRowAction` feature https://github.com/typeorm/typeorm/issues/2121#issuecomment-788152519

**Comment by nikelborm** [comment]
I have such problem

I have user model like this:
```typescript
@Entity({ name: 'user' })
export class User {
  @PrimaryGeneratedColumn({ name: 'user_id' })
  id!: number;

  @ManyToMany(
    () => AccessScope,
    (accessScope) => accessScope.usersWithThatAccessScope,
  )
  @JoinTable({
    name: 'user_to_access_scope',
    joinColumn: { name: 'user_id' },
    inverseJoinColumn: { name: 'access_scope_id' },
  })
  accessScopes!: AccessScope[];

  @OneToMany(
    () => UserToAccessScope,
    (userToAccessScope) => userToAccessScope.user,
  )
  userToAccessScopeRelations!: UserToAccessScope[];
  
    // other fields
}
```

and access scope model:
```typescript
@Entity({ name: 'access_scope' })
export class AccessScope {
  @PrimaryGeneratedColumn({ name: 'access_scope_id' })
  id!: number;

  @ManyToMany(() => User, (user) => user.accessScopes)
  usersWithThatAccessScope!: User[];

  @OneToMany(
    () => UserToAccessScope,
    (userToAccessScope) => userToAccessScope.accessScope,
  )
  userToAccessScopeRelations!: UserToAccessScope[];

  // other fields
}
```

And model that connect both: 

```typescript
@Entity({ name: 'user_to_access_scope' })
export class UserToAccessScope {
  @ManyToOne(() => User, (user) => user.userToAccessScopeRelations, {
    nullable: false,
  })
  @JoinColumn({ name: 'user_id' })
  user!: User;

  @Column({
    name: 'user_id',
    primary: true,
    nullable: false,
  })
  userId!: number;

  @ManyToOne(
    () => AccessScope,
    (accessScope) => accessScope.userToAccessScopeRelations,
    { nullable: false },
  )
  @JoinColumn({ name: 'access_scope_id' })
  accessScope!: AccessScope;

  @Column({
    name: 'access_scope_id',
    primary: true,
    nullable: false,
  })
  accessScopeId!: number;
}
```

My code tries to insert accessScope, then user, then updates accessScope's field `usersWithThatAccessScope`.
Third step, as you can guess, fails. 

```typescript
const systemAdminScope = await this.accessScopeRepo.save({
  type: AccessScopeType.SYSTEM_ADMIN,
});
console.log('systemAdminScope: ', systemAdminScope);

const defaultUser = await this.userRepo.save({
  email: 'asd@asd.asd',
  lastName: 'Такой-тов',
  firstName: 'Такой-то',
  patronymic: 'Такой-тович',
  gender: 'male',
  password: 'asdasdasd',
});
console.log('defaultUser: ', defaultUser);

await this.accessScopeRepo.save({
  id: systemAdminScope.id,
  usersWithThatAccessScope: [defaultUser],
});
```

[solution in this example](https://github.com/typeorm/typeorm/issues/2121#issuecomment-788152519) does not help, because there mentioned not many-to-many, but many-to-one relation. I tried anyway, and it didn't help

output I get:

```
backend  | newEntity:  { type: 'superAdmin' }
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "access_scope"("type", "created_at", "updated_at") VALUES ($1, DEFAULT, DEFAULT) RETURNING "access_scope_id", "created_at", "updated_at" -- PARAMETERS: ["superAdmin"]
backend  | query: COMMIT
backend  | systemAdminScope:  {
backend  |   type: 'superAdmin',
backend  |   id: 26,
backend  |   createdAt: 2022-10-08T16:28:26.865Z,
backend  |   updatedAt: 2022-10-08T16:28:26.865Z
backend  | }
backend  | newEntity:  {
backend  |   email: 'asd@asd.asd',
backend  |   lastName: 'Такой-тов',
backend  |   firstName: 'Такой-то',
backend  |   patronymic: 'Такой-тович',
backend  |   gender: 'male',
backend  | }
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "user"("first_name", "last_name", "email", "salt", "password_hash", "patronymic", "gender", "phone", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, DEFAULT, DEFAULT, DEFAULT) RETURNING "user_id", "created_at", "updated_at" -- PARAMETERS: ["Такой-то","Такой-тов","asd@asd.asd","eaedd02b7a0b4e4505c35bcf92b8db2372e99b3e55324e481c2514ee49e46b2c575fa937d4fa4d06b0ed1cf8226f822fda277108a7d8859be2ecb477e5d8d180","74227546f2147f15953a47ef09688ced62a95d287bb563ecfd70ab949eec0008","Такой-тович","male"]
backend  | query: COMMIT
backend  | defaultUser:  {
backend  |   email: 'asd@asd.asd',
backend  |   lastName: 'Такой-тов',
backend  |   firstName: 'Такой-то',
backend  |   patronymic: 'Такой-тович',
backend  |   gender: 'male',
backend  |   phone: null,
backend  |   id: 12,
backend  |   createdAt: 2022-10-08T16:28:26.888Z,
backend  |   updatedAt: 2022-10-08T16:28:26.888Z
backend  | }
backend  | before repo.save UpdateEntity: {
backend  |   id: 26,
backend  |   usersWithThatAccessScope: [
backend  |     {
backend  |       email: 'asd@asd.asd',
backend  |       lastName: 'Такой-тов',
backend  |       firstName: 'Такой-то',
backend  |       patronymic: 'Такой-тович',
backend  |       gender: 'male',
backend  |       phone: null,
backend  |       id: 12,
backend  |       createdAt: 2022-10-08T16:28:26.888Z,
backend  |       updatedAt: 2022-10-08T16:28:26.888Z
backend  |     }
backend  |   ]
backend  | }
backend  | query: SELECT "AccessScope"."access_scope_id" AS "AccessScope_access_scope_id", "AccessScope"."type" AS "AccessScope_type", "AccessScope"."created_at" AS "AccessScope_created_at", "AccessScope"."updated_at" AS "AccessScope_updated_at" FROM "access_scope" "AccessScope" WHERE "AccessScope"."access_scope_id" IN ($1) -- PARAMETERS: [26]
backend  | query: SELECT "AccessScope_usersWithThatAccessScope_rid"."user_id" AS "user_id", "AccessScope_usersWithThatAccessScope_rid"."access_scope_id" AS "access_scope_id" FROM "user" "user" INNER JOIN "user_to_access_scope" "AccessScope_usersWithThatAccessScope_rid" ON ("AccessScope_usersWithThatAccessScope_rid"."access_scope_id" = $1 AND "AccessScope_usersWithThatAccessScope_rid"."user_id" = "user"."user_id") ORDER BY "AccessScope_usersWithThatAccessScope_rid"."user_id" ASC, "AccessScope_usersWithThatAccessScope_rid"."access_scope_id" ASC -- PARAMETERS: [26]
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
postgres | 2022-10-08 19:28:26.915 MSK [133] ERROR:  null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
postgres | 2022-10-08 19:28:26.915 MSK [133] DETAIL:  Failing row contains (null, null).
postgres | 2022-10-08 19:28:26.915 MSK [133] STATEMENT:  INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
backend  | query failed: INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
backend  | error: error: null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
backend  |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
backend  |     at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
backend  |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
backend  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
backend  |     at Socket.emit (node:events:527:28)
backend  |     at addChunk (node:internal/streams/readable:315:12)
backend  |     at readableAddChunk (node:internal/streams/readable:289:9)
backend  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
backend  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
backend  |   length: 232,
backend  |   severity: 'ERROR',
backend  |   code: '23502',
backend  |   detail: 'Failing row contains (null, null).',
backend  |   hint: undefined,
backend  |   position: undefined,
backend  |   internalPosition: undefined,
backend  |   internalQuery: undefined,
backend  |   where: undefined,
backend  |   schema: 'public',
backend  |   table: 'user_to_access_scope',
backend  |   column: 'user_id',
backend  |   dataType: undefined,
backend  |   constraint: undefined,
backend  |   file: 'execMain.c',
backend  |   line: '1883',
backend  |   routine: 'ExecConstraints'
backend  | }
backend  | query: ROLLBACK
backend  | 
backend  | /app/src/driver/postgres/PostgresQueryRunner.ts:299
backend  |             throw new QueryFailedError(query, parameters, err)
backend  |                   ^
backend  | QueryFailedError: null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
backend  |     at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
backend  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
backend  |     at InsertQueryBuilder.execute (/app/src/query-builder/InsertQueryBuilder.ts:161:33)
backend  |     at SubjectExecutor.executeInsertOperations (/app/src/persistence/SubjectExecutor.ts:428:42)
backend  |     at SubjectExecutor.execute (/app/src/persistence/SubjectExecutor.ts:137:9)
backend  |     at EntityPersistExecutor.execute (/app/src/persistence/EntityPersistExecutor.ts:194:21)
backend  |     at updateOneWithRelations (/app/src/tools/repo/updateOneWithRelations.ts:16:16)
backend  |     at AccessScopeRepo.updateOneWithRelations (/app/src/modules/infrastructure/repo/accessScope.repo.ts:33:12)
backend  |     at MockDataUseCase.fillDBScript (/app/src/mock/mockData.useCase.ts:50:5)
backend  |     at MockDataUseCase.executeMock (/app/src/mock/mockData.useCase.ts:27:5)
```
