### ISSUE TITLE
Error at startup in EntityMetadataValidator

### ISSUE THREAD

**Issue by jtremback** [typeorm/typeorm#3806]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.13`

**Steps to reproduce or a small repository showing the problem:**

I am getting this error when the server starts:

```typescript
(node:20074) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at new PreRegistration (/Users/jehan/foo/dist/entity/PreRegistration.js:15:25)
    at EntityMetadata.create (/Users/jehan/foo/node_modules/typeorm/metadata/EntityMetadata.js:236:19)
    at EntityMetadataValidator.validate (/Users/jehan/foo/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:97:45)
    at /Users/jehan/foo/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/jehan/foo/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:25)
    at Connection.buildMetadatas (/Users/jehan/foo/node_modules/typeorm/connection/Connection.js:478:33)
    at Connection.<anonymous> (/Users/jehan/foo/node_modules/typeorm/connection/Connection.js:129:30)
    at step (/Users/jehan/foo/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/jehan/foo/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/jehan/foo/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here is the entity that has the problem:

```typescript
@Entity()
export class PreRegistration {
  constructor(prr: PreRegReq, postcard_code: string, airtable_id: string) {
    this.name = prr.name;
    this.company = prr.company;
    this.neighborhood = prr.neighborhood;
    this.address_line1 = prr.address_line1;
    this.address_line2 = prr.address_line2;
    this.address_city = prr.address_city;
    this.address_state = prr.address_state;
    this.address_zip = prr.address_zip;
    this.address_country = prr.address_country;
    this.postcard_code = postcard_code;
    this.airtable_id = airtable_id;
    this.qualified = true;
  }

  @PrimaryGeneratedColumn("uuid")
  id!: string;

  @CreateDateColumn()
  createdAt!: string;

  @UpdateDateColumn()
  updatedAt!: string;

  @VersionColumn()
  numberOfUpdates!: string;

  @Column()
  neighborhood: string;

  @Column()
  name: string;

  @Column()
  company: string;

  @Column()
  address_line1: string;

  @Column()
  address_line2: string;

  @Column()
  address_city: string;

  @Column()
  address_state: string;

  @Column()
  address_zip: string;

  @Column()
  address_country: string;

  @Column()
  postcard_code: string;

  @Column()
  qualified: boolean;

  @Column()
  airtable_id: string;
}
```

**Comment by jtremback** [comment]
Doing this for now:

```

@Entity()
export class PreRegistration {
  conztructor(prr: PreRegReq, postcard_code: string, airtable_id: string) {
    this.name = prr.name;
    this.company = prr.company;
    this.neighborhood = prr.neighborhood;
    this.address_line1 = prr.address_line1;
    this.address_line2 = prr.address_line2;
    this.address_city = prr.address_city;
    this.address_state = prr.address_state;
    this.address_zip = prr.address_zip;
    this.address_country = prr.address_country;
    this.postcard_code = postcard_code;
    this.airtable_id = airtable_id;
    this.qualified = true;
  }

  @PrimaryGeneratedColumn("uuid")
  id!: string;

  @CreateDateColumn()
  createdAt!: string;

  @UpdateDateColumn()
  updatedAt!: string;

  @VersionColumn()
  numberOfUpdates!: string;

  @Column()
  neighborhood!: string;

  @Column()
  name!: string;

  @Column()
  company!: string;

  @Column()
  address_line1!: string;

  @Column()
  address_line2!: string;

  @Column()
  address_city!: string;

  @Column()
  address_state!: string;

  @Column()
  address_zip!: string;

  @Column()
  address_country!: string;

  @Column()
  postcard_code!: string;

  @Column()
  qualified!: boolean;

  @Column()
  airtable_id!: string;
}
```

**Comment by rustamwin** [comment]
Make sure the 1st argument is not undefined in the constructor.

**Comment by vlapo** [comment]
Hey @jtremback from [documentation](https://typeorm.io/#/entities/what-is-entity). 
> When using an entity constructor its arguments must be optional. Since ORM creates instances of entity classes when loading from the database, therefore it is not aware of your constructor arguments.
More info about this problem https://github.com/typeorm/typeorm/pull/1773
