### ISSUE TITLE
What is wrong with the parameters in my where clause for the QueryBuilder?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [typeorm/typeorm#3851]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Can someone explain to me what I am doing wrong when using the parameters for my where clause?

This next block gives me the error below it:

```ts
@EntityRepository(Something)
export class SomethingRepository extends Repository<Something>{
  
  findByUserAndSomethingById(userId: number, spotId: number){
    const thing = this.createQueryBuilder('something')
    .where('something.userId = :id', {id: userId})
    .andWhere('something.id = :id',{id: spotId}).getOne();
    return thing;
  }
}
```

```shell
QueryFailedError: column something.userid does not exist
```

This request gives me the right result.

```ts
@EntityRepository(Something)
export class SomethingRepository extends Repository<Something>{

  findByUserAndSomethingById(userId: number, spotId: number){
    const thing = this.createQueryBuilder('something')
    .where(`"something"."userId" = ${userId}`)
    .andWhere('something.id = :id',{id: spotId}).getOne();
    return thing;
  }
}
```

You can see my problem in isolation here [fabianmoronzirfas/typeorm-issue-qb](https://github.com/fabianmoronzirfas/typeorm-issue-qb)

P.S. I already asked this on [so](https://stackoverflow.com/questions/55240553/what-is-wrong-with-the-parameters-in-my-typeorm-where-clause-for-the-querybuilde) but the reaction time seems to be faster here.

**Comment by fabianmoronzirfas** [comment]
Okay I got the answer from so. I need to add quotation marks around the aliases. The example below is working.

```ts
@EntityRepository(Something)
export class SomethingRepository extends Repository<Something>{
  
  findByUserAndSomethingById(userId: number, spotId: number){
    const thing = this.createQueryBuilder('something')
    .where('"something"."userId" = :id', {id: userId})
    .andWhere('something.id = :id',{id: spotId}).getOne();
    return thing;
  }
}
```

Can someone explain the reason for that and why is that?

**Comment by fabianmoronzirfas** [comment]
I was able to fix this issue in isolation adding the quotation marks but not in my main repo.

**Comment by fabianmoronzirfas** [comment]
Is it possible that there is something changing the camelcase of the string that is being used with the paramters?

Error message is `'column bathingspot.userid does not exist'` the hint for that is `'Perhaps you meant to reference the column "bathingspot.userId"` 

It seems like the camelcase in the string where the parameters are applied is beeing "uncamelcased" somehow.

```plain
Failing query: SELECT "bathingspot"."id" AS "bathingspot_id", "bathingspot"."name" AS "bathingspot_name", "bathingspot"."isPublic" AS "bathingspot_isPublic", "bathingspot"."apiEndpoints" AS "bathingspot_apiEndpoints", "bathingspot"."state" AS "bathingspot_state", "bathingspot"."location" AS "bathingspot_location", "bathingspot"."latitde" AS "bathingspot_latitde", "bathingspot"."longitude" AS "bathingspot_longitude", "bathingspot"."elevation" AS "bathingspot_elevation", "bathingspot"."userId" AS "bathingspot_userId" FROM "bathingspot" "bathingspot" WHERE bathingspot.userId = $1 AND "bathingspot"."id" = $2
{ QueryFailedError: column bathingspot.userid does not exist
    at new QueryFailedError (/Users/icke/tmp/typeorm-issue-qb/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/icke/tmp/typeorm-issue-qb/src/driver/postgres/PostgresQueryRunner.ts:176:30)
    at Query.handleError (/Users/icke/tmp/typeorm-issue-qb/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/icke/tmp/typeorm-issue-qb/node_modules/pg/lib/client.js:183:17)
    at Connection.emit (events.js:197:13)
    at Connection.EventEmitter.emit (domain.js:439:20)
    at Socket.<anonymous> (/Users/icke/tmp/typeorm-issue-qb/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:439:20)
    at addChunk (_stream_readable.js:288:12)
  message: 'column bathingspot.userid does not exist',
  name: 'QueryFailedError',
  length: 182,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint:
   'Perhaps you meant to reference the column "bathingspot.userId".',
  position: '546',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn',
  query:
   'SELECT "bathingspot"."id" AS "bathingspot_id", "bathingspot"."name" AS "bathingspot_name", "bathingspot"."isPublic" AS "bathingspot_isPublic", "bathingspot"."apiEndpoints" AS "bathingspot_apiEndpoints", "bathingspot"."state" AS "bathingspot_state", "bathingspot"."location" AS "bathingspot_location", "bathingspot"."latitde" AS "bathingspot_latitde", "bathingspot"."longitude" AS "bathingspot_longitude", "bathingspot"."elevation" AS "bathingspot_elevation", "bathingspot"."userId" AS "bathingspot_userId" FROM "bathingspot" "bathingspot" WHERE bathingspot.userId = $1 AND "bathingspot"."id" = $2',
  parameters: [ 1, 1 ] }
```

**Comment by fabianmoronzirfas** [comment]
Okay. My bad. I did not load the relations right. The solution is the following query:

```ts
findByUserAndSomethingById(userId: number, spotId: number) {
    const thing = this.createQueryBuilder('something')
    .innerJoin('something.user', 'user')
      .where('user.id = :uid', { uid: userId })
      .andWhere('something.id = :sid', { sid: spotId }).getOne();
    return thing;
}
```
