### ISSUE TITLE
Cannot perform update query because update values are not defined.

### ISSUE THREAD

**Issue by aaroninaustin** [typeorm/typeorm#3869]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am getting an error when trying to save to the database. It looks like I'm just misunderstanding saving with a repository or perhaps how the promise works in this situation, but any help would be great. 

I am including a break down of all the files, sorry its long! 

Here is the error I'm seeing surfaced from my docker instance.
```shell
Error caught:  { UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.
experiments_ms_1  |     at new UpdateValuesMissingError (/experiments-service/src/error/UpdateValuesMissingError.ts:8:9)
experiments_ms_1  |     at UpdateQueryBuilder.createUpdateExpression (/experiments-service/src/query-builder/UpdateQueryBuilder.ts:456:19)
experiments_ms_1  |     at UpdateQueryBuilder.getQuery (/experiments-service/src/query-builder/UpdateQueryBuilder.ts:45:24)
experiments_ms_1  |     at UpdateQueryBuilder.QueryBuilder.getQueryAndParameters (/experiments-service/src/query-builder/QueryBuilder.ts:385:28)
experiments_ms_1  |     at UpdateQueryBuilder.<anonymous> (/experiments-service/src/query-builder/UpdateQueryBuilder.ts:82:44)
experiments_ms_1  |     at step (/experiments-service/node_modules/tslib/tslib.js:133:27)
experiments_ms_1  |     at Object.next (/experiments-service/node_modules/tslib/tslib.js:114:57)
experiments_ms_1  |     at /experiments-service/node_modules/tslib/tslib.js:107:75
experiments_ms_1  |     at new Promise (<anonymous>)
experiments_ms_1  |     at Object.__awaiter (/experiments-service/node_modules/tslib/tslib.js:103:16)
experiments_ms_1  |   name: 'UpdateValuesMissingError',
experiments_ms_1  |   message:
experiments_ms_1  |    'Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.' }
```

**Steps to reproduce:**

***Requirements: NodeJs/Express, TypeScript***

The following file is out basic file setup.

****/entity/Experiment.ts****
```ts 
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne, OneToMany, ManyToMany, JoinTable} from "typeorm";
import { Author } from "./Author";
import { Image } from "./Image";
import { Platform } from './Platform';
import { Variation } from "./Variation";

@Entity()
export class Experiment {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        nullable: true
      })
    testplan: string; 
    
    @Column({
        nullable: true
      })
    name: string;

    @Column({
        nullable: true
      })
    isLive: boolean;

    @ManyToOne(type => Author, author => author.experiments)
    author: Author;

    @ManyToOne(type => Platform, platform => platform.experiments)
    platform: Platform;

    @OneToMany(type => Image, image => image.experiment)
    images: Image[];

    @OneToMany(type => Variation, variation => variation.experiment)
    variations: Variation[];
}
```

****/entity/Variation.ts****
```ts 
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import { Experiment } from "./Experiment";

@Entity()
export class Variation {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    url: string;

    @ManyToOne(type => Experiment, experiment => experiment.variations)
    experiment: Experiment;
}
```
****/entity/Image.ts****
```ts
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import { Experiment } from "./Experiment";

@Entity()
export class Image {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    path: string;

    @ManyToOne(type => Experiment, experiment => experiment.images)
    experiment: Experiment;
}
```

****/entity/Author.ts****
```ts
import {Entity, PrimaryGeneratedColumn, Column, OneToMany, JoinColumn} from "typeorm";
import {Experiment} from "./Experiment";

@Entity()
export class Author {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    prefs: 'json';

    @OneToMany(type => Experiment, experiment => experiment.author)
    experiments: Experiment[];
}
```

****/entity/Platform.js****
```ts
import {Entity, PrimaryGeneratedColumn, Column, OneToMany, JoinColumn} from "typeorm";
import {Experiment} from "./Experiment";

@Entity()
export class Platform {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Experiment, experiment => experiment.platform)
    experiments: Experiment[];
}
```

****/index.ts****
```ts
import "reflect-metadata";
import * as express from "express";
import * as bodyParser from "body-parser";
import {Request, Response} from "express";
import {Routes} from "./routes";
import {createConnection} from "typeorm";

createConnection().then(async connection => {

const app = express();
app.use(bodyParser.json());

// register express routes from defined application routes
Routes.forEach(route => {
    (app as any)[route.method](route.route, (req: Request, res: Response, next: Function) => {
        const result = (new (route.controller as any))[route.action](req, res, next);
        if (result instanceof Promise) {
            result.then(result => result !== null && result !== undefined ? res.send(result) : undefined);

        } else if (result !== null && result !== undefined) {
            res.json(result);
        }
    });
});

// start express server
app.listen(3000);

console.log("Express server has started on port 3000. Open http://localhost:3000/health to see it running.");

}).catch(error => console.log("TypeORM connection error: ", error));
```

****/routes.ts****
```ts
import {UserController} from "./controller/UserController";
import {ExperimentController} from "./controller/ExperimentController";
import {HealthController} from "./controller/HealthController";

export const Routes = [{
    method: "post",
    route: "/experiments",
    controller: ExperimentController,
    action: "save"
}
```

****/controller/ExperimentController.ts****
```ts

import {createConnection, getManager} from "typeorm";
import {getRepository} from "typeorm";
import {NextFunction, Request, Response} from "express";
import {Experiment} from "../entity/Experiment";
import {Author} from "../entity/Author";
import {Image} from "../entity/Image";
import {User} from "../entity/User";
import {Variation} from "../entity/Variation";
import { Platform } from "../entity/Platform";

// ... Other functions ...
       async save(request: Request, response: Response, next: NextFunction) {

        const author = new Author();
        author.firstName = "Aaron";
        author.lastName = "Montana";
    
        const platform = new Platform();
        platform.name = "SaaS 1";
        
        const image = new Image();
        image.path = "/path/to/image.svg";

        const v1 = new Variation();
        v1.url = "http://example.com/path1";

        const v2 = new Variation();
        v2.url = "http://example.com/path2";
    
        const experiment = new Experiment();
        experiment.testplan = "https://link.to/document";
        experiment.name = 'Experiment 100';
        experiment.isLive = true;    
        experiment.author = author;
        experiment.platform = platform;
        experiment.images = [image];
        experiment.variations = [v1,v2];

        try{
           let savedExp =  await getManager().getRepository(Experiment).save(experiment);
            console.log("Post has been saved: ", experiment, savedExp);
            response.send(experiment);
        }catch(e){
            console.log('Error caught: ', e);
            response.send(e);
        }   
    }
```

**Thanks for taking a look :)**

**Comment by aaroninaustin** [comment]
I can't label this? But I think this falls into 'Needs Help'

**Comment by aaroninaustin** [comment]
Closing this one - I figured it out. Turns out I was missing the cascade option:

```
 @OneToMany(type => Variation, variation => variation.experiment, **{
        cascade: true,
    }**)
```

**Comment by tuliofaria** [comment]
Another source for the problem is sending primary keys in values, for example:
```
this.categoryRepository.update(input.id, {
      name: input.name,
      slug: input.slug
      // we cannot send id here
})
```

**Comment by totalolage** [comment]
I just had this and it was caused by setting `{update: false}` on a relation column (in my case it was `userId` which links a `profile` entity to the corresponding `user` entity)

**Comment by jagabs** [comment]
i have this issue in @next "typeorm": "^0.3.0-alpha.24"

OneToOne relationship
MaterialEntity.ts
```
@OneToOne(
    (type: any) => ProjectTransactionEntity,
    (projectTransactionEntity: ProjectTransactionEntity) =>
      projectTransactionEntity.material,
    {
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "RESTRICT",
    },
  )
  @JoinColumn({ name: "project_transaction_id" })
  projectTransaction: ProjectTransactionEntity;
```

projectTransactionEntity.ts
```
@OneToOne(
    (type: any) => MaterialEntity,
    (materialEntity: MaterialEntity) => materialEntity.projectTransaction,
    {
      onDelete: "RESTRICT",
      onUpdate: "RESTRICT",
      cascade: true,
    },
  )
  material: Promise<MaterialEntity> | MaterialEntity;
```

```
query: UPDATE `ledgerdb`.`material` SET `project_transaction_id` = ? WHERE `material_id` IN (37) -- PARAMETERS: [139]
query: ROLLBACK
{ UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.
```

but the update query is correct right why am i getting this error?

**Comment by fafamnzm** [comment]
@jagabas try saving with the different sequence! With one to one relation you should save the one with the join column last if you do not enable {cascade:true}
I think the problem is when we try adding the one with the joinColumn() first, the other one is not saved, therefore does not have an Id to fill the relation column.
At least this is how it works for me!

**Comment by CemYil03** [comment]
I am running into a similar issue, where `save` fails only, when I use `@JoinColumn` for renaming my columns.

"Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values."

When letting TypeORM name the columns by it self everything seems to work.

**Comment by Manivela** [comment]
I just spent a couple hours on this error
```
const conversation = await Conversation.find({ where: { id: conversationId } })
let newMessage = new Message()
newMessage.conversation = conversation
await newMessage.save();
```
in my case I was using `find` where I was supposed to use `findOne` so the conversation object ended up being an array. This is totally my bad but I might as well write it here in case somebody else makes the same mistake 😅

**Comment by alex6296** [comment]
I got this mistake by having a @oneToMany in a case where it should have been @manyToMany changing it to the correct decorator fixed it.

**Comment by tth37** [comment]
In my case I forgot to add @ JoinColumn at a @ OneToOne relation.

**Comment by Marrieta99** [comment]
I got this error because I was sending arrays directly in the constructor call instead of loading them into the object after initialization

**Comment by Sid-Turner-Ellis** [comment]
My issue seems to come from having two child entities with the same property but different property types: https://github.com/typeorm/typeorm/issues/9742

**Comment by Gabriel7L** [comment]
If anyone is stil having some issues like that, in my case i resolve that setting persistance to false in EntitySchema:

```typescript

export const EmployeesSchema = new EntitySchema<Employees>({
  name: 'employees',
  tableName: 'employees',
  target: Employees,
  columns: {
    ...BasicCollumnsSchema,
    dt_hiring: {
      type: 'date',
      nullable: true,
    },
    fiscal_wage: {
      type: 'decimal',
      precision: 10,
      scale: 2,
    },
    real_wage: {
      type: 'decimal',
      precision: 10,
      scale: 2,
    },
    position: {
      type: 'varchar',
      length: 100,
    },
    workload: {
      type: 'time',
      nullable: true,
    },
    id_person: {
      type: 'integer',
    },
  },
  relations: {
    person: {
      type: 'one-to-one',
      target: 'people',
      joinColumn: {
        name: 'id_person',
      },
      eager: true,
      persistence: false, // <= right here
    },
    attachments: {
      type: 'one-to-many',
      target: 'attachments',
      inverseSide: 'employee',
      eager: true, // i didn't set persistance false here because i don't update this relation
    },
    dependents: {
      type: 'one-to-many',
      target: 'dependents',
      inverseSide: 'employee',
      eager: true,
      persistence: false, // <= and here
      cascade: true,
    },
  },
});
```

**Comment by clintonb** [comment]
I don't understand the issue, nor do I have an example to share, but adding a `VirtualColumn` causes this error to appear when saving a model that has been updated.

**Comment by qtnx** [comment]
You may also forget to add ManyToOne in the relation table

Eg

```
// Should be
@OneToMany(() => ImageEntity, (image) => image.postId)
  images: ImageEntity[];

// Not
@OneToMany(() => ImageEntity, (image) => image.id)
  images: ImageEntity[];
```

Also, in `ImageEntity`

```
export class ImageEntity{
//....
// Remember to add this
@ManyToOne(() => PostEntity, (post) => post.images)
  postId: PostEntity;
}
```

I hope this will  be helpful for future googlers

Docs: https://orkhan.gitbook.io/typeorm/docs/many-to-one-one-to-many-relations

**Comment by devodii** [comment]
Well.. the error for me was that i wasn't creating proper joins for the relationships, i.e using the `@JoinColumn() ` decorator. ;)

**Comment by renolation** [comment]
i got this error when use One to One and use JoinTable instead of JoinColumn
