### ISSUE TITLE
autoSave does not work when calling repository.clear()

### ISSUE THREAD

**Issue by jacobg** [typeorm/typeorm#3895]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[X ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Calling `repository.clear()` with `autoSave: true` does not persist the change, i.e., in the current application lifecycle, the data is cleared, but when restarting the application, the data is still there.

@pleerock said in a slack chat:

> clear isn’t wrapped into transaction. You might want to create a github issue with a bug report.

So this is the bug report.

I was able to get it to autoSave by doing the following:
```
        await repository().manager.transaction(async manager => {
          await manager.createQueryBuilder().delete().from(entityClass).execute()
        })
```

I first tried:
```
        await repository().manager.transaction(async manager => {
          await manager.clear()
        })
```
but that caused the folliowing error:
```
EntityMetadataNotFoundError.js?064e:8 Uncaught (in promise) EntityMetadataNotFound: No metadata for "undefined" was found.
    at new EntityMetadataNotFoundError (webpack-internal:///./node_modules/typeorm/browser/error/EntityMetadataNotFoundError.js:12:28)
    at Connection.getMetadata (webpack-internal:///./node_modules/typeorm/browser/connection/Connection.js:344:19)
    at SqljsEntityManager.eval (webpack-internal:///./node_modules/typeorm/browser/entity-manager/EntityManager.js:490:52)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:117:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:98:53)
    at eval (webpack-internal:///./node_modules/tslib/tslib.es6.js:91:71)
    at new Promise (<anonymous>)
    at Module.__awaiter (webpack-internal:///./node_modules/tslib/tslib.es6.js:87:12)
    at SqljsEntityManager.EntityManager.clear (webpack-internal:///./node_modules/typeorm/browser/entity-manager/EntityManager.js:485:63)
```
I'm not sure if this last error is also a bug or a related bug; or whether it's something I'm doing wrong.

Also, that manager transaction can not be concurrently run on two different repositories at the same time. In such a case, an error occurs about a transaction already being open.

**Comment by nandomoreirame** [comment]
👀
