### ISSUE TITLE
Entity metadata not found.

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#39]
Hi, 

I have the following two classes with a M2M relationship.

**DatabaseConnectionDB.ts**
```
...
private connect() {

        const loggerOptions: LoggerOptions = {
            logger: (message: string, level: string) => console.log(level, message),
            logQueries: true,
            logFailedQueryError: true
        };

        const options: ConnectionOptions = {
            driver: {
                type: 'postgres', // specify driver type here.
                host: this.dbHost,
                port: this.dbPort,
                username: this.dbUserName,
                password: this.dbPassword,
                database: this.dbName
            },
            autoSchemaCreate: true,
            logging: loggerOptions,
            entities: [UserDB, OrganisationDB]
            // entityDirectories: [__dirname + '/model/**/{*.js}']
        };

        createConnection(options).then((connection: Connection) => {
            // at this point you are connected to the database, and you can
            // perform queries
            console.log('######### Connected to Database: ' + connection);
            this.connection = connection;
            this.isConnected = true;
        }).catch(error => console.log('Error during connection to the db: ', error));
    }
...
```
**UserDB.ts**
```
import 'reflect-metadata';
import {User} from '../../shared/model';
import {Table, PrimaryColumn, Column, JoinTable, ManyToMany} from 'typeorm';
import {UserGroupDB, OrganisationDB} from './';

@Table("USER")
export class UserDB {

    /**************************************************************
     * Instance variables.
     **************************************************************/

    @PrimaryColumn('int', {generated: true })
    id: number;

    @Column()
    username: string;

    @Column()
    password: string;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    email: string;

    @Column()
    phoneNumber: string;

    @ManyToMany(type => OrganisationDB, organisation => organisation.users)
    @JoinTable()
    organisations: OrganisationDB[];
}
```
**OrganisationDB.ts**
```
import 'reflect-metadata';
import {Table, PrimaryColumn, Column, JoinTable, ManyToMany, OneToMany, ManyToOne, JoinColumn} from 'typeorm';
import {UserDB} from './';

@Table('ORGANISATION')
export class OrganisationDB {

    @PrimaryColumn('int', {generated: true })
    id: number;

    // @Column('string', {name: 'ORGANISATION_NAME', length: '250'})
    @Column()
    organisationName: string;

    // @Column('string', {name: 'PRIMARY_CONTACT_NAME', length: '50'})
    @Column()
    primaryContactName: string;

    // @Column('string', {name: 'PRIMARY_EMAIL', length: '50'})
    @Column()
    primaryEmail: string;

    // @Column('string', {name: 'PRIMARY_PHONE', length: '50'})
    @Column()
    primaryPhone: string;

    // @Column('string', {name: 'SECONDARY_CONTACT_NAME', length: '50', nullable: true})
    @Column()
    secondaryContactName: string;

    // @Column('string', {name: 'SECONDARY_EMAIL', length: '100', nullable: true})
    @Column()
    secondaryEmail: string;

    // @Column('string', {name: 'SECONDARY_PHONE', length: '50', nullable: true})
    @Column()
    secondaryPhone: string;

    @ManyToOne(type => OrganisationDB, parentOrganisation => parentOrganisation.childOrganisations)
    parentOrganisation: OrganisationDB;

    @OneToMany(type => OrganisationDB, childOrganisations => childOrganisations.parentOrganisation)
    childOrganisations: OrganisationDB[];

    @ManyToMany(type => UserDB, user => user.organisations)
    users: UserDB[] = []; // we initialize array for convinience here
}
```
These two classes return the following error:
```
Error during connection to the db:  Error: Entity metadata for UserDB#organisations was not found.
    at entityMetadata.relations.forEach.relation (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:249:27)
    at PropertyMetadataArgsCollection.forEach (native)
    at entityMetadatas.forEach.entityMetadata (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:246:38)
    at TargetMetadataArgsCollection.forEach (native)
    at EntityMetadataBuilder.build (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:245:25)
    at EntityMetadataBuilder.buildFromMetadataArgsStorage (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:154:21)
    at Connection.buildMetadatas (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/connection/Connection.js:355:18)
    at Connection.<anonymous> (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/connection/Connection.js:121:18)
    at next (native)
    at fulfilled (/Users/jt/Documents/workspace/testproject/node_modules/typeorm/connection/Connection.js:4:58)
```

From what I can see the various fields are matching up as per the examples. Can you see an issue here?

JT

**Comment by pleerock** [comment]
Your imports looks strange: 

```typescript
import {UserGroupDB, OrganisationDB} from './';
import {UserDB} from './';
```

maybe issue there?

**Comment by paistipoikka** [comment]
OK, I was using an index.ts file to help simplify imports. If I import each class individually then it works.
