### ISSUE TITLE
MongoDB QueryBuilder

### ISSUE THREAD

**Issue by pairmix** [typeorm/typeorm#3906]
Hi there,
What QueryBuilder to use ?
I'd like to use repositories and custom repositories.
But i get the following error when i call queryBuilder from repository:
"Using Query Builder with MongoDB is not supported yet. Calling this method will return an error."

````
Error: Query Builder is not supported by MongoDB.                                                                                                  
    at MembreRepository.MongoRepository.createQueryBuilder (C:\Applications\Node\MongoDB\node_modules\typeorm\repository\MongoRepository.js:37:15) 
    at AuthService.<anonymous> (C:\Applications\Node\MongoDB\dist\modules\membre\services\AuthService.js:45:54)                                    
    at Generator.next (<anonymous>)                                                                                                                
    at C:\Applications\Node\MongoDB\dist\modules\membre\services\AuthService.js:13:71                                                              
    at new Promise (<anonymous>)                                                                                                                   
    at __awaiter (C:\Applications\Node\MongoDB\dist\modules\membre\services\AuthService.js:9:12)                                                   
    at AuthService.login (C:\Applications\Node\MongoDB\dist\modules\membre\services\AuthService.js:39:16)                                          
    at Membre_IdentificationController.login (C:\Applications\Node\MongoDB\dist\modules\membre\controllers\IdentificationController.js:23:28)      
    at ActionMetadata.callMethod (C:\Applications\Node\MongoDB\node_modules\routing-controllers\metadata\ActionMetadata.js:108:48)                 
    at C:\Applications\Node\MongoDB\node_modules\routing-controllers\RoutingControllers.js:92:140                                                  
    at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                  
````

But it seems querybuilder from connection and/or entitymanager is ok.

My custom repository:
````
import { Service, Container } from "typedi";
import { MongoRepository, EntityRepository } from "typeorm";
import { Membre } from "../entity/Membre";

// create custom Repository class
@Service()
@EntityRepository(Membre)
export class MembreRepository extends MongoRepository<Membre>
{
....
}
````

**Comment by qianlizhe** [comment]
Hi，did you solve this problem later? I have encountered this problem now, but found no solution

**Comment by pairmix** [comment]
No, i deleted all my custom repositories.
Now i'm using only services.
Regards

**Comment by qianlizhe** [comment]
> No, i deleted all my custom repositories.
> Now i'm using only services.
> Regards

Okay, I can only use the service.
Hope someone can fix this problem.
Thank you for your reply

**Comment by equaliser0** [comment]
+1
