### ISSUE TITLE
Attempting to save Tree('closure-table') entity through entity with ManyToOne using cascade: true fails.

### ISSUE THREAD

**Issue by c-orter** [typeorm/typeorm#3917]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When I try to run the following code using the entities provided below the process fails with the error shown. The project was created with the typeorm-cli and the only settings I changed in the ormconfig.json were username and password. 

It should be noted too that this works from the other direction (ie. setting user.folder and inserting).

### Error
```
Inserting a new user into the database...
User {}
{ QueryFailedError: duplicate key value violates unique constraint "PK_117e57e38a6cabe49d52592c939"
    at new QueryFailedError (/home/carter/Work/minimal/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/home/carter/Work/minimal/src/driver/postgres/PostgresQueryRunner.ts:176:30)
    at Query.handleError (/home/carter/Work/minimal/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/home/carter/Work/minimal/node_modules/pg/lib/client.js:183:17)
    at Connection.emit (events.js:197:13)
    at Connection.EventEmitter.emit (domain.js:481:20)
    at Socket.<anonymous> (/home/carter/Work/minimal/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:288:12)
  message:
   'duplicate key value violates unique constraint "PK_117e57e38a6cabe49d52592c939"',
  name: 'QueryFailedError',
  length: 254,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id_ancestor, id_descendant)=(1, 1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'user_closure',
  column: undefined,
  dataType: undefined,
  constraint: 'PK_117e57e38a6cabe49d52592c939',
  file: 'nbtinsert.c',
  line: '434',
  routine: '_bt_check_unique',
  query:
   'INSERT INTO "user_closure" ("id_ancestor", "id_descendant") SELECT "id_ancestor", $1 FROM "user_closure" WHERE "id_descendant" = $2',
  parameters: [ 1, 1 ] }
```

### Entity
```typescript
import {Entity, PrimaryGeneratedColumn, Column, Tree, TreeChildren, TreeParent, BaseEntity, ManyToOne, OneToMany} from "typeorm";

@Entity()
export class UserFolder extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @OneToMany(type => User, user => user.folder, { cascade: ['insert'] })
    users: User[];
}

@Entity()
@Tree('closure-table')
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @TreeParent()
    parent: User;

    @TreeChildren({ cascade: true })
    children: User[];

    @Column()
    age: number;

    @ManyToOne(type => UserFolder, userFolder => userFolder.users, { cascade: true })
    folder: UserFolder;

}
```

### Index
```typescript
import "reflect-metadata";
import {createConnection} from "typeorm";
import {User, UserFolder} from "./entity/User";

createConnection().then(async connection => {

    await connection.dropDatabase();
    await connection.synchronize();

    console.log("Inserting a new user into the database...");
    const folder = new UserFolder();
    const user = new User();
    console.log(user);
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;
    user.children = new Array(10).fill(1).map(() => {
        const user = new User();
        user.firstName = Math.random().toString();
        user.lastName = Math.random().toString();
        user.age = Math.floor(Math.random() * 50);
        return user;
    });

    folder.users = [user];

    await folder.save();

    console.log("Saved a new user with id: " + user.id);

    console.log("Loading users from the database...");
    const users = await connection.manager.find(User);
    console.log("Loaded users: ", users);

    console.log("Here you can setup and run express/koa/any other framework.");

}).catch(error => console.log(error));

```

From what I can tell the issue originates in the [ClosureSubjectExecutor.ts](https://github.com/typeorm/typeorm/blob/master/src/persistence/tree/ClosureSubjectExecutor.ts#L63) because a second insert query is run.

P.S. Loving the project!

**Comment by GamerGirlandCo** [comment]
did you ever figure this out?
