### ISSUE TITLE
createConnection TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by vrondelli** [typeorm/typeorm#3976]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```@Entity()
export class Media {
  @ObjectIdColumn()
  public id: ObjectID;

  @Column()
  public instagramId: string;

  @Column({ enum: ['image', 'video']})
  public type: 'image' | 'video';

  @OneToOne(type => InstaLink, link => link.media)
  public link: InstaLink;

  @Column()
  public caption: string;

  @Column()
  public instagramCreatedTime: number;

  @Column()
  public images: {
    thumbnail?: IMediaImage;
    lowResolution?: IMediaImage;
    standardResolution?: IMediaImage;
  };

  @ManyToOne(type => User, user => user.media)
  public user: User;

  constructor(instagramMedia: InstagramMedia, user: User) {
    this.type = instagramMedia.type;
    this.instagramId = instagramMedia.id;
    this.caption = instagramMedia.caption.text;
    this.images = {
      thumbnail: {
        url: instagramMedia.images.thumbnail.url,
        height: instagramMedia.images.thumbnail.height,
        width: instagramMedia.images.thumbnail.width
      },
      lowResolution: {
        url: instagramMedia.images.low_resolution.url,
        height: instagramMedia.images.low_resolution.height,
        width: instagramMedia.images.low_resolution.width
      },
      standardResolution: {
        url: instagramMedia.images.standard_resolution.url,
        height: instagramMedia.images.standard_resolution.height,
        width: instagramMedia.images.standard_resolution.width
      }
    };
    this.user = user;
    this.instagramCreatedTime = parseInt(instagramMedia.created_time);
  }
}
```

I have this entity and when I'm creating connection i get this error : 

```
TypeError: Cannot read property 'type' of undefined
    at new Media (/home/vrondelli/projects/tokilabs/livebio/service/src/models/media.ts:39:32)
    at EntityMetadata.create (/home/vrondelli/projects/tokilabs/livebio/service/src/metadata/EntityMetadata.ts:499:19)
    at EntityMetadataValidator.validate (/home/vrondelli/projects/tokilabs/livebio/service/src/metadata-builder/EntityMetadataValidator.ts:111:47)
    at /home/vrondelli/projects/tokilabs/livebio/service/src/metadata-builder/EntityMetadataValidator.ts:44:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/vrondelli/projects/tokilabs/livebio/service/src/metadata-builder/EntityMetadataValidator.ts:44:25)
    at Connection.buildMetadatas (/home/vrondelli/projects/tokilabs/livebio/service/src/connection/Connection.ts:505:33)
    at Connection.<anonymous> (/home/vrondelli/projects/tokilabs/livebio/service/src/connection/Connection.ts:189:18)
    at step (/home/vrondelli/projects/tokilabs/livebio/service/node_modules/typeorm/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/vrondelli/projects/tokilabs/livebio/service/node_modules/typeorm/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/vrondelli/projects/tokilabs/livebio/service/node_modules/typeorm/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by deep-techuz** [comment]
Show some more code which is related to your DB Connection

**Comment by deep-techuz** [comment]
well I got your error it says you are trying to user type of undefined which probably throwing from that
`this.type = instagramMedia.type;`

NOTE: Please do not post issues outside of typeorm's scope.

**Comment by vrondelli** [comment]
Sorry if got wrong, but this is happening when connection, is trying to build metadatas, `at Connection.buildMetadatas (/home/vrondelli/projects/tokilabs/livebio/service/src/connection/Connection.ts:505:33)`,  not when I'm instantiating my media class in some part of my code, I've done some tests and I saw that the entire class `this` is undefined, I think for some reason, the `entityMetadat` a for media wasn't properly built

**Comment by vlapo** [comment]
Hey @vrondelli. From docs https://typeorm.io/#/entities.
> When using an entity constructor its arguments must be optional. Since ORM creates instances of entity classes when loading from the database, therefore it is not aware of your constructor arguments.

So mark your constructor arguments as optional and handle undefined values.
```
constructor(instagramMedia?: InstagramMedia, user?: User) {
```

Warning: This behavior is subject to change in next versions as it is discussed in https://github.com/typeorm/typeorm/issues/1772, https://github.com/typeorm/typeorm/pull/3845 and also https://github.com/typeorm/typeorm/pull/3910.
