### ISSUE TITLE
Entity "Photo" does not have a primary column.

### ISSUE THREAD

**Issue by aloysius-tim** [typeorm/typeorm#406]
Hey Guys,

Thanks for providing this amazing ORM ! Looking forward to use it full potential.

But for the moment I'm stuck on setting it up... Indeed, I'm for the moment just following the documentation trying to create the dataTable Photo:

`import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Photo {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    length: 500
  })
  name: string;

  @Column("text")
  description: string;

  @Column()
  fileName: string;

  @Column("int")
  views: number;

  @Column()
  isPublished: boolean;
}`

And creating the connection:

`createConnection({
  driver: {
    type: "mysql",
    host: "localhost",
    port: 8889,
    username: "root",
    password: "root",
    database: "hashbot"
  },
  entities: [
    Photo
  ],
  autoSchemaSync: true,
}).then(connection => {
  // here you can start to work with your entities
}).catch(error => console.log(error));`

But it's not working as it should, I receive this error:

`From previous event:
    at __awaiter (/Users/Aloysius_tim/Desktop/Hashbot/Hashbot_BackEnd/node_modules/typeorm/connection/ConnectionManager.js:3:12)
    at ConnectionManager.createAndConnect (/Users/Aloysius_tim/Desktop/Hashbot/Hashbot_BackEnd/node_modules/typeorm/connection/ConnectionManager.js:141:16)
    at createConnection (/Users/Aloysius_tim/Desktop/Hashbot/Hashbot_BackEnd/node_modules/typeorm/index.js:119:35)
    at Object.<anonymous> (/Users/Aloysius_tim/Desktop/Hashbot/Hashbot_BackEnd/dist/index.js:56:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  name: 'MissingPrimaryColumnError',
  message: 'Entity "Photo" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.' }
`

The PrimaryColumn decorator is already set! I've tried @PrimaryGeneratedColumn also but without any success.

I've added typeORM to a nodeJS project, don't think so but maybe my settings are not good and decorators not understood correctly ?

Thanks for your time,
Tim

**Comment by aloysius-tim** [comment]
Figure it out ! 

CompileOnSave option in TSConfig should be set to true.

`{
  "compileOnSave": true,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016"
    ]
  }
}
`
