### ISSUE TITLE
Index keys empty with @TableInheritance, mongoDB

### ISSUE THREAD

**Issue by Nooka10** [typeorm/typeorm#4126]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I'm trying to create a single-table-inheritance between _user_, _physio_ and _patient_ as explained [here](https://typeorm.io/#/entity-inheritance/single-table-inheritance) but I get always this error:

```
{ MongoError: Index keys cannot be empty.
    at Connection.<anonymous> (/BackEnd/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:197:13)
    at processMessage (/BackEnd/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/BackEnd/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  ok: 0,
  errmsg: 'Index keys cannot be empty.',
  code: 67,
  codeName: 'CannotCreateIndex',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

Here is my code:

```
@Entity({ name: 'user' })
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
export abstract class UserModel {
  @ObjectIdColumn({ readonly: true })
  id: ObjectID;

  @ColumnORM({ readonly: true })
  @IsEmail()
  email: string;
......
}

@ChildEntity()
export class PhysioModel extends UserModel {
  @OneToMany(type => PatientModel, patient => patient.linkedPhysio, { nullable: true })
  linkedPatients: PatientModel[];

 ......
}

@ChildEntity()
export class PatientModel extends UserModel {
  @ColumnORM({ nullable: true })
  @IsOptional()
  @IsDate()
  surgeryDate?: Date;

  @ManyToMany(type => PhysioModel, physio => physio.linkedPatients, { nullable: true })
  @IsOptional()
  linkedPhysio?: PhysioModel;

......
}
```

**Comment by ramimanna** [comment]
I'm having the same issue! Any updates on this?

**Comment by danilapelko** [comment]
Today, after a couple of hours of debugging, I found that the error occurred due to an empty columnNamesWithOrderingMap parameter in [MongoSchemaBuilder:50](https://github.com/typeorm/typeorm/blob/685d76b20464388c6f86c7d268770577452124b6/src/schema-builder/MongoSchemaBuilder.ts#L50). Which cannot be filled for @TableInheritance index in [IndexMetadata:198](https://github.com/typeorm/typeorm/blob/master/src/metadata/IndexMetadata.ts#L198) due to the empty givenColumnNames not represented in [EntityMetadataBuilder:673](https://github.com/typeorm/typeorm/blob/master/src/metadata-builder/EntityMetadataBuilder.ts#L673)

How to avoid this error?

**Comment by GerkinDev** [comment]
Hey there,

Same issue here. This bug seems to be kind of related to #4267. I bypassed the error following the solution given in the related issue. For reference, make sure that your connection's `synchronize` option is falsy.
