### ISSUE TITLE
Typeorm + serverless-offline failing (mac os, win, linux) with cannot find module 'app-root-path'

### ISSUE THREAD

**Issue by rahabash** [typeorm/typeorm#4163]
I've tried this now on mac os, windows, and linux and all are throwing the same issue.

If you create a serverless aws-nodejs-typescript project, add the serverless-offline plugin, and typeorm (w/ mysql driver), when you try to test locally using serverless-offline, the following error pops up:

Serverless: GET /hello (λ: hello)
{ Error: Cannot find module 'C:\Users\kuba\fortis\testservice\node_modules\app-root-path'
at webpackEmptyContext (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\platform sync:2:1)
at Function../node_modules/typeorm/platform/PlatformTools.js.PlatformTools.load (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\platform\PlatformTools.js:112:24)
at ConnectionOptionsReader.get [as baseDirectory] (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:213:1)
at ConnectionOptionsReader.get [as baseFilePath] (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:201:1)
at ConnectionOptionsReader. (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:96:1)
at step (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:97:1)
at Object.next (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:78:45)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:71:1
at new Promise ()
at Module.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:67:1)
at ConnectionOptionsReader../node_modules/typeorm/connection/ConnectionOptionsReader.js.ConnectionOptionsReader.load (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:88:1)
at ConnectionOptionsReader. (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:30:1)
at step (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:97:1)
at Object.next (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:78:45)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:71:1
at new Promise ()
at Module.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:67:1)
at ConnectionOptionsReader../node_modules/typeorm/connection/ConnectionOptionsReader.js.ConnectionOptionsReader.all (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:26:1)
at ConnectionOptionsReader. (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:49:1)
at step (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:97:1)
at Object.next (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:78:45)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:71:1
at new Promise ()
at Module.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:67:1)
at ConnectionOptionsReader../node_modules/typeorm/connection/ConnectionOptionsReader.js.ConnectionOptionsReader.get (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\connection\ConnectionOptionsReader.js:45:1)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\index.js:163:1
at step (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:97:1)
at Object.next (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:78:45)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:71:1
at new Promise ()
at Module.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:67:1)
at getConnectionOptions (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\index.js:161:1)
at Object. (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\index.js:192:1)
at step (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:97:1)
at Object.next (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:78:45)
at C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:71:1
at new Promise ()
at Module.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\tslib\tslib.es6.js:67:1)
at Object.createConnection (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\node_modules\typeorm\index.js:183:1)
at Object../handler.ts (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\handler.ts:7:1)
at webpack_require (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\webpack\bootstrap:19:1)
at ./handler.ts.__awaiter (C:\Users\kuba\fortis\testservice.webpack\service\webpack:\webpack\bootstrap:83:1)
at Object. (C:\Users\kuba\fortis\testservice.webpack\service\handler.js:87:10)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.createHandler (C:\Users\kuba\fortis\testservice\node_modules\serverless-offline\src\functionHelper.js:192:17)
at handler (C:\Users\kuba\fortis\testservice\node_modules\serverless-offline\src\index.js:624:40)
at Object.internals.handler (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\handler.js:101:51)
at request._protect.run (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\handler.js:32:23)
at module.exports.internals.Protect.internals.Protect.run (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\protect.js:60:12)
at exports.execute (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\handler.js:26:22)
at each (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:401:16)
at iterate (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:36:13)
at done (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:28:25)
at module.exports.internals.Auth.internals.Auth._authenticate (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\auth.js:222:16)
at internals.Auth.authenticate (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\auth.js:197:17)
at each (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:401:16)
at iterate (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:36:13)
at done (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:28:25)
at internals.state (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\route.js:292:16)
at each (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:401:16)
at iterate (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:36:13)
at Object.exports.serial (C:\Users\kuba\fortis\testservice\node_modules\items\lib\index.js:39:9)
at internals.Request._lifecycle (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:404:18)
at internals.Request._match (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:381:17)
at internals.Request._execute (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\request.js:335:21)
at Domain.request._protect.enter (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\connection.js:275:25)
at Domain.run (domain.js:342:14)
at module.exports.internals.Protect.internals.Protect.enter (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\protect.js:76:17)
at Server. (C:\Users\kuba\fortis\testservice\node_modules\hapi\lib\connection.js:273:30)
at Server.emit (events.js:189:13)
at Server.EventEmitter.emit (domain.js:441:20)
at parserOnIncoming (_http_server.js:676:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17) code: 'MODULE_NOT_FOUND' }

Now in node-modules the app-root-path package is there. Just to be sure I've reinstalled all node modules in both the typeorm folder and root project but no matter the case if I run the serverless offline start cmd it will throw the above error once I hit the endpoint.

If i run the code via VS Code debugger w/ an entry point such as index.ts everything executes fine and inserts the new user into the table, but running it from the handler w/ serverless-offline I instead get the app module not found error.

Any help would be appreciated!

**Comment by Kononnable** [comment]
Please format your code correctly and prepare a reproduction repo. It's look like something is wrong with your webpack configuration, but nobody will even be able to guess how does it look like without reproduction data.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
