### ISSUE TITLE
PostgreSQL Partial Index creation is weird/ugly/unclear/hard to make it work

### ISSUE THREAD

**Issue by constb** [typeorm/typeorm#4171]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I'm having this entity that indexes only unapproved entries:

```ts
@Entity()
export class Test {
    @PrimaryGeneratedColumn()
    public id?: number;

    @Column()
    @Index({ where: "approvedBy IS NULL" })
    public theKey?: string;

    @Column()
    public approvedBy?: string;
}
```

Trying to sync, I get this error:

```
query: CREATE TABLE "test" ("id" SERIAL NOT NULL, "theKey" character varying NOT NULL, "approvedBy" character varying NOT NULL, CONSTRAINT "PK_5417af0062cf987495b611b59c7" PRIMARY KEY ("id"))
query: CREATE INDEX "IDX_ff7409e54a06ac21a0ca142a9b" ON "test" ("theKey") WHERE approvedBy IS NULL
query failed: CREATE INDEX "IDX_ff7409e54a06ac21a0ca142a9b" ON "test" ("theKey") WHERE approvedBy IS NULL
error: error: column "approvedby" does not exist
    at Connection.parseE (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

Error details:

```
{
  name: 'error',
  length: 172,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "test.approvedBy".',
  position: '74',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn'
}
```

The lower-cased column `approvedby` here is a distraction. I enabled logging and it seems that query contains correct name.

Let's try to explicitly specify table name as `@Index({ where: "test.approvedBy IS NULL" })` as hint suggests:

```
query: CREATE TABLE "test" ("id" SERIAL NOT NULL, "theKey" character varying NOT NULL, "approvedBy" character varying NOT NULL, CONSTRAINT "PK_5417af0062cf987495b611b59c7" PRIMARY KEY ("id"))
query: CREATE INDEX "IDX_24a5f148f75962c2c84eefe956" ON "test" ("theKey") WHERE test.approvedBy IS NULL
query failed: CREATE INDEX "IDX_24a5f148f75962c2c84eefe956" ON "test" ("theKey") WHERE test.approvedBy IS NULL
error: error: column test.approvedby does not exist
    at Connection.parseE (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/Users/constb/PhpstormProjects/finso-crypto-api/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

And also:

```
{
  name: 'error',
  length: 175,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "test.approvedBy".',
  position: '74',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn'
}
```

Now this is proper weird, right? After a couple hours of tinkering I managed to make it work, but the solution is ugly, unclear from the docs and it all just was kind of hard to make it work:

```ts
@Entity()
export class Test {
    @PrimaryGeneratedColumn()
    public id?: number;

    @Column()
    @Index({ where: "\"approvedBy\" IS NULL" })
    public theKey?: string;

    @Column()
    public approvedBy?: string;
}
```

Am I right? :)

**Comment by ShaharHD** [comment]
why not use

```ts
@Entity()
export class Test {
    @PrimaryGeneratedColumn()
    public id?: number;

    @Column()
    @Index({ where: '"approvedBy" IS NULL' })
    public theKey?: string;

    @Column()
    public approvedBy?: string;
}
```

**Comment by gaurav-** [comment]
@constb I don't think this is a `typeorm` issue. That's just how Postgresql behaves when you specify a mixed-case name (column name here) without double-quotes.

**Comment by constb** [comment]
you know, I actually sort of reexperienced this today, when I was trying to set column default value to an empty string in a migration, mysql this time.

`default: ''` is logical but doesn't really work. you get syntax error. the way that works is `default: '""'`. also – weird. I kinda understand the rationale behind this, trying to give developers an instrument that's a little more universal and less opinionated about things. but at least, please document those corner cases. it takes hours each time to figure out something that should just work, and it just doesn't.

**Comment by AlexMesser** [comment]
`where` parameter accepts any string and there is no way to determine is it a column name, a function or a something else. So, you must properly escape column names yourself.
