### ISSUE TITLE
Weird issues with transaction and onConflict

### ISSUE THREAD

**Issue by rhlsthrm** [typeorm/typeorm#4181]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm defining a `set` function for my app here, it sets a string key and JSON value into a Postgres database with an "upsert":

```ts
async set(pairs: { key: string; value: any }[]): Promise<any> {
  const connection = this.connectionMgr.get();
  const queryRunner = connection.createQueryRunner();
  await queryRunner.connect();
  await queryRunner.startTransaction();

  try {
    const queryBuilder = connection.createQueryBuilder(queryRunner);
    for (const pair of pairs) {
      const storeKey = `${this.storeServiceKey}_${pair.key}`;
      // wrap value so its always JSON
      const storeValue = {
        [pair.key]: JSON.parse(JSON.stringify(pair.value))
      };
      await queryBuilder
        .insert()
        .into(NodeEntity)
        .values({
          key: storeKey,
          value: storeValue
        })
        .onConflict(`("key") DO UPDATE SET "value" = :value`)
        .setParameter("value", storeValue)
        .execute();
    }
    await queryRunner.commitTransaction();
  } catch (e) {
    console.error("Error saving to database: ", e);
    await queryRunner.rollbackTransaction();
  } finally {
    await queryRunner.release();
  }
}
```

I keep hitting an error saying:
```
error: { error: column "value" is of type json but expression is of type character varying
    at Connection.parseE (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:439:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
``` 

I'm sure I'm passing everything in as JSON (you can see above that I forcibly wrap the values to turn them into JSON).

I see some other weird logging here:

```
Error saving to database:  { QueryFailedError: column "value" is of type json but expression is of type character varying
    at new QueryFailedError (/Users/rahul/Desktop/connext/connext/monorepo/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/rahul/Desktop/connext/connext/monorepo/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/client.js:183:17)
    at Connection.emit (events.js:197:13)
    at Connection.EventEmitter.emit (domain.js:439:20)
    at Socket.<anonymous> (/Users/rahul/Desktop/connext/connext/monorepo/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:439:20)
    at addChunk (_stream_readable.js:288:12)
  message:
   'column "value" is of type json but expression is of type character varying',
  name: 'QueryFailedError',
  length: 200,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You will need to rewrite or cast the expression.',
  position: '96',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '540',
  routine: 'transformAssignedExpr',
  query:
   'INSERT INTO "node"("key", "value") VALUES ($3, $4) ON CONFLICT ("key") DO UPDATE SET "value" = $3',
  parameters:
   [ 'tttBotStore1_store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/ownersHashToMultisigAddress/0x3d9bcca75536bb2172b7dce8aa4fa9db7658963e9ffc7b235b47dec31bd0c2e9',
     '{"store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/ownersHashToMultisigAddress/0x3d9bcca75536bb2172b7dce8aa4fa9db7658963e9ffc7b235b47dec31bd0c2e9":"0x139A07598fB35265836c107DdEB42455f0035182"}',
     { 'store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/ownersHashToMultisigAddress/0x3d9bcca75536bb2172b7dce8aa4fa9db7658963e9ffc7b235b47dec31bd0c2e9': '0x139A07598fB35265836c107DdEB42455f0035182' } ] }
```

I'm unsure why the parameter values are being bumped to `$3` and `$4` instead of using the `$1` and `$2` values.

**Comment by Kononnable** [comment]
If you remove the transaction does typeorm generates different query? I don't see how this could be related to transactions.

**Comment by rhlsthrm** [comment]
I worked around this issue so it's not relevant anymore. If I encounter again I'll reopen.
