### ISSUE TITLE
Multi Foreign Key Postgres

### ISSUE THREAD

**Issue by kferrone** [typeorm/typeorm#4206]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

[Here is our repository showing off the issue](https://github.com/Akirix/typeorm-lab).

To run the repo you will need a postgres server to test on. The command to run is: 

```sh
npm install
```
then
```sh
npm run start:multiKey
```

I have a few other scenarios I was testing as well. There are a few model folders in the model folder, the one to check out is the multiKey model here: [multiKey model](https://github.com/Akirix/typeorm-lab/tree/master/src/model/multiKey)

  I have confirmed that SQLJS and SQLITE will indeed generate a table with a foreign key referencing more than once column. However if you sync your model to postgres then the mapping to the foreign key fails with the error below: 

```
Setting the orm client now
{ QueryFailedError: foreign key constraint "FK_0f9bc59a1f7a61702361dc653a9" cannot be implemented
    at new QueryFailedError (/Users/kelly/git/akx-uber-server/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/kelly/git/akx-uber-server/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/kelly/git/akx-uber-server/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/kelly/git/akx-uber-server/node_modules/pg/lib/client.js:194:17)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (/Users/kelly/git/akx-uber-server/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
  message:
   'foreign key constraint "FK_0f9bc59a1f7a61702361dc653a9" cannot be implemented',
  name: 'QueryFailedError',
  length: 244,
  severity: 'ERROR',
  code: '42804',
  detail:
   'Key columns "contact_id" and "id" are of incompatible types: character varying and integer.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '7292',
  routine: 'ATAddForeignKeyConstraint',
  query:
   'ALTER TABLE "public"."contact_detail" ADD CONSTRAINT "FK_0f9bc59a1f7a61702361dc653a9" FOREIGN KEY ("contact_id", "contact_id") REFERENCES "public"."contact"("id","type") ON DELETE NO ACTION ON UPDATE NO ACTION',
  parameters: [] }
```

From the error above you can see that with postgres, the foreign key tries to map `(contact_id,contact_id) to (id,type)` instead of `(contact_id,contact_type) to (id,type)` like SQLJS and SQLITE.

**Comment by kferrone** [comment]
Actually I am wrong about SQLJS and SQLITE. They just seem to be working but they are creating the same erroneous relationship but not complaining whereas postgres complains.

**Comment by kferrone** [comment]
figured it out . . . 

I need to mention the reference column as well: 

```typescript
@JoinColumn([
        {
            name: 'contact_id',
            referencedColumnName: 'id'
        },
        {
            name: 'contact_type',
            referencedColumnName: 'type'
        }
])
```
