### ISSUE TITLE
Query builder does not work with prototype-less (Object.create(null)) objects

### ISSUE THREAD

**Issue by imdoroshenko** [typeorm/typeorm#4218]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

I am building an application using [graphql-js](https://github.com/graphql/graphql-js) which uses prototype-less (`Object.create(null)`) objects for `args` in resolver functions. [Link](https://github.com/graphql/express-graphql/issues/177#issuecomment-273955947).
QueryBuilder does not recognize prototype-less objects when they are used as `InsertValues` or `UpdatesValues`.

**Example:**
```ts
interface IArgs {
    email: string
    first_name: string
    last_name: string
}

export const createUser: GraphQLFieldResolver<null, null, { user: IArgs }> =
async (_, { user }) => {
  console.log(user);
  await getRepository(User).insert(user);
}
```

```
[Object: null prototype] {
  email: 'test@email.com',
  first_name: 'John Doe'
}
InsertValuesMissingError: Cannot perform insert query because values are not defined. Call "qb.values(...)" method to specify inserted values.
    at new InsertValuesMissingError (/usr/src/app/src/error/InsertValuesMissingError.ts:8:9)
    at InsertQueryBuilder.getValueSets (/usr/src/app/src/query-builder/InsertQueryBuilder.ts:558:15)
    at InsertQueryBuilder.<anonymous> (/usr/src/app/src/query-builder/InsertQueryBuilder.ts:57:53)
    at step (/usr/src/app/node_modules/tslib/tslib.js:133:27)
    at Object.next (/usr/src/app/node_modules/tslib/tslib.js:114:57)
    at /usr/src/app/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:103:16)
    at InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:41:24)
    at EntityManager.<anonymous> (/usr/src/app/src/entity-manager/EntityManager.ts:488:14)
```

However, if you modify the code in any of the following ways, it will work just fine. 

```ts
await getRepository(User).insert({...user});
```

```ts
await getRepository(User).insert(Object.setPrototypeOf(user, Object));
```

```
query: INSERT INTO "app_user"("email", "first_name") VALUES ($1, $2) RETURNING "user_id" -- PARAMETERS: ["test@email.com","John Doe"]
```

**Solution:**
TypeORM code should be updated to consider such cases. e.g:

Such code:
```ts
// query-builder/InsertQueryBuilder.ts:558
/**
 * Gets array of values need to be inserted into the target table.
 */
protected getValueSets(): ObjectLiteral[] {
    if (this.expressionMap.valuesSet instanceof Array && this.expressionMap.valuesSet.length > 0)
        return this.expressionMap.valuesSet;

    if (this.expressionMap.valuesSet instanceof Object)
        return [this.expressionMap.valuesSet];

    throw new InsertValuesMissingError();
}
```
Should be updates like this:
```ts
// query-builder/InsertQueryBuilder.ts:558
/**
 * Gets array of values need to be inserted into the target table.
 */
protected getValueSets(): ObjectLiteral[] {
    if (this.expressionMap.valuesSet instanceof Array && this.expressionMap.valuesSet.length > 0)
        return this.expressionMap.valuesSet;

    if (this.expressionMap.valuesSet !== null && typeof this.expressionMap.valuesSet === "object")
        return [this.expressionMap.valuesSet];

    throw new InsertValuesMissingError();
}
```

**Comment by meteorlxy** [comment]
`[Object: null prototype]` also failed in find options with `where` condition of relations:

```js
// Works
repository.find({
  where: {
    relation: {
      id: 1,
    },
  },
})

// Fails
const relationCondition = Object.create(null)
relationCondition.id = 1

repository.find({
  where: {
    relation: relationCondition,
  },
})
```

**Comment by Kononnable** [comment]
Yeah, problem with `Object.create(null)` is global one and it would need one global solution, so let's keep the discussion in one issue.

Closing in favor of #2065
