### ISSUE TITLE
Primary Key Doesn't Exists

### ISSUE THREAD

**Issue by artinZareie** [typeorm/typeorm#4223]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I installed TypeORM on nest.js, and I made an entity :

`import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    PrimaryColumn,
} from 'typeorm';

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 30,
    })
    name: string;

    @Column('text')
    email: string;

    @Column({
        length: 32,
    })
    password: string;

}
`

But when I run the applicartion I get `[Nest] 4452   - 06/02/2019, 1:34 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +103ms
[0] MissingPrimaryColumnError: Entity "User" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
[0]     at new MissingPrimaryColumnError (/var/www/html/chapps-api/node_modules/typeorm/error/MissingPrimaryColumnError.js:9:28)
[0]     at EntityMetadataValidator.validate (/var/www/html/chapps-api/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:51:19)
[0]     at /var/www/html/chapps-api/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:74
[0]     at Array.forEach (<anonymous>)
[0]     at EntityMetadataValidator.validateMany (/var/www/html/chapps-api/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:25)
[0]     at Connection.buildMetadatas (/var/www/html/chapps-api/node_modules/typeorm/connection/Connection.js:480:33)
[0]     at Connection.<anonymous> (/var/www/html/chapps-api/node_modules/typeorm/connection/Connection.js:126:30)
[0]     at step (/var/www/html/chapps-api/node_modules/tslib/tslib.js:133:27)
[0]     at Object.next (/var/www/html/chapps-api/node_modules/tslib/tslib.js:114:57)
[0]     at fulfilled (/var/www/html/chapps-api/node_modules/tslib/tslib.js:104:62)`

**Comment by haschu** [comment]
Can you provide a minimal GitHub repository with your problem?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by cleivson** [comment]
I'm having the same problem as OP.

My problem entity is:
```
@Entity()
export class VerificationToken {
  constructor(user: User, expirationDate: Date) {
    this.user = user;
    this.expirationDate = expirationDate;
  }

  @PrimaryGeneratedColumn('uuid')
  token?: string;

  @Column({type: 'date'})
  expirationDate: Date;

  @JoinColumn()
  @OneToOne(type => User, { eager: true })
  user: User;

}
```

The related user entity is:
```
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  @IsOptional({ always: true })
  @ApiPropertyOptional()
  id?: number;

  @Column()
  @IsDefined({ groups: [CREATE] })
  @IsOptional({ groups: [UPDATE] })
  @ApiPropertyOptional()
  firstName?: string;

  @Column()
  @IsDefined({ groups: [CREATE] })
  @IsOptional({ groups: [UPDATE] })
  @ApiPropertyOptional()
  lastName?: string;

  @Column({ unique: true })
  @IsEmail()
  @IsDefined({ groups: [CREATE] })
  @IsOptional({ groups: [UPDATE] })
  @ApiPropertyOptional()
  email: string;

  @Exclude({ toPlainOnly: true })
  @IsDefined({ groups: [CREATE, UPDATE] })
  @IsOptional({ groups: [UPDATE] })
  @ApiPropertyOptional({ writeOnly: true })
  password: string;

  @Column({ type: 'enum', default: UserRoles.User, enum: Object.keys(UserRoles) })
  @IsEnum(UserRoles)
  @IsOptional({ always: true })
  @ApiPropertyOptional()
  role: UserRoles;

  @Column({ default: false })
  verified: boolean;

  @Column({ default: false })
  locked: boolean;

  @Column()
  passwordHash: string;

  @Column({ type: 'mediumblob', nullable: true })
  picture?: ArrayBufferLike;
}
```

**Comment by cleivson** [comment]
Version: 6.2.0

Stack trace:
```
MissingPrimaryColumnError: Entity "VerificationToken" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
    at new MissingPrimaryColumnError (/mnt/c/Workspaces/toptal/second-try/src/error/MissingPrimaryColumnError.ts:9:9)
    at EntityMetadataValidator.validate (/mnt/c/Workspaces/toptal/second-try/src/metadata-builder/EntityMetadataValidator.ts:57:19)
    at /mnt/c/Workspaces/toptal/second-try/src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/mnt/c/Workspaces/toptal/second-try/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/mnt/c/Workspaces/toptal/second-try/src/connection/Connection.ts:526:33)
    at Connection.<anonymous> (/mnt/c/Workspaces/toptal/second-try/src/connection/Connection.ts:191:18)
    at step (/mnt/c/Workspaces/toptal/second-try/node_modules/tslib/tslib.js:136:27)
    at Object.next (/mnt/c/Workspaces/toptal/second-try/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/mnt/c/Workspaces/toptal/second-try/node_modules/tslib/tslib.js:107:62)
```

**Comment by zibrohimov** [comment]
remove the dist folder
