### ISSUE TITLE
Argument of type 'ObjectId' is not assignable to parameter of type 'string | number | Date | ObjectID | FindOneOptions

### ISSUE THREAD

**Issue by davidquintard** [typeorm/typeorm#4241]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Impossible to execute findOne(<ObjectID>)

````
import {ObjectID} from "mongodb";
....
async changeGalerie(id_photo:ObjectID, acces: number) {
    let photo = await this.candidatPhotoRepository.findOne(id_photo);
}
````
error TS2345: Argument of type 'ObjectId' is not assignable to parameter of type 'string | number | Date | ObjectID | FindOneOptions<CandidatPhoto> | Partial<CandidatPhoto>'.
  Property 'generate' is missing in type 'ObjectId' but required in type 'ObjectID'.

**Comment by pairmix** [comment]
CandidatPhotoRepository:
````
import {Service} from "typedi";
import { MongoRepository, EntityRepository } from "typeorm";
import {ObjectID} from "mongodb";
import {CandidatPhoto} from "../entity/CandidatPhoto";

// create custom Repository class
@Service()
@EntityRepository(CandidatPhoto)
export class CandidatPhotoRepository extends MongoRepository<CandidatPhoto>
{
    ....
}
````

**Comment by pairmix** [comment]
It seems i have to replace:
````
let photo = await this.candidatPhotoRepository.findOne(id_photo);
````
By 
````
let photo = await this.candidatPhotoRepository.findOne({id: id_photo});
````

to let it work.

**Comment by vlapo** [comment]
You have to import `ObjectID` from `typeorm`.
```ts
import { ObjectID } from "typeorm";
```

**Comment by pairmix** [comment]
I dit it.
TypeORM is waiting for a typeorm "ObjectID" type. (import { ObjectID } from "typeorm";)
But my entities are defined with a mongodb "ObjectID" type (import {ObjectID} from "mongodb";)
which is deprecated and is an alias of "ObjectId".

@types/bson/index.t.ts
````
/**
 * ObjectID (with capital "D") is deprecated. Use ObjectId (lowercase "d") instead. 
 * @deprecated
 */
export { ObjectId as ObjectID };
````
It seems that MongoDb ObjectId and TypeORM ObjectID are incompatible.

**Comment by vlapo** [comment]
So, did you resolve your issue? Or there is something we have to change in `typeorm`?

**Comment by pairmix** [comment]
If nobody else got this problem, maybe i do wrong.
Or maybe nobody uses typeorm with mongodb...

I'm trying to compile my project par replacing everywhere
````
myrepository.findOne(myMongodbObjectId);
````

by 

````
myrepository.findOne({id: myMongodbObjectId});
````

but i'm not sure that it will work correctly.

I will let you know asap.

**Comment by rustamwin** [comment]
> It seems that MongoDb ObjectId and TypeORM ObjectID are incompatible.

You are right. We can do this change, PRs are accepted!

**Comment by vlapo** [comment]
> > It seems that MongoDb ObjectId and TypeORM ObjectID are incompatible.
> 
> You are right. We can do this change, PRs are accepted!

Why is it changed? It is because of mongodb v4 or it is just problem of pairmix environment. Is this change breaking?

**Comment by rustamwin** [comment]
It seems deprecated since 4 version of bson.
> Is this change breaking?

No, we can deprecate `ObjectID` type and keep that as legacy type.

**Comment by ruscon** [comment]
I have the same issue

**Comment by KumarAbhirup** [comment]
Same issue here. @pairmix were you able to resolve it?

**Comment by lusatiro** [comment]
Same issue here

**Comment by anlauren** [comment]
Same issue here. It seems that the PR has been closed there https://github.com/typeorm/typeorm/pull/4777 but not merged

**Comment by moimstone-Crong** [comment]
Same issue here with version 0.2.34

**Comment by moimstone-Crong** [comment]
same issue here. version 0.2.34

**Comment by ruscon** [comment]
@moimstone-Crong you can import ObjectId from mongodb

**Comment by moimstone-Crong** [comment]
When I import ObjectID from mongodb, like below
``import { ObjectID } from 'mongodb';
.....
public readCustomerPrivilege(id: string) {        
        return this.findOne(new ObjectID(id));
    }

I got erros like below.
`server/store/CustomerPrivilegeStore.ts:15:29 - error TS2345: Argument of type 'ObjectId' is not assignable to parameter of type 'string | number | Date | ObjectID | FindOneOptions<CustomerPrivilege> | Partial<CustomerPrivilege>'.
  Property 'generate' is missing in type 'ObjectId' but required in type 'ObjectID'.

15         return this.findOne(new ObjectID(id));
                               ~~~~~~~~~~~~~~~~

  node_modules/typeorm/driver/mongodb/typings.d.ts:1654:5
    1654     generate(time?: number): string;
             ~~~~~~~~
    'generate' is declared here.


Found 1 error.`


If I import ObjectID from mongodb, like below
``import { ObjectID } from 'mongodb';
.....
public readCustomerPrivilege(id: string) {        
        return this.findOne(new ObjectID(id));
    }

I got runtime error like below...
`"stacktrace": [
            "TypeError: typeorm_1.ObjectID is not a constructor",
            "    at CustomerPrivilegeStore.readCustomerPrivilege (/home/crong/work/smartwork/svcs/usersettingsservice/src/dist/server/store/CustomerPrivilegeStore.js:13:21)",
            "    at _admin_getPrivilege (/home/crong/work/smartwork/svcs/usersettingsservice/src/dist/server/service/API/resolvers/customerResolver.js:26:94)",
            "    at field.resolve (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)",
            "    at resolveFieldValueOrError (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:434:16)",
            "    at executeFields (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:275:18)",
            "    at executeOperation (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:219:122)",
            "    at executeImpl (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:104:14)",
            "    at Object.execute (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:64:35)",
            "    at /home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/apollo-server-core/dist/requestPipeline.js:261:48"
          ]`

**Comment by ruscon** [comment]
`npm i mongodb@3`

`import { ObjectId } from 'mongodb';`

**Comment by moimstone-Crong** [comment]
@ruscon To make it clear, I'd like to share my package versions.
    "mongodb": "^3.6.10",
    "redis": "^3.1.0",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^1.0.0-rc.1",
    "typeorm": "^0.2.34"

I've tried your recipe but, got the same error.

**Comment by BenRacicot** [comment]
After reinstalling node_modules I am suddenly getting this same `FindOneOptions/ObjectID` error in my NestJS server.

Using "@nestjs/typeorm": "^7.1.5"
Which seems to be using typeorm 0.2.35:
`Local installed version: 0.2.35`
`Global installed TypeORM version: 0.2.37`

The actual code

```
async getOne(id: number, userId?: string, type?: XPType, currentUser?: User) {
    const options: FindConditions<XP> = {
        id
    };
    userId && (options.userId = userId);
    type && (options.type = type);

    const post = await XP.findOne(options); // <-- error
    ...
```

Here is the actual error:

```
No overload matches this call.
  Overload 1 of 3, '(this: ObjectType<XP>, id?: string | number | Date | ObjectID, options?: FindOneOptions<XP>): Promise<...>', gave the following error.
    Argument of type 'FindConditions<XP>' is not assignable to parameter of type 'string | number | Date | ObjectID'.
      Type 'FindConditions<XP>' is missing the following properties from type 'ObjectID': generationTime, equals, generate, getTimestamp, toHexString
  Overload 2 of 3, '(this: ObjectType<XP>, options?: FindOneOptions<XP>): Promise<XP>', gave the following error.
    Type 'FindConditions<XP>' has no properties in common with type 'FindOneOptions<XP>'.
  Overload 3 of 3, '(this: ObjectType<XP>, conditions?: FindConditions<XP>, options?: FindOneOptions<XP>): Promise<...>', gave the following error.
    Argument of type 'import("/Users/bracicot/dev/dev-server/dev-server/node_modules/typeorm/find-options/FindConditions").FindConditions<import("/Users/bracicot/dev/dev-server/packages/server-common/dist/entities/experience-post.entity").XP>' is not assignable to parameter of type 'import("/Users/bracicot/dev/dev-server/packages/server-common/node_modules/typeorm/find-options/FindConditions").FindConditions<import("/Users/bracicot/dev/dev-server/packages/server-common/dist/entities/experience-post.entity").XP>'.
      Types of property 'userId' are incompatible.
        Type 'string | import("/Users/bracicot/dev/dev-server/dev-server/node_modules/typeorm/find-options/FindOperator").FindOperator<string>' is not assignable to type 'string | import("/Users/bracicot/dev/dev-server/packages/server-common/node_modules/typeorm/find-options/FindOperator").FindOperator<string>'.
          Type 'FindOperator<string>' is not assignable to type 'string | FindOperator<string>'.
            Type 'import("/Users/bracicot/dev/dev-server/dev-server/node_modules/typeorm/find-options/FindOperator").FindOperator<string>' is not assignable to type 'import("/Users/bracicot/dev/dev-server/packages/server-common/node_modules/typeorm/find-options/FindOperator").FindOperator<string>'.
              Types have separate declarations of a private property '_type'.ts(2769)
const options: FindConditions<XP>
```

**Comment by fleecmf** [comment]
> Thank you for you answer @ruscon
> 
> When I import ObjectID from mongodb, like below
> 
> ```
> import { ObjectID } from 'mongodb';
> .....
> public readCustomerPrivilege(id: string) {        
>         return this.findOne(new ObjectID(id));
>     }
> ```
> 
> I got erros like below.
> 
> ```
> server/store/CustomerPrivilegeStore.ts:15:29 - error TS2345: Argument of type 'ObjectId' is not assignable to parameter of type 'string | number | Date | ObjectID | FindOneOptions<CustomerPrivilege> | Partial<CustomerPrivilege>'.
>   Property 'generate' is missing in type 'ObjectId' but required in type 'ObjectID'.
> 
> 15         return this.findOne(new ObjectID(id));
>                                ~~~~~~~~~~~~~~~~
> 
>   node_modules/typeorm/driver/mongodb/typings.d.ts:1654:5
>     1654     generate(time?: number): string;
>              ~~~~~~~~
>     'generate' is declared here.
> 
> 
> Found 1 error.
> ```
> 
> If I import ObjectID from typeorm, like below
> 
> ```
> import { ObjectID } from 'typeorm';
> .....
> public readCustomerPrivilege(id: string) {        
>         return this.findOne(new ObjectID(id));
>     }
> ```
> 
> I got runtime error like below...
> 
> > "stacktrace": [
> 
> ```
>         "TypeError: typeorm_1.ObjectID is not a constructor",
>         "    at CustomerPrivilegeStore.readCustomerPrivilege (/home/crong/work/smartwork/svcs/usersettingsservice/src/dist/server/store/CustomerPrivilegeStore.js:13:21)",
>         "    at _admin_getPrivilege (/home/crong/work/smartwork/svcs/usersettingsservice/src/dist/server/service/API/resolvers/customerResolver.js:26:94)",
>         "    at field.resolve (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)",
>         "    at resolveFieldValueOrError (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:467:18)",
>         "    at resolveField (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:434:16)",
>         "    at executeFields (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:275:18)",
>         "    at executeOperation (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:219:122)",
>         "    at executeImpl (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:104:14)",
>         "    at Object.execute (/home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/graphql/execution/execute.js:64:35)",
>         "    at /home/crong/work/smartwork/svcs/usersettingsservice/src/node_modules/apollo-server-core/dist/requestPipeline.js:261:48"
>       ]
> ```

@moimstone-Crong hi, I have the same problem, have you solved this problem?

**Comment by sagun-k** [comment]
I am getting the same problem, ObjectID is deprecated by mongodb but query methods only accept one of kind of ObjectID

**Comment by tevaum** [comment]
I'm also having this same issue is it still unsolved? Is there any workaround?

**Comment by NoamAnisfeld** [comment]
I don't know how it was in the past, but right now it worked for me using
```
import { ObjectId } from 'mongodb';
```
and then
```
_db.collection(collection).deleteOne({ _id: new ObjectId(id) });
```
