### ISSUE TITLE
How to create new table and run migration automatically when application is running in production mode?

### ISSUE THREAD

**Issue by jerrychong25** [typeorm/typeorm#4295]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.17`

**Steps to reproduce or a small repository showing the problem:**

I would like to create new table and run migration automatically when application running in production mode.

**Note: This new table is not created prior starting of application in production mode.**

According to [Migration Documentation](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md), it need to use `typeorm migration:run` command to run migration.

Due to my new table only created when application called **CreateNewTableTimeStamp(inputTableName).up**, at this point it will trigger to create new table into my database.

But I found no solution how to do this migration automatically, since it is impossible for me to run `typeorm migration:run` manually each time application called this method.

After this table is created, I will write new data into this new table afterwards.

Could anyone assist on this issue?

Thanks.

My New Table Code:
```
class CreateNewTableTimeStamp implements MigrationInterface  {

  tableName: string;

  constructor (inputTableName: string) {
    this.tableName = inputTableName
  }

  async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createTable(new Table({
          name: this.tableName,
          columns: [
              {
                  name: "id",
                  type: "int",
                  isPrimary: true
              },
              {
                  name: "email",
                  type: "varchar",
              }
          ]
      }), true)
  }

  async down(queryRunner: QueryRunner): Promise<any> {
    const table = await queryRunner.getTable(this.tableName);
    await queryRunner.dropTable(this.tableName);
  }
}
```

**Comment by vlapo** [comment]
Did you try `migrationsRun` option? 
```ts
createConnection({
    // ...
    migrations: [
        CreateNewTableTimeStamp
    ],
    migrationsRun: true
    // ...
}) 
```
https://typeorm.io/#/connection-options/common-connection-options

**Comment by jerrychong25** [comment]
> Did you try `migrationsRun` option?
> 
> ```ts
> createConnection({
>     // ...
>     migrations: [
>         CreateNewTableTimeStamp
>     ],
>     migrationsRun: true
>     // ...
> }) 
> ```
> 
> https://typeorm.io/#/connection-options/common-connection-options

Tried added **"migrationRun": true** in **ormconfig.json**, but still not working.

Error Code:
```
(node:2805) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:2805) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "teacherken@gmail.com" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/error/RepositoryNotFoundError.ts:10:9)
    at EntityManager.getRepository (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/entity-manager/EntityManager.ts:1008:19)
    at Connection.getRepository (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/connection/Connection.ts:330:29)
    at Object.getRepository (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/index.ts:279:55)
    at Object.<anonymous> (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/controllers/RegisterController.ts:99:35)
    at step (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/controllers/RegisterController.ts:32:23)
    at Object.next (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/controllers/RegisterController.ts:13:53)
    at fulfilled (/Users/Test/Documents/NewFolder/ufinity-nodejs-assignment/src/controllers/RegisterController.ts:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:2805) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled wi
th .catch(). (rejection id: 1)
(node:2805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vlapo** [comment]
```
(node:2805) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "teacherken@gmail.com" was found. Looks like this entity is not registered in current "default" connection?
```
This is really weird error. Looks like you call `getRepository` with some incorrect argument. Could you create some small repository with simple reproduction of error?

**Comment by Jornve** [comment]
@jerrychong25 Based on the error above there is probably something wrong in your ORM configuration. With the config below I'm able to generate migrations via the CLI and they will run automatically each time my app is launched. It should be something like: 

**orm.config.ts**
```
import { ConnectionOptions } from 'typeorm';
import { join } from 'path';

const config: ConnectionOptions = {
  type: 'postgres',
  host: process.env.TYPEORM_HOST,
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
  synchronize: process.env.TYPEORM_SYNC === 'true',
  logging: process.env.TYPEORM_LOGGING === 'true',
  migrationsRun: process.env.TYPEORM_MIGRATIONS_RUN === 'true',
  entities: [join(__dirname, './../**/**.entity{.ts,.js}')],
  migrations: [join(__dirname, './../migrations/{.ts,*.js}')],
  cli: {
    migrationsDir: 'src/migrations',
  },
};

export = config;
```

**Comment by jerrychong25** [comment]
Found the root cause.

It turns out that using wrong input variable for getRepository().

**Not Working in RegisterController.ts:**
`const teacherRepository = getRepository("test@example.com");`

**Working in RegisterController.ts:**
```
import { School } from "../entity/School";
const teacherRepository = getRepository(Teacher);
```

**School Entity in School.ts:**
```
import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    UpdateDateColumn
  } from "typeorm";
  import { Length } from "class-validator";
  
  @Entity()
  export class School {
    @PrimaryGeneratedColumn()
    id: number;
  
    @Column()
    @Length(3, 254)
    teacher_email: string;

    @Column()
    @Length(3, 254)
    student_email: string;

    @Column()
    @Length(1, 20)
    status: string;

    @Column()
    @CreateDateColumn()
    createdAt: Date;
  
    @Column()
    @UpdateDateColumn()
    updatedAt: Date;
}
```

Thanks @vlapo & @Jornve for your supports.
