### ISSUE TITLE
Error during migration generation: { DriverPackageNotInstalledError: React-Native package has not been found installed. Try to install it: npm install react-native-sqlite-storage --save

### ISSUE THREAD

**Issue by nthsense** [typeorm/typeorm#4341]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create a new TypeORM project using `typeorm init`
2. Install react-native-sqlite-storage
3. Change the `ormconfig.json` to use react-native
4. Try to run `typeorm migration:generate -n Test`
5. Get an error:  

```{ DriverPackageNotInstalledError: React-Native package has not been found installed. Try to install it: npm install react-native-sqlite-storage --save
    at new DriverPackageNotInstalledError (/usr/local/lib/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at ReactNativeDriver.loadDependencies (/usr/local/lib/node_modules/typeorm/driver/react-native/ReactNativeDriver.js:87:19)
```

I modified the source of ReactNativeDriver.js to print out the original error, and it shows this:

```
{ Error: Cannot find module 'warnOnce'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
```

I definitely have `react-native-sqlite-storage` installed.  Any pointers?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
In react-native you're running your code on browser-like environment, right? So you won't be able to use migrations cli - there is simply no access to command line while you're running on mobile device - and without running on that environment you won't be able to connect to your db.

**Comment by nthsense** [comment]
My assumption - correct or not - was that the migrations cli would make its own connection via its own run-time environment, not via my react-native code.  As I understand it, there doesn't need to be a server running in order to connect to the SQLite database, since it's just a file, so the cli tool just needs to know where the file is.

I guess at minimum, a more helpful error message for this situation would be useful... but it seems like it should be possible to use migrations cli with embedded SQLite.

**Comment by Kononnable** [comment]
Sorry for late response.
Yes, it's just a file, but could you point typeorm to this file? I'm not 100% sure about react-native, but in most cases like this db is saved inside a secure storage, which can't be accessed and modified from the outside. So in order to connect to db you have to launch a mobile application(i.e. install and launch apk file for android), but when you run code in a mobile app you are loosing the ability to access files on your desktop machine(phone doesn't have access to files on your PC).
