### ISSUE TITLE
"Cannot read property 'createValueMap' of undefined" with mongo BaseEntity's create method 

### ISSUE THREAD

**Issue by AnatoleLucet** [typeorm/typeorm#4367]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```typescript
@ObjectType()
@Entity()
export class User extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn()
  id: string;

  @Field()
  @Column()
  name: string;
}
```
```typescript
@Mutation(() => User)
  async register(
    @Arg('name') name: string,
  ): Promise<User> {
    // Doesn't work
    return getMongoManager()
      .create(User, {
        name
      })
      .save();

    // Doesn't work
    return User.create({
      name
    }).save();

    // Work but I don't want to use this
    const user = new User();
    user.name = name;
    return getMongoManager().save(user);
  }
```

It seems like using `BaseEntity` return me this error : 
```
"TypeError: Cannot read property 'createValueMap' of undefined",
            "    at MongoDriver.createGeneratedMap (/home/mint/dev/Learn/TypeGraphQL/auth/src/driver/mongodb/MongoDriver.ts:364:41)",
            "    at /home/mint/dev/Learn/TypeGraphQL/auth/src/entity-manager/MongoEntityManager.ts:204:66",
            "    at Array.forEach (<anonymous>)",
            "    at MongoEntityManager.<anonymous> (/home/mint/dev/Learn/TypeGraphQL/auth/src/entity-manager/MongoEntityManager.ts:202:49)",
            "    at step (/home/mint/dev/Learn/TypeGraphQL/auth/node_modules/tslib/tslib.js:136:27)",
            "    at Object.next (/home/mint/dev/Learn/TypeGraphQL/auth/node_modules/tslib/tslib.js:117:57)",
            "    at fulfilled (/home/mint/dev/Learn/TypeGraphQL/auth/node_modules/tslib/tslib.js:107:62)",
            "    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
```

I don't really know what else I can give you but if you need anythings just ask me.

**Comment by AnatoleLucet** [comment]
Ok actually the last technique doesn't work anymore, I can not figure out why.
I leave you this repo which could reproduce the issue on your machine : https://github.com/AnatoleLucet/issue

Just rename `ormconfig.sample.json` to `ormconfig.json` an fill the `url` property.

**Comment by Rainnut** [comment]
me too

**Comment by dmitrye** [comment]
This seems to be a continuing problem with MongoEntityManager and handling primary columns that are UUID instead of ObjectID.
