### ISSUE TITLE
MYSQL/ Join tables from different databases.

### ISSUE THREAD

**Issue by AdelBachene** [typeorm/typeorm#4394]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

HI there,

I'm working on a service which interacts with different services databases using MySQL raw queries.

In one of the queries, I want to join tables from different databases but I'm getting an error, Please find my query in the fetchUsersPublications function.

```import {injectable} from "inversify";
import {EntityManager} from "typeorm";
import WallDAO from "./WallDAO";
import {ORMManager} from "../../../../config/orm";
import {ServicesEnum} from "../../ServicesEnum";
import {mutations} from "../../../../config/graphql/client";
import {ProductionGraphQLClient} from "../../../../config/graphql/client/graphql-client-factory";
import {GraphQlValidation} from "../../../Validation/graphql-result-validation";

@injectable()
export default class WallDAOImpl implements WallDAO {

    private _connectionManager: Promise<EntityManager>;

    public constructor() {
        this._connectionManager = ORMManager.Instance().getConnectionManager(ServicesEnum.WALL_SERVICE.valueOf());
    }

    fetchUsersPublications(usersIds: number[], locale: string): Promise<any> {
        if(!usersIds || !usersIds.length) {
            return new Promise(resolve => resolve({}));
        }
        return this._connectionManager
            .then(manager => {
                return manager.query(`SELECT
                  p.id as "PublicationId",
                  it.instruction as "Instruction content",
                  it.title as "Instruction title",
                  p.day_of_publication as "Day of publication",
                  p.user_id as "User Id",
                  CONCAT(ud.first_name, " ", ud.last_name) as "User name",
                  p.group_id as "Group ID",
                  g.name as "Group name",
                  at.name as  "Activity type",
                  ct.name as "Creation tool",
                  gf.receiver_user_id as "Challenge receiver id",
                  CONCAT(ud1.first_name, " ", ud1.last_name) as "Challenge receiver name",
                  p.image_id as "Image id",
                  CONCAT("https://media.mysite.com/",fl.resource) as "Image URL"
                FROM publication p
                LEFT OUTER JOIN instruction i on p.instruction_id = i.id
                LEFT OUTER JOIN instruction_translation it on i.id = it.translatable_id
                LEFT OUTER JOIN activity_type at ON p.activity_type_id = at.id
                LEFT OUTER JOIN creation_tool ct ON p.creation_tool_id = ct.id
                LEFT OUTER JOIN gift gf ON gf.id = p.gift_id
                LEFT OUTER JOIN \`user_service_database\`.\`user_detail\` ud1 ON ud1.user_id = gf.receiver_user_id
                LEFT OUTER JOIN \`user_service_database\`.\`user_detail\` ud ON ud.user_id = p.user_id
                LEFT OUTER JOIN \`user_service_database\`.\`group\` g ON g.id = p.group_id
                LEFT OUTER JOIN \`media_service_database\`.file fl ON fl.id = p.image_id
                WHERE p.user_id IN (${usersIds.join()})
                AND it.locale = "${locale}";`);
            });
    }
}
```
If you want to understand how I'm loading the DB connections check my ORMManager class

```
import "reflect-metadata";
import {createConnections, getConnection} from "typeorm";
import {Connection} from "typeorm/connection/Connection";
import {config} from "./config";
import {ServicesEnum} from "../src/Services/ServicesEnum";
import {UnprocessableEntityHttpError} from "../src/Controller/Exception/UnprocessableEntityHttpError";
const DB_CONFIGS = require(config.dbConnectionsPath);


export class ORMManager {

    private static _instance: ORMManager;
    private _connections: Promise<Connection[]>;

    private _basicORMConfig = {
        "name": "default",
        "type": "mysql",
        "host": "database-host",
        "port": 3306,
        "username": "root",
        "password": "root",
        "database": "database-name",
        "logging": true,
    };

    private constructor() {
        let ormConfig: any = [];

        if (DB_CONFIGS !== undefined) {
            for (let DBConfig of DB_CONFIGS) {
                let currentServiceConfig   = {...this._basicORMConfig};
                currentServiceConfig.name      = DBConfig.SERVICE_NAME;
                currentServiceConfig.host      = DBConfig.DB_HOST;
                currentServiceConfig.port      = DBConfig.DB_PORT;
                currentServiceConfig.database  = DBConfig.DB_NAME;
                currentServiceConfig.username  = DBConfig.DB_USERNAME;
                currentServiceConfig.password  = DBConfig.DB_PASSWORD;

                ormConfig.push(currentServiceConfig);
            }
        }
        this._connections = createConnections(ormConfig);
    }

    public static Instance() {
        return this._instance || (this._instance = new this())
    }

    public getConnectionManager = async (serviceName: string) => {
        if (serviceName in ServicesEnum) {
            try {
                const connection = await getConnection(serviceName);
                return connection.manager;
            }
            catch (error) {
                throw new Error(error);
            }
        }
        else {
            throw new UnprocessableEntityHttpError("Service Not Supported");
        }
    }
}
```

and my error log is:

```
{"message":"error: { Error: ER_NO_SUCH_TABLE: Table 'user_service_database.user_detail' doesn't exist
    at Query.Sequence._packetToError (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/docker/workspace/gdpr-api/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    }"
    }
 ```

do you have any idea how I could achieve this using typeorm raw queries

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
