### ISSUE TITLE
Migration:run creates only the "migration" table

### ISSUE THREAD

**Issue by TheDoomKing** [typeorm/typeorm#4404]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.15` (or put your version here)

I generated a migration using ts-node and got a proper migration .ts file. However, when I run the migration, only a `migration` table gets created in the database.

Creating: `ts-node ./node_modules/typeorm/cli.js migration:generate -n NAME`
Running: `ts-node ./node_modules/typeorm/cli.js migration:run`

I also tried to run it using `ts-node -r tsconfig-paths/register node_modules/.bin/typeorm migration:run`, but that produces the same result as well.

The "running" command above produces this in the log:

```bash
$ ts-node -r tsconfig-paths/register node_modules/typeorm/cli.js migration:run
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: CREATE TABLE "migrations" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id"))
query: SELECT * FROM "migrations" "migrations"
No migrations are pending
```

The latter command (`ts-node -r tsconfig-paths/register node_modules/.bin/typeorm migration:run`) produces an error:

```bash
$ npm run update

> app@1.0.0 update %ProjectRootDir%
> ts-node -r tsconfig-paths/register node_modules/.bin/typeorm migration:run

...\app\node_modules\.bin\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (%ProjectRootDir%\node_modules\ts-node\src\_bin.ts:182:12)
    at Module._compile (module.js:652:30)
```

I am out of ideas how to fix it, and search on the Internet provides zero help, as the documentation hasn't covered it and there are no user-made guides.

**Comment by TheDoomKing** [comment]
I love it when I find a solution right after posting for help. Turns out that I had forgotten to modify my `ormconfig.json` to let the migrations look for `*.ts` instead of `*.js` files. After setting it to `*.ts`, it works now (which it didn't last night, oddly enough).

```json
  "migrations": [
    "src/migration/*.ts"
  ],
```
