### ISSUE TITLE
Unable to add new record with OneToMany relation

### ISSUE THREAD

**Issue by sagerio** [typeorm/typeorm#4482]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.18`

For the last 3 days I'm going nuts because I can't add a new record with a @OneToMany() relation to a MySQL database anymore.

The OneToMany entity is as follows:

```
import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Detail } from './Detail';

@Entity()
export class Biergarten {

    @PrimaryGeneratedColumn()
    id: number;

    @Column( { default: true } )
    isBiergarten: boolean;

    @Column("simple-array")
    attendees: string[];

    @Column( { unique: true } )
    date: number;

    @Column( { unique: true } )
    link: number;

    @Column("simple-json")
    location: { latitude: number, longitude: number };

    @Column()
    name: string;

    @OneToMany( type => Detail, detail => detail.biergarten, { eager: true, cascade: true } )
    details: Detail[];

    @Column( { type: "mediumtext", nullable: false } )
    geojson: string;

    @Column( { type: "char", length: 32 } )
    hash: string;
}
```

The ManyToOne-Side is as follows:

```
import {Entity, Column, ManyToOne, PrimaryGeneratedColumn} from "typeorm";
import { Biergarten } from './Biergarten';

@Entity()
export class Detail {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    comment: string;

    @Column()
    picture: string;

    @ManyToOne( type => Biergarten, biergarten => biergarten.details, { onDelete: "CASCADE" } )
    biergarten: Biergarten;
}
```

I tried a bunch of combinations with "cascade" etc, but everytime I try to add a new record with the following code, I get an MySQL error message:

```
const repository = getRepository( Biergarten );
const biergarten = repository.create( {
  attendees: _.body.attendees,
  date: _.body.date,
  link: _.body.link,
  isBiergarten: _.body.isBiergarten,
  location: _.body.location,
  name: _.body.name,
  geojson: '',
  details: [],
  hash: '',
});

let details: Array<Detail> = Array.from(_.body.details);
details.forEach( detail => biergarten.details.push( detail ) 
await repository.save( biergarten );
);
```

The error:

```
[server] query: START TRANSACTION
[server] query: INSERT INTO `biergarten`(`id`, `isBiergarten`, `attendees`, `date`, `link`, `location`, `name`, `geojson`, `hash`) VALUES (DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [1,"Robert",1563989940,2084,"{\"latitude\":48.12694671104566,\"longitude\":11.644134521484377}","testtestest","",""]
[server] query: SELECT `Biergarten`.`id` AS `Biergarten_id`, `Biergarten`.`isBiergarten` AS `Biergarten_isBiergarten` FROM `biergarten` `Biergarten` WHERE `Biergarten`.`id` = ? -- PARAMETERS: [204]
[server] query: INSERT INTO `detail`(`id`, `comment`, `picture`, `biergartenId`) VALUES (DEFAULT, ?, ?, ?) -- PARAMETERS: [" :think: ",{},204]
[server] query failed: INSERT INTO `detail`(`id`, `comment`, `picture`, `biergartenId`) VALUES (DEFAULT, ?, ?, ?) -- PARAMETERS: [" :think: ",{},204]
[server] error: { Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 204)' at line 1
[server]     at Packet.asError (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/packets/packet.js:684:17)
[server]     at Query.execute (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/commands/command.js:28:26)
[server]     at PoolConnection.handlePacket (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/connection.js:449:32)
[server]     at PacketParser.Connection.packetParser.p [as onPacket] (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/connection.js:72:12)
[server]     at PacketParser.executeStart (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/packet_parser.js:75:16)
[server]     at Socket.Connection.stream.on.data (/home/robert/Repository/BiergartenByBike/server/node_modules/mysql2/lib/connection.js:79:25)
[server]     at Socket.emit (events.js:198:13)
[server]     at addChunk (_stream_readable.js:288:12)
[server]     at readableAddChunk (_stream_readable.js:269:11)
[server]     at Socket.Readable.push (_stream_readable.js:224:10)
[server]   code: 'ER_PARSE_ERROR',
[server]   errno: 1064,
[server]   sqlState: '42000',
[server]   sqlMessage:
[server]    'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \' 204)\' at line 1' }
[server] query: ROLLBACK
```

I've also set up a minimal git repository to find where the error is, but there it's running fine: [github](https://github.com/sagerio/ChildInsertFailed)

I've no idea where to look at now, I've also seen no difference in the tables used in the original and the minimal repository.

Thanks, Robert

**Comment by sagerio** [comment]
I figured it out, problem was the field `Detail.picture`, which was defined as string, but comes from the upload as `File`, therefore the syntax error in the query.
