### ISSUE TITLE
error: relation t does not exist

### ISSUE THREAD

**Issue by angieyu** [typeorm/typeorm#4483]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `^0.2.13`

**Steps to reproduce or a small repository showing the problem:**

```
query failed: INSERT INTO "t"("company_id", "xml", "token") VALUES ($1, $2, $3) RETURNING "id" -- PARAMETERS: [1,"<?xml version=\"1.0\"?><QBWCXML><AppName>Anami Quickbooks</AppName><AppID></AppID><AppURL>https://quickbooks-staging.anami.io/s
oap/wsdl</AppURL><AppDescription>Anami Quickbooks</AppDescription><AppSupport>https://quickbooks-staging.anami.io/desktop</AppSupport><UserName>anami</UserName><OwnerID>{4602db62-dadc-41e7-88f9-a5eb5f2e3ae3}</OwnerID><FileID>{065510dc-746f-4
976-8893-41739b0a0191}</FileID><QBType>QBFS</QBType><Scheduler><RunEveryNSeconds>60</RunEveryNSeconds></Scheduler><IsReadOnly>false</IsReadOnly></QBWCXML>","564eae1b2899"]
error: { error: relation "t" does not exist
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:466:23)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I have tried:
1) 
```
const qbWebConnector = new QuickbooksWebConnector();
qbWebConnector.companyId = companyId;
qbWebConnector.xml = xml.data.xml;
qbWebConnector.token = xml.data.token;
await qbWebConnector.save();
```

2) 
```
let xml_insert = await getManager().query(`
INSERT INTO quickbooks_web_connector (company_id, xml, token) VALUES (${companyId}, ${xmlString}, ${tokenString})
`);
```

3) 
```
await getConnection()
.createQueryBuilder()
.insert()
.into(QuickbooksWebConnector)
.values([{ companyId: companyId, xml: xml.data.xml, token: xml.data.token},])
.execute();
```

All three result in this same error but only on my production and staging environment. The queries work locally. 

This is the model:
```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm';

@Entity('quickbooks_web_connector')
export class QuickbooksWebConnector extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        name: 'company_id',
        type: 'integer',
    })
    companyId: number;

    @Column({
        name: 'xml',
        type: 'character varying',
    })
    xml: string;

    @Column({
        name: 'token',
        type: 'character varying',
    })
    token: string;
}
```

I suspect that TypeORM alias the table as “t” then goes looking for a table “t” instead of “quickbooks_web_connector”.

**Comment by angieyu** [comment]
I disabled the minifier, which fixed the issue

**Comment by dugajean** [comment]
@angieyu What minifier are you talking about?

**Comment by Rick2003** [comment]
optimization: {
        minimize: false,
    },

put this in your webpack config, on the bottom, so that the table name would not be minimized to "t" for example.

**Comment by kindacoder** [comment]
> @angieyu What minifier are you talking about?

he @dugajean  where is this file ?

**Comment by JoeCase** [comment]
@angieyu some years later but THANK YOU! Beating my head against this for a whole day.
