### ISSUE TITLE
TypeError: Cannot read property 'setEntityValue' of undefined

### ISSUE THREAD

**Issue by stuarthimmerwt** [typeorm/typeorm#4493]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have a many-to-many relationship between 3 entities. I am trying to get to have the ORM map the relationship appropriately. The SQL the query builder produces, runs but during its attempt to map it throws the following errror: 
` TypeError: Cannot read property 'setEntityValue' of undefined`
```
      at src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:196:32
          at Array.forEach (<anonymous>)
      at RawSqlResultsToEntityTransformer.Object.<anonymous>.RawSqlResultsToEntityTransformer.transformJoins (src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:160:43)
      at RawSqlResultsToEntityTransformer.Object.<anonymous>.RawSqlResultsToEntityTransformer.transformRawResultsGroup (src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:106:35)
      at src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:43:33
          at Map.forEach (<anonymous>)
      at RawSqlResultsToEntityTransformer.Object.<anonymous>.RawSqlResultsToEntityTransformer.transform (src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:42:15)
      at src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:185:36
          at Array.forEach (<anonymous>)
      at RawSqlResultsToEntityTransformer.Object.<anonymous>.RawSqlResultsToEntityTransformer.transformJoins (src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:160:43)
```
my query looks like
```
const personResult = await this.conn.manager.createQueryBuilder(Person, "person")
                            .addSelect("skill.name")
                            .addSelect("level.name")
                            .innerJoinAndMapMany("person.skills", PersonSkillLevel, "skills", 'skills."personId" = person.id')
                            .innerJoinAndMapMany("skills", Skill, "skill", 'skill.id = skills."skillId"')
                            .innerJoinAndMapMany("level", Level, "level", 'level.id = skills."levelId"')
                            .where('person.id = :uuid', {uuid: uuid})
                            .getOne();
```

Am I doing something wrong or is this condition not being handled properly?

**Comment by stuarthimmerwt** [comment]
don't know why this doesn't work but i fixed my issue by using eager relationships and this kind of query:
repo.findOne(uuid, {relations: ['title', 'specialization', 'skills']})
