### ISSUE TITLE
MongoRepository save() insert instead of update

### ISSUE THREAD

**Issue by pairmix** [typeorm/typeorm#4496]
**Issue type:**
[x ] bug report

**Database system/driver:**
[x ] `mongodb`

**TypeORM version:**

[x ] `latest`

**Steps to reproduce or a small repository showing the problem:**

candidat.entity.ts
````
import { Entity, Column, ObjectIdColumn } from 'typeorm';
import { ApiModelProperty } from '@nestjs/swagger';
import { ObjectId } from 'mongodb';
import { Membre } from '../../membres/entity/membre.entity';
import { Adresse } from './adresse.entity';
import { Annonce } from './annonce.entity';
import {Photo} from '../../photos/entity/photo.entity';

@Entity('candidats')
export class Candidat {
  @ObjectIdColumn()
  _id: ObjectId;

  @ApiModelProperty()
  @Column('smallint')
  id_sexe: number;

  @ApiModelProperty()
  @Column(type => Photo)
  photo: Photo;

  @ApiModelProperty()
  @Column({ length: 50 })
  pseudo: string;
}
````

service:
````
@Injectable()
export class AdminService {
    constructor(
        @InjectRepository(Candidat) private readonly candidatRepository: MongoRepository<Candidat>,
    ) {}

async upgradeCandidatWithPhoto() {
const candidat = await this.candidatRepository.findOne({
            where: {
                _id: new ObjectId('5d30289c2baf282802038f6c'),
            },
        });
         await this.candidatRepository.save(candidat); =>trying to insert a new document with same _id instead of updating current 
}
}
````

````
(node:8508) UnhandledPromiseRejectionWarning: BulkWriteError: E11000 duplicate key error collection: pair
mix.candidats index: _id_ dup key: { : ObjectId('5d30289c2baf282802038f6c') }                            
    at OrderedBulkOperation.handleWriteError (C:\Data\Projects\nestjs\node_modules\mongodb\lib\bulk\commo
n.js:1112:11)                                                                                            
    at resultHandler (C:\Data\Projects\nestjs\node_modules\mongodb\lib\bulk\common.js:501:23)            
    at C:\Data\Projects\nestjs\node_modules\mongodb-core\lib\connection\pool.js:397:18                   
    at process._tickCallback (internal/process/next_tick.js:61:11)                                       
(node:8508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either b
y throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). (rejection id: 2)                                                                    
(node:8508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, pro
mise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
````

**Comment by pairmix** [comment]
Are save and remove Repository methods compatible with mongoRepository ?

**Comment by rustamwin** [comment]
Yes

**Comment by pairmix** [comment]
It's weird, it doesn't work for me.
I replaced all my save and remove method by updateOne/Many and deleteOne/many and it works fine.
I suspect that save and remove methods don't manage @ObjectIdColumn "_id" but "id".

**Comment by sinedied** [comment]
Any news on this?

**Comment by yijiasu** [comment]
I got a similar issue regarding this.

If we remove the mapping column (e.g. `@Column(type => Photo)` in this case) and execute a `save()` it will work as expected, that's updating the persisted entity instead of inserting a new one.

Looking into the code to try to find why that causes this.

**Comment by hkhoan90** [comment]
I got the same issue with Postgresql/TypeORM
- insert 120 records for a table
- find a random item and change data
- call function repository.save
- a new record is created

**Comment by ksondhi** [comment]
@yijiasu I had the same issue, and your solution above fixed the issue.  Thanks a lot!

**Comment by DieserMerlin** [comment]
Any news on this?
Seems like we have no relationships with mongodb right now due to this bug

**Comment by mohamed-abdelrhman** [comment]
I had the same issue but this happens when decorating any column with PrimaryColumn() instead of Column(), Using Column() fixed it .

**Comment by sleeyax** [comment]
In my case I had another `id` field defined in my entity, as we are migrating one of our databases from MySQL to Mongo:
```ts
 /**
   * Mongo ID.
   */
  @ObjectIdColumn()
  _id: ObjectID;

  /**
   * @deprecated Please use `_id` instead. 
   */
  @PrimaryGeneratedColumn()
  id: number;
```

Removing `id` 'fixes' the issue for me. As mentioned by someone else earlier, it looks like the `save` method is looking for `id` by default, ignoring Mongo's  `_id` .
