### ISSUE TITLE
ORDERBY case insensitive

### ISSUE THREAD

**Issue by iFonny** [typeorm/typeorm#4547]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We currently can't make a case insensitive orderBy (using **orderBy** of querybuilder)

**Comment by Ginden** [comment]
What do you want to achieve?

Because it's possible to do eg. 
```
.orderBy(`LOWER(table.field)`)
```

**Comment by iFonny** [comment]
@Ginden I don't know what I've changed but its working fine now (even without LOWER())
But it's not working if I sorting using a field of a joined table

for `.orderBy('LOWER(information.streetAddress)')` (information is a OneToOne relation in user table)
```
Error: "LOWER(information" alias was not found. Maybe you forgot to join it?
    at QueryExpressionMap.findAliasByName (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/src/query-builder/QueryExpressionMap.ts:341:19)
    at /Users/ifonny/Travail/Lucette/Lucette-API-nestjs/src/query-builder/SelectQueryBuilder.ts:1864:54
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/src/query-builder/SelectQueryBuilder.ts:1861:14)
    at SelectQueryBuilder.<anonymous> (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/src/query-builder/SelectQueryBuilder.ts:1779:46)
    at step (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/node_modules/tslib/tslib.js:114:57)
    at /Users/ifonny/Travail/Lucette/Lucette-API-nestjs/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/ifonny/Travail/Lucette/Lucette-API-nestjs/node_modules/tslib/tslib.js:103:16)
```
But the request is working If I printSql() and run it manually. Looks like it consider 'LOWER(' as part of the alias

**Comment by denvaar** [comment]
I'm also seeing the bug described by  @iFonny

**Comment by D8989** [comment]
Hello.
I do not know if i can ask this here, but how is going this issue?

I use typeorm  0.2.22, and postgres, and i has received the same error of @iFonny .

`"Error: \"LOWER(auto\" alias was not found. Maybe you forgot to join it?",
            "    at QueryExpressionMap.findAliasByName (/app/node_modules/typeorm/query-builder/QueryExpressionMap.js:220:19)",
            "    at /app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1470:49",
            "    at Array.map (<anonymous>)",
            "    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1467:14)",
            "    at SelectQueryBuilder.<anonymous> (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1377:50)",
            "    at step (/app/node_modules/tslib/tslib.js:136:27)",
            "    at Object.next (/app/node_modules/tslib/tslib.js:117:57)",
            "    at /app/node_modules/tslib/tslib.js:110:75",
            "    at new Promise (<anonymous>)",
            "    at Object.__awaiter (/app/node_modules/tslib/tslib.js:106:16)"`

thanks

**Comment by emsitra** [comment]
I've found an alternative way to solve the issue.
Just added a temporary 'select field' for sorting while making a query.

e.g. you wanna use : 
`.orderBy('LOWER(information.streetAddress)')`

so it can be changed by these expressions in your QB:
```
.addSelect('LOWER("information"."streetAddress")', 'info_st_address')
.orderBy('info_st_address', 'ASC')
```

**Comment by ggrantrowberry** [comment]
I'm having a similar issue. I used the ts_rank function in my order by clause and got a similar error.
`Error: \"ts_rank(user\" alias was not found. Maybe you forgot to join it?`
The workaround by @emsitra worked for me.

**Comment by tseringn** [comment]
Having same issue, any updates?

**Comment by jlapier** [comment]
Can confirm, same issue on 0.2.38. Using the addSelect to create an alias as described by @emsitra worked as a workaround.

**Comment by MatthiasChometon** [comment]
Ok, I found that the error comes from PostgresSQL. When I run my query on pgAdmin, I get the same error. The solution is therefore to wrap it around "" like this, for example:

query.orderBy("${orderBy.name}", orderBy.direction)

and not :

query.orderBy(orderBy.name, orderBy.direction)

But yes, it would be cool to always have "" when call orderBy

**Comment by Zackynson** [comment]
> I've found an alternative way to solve the issue with the thrown 'alias was not found' error. Just added a temporary field with an alias while building a query which helped me to make case insensitive sorting.
> 
> e.g. you wanna use : `.orderBy('LOWER(information.streetAddress)')`
> 
> Change it to these expressions in your QB and it should work:
> 
> ```
> .addSelect('LOWER("information"."streetAddress")', 'info_st_address')
> .orderBy('info_st_address', 'ASC')
> ```

worked like a charm, thank you so much!

**Comment by chalzblue** [comment]
> > I've found an alternative way to solve the issue with the thrown 'alias was not found' error. Just added a temporary field with an alias while building a query which helped me to make case insensitive sorting.
> > e.g. you wanna use : `.orderBy('LOWER(information.streetAddress)')`
> > Change it to these expressions in your QB and it should work:
> > ```
> > .addSelect('LOWER("information"."streetAddress")', 'info_st_address')
> > .orderBy('info_st_address', 'ASC')
> > ```
> 
> worked like a charm, thank you so much!

it's working

**Comment by KennyMk-stack** [comment]
Also running into this issue trying to put `.addOrderBy('LOWER(rm.displayTitle', 'DESC')` or `with .orderBy`

Tried various combination of " ' ` and () with this error or with database name was not found.

I'm about to try the solution with the addSelect, but we had this part automated / working with functions, so it is not great
