### ISSUE TITLE
Cannot read property 'indexOf' of undefined error on find

### ISSUE THREAD

**Issue by robertt** [typeorm/typeorm#4641]
**Issue type:**

[x] question
[x] bug report - maybe?
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I have a model that looks like this: https://pastebin.com/8qvZ8gj5
And I'm doing this: `const cases = await Case.find({ completed: false });`, but I'm getting this error: https://pastebin.com/GpwJfBtT. I'm confused, because the files its referencing in my src folder aren't there, and none of the code leads to mine.

**Comment by ktachev** [comment]
Having the same issue 

```
`query: SELECT "Wallet"."id" AS "Wallet_id", "Wallet"."available_amount" AS "Wallet_available_amount", "Wallet"."wallet_type" AS "Wallet_wallet_type", "Wallet"."user_id" AS "Wallet_user_id", "Wallet"."created_at" AS "Wallet_created_at", "Wallet"."updated_at" AS "Wallet_updated_at" FROM "wallets" "Wallet" WHERE "Wallet"."user_id" = $1 LIMIT 1 -- PARAMETERS: ["1"]
TypeError: Cannot read property 'indexOf' of undefined
    at PostgresDriver.prepareHydratedValue (/myProject/src/driver/postgres/PostgresDriver.ts:546:64)
    at /myProject/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:143:55
    at Array.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transformColumns (/myProject/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:128:26)
    at RawSqlResultsToEntityTransformer.transformRawResultsGroup (/myProject/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:105:33)
    at /myProject/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:43:33
    at Map.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transform (/myProject/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts:42:15)
    at SelectQueryBuilder.<anonymous> (/myProject/src/query-builder/SelectQueryBuilder.ts:1889:36)
    at step (/myProject/node_modules/tslib/tslib.js:136:27)
    at Object.next (/myProject/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/myProject/node_modules/tslib/tslib.js:107:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`;
```
