### ISSUE TITLE
Binding of two entities in a many-to-many relationship throws TypeError on persist

### ISSUE THREAD

**Issue by tylerjwatson** [typeorm/typeorm#471]
Hi again,

Using version .11, I have two entities which are defined as below:

```ts
@Entity('UserGroup')
export class UserGroup extends ListItem {
        ...
	@ManyToMany(type => User, user => user.Groups, { cascadeInsert: true, cascadeUpdate: true })
	@JoinTable({ name: 'UserInUserGroup' })
	Users: User[] = [];
}

@Entity('User')
export class User extends ListItem {
        ...
	@ManyToMany(type => UserGroup, group => group.Users, { cascadeInsert: true, cascadeUpdate: true })
	Groups: UserGroup[] = [];
}
```

and code which binds them together such as below: 

```ts
for (let spGroup of remoteGroups) {
	let group = new fw.metadata.UserGroup();

	group.Title = group.Title;

	for (let spUserInGroup of spGroup.Users) {
		let user = ...;
		group.Users.push(user);
	}

	tenantSite.Groups.push(group);
}
```

Results in a `TypeError` on persist.

```
TypeError: Cannot read property 'Id' of undefined
    at /home/tw/src/bms/server/src/persistence/SubjectBuilder.ts:691:85
    at Array.map (native)
    at /home/tw/src/bms/server/src/persistence/SubjectBuilder.ts:691:67
    at Array.map (native)
    at SubjectBuilder.<anonymous> (/home/tw/src/bms/server/src/persistence/SubjectBuilder.ts:690:84)
    at step (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at /home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:7:71
    at __awaiter (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:3:12)
    at SubjectBuilder.buildJunctionOperations (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:635:16)
    at SubjectBuilder.<anonymous> (/home/tw/src/bms/server/src/persistence/SubjectBuilder.ts:114:20)
    at step (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at fulfilled (/home/tw/src/bms/server/node_modules/typeorm/persistence/SubjectBuilder.js:4:58)
```

I am trying to isolate a test case at the moment.

**Comment by pleerock** [comment]
do you still have this problem?

**Comment by pleerock** [comment]
ping @tylerjwatson

**Comment by pleerock** [comment]
closing as no answer from author. Feel free to reopen conversation if you want.
