### ISSUE TITLE
Unable to save returned "INTERVAL" format to postgres DB 

### ISSUE THREAD

**Issue by sirwesley** [typeorm/typeorm#4772]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Issue/error when saving data to postgres database of type "Interval" when data is "object".  

The data originally shows in pgAdmin as : `01:23:23`  

When reading data thru typeorm using 'find', the data is converted to an object: 
`my_interval: {hours: 1, minutes: 23, seconds: 23};` 

However, when trying to save that format back to the database using 'save', I get the following error response: ```[ExceptionsHandler] invalid input syntax for type interval: "{"hours":1,"minutes":23,"seconds":23}"```

According to the following link: https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/postgres/column-types-postgres.ts  the format looks to be documented as a string: `post.interval = "1 year 2 months 3 days 4 hours 5 minutes 6 seconds";`

**Expected Behavior:** 
I would expect that the data returned from a "find" would be able to be "saved" in the same format without throwing an error. 

**Questions:** 
- Should the saved format be a "string"?  
- Do I have to find all instances of an "interval" and convert it to a "string" format from the "object" format?  
- Is there a way that doesn't require manual conversion?  
- Is there an option that can be passed to the queries to convert them to a specific format? | object | string | something else | 
- Is there any better documentation on how to use "interval"? 
- Is there an error in the documentation? 

**Entity details:** 
`@Column({
        type: 'interval',
        nullable: true,
        name: 'my_interval',
    })
    my_interval: any | null;
`

**Error Thrown:** 
`[ExceptionsHandler] invalid input syntax for type interval: "{"hours":1,"minutes":23,"seconds":23}"
QueryFailedError: invalid input syntax for type interval: "{"hours":1,"minutes":23,"seconds":23}"
at new QueryFailedError (/src/error/QueryFailedError.ts:9:9) at Query.callback (/src/driver/postgres/PostgresQueryRunner.ts:178:30)
at Query.handleError (/node_modules/pg/lib/query.js:142:17)`

**Comment by sirwesley** [comment]
Just following up to my own questions...
Looks like this could be an issue with how pg, pg-types is configured to use postgres-interval. 

- pg:  https://github.com/brianc/node-postgres
- pg-types:  https://github.com/brianc/node-pg-types
- postgres-interval:  https://github.com/bendrucker/postgres-interval 

Will likely have to find all instances of "Interval" and will need to run it thru the parser: ```value.toPostgres()```

Would be nice if there was a configuration preference that could handle this auto-magically.

**Comment by PachowStudios** [comment]
Any update on this?

**Comment by 1valdis** [comment]
I was really surprised to see that I can't save the returned format back. What gives?

But even funnier, if you try to save something like
```
{
  minutes: 0,
  hours: 5
}
```
it will save an interval of 5 minutes. So, intervals seem to be FUBAR by default in TypeORM.

**Comment by rebolyte** [comment]
I ended up getting around this with a transformer on my `interval` columns and handling everything in seconds:
```ts
const intervalTransformer = {
	to: (seconds: number): string => `${seconds} seconds`,
	from: (intv: IPostgresInterval): number => {
		// e.g. 'P0Y0M0DT1H0M0S'
		const isoDuration = intv.toISOString();

		const dur = moment.duration(isoDuration);

		return dur.asSeconds();
	}
};

// ...

@Column({
	type: 'interval',
	transformer: intervalTransformer
})
duration!: number;
```

**Comment by guigeek973mesdocteurs** [comment]
Typeorm is not providing a native way in 2022 to automatically handle interval postgresql ?

**Comment by aMOPel** [comment]
Since this is still unresolved and I wasn't quite happy with the "handling everything in seconds" solution, I settled on using
ISO8601 duration strings, which still represent the different time units:

```typescript
import { duration } from 'moment';
import { IPostgresInterval } from 'postgres-interval';

export const intervalTransformer = {
  // db wants string like '5 days 5 hours 5 seconds'
  to: (isoDuration: string): string => {
    const d = duration(isoDuration);
    let result = '';
    if (d.years()) result += `${d.years()} years `;
    if (d.months()) result += `${d.months()} mons `;
    if (d.days()) result += `${d.days()} days `;
    if (d.hours()) result += `${d.hours()} hours `;
    if (d.minutes()) result += `${d.minutes()} minutes `;
    if (d.seconds()) result += `${d.seconds()} seconds `;
    return result;
  },
  // db gives us IPostgresInterval
  from: (intv: IPostgresInterval): string => {
    // e.g. 'P0Y0M0DT1H0M0S'
    return intv.toISOString();
  },
};

// ...
  @Column({ type: 'interval', transformer: intervalTransformer })
  duration: string;
// ...
```

With this you can put in `"P1Y2M3DT4H5M6S"` and get the same string out again, while saving it in postgres as an interval. Every conversion between units would result in the returned string possibly being different. Eg when going down to seconds (`d.asSeconds()`), when passing `"P0Y0M5DT0H0M0S"` (5 days) it would save it in postgres as 120 hours and thus return `"P0Y0M0DT120H0M0S"`, which is indeed the same duration, but a different representation and thus string comparisons (eg in tests) would fail.

Thanks @rebolyte for your snippet!

**Comment by guiterguy219** [comment]
An alternative workaround, related to what @sirwesley found, that allows you to continue working with the PostgresInterval object without converting to an ISO string or seconds. It seems that TypeORM is simply trying to store the object in Postgres as is. So you end up with an update statement that behaves like this one:

```sql
UPDATE some_table SET someInterval = '{minutes:''5''}' WHERE id = 'some_id_12345'
```

Per a comment on [this postgres-interval issue](https://github.com/bendrucker/postgres-interval/issues/27) and combined with above workarounds:

```typescript
import PostgresInterval, { IPostgresInterval } from "postgres-interval";

/**
 * Handles the logic missing from typeorm to properly serialize a `PostgresInterval` object to
 * a string.
 */
export const intervalTransformer = {
    to: (anonIntervalObject: object): string => {
        if (anonIntervalObject !== null && typeof anonIntervalObject === "object") {
            // Somewhere along the line, `anonIntervalObject` loses some properties required by
            // `PostgresInterval.prototype.toPostgres`. Specifically, the `hasOwnProperty` method
            // is undefined, which breaks `PostgresInterval.prototype.toPostgres`.
            return PostgresInterval.prototype.toPostgres.call({...anonIntervalObject});
        }
        return anonIntervalObject;
    },
    from: (interval: IPostgresInterval): IPostgresInterval => {
        return interval;
    }
}
```
