### ISSUE TITLE
TypeError: str.replace is not a function at Object.snakeCase when saving entity to repository

### ISSUE THREAD

**Issue by bartolomej** [typeorm/typeorm#4805]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi! When i run `await getRepository("Course").save(course)` on some entity i get the following error:

```
TypeError: str.replace is not a function
at Object.snakeCase (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/util/StringUtils.ts:20:16)
at DefaultNamingStrategy.Object.<anonymous>.DefaultNamingStrategy.tableName (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/naming-strategy/DefaultNamingStrategy.ts:18:56)
at EntityMetadata.Object.<anonymous>.EntityMetadata.build (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/metadata/EntityMetadata.ts:787:58)
at /Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/metadata-builder/EntityMetadataBuilder.ts:94:55
at Array.forEach (<anonymous>)
at EntityMetadataBuilder.Object.<anonymous>.EntityMetadataBuilder.build (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/metadata-builder/EntityMetadataBuilder.ts:94:14)
at ConnectionMetadataBuilder.Object.<anonymous>.ConnectionMetadataBuilder.buildEntityMetadatas (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/connection/ConnectionMetadataBuilder.ts:69:113)
at Connection.Object.<anonymous>.Connection.buildMetadatas (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/connection/Connection.ts:513:59)
at Connection.<anonymous> (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/src/connection/Connection.ts:190:18)
at step (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/node_modules/tslib/tslib.js:136:27)
at Object.next (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/node_modules/tslib/tslib.js:117:57)
at fulfilled (/Users/<user>/WebstormProjects/typeorm-reproduce-bugg/node_modules/tslib/tslib.js:107:62)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

I've created an example repository at `https://github.com/bartolomej/typeorm-reproduce-bugg` with steps to reproduce the described error.

**Comment by bartolomej** [comment]
I solved the issue. The problem was that i had the following entity Course:

```
const EntitySchema = require('typeorm').EntitySchema
const Course = require('../Course')

module.exports = new EntitySchema({
  name: 'Course',
  target: Course,
  columns: {
    uid: {
      primary: true,
      type: 'varchar'
    },
    title: {
      type: 'varchar'
    },
    description: {
      type: 'varchar'
    },
    tags: {
      type: 'varchar'
    },
    content: {
      type: 'text'
    },
    created: {
      type: 'date'
    },
  },
  relations: {
    subcategories: {
      target: "Subcategory",
      type: "many-to-many",
      joinTable: true,
      cascade: true
    }
  }
})
```

and I forgot to export Course model at `require('../Course')` so the naming strategy function received an empty object, which produced `TypeError: str.replace is not a function`
