### ISSUE TITLE
CannotDetermineConnectionOptionsError is unclear

### ISSUE THREAD

**Issue by seiyria** [typeorm/typeorm#483]
I've defined all of these environment variables:

```
TYPEORM_URL=aesir;
TYPEORM_HOST=localhost;
TYPEORM_PORT=5432;
TYPEORM_USERNAME=postgres;
TYPEORM_PASSWORD=postgres;
TYPEORM_DRIVER_TYPE =postgres;
TYPEORM_AUTO_SCHEMA_SYNC=1;
TYPEORM_ENTITIES=src/server/entities
```

but I still get the error: 

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 2): CannotDetermineConnectionOptionsError: Cannot create connection, beca
use connection options are missing. You either need to explicitly pass connection o
ptions, either create a ormconfig.json with connection options and "default" connec
tion name, either to set proper environment variables. Also, if you are using envir
onment-specific configurations in your ormconfig.json make sure your are running un
der correct NODE_ENV.
```
it's very confusingly-worded. it says "either create a config, either to set proper environment variables"

I don't understand that last part, but I set the environment variables and it's not working.  I create my connection as follows:

```
class Database {

  isReady: Promise<any>;

  constructor() {

    this.isReady = new Promise((resolve, reject) => {
      createConnection().then(connection => {
        resolve(connection);
      }).catch(error => reject(error));
    });

  }
}

export const DB = new Database();
```

any ideas?

**Comment by pleerock** [comment]
does it work for you with `ormconfig.json` instead of ENV variables?

**Comment by seiyria** [comment]
Yes, that works.

**Comment by jdelobel** [comment]
Same for me. Not working with env vars but works weel with ormconfig.json.

Err: Cannot create connection, because connection options are missing. You either need to explicitly pass connection options, either create a ormconfig.json with connection options and \"default\" connection name, either to set proper environment variables. Also, if you are using environment-specific configurations in your ormconfig.json make sure your are running under correct NODE_ENV.

Did I forget something?

**Comment by jdelobel** [comment]
Fix it  by adding TYPEORM_DATABASE=my-db-name. 

But now How I can make a migrations without ormconfig.json butt with env var?

**Comment by pleerock** [comment]
You can update docs [here](https://github.com/typeorm/typeorm.github.io).

In recent `0.1.0-alpha.8` version I have added complete support of ENV variables in both cli and app.

Now typeorm uses [donenv](https://github.com/motdotla/dotenv) package, so instead of ormconfig.json you can create ormconfig.env and define it this way:

```ini
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = localhost
TYPEORM_PORT = 3306
TYPEORM_USERNAME = test
TYPEORM_PASSWORD = test
TYPEORM_DATABASE = test
TYPEORM_AUTO_SCHEMA_SYNC = true
TYPEORM_ENTITIES = src/entity/*.js
TYPEORM_SUBSCRIBERS = src/subscriber/*.js
TYPEORM_MIGRATIONS = src/migration/*.js
TYPEORM_ENTITIES_DIR = src/entity
TYPEORM_MIGRATIONS_DIR = src/migration
TYPEORM_SUBSCRIBERS_DIR = src/subscriber
```

and btw `TYPEORM_DRIVER_TYPE` has been renamed to `TYPEORM_CONNECTION`

**Comment by pleerock** [comment]
@seiyria if you still have questions/issues let me know.

**Comment by seiyria** [comment]
thanks, I'll be sure to give that a try when I can.

**Comment by mattfung** [comment]
Hello,

 I am experiencing the same issue where using ormconfig.json works, but using .env files lead to:

```
web_1    | error: TypeORM connection error:  Error  
web_1    |     at new CannotDetermineConnectionOptionsError (/app/node_modules/typeorm/connection/error/CannotDetermineConnectionOptionsError.js:26:23)
web_1    |     at ConnectionManager.<anonymous> (/app/node_modules/typeorm/connection/ConnectionManager.js:155:23)
web_1    |     at step (/app/node_modules/typeorm/connection/ConnectionManager.js:32:23)                
web_1    |     at Object.next (/app/node_modules/typeorm/connection/ConnectionManager.js:13:53)         
web_1    |     at /app/node_modules/typeorm/connection/ConnectionManager.js:7:71                        
web_1    |     at __awaiter (/app/node_modules/typeorm/connection/ConnectionManager.js:3:12)            
web_1    |     at ConnectionManager.createAndConnect (/app/node_modules/typeorm/connection/ConnectionManager.js:141:16)
web_1    |     at Object.createConnection (/app/node_modules/typeorm/index.js:119:35)                   
web_1    |     at Object.<anonymous> (/app/app.js:153:11)                                               
web_1    |     at Module._compile (module.js:570:32)        
```
Here's my env file. Am I missing something?

```
TYPEORM_CONNECTION=postgres                         
TYPEORM_HOST=pg_db                                  
TYPEORM_PORT=5432                                   
TYPEORM_USERNAME=postgres                           
TYPEORM_PASSWORD=test                               
TYPEORM_DATABASE=test                         
TYPEORM_AUTO_SCHEMA_SYNC=true                       
TYPEORM_LOGGING=true                               
TYPEORM_ENTITIES_DIR=src/controller/entity      
```

best
