### ISSUE TITLE
How to get connection ?

### ISSUE THREAD

**Issue by booradleys** [typeorm/typeorm#487]
Hi,
I don't know how to get connection into my repositories.
Here is what i do:

// app.js
````typescript
"use strict";
exports.__esModule = true;
require("reflect-metadata");
var typeorm = require("typeorm");
var routing_controllers = require("routing-controllers");
var typedi = require("typedi");

typeorm.createConnection({
    name: "default",
    driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "",
        database: "db_exotica"
    },
    entities: [
        __dirname + "/dist/entity/*.js"
    ],
    autoSchemaSync: false,
}).then(connection => {
    // Here you can start to work with your entities
    // setup routing-controllers to use typedi container. You can use any container here
    routing_controllers.useContainer(typedi.Container);
    // create express server
    var expressApp = routing_controllers.createExpressServer({
        // now import all our controllers. alternatively you can specify controllerDirs in routing-controller options
        controllers: [__dirname + "/dist/modules/**/controllers/*.js"],
    });

    // run express app
    expressApp.listen(params.port);
    console.log("Server is up and running at port "+params.port);
}).catch(error => console.log(error));
````
//modules/default/controllers/IndexController.ts
````typescript
import {Service, Container} from "typedi";
import { FindOptions } from "typeorm";
import {Request, Response} from "express";
import {JsonController, Req, Res, Param, Body, Get, Post, Put, Delete} from "routing-controllers";
import Promise from "ts-promise";
import { OrmCustomRepository } from "../../../../../node_modules/typeorm-typedi-extensions/decorators/OrmCustomRepository";
import {TCandidatRepository} from "../../../repository/TCandidatRepository";

@Service()
@JsonController("/default")
export class IndexController
{   
    constructor(
        private candidatRepository: TCandidatRepository         
    ) {}

    //@OrmCustomRepository(TCandidatRepository)
    //private candidatRepository: TCandidatRepository

    @Get("/test")
    test(@Req() request: Request, @Res() response: Response)
    {		
        return {
           'vhost' : request.params
        }
    } 
}
````

When i call localhost:3000/default/test?param=value , i've got this error:
````bash
{"name":"TypeError","message":"connectionManager.has is not a function","stack":"TypeError: connectionManager.has is not a function\n    at Object.value (C:\\Applications\\Node\\exotica\\node_modules\\typeorm-typedi-extensions\\decorators\\OrmCustomRepository.js:13:40)\n    at C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:171:32\n    at Array.forEach (native)\n    at Function.Container.applyPropertyHandlers (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:162:23)\n    at Function.Container.get (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:68:14)\n    at C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:148:34\n    at Array.map (native)\n    at Function.Container.initializeParams (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:143:27)\n    at Function.Container.get (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:48:48)\n    at Object.getFromContainer (C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\container.js:36:42)"}
````

Then if i replace
````typescript
constructor(
        private candidatRepository: TCandidatRepository         
    ) {}
````
by
````typescript
@OrmCustomRepository(TCandidatRepository)
private candidatRepository: TCandidatRepository
````
I get the following error:
````bash
{"name":"Error","message":"Cannot get connection \"default\" from the connection manager. Make sure you have created such connection. Also make sure you have called useContainer(Container) in your application before you established a connection and importing any entity.","stack":"Error: Cannot get connection \"default\" from the connection manager. Make sure you have created such connection. Also make sure you have called useContainer(Container) in your application before you established a connection and importing any entity.\n    at Object.value (C:\\Applications\\Node\\exotica\\node_modules\\typeorm-typedi-extensions\\decorators\\OrmCustomRepository.js:14:27)\n    at C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:171:32\n    at Array.forEach (native)\n    at Function.Container.applyPropertyHandlers (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:162:23)\n    at Function.Container.get (C:\\Applications\\Node\\exotica\\node_modules\\typedi\\Container.js:68:14)\n    at Object.getFromContainer (C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\container.js:36:42)\n    at ControllerMetadata.get [as instance] (C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\metadata\\ControllerMetadata.js:27:32)\n    at ActionMetadata.executeAction (C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\metadata\\ActionMetadata.js:258:39)\n    at C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\RoutingControllerExecutor.js:74:33\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}
````
I don't know how to resolve this.
Can anyone help me ?
David

**Comment by 19majkel94** [comment]
Use `@OrmCustomRepository` from `typeorm-typedi-extensions`.

**Comment by 19majkel94** [comment]
You also have to configure TypORM to work with TypeDI - use `useContainer` not only for routing-controllers.

**Comment by booradleys** [comment]
Thank you very much @19majkel94 .
I added :
typeorm.useContainer(typedi.Container);
It works fine!
David
