### ISSUE TITLE
Error：Cannot build query because main alias is not set

### ISSUE THREAD

**Issue by xmsz** [typeorm/typeorm#4890]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to create this query：
```
SELECT
	sum( num ) 
FROM
	( SELECT count( DISTINCT `ele_red_user_record`.`user_id` ) AS `num` FROM `ele_red_user_record` GROUP BY `ele_red_user_record`.`date` ORDER BY `ele_red_user_record`.`date` DESC ) s
```

I wrote this code:
```
  const sumQuery = repository
      .createQueryBuilder()
      .select('sum(num)', 'total_sum')
      .from(subQuery => {
        return subQuery
          .select('count(distinct ele_red_user_record.user_id)', 'num')
          .groupBy('ele_red_user_record.date')
          .orderBy('ele_red_user_record.date', 'DESC');
      }, 's');
``` 

But, I got this
```
Error: Cannot build query because main alias is not set (call qb#from method)
    at SelectQueryBuilder.createSelectExpression (node_modules/_typeorm@0.2.19@typeorm/query-builder/SelectQueryBuilder.js:950:19)
    at SelectQueryBuilder.getQuery (node_modules/_typeorm@0.2.19@typeorm/query-builder/SelectQueryBuilder.js:42:24)
    at SelectQueryBuilder.QueryBuilder.createFromAlias (node_modules/_typeorm@0.2.19@typeorm/query-builder/QueryBuilder.js:363:44)
    at SelectQueryBuilder.from (node_modules/_typeorm@0.2.19@typeorm/query-builder/SelectQueryBuilder.js:119:30)
    at Object.getTotalReceiveUsersCount (EleRedUserRecord.mjs:21:8)
```

**Comment by veluxa** [comment]
sql:

``` sql
SELECT
    sum( s.num )
FROM
( 
    SELECT count( DISTINCT `ele_red_user_record`.`user_id` ) AS `num` 
    FROM `ele_red_user_record` `user_record` -- main alias set here
    GROUP BY `user_record`.`date`
    ORDER BY `user_record`.`date` DESC 
) s
```

code:
``` javascript
const sumQuery = repository
.createQueryBuilder()
.select('sum(s.num)', 'total_sum')
.from(subQuery => {
  return subQuery
    .select('count(distinct user_record.user_id)', 'num')
    .from('ele_red_user_record','user_record')
    .groupBy('user_record.date')
    .orderBy('user_record.date', 'DESC');
}, 's');
```

**Comment by xmsz** [comment]
> sql:
> 
> ```sql
> SELECT
>     sum( s.num )
> FROM
> ( 
>     SELECT count( DISTINCT `ele_red_user_record`.`user_id` ) AS `num` 
>     FROM `ele_red_user_record` `user_record` -- main alias set here
>     GROUP BY `user_record`.`date`
>     ORDER BY `user_record`.`date` DESC 
> ) s
> ```
> 
> code:
> 
> ```js
> const sumQuery = repository
> .createQueryBuilder()
> .select('sum(s.num)', 'total_sum')
> .from(subQuery => {
>   return subQuery
>     .select('count(distinct user_record.user_id)', 'num')
>     .from('ele_red_user_record','user_record')
>     .groupBy('user_record.date')
>     .orderBy('user_record.date', 'DESC');
> }, 's');
> ```

I tried this. but the sql will be :
```
SELECT
	sum( s.num ) AS `total_sum` 
FROM
	`ele_red_user_record` `eleRedUserRecord`,  -- It's wrong
	( SELECT count( DISTINCT `user_record`.`user_id` ) AS `num` FROM `ele_red_user_record` `user_record` GROUP BY user_record.date ORDER BY user_record.date DESC ) `s`
```

**Comment by OLDIN** [comment]
@xmsz 
I have the same problem.
Did you manage to find a workaround?

**Comment by xmsz** [comment]
> @xmsz
> I have the same problem.
> Did you manage to find a workaround?

Not yet

**Comment by wlsdud2194** [comment]
I'm using Mysql, but it might work

try to this code:
```javascript
import UserRecord from 'UserRecord'; // entity class

const sumQuery = getManager().createQueryBuilder()
  .select('sum(s.num) AS total_sum')
  .from(subQuery => {
    return subQuery
      .select('count(distinct user_record.user_id) AS num')
      .from(UserRecord, 'user_record') // from(entity class, alias)
      .groupBy('user_record.date')
      .orderBy('user_record.date', 'DESC');
  }, 's')
  .getRawMany();
```

**Comment by brahn** [comment]
Same problem on postgres

**Comment by brahn** [comment]
On postgres I was able to workaround the error using the other method for adding subqueries to a `from` clause suggested in https://typeorm.io/#/select-query-builder/using-subqueries (just before it recommends the "more elegant syntax" that leads to this issue)

1. Create an entirely new querybuilder for the subquery
2. Jam it in using `.getQuery` and `.getParams`

The example from the docs is as follows:
```typescript
const userQb = await connection.getRepository(User)
    .createQueryBuilder("user")
    .select("user.name", "name")
    .where("user.registered = :registered", { registered: true });

const posts = await connection
    .createQueryBuilder()
    .select("user.name", "name")
    .from("(" + userQb.getQuery() + ")", "user")
    .setParameters(userQb.getParameters())
    .getRawMany();
```

But it's disappointing that the "more elegant syntax" suggested by the docs doesn't work.

**Comment by V1raNi** [comment]
I've had a similar issue with Postgres. In the company, we used `.addFrom` subquery which contained only SELECT statement (it was UNNEST from passed parameters cast to an array) without `from` (since we did UNNEST). After some digging, I found out that if you don't call `from` method, you don't have an alias and, therefore, have this error.

Rough code example:

```js
const customIds = ['10'];
const query = getRepository(Entity)
      .createQueryBuilder()
      .select([ '"entities"."id"', 'custom', 'input' ])
      .from((qb) => (
        qb.subQuery()
          .select('"entities"."id"')
          .addSelect('UNNEST(custom_id)', 'custom')
          .from(Entity, 'entities')
      ), 'entities')
      .addFrom((qb) => (
        qb.subQuery()
          .select(`UNNEST(' { ${customIds.join(',')} } ')`, 'input')
      ), 'i')
      .where('LOWER(input) = LOWER(custom)');
```

In particular, it was falling at `createFromAlias` function in `QueryBuilder` (line 599), which called `subQueryBuilder.getQuery()` which, in turn, called `createSelectExpression` function in `SelectQueryBuilder`. Sorry, I don't have more detailed stack trace available anymore. TypeORM v.0.2.41.

**Comment by OmarLomsadze** [comment]
typeOrm is garbage just so yall know

**Comment by Subhankar6991** [comment]
I have found a solution to this. One can use the data source API of TypeORM for the same.

Problem with the previous approaches: 
while using `repository.createQueryBuilder()` then TypeORM automatically creates the query for that particular repository. 

So, simply we need to get rid of the dependency on a particular repository for creating an independent query builder.

To do that, use the `DataSource` api.

example:

`dataSource
      .createQueryBuilder()
      .select('AVG(r.price)', 'price')
      .from((subQuery) => {
        return subQuery
          .select('*')
          .from(Report, 'report')
          .where('report.make = :make', { make: query.make })
          .andWhere('report.model = :model', { model: query.model })
          .andWhere('report.lng - :lng BETWEEN -5 AND 5', { lng: query.lng })
          .andWhere('report.lat - :lat BETWEEN -5 AND 5', { lat: query.lat })
          .andWhere('report.year - :year BETWEEN -3 AND 3', {
            year: query.year,
          })
          .andWhere("report.approved = 'true'")
          .orderBy('report.mileage - :mileage', 'DESC')
          .setParameters({ mileage: query.mileage })
          .limit(3);
      }, 'r')
     .getRawMany();`

**Comment by Subhankar6991** [comment]
I have found a solution to this. One can use the data source API of TypeORM for the same.

Problem with the previous approaches: 
while using `repository.createQueryBuilder()` then TypeORM automatically creates the query for that particular repository. 

So, simply we need to get rid of the dependency on a particular repository for creating an independent query builder.

To do that, use the `DataSource` api.

example:

```typescript
      dataSource
      .createQueryBuilder()
      .select('AVG(r.price)', 'price')
      .from((subQuery) => {
        return subQuery
          .select('*')
          .from(Report, 'report')
          .where('report.make = :make', { make: query.make })
          .andWhere('report.model = :model', { model: query.model })
          .andWhere('report.lng - :lng BETWEEN -5 AND 5', { lng: query.lng })
          .andWhere('report.lat - :lat BETWEEN -5 AND 5', { lat: query.lat })
          .andWhere('report.year - :year BETWEEN -3 AND 3', {
            year: query.year,
          })
          .andWhere("report.approved = 'true'")
          .orderBy('report.mileage - :mileage', 'DESC')
          .setParameters({ mileage: query.mileage })
          .limit(3);
      }, 'r')
     .getRawMany();
```


and generated query is: 


```sql
SELECT 
          AVG(r.price) AS "price" 
FROM (
          SELECT 
                *
          FROM 
               "Report" "report" 
          WHERE
                  "report"."make" = @0 AND "report"."model" = @1 AND "report"."lng" - @2 BETWEEN -5 AND 5 AND "report"."lat" - @3 BETWEEN -5 AND 5 AND "report"."year" - @4 BETWEEN -3 AND 3 AND "report"."approved" = 'true' 
        ORDER BY "report"."mileage" - @5 DESC 
        OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY

) "r"

 ```

**Comment by rangyia** [comment]
Your subquery is just hitting raw data.  You need to ensure you have a from set in your subquery.

@OmarLomsadze, there's plenty of tutorials online for you to learn SQL yourself.
