### ISSUE TITLE
UnhandledPromiseRejectionWarning: QueryFailedError: cnst.consrc column does not exist

### ISSUE THREAD

**Issue by S1lentium** [typeorm/typeorm#4932]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
In PostgreSQL 12, when ```synchronize=true```, an error appears:

<pre>
(node:10592) UnhandledPromiseRejectionWarning: QueryFailedError: cnst.consrc column does not exist
    at new QueryFailedError (D:\projects\music-app\src\error\QueryFailedError.ts:9:9)
    at Query.callback (D:\projects\music-app\src\driver\postgres\PostgresQueryRunner.ts:178:30)
    at Query.handleError (D:\projects\music-app\node_modules\pg\lib\query.js:142:17)
    at Connection.connectedErrorMessageHandler (D:\projects\music-app\node_modules\pg\lib\client.js:211:17)
    at Connection.emit (events.js:198:13)
    at Socket.<anonymous> (D:\projects\music-app\node_modules\pg\lib\connection.js:126:12)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
</pre>
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by azzicharbel** [comment]
got the same error ...

**Comment by pjoe** [comment]
Sounds like #4332

**Comment by zishe** [comment]
Fixed in `0.2.21`, please close this issue @S1lentium
