### ISSUE TITLE
all my where field change to lower case

### ISSUE THREAD

**Issue by ruandao** [typeorm/typeorm#5090]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.x.x` (or put your version here)
"typeorm": "^0.2.20"

**Steps to reproduce or a small repository showing the problem:**
```
const newLearnPlans = await lplanRepo.createQueryBuilder("lplan")
                .where("kpId in (:...kpIds)", {kpIds})
                .getMany();
```

and get exception:
```
createOrUpdatePlan:  QueryFailedError: column "kpid" does not exist
    at new QueryFailedError (/Users/cpu/gitClone/nyd-server/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/cpu/gitClone/nyd-server/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/cpu/gitClone/nyd-server/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/cpu/gitClone/nyd-server/node_modules/pg/lib/client.js:211:17)
    at Connection.emit (events.js:210:5)
    at Socket.<anonymous> (/Users/cpu/gitClone/nyd-server/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10) {
```

my entity:
```
@Entity()
@Index(["creatorId", "kpId"])
@Unique(["creatorId", "kpId"])
export class LPlan {
    @Column({type: "uuid", nullable: false})
    kpId!: string;
    @ManyToOne(type => KP)
    kp!: KP; 
}
```

**Comment by ruandao** [comment]
the `kpId = ...` change to `kpid = ...`

**Comment by ruandao** [comment]
https://github.com/typeorm/typeorm/issues/2174#issuecomment-391015510

success after add table alias
