### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by bijeebuss** [typeorm/typeorm#51]
I'm hitting an error when my Entity class is parsed. This is the stack trace

```
c:\Users\mwelnick\Source\TypeOrm\node_modules\typeorm\metadata\types\ColumnTypes.js:64
        return type.name.toLowerCase();
                   ^

TypeError: Cannot read property 'name' of undefined
    at Function.typeToString (c:\Users\mwelnick\Source\TypeOrm\node_modules\typeorm\metadata\types\ColumnTypes.js:64:20)
    at exports.PrimaryColumn (c:\Users\mwelnick\Source\TypeOrm\node_modules\typeorm\decorator\columns\PrimaryColumn.js:20:57)
    at DecoratePropertyWithoutDescriptor (c:\Users\mwelnick\Source\TypeOrm\node_modules\reflect-metadata\Reflect.js:555:13)
    at Object.decorate (c:\Users\mwelnick\Source\TypeOrm\node_modules\reflect-metadata\Reflect.js:108:20)
    at __decorate (c:\Users\mwelnick\Source\TypeOrm\bin\server.js:4:92)
    at Object.<anonymous> (c:\Users\mwelnick\Source\TypeOrm\bin\server.js:14:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```
Im using 
version 0.0.2-alpha.67
node v6.7.0
tsc v2.1.0

This is the code 

```
import "reflect-metadata"
import {createConnection} from "typeorm";
import {Table} from "typeorm";
import {PrimaryColumn, Column} from "typeorm";

@Table("photo")
export class Photo {

    @PrimaryColumn("int", { generated: true })
    id: number;

    @Column()
    name: string;

    @Column()
    description: string;

    @Column()
    filename: string;

    @Column()
    isPublished: boolean;

}

createConnection({
    driver: {
        type: "mssql",
        host: "localhost",
        //port: 3306,
        //username: "root",
        password: "admin",
        database: "test"
    },
    entities: [
        Photo
    ],
    autoSchemaSync: true,
}).then(connection => {
    // here you can start to work with your entities
});
```

**Comment by pleerock** [comment]
I'm sorry but mssql driver still not completely ready. I had sql server installed on my windows laptop, but it suddenly died. So I need to repair it before I can finish it. You still can use mssql but some things may not work. I'll let you know when it getting more stabilized. 

Regarding to your error, looks like you have not configured tsc compiler properly. You need to add to you tsconfig.json following lines:

```
  "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
```

more info in #35

**Comment by bijeebuss** [comment]
Ah, I didn't have "emitDecoratorMetadata", that fixed the issue. For now ill try using mssql, thanks!
