### ISSUE TITLE
typeorm-esm requires mysql and does not support postgres

### ISSUE THREAD

**Issue by ithr0n** [typeorm/typeorm#5180]
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.15-dev10`

**Steps to reproduce or a small repository showing the problem:**

I have a project with typescript target "esnext" and want to use typeorm for connections with postgresql. When I use the package `typeorm @0.2.20` in my project I get this runtime error:

```SyntaxError: The requested module 'typeorm' does not provide an export named 'PrimaryGeneratedColumn'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:93:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:108:20)
    at async Loader.import (internal/modules/esm/loader.js:131:24)
    at async _third_party_main.js:29:16
```

Then I found the package `typeorm-esm @0.2.15-dev10`, but it looks like it works only with mysql. When I look into the file typeorm-esm/platform/PlatformTools.mjs there is an import statement for the package "mysql" in the beginning of the file instead at the correct position within the function `static load(name)`. Also the switch case for postgres and others is missing.

```import * as path from "path";
import * as fs from "fs";
import { highlight } from "cli-highlight-esm";
import chalk from "chalk";
----> import mysql from "mysql";
import debug from "debug";
import appRootPath from "app-root-path";
import glob from "glob";
import * as mkdirp from "mkdirp";
export { ReadStream } from "fs";
export { EventEmitter } from "events";
export { Readable, Writable } from "stream";
/**
 * Platform-specific tools.
 */
export class PlatformTools {
    /**
     * Gets global variable where global stuff can be stored.
     */
    static getGlobalVariable() {
        return global;
    }
    /**
     * Loads ("require"-s) given file or package.
     * This operation only supports on node platform
     */
    static load(name) {
        // if name is not absolute or relative, then try to load package from the node_modules of the directory we are currently in
        // this is useful when we are using typeorm package globally installed and it accesses drivers
        // that are not installed globally
        try {
            // switch case to explicit require statements for webpack compatibility.
            switch (name) {
                /**
                * mysql
                */
                case "mysql":
                    return mysql;
                /**
                * other modules
                */
                case "mkdirp":
                    return mkdirp;

...
```

This file in comparison to the regular `typeorm` package:

```"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var path = require("path");
var fs = require("fs");
var cli_highlight_1 = require("cli-highlight");
var fs_1 = require("fs");
exports.ReadStream = fs_1.ReadStream;
var events_1 = require("events");
exports.EventEmitter = events_1.EventEmitter;
var stream_1 = require("stream");
exports.Readable = stream_1.Readable;
exports.Writable = stream_1.Writable;
var chalk = require("chalk");
/**
 * Platform-specific tools.
 */
var PlatformTools = /** @class */ (function () {
    function PlatformTools() {
    }
    /**
     * Gets global variable where global stuff can be stored.
     */
    PlatformTools.getGlobalVariable = function () {
        return global;
    };
    /**
     * Loads ("require"-s) given file or package.
     * This operation only supports on node platform
     */
    PlatformTools.load = function (name) {
        // if name is not absolute or relative, then try to load package from the node_modules of the directory we are currently in
        // this is useful when we are using typeorm package globally installed and it accesses drivers
        // that are not installed globally
        try {
            // switch case to explicit require statements for webpack compatibility.
            switch (name) {
                /**
                * mongodb
                */
                case "mongodb":
                    return require("mongodb");
                /**
                * mysql
                */
                case "mysql":
                    return require("mysql");
                case "mysql2":
                    return require("mysql2");
                /**
                * oracle
                */
                case "oracledb":
                    return require("oracledb");
                /**
                * postgres
                */
                case "pg":
                    return require("pg");
                case "pg-native":
                    return require("pg-native");
                case "pg-query-stream":
                    return require("pg-query-stream");
                /**
                * redis
                */

...
```

- Is `typeorm-esm` the correct package to use for projects with target "esnext"?
- Is support for postgresql planned by `typeorm-esm` ?

**Comment by imnotjames** [comment]
`typeorm-esm` does not seem to be a project maintained by typeorm officially.
