### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by geekox86** [typeorm/typeorm#5220]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Greetings, I am not sure why I am getting the following error everytime I try to sync with the database.

```
Error during schema synchronization:
TypeError: Cannot read property 'build' of undefined
    at /Users/geekox86/Documents/GitHub/OE Scoring/src/metadata-builder/EntityMetadataBuilder.ts:594:66
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeEntityMetadataStep2 (/Users/geekox86/Documents/GitHub/OE Scoring/src/metadata-builder/EntityMetadataBuilder.ts:594:37)
    at /Users/geekox86/Documents/GitHub/OE Scoring/src/metadata-builder/EntityMetadataBuilder.ts:113:56
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/Users/geekox86/Documents/GitHub/OE Scoring/src/metadata-builder/EntityMetadataBuilder.ts:113:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/geekox86/Documents/GitHub/OE Scoring/src/connection/ConnectionMetadataBuilder.ts:66:111)
    at Connection.buildMetadatas (/Users/geekox86/Documents/GitHub/OE Scoring/src/connection/Connection.ts:516:59)
    at Connection.<anonymous> (/Users/geekox86/Documents/GitHub/OE Scoring/src/connection/Connection.ts:191:18)
    at step (/Users/geekox86/Documents/GitHub/OE Scoring/node_modules/tslib/tslib.js:136:27)
```

[Reproduction repo](https://github.com/geekox86/oe-scoring/tree/master)

**Comment by ZBAGI** [comment]
Probably a bit late answer, but for whoever will have the same problem - it is usually due to missing `@ChildEntity()` in one of the inherited classes.

**Comment by imnotjames** [comment]
Reproduction repo is gone & pretty sure that's the case as described - missing `@Entity` decorator.
