### ISSUE TITLE
Does typeorm support oracle 10g(10.2.0.4.0)?

### ISSUE THREAD

**Issue by momopig** [typeorm/typeorm#5264]
**Issue type:**

[*] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[*] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[*] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I use the command 'typeorm init --name MyProject --database oracle' to generate a typeorm dmoes to test the connection with oracle 10g in remote server. And my local instant client version is 12.2. When I `npm start`, I meet a error: `QueryFailedError: ORA-00923: ?????? FROM ???`, the log detail is as follow:
```
> ts-node src/index.ts

query: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
query: SELECT * FROM "USER_TABLES" WHERE "TABLE_NAME" IN ('TEST_LINK')
query: SELECT * FROM "USER_TAB_COLS" WHERE "TABLE_NAME" IN ('TEST_LINK')
query: SELECT "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS", LISTAGG ("COL"."COLUMN_NAME", ',') WITHIN GROUP (ORDER BY "COL"."COLUMN_NAME") AS "COLUMN_NAMES" FROM "USER_INDEXES" "IND" INNER JOIN "USER_IND_COLUMNS" "COL" ON "COL"."INDEX_NAME" = "IND"."INDEX_NAME" LEFT JOIN "USER_CONSTRAINTS" "CON" ON "CON"."CONSTRAINT_NAME" = "IND"."INDEX_NAME" WHERE "IND"."TABLE_NAME" IN ('TEST_LINK') AND "CON"."CONSTRAINT_NAME" IS NULL GROUP BY "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS"
query: SELECT "C"."CONSTRAINT_NAME", "C"."TABLE_NAME", "COL"."COLUMN_NAME", "REF_COL"."TABLE_NAME" AS "REFERENCED_TABLE_NAME", "REF_COL"."COLUMN_NAME" AS "REFERENCED_COLUMN_NAME", "C"."DELETE_RULE" AS "ON_DELETE" FROM "USER_CONSTRAINTS" "C" INNER JOIN "USER_CONS_COLUMNS" "COL" ON "COL"."OWNER" = "C"."OWNER" AND "COL"."CONSTRAINT_NAME" = "C"."CONSTRAINT_NAME" INNER JOIN "USER_CONS_COLUMNS" "REF_COL" ON "REF_COL"."OWNER" = "C"."R_OWNER" AND "REF_COL"."CONSTRAINT_NAME" = "C"."R_CONSTRAINT_NAME" AND "REF_COL"."POSITION" = "COL"."POSITION" WHERE "C"."TABLE_NAME" IN ('TEST_LINK') AND "C"."CONSTRAINT_TYPE" = 'R'
query: SELECT "C"."CONSTRAINT_NAME", "C"."CONSTRAINT_TYPE", "C"."TABLE_NAME", "COL"."COLUMN_NAME", "C"."SEARCH_CONDITION" FROM "USER_CONSTRAINTS" "C" INNER JOIN "USER_CONS_COLUMNS" "COL" ON "COL"."OWNER" = "C"."OWNER" AND "COL"."CONSTRAINT_NAME" = "C"."CONSTRAINT_NAME" WHERE "C"."TABLE_NAME" IN ('TEST_LINK') AND "C"."CONSTRAINT_TYPE" IN ('C', 'U', 'P') AND "C"."GENERATED" = 'USER NAME'
query failed: SELECT "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS", LISTAGG ("COL"."COLUMN_NAME", ',') WITHIN GROUP (ORDER BY "COL"."COLUMN_NAME") AS "COLUMN_NAMES" FROM "USER_INDEXES" "IND" INNER JOIN "USER_IND_COLUMNS" "COL" ON "COL"."INDEX_NAME" = "IND"."INDEX_NAME" LEFT JOIN "USER_CONSTRAINTS" "CON" ON "CON"."CONSTRAINT_NAME" = "IND"."INDEX_NAME" WHERE "IND"."TABLE_NAME" IN ('TEST_LINK') AND "CON"."CONSTRAINT_NAME" IS NULL GROUP BY "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS"
error: { [Error: ORA-00923: ?????? FROM ???] errorNum: 923, offset: 109 }
query: ROLLBACK
{ QueryFailedError: ORA-00923: ?????? FROM ???
    at new QueryFailedError (/Users/Jamter/project/typeorm-oracle-starter/src/error/QueryFailedError.ts:9:9)
    at handler (/Users/Jamter/project/typeorm-oracle-starter/src/driver/oracle/OracleQueryRunner.ts:175:37)
    at Connection.custExecuteCb (/Users/Jamter/project/typeorm-oracle-starter/node_modules/oracledb/lib/connection.js:103:7)
  message: 'ORA-00923: ?????? FROM ???',
  errorNum: 923,
  offset: 109,
  name: 'QueryFailedError',
  query:
   'SELECT "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS", LISTAGG ("COL"."COLUMN_NAME", \',\') WITHIN GROUP (ORDER BY "COL"."COLUMN_NAME") AS "COLUMN_NAMES" FROM "USER_INDEXES" "IND" INNER JOIN "USER_IND_COLUMNS" "COL" ON "COL"."INDEX_NAME" = "IND"."INDEX_NAME" LEFT JOIN "USER_CONSTRAINTS" "CON" ON "CON"."CONSTRAINT_NAME" = "IND"."INDEX_NAME" WHERE "IND"."TABLE_NAME" IN (\'TEST_LINK\') AND "CON"."CONSTRAINT_NAME" IS NULL GROUP BY "IND"."INDEX_NAME", "IND"."TABLE_NAME", "IND"."UNIQUENESS"',
  parameters: [] }

```
note: I use node-oracledb(4.1.0) and raw sql statement to link and operate(create table and insert rows) oracle 10g((10.2.0.4.0)) successfully.

**Comment by Kononnable** [comment]
Not, I don't think typeorm will work correctly with that version - it's pretty old. You can try to disable some of the features(e.g. schema sync) and check if it helps. However most functionalities probably won't work correctly.

According to http://www.oracle.com/us/support/library/lsp-tech-chart-069290.pdf oracle 10g was released almost 15 years ago. You should really consider upgrading it(even if you choose to not use typeorm).

**Comment by momopig** [comment]
> Not, I don't think typeorm will work correctly with that version - it's pretty old. You can try to disable some of the features(e.g. schema sync) and check if it helps. However most functionalities probably won't work correctly.
> 
> According to http://www.oracle.com/us/support/library/lsp-tech-chart-069290.pdf oracle 10g was released almost 15 years ago. You should really consider upgrading it(even if you choose not to use typeorm).

**Comment by momopig** [comment]
@Kononnable Thank you for your prompt reply.
