### ISSUE TITLE
Customize naming strategy : TypeError: namingStrategy.tableName 

### ISSUE THREAD

**Issue by karousn** [typeorm/typeorm#5286]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i am trying to create a custom naming strategy for the columnName:
```ts
export class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {
  columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
    return snakeCase(embeddedPrefixes.concat(customName ? customName : propertyName).join("_"));
  }
}
```
ormconfig.json
```json
  "namingStrategy": ["src/libs/typeorm/namingStrategy/CustomNamingStrategy.ts"],
```
inspired by [this](https://github.com/typeorm/typeorm/blob/master/sample/sample12-custom-naming-strategy/naming-strategy/CustomNamingStrategy.ts#L11), i try to change the method by one other exist in the example and i got the same message error.
i got this message error when i save ( i have  : **"synchronize": true** in config file) :
`TypeError: namingStrategy.tableName is not a function`
The trace :
`(node:1465) UnhandledPromiseRejectionWarning: TypeError: namingStrategy.tableName is not a function
    at EntityMetadata.build (/home/node/app/src/metadata/EntityMetadata.ts:787:58)
    at /home/node/app/src/metadata-builder/EntityMetadataBuilder.ts:94:55
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/home/node/app/src/metadata-builder/EntityMetadataBuilder.ts:94:14)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/home/node/app/src/connection/ConnectionMetadataBuilder.ts:66:111)
    at Connection.buildMetadatas (/home/node/app/src/connection/Connection.ts:513:59)
    at Connection.<anonymous> (/home/node/app/src/connection/Connection.ts:190:18)`
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ghry5** [comment]
I ran into the same issue. I was able to get it working by replacing my ormconfig.json with ormconfig.ts. Just for any one searching:
```ts
import { DefaultNamingStrategy, Table, NamingStrategyInterface } from "typeorm";

export default class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface{
   columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
    return snakeCase(embeddedPrefixes.concat(customName ? customName : propertyName).join("_"));
  }
}

module.exports = {
    type: "postgres",
    host: "localhost",
    port: 5444,
    username: "postgres",
    ...
    namingStrategy: new CustomNamingStrategy()
}
```

**Comment by danieldrm** [comment]
I can confirm this error. I am getting it when trying to generate a migration using a custom naming strategy. Setting it as per above does not fix the error. I am using typeorm@^0.2.24 with mysql 5.6.

**Comment by Drew-Kimberly** [comment]
Ran into this as well. In my case I was using [deepmerge](https://www.npmjs.com/package/deepmerge) to merge together typeorm options objects, and the merged naming strategy instance was not cloned properly. Solved by just merging with spread operations
