### ISSUE TITLE
Problem with connection to database [postgres]

### ISSUE THREAD

**Issue by Bundas** [typeorm/typeorm#53]
This is the error I am getting: 
```
\typeorm\connection\ConnectionManager.js:51
    get(name = "default") {
             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jan Burda\Documents\Visual Studio 2015\Projects\NodejsApppp\NodejsApppp\node_modules\typeorm\index.js:7:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

this is my code
```ts
const options: ConnectionOptions = {
    driver: {
        type: "postgres",
        host: "localhost",
        port: 5432,
        username: "postgres",
        password: "toor",
        database: "TypeTest"
    },
    autoSchemaSync: true,
    entitySchemas: [
        require(__dirname + "/schemas/records.json")
    ]
};

createConnection(options).then(connection => {
    let repo = connection.getRepository<Record.IRecord>("Record");
    // at this point you are connected to the database, and you can
    // perform queries

}).catch(error => console.log("Error during connection to the db: ", error));
```

node version: 4.5
typescript version: 2.0.3

**Comment by pleerock** [comment]
you have old version of node. try upgrade to latest one

**Comment by pleerock** [comment]
are you success with the latest node?

**Comment by pleerock** [comment]
reopen this issue if you are not
