### ISSUE TITLE
missing FROM-clause entry for table "token"

### ISSUE THREAD

**Issue by matthiashermsen** [typeorm/typeorm#5320]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using NestJs with a Postgres database and would like to delete my expired tokens from the database at regular intervals. This is my token entity

```ts
@Entity('Token')
export class Token extends BaseEntity {
  @PrimaryColumn()
  public encoding: string;

  @Column()
  public expiresOn: Date;
}
```

and I want to delete every token from the database that has expired. So the `expiresOn` returns an older date than the current date.

 When I call this 

```ts
    await this.tokensRepository
      .createQueryBuilder('token')
      .delete()
      .from(Token)
      .where('token.expiresOn <= :currentDate', { currentDate: new Date() })
      .execute();
```

I get the following error:

```
query: DELETE FROM "Token" WHERE token.expiresOn <= $1 -- PARAMETERS: ["2020-01-11T16:37:21.964Z"]
query failed: DELETE FROM "Token" WHERE token.expiresOn <= $1 -- PARAMETERS: ["2020-01-11T16:37:21.964Z"]
error: error: missing FROM-clause entry for table "token"
    at Connection.parseE (/home/matthias/Projects/nest-api/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/home/matthias/Projects/nest-api/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/home/matthias/Projects/nest-api/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 116,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '27',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3240',
  routine: 'errorMissingRTE'
}
(node:18572) UnhandledPromiseRejectionWarning: QueryFailedError: missing FROM-clause entry for table "token"
    at new QueryFailedError (/home/matthias/Projects/nest-api/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/matthias/Projects/nest-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/matthias/Projects/nest-api/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/home/matthias/Projects/nest-api/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:210:5)
    at Socket.<anonymous> (/home/matthias/Projects/nest-api/node_modules/pg/lib/connection.js:128:12)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

If you would like to have a look at the repository, there it is

https://github.com/matthiashermsen/nest-api/blob/master/src/authentications/expired-tokens-removal.service.ts#L60

If you would like to try out the NestJs API this this my .env file configuration

```
SERVER_PORT = 3000

DATABASE_TYPE = postgres
DATABASE_HOST = localhost
DATABASE_PORT = 5432
DATABASE_USERNAME = postgres
DATABASE_PASSWORD = postgres
DATABASE_NAME = api
DATABASE_LOGGING = true
DATABASE_SYNCHRONIZE = true

NODE_ENV = development

AUTHENTICATION_SALT_ROUNDS = 12
TOKEN_SECRET = secret
TOKEN_EXPIRATION_IN_SECONDS = 36000
EXPIRED_TOKEN_REMOVAL_IN_MILLISECONDS = 5000
```

I'm not sure if I missed something but maybe someone can help :) Thanks

**Comment by matthiashermsen** [comment]
I solved it by removing the name from the entity decorator in my token entity.

```
    @Entity()
    export class Token extends BaseEntity {
      @PrimaryColumn()
      public encoding: string;
    
      @Column()
      public expiresOn: Date;
    }
```

Next I took the sample from the docs https://github.com/typeorm/typeorm/blob/master/docs/delete-query-builder.md#delete-using-query-builder and created this delete query which seems to work fine for me

```ts
    await this.tokensRepository
      .createQueryBuilder()
      .delete()
      .from(Token)
      .where('expiresOn <= :currentDate', { currentDate: new Date() })
      .execute();
```
