### ISSUE TITLE
Unable to perform find with where clause containing a date

### ISSUE THREAD

**Issue by Benjamin-Dobell** [typeorm/typeorm#5334]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**NOTE**: Tested on PSQL, but affects all drivers.

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export default class SomeEntityWithADate {
    @Column({type: "time without time zone"})
    someDateField: Date;
};

const repository = getRepository(SomeEntityWithADate);

const someEntity = await repository.findOne({
    where: {
        someDateField: new Date("2020-01-13")
     }
}); // Throw error
```

Error is:

> error: invalid input syntax for type timestamp: "{}"

**Cause:**

https://github.com/typeorm/typeorm/blob/next/src/find-options/FindOptionsUtils.ts#L95-L101

`FindOptionsUtils` is attempting to recursively detect where clauses, however it does so by assuming any `Object` that _isn't_ a `FindOperator` is a where clause.

`Date` is of course an object, so `FindOptionsUtils` incorrectly assumes its encountered a where clause and replaces our `Date` with the contents of the evaluated recursively evaluted "where clause" (an empty object in the case of a `Date`).

_PR inbound_.

**Comment by artoodeeto** [comment]
@Benjamin-Dobell hello sir. this bug still on  latest version. I have this code. 

```
 static async checkUserBeforeLogin(req: Request, res: Response, next: NextFunction): Promise<void> {
    const { email, password } = req.body;
    try {
      const user = await User.findOneOrFail({ select: ['id', 'email', 'username'], where: { email } });
      const isPasswordCorrect = await bcrypt.compare(password, user.password);
      if (isPasswordCorrect) {
        res.locals = {
          user
        };
        next();
      } else {
        res.json({
          error: 'incorrect password'
        });
      }
    } catch (error) {
      res.status(404).json({
        error: `no user with ${email}`
      });
    }
  }
```

It cant filnd the email. and when I try to signup with the same email I get this error.


```
error: Error: Duplicate entry 'nocap1@gmail.com' for key 'email'
server_1  |     at Packet.asError (/server/node_modules/mysql2/lib/packets/packet.js:712:17)
server_1  |     at Query.execute (/server/node_modules/mysql2/lib/commands/command.js:28:26)
server_1  |     at PoolConnection.handlePacket (/server/node_modules/mysql2/lib/connection.js:408:32)
server_1  |     at PacketParser.onPacket (/server/node_modules/mysql2/lib/connection.js:70:12)
server_1  |     at PacketParser.executeStart (/server/node_modules/mysql2/lib/packet_parser.js:75:16)
server_1  |     at Socket.<anonymous> (/server/node_modules/mysql2/lib/connection.js:77:25)
server_1  |     at Socket.emit (events.js:210:5)
server_1  |     at addChunk (_stream_readable.js:309:12)
server_1  |     at readableAddChunk (_stream_readable.js:290:11)
server_1  |     at Socket.Readable.push (_stream_readable.js:224:10) {
server_1  |   code: 'ER_DUP_ENTRY',
server_1  |   errno: 1062,
server_1  |   sqlState: '23000',
server_1  |   sqlMessage: "Duplicate entry 'nocap1@gmail.com' for key 'email'"
server_1  | }
server_1  | query: ROLLBACK
```

so its in my database.

also the query is this.

```
 SELECT `User`.`id` AS `User_id`, `User`.`username` AS `User_username`, `User`.`email` AS `User_email` FROM `users` `User` WHERE `User`.`email` = ? LIMIT 1 -- PARAMETERS: ["nocap1@gmail.com"]
```

This query looks fine to me.  am i missing something? this code was working on version `0.2.20` then I updated to `0.2.21` then it wasnt working, then i update just right now version `0.2.22` and still failing.

**Comment by artoodeeto** [comment]
@pleerock any idea? please 🙏

**Comment by artoodeeto** [comment]
false alarm sorry but still a bug though. When I change the `select values` lets say I want the `username` instead of `password ` it  cant find it. but when i use `password` It returns data

**Comment by Cali93** [comment]
@artoodeeto I don't think that your issue is on the where clause, the error that you see here is because you have a uniqueness constraint on the `email` field, so that you can't have multiple users with the same email.

This is probably because you have duplicates with the same email so it can't `findOne` and it fails as expected.

**Comment by artoodeeto** [comment]
@Cali93 hello sir. thanks for reading the issue. The error that i posted is just for a confirmation that, that user is really in my database. So the `findOne` wasn't working or thats how thought about it but then again upon investigating some more I found out that when I specifically select `username` column it will fail but when I select `password` column it returns me a user. weird.

**Comment by artoodeeto** [comment]
@Benjamin-Dobell @pleerock @Cali93 sorry. my bad. my mistake I deleted my issue.

**Comment by xileftenurb** [comment]
A workaround, for now, is to use "new Date().toISOString()", but it would be nice to be able to send direcly the Date object and let typeorm do the conversion for us.
