### ISSUE TITLE
TypeError: Cannot read property 'table' of undefined

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#538]
Hello again!

All of a sudden, I'm experiencing this error: `TypeError: Cannot read property 'table' of undefined`.

I have this entity:

```typescript
import {Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, ManyToOne, JoinColumn} from 'typeorm';

import {User} from '../user/user.model';


@Entity('passports')
export class Passport {

  @PrimaryGeneratedColumn()
  id?: number;

  @ManyToOne(type => User, user => user.passports)
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column()
  password?: string;

  @CreateDateColumn()
  createdAt?: Date;

  @UpdateDateColumn()
  updatedAt?: Date;

}
```

And this custom repository:

```typescript
import {Repository} from 'typeorm';
import {EntityRepository} from 'typeorm/decorator/EntityRepository';

import {Passport} from './passport.model';
import {User} from '../user/user.model';


@EntityRepository(Passport)
export class PassportsRepository extends Repository<Passport> {

  getLocalPassportForUser (user: User) {
    return this.findOne({ user: user.id });
  }

}
```

When I call `getLocalPassportForUser()`, I'm getting this error:

```
TypeError: Cannot read property 'table' of undefined
    at PassportsRepository.Repository.createFindQueryBuilder (./src/repository/Repository.ts:412:70)
    at PassportsRepository.<anonymous> (./src/repository/Repository.ts:317:21)
    at step (./node_modules/typeorm/repository/Repository.js:32:23)
    at Object.next (./node_modules/typeorm/repository/Repository.js:13:53)
    at ./node_modules/typeorm/repository/Repository.js:7:71
    at Promise (<anonymous>)
    at __awaiter (./node_modules/typeorm/repository/Repository.js:3:12)
    at PassportsRepository.Repository.findOne (./node_modules/typeorm/repository/Repository.js:238:16)
    at PassportsRepository.getLocalPassportForUser (./build/src/application/models/src/application/models/passport/passports.repository.ts:13:17)
    at UsersManager.<anonymous> (./build/src/application/models/src/application/models/user/users-manager.ts:191:53)
```

```
$ node --version
v8.1.0
```

```
$ ./node_modules/.bin/tsc --version
Version 2.3.4
```

```
├─ typeorm@0.0.11
│  ├─ app-root-path@^2.0.1
│  ├─ glob@^7.1.1
│  ├─ reflect-metadata@^0.1.9
│  ├─ yargonaut@^1.1.2
│  └─ yargs@^6.6.0
```

What could be the problem? Thanks!

**Comment by slavafomin** [comment]
Well, the magic of dependency injection makes it easy to forget about `@OrmCustomRepository()`. I was mechanically injecting the repository directly to the constructor of my service = )
