### ISSUE TITLE
Repository.findByIds() throws a TypeError

### ISSUE THREAD

**Issue by aldahick** [typeorm/typeorm#542]
I'm using version 0.1.0-alpha.8.
When calling `Repository.findByIds()`, a TypeError is thrown like so:
```
TypeError: Cannot read property 'map' of undefined
      at EntityManager.findByIds (C:\Users\Alex\development\foo\src\entity-manager\EntityManager.ts:472:18)
      at Repository.findByIds (C:\Users\Alex\development\foo\src\repository\Repository.ts:281:29)
      at Function.<anonymous> (C:\Users\Alex\development\foo\foo.ts:41:39)
```

**Comment by aldahick** [comment]
Resolved by #543.
