### ISSUE TITLE
MongoDB Support with TypeORM 0.3.rc-3 onwards

### ISSUE THREAD

**Issue by larsdecker** [typeorm/typeorm#5446]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[x] `0.3.rc-3`

**Steps to reproduce or a small repository showing the problem:**

We use typeorm in a nestJS Enviroment together with MongoDB. When we just update the typeorm packages to the next branch, we got the following issue.

```js
//node_modules/@nestjs/typeorm/dist/common/typeorm.utils.js:16
    if (entity.prototype instanceof typeorm_1.Repository ||
                         ^
TypeError: Right-hand side of 'instanceof' is not an object
    at Object.getRepositoryToken (/node_modules/@nestjs/typeorm/dist/common/typeorm.utils.js:16:26)
    at Object.exports.InjectRepository (/node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.js:6:130)
    at Object.<anonymous> (/src/campaigns/campaigns.service.ts:20:6)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.require.extensions.<computed> [as .ts] (/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
npm ERR! code ELIFECYCLE
```

typeorm under version 0.3.rc-2 are working fine.
It would be nice this can be fixed in the one of the next version.

**Comment by khalilou88** [comment]
Maybe it's a nestjs bug?

**Comment by Kononnable** [comment]
It's due to big changes introduced in latest commit(ba4bebe5d9045ec8655ca50e0e022fb606149f13). It will take some time for other libraries to respond to it. And they can't do this right away - api still might change.

**Comment by larsdecker** [comment]
> Maybe it's a nestjs bug?

No, t don´t think so.

@Kononnable 
Good to know.  Let me know, if you think that the api is now stable enough, to look deeply into the issue. It would be nice if TypeORM could also work with MongoDB in the future.

**Comment by Kononnable** [comment]
I think we will be able to freeze next branch api by the end of this month(no more breaking changes from that point). And we might have a shot on releasing 0.3 in Q2 - finally after 2 years of having two active branches at the same time.
