### ISSUE TITLE
Primary column is required on table with FK's

### ISSUE THREAD

**Issue by klaaz0r** [typeorm/typeorm#5457]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**

I have a weird problem with creating a reference to a FK. The code below does not work.
```
@Entity("plays")
export class Play extends BaseEntity {
  @Column("int", { default: 0 })
  public time!: number;

  @ManyToOne(
    () => Episode,
    episode => episode.plays,
    {
      nullable: false,
      primary: true
    }
  )
  @JoinColumn({ name: "episode_id" })
  public episode!: Episode;

  @ManyToOne(
    () => User,
    user => user.plays,
    { nullable: false, primary: true }
  )
  @JoinColumn({ name: "user_id" })
  public user!: User;
 
   // This results in an error
  @Column({ name: "episode_id" })
  public episodeId!: string;
 
  // This works
  @Column({ name: "user_id" })
  public userId!: string;

  @CreateDateColumn({ name: "created_at", type: "timestamptz" })
  readonly createdAt!: Date;

  @UpdateDateColumn({ name: "updated_at", type: "timestamptz" })
  readonly updatedAt!: Date;
}
```
I get the following error:
```
(node:487) UnhandledPromiseRejectionWarning: MissingPrimaryColumnError: Entity "Play" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
     at new MissingPrimaryColumnError (/api/src/src/error/MissingPrimaryColumnError.ts:9:9)
     at EntityMetadataValidator.validate (/api/src/src/metadata-builder/EntityMetadataValidator.ts:57:19)
     at /api/src/src/metadata-builder/EntityMetadataValidator.ts:45:56
     at Array.forEach (<anonymous>)
     at EntityMetadataValidator.validateMany (/api/src/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/api/src/src/connection/Connection.ts:526:33)
    at Connection.<anonymous> (/api/src/src/connection/Connection.ts:191:18)
    at step (/api/src/node_modules/tslib/tslib.js:136:27)
    at Object.next (/api/src/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/api/src/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

If I remove ` @Column({ name: "episode_id" }) public episodeId!: string;` Everything is fine, but why is the reference to `user_id` not breaking anything? FK's are also shown correctly in the database schema.

**Comment by klaaz0r** [comment]
Solved the issue after digging trough some examples on the web, 

`@Column` -> `@PrimaryColumn`

Which does make sense but the fact that it does work with just one column and not two makes it a little unclear.
