### ISSUE TITLE
query 'CREATE DATABASE test;' => Error during query execution: error: database "test" does not exist

### ISSUE THREAD

**Issue by brussee** [typeorm/typeorm#5466]
* [x] bug report
* [x] `postgres`
* [x] `0.2.22`

```
yarn run typeorm query "CREATE DATABASE test;"
yarn run v1.21.1
$ ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js   --config src/configurations/TypeOrm.ts query 'CREATE DATABASE test;'
Error during query execution:
error: database "test" does not exist
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
  name: 'error',
  length: 89,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '890',
  routine: 'InitPostgres'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`package.json`:
```
"scripts": {
    "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js   --config src/configurations/TypeOrm.ts"
}
```

`TypeOrm.ts`:
```
import {ConnectionOptions} from "typeorm";

import {AisRequest, MTRequest, VFRequest} from "../entities/AisRequest";
import {AisResponse, MTExtendedResponse, MTFullResponse, MTSimpleResponse, VFResponse} from "../entities/AisResponse";

const databaseConfig: ConnectionOptions = {
    type: "postgres",
    host: process.env.DB_HOST ?? "",
    port: parseInt(process.env.DB_PORT ?? ""),
    database: process.env.DB_NAME ?? "",
    username: process.env.DB_USER ?? "",
    password: process.env.DB_PW ?? "",
    synchronize: !!process.env.DB_SYNC,
    entities: [],
    migrations: [__dirname + "/migrations/*.{js,ts}"],
    cli: {
        migrationsDir: __dirname + "/migrations",
    },
};

export = databaseConfig; // used by CLI
```

**Comment by tcd** [comment]
See [#809](https://github.com/typeorm/typeorm/issues/809)

**Comment by brussee** [comment]
The cause of my issue was the fact that my TypeOrm configuration referred to a database that was not (yet) created, but this configuration was used for connecting to the database, which then failed and no attempt to create the database is made because of that.
Normally you connect to the default postgres database when creating your (first) database. This was the solution: (temporarily) change the database to which the connection is made (overriding the env var on the command-line), leaving the default as is in the .env file.
