### ISSUE TITLE
Closure Table - Upserting an treeNode  array inside a transaction block fail.

### ISSUE THREAD

**Issue by leonardootoni** [typeorm/typeorm#5468]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

I am saving multiple tree nodes using a closure-table mapping inside a transaction block to only commit all records if all DB operations ended with success. However, Typeorm internally manages another DB operations to insert records inside the closure-table.

So, as soon as my process persists all data, the transaction is closed and there is no time to allow Typeorm to execute its closure-table operations with the same transaction.

Does anyone know a way to solve this issue?

My code: 
```
this.taxonomyNodeRepository.manager.transaction(async manager => {
      try {
        nodesToUpsert.forEach(async node => {
          await manager.save(node);
        });
        nodesToDelete.forEach(async node => {
          await manager.remove(node);
        });

      } catch (error) {
        logger.error(error);
        throw error;
      }
      logger.debug(`Closing transaction for Taxonomy ${id}`);
    });
```

My mapped Entity:

```
@Entity({ name: 'taxonomy_nodes' })
@Tree('closure-table')
export default class TaxonomyNode extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @MaxLength(50)
  @IsNotEmpty()
  @Column()
  name!: string;
  // @JoinColumn does not work to set a custom name. So, in the database is mandatory to set parentId
  @TreeParent()
  parent?: TaxonomyNode;

  @TreeChildren()
  children!: TaxonomyNode[];

  @IsNumber()
  @Column({ name: 'taxonomy_id' })
  taxonomyId!: number;

  @Column({ name: 'created_at', type: 'timestamp', nullable: false, select: false })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', select: false })
  updatedAt!: Date;

  @VersionColumn({ select: false })
  private version!: number;

  @BeforeInsert()
  private beforeInsert(): void {
    // Workaround to solve a bug since 0.2.19 version
    this.createdAt = new Date();
  }
}
```

The log operations:
```
query: START TRANSACTION
[2020-02-03T18:14:26.881] [DEBUG] TaxonomyModel.ts Closing transaction for Taxonomy 1
query: COMMIT
query: INSERT INTO "taxonomy_nodes"("name", "taxonomy_id", "created_at", "updated_at", "version", "parentId") VALUES ($1, $2, $3, DEFAULT, 1, DEFAULT) RETURNING "id", "updated_at", "version" -- PARAMETERS: ["Employee",1,"2020-02-03T23:14:26.885Z"]
query: INSERT INTO "taxonomy_nodes"("name", "taxonomy_id", "created_at", "updated_at", "version", "parentId") VALUES ($1, $2, $3, DEFAULT, 1, DEFAULT) RETURNING "id", "updated_at", "version" -- PARAMETERS: ["Employee Child 1",1,"2020-02-03T23:14:26.886Z"]
query: INSERT INTO "taxonomy_nodes"("name", "taxonomy_id", "created_at", "updated_at", "version", "parentId") VALUES ($1, $2, $3, DEFAULT, 1, DEFAULT) RETURNING "id", "updated_at", "version" -- PARAMETERS: ["Employee GrandChild 1",1,"2020-02-03T23:14:26.886Z"]
query: INSERT INTO "taxonomy_nodes"("name", "taxonomy_id", "created_at", "updated_at", "version", "parentId") VALUES ($1, $2, $3, DEFAULT, 1, DEFAULT) RETURNING "id", "updated_at", "version" -- PARAMETERS: ["Employee Child 2",1,"2020-02-03T23:14:26.886Z"]
query: INSERT INTO "taxonomy_nodes"("name", "taxonomy_id", "created_at", "updated_at", "version", "parentId") VALUES ($1, $2, $3, DEFAULT, 1, DEFAULT) RETURNING "id", "updated_at", "version" -- PARAMETERS: ["Director",1,"2020-02-03T23:14:26.886Z"]
(node:1007) UnhandledPromiseRejectionWarning: QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at new QueryRunnerAlreadyReleasedError (/home/wallup1/dev/wallupcms/src/error/QueryRunnerAlreadyReleasedError.ts:7:9)
    at PostgresQueryRunner.query (/home/wallup1/dev/wallupcms/src/driver/postgres/PostgresQueryRunner.ts:159:19)
    at InsertQueryBuilder.<anonymous> (/home/wallup1/dev/wallupcms/src/query-builder/InsertQueryBuilder.ts:85:50)
    at step (/home/wallup1/dev/wallupcms/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/wallup1/dev/wallupcms/node_modules/tslib/tslib.js:117:57)
    at /home/wallup1/dev/wallupcms/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/wallup1/dev/wallupcms/node_modules/tslib/tslib.js:106:16)
    at InsertQueryBuilder.execute (/home/wallup1/dev/wallupcms/node_modules/typeorm/query-builder/InsertQueryBuilder.js:43:24)
    at ClosureSubjectExecutor.<anonymous> (/home/wallup1/dev/wallupcms/src/persistence/tree/ClosureSubjectExecutor.ts:57:14)
(node:1007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by leonardootoni** [comment]
My problem happened when I tried to save multiples tree-nodes at once. Some of those nodes were intended to be inserted and some only to be updated.

The crucial point is that using the async EntityManager.save() for multiple nodes create a race condition  of promises that will eventually insert 'new' records. Considering that a node can reference a parent that was not saved yet, it was necessary to guarantee that all promises were chained in a way that forces all db transactions happened sequentially. 

To achieve that, I used an Array<Promises>.reduce(), binding the all the promises: 

```
const basePromise = Promise.resolve<TaxonomyNode>(new TaxonomyNode());
        await nodesToUpsert
          .reduce((promise, node) => promise.then(() => manager.save(node)), basePromise)
          .catch(error => {
            throw error;
          });
```

This approach solved my problem.
