### ISSUE TITLE
Trouble to connect to db with docker-compose

### ISSUE THREAD

**Issue by LadIQe** [typeorm/typeorm#5503]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello guys,

I have problems to properly run Typeorm with docker-compose. Im using NodeJS 13.8, latest TS, latest express etc. When I use PG_HOST as "localhost", I got
```
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```

but, whats funny is, that `migration:generate` works perfectly, when I change PG_HOST to docker container name, in this situation to `stater-lite-postgres`, I get no error, but migration:generate doesnt work and I get

```
Error during migration generation:
Error: getaddrinfo ENOTFOUND starter-lite-postgres
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'starter-lite-postgres'
}
error Command failed with exit code 1.
```

So, with localhost, I cant use db and my server doesnt work, without localhost I can use db (but migration doesnt work) but server works. What am I doing wrong? Sorry for long post

This is my .env file
```
PORT=4000
CORS_WHITELIST=http://localhost:3000
PG_HOST=localhost
PG_PORT=5432
PG_USER=starter-lite
PG_PASS=starter-lite
PG_DB=starter-lite
```

This is ormconfig.ts
```
import { ConnectionOptions } from 'typeorm';

const config: ConnectionOptions = {
  name: 'default',
  type: 'postgres',
  host: process.env.PG_HOST,
  port: Number(process.env.PG_PORT),
  username: process.env.PG_USER,
  password: process.env.PG_PASS,
  database: process.env.PG_DB,
  synchronize: false,
  migrationsRun: true,
  entities: [
    'src/entities/**/*.ts'
  ],
  migrations: [
    "migrations/*.ts"
  ],
  cli: {
    "migrationsDir": "migrations"
  }
};
 
export = config;
```

package.json for script
`"dev": "nodemon"`

nodemon.json
```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "ts-node ./bin/server.ts"
}
```

and finally app.ts
```
import 'dotenv/config';
import 'reflect-metadata';

import cors, { CorsOptions } from "cors";

import bodyParser from "body-parser";
import config from '../ormconfig';
import { createConnection } from 'typeorm';
import express from "express";
import helmet from "helmet";
import routes from "./api/routes";

const app = express();

const createConnectionWithDB = async () => {
  try {
    const connection = await createConnection(config)

    const whitelist = process.env.CORS_WHITELIST!.split(",");

    const corsOptions: CorsOptions = {
      origin: function(origin, callback) {
        if (whitelist.includes(origin!) || !origin) {
          callback(null, true);
        } else {
          callback(null);
        }
      },
      exposedHeaders: "X-Version"
    };

    // Call midlewares
    app.use(cors(corsOptions));
    app.use(helmet());
    app.use(bodyParser.json());

    //Set all routes from routes folder
    app.use("/", routes);
  } catch (error) {
    console.log(error)
    setTimeout(() => createConnectionWithDB(), 1000) // this was for test, if I can connect when I try again
  }
}

createConnectionWithDB()
/* previous code, no luck
createConnection(config)
  .then(async connection => {
    await connection.runMigrations();
    
    const whitelist = process.env.CORS_WHITELIST!.split(",");

    const corsOptions: CorsOptions = {
      origin: function(origin, callback) {
        if (whitelist.includes(origin!) || !origin) {
          callback(null, true);
        } else {
          callback(null);
        }
      },
      exposedHeaders: "X-Version"
    };

    // Call midlewares
    app.use(cors(corsOptions));
    app.use(helmet());
    app.use(bodyParser.json());

    //Set all routes from routes folder
    app.use("/", routes);
  })
  .catch(error => console.log(error));
*/
export default app;
```

tsconfig
```
{
  "compilerOptions": {
    "moduleResolution": "Node",
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "dist",
    "target": "ESNext",
    "module": "CommonJS",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
  },
  "exclude": ["node_modules", "dist"],
  "include": ["src", "../common", "ormconfig.ts"]
}
```

**Comment by LadIQe** [comment]
If someone would have similar problem, for me it resolved another ormconfig, where is host set as "localhost" and its used only for migration:generate

**Comment by dionathanCordova** [comment]
I have same problem.
