### ISSUE TITLE
yarn start issue

### ISSUE THREAD

**Issue by satishblr** [typeorm/typeorm#5541]
**Issue type:**

[x ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. cloned the project
2. yarn start setup
3. cloned .env to .env.development
4. in src/env.ts added this code 
`dotenv.config({ path: path.join(process.cwd(), `.env.${process.env.NODE_ENV}`) });` instead of 
`dotenv.config({ path: path.join(process.cwd(), `.env${((process.env.NODE_ENV === 'test') ? '.test' : '')}`) });`
5. yarn build
6. yarn start

my env.development looks like this for path variables
```
#
# PATH STRUCTRUE
#
TYPEORM_MIGRATIONS=src/database/migrations/**/*.ts
TYPEORM_MIGRATIONS_DIR=src/database/migrations
TYPEORM_ENTITIES=src/api/models/**/*.ts
TYPEORM_ENTITIES_DIR=src/api/models
CONTROLLERS=src/api/controllers/**/*Controller.ts
MIDDLEWARES=src/api/middlewares/**/*Middleware.ts
INTERCEPTORS=src/api/interceptors/**/*Interceptor.ts
SUBSCRIBERS=src/api/subscribers/**/*Subscriber.ts
RESOLVERS=src/api/resolvers/**/*Resolver.ts

```

my package-script.js looks like this
```
module.exports = {
    scripts: {
        default: 'nps start',
        /**
         * Starts the builded app from the dist directory.
         */
        start: {
            script: 'cross-env NODE_ENV=development node dist/app.js',
            description: 'Starts the builded app',
        },

```

I get this error when node starts
```

yarn start
yarn run v1.17.3
$ nps
nps is executing `default` : nps start
nps is executing `start` : cross-env NODE_ENV=development node dist/app.js
error: uncaughtException: Unexpected token {
C:\project\PocketGuide\pg-api\src\api\subscribers\UserEventSubscriber.ts:1
import { EventSubscriber, On } from 'event-dispatch';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at glob_1.default (C:\project\PocketGuide\pg-api\dist\loaders\eventDispatchLoader.js:18:21)
    at f (C:\project\PocketGuide\pg-api\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (C:\project\PocketGuide\pg-api\node_modules\glob\glob.js:151:7) {"error":{},"stack":"C:\\project\\PocketGuide\\pg-api\\src\\api\\subscribers\\UserEventSubscriber.ts:1\nimport { EventSubscriber, On } from 'event-dispatch';\n       ^\n\nSyntaxError: Unexpected token {\n    at Module._compile (internal/modules/cjs/loader.js:721:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n  
  at glob_1.default (C:\\project\\PocketGuide\\pg-api\\dist\\loaders\\eventDispatchLoader.js:18:21)\n    at f (C:\\project\\PocketGuide\\pg-api\\node_modules\\once\\once.js:25:25)\n    at Glob.<anonymous> (C:\\project\\PocketGuide\\pg-api\\node_modules\\glob\\glob.js:151:7)","exception":true,"date":"Mon Feb 17 2020 18:19:44 GMT-0500 (Eastern Standard Time)","process":{"pid":156556,"uid":null,"gid":null,"cwd":"C:\\project\\PocketGuide\\pg-api","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\project\\PocketGuide\\pg-api\\dist\\app.js"],"memoryUsage":{"rss":85409792,"heapTotal":74080256,"heapUsed":35134704,"external":509765}},"os":{"loadavg":[0,0,0],"uptime":292571},"trace":[{"column":23,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":721,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":690,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":25,"method":null,"native":false},{"column":21,"file":"C:\\project\\PocketGuide\\pg-api\\dist\\loaders\\eventDispatchLoader.js","function":"glob_1.default","line":18,"method":"default","native":false},{"column":25,"file":"C:\\project\\PocketGuide\\pg-api\\node_modules\\once\\once.js","function":"f","line":25,"method":null,"native":false},{"column":7,"file":"C:\\project\\PocketGuide\\pg-api\\node_modules\\glob\\glob.js","function":null,"line":151,"method":null,"native":false}]}
The script called "start" which runs "cross-env NODE_ENV=development node dist/app.js" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "default" which runs "nps start" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

if  I dont pass the environment file name I get this error
`Exception has occurred: Error
Error: Environment variable APP_NAME is not set.`

I am not sure what I am missing.

Thanks

**Comment by satishblr** [comment]
I updated the .env.developement file with these values

`#
# PATH STRUCTRUE
#
TYPEORM_MIGRATIONS=./database/migrations/**/.js
TYPEORM_MIGRATIONS_DIR=./database/migrations
TYPEORM_ENTITIES=./api/models/**/.js
TYPEORM_ENTITIES_DIR=./api/models
CONTROLLERS=./api/controllers/**/*Controller.js
MIDDLEWARES=./api/middlewares/**/*Middleware.js
INTERCEPTORS=./api/interceptors/**/*Interceptor.js
SUBSCRIBERS=./api/subscribers/**/*Subscriber.js
RESOLVERS=./api/resolvers/**/*Resolver.js
`


did `yarn build`

and now I see the following issue
`nps is executing `default` : nps start
nps is executing `start` : cross-env NODE_ENV=development node dist/app.js
error: [app] Application is crashed: EntityMetadataNotFound: No metadata for "User" was found.`


I did look into issue/bug but the article did not help

https://github.com/typeorm/typeorm/issues/2882
https://github.com/typeorm/typeorm/issues/2258

Not sure if I am doing something wrong?

**Comment by imnotjames** [comment]
This looks like a nest problem, not a typeorm problem.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
