### ISSUE TITLE
typeorm-view entity-mssql-migrations-errors

### ISSUE THREAD

**Issue by kordeviant** [typeorm/typeorm#5575]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[*] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
simple view entity that does not break on generating migrations, with oracledb and sqlite,
```
@ViewEntity({
    expression: (connection: Connection) => connection.createQueryBuilder()
        .select('*')
        .from(User, "user"),
})
export class MasterData {

    @ViewColumn()
    tid: string;

    @ViewColumn()
    amount: number;

    @ViewColumn()
    date: Date;
}
```
this gives this error when on command:
tsnd ./node_modules/typeorm/cli.js migration:generate -n "Init"
```
error:
```
Error during migration generation:
QueryFailedError: Error: The column prefix 'T' does not match with a table name or alias name used in the query.
    at new QueryFailedError (D:\Code\vip\VipMerchant Backend\src\error\QueryFailedError.ts:9:9)
    at D:\Code\vip\VipMerchant Backend\src\driver\sqlserver\SqlServerQueryRunner.ts:223:37
    at D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\base\request.js:409:25
    at Request.userCallback (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:471:15)
    at Request.callback (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\request.js:56:14)
    at Connection.endOfMessageMarkerReceived (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:2407:20)
    at Connection.dispatchEvent (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:1279:15)
    at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:1072:14)
    at Parser.emit (events.js:223:5)
    at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14) {
  message: "Error: The column prefix 'T' does not match with a table name or alias name used in the query.",
  code: 'EREQUEST',
  originalError: Error: The column prefix 'T' does not match with a table name or alias name used in the query.
      at handleError (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:364:19)
      at Connection.emit (events.js:223:5)
      at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:832:12)
      at Parser.emit (events.js:223:5)
      at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
      at Parser.emit (events.js:223:5)
      at addChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
      at readableAddChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
      at Parser.Readable.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
      at Parser.Transform.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32) {
    info: ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 107,
      state: 1,
      class: 15,
      message: "The column prefix 'T' does not match with a table name or alias name used in the query.",
      serverName: 'WIN-IB16DO5HB8U',
      procName: '',
      lineNumber: 1
    }
  },
  name: 'QueryFailedError',
  number: 107,
  lineNumber: 1,
  state: 1,
  class: 15,
  serverName: 'WIN-IB16DO5HB8U',
  procName: '',
  precedingErrors: [
    RequestError: The multi-part identifier "T.SCHEMA" could not be bound.
        at handleError (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:366:15)
        at Connection.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:832:12)
        at Parser.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
        at Parser.emit (events.js:223:5)
        at addChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
        at readableAddChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
        at Parser.Readable.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
        at Parser.Transform.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      name: 'RequestError',
      number: 4104,
      lineNumber: 1,
      state: 1,
      class: 16,
      serverName: 'WIN-IB16DO5HB8U',
      procName: ''
    },
    RequestError: The multi-part identifier "v.TABLE_NAME" could not be bound.
        at handleError (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:366:15)
        at Connection.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:832:12)
        at Parser.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
        at Parser.emit (events.js:223:5)
        at addChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
        at readableAddChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
        at Parser.Readable.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
        at Parser.Transform.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      name: 'RequestError',
      number: 4104,
      lineNumber: 1,
      state: 1,
      class: 16,
      serverName: 'WIN-IB16DO5HB8U',
      procName: ''
    },
    RequestError: The multi-part identifier "T.NAME" could not be bound.
        at handleError (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:366:15)
        at Connection.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:832:12)
        at Parser.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
        at Parser.emit (events.js:223:5)
        at addChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
        at readableAddChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
        at Parser.Readable.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
        at Parser.Transform.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      name: 'RequestError',
      number: 4104,
      lineNumber: 1,
      state: 1,
      class: 16,
      serverName: 'WIN-IB16DO5HB8U',
      procName: ''
    },
    RequestError: The multi-part identifier "T.TYPE" could not be bound.
        at handleError (D:\Code\vip\VipMerchant Backend\node_modules\mssql\lib\tedious\request.js:366:15)
        at Connection.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\connection.js:832:12)
        at Parser.emit (events.js:223:5)
        at Parser.<anonymous> (D:\Code\vip\VipMerchant Backend\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
        at Parser.emit (events.js:223:5)
        at addChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
        at readableAddChunk (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
        at Parser.Readable.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
        at Parser.Transform.push (D:\Code\vip\VipMerchant Backend\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      name: 'RequestError',
      number: 4104,
      lineNumber: 1,
      state: 1,
      class: 16,
      serverName: 'WIN-IB16DO5HB8U',
      procName: ''
    }
  ],
  query: `SELECT "T".*, "V"."CHECK_OPTION" FROM "vip".."typeorm_metadata" "t" INNER JOIN "vip"."INFORMATION_SCHEMA"."VIEWS" "V" ON "V"."TABLE_SCHEMA" = "T"."SCHEMA" AND "v"."TABLE_NAME"
 = "T"."NAME" WHERE "T"."TYPE" = 'VIEW' `,
  parameters: []
}
```

**Comment by PitsoHumphrey** [comment]
is there a solution to this?

**Comment by david-villafrut** [comment]
I have the same problem using a database with collation set to :  **Latin1_General_CS_AS**

but

using another database with collation **Latin1_General_CI_AS** seems to be working with the same setup

**Comment by Deftera186** [comment]
For anyone else encountering this: when TypeORM generates migrations that include views, it creates a `typeorm_metadata`  table to store view metadata. For unknown reasons, sometimes that table will just be empty, which will cause this error and the migration to fail. A simple workaround is to  just drop the `typeorm_metadata` table and then you will be able to re-run the migration. Thank me later :3

**Comment by Cprakhar** [comment]
@kordeviant Could you give me the entity files so I can understand more? You also claim that there are no issues with Oracle and SQLite.

**Comment by thecoolestcoderrushil** [comment]
A migration that fails to generate for view entities on MSSQL is a painful blocker, since the column prefix error breaks the whole generate command. Rehearsing the migration on a production-shaped twin first would surface the generation problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
