### ISSUE TITLE
Calling findOneById throws a weird error

### ISSUE THREAD

**Issue by esdoppio** [typeorm/typeorm#558]
This is the original version of the function, which works without errors:

```typescript
const get_owner_id:Tiger.DbGetWorkOwnerId = async function get_owner_id(work_id:number) {
  const result:any[] = await user_work_repo
      .createQueryBuilder('user_work')
      .select('user_id')
      .where('user_work.id = :work_id', { work_id })
      .execute();

  return result[0] && result[0].user_id;
}
```

Later I discovered the `findOneById` method, and it seemed to make more sense to use it instead, so I changed the function to

```typescript
const get_owner_id:Tiger.DbGetWorkOwnerId = async function get_owner_id(work_id:number) {
  const result:any = await user_work_repo.findOneById(work_id);
  return result && result.user_id;
}
```

which throws

```
TypeError: date.getFullYear is not a function
    at Function.DataTransformationUtils.normalizeHydratedDate (/usr/src/app/node_modules/typeorm/util/DataTransformationUtils.js:23:47)
    at MysqlDriver.prepareHydratedValue (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:227:74)
    at /usr/src/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:89:42
    at Array.forEach (native)
    at RawSqlResultsToEntityTransformer.transformIntoSingleResult (/usr/src/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:85:26)
    at /usr/src/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:48:26
    at Array.map (native)
    at RawSqlResultsToEntityTransformer.groupAndTransform (/usr/src/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:45:14)
    at RawSqlResultsToEntityTransformer.transform (/usr/src/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:24:21)
    at QueryBuilder.rawResultsToEntities (/usr/src/app/node_modules/typeorm/query-builder/QueryBuilder.js:1032:28)
    at /usr/src/app/node_modules/typeorm/query-builder/QueryBuilder.js:731:46
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Am I doing this right? Or this is a bug?

**Comment by pleerock** [comment]
```ts
  const result:any[] = await user_work_repo
      .createQueryBuilder('user_work')
      .select('user_id')
      .where('user_work.id = :work_id', { work_id })
      .execute();

  return result[0] && result[0].user_id;
```

Its not something you should do using orm. `findOneById` is the way to go or using query builder but using `getOne` or `getMany` instead or `execute`. Please provide your models at minimals that reproduce this issue.

**Comment by esdoppio** [comment]
These fields `create_time`, `publish_time`, `update_time`, `sharetime` in the related table are of type `INT`. Do you think that might be the cause of the problem?

**Comment by pleerock** [comment]
show me your entity

**Comment by esdoppio** [comment]
There you go

```typescript
@Entity('tbl_user_works')
@Index("PRIMARY",["id",])
@Index("create_time_index",["create_time",])
@Index("idx_update_time",["update_time",])
@Index("idx_order_level",["order_level",])
@Index("idx_work_search",["user_id","status","publish_time",],{unique:true})
@Index("idx_type",["type",])
@Index("idx_praise_times",["praise_times",])
@Index("idx_work_url",["work_url",],{unique:true})
@Index("idx_search_work_name",["publish_time","name","status","type",])
@Index("idx_isold_createtime",["is_old","create_time",])
@Index("status_index",["status","publish_time","fork_times",])
@Index("user_id_index",["user_id","status","create_time",],{unique:true})
@Index("idx_work_name",["name","status",])
export class UserWork {

    @PrimaryGeneratedColumn()
    id:number;
    @Column("int",{ nullable:true,})
    user_id:number;
    @CreateDateColumn()
    create_time:number;
    @Column("int",{ nullable:true,})
    view_times:number;
    @Column("int",{ default:0,})
    praise_times:number;
    @Column("text",{ nullable:true,length:4294967295,})
    config:string;
    @Column("smallint",{ nullable:true,})
    is_share:number;
    @Column("string",{ nullable:true,length:50,})
    name:string;
    @Column("string",{ nullable:true,length:2000,})
    description:string;
    @Column("string",{ nullable:true,length:200,})
    preview:string;
    @Column("smallint",{ default:1,})
    status:number;
    @Column("int",{ })
    publish_time:number;
    @Column("string",{ nullable:true,length:200,})
    types:string;
    @Column("int",{ nullable:true,})
    spendtime:number;
    @Column("string",{ nullable:true,length:6,})
    pass:string;
    @Column("int",{ nullable:true,})
    score:number;
    @Column("int",{ nullable:true,})
    lesson_id:number;
    @Column("int",{ nullable:true,})
    sharetime:number;
    @UpdateDateColumn()
    update_time:number;
    @Column("int",{ nullable:true,})
    parent_id:number;
    @Column("int",{ default:0,})
    order_level:number;
    @Column("int",{ nullable:true,})
    isallow_fork:number;
    @Column("int",{ default:0,})
    teaching_lesson_id:number;
    @Column("int",{ nullable:true,})
    fork_times:number;
    @Column("int",{ nullable:true,})
    collection_times:number;
    @Column("int",{ nullable:true,})
    comment_times:number;
    @Column("smallint",{ nullable:true,})
    is_old:number;
    @Column("int",{ nullable:true,})
    fork_time:number;
    @Column("string",{ nullable:true,length:255,})
    current_show_preview:string;
    @Column("int",{ default:1,})
    type:number;
    @Column("string",{ nullable:true,length:1000,})
    work_url:string;
    @Column("string",{ nullable:true,length:255,})
    sub_config:string;
    @Column("smallint",{ nullable:true,})
    orientation:number;
}
```

**Comment by esdoppio** [comment]
Removed the annotations `@UpdateDateColumn()` and `@CreateDateColumn()`. Problem solved. Thanks!

**Comment by esdoppio** [comment]
But could you please explain to me what exactly these two annotations do?

**Comment by pleerock** [comment]
@UpdateDateColumn() and @CreateDateColumn() automatically create in your database date columns and when you first time persist/save your object it stores data in create date column and never changes it. Each time you update your entity using persist/save method update date column makes sure to update date in the database too.

In your model you should have @UpdateDateColumn() @CreateDateColumn() columns to be typeof `Date`, not `number` and you should never assign value to them - they are getting assigned automatically

**Comment by esdoppio** [comment]
Oh, the thing is, instead of using this entity to create a structure, it is generated from an existing table. Sorry about the poor question. What I meant to ask was, when you try to fetch data from the database, what does TypeORM do with the data of the field with annotation `@CreateDateColumn()`?
