### ISSUE TITLE
ManyToMany empty array produce error

### ISSUE THREAD

**Issue by scieslickicc** [typeorm/typeorm#5604]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

website.entity.ts

```
import { Entity, Column, ManyToOne, ManyToMany, JoinTable } from 'typeorm';
import { Publisher } from '../publisher/publisher.entity';
import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';
import { Category, categoryExample } from '../category/category.entity';
import { StatusedBaseEntity } from '../../common/statused-base-entity';

@Entity()
export class Website extends StatusedBaseEntity {
  @Column({ type: 'varchar', length: 255, nullable: false })
  public name!: string;

  @Column({ length: 4096, nullable: false })
  public url!: string;

  @ManyToMany(type => Category, {
    eager: true,
    onDelete: 'CASCADE',
    nullable: true,
  })
  @JoinTable()
  public categories?: Category[];
}
```

payload:
```
{
      "name": "Website_1",
      "url": "http://example1.org",
      "categories": [ ]
}
```

produces error:
```
QueryFailedError: syntax error at or near ")"
    at new QueryFailedError (/Users/user/Sites/project/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/Users/user/Sites/project/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/Users/user/Sites/project/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/Users/user/Sites/project/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:321:20)
    at Socket.<anonymous> (/Users/user/Sites/project/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
```

**Comment by artoodeeto** [comment]
Hello can you post the code where the actual usage of the entity is? its a syntax error youre missing and extra `)`

**Comment by scieslickicc** [comment]
> Hello can you post the code where the actual usage of the entity is? its a syntax error youre missing and extra `)`

For now I cannot publish this code (nda) but this 'syntax error' is only for postgresql db, for sqlite its working without error...

**Comment by artoodeeto** [comment]
sorry my friend I cant help you. I'm on the blind spot here. Sometimes what I do I read the actual code. maybe you could start on the very first call stack and trace your error there? sorry man.

**Comment by scieslickicc** [comment]
I have a 'hack' for this situation for postgres to clear manyToMany relation I've set
`categories: [{}]`

so new payload is:
```
{
      "name": "Website_1",
      "url": "http://example1.org",
      "categories": [{}]
}
```
