### ISSUE TITLE
pgcrypto extension does not load with `synchronize: true`

### ISSUE THREAD

**Issue by rhlsthrm** [typeorm/typeorm#5639]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using Postgres syntax in a view query like this:
```
encode(digest("channel"."userPublicIdentifier", 'sha256'), 'hex') as "channelIdentifier"
```

I can run this if I have a migration with the following:
```
await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;`);
```

However, I get an error when I try to run with the option `synchronize: true`:
```
error: error: function digest(text, unknown) does not exist
    at Connection.parseE (/root/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/root/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/root/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 215,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '540',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '516',
  routine: 'ParseFuncOrColumn'
}
```

**Comment by Ginden** [comment]
TypeORM can't know about your custom functions (because Postgres extensions are basically packages with custom functions).
