### ISSUE TITLE
Can't use take and skip alongside order by in querybuilder with joined entities

### ISSUE THREAD

**Issue by Ripper346** [typeorm/typeorm#5670]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm facing the same issue of #2771, #2912 and #3356. I noticed that in all the queries I try to do that involve any type of `join`, the `orderBy` statement can't be used with `take` and/or `skip` methods. The query presented works if I delete the `take/skip` callings or alternatively the `orderBy` call. If I try to make a pagination and calling the `orderBy` method it's thrown an error.

Since I log every query made to my mariadb database I came up with a workaround. It's very dirty but at the moment I will go on with that. I hope in a fix soon. 

Let's start. My entities are: subscription, subscriptionType and subscriptionTypeFeatures. The relations are: 1 to many subscription - subscriptionType and 1 to many subscriptionType - subscriptionTypeFeatures.

I wrote this querybuilder:

```
getAll(args: {} = {}): Promise<Subscription[]> {
    let qb = this.subscriptionsRepository.createQueryBuilder('subscription')
        .leftJoinAndSelect('subscription.subscriptionType', 'subscriptionType')
        .leftJoinAndSelect('subscriptionType.features', 'feature')
        .take(args['take'])
        .skip(args['skip']);
    return qb.orderBy({
        date: "ASC",
        expirationDate: "ASC",
        ...args['orderBy'],
        "feature.priority": "DESC",
        "feature.feature": "ASC"
    }).getMany();
}
```
This produce the error
```[Nest] 40100   - 11/03/2020, 16:17:05   [ExceptionsHandler] ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , `distinctAlias`.`feature_priority`, `distinctAlias`.`feature_feature` FROM (S' at line 1 +2466ms
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , `distinctAlias`.`feature_priority`, `distinctAlias`.`feature_feature` FROM (S' at line 1
    at new QueryFailedError (node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Query.<anonymous> (node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:170:45)
    at Query.<anonymous> (node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (node_modules\mysql\lib\protocol\Protocol.js:38:16)```

### SQL analysis
If we take a look at the query executed there is
```SELECT DISTINCT `distinctAlias`.`subscription_id` as "ids_subscription_id", , , `distinctAlias`.`feature_priority`, `distinctAlias`.`feature_feature` FROM (SELECT `subscription`.`id` AS `subscription_id`, `subscription`.`date` AS `subscription_date`, `subscription`.`expirationDate` AS `subscription_expirationDate`, `subscription`.`subscriptionTypeId` AS `subscription_subscriptionTypeId`, `subscription`.`userId` AS `subscription_userId`, `subscriptionType`.`id` AS `subscriptionType_id`, `subscriptionType`.`name` AS `subscriptionType_name`, `subscriptionType`.`duration` AS `subscriptionType_duration`, `subscriptionType`.`price` AS `subscriptionType_price`, `subscriptionType`.`color` AS `subscriptionType_color`, `subscriptionType`.`description` AS `subscriptionType_description`, `subscriptionType`.`active` AS `subscriptionType_active`, `feature`.`id` AS `feature_id`, `feature`.`feature` AS `feature_feature`, `feature`.`priority` AS `feature_priority`, `feature`.`subscriptionTypeId` AS `feature_subscriptionTypeId` FROM `subscription` `subscription` LEFT JOIN `subscription_type` `subscriptionType` ON `subscriptionType`.`id`=`subscription`.`subscriptionTypeId`  LEFT 
JOIN `subscription_type_feature` `feature` ON `feature`.`subscriptionTypeId`=`subscriptionType`.`id`) `distinctAlias` ORDER BY date ASC, expirationDate ASC, `distinctAlias`.`feature_priority` DESC, `distinctAlias`.`feature_feature` ASC, `subscription_id` ASC LIMIT 1 OFFSET 1```

There are produced two errors: the first is the one reported ```SELECT DISTINCT `distinctAlias`.`subscription_id` as "ids_subscription_id", , , `distinctAlias`.`feature_priority`, `distinctAlias`.`feature_feature` ``` that for some reasons there are empty fields.

The second it's more important and it's the reason why take/skip doesn't work with order. The order statement is placed outside the main query ``` [...] LEFT 
JOIN ... ON ...) `distinctAlias` ORDER BY date ASC, [... other order fields...], `subscription_id` ASC LIMIT 1 OFFSET 1``` the closed parenthesis should be after the order clause and not before to be valid.

### Workaround
Using the sql construct I came up with this workaround:
```
getAll(args: {} = {}): Promise<Subscription[]> {
    let qb = this.subscriptionsRepository.createQueryBuilder('subscription')
        .leftJoinAndSelect('subscription.subscriptionType', 'subscriptionType')
        .leftJoinAndSelect('subscriptionType.features', 'feature');
    qb = qb.orderBy({
        date: "ASC",
        expirationDate: "ASC",
        ...args['orderBy'],
        "feature.priority": "DESC",
        "feature.feature": "ASC"
    });
    if (args['take'] || args['skip']) {
        qb = qb.select('subscription.id').distinct(true);
        if (args['take']) qb.limit(args['take']);
        if (args['skip']) qb.offset(args['skip']);
        qb = this.subscriptionsRepository.createQueryBuilder('subscription')
            .innerJoin(`(${qb.getSql()})`, "filteredSubscriptions", "filteredSubscriptions.subscription_id = subscription.id")
            .leftJoinAndSelect('subscription.subscriptionType', 'subscriptionType')
            .leftJoinAndSelect('subscriptionType.features', 'feature')
            .orderBy({
                date: "ASC",
                expirationDate: "ASC",
                ...args['orderBy'],
                "feature.priority": "DESC",
                "feature.feature": "ASC"
            });
    }
    return qb.getMany();
}
```
So, I don't use anymore `take` and `skip`, instead I create a subquery in which I use `limit` and `offset` and I select only the ids of my main entity. 

In the main query I will have to do the joins, the ordering and a `where` statement in which I filter only the ids limited in the subquery (since I am using mariadb that doesn't support `limit` in `where in` I have to use the `inner join`, they are both equivalent for the result). 

To generalize the concept, if we have also a `where` statement to do, we have to put it only in the subquery that's the one which do all the work. The main one doesn't have to filter anything except the ids.

I hope my explanation was clear enough. If you need more code, like the entities, I can provide them but I think it's pretty clear what it's happening. I tested the queries on multiple cases and the behavior of the errors and the queries is always the same.

**Comment by Ripper346** [comment]
@rennenc if you have where parameterized conditions you have to:
1. add where commands before the if block
2. save the parameters with `const parameters = qb.getParameters()` before the second creation of queryBuilder (let's say as first row of the if block)
3. add `qb = qb.setParameters(parameters);` as last row of the if block to set the where parameters for the new queryBuilder

I managed to make it works in this way with every findOperator (in sql correspondence) except `any` operator that I haven't tested it yet. If you still have undefined parameters you should check the scope of them, I lost a lot of time on it.

**Comment by rennenc** [comment]
Thanks for the reply. I did that exactly and yet still getting an exception that $1 is not set.

**Comment by Ripper346** [comment]
`$1`? I don't know which method you are using to parameterize the expressions, I use the one provided in the documentation [here](https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#adding-where-expression). In this way the SQL should be `?` or empty if it's escaped and the parameter is missing, but not `$1`. My method is tested on mariadb/mysql, I can't help you if you are using something else.

**Comment by mopcweb** [comment]
any news?

**Comment by Ripper346** [comment]
@mopcweb I don't know, since there weren't any news I built a whole generic ecosystem around the workaround I proposed and now I don't have the incentive to try that out. If I bet I would bet about no and not anytime soon, there are bigger problems that aren't fixed yet.

**Comment by Mati365** [comment]
It is shame that so popular framework is not even able to perform simple order by pagination without any kind of bug. Is there any functionality in this library that is critical bug free?

**Comment by madipta** [comment]
i have same problem with postgres, are there workaround  for this?

**Comment by madipta** [comment]
> i have same problem with postgres, are there workaround for this?

using limit and offset works

**Comment by nessur** [comment]
I wrote a function, rewriting parts of `.paginate()` in order get around this problem caused by calling `.getMany()`. 
Calling `.getManyRaw()` uses all the important query builder parts from TypeORM without the double-query behavior.
I'm not sure how to generalize this well, or I'd put in a PR. In the modeling, the `EventEntity` has a `TelemetryEntity` attribute named `telemetry`. 

```
/**
   * TypeORM does not handle joined-models and pagination very well, at all.
   * The second you supply a .take(N) value, it follows a completely different builder plan
   * to generate your results in a two-phase query. The results were at least 100x slower
   * than just doing a join and parsing the objects.
   *
   * this method is yanked from the `typeorm-cursor-pagination/Paginator.paginate()` source,
   * and avoids calling .getMany()
   */
  private paginateEventTelemetry = async (
    query: SelectQueryBuilder<EventEntity>,
    limit: number,
    beforeCursor: string | null,
    afterCursor: string | null,
    order?: GetVehicleEventsOrderOption
  ): Promise<PagingResult<EventEntity>> => {
    const pager = buildPaginator({
      entity: EventEntity,
      alias: 'events',
      paginationKeys: [order?.column ?? 'timestamp', 'id'],
      query: {
        limit,
        order: order?.direction ?? (order?.column === undefined ? 'DESC' : 'ASC'),
        beforeCursor: beforeCursor ?? undefined, // typeorm-cursor-pagination type weirdness
        afterCursor: afterCursor ?? undefined // typeorm-cursor-pagination type weirdness
      }
    })

    /* you have to manually declare a limit, since we're skipping the .take() call that normally happens in .getMany() */
    query.limit(limit + 1)
    const pagedQuery: SelectQueryBuilder<{ event: EventEntity; telemetry: TelemetryEntity }> =
      pager['appendPagingQuery'](query)
    /**
     * results are selected as JSON, so that we can skip the TypeORM entity builder.
     */
    pagedQuery.select('row_to_json(events.*) as event, row_to_json(telemetry.*) as telemetry')
    const results: { event: EventEntity; telemetry: TelemetryEntity }[] = await pagedQuery.getRawMany()
    const entities = results.map(({ event, telemetry }) => ({ ...event, telemetry }))
    const hasMore = entities.length > (limit || 100)
    if (hasMore) {
      entities.splice(entities.length - 1, 1)
    }
    if (entities.length === 0) {
      return pager['toPagingResult'](entities)
    }
    if (!pager['hasAfterCursor']() && pager['hasBeforeCursor']()) {
      entities.reverse()
    }
    if (pager['hasBeforeCursor']() || hasMore) {
      pager['nextAfterCursor'] = pager['encode'](entities[entities.length - 1])
    }
    if (pager['hasAfterCursor']() || (hasMore && pager['hasBeforeCursor']())) {
      pager['nextBeforeCursor'] = pager['encode'](entities[0])
    }
    return pager['toPagingResult'](entities) as PagingResult<EventEntity>
  }
  ```

**Comment by blitzmann** [comment]
> > i have same problem with postgres, are there workaround for this?
> 
> using limit and offset works

From the documentation, `limit` should be avoided when using joined entities

**Comment by Ripper346** [comment]
> From the documentation, `limit` should be avoided when using joined entities

If I may, it is the first time that I heard that `limit` should be avoided, can you link the reason? I don't know if your statement is from the documentation of Postgres or TypeOrm. 

We all know that it is better to load millions of records instead of a bunch of them, of course, we can manipulate time and navigate in a sea full of RAM that even Chrome doesn't know what to do with it but I miss the reason behind

**Comment by blitzmann** [comment]
Is there any more information on this? I made my own issue with my own example: https://github.com/typeorm/typeorm/issues/8014

**Comment by blitzmann** [comment]
> > From the documentation, `limit` should be avoided when using joined entities
> 
> If I may, it is the first time that I heard that `limit` should be avoided, can you link the reason? I don't know if your statement is from the documentation of Postgres or TypeOrm.
> 
> We all know that it is better to load millions of records instead of a bunch of them, of course, we can manipulate time and navigate in a sea full of RAM that even Chrome doesn't know what to do with it but I miss the reason behind

https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/query-builder/SelectQueryBuilder.ts#L910

For what it's worth, using `limit` didn't work for me (my example linked in my above comment), so regardless of what the reason is for avoiding limit with joins, doesn't seem to address this issue :/

**Comment by Ripper346** [comment]
`skip / take` are the correspondent of `offset / limit` of typeorm, if you inspect the code an the queries they do the same thing.

About the recommendation, that's only because `take` should make the work for you but since it doesn't work with the joins, you must use `offset / limit`

**Comment by Azamatjon** [comment]
This problem was resolved in the latest version `0.2.40`

**Comment by Al3x20** [comment]
Hello, is there any news about this issue ? The SQL is still in failure when order by is used with take and skip.
Thanks

**Comment by Ripper346** [comment]
@Al3x20 if it is still in failure I suppose there aren't (at least) any good news

**Comment by Mati365** [comment]
In some cases using `skip` and `take` leads to read all records from table and then filtering from them selected records. It pretty sure could kilka production.

**Comment by fperaltalitebox** [comment]
> In some cases using `skip` and `take` leads to read all records from table and then filtering from all of them selected records. I'm pretty sure it could kill production.

@Mati365  It selects the distinct ids of the primary entity limited by the amout of items you want per page, so you shouldn't have any problem in production!

**Comment by hungluu** [comment]
Still happening in `0.3.26`. It only works without any order by.

**Comment by R3veng3R** [comment]
yeap  0.3.28 still same issue..  any workarounds here?
