### ISSUE TITLE
Many-to-many gives error ER_DUP_ENTRY everytime I save. This one also related to inverseJoinColumn.

### ISSUE THREAD

**Issue by Ouspheaktra** [typeorm/typeorm#5704]
**Issue type:**

[x ] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

``` ts
@Entity()
export class Tag {

  @PrimaryGeneratedColumn()
  id: number;

  @PrimaryColumn()
  title: string;

  @ManyToMany(() => Article, article => article.tags)
  articles: Article[]

}

// ---

@Entity()
export class Article {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @ManyToMany(() => Tag, tag => tag.articles)
  // if no inverseJoinColumn here, it works fine but I need it
  // because in Tag, there are 2 primary columns but I only need one, here.
  @JoinTable({
    inverseJoinColumn: {
      referencedColumnName: 'id'
    }
  })
  tags: Tag[]

}

// ---

createConnection().then(async conn => {

    /* FAKE DATA , uncomment this if u need a fake data
    const article = new Article();
    article.title = 'test'
    const tag = new Tag();
    tag.title = 't';
    await conn.manager.save(tag)
    article.tags = [tag]
    await conn.manager.save(article)
    /* --- */

    const articleRepo = conn.getRepository(Article)
    const one = await articleRepo.findOne(1, { relations: ['tags'] });
    // no error if no load 'tags'
    // I'm not doing any editing, but it still produces error
    await articleRepo.save(one)

    await conn.close()
    console.log('herer')

}).catch(error => console.log(error));

```

This is the error:
```
ER_DUP_ENTRY: Duplicate entry '1-1' for key 'PRIMARY'`.
```

After I look at SQL, I see: 
```sql
INSERT INTO `article_tags_tag`(`articleId`, `tagId`) VALUES (?, ?) -- PARAMETERS: [1,1]
```
There shouldn't be any error because I didn't do any editing at all.

**Comment by vikei** [comment]
Did you find solution?

Have same issue projects <-> categories
```ts
import { Field, ID, ObjectType } from 'type-graphql'
import {
  Column,
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  ManyToMany,
  JoinTable,
} from 'typeorm'
import { UserEntity } from '../users'
import { VacantionEntity } from '../vacantions'
import { CategoryEntity } from '../categories'

@Entity()
@ObjectType('Project')
export class ProjectEntity {
  @PrimaryGeneratedColumn()
  @Field(() => ID)
  id: number

  @Column()
  @Field()
  title: string

  @Column()
  @Field()
  description: string

  @Column()
  @Field()
  ownerId: number

  @ManyToOne(() => UserEntity)
  @Field(() => UserEntity)
  owner: UserEntity

  @OneToMany(
    () => VacantionEntity,
    (v) => v.project
  )
  @Field(() => [VacantionEntity])
  vacantions: VacantionEntity[]

  @ManyToMany(() => CategoryEntity)
  @JoinTable()
  @Field(() => [CategoryEntity])
  categories: CategoryEntity[]
}

import { Field, ID, ObjectType } from 'type-graphql'
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'

@Entity()
@ObjectType('Category')
export class CategoryEntity {
  @PrimaryGeneratedColumn()
  @Field(() => ID)
  id: number

  @Column()
  @Field()
  name: string
}
```

Query to add categories to projects
```ts
  async create(data: CreateProjectData) {
    const { id } = await this.projectsRepository.save(omit(data, ['vacantions', 'categoriesIds']))

    const { vacantions } = data
    if (vacantions) {
      await Promise.all(
        vacantions.map((v) => this.vacantionsService.create({ ...v, projectId: id }))
      )
    }

    const { categoriesIds } = data
    await this.projectsRepository
      .createQueryBuilder()
      .relation('categories')
      .of(id)
      .add(categoriesIds)

    return await this.findOne({ id })
  }
```

Error:
```bash
    query failed: INSERT INTO "project_entity_categories_category_entity"("projectEntityId", "categoryEntityId") VALUES ($1, $2), ($3, $4) -- PARAMETERS: [31,1,31,1]

  console.log node_modules/typeorm/platform/PlatformTools.js:200
    error: error: duplicate key value violates unique constraint "PK_bfd55a65b66f80bfdbdf5910f8e"
        at Connection.Object.<anonymous>.Connection.parseE (/Users/vikei/Kingdom/Team-Organizer/team-organizer.core/node_modules/pg/lib/connection.js:614:13)
        at Connection.Object.<anonymous>.Connection.parseMessage (/Users/vikei/Kingdom/Team-Organizer/team-organizer.core/node_modules/pg/lib/connection.js:413:19)
        at Socket.<anonymous> (/Users/vikei/Kingdom/Team-Organizer/team-organizer.core/node_modules/pg/lib/connection.js:129:22)
        at Socket.emit (events.js:316:20)
        at addChunk (_stream_readable.js:297:12)
        at readableAddChunk (_stream_readable.js:273:9)
        at Socket.Readable.push (_stream_readable.js:214:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
      name: 'error',
      length: 295,
      severity: 'ERROR',
      code: '23505',
      detail: 'Key ("projectEntityId", "categoryEntityId")=(31, 1) already exists.',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'project_entity_categories_category_entity',
      column: undefined,
      dataType: undefined,
      constraint: 'PK_bfd55a65b66f80bfdbdf5910f8e',
      file: 'nbtinsert.c',
      line: '570',
      routine: '_bt_check_unique'
    }
```

**Comment by vikei** [comment]
Set `logger, logging` properties and look at output, it should have two identical rows

```ts
    type: 'postgres',
    url: process.env.PG_URL,
    synchronize: true,
    entities: dbEntities,
    logging: true,
    logger: 'advanced-console',
  })
```

**Comment by Ouspheaktra** [comment]
@vikei the thing is, after I use `findOne()`, I do NOTHING at all. So when I save, it shouldn't be saved. When it saves, it produces such error, that's not strange. The thing is it shouldn't be saved.

**Comment by ygorlazaro** [comment]
Just some of another problem I had with this ORM. https://github.com/typeorm/typeorm/issues/4686

If your project is still in its beginning, it's better to move on to another ORM.

I just did it with a project with 220k lines and 40k simultaneous access. Totally worth it.

**Comment by shubhamR1997** [comment]
In respect to the above example, you have to make sure the Tag id in the object you are passing on to the save function should be of the same type as it is in the entity (e.g number). I was having the same issue for updating the @manytomany relation every time it was throwing the duplicate key error unless I saw the data object was having the id in a string instead of a number when I manually change the id to number by iterating the array then it was updating the things without any error. Hope it helps someone facing the same issue.

**Comment by rolandvar** [comment]
> @vikei the thing is, after I use `findOne()`, I do NOTHING at all. So when I save, it shouldn't be saved. When it saves, it produces such error, that's not strange. The thing is it shouldn't be saved. It shouldn't INSERT new row into database because such row already exists.

Hi, I've been going crazy on this issue for days.

Have you found a solution?

**Comment by aleksey-tk** [comment]
Also have this issue. For now no solution found, but i will have to dig into it at some point. The dumb thing to do - remove your many 2 many relation from object before save() in order not to trigger this error, but test thoroughly that it is not getting removed in the db afterwards (i doubt so, but anyway)

**Comment by NadaTO** [comment]
> In respect to the above example, you have to make sure the Tag id in the object you are passing on to the save function should be of the same type as it is in the entity (e.g number). I was having the same issue for updating the @manytomany relation every time it was throwing the duplicate key error unless I saw the data object was having the id in a string instead of a number when I manually change the id to number by iterating the array then it was updating the things without any error. Hope it helps someone facing the same issue.
