### ISSUE TITLE
BaseEntity remove issue with onDelete: "RESTRICT"

### ISSUE THREAD

**Issue by changhoi** [typeorm/typeorm#5707]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I used v 0.2.24.

I think there is issue related with `onDelete: "RESTRICT"`.
these are my entities.

```ts
// Item.entity.ts
 import {
  Entity,
  BaseEntity,
  PrimaryGeneratedColumn,
  ManyToOne
} from "typeorm";
import ItemInfo from "./ItemInfo.entity";

@Entity()
class Item extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

// ...

  @ManyToOne(
    type => ItemInfo,
    itemInfo => itemInfo.instances,
    {cascade: true, onDelete: "RESTRICT"}
  )
  info: ItemInfo | number;
}
```
```ts
// ItemInfo.entity.ts
import {Entity, BaseEntity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import Item from "./Item.entity";

@Entity()
class ItemInfo extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

// ...

  @OneToMany(
    type => Item,
    item => item.info
  )
  instances?: Item[] | number[];
}
```

this is my test code

```ts
describe("remove test", () => {
    test("Delete itemInfo if there is no relation.", async () => {
      const beforeCreate = await ItemInfo.count();
      const itemInfo = await ItemInfo.create(itemInfoRequired).save();
      const itemInfoWithRelattions = await ItemInfo.findOne(itemInfo.id, {
        relations: ["instances"]
      }); 
      console.log(itemInfoWithRelattions); // check no instance relation
      const ret = await ItemInfo.remove();
//or await (await itemInfo.remove()).save();  // remove is triggered both way
      const afterRemove = await ItemInfo.count();

      expect(beforeCreate).toBe(afterRemove);
      expect(ret.success).toBeTruthy();
    });
```

expect:
I think it should be passed because `itemInfo` has no item relation, `instances`

result:
```bash
console.log tests/services/adminService.test.ts:82
    ItemInfo {
      id: 17,
# ...
      instances: []
    }

  console.log node_modules/typeorm/platform/PlatformTools.js:200
    query failed: DELETE FROM "item_info" WHERE "id" = $1 -- PARAMETERS: [19]

  console.log node_modules/typeorm/platform/PlatformTools.js:200
    error: error: update or delete on table "item_info" violates foreign key constraint "FK_0a7024aa3e4182afe3d75b84fc5" on table "item"
        at Connection.Object.<anonymous>.Connection.parseE (/Users/changhoi/dev/pilltong/deliverypharmacy/backend-core/node_modules/pg/lib/connection.js:614:13)
        at Connection.Object.<anonymous>.Connection.parseMessage (/Users/changhoi/dev/pilltong/deliverypharmacy/backend-core/node_modules/pg/lib/connection.js:413:19)
        at Socket.<anonymous> (/Users/changhoi/dev/pilltong/deliverypharmacy/backend-core/node_modules/pg/lib/connection.js:129:22)
        at Socket.emit (events.js:311:20)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:209:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
      name: 'error',
      length: 287,
      severity: 'ERROR',
      code: '23503',
      detail: 'Key (id)=(19) is still referenced from table "item".',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'item',
      column: undefined,
      dataType: undefined,
      constraint: 'FK_0a7024aa3e4182afe3d75b84fc5',
      file: 'ri_triggers.c',
      line: '3280',
      routine: 'ri_ReportViolation'
    }
```

**Comment by changhoi** [comment]
My mistakes sorry
