### ISSUE TITLE
orderBy option in Entity cause GROUP BY clause and undefined error.

### ISSUE THREAD

**Issue by firmanjml** [typeorm/typeorm#5725]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. add orderBy option in "@Entity" decorator
2. maybe add relations to other entity
3. run any .find() method and you will get an error.

I have been getting two different errors at the time, sometimes "GROUP BY clause or be used in an aggregate function" and sometimes "syntax error at or near 'undefined'".

Error Output
```
QueryFailedError: syntax error at or near "undefined"
    at new QueryFailedError (/Users/firmanjamal/Documents/KibblePaw-Server/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/firmanjamal/Documents/KibblePaw-Server/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/firmanjamal/Documents/KibblePaw-Server/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/Users/firmanjamal/Documents/KibblePaw-Server/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:223:5)
    at Socket.<anonymous> (/Users/firmanjamal/Documents/KibblePaw-Server/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10) {
  message: 'syntax error at or near "undefined"',
  name: 'QueryFailedError',
  length: 99,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '188',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1149',
  routine: 'scanner_yyerror',
  query: 'SELECT "listing"."sellerId" AS "parentId", COUNT(*) AS "cnt" FROM "listing" "listing" WHERE "listing"."sellerId" IN ($1) GROUP BY "listing"."sellerId" ORDER BY "listing"."createdAt" DESC undefined',
  parameters: [ '8406978c-d695-4261-a87d-2d3a0224983c' ]
}
```

Listing.ts
```
@Entity({
    orderBy: {
        createdAt: {
            order: "DESC"
        }
    }
})
export class Listing extends BaseEntity {
    @PrimaryGeneratedColumn("uuid")
    id: string;

    @Index()
    @Column()
    name: string;

    @Column()
    sellerId: string;

    @ManyToOne(() => Profile)
    @JoinColumn()
    seller: Profile;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
```

Profile.ts
```
@Entity({
    orderBy: {
         createdAt: "DESC"
     }
})
export class Profile extends BaseEntity {

    @PrimaryColumn()
    id: string;

    @Column({ select: false })
    email: string;

    @Index()
    @Column({ unique: true })
    username: string;

    @OneToMany(() => Listing, listing => listing.seller)
    listings: Listing[];

    @RelationCount((user: Profile) => user.listings)
    listingCount: number;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
```

Get Profile 
```
const profile = await Profile.findOne({
                where: [
                    {
                        email: "firmanjml"
                    },
                    {
                        username: "firmanjml"
                    }
                ]
            });

```

**Comment by firmanjml** [comment]
I found the root cause of the problem, it is caused by @RelationCount decorator. Seems like it orders the RelationCount statement as well.

**Comment by firmanjml** [comment]
I can confirm that I have found the root cause and it's caused by @RelationCount() decorator. It seems that it adds ORDER BY in count sql statement as well.

**Comment by jim-obrien-orig** [comment]
I'm not using the `@RelationCount()` decorator, but the `loadRelationCountAndMap()` function in queryBuilder, and encountering the same problem.
