### ISSUE TITLE
Tests fail with error: collation "en_US" for encoding "UTF8" does not exist

### ISSUE THREAD

**Issue by golergka** [typeorm/typeorm#5741]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Clone TypeORM repository
2. Checkout 0.2.22 tag
3. Create a new local Postgresql database, with extensions `cube` and `uuid-ossp`, and create appropriate ormconfig
4. Run `npm install && npm test`

**Expected result:**

All tests run successfully.

**Actual result:**

Tests fail at:
```
  database schema > column collation > postgres
    1) "before each" hook for "should correctly create column with collation option"


  56 passing (7s)
  4 pending
  1 failing

  1) database schema > column collation > postgres
       "before each" hook for "should correctly create column with collation option":
     QueryFailedError: collation "en_US" for encoding "UTF8" does not exist
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at Query.callback (src/driver/postgres/PostgresQueryRunner.ts:178:30)
      at Query.handleError (node_modules/pg/lib/query.js:142:17)
      at Connection.connectedErrorMessageHandler (node_modules/pg/lib/client.js:160:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:125:12)
      at addChunk (_stream_readable.js:332:12)
      at readableAddChunk (_stream_readable.js:307:11)
      at Socket.Readable.push (_stream_readable.js:241:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:185:23)
```

**Discussion:**

It seems as if there's some setup step for tests that I didn't figure out?

I already have stumbled upon the fact that neccessary Postgresql extensions (`cube` and `uuid-ossp`) aren't metion in documentation, and wanted to create a PR with them later.

**Comment by imnotjames** [comment]
Try with the docker containers.  Works here and in CI.
