### ISSUE TITLE
Wrong entity listeners triggered when using ChildEntities (with TableInheritance)

### ISSUE THREAD

**Issue by KennyDurand** [typeorm/typeorm#5825]
**Issue type:** bug report

**Database system/driver:** Probably all (tested with `postgres`)

**TypeORM version:** `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

Considering this model:
```
@Entity()
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
class A {}

@ChildEntity()
export class B extends A {
  @BeforeInsert()
  @BeforeUpdate()
  onInsertOrUpdate() {
    // do stuff
  }
}


@ChildEntity()
export class C extends A {
  // No listener defined
}
```

When saving entities of class `C` using the Repository for class `A`, an error will occur:
```
TypeError: entity[this.propertyName] is not a function
    at EntityListenerMetadata.execute (/project/path/node_modules/typeorm/metadata/EntityListenerMetadata.js:32:45)
    at /project/path/node_modules/typeorm/subscriber/Broadcaster.js:66:52
    at Array.forEach (<anonymous>)
    at Broadcaster.broadcastBeforeUpdateEvent (/project/path/node_modules/typeorm/subscriber/Broadcaster.js:64:44)
    at /project/path/node_modules/typeorm/persistence/SubjectExecutor.js:189:99
    at Array.forEach (<anonymous>)
    at SubjectExecutor.broadcastBeforeEventsForAll (/project/path/node_modules/typeorm/persistence/SubjectExecutor.js:189:33)
    at SubjectExecutor.<anonymous> (/project/path/node_modules/typeorm/persistence/SubjectExecutor.js:76:50)
    at step (/project/path/node_modules/tslib/tslib.js:136:27)
    at Object.next (/project/path/node_modules/tslib/tslib.js:117:57)
```

This is due to TypeORM trying to execute method `onInsertOrUpdate` on a `C` entity. Metadata seem to detect all listeners for `A` sub-classes, rather than only sticking on the corresponding subclass metadata.

**Comment by danilexx** [comment]
Same error here, but Subscriber still works

**Comment by kalinichenko88** [comment]
Same issue with sqlite and typeorm 0.2.25

**Comment by mariuszbeltowski** [comment]
Same here

**Comment by andynunes** [comment]
Facing this issue as well, leaving no way to set a default value for a boolean column.

Due to https://github.com/typeorm/typeorm/issues/3799 not being fixed, I can't use `@Column({ type: 'boolean', default: 'false' })`.

The following `@BeforeInsert` method causes the `TypeError: entity[this.propertyName] is not a function` error:
```
@ChildEntity()
export class ChildEntity extends ParentEntity {

    @Column()
    shouldRecommend?: boolean;

    @BeforeInsert()
    setDefaults() {
        if (this.shouldRecommend === undefined) {
            this.shouldRecommend = false;
        }
    }
}
```

Is anyone able to work on a fix?

**Comment by PatrickHallek** [comment]
Same here, I had to do a super dirty workaround while moving the logic to the top level entity and make the manipulated property optional. I am more than unhappy with that solution. A real fix would be great!

**Comment by swordofwolf** [comment]
I have very bad way to deal with it. 
In EntityListenerMetadata.js in 37 line
I change 
      "return entity[this.propertyName]();"
On
      "if (entity[typeof this.propertyName] === "function") {
                return entity[this.propertyName]();
       }else return entity[this.propertyName];"

it is not clever, but it works )

**Comment by LuckyArdhika** [comment]
> I have very bad way to deal with it. In EntityListenerMetadata.js in 37 line I change ` return entity[this.propertyName]();` On
> 
> ```
>       if (entity[typeof this.propertyName] === "function") {
>                 return entity[this.propertyName]();
>        }else return entity[this.propertyName];
> ```
> 
> it is not clever, but it works )

you cannot edit deps bro, its can cause error when u install the module from original source like "npm i".

**Comment by YhomiAce** [comment]
I'm getting this error while trying to load some data in the child entity in AfterLoad method.
This error is only happening to me in Production.

**Comment by eliasyishak** [comment]
This may or may not help someone later but i found that i ran into error for an entity i created but did not add to the list of data source entities

**Comment by thegrandpoobah** [comment]
A solution is to define the method on the base class and hen override it on the child class:

base:
```
@Entity()
@TableInheritance({ column: { type: 'varchar', name: 'entityType' } })
export abstract class BaseEntity {
  @AfterLoad()
  doStuff() { /* contents left intentionally blank */ }
}
```

child:
```
@ChildEntity()
export class AssetDocument extends Document {
  @AfterLoad()
  doStuff() { console.log('really doing things now') }
}
```

its ugly imo, but its a workaround..

**Comment by gioboa** [comment]
Closed by #12219
