### ISSUE TITLE
How can I left-join query with TypeOrm

### ISSUE THREAD

**Issue by resotto** [typeorm/typeorm#5900]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
There are some tables:

```
CREATE TABLE a (
  a_id serial PRIMARY KEY,
  name text
);

CREATE TABLE b (
  a_id integer REFERENCES a (a_id),
  name text
);

CREATE TABLE c (
  a_id integer REFERENCES a (a_id),
  name text
);
```

And then I want to query something like this:

```
SELECT * FROM a
LEFT JOIN b USING (a_id)
LEFT JOIN c USING (a_id)
;
```

How do I query above with TypeOrm?

**Comment by Flusinerd** [comment]
Hey,
take a look at this part of the docs:
[Query Builder Relations](https://typeorm.io/#/select-query-builder/joining-relations)
or you can do it using the find.options.relations:
[Find Options](https://typeorm.io/#/find-options)

**Comment by resotto** [comment]
@Flusinerd
Thank you for your fast replying.
I just tried QueryBuilder with something like this:

```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';
import { BDbModel } from './b.entity';

@Entity({ schema: 'public', name: 'a' })
export class ADbModel {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'text' })
  name!: string;

  b!: BDbModel;
}
```
```
import { Entity, ManyToOne, JoinColumn, Column } from 'typeorm';
import { ADbModel } from './a.entity';

@Entity({ schema: 'public', name: 'b' })
export class BDbModel {
  @ManyToOne(() => ADbModel, { primary: true })
  @JoinColumn({ name: 'id' })
  a!: ADbModel;

  @Column({ type: 'text' })
  name!: string;
}
```
```
  const aDbModel = await conn
    .getRepository(ADbModel)
    .createQueryBuilder('a')
    .leftJoinAndSelect('b', 'b', 'b.a_id = a.a_id')
    .where('a.id = :id', { id: 1 })
    .getRawOne();
  // .getOne();
```

When I used `.getOne()`, I couldn't get the value of `b.name` in return value.
When I used `.getRawOne()`, I could get the value in return value, but type of return value was just object, not `ADbModel` (entity of a).

So could I get the value of `b.name` with `ADbModel` (entity type)?

**Comment by Flusinerd** [comment]
Wouldnt it be
```
.leftJoinAndSelect('a.b', 'b', 'b.a_id = a.ai_id')
```

**Comment by resotto** [comment]
Thanks a lot, but it didn't work:

This is current table states:
```
postgres=# \d a
                            Table "public.a"
 Column |  Type   | Collation | Nullable |            Default
--------+---------+-----------+----------+-------------------------------
 a_id   | integer |           | not null | nextval('a_id_seq'::regclass)
 name   | text    |           | not null |
Indexes:
    "PK_4389d345cf0a29dba3be07b30b1" PRIMARY KEY, btree (a_id)
Referenced by:
    TABLE "c" CONSTRAINT "FK_27efbcef7015a25e0bb22d32801" FOREIGN KEY (a_id) REFERENCES a(a_id)
    TABLE "b" CONSTRAINT "FK_c42e9e2e18e2afc34fc9260002d" FOREIGN KEY (a_id) REFERENCES a(a_id)

postgres=# \d b
                 Table "public.b"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 name   | text    |           | not null |
 a_id   | integer |           | not null |
Indexes:
    "PK_c42e9e2e18e2afc34fc9260002d" PRIMARY KEY, btree (a_id)
Foreign-key constraints:
    "FK_c42e9e2e18e2afc34fc9260002d" FOREIGN KEY (a_id) REFERENCES a(a_id)

postgres=# \d c
                 Table "public.c"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 name   | text    |           | not null |
 a_id   | integer |           | not null |
Indexes:
    "PK_27efbcef7015a25e0bb22d32801" PRIMARY KEY, btree (a_id)
Foreign-key constraints:
    "FK_27efbcef7015a25e0bb22d32801" FOREIGN KEY (a_id) REFERENCES a(a_id)
```

record exists:
```
postgres=# select * from a left join b using(a_id) left join c using(a_id);
 a_id | name  |  name  | name
------+-------+--------+-------
    1 | apple | orange | lemon
(1 row)
```



A data model:
```
@Entity({ schema: 'public', name: 'a' })
export class ADbModel {
  @PrimaryGeneratedColumn({ name: 'a_id' })
  id!: number;

  @Column({ type: 'text' })
  name!: string;

  b!: BDbModel;
}
```

B data model:
```
import { Entity, ManyToOne, JoinColumn, Column } from 'typeorm';
import { ADbModel } from './a.entity';

@Entity({ schema: 'public', name: 'b' })
export class BDbModel {
  @ManyToOne(() => ADbModel, { primary: true })
  @JoinColumn({ name: 'a_id' })
  a!: ADbModel;

  @Column({ type: 'text' })
  name!: string;
}
```

And query is:
```
  const aDbModel = await conn
    .getRepository(ADbModel)
    .createQueryBuilder('a')
    .leftJoinAndSelect('a.b', 'b', 'b.a_id = a.ai_id')
    .where('a.id = :id', { id: 1 })
    .getOne();
```

query above returned following error:
```
➜  app git:(master) ✗ ts-node src/index.ts
(node:95931) UnhandledPromiseRejectionWarning: Error: Relation with property path b in entity was not found.
    at JoinAttribute.getValue (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/JoinAttribute.ts:160:23)
    at JoinAttribute.get [as relation] (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/JoinAttribute.ts:162:53)
    at JoinAttribute.get [as metadata] (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/JoinAttribute.ts:175:18)
    at SelectQueryBuilder.join (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/SelectQueryBuilder.ts:1325:27)
    at SelectQueryBuilder.leftJoin (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/SelectQueryBuilder.ts:302:14)
    at SelectQueryBuilder.leftJoinAndSelect (/Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/query-builder/SelectQueryBuilder.ts:382:14)
    at /Users/akiratoyoshima/develop/git/exploring-typeorm/app/src/index.ts:8:6
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:95931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:95931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Flusinerd** [comment]
Try adding this decorator to your a-model
```
@OneToMany( type =>BDbModel, b => b.a)
b!: BDbModel[];
```

I think the error is because it cannot find the relation (Only defined from b-side not from the a-side)

Then you should be able to do the following:
```
.leftJoinAndSelect('a.b', 'b',)
```

Thats how I do it.

**Comment by resotto** [comment]
Thank you so much.
It didn't work, but should I set bi-directional relation between ADbModel and BDbModel to accomplish my purpose?

**Comment by Flusinerd** [comment]
For your usecase, I would do it from both sides, since you want to access all B-Models from the A-Side.
But I am not deeply into typeorm to be 100% sure on that.

Maybe someone else can clarify.

**Comment by resotto** [comment]
That makes sense.
Your advice got me advanced a lot.
Thank you so much again.

**Comment by resotto** [comment]
@Flusinerd 
Excuse me I forgot to transpile *.ts.
And then your code worked!!!!
I really appreciate your help.

ADbModel
```
@Entity({ schema: 'public', name: 'a' })
export class ADbModel {
  @PrimaryGeneratedColumn({ name: 'a_id' })
  id!: number;

  @Column({ type: 'text' })
  name!: string;

  @OneToMany(() => BDbModel, (b) => b.a)
  b!: BDbModel[];
}
```

BDbModel
```
@Entity({ schema: 'public', name: 'b' })
export class BDbModel {
  @ManyToOne(() => ADbModel, { primary: true })
  @JoinColumn({ name: 'a_id' })
  a!: ADbModel;

  @Column({ type: 'text' })
  name!: string;
}

```

And query
```
  const aDbModel = await conn
    .getRepository(ADbModel)
    .createQueryBuilder('a')
    .leftJoinAndSelect('a.b', 'b')
    .where('a.a_id = :id', { id: 1 })
    .getOne();
```

returned
```
➜  app git:(master) ✗ ts-node src/index.ts
ADbModel { id: 1, name: 'apple', b: [ BDbModel { name: 'orange' } ] }
```

**Comment by Flusinerd** [comment]
Glad to hear that :)
Issue can now be closed I guess

**Comment by resotto** [comment]
Thank you.
OK, I close this issue.
