### ISSUE TITLE
Postgres connection error. Mysql package has not been found installed.

### ISSUE THREAD

**Issue by vishnu-dev** [typeorm/typeorm#5911]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Below is my app module. It has initialized typeorm with type `postgres`. When I start the application using `nest start`, it says `DriverPackageNotInstalledError: Mysql package has not been found installed. Try to install it: npm install mysql --save`. Is this a bug or am I doing something wrong here?

```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UsersModule } from './users/users.module';
import { ClientsModule } from './clients/clients.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DBCred } from '../config/db/sumyag';
import { Clients } from './clients/clients.entity';

@Module({
  imports: [
    UsersModule,
    ClientsModule,
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: DBCred.HOSTNAME,
      port: DBCred.PORT,
      username: DBCred.USERNAME,
      password: DBCred.PASSWORD,
      database: DBCred.DATABASE,
      entities: [Clients],
      synchronize: true,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
}

```
The error

```shell
[Nest] 15029   - 04/20/2020, 12:52:22 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3009ms
DriverPackageNotInstalledError: Mysql package has not been found installed. Try to install it: npm install mysql --save
at new DriverPackageNotInstalledError (/redacted-path/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
at MysqlDriver.loadDependencies (/redacted-path/node_modules/typeorm/driver/mysql/MysqlDriver.js:743:23)
at new MysqlDriver (/redacted-path/node_modules/typeorm/driver/mysql/MysqlDriver.js:243:14)
at DriverFactory.create (/redacted-path/node_modules/typeorm/driver/DriverFactory.js:31:24)
at new Connection (/redacted-path/node_modules/typeorm/connection/Connection.js:53:59)
at ConnectionManager.create (/redacted-path/node_modules/typeorm/connection/ConnectionManager.js:56:26)
at Object.<anonymous> (/redacted-path/node_modules/typeorm/index.js:207:66)
at step (/redacted-path/node_modules/tslib/tslib.js:139:27)
at Object.next (/redacted-path/node_modules/tslib/tslib.js:120:57)
at /redacted-path/node_modules/tslib/tslib.js:113:75
```

**Comment by vishnu-dev** [comment]
Deleting the `dist` folder worked for me. It is quite weird.
