### ISSUE TITLE
    TypeError: typeorm_1.PrimaryGeneratedColumn is not a function

### ISSUE THREAD

**Issue by thibault-lr** [typeorm/typeorm#5918]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm having an issue when I try to perform unit tests on a controller that uses a typeorm model. I'm posting it here as I don't know if the issue is linked to ts-jest or typeorm.

I have a very small controller that I want to test : 
`class Album {
  public static getAlbums(): Promise<AlbumModel[]> {
    return getRepository(AlbumModel).find();
  }
}`

This one is related to an entity 
`@Entity({
  name: 'T_ALBUM_AL',
  synchronize: true,
})
export class AlbumModel {
  @PrimaryGeneratedColumn({
    name: 'AL_id',
  })
  id: number;

  @Column({
    name: 'AL_name',
  })
  name: string;
}`

And this is the unit test. I want to make sure that getRepository and find are called, so I did a test like this :: 
```
import Album from './album.controller';

const getRepMock = jest.fn(() => ({
  find: jest.fn().mockImplementation(),
}));

jest.mock('typeorm', () => ({
  getRepository: getRepMock,
}));

describe('Album', () => {
  it('Should work', () => {
    Album.getAlbums();
    expect(getRepMock).toBeCalled();
  });
});
```

When I execute my test using ts-jest, I have the following error   
` ● Test suite failed to run

    TypeError: typeorm_1.PrimaryGeneratedColumn is not a function

       6 | })
       7 | export class AlbumModel {
    >  8 |   @PrimaryGeneratedColumn({
         |    ^
       9 |     name: 'AL_id',
      10 |   })
      11 |   id: number;

      at src/album.model.ts:8:4
      at Object.<anonymous> (src/album.model.ts:7:1)
      at Object.<anonymous> (src/album.controller.ts:2:1)`

I'm using node  11.15.0. 

I also created a small repo : https://github.com/thibault-lr/decorator-issue

I would love to know why it doesn't work, thanks in advance

**Comment by thibault-lr** [comment]
Ok I found it out after a while. It seems that I needed to also mock those typeorm decorators functions 👍 
`import { Repository }from 'typeorm';
import { mock } from 'jest-mock-extended';

const repoMock = mock<Repository<any>>();
import Album from './album.controller';

jest.mock('typeorm', () => {
  repoMock.find.mockResolvedValue(['ok']);

  return {
    getRepository: () => repoMock,
    PrimaryGeneratedColumn: () => {},
    Column: () => {},
    Entity: () => {}
  }
});


describe('Album', () => {
  it('Should work', async () => {

    const res = await Album.getAlbums();

    expect(res.length).toBe(1)
  });
});

`
