### ISSUE TITLE
Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.

### ISSUE THREAD

**Issue by leixu2txtek** [typeorm/typeorm#592]
stack:

```javascript
Error: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
    at new AlreadyHasActiveConnectionError (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\src\connection\error\AlreadyHasActiveConnectionError.ts:11:22)
    at ConnectionManager.create (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\src\connection\ConnectionManager.ts:61:23)
    at Object.<anonymous> (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\src\index.ts:148:35)
    at step (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\node_modules\typeorm\index.js:32:23)
    at Object.next (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\node_modules\typeorm\index.js:13:53)
    at c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\node_modules\typeorm\index.js:7:71
    at Promise (<anonymous>)
    at __awaiter (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\node_modules\typeorm\index.js:3:12)
    at Object.createConnection (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\node_modules\typeorm\index.js:161:12)
    at Object.<anonymous> (c:\Users\leixu2txtek\Documents\Workbench\uethinking\org-admin.server\src\routers\shops.ts:44:30)
```

my code:

```javascript

    const connection = await createConnection({
        type: 'mysql',
        driver: config.database.youk,
        entities: [Shop],
        logging: config.orm.logging
    });

    let query = connection.getRepository(Shop).createQueryBuilder('shop').where('1=1');
```

where am I wrong?

operating system: windows 10 15063;
node: 8.0.0;
typeorm:0.1.0-alpha.19

thx a lot

**Comment by leixu2txtek** [comment]
create  connect in each request ..
Is that right ?

**Comment by sbacem** [comment]
i think is better to create one connection for db.
you can see this example   [this](https://github.com/typeorm/typescript-express-example/blob/master/src/index.ts)
in controller like [this ](https://github.com/typeorm/typescript-express-example/blob/master/src/controller/PostSaveAction.ts)

**Comment by pleerock** [comment]
@sbacem is correct. You should have a single connection in your app (you actually creating connection pool, and on each request when you use orm functions they are using different connections from the pool)

**Comment by leixu2txtek** [comment]
@sbacem Thanks for your reply..  I have to do some try.

**Comment by leixu2txtek** [comment]
@pleerock Awesome project ...  Thank you very much .

**Comment by leixu2txtek** [comment]
If I use multiple database , how can I config with connection manager?
@sbacem @pleerock sorry for my pool english .

**Comment by leixu2txtek** [comment]
it works well ..
Thanks a lot. :)

**Comment by guilhermemiua** [comment]
> @sbacem is correct. You should have a single connection in your app (you actually creating connection pool, and on each request when you use orm functions they are using different connections from the pool)

Hello! Do they close the connection after using the orm function? Actually, I'm creating some microservices that connects to two or more databases each, I need to connect to the database only when I'm doing a query, and after finishing the query I need to close the connection, for performance issues. If it doesn't close, how can I connect to several databases only when needed? Thank you very much! :)
