### ISSUE TITLE
"character" ColumnType not supported by MySQL

### ISSUE THREAD

**Issue by stevendesu** [typeorm/typeorm#5943]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Per https://github.com/typeorm/typeorm/blob/master/src/driver/types/ColumnTypes.ts#L61 it looks like the `"character"` ColumnType should work in: "mysql, postgres, sqlite, cockroachdb"

I created the following entity:

```
export default class Token extends BaseEntity
{
    @Column({
        type: "character",
        length: 36
    })
    jti: string;
}
```

I wanted a constant-length field for storing a UUID (versus the default 255-character variable-length field). This worked fine in SQLite, but when I tried MySQL I got the error:

```
 (node:18) UnhandledPromiseRejectionWarning: DataTypeNotSupportedError: Data type "character" in "Token.jti" is not supported by "mysql" database.
     at new DataTypeNotSupportedError (/usr/src/app/node_modules/typeorm/error/DataTypeNotSupportedError.js:7:28)
     at /usr/src/app/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:74:27
     at Array.forEach (<anonymous>)
     at EntityMetadataValidator.validate (/usr/src/app/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:71:36)
     at /usr/src/app/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:42:74
     at Array.forEach (<anonymous>)
     at EntityMetadataValidator.validateMany (/usr/src/app/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:42:25)
     at Connection.buildMetadatas (/usr/src/app/node_modules/typeorm/connection/Connection.js:497:33)
     at Connection.<anonymous> (/usr/src/app/node_modules/typeorm/connection/Connection.js:127:30)
     at step (/usr/src/app/node_modules/tslib/tslib.js:139:27)
 (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mguida22** [comment]
In mysql the character column type is char
