### ISSUE TITLE
Are there any specialities between mysql2 and typeorm?

### ISSUE THREAD

**Issue by bude10** [typeorm/typeorm#5956]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**MySql2 version:**

[x] `1.7.0`

**Steps to reproduce or a small repository showing the problem:**

I want to update the field icon_id of my app
```
const app: App = await this.connection.getRepository(App).findOne({
      where: { uuid: appUuid },
      relations: ['iconReference']
    });
app.iconReferenceId = file.id;
await txn.getRepository(App).save(app);
```
Saving the whole entity causes a SQL syntax error, that syntax isn't correct.
```
QueryFailedError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1
    at new QueryFailedError (C:\projects\source.sick.com\apppool-backend\.build\src\error\QueryFailedError.ts:9:9)
    at Query.onResult (C:\projects\source.sick.com\apppool-backend\.build\src\driver\mysql\MysqlQueryRunner.ts:167:37)
    at Query.execute (C:\projects\source.sick.com\apppool-backend\.build\node_modules\mysql2\lib\commands\command.js:30:14)
    at PoolConnection.handlePacket (C:\projects\source.sick.com\apppool-backend\.build\node_modules\mysql2\lib\connection.js:408:32)    at PacketParser.onPacket (C:\projects\source.sick.com\apppool-backend\.build\node_modules\mysql2\lib\connection.js:70:12)
    at PacketParser.executeStart (C:\projects\source.sick.com\apppool-backend\.build\node_modules\mysql2\lib\packet_parser.js:75:16)    at Socket.<anonymous> (C:\projects\source.sick.com\apppool-backend\.build\node_modules\mysql2\lib\connection.js:77:25)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
  message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1",
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1",
  name: 'QueryFailedError',
  query: 'UPDATE `app` SET `icon_reference_id` = ?, `icon_reference_id` = ? WHERE `id` IN (?)',
  parameters: [ 11, 224 ]
```
Do I have to consider any specialities between mysql2 and typeorm, e.g. different versions, that aren't compatible to each other?
Writing my custom query works perfect:
```
await txn.getRepository(App).query( 'UPDATE app SET icon_reference_id = ? WHERE id IN (?)', [ app.iconReferenceId, app.id ] );
```

**Comment by imnotjames** [comment]
Is this still an issue in 0.2.27?

**Comment by imnotjames** [comment]
We're cleaning up the backlog and it seems like this shouldn't be an issue now.

Feel free to respond back with more info & we can reopen it.
