### ISSUE TITLE
TypeError: Cannot read property 'joinColumns' of undefined

### ISSUE THREAD

**Issue by avchugaev** [typeorm/typeorm#5986]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I build an application with NestJS and TypeORM. A part of the data model looks like this (I do use the Active Record approach):

**RichMessage** entity:

```ts
import { BaseEntity, Column, CreateDateColumn, Entity, Index, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { RichMessageReactionEntity } from './rich-message-reaction.entity';

@Entity({
  name: 'message',
  schema: 'mod_rich_message'
})
export class RichMessageEntity extends BaseEntity {
  @PrimaryGeneratedColumn('uuid', { name: 'id' })
  id!: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp' })
  @Index()
  createdAt!: Date;

  @Column({ name: 'message_id', type: 'varchar', unique: true })
  messageId!: string;

  @Column({ name: 'channel_id', type: 'varchar' })
  channelId!: string;

  @OneToMany(() => RichMessageReactionEntity, reaction => reaction.message, { eager: true, cascade: true })
  reactions!: Array<RichMessageReactionEntity>;
}
```

**RichMessageReaction** entity:

```ts
import { BaseEntity, Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { RichMessageEntity } from './rich-message.entity';

export interface Command {
  action: string;
  payload?: any;
}

@Entity({
  name: 'reaction',
  schema: 'mod_rich_message'
})
export class RichMessageReactionEntity extends BaseEntity {
  @PrimaryGeneratedColumn('uuid', { name: 'id' })
  id!: string;

  @JoinColumn({ name: 'message_id', referencedColumnName: 'id' })
  @ManyToOne(() => RichMessageEntity, message => message.reactions, { onDelete: 'CASCADE' })
  message!: RichMessageEntity;

  @Column({ name: 'emoji', type: 'varchar', length: 32 })
  emoji!: string;

  @Column({ name: 'on_add', type: 'jsonb', nullable: true })
  onAdd?: Command;

  @Column({ name: 'on_remove', type: 'jsonb', nullable: true })
  onRemove?: Command;
}
```

It seems alright, all relations are properly configured, but I've got this error and can't manage to solve it:

```
query: SELECT "RichMessageEntity"."id" AS "RichMessageEntity_id", "RichMessageEntity"."created_at" AS "RichMessageEntity_created_at", "RichMessageEntity"."message_id" AS "RichMessageEntity_message_id", "RichMessageEntity"."channel_i
d" AS "RichMessageEntity_channel_id", "RichMessageEntity_reactions"."id" AS "RichMessageEntity_reactions_id", "RichMessageEntity_reactions"."emoji" AS "RichMessageEntity_reactions_emoji", "RichMessageEntity_reactions"."on_add" AS "R
ichMessageEntity_reactions_on_add", "RichMessageEntity_reactions"."on_remove" AS "RichMessageEntity_reactions_on_remove", "RichMessageEntity_reactions"."message_id" AS "RichMessageEntity_reactions_message_id" FROM "mod_rich_message"
."message" "RichMessageEntity" LEFT JOIN "mod_rich_message"."reaction" "RichMessageEntity_reactions" ON "RichMessageEntity_reactions"."message_id"="RichMessageEntity"."id"
(node:22556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'joinColumns' of undefined
    at D:\Projects\speakenglish.bot\src\query-builder\SelectQueryBuilder.ts:1500:61
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (D:\Projects\speakenglish.bot\src\query-builder\SelectQueryBuilder.ts:1470:57)
    at SelectQueryBuilder.getQuery (D:\Projects\speakenglish.bot\src\query-builder\SelectQueryBuilder.ts:54:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (D:\Projects\speakenglish.bot\src\query-builder\QueryBuilder.ts:415:28)
    at SelectQueryBuilder.<anonymous> (D:\Projects\speakenglish.bot\src\query-builder\SelectQueryBuilder.ts:1956:40)
    at step (D:\Projects\speakenglish.bot\node_modules\tslib\tslib.js:139:27)
    at Object.next (D:\Projects\speakenglish.bot\node_modules\tslib\tslib.js:120:57)
    at D:\Projects\speakenglish.bot\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
(node:22556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 2)
(node:22556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And the operation I want to perform is a simple "find all":

```ts
const entities = await RichMessageEntity.find();
```

Please help.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by avchugaev** [comment]
That was by mistake. After a debug I've found the reason.

**Comment by neekey** [comment]
> That was by mistake. After a debug I've found the reason.

Hey @avchugaev I'm glad you fixed your issue, but can you share what's the issue here? I bumped into the same hole here

**Comment by goktugyil** [comment]
Well, share it haha
