### ISSUE TITLE
QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'

### ISSUE THREAD

**Issue by puttputt** [typeorm/typeorm#6008]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Error**

```
TypeORM connection error:  QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at new QueryFailedError (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query._callback (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
    at Query.Sequence.end (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead [as _originalOnread] (internal/stream_base_commons.js:186:23)
    at TCP.<anonymous> (/Users/puttputt/Documents/Projects/offstreet/repositories/api/node_modules/async-listener/glue.js:188:31) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'id' in 'order clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM `test`.`migrations` `migrations` ORDER BY `id` DESC',
  query: 'SELECT * FROM `test`.`migrations` `migrations` ORDER BY `id` DESC',
  parameters: []
}
```

**Comment by puttputt** [comment]
We recently upgraded to 0.2.24 from 0.2.17 and noticed this error pop up. And after a little bit of digging figured out why.

Originally we were on 0.1.x of typeorm, and from 0.1.19 -> 0.2.0 the primary key in the migrations table, `timestamp`, was replaced with `id`. We obviously missed the memo on this, however, it went under the radar because we had what mattered already (the timestamp and class name).

In our most recent upgrade from 0.2.17 -> 0.2.24 we noticed the query generated in `MigrationExecutor. loadExecutedMigrations()` included this new clause`  .orderBy(this.connection.driver.escape("id"), "DESC")` which is the issue we encountered.

So, if you're like us, and you blindly upgraded from 0.1 -> 0.2. (I wonder what other things we may have glossed over) this should resolve your problems [in mysql]:

```
ALTER TABLE migrations DROP PRIMARY KEY;
ALTER TABLE migrations ADD id INT PRIMARY KEY AUTO_INCREMENT;
```
