### ISSUE TITLE
Geometry array column causes error in PostgresQueryRunner when synchronizing

### ISSUE THREAD

**Issue by RobbieGM** [typeorm/typeorm#6019]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.24` (latest) and `0.2.22` and `0.2.15`

**Steps to reproduce or a small repository showing the problem:**

Create a model with a spatial column in a postgres database. For example:
```typescript
import type { Point } from "geojson";

class Test {
  @Column('geometry', { spatialFeatureType: 'Point', srid: 4326, array: true })
  locations!: Point[];
}
```
The error happens when creating a connection and saving/synchronizing the new schema. The error given is:
```
TypeError: Cannot read property 'type' of undefined
    at PostgresQueryRunner.<anonymous> (C:\Users\Robbie\Code\project\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:2062:109)
    at step (C:\Users\Robbie\Code\project\node_modules\tslib\tslib.js:136:27)
```
The actual location of this error in the uncompiled TS code is [here](https://github.com/typeorm/typeorm/blob/ee575570c72e7c45b286111e81fe5ee5d89dc021/src/driver/postgres/PostgresQueryRunner.ts#L1507). This error has been reported before in #5747 but that issue blames the problem on changes in recent versions. I have this problem in a few different versions of typeorm, `0.2.24` (latest) and `0.2.22` and `0.2.15`, so it doesn't seem to be something new.

**Comment by RobbieGM** [comment]
Just made a bug repro for this and.. the bug isn't there! It it most likely an issue with my code somehow, although TypeORM is involved. I'll close this issue for now.

**Comment by RobbieGM** [comment]
I figured out what was happening. The problem happens when you try to make an array of geolocations, and I hadn't synchronized the database so the above code doesn't reproduce the error, but [this repository](https://github.com/RobbieGM/typeorm-postgis-bug-repro) should.
**To reproduce:**
1. Clone repository
2. Set your `DATABASE_URL` environment variable to a postgres database url.
3. Run the code once to set up the database tables.
4. Run it again and it will throw an error when trying to diff the database.
