### ISSUE TITLE
typeorm ignores ormconfig.env

### ISSUE THREAD

**Issue by AcrylicShrimp** [typeorm/typeorm#6038]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create an `ormconfig.env` in the project root directory.

```
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = localhost
TYPEORM_PORT = 3306
TYPEORM_USERNAME = root
TYPEORM_PASSWORD = my_pass
TYPEORM_DATABASE = my_db
TYPEORM_SYNCHRONIZE = false
TYPEORM_LOGGING = true
TYPEORM_ENTITIES = src/db/entity/**/*.ts
TYPEORM_MIGRATIONS = src/db/migration/**/*.ts
TYPEORM_SUBSCRIBERS = src/db/subscriber/**/*.ts
TYPEORM_ENTITIES_DIR = src/db/entity
TYPEORM_MIGRATIONS_DIR = src/db/migration
TYPEORM_SUBSCRIBERS_DIR = src/db/subscriber
```

Now `typeorm` ignores it.

```
Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/typeorm/connection/ConnectionOptionsReader.js:34:35)
    at step (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:110:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

CLI too.

```
> ts-node ./node_modules/.bin/typeorm "migration:generate" "-n" "Add_index"

Error during migration generation:
Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/Users/ashrimp/Devel/Node.js/devlog-backend/src/connection/ConnectionOptionsReader.ts:41:19)
    at step (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/tslib/tslib.js:110:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at main (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/ts-node/src/bin.ts:226:14)
    at Object.<anonymous> (/Users/ashrimp/Devel/Node.js/devlog-backend/node_modules/ts-node/src/bin.ts:485:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

But `.env` files works well.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by mason-meng** [comment]
I met this bug too,  the `ormconfig.env` file it works, but not read the config options.
```
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = 192.168.1.2
TYPEORM_USERNAME = root
TYPEORM_PASSWORD = robot#EDC
TYPEORM_DATABASE = robot
TYPEORM_PORT = 3306
TYPEORM_SYNCHRONIZE = true
TYPEORM_LOGGING = true
TYPEORM_ENTITIES = src/entity/**/*.ts
```

**Comment by imnotjames** [comment]
Can't replicate locally, unfortunately.  Might be how you're calling everything?
