### ISSUE TITLE
TypeError: Cannot set property EntityManager of #<Object> which has only a getter

### ISSUE THREAD

**Issue by CoreParadox** [typeorm/typeorm#6055]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

When installing Type ORM I get this error whenever it tries to run, either globally or locally.

Typescript 3.8.3
```
AppData\Roaming\npm\node_modules\typeorm\index.js:120
exports.EntityManager = EntityManager_1.EntityManager;
                      ^

TypeError: Cannot set property EntityManager of #<Object> which has only a getter
    at Object.<anonymous> 
(\AppData\Roaming\npm\node_modules\typeorm\index.js:120:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Mike\AppData\Roaming\npm\node_modules\typeorm\commands\SchemaSyncCommand.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by douglance** [comment]
@CoreParadox Did you solve the issue? How?? Thanks!

**Comment by gaoshang212** [comment]
@douglance @CoreParadox Did you solve the issue? i got it now. how? Thanks

**Comment by felipellrocha** [comment]
@CoreParadox @douglance @gaoshang212 I also have the issue

**Comment by chatch** [comment]
Duplicate: https://github.com/typeorm/typeorm/issues/6054
