### ISSUE TITLE
Repository.save() cause duplicate keys with PrimaryGeneratedColumn

### ISSUE THREAD

**Issue by Kijin-Seija** [typeorm/typeorm#6060]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

entity
```ts
export class PostType {
  @PrimaryGeneratedColumn({
    type: 'bigint',
    unsigned: true,
    name: 'id',
  })
  id: number


  @Column({
    type: 'bigint',
    unsigned: true,
    name: 'wp_termid',
    nullable: true
  })
  wpTermid: number


  @Column({
    type: 'text',
    name: 'name'
  })
  name: string
}
```

controller
```ts
export class PostTypeController {
  private repository: Repository<PostType> = getRepository(PostType);

  async update() {
    let rawdata: Buffer = readFileSync(resolve(__dirname, '../data/post_types.json'))
    let data = JSON.parse(rawdata.toString())
    await this.repository.save(data)
  }
}
```

post_type.json
```json
[
  {
    "id": 1,
    "wpTermid": 409,
    "name": "a"
  },
  {
    "id": 2,
    "wpTermid": 410,
    "name": "b"
  },
  {
    "id": 3,
    "wpTermid": 411,
    "name": "c"
  },
  {
    "id": 4,
    "wpTermid": 412,
    "name": "d"
  },
  {
    "id": 5,
    "wpTermid": 413,
    "name": "e"
  },
  {
    "id": 6,
    "wpTermid": 414,
    "name": "f"
  }
]
```
error info
```
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '1' for key 'post_types.PRIMARY'
    at new QueryFailedError (/Users/almon/code/node_artical_push/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/almon/code/node_artical_push/src/driver/mysql/MysqlQueryRunner.ts:167:37)
    at Query.<anonymous> (/Users/almon/code/node_artical_push/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/almon/code/node_artical_push/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/almon/code/node_artical_push/node_modules/mysql/lib/protocol/Protocol.js:38:16) {
```

I'm not sure. this is a bug or a rule that typeorm cannot use save() on auto increment key?  does anyone can help?

**Comment by BTOdell** [comment]
This error could be caused by the `bigNumberStrings` feature in the connection options: https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options

Essentially, since you're using `bigint` for the id type, TypeORM will actually load the value as a string. Without looking at the code in `MysqlQueryRunner`, I would assume that it uses strict equality to find existing primary keys and it crashes when it attempts to **insert** the data instead of update it.

Either change the datatype from `bigint` to `int` or use a transformer in the column definition:
```ts
@PrimaryGeneratedColumn({
    type: 'bigint',
    unsigned: true,
    name: 'id',
    transformer: { from: Number, to: Number }
  })
  id: number
```
This will force it to load as a number, although at a risk of precision loss once the values exceed `Number.MAX_SAFE_INTEGER`.

**Comment by Kijin-Seija** [comment]
> This error could be caused by the `bigNumberStrings` feature in the connection options: https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options
> 
> Essentially, since you're using `bigint` for the id type, TypeORM will actually load the value as a string. Without looking at the code in `MysqlQueryRunner`, I would assume that it uses strict equality to find existing primary keys and it crashes when it attempts to **insert** the data instead of update it.
> 
> Either change the datatype from `bigint` to `int` or use a transformer in the column definition:
> 
> ```ts
> @PrimaryGeneratedColumn({
>     type: 'bigint',
>     unsigned: true,
>     name: 'id',
>     transformer: { from: Number, to: Number }
>   })
>   id: number
> ```
> 
> This will force it to load as a number, although at a risk of precision loss once the values exceed `Number.MAX_SAFE_INTEGER`.

I tried that and had success.  through your explaination, it could also be resolved by changing the type of id to string. Thank you very much.

**Comment by gavin-c-tcg** [comment]
@PrimaryGeneratedColumn don't exist "transformer"

**Comment by BTOdell** [comment]
Yes, you're right. The @PrimaryGeneratedColumn doesn't seem to support a transformer. I know it's supported by @PrimaryColumn and so I assumed it was supported by @PrimaryGeneratedColumn.

You could try changing the type to `number | string`. Although I'm not sure this will help since the error happens at runtime... but TypeORM reads metadata so anything is possible :smile:

**Comment by diogodomanski** [comment]
> > This error could be caused by the `bigNumberStrings` feature in the connection options: https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options
> > Essentially, since you're using `bigint` for the id type, TypeORM will actually load the value as a string. Without looking at the code in `MysqlQueryRunner`, I would assume that it uses strict equality to find existing primary keys and it crashes when it attempts to **insert** the data instead of update it.
> > Either change the datatype from `bigint` to `int` or use a transformer in the column definition:
> > ```ts
> > @PrimaryGeneratedColumn({
> >     type: 'bigint',
> >     unsigned: true,
> >     name: 'id',
> >     transformer: { from: Number, to: Number }
> >   })
> >   id: number
> > ```
> > 
> > 
> > This will force it to load as a number, although at a risk of precision loss once the values exceed `Number.MAX_SAFE_INTEGER`.
> 
> I tried that and had success. through your explaination, it could also be resolved by changing the type of id to string. Thank you very much.

@Kijin-Seija thank you so much for posting this solution.... I have spent many hours trying to find out why save() method was running "insert" besides "update".

TypeORM Team, please solve this datatype issue for db drivers like MySQL and Postgres - because in those drivers the following queries have the same results:

```mysql
SELECT * FROM users WHERE id = 123;
SELECT * FROM users WHERE id = '123';
```

**Comment by azakyk** [comment]
This solution also works for PostgreSQL.

**Comment by tarekbazine** [comment]
if you have the `id` as `bigint` db type, you need to set:

```ts
    supportBigNumbers: true,
    bigNumberStrings: false,
```

in your db config.

REF : https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options

**Comment by thexeos** [comment]
This is also happening with @PrimaryColumn (not generated one). I have `bigint` ID column with transformer that maps it from string to BigInt type and back. The relationship is @ManyToMany. Loading and then immediately saving the object triggers INSERT statement with all the already existing relationship ID pairs.

As a workaround, I do something this:

```javascript
const id = 1n // Entity that we want to save
const desiredSubentityIds = [101n, 102n, 103n] // Array of IDs of subentities - this is what we truly want to save

await getManager().transaction(async (tManager) => {
  const entity = await tManager.getRepository(Entity)
    .createQueryBuilder('entity')
    .setLock('pessimistic_write')
    .leftJoinAndSelect('entity.subentities', 'subentity')
    .select(['entity', 'subentity.id'])
    .where('entity.id = :id', { id })
    .getOne()

  if (desiredSubentityIds.length) {
    const existingSubentityIds = entity.subentities.map((subentity) => subentity.id)

    const subentityIdsToAdd = desiredSubentityIds.filter((subentityId) => !existingSubentityIds.includes(subentityId))
    const subentityIdsToRemove = existingSubentityIds.filter((subentityId) => !desiredSubentityIds.includes(subentityId))

    if (subentityIdsToAdd.length || subentityIdsToRemove.length) {
      await tManager.getRepository(Entity)
        .createQueryBuilder()
        .relation(Entity, 'subentities')
        .of(id)
        .addAndRemove(subentityIdsToAdd, subentityIdsToRemove)
    }

    entity.subentities = desiredSubentityIds as Subentity[]
  } else {
    const existingSubentityIds = entity.subentities.map((subentity) => subentity.id)

    // Delete all relations in single DELETE statement
    await tManager.getRepository(Entity)
      .createQueryBuilder()
      .relation(Entity, 'entities')
      .of(id)
      .remove(existingSubentityIds)

    entity.subentities = []
  }

  return entity
})
```

If we also want to update the object **without** TypeORM trying to resolve relations and run duplicate insert queries, then we can run the following code as part of the transaction:

```javascript
await tManager.getRepository(Entity).update({ id }, { propertiesOtherThanSubentites: 'foo', someOtherProperty: 1 })
```

**Comment by mpaauw** [comment]
> if you have the `id` as `bigint` db type, you need to set:
> 
> ```ts
>     supportBigNumbers: true,
>     bigNumberStrings: false,
> ```
> 
> in your db config.
> 
> REF : https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options

@tarekbazine Thanks, this worked for me. This is a great solution, as it doesn't require constrictive changes to Entities.
