### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by machadolucasvp** [typeorm/typeorm#6123]
I really like this project, despite being new here, what do you guys think and feel about starting to support the deno runtime environment? I didn't find any suggestions or discussions like that in #3267 and in overall issues

**Comment by hermy991** [comment]
From what I could see there is currently no orm in Deno, it would be incredible to see Typeorm in Deno runtime environment.

**Comment by xorik** [comment]
@hermy991 there are at least 2 ORMs mentioned here https://deno.land/x

**Comment by vinnymac** [comment]
[This repository](https://github.com/denolib/typeorm) may interest you all

**Comment by elika-filin** [comment]
Typeorm for deno is required a lot, as deno becomes more mature day by day

**Comment by imnotjames** [comment]
If there's an easier way to implement this than maintaining a completely separate version of TypeORM I'd be interested in hearing it!

**Comment by fanybook** [comment]
https://github.com/garronej/denoify

**Comment by ClaudiuCeia** [comment]
Some time later it seems like TypeORM works _pretty_ well with Deno, simply using the `npm` compat layer (`import { ... } from "npm:typeorm"`).

However, I'm stuck at migration generation using the CLI:


```
Error during migration generation:
Error: Unable to open file: "/.../src/core/AppDataSource.ts". Cannot use import statement outside a module
    at Function.loadDataSource (/home/claudiu/.npm/_npx/52bed5231df197e3/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/home/claudiu/.npm/_npx/52bed5231df197e3/node_modules/typeorm/commands/MigrationGenerateCommand.js:68:26) 

```

I've tried several things:

- Using `npx typeorm` for the CLI
- Using `deno run npm:typeorm`
- Using `import { DataSource } from "npm:typeorm"`, `import { DataSource } from "https://esm.sh/typeorm"` as well as bundling the `AppDataSource.ts` file into a JS file with `esbuild`

At this point I'm running out of ideas and I see myself mostly having to choose between Deno and Node.js again. `TypeORM` would have been amazing to use and one of the last hurdles in adopting Deno for more serious work. The alternatives to TypeORM are not that great:

- most "deno native" options like denogres seem nice, but they have very low activity
- TypeORM deno fork seems dead
- Prisma added support for Deno but it still relies on `npm`  quite heavily and only supports the Proxy model, where requests are routed via their Data Platform offering
- edgedb is very nice but I keep running into unpolished edge cases

**Comment by JumpLink** [comment]
In case it might be useful for someone: I also use TypeORM in Deno experimentally with SQLite and have written a small wrapper to adapt the sqlite3 module for Deno to the node-sqlite3 module. The wrapper can be found here: https://github.com/beabee-communityrm/telegram-bot/tree/af90fd94f9f31e7c0e53a5f1857d59f63399e647/node-sqlite3

**Comment by shepherdjerred** [comment]
> In case it might be useful for someone: I also use TypeORM in Deno experimentally with SQLite and have written a small wrapper to adapt the sqlite3 module for Deno to the node-sqlite3 module. The wrapper can be found here: https://github.com/beabee-communityrm/telegram-bot/tree/af90fd94f9f31e7c0e53a5f1857d59f63399e647/node-sqlite3

Thank you so much! This worked great.

**Comment by JumpLink** [comment]
@shepherdjerred I recently learnt that the deno sqlite3 module is based on the Node.js module better-sqlite3, for which there is also support in TypeORM. Unfortunately, I couldn't get it to work quickly, but I suspect that it's just a few little things that are causing problems here. Maybe you'll find out what? See this issue https://github.com/denodrivers/sqlite3/issues/113 for more information.
