### ISSUE TITLE
Primary key in class entity child table not added to join table in M:N 

### ISSUE THREAD

**Issue by ryuuji3** [typeorm/typeorm#613]
I have 2 tables; Crew and Position. I want to establish a M:N relationship between them with a join table. However, Crew is a child table of the Employee table.

```typescript
// Employee.ts (Base Class)
@Entity()
@TableInheritance('class-table')
@DiscriminatorColumn({ name: 'employeeType', type: 'varchar'})
export default class Employee { ... }
```

```typescript
// Crew.ts ( Crew :: Employee) (M: )
@ClassEntityChild()
export default class Crew extends Employee {

  @ManyToMany(type => Position, position => position.crewMembers)
  @JoinTable()
  positionsTrained: Position[] = []
}
```

```typescript
// Position.ts (:N )
@Entity()
export default class Position {
  @PrimaryGeneratedColumn()
  id: number

  @ManyToMany(type => Crew, crewMember => crewMember.positionsTrained)
  crewMembers: Crew[] = [] 
```

Unfortunately, when the schema is created, the `employeeId` primary key in the Crew table is never added to the join table. Therefore when trying to create the index for the employeeId, it fails.

Most notable from the generated SQL is this:
```sql
CREATE TABLE `crew` (`availability` text, `preferredSchedule` text, `employeeId` int(11) NOT NULL UNIQUE, PRIMARY KEY(`employeeId`)) ENGINE=InnoDB

CREATE TABLE `position` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `positionType` varchar(255) NOT NULL) ENGINE=InnoDB

CREATE TABLE `position_crew_members_crew` (`positionId` int(11) NOT NULL, PRIMARY KEY(`positionId`)) ENGINE=InnoDB

CREATE INDEX `ind_f2a978e449d202fd5f0d789136` ON `position_crew_members_crew`(`positionId`)
CREATE INDEX `ind_47ea39eff8c9484f52a7914868` ON `position_crew_members_crew`()
```
Here is the full output.
```sql
executing query: START TRANSACTION
executing query: SET FOREIGN_KEY_CHECKS = 0;
executing query: SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') AS query FROM information_schema.tables WHERE table_schema = 'schedules'
executing query: DROP TABLE IF EXISTS employee;
executing query: DROP TABLE IF EXISTS position;
executing query: SET FOREIGN_KEY_CHECKS = 1;
executing query: COMMIT
executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'schedules' AND TABLE_NAME IN ('employee', 'position', 'crew', 'manager', 'scheduled_absence_reason', 'scheduled_absence', 'user', 'position_crew_members_crew', 'crew_positions_trained_position')
executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'schedules'
executing query: SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'schedules' AND INDEX_NAME != 'PRIMARY'
executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'schedules' AND REFERENCED_COLUMN_NAME IS NOT NULL
executing query: START TRANSACTION
executing query: CREATE TABLE `employee` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `firstName` varchar(100) NOT NULL, `lastName` varchar(100) NOT NULL, `birthday` datetime NOT NULL, `address` text, `contactInfo` text, `employeeType` varchar(255) NOT NULL) ENGINE=InnoDB
executing query: CREATE TABLE `position` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `positionType` varchar(255) NOT NULL) ENGINE=InnoDB
executing query: CREATE TABLE `crew` (`availability` text, `preferredSchedule` text, `employeeId` int(11) NOT NULL UNIQUE, PRIMARY KEY(`employeeId`)) ENGINE=InnoDB
executing query: CREATE TABLE `manager` (`preferredSchedule` text, `employeeId` int(11) NOT NULL UNIQUE, PRIMARY KEY(`employeeId`)) ENGINE=InnoDB
executing query: CREATE TABLE `scheduled_absence_reason` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `note` varchar(255) NOT NULL, `criteria` varchar(255) NOT NULL) ENGINE=InnoDB
executing query: CREATE TABLE `scheduled_absence` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `dateOff` datetime NOT NULL, `dateRequested` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `dateReviewed` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `employeeId` int(11), `reasonId` int(11)) ENGINE=InnoDB
executing query: CREATE TABLE `user` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `username` varchar(255) NOT NULL, `password` text NOT NULL, `employeeId` int(11)) ENGINE=InnoDB
executing query: CREATE TABLE `position_crew_members_crew` (`positionId` int(11) NOT NULL, PRIMARY KEY(`positionId`)) ENGINE=InnoDB
executing query: CREATE TABLE `crew_positions_trained_position` (`positionId` int(11) NOT NULL, PRIMARY KEY(`positionId`)) ENGINE=InnoDB
executing query: CREATE INDEX `ind_f2a978e449d202fd5f0d789136` ON `position_crew_members_crew`(`positionId`)
executing query: CREATE INDEX `ind_47ea39eff8c9484f52a7914868` ON `position_crew_members_crew`()
query failed: CREATE INDEX `ind_47ea39eff8c9484f52a7914868` ON `position_crew_members_crew`()
error during executing query:Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
executing query: ROLLBACK
{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    at Query.Sequence._packetToError (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/Users/ryuuji3/Projects/shift-scheduler/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (/Users/ryuuji3/Projects/shift-scheduler/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:182:44)
    at step (/Users/ryuuji3/Projects/shift-scheduler/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/Users/ryuuji3/Projects/shift-scheduler/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at fulfilled (/Users/ryuuji3/Projects/shift-scheduler/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
```

**Comment by pleerock** [comment]
there are lot of issues and limitations with class/single table inheritances at the moment and I won't expect a quick resolutions for all those issues. I recommend to use `Embed` and regular inheritance  (e.g. `a extends b`) for now

**Comment by ryuuji3** [comment]
Alright, thanks I'll try that for now. I'll close this for now then.
