### ISSUE TITLE
Find operators broken in Release 0.2.25

### ISSUE THREAD

**Issue by drtyh2o** [typeorm/typeorm#6144]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

After upgrading to 0.2.25 I am receiving the following **invalid input syntax for type bigint** error which does not occur in 0.2.24 ...

```
query failed: SELECT "MetricEntity"."recorded" AS "MetricEntity_recorded", "MetricEntity"."id" AS "MetricEntity_id", "MetricEntity"."name" AS "MetricEntity_name", "MetricEntity"."time_bin_size" AS "MetricEntity_time_bin_size", "MetricEntity"."time_bin_start" AS "MetricEntity_time_bin_start", "MetricEntity"."provider_id" AS "MetricEntity_provider_id", "MetricEntity"."geography_id" AS "MetricEntity_geography_id", "MetricEntity"."vehicle_type" AS "MetricEntity_vehicle_type", "MetricEntity"."count" AS "MetricEntity_count", "MetricEntity"."sum" AS "MetricEntity_sum", "MetricEntity"."min" AS "MetricEntity_min", "MetricEntity"."max" AS "MetricEntity_max", "MetricEntity"."avg" AS "MetricEntity_avg", "MetricEntity"."timestamp" AS "MetricEntity_timestamp" FROM "metrics" "MetricEntity" WHERE "MetricEntity"."name" = $1 AND "MetricEntity"."time_bin_size" = $2 AND "MetricEntity"."time_bin_start" = $3 AND "MetricEntity"."provider_id" = $4 AND "MetricEntity"."geography_id" = $5 -- PARAMETERS: ["test.metric",300000,{"_type":"between","_value":[1590512700000,1590512999999],"_useParameter":true,"_multipleParameters":true},"4b56ac00-839b-4704-aff9-6daad618b1d9","0bb85755-fd78-4088-aacc-0d639dee6681"]
error: error: invalid input syntax for type bigint: "{"_type":"between","_value":[1590512700000,1590512999999],"_useParameter":true,"_multipleParameters":true}"
    at Parser.parseErrorMessage (/Users/mdurling/Repos/lacuna/lacuna-mds/node_modules/pg-protocol/src/parser.ts:325:11)
    at Parser.handlePacket (/Users/mdurling/Repos/lacuna/lacuna-mds/node_modules/pg-protocol/src/parser.ts:154:21)
    at Parser.parse (/Users/mdurling/Repos/lacuna/lacuna-mds/node_modules/pg-protocol/src/parser.ts:106:30)
    at Socket.<anonymous> (/Users/mdurling/Repos/lacuna/lacuna-mds/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 197,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'int8.c',
  line: '129',
  routine: 'scanint8'
}
```

**Comment by drtyh2o** [comment]
Here is query produced in **0.2.24** :
```
query: SELECT "MetricEntity"."recorded" AS "MetricEntity_recorded", "MetricEntity"."id" AS "MetricEntity_id", "MetricEntity"."name" AS "MetricEntity_name", "MetricEntity"."time_bin_size" AS "MetricEntity_time_bin_size", "MetricEntity"."time_bin_start" AS "MetricEntity_time_bin_start", "MetricEntity"."provider_id" AS "MetricEntity_provider_id", "MetricEntity"."geography_id" AS "MetricEntity_geography_id", "MetricEntity"."vehicle_type" AS "MetricEntity_vehicle_type", "MetricEntity"."count" AS "MetricEntity_count", "MetricEntity"."sum" AS "MetricEntity_sum", "MetricEntity"."min" AS "MetricEntity_min", "MetricEntity"."max" AS "MetricEntity_max", "MetricEntity"."avg" AS "MetricEntity_avg", "MetricEntity"."timestamp" AS "MetricEntity_timestamp" FROM "metrics" "MetricEntity" WHERE "MetricEntity"."name" = $1 AND "MetricEntity"."time_bin_size" = $2 AND "MetricEntity"."time_bin_start" BETWEEN $3 AND $4 AND "MetricEntity"."provider_id" IS NULL AND "MetricEntity"."geography_id" IS NULL AND "MetricEntity"."vehicle_type" IS NULL -- PARAMETERS: ["test.metric",300000,1590515700000,1590602399999]
```
And the same query produced in **0.2.25**
```
query: SELECT "MetricEntity"."recorded" AS "MetricEntity_recorded", "MetricEntity"."id" AS "MetricEntity_id", "MetricEntity"."name" AS "MetricEntity_name", "MetricEntity"."time_bin_size" AS "MetricEntity_time_bin_size", "MetricEntity"."time_bin_start" AS "MetricEntity_time_bin_start", "MetricEntity"."provider_id" AS "MetricEntity_provider_id", "MetricEntity"."geography_id" AS "MetricEntity_geography_id", "MetricEntity"."vehicle_type" AS "MetricEntity_vehicle_type", "MetricEntity"."count" AS "MetricEntity_count", "MetricEntity"."sum" AS "MetricEntity_sum", "MetricEntity"."min" AS "MetricEntity_min", "MetricEntity"."max" AS "MetricEntity_max", "MetricEntity"."avg" AS "MetricEntity_avg", "MetricEntity"."timestamp" AS "MetricEntity_timestamp" FROM "metrics" "MetricEntity" WHERE "MetricEntity"."name" = $1 AND "MetricEntity"."time_bin_size" = $2 AND "MetricEntity"."time_bin_start" = $3 AND "MetricEntity"."provider_id" IS NULL AND "MetricEntity"."geography_id" IS NULL AND "MetricEntity"."vehicle_type" IS NULL -- PARAMETERS: ["test.metric",300000,{"_type":"between","_value":[1590512700000,1590599399999],"_useParameter":true,"_multipleParameters":true}]
```

**Comment by pleerock** [comment]
can you please debug a bit and find what change could cause this problem

**Comment by drtyh2o** [comment]
> can you please debug a bit and find what change could cause this problem

I have already spent a fair amount of time debugging this issue. It was broken sometime between 0.2.24 and 0.2.25. It looks to me like `toSql` isn't being performed on the FindOperator.

**Comment by drtyh2o** [comment]
Specifically, it appears this `if (parameterValue instanceof FindOperator)` is failing [here](https://github.com/typeorm/typeorm/blob/e073e027808f388f12cf374a6a305c25222bf242/src/query-builder/QueryBuilder.ts#L807)

**Comment by chriswep** [comment]
@drtyh2o i also had this issue and in my case the issue was that i had mixed typeorm versions in my project (one inter-project module was still using 0.2.24). Putting everything on the same version fixed the issue.

**Comment by drtyh2o** [comment]
> @drtyh2o i also had this issue and in my case the issue was that i had mixed typeorm versions in my project (one inter-project module was still using 0.2.24). Putting everything on the same version fixed the issue.

Thanks @chriswep ... I was just now investigating this as a possible cause. My project takes a dependency on another package that's using 0.2.4 so I too have two versions of typeorm. I manually deleted the 0.2.4 version and the problem went away. I have a PR up now to make typeorm a peer dependency of the installed package. Hopefully this conversation can help anyone else that might encounter this.

**Comment by drtyh2o** [comment]
As @chriswep and I have both discovered, installing dependencies that use a different version of typeorm can lead to issues that manifest in this particular error.

**Comment by marines** [comment]
I don't have multiple typeorm versions and the issue still occurs for me.

**Comment by marines** [comment]
I don't have multiple versions of typeorm and the issue still occurs.
