### ISSUE TITLE
Test script

### ISSUE THREAD

**Issue by taoqf** [typeorm/typeorm#616]
I got an Error while I run npm test.
```sh
creating a foreign keys: fk_2826d5940edb743a7f6e3acdb07, fk_1cb8f7a183cc7b783f261327304
executing query: ALTER TABLE `sample4_post_informations_sample4_post_information` ADD CONSTRAINT `fk_2826d5940edb743a7f6e3acdb07` FOREIGN KEY (`sample4PostId`) REFERENCES `sample4_post`(`id`)
executing query: ALTER TABLE `sample4_post_informations_sample4_post_information` ADD CONSTRAINT `fk_1cb8f7a183cc7b783f261327304` FOREIGN KEY (`sample4PostInformationId`) REFERENCES `sample4_post_information`(`id`)
creating a foreign keys: fk_68e2bc1efc6de878976f7690880, fk_7de1ecf457ca318907dbcee0aaa
executing query: ALTER TABLE `sample4_post_authors_sample4_post_author` ADD CONSTRAINT `fk_68e2bc1efc6de878976f7690880` FOREIGN KEY (`sample4PostId`) REFERENCES `sample4_post`(`id`)
executing query: ALTER TABLE `sample4_post_authors_sample4_post_author` ADD CONSTRAINT `fk_7de1ecf457ca318907dbcee0aaa` FOREIGN KEY (`sample4PostAuthorId`) REFERENCES `sample4_post_author`(`id`)
executing query: COMMIT
      2) "before all" hook: reloadDatabase

  47 passing (2m)
  2 failing

  1) many-to-many insert post and details (has inverse relation + full cascade options) "before all" hook: reloadDatabase:
     Error: done() called multiple times
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:57:9)
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:54:5)

  2) many-to-many insert post and details (has inverse relation + full cascade options) "before all" hook: reloadDatabase:
     Error: done() called multiple times
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:57:9)
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:54:5)



(node:19662) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-mocha'
Message:
    2 tests failed.
(node:19662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by taoqf** [comment]
node version 8.1.3

**Comment by pleerock** [comment]
all tests are passed on my local and on travis CI. So its probably something on your end. Can you try to `.skip` this test and see if others are run successfully?

**Comment by taoqf** [comment]
integration/sample1,sample2,sample3 all passed. I compared the code, find nothing.

OS:Debian 
node: 8.1.3
mysql: running in docker.

**Comment by taoqf** [comment]
Thereis no test under node.js8.1.3 on travis CI yet.

**Comment by pleerock** [comment]
Yes but I don't think its a node issue... Can you skip tests that are failing for you? just do `describe.skip("many-to-many .... ")` on tests which are failing for you

**Comment by taoqf** [comment]
Now I'm running test without integration/sample3,sample4, and it seems no error thrown, for now.

**Comment by taoqf** [comment]
Excuse me, where should i put `describe.skip("many-to-many .... ")`
> Yes but I don't think its a node issue... Can you skip tests that are failing for you? just do describe.skip("many-to-many .... ") on tests which are failing for you

**Comment by taoqf** [comment]
What should I do if I want test a single test? I find it takes too much time to test all the tests.

**Comment by pleerock** [comment]
Just create a test and do 
```ts
describe.only("your test description", function() {
/// ... your test content
});
```

`only` will run only your test.

**Comment by taoqf** [comment]
thanks.

**Comment by taoqf** [comment]
Something must be wrong with "many-to-many", I run only this test it throws exception again.
and I try other tests, all works fine. 
I think something is `connection.syncSchema(true)`. @pleerock  please try using the latest mysql docker `sudo docker run --rm --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -p 3306:3306 -d mysql` may see this exception:
```bash
many-to-many
    insert post and details (has inverse relation + full cascade options)
      1) "before all" hook: reloadDatabase

  0 passing (15s)
  1 failing

  1) many-to-many insert post and details (has inverse relation + full cascade options) "before all" hook: reloadDatabase:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



      2) "before all" hook: reloadDatabase

  0 passing (19s)
  2 failing

  1) many-to-many insert post and details (has inverse relation + full cascade options) "before all" hook: reloadDatabase:
     Error: done() called multiple times
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:54:9)
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:51:5)

  2) many-to-many insert post and details (has inverse relation + full cascade options) "before all" hook: reloadDatabase:
     Error: done() called multiple times
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:54:9)
      at Suite.<anonymous> (test/integration/sample4-many-to-many.ts:51:5)
```

**Comment by pleerock** [comment]
I'll try to reproduce it, but for now skip it only on your own.

**Comment by taoqf** [comment]
@pleerock , You know what? I think the problem is maybe the timeout 15000ms is too short, but I could not find where to set the timeout.
