### ISSUE TITLE
Memory leak in jest when using `createConnection`

### ISSUE THREAD

**Issue by typehorror** [typeorm/typeorm#6164]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repository demonstrating the issue: https://github.com/brigalabs/typeorm-memoryleak

using the following test in /src/leak.test.ts: 

```ts
import { createConnection } from "typeorm";

describe("leak detector", () => {
  it("test leak", async () => {
    let conn = await createConnection({
      name: "default",
      type: "sqlite",
      database: ":memory:",
      logging: false,
      entities: [],
    });

    await conn.close();
  });
});
```

the following command exposes a memory leak. I can create a repository if necessary

```
yarn node --expose-gc ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --detectLeaks src/leak.test.ts
```

```
yarn run v1.22.4
$ yarn node --expose-gc ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --detectLeaks src/leak.test.ts
 FAIL  src/leak.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:188:18)
```

Note that you'll need to install the `weak-napi` package to use the jest `--detectLeaks` parameter.

**Comment by FanAs** [comment]
This is caused by a long.js WebAssembly usage and it should be fixed in Node 12 after v8 7.9.317.23-node.20.
Thereforce you can use
```
global['WebAssembly'] = undefined;
```

in your setupFiles jest

**Comment by debrice** [comment]
Hi @FanAs , 

I've attempted your recommendation and it doesn't seem to be resolving the memory leak. I've added your changes to the codebase. I'm running nodeJS v12.18.0

**Comment by djoca** [comment]
I'm having the same issue. Any updates on this?

**Comment by imnotjames** [comment]
Creating a connection via the `createConnection` API adds it to the connection manager.  Closing the connection does not remove it from the connection manager.

https://github.com/typeorm/typeorm/blob/c5143aab08a04e96aebb55996ed7683d48542bbd/src/connection/ConnectionManager.ts#L10

You either want to clean up by removing the connection manually or by using the standard `Connection` constructor.

**Comment by debrice** [comment]
@imnotjames , thanks for the comment. I've replaced the use of the ConntectionManager with the Connection class as you recommended but the memory leak persist. I have updated my example PR to reflect the use of the Connection class.

Could you re-open this ticket please?

**Comment by biels** [comment]
Related to #6629

**Comment by kevin-lindsay-1** [comment]
@debrice I just ran into this same issue (I have a function that runs over and over and creates different connections depending on the inputs), and I can confirm that using:

```ts
import { Connection } from 'typeorm';

const connection = new Connection(...);
```

does get rid of my memory leak.

Have you tried profiling via `chrome://inspect` and issuing a `kill -s SIGUSR1 <pid>` to your node PID?

**Comment by imnotjames** [comment]
> Related to #6629

I'm not so sure.

Looking again at all of this, I don't really see how this is leaking memory.

Can anyone do some profiling & find the cause?

**Comment by kevin-lindsay-1** [comment]
@imnotjames last I profiled it I found that createConnection creates a map that is globally in scope, and closing a connection does not ever clean up the previous connections.

I only encountered it because I had many connections with (effectively) UUIDs for the connection name, each would run for an extended period of time, but after hundreds or thousands of created & closed connections, it becomes pretty apparent.

**Comment by imnotjames** [comment]
Right - but bypassing the connection manager and creating them with the constructor ends up with no leaks.

**Comment by imnotjames** [comment]
I've tried a few different ways to reproduce.  No dice.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by debrice** [comment]
Hi @imnotjames , 

I'm not sure if your last message was passive/aggressive, so I'll assume it's not. If you look closely at my initial message, I've provided a complete self contain method to reproduce that is also very minimal. I hate to have to write this but, as of today, TypeORM is leaking memory. I can definitely understand that long lasting bugs can be frustrating to a contributor and I wish I could help (I tried many way to fix the issue, including your recommendation, but it does not go away). 

I truly don't believe closing this issue would be doing typeORM a favor.

**Comment by imnotjames** [comment]
> Hi @imnotjames ,
> 
> I'm not sure if your last message was passive/aggressive, so I'll assume it's not.

It was not intended in the slightest, if it came off that way.

> If you look closely at my initial message, I've provided a complete self contain method to reproduce that is also very minimal. I hate to have to write this but, as of today, TypeORM is leaking memory.

I was unable to replicate any leak when I create the connection via a constructor then close it again.  `createConnection` & that whole connection manager leaks memory as a bizarre feature, which is known.

Another member of the community confirmed that they could not replicate it either.

Without a reproduction I cannot find the root cause, nor can I confirm it's not a local issue specific to your environment.

**Comment by baublet** [comment]
Is it on the roadmap to fix this leak in `createConnection`, or will it exist in perpetuity as a footgun and "bizarre feature?" We might consider documenting the behavior that in testing environments, use `new Connection` instead of `createConnection` due to memory leak potential.

I assume the entire `createConnection` toolchain exists for running the actual code, rather than testing it, so little thought went into memory leaks in testing environments with `createConnection` and the connection manager pieces. Makes sense, but if TypeORM keeps it this way, it should be pretty obvious in the documentation.

**Comment by kevin-lindsay-1** [comment]
I would argue that `createConnection` could just have a flag that states to cleanup the connection automatically when closed, so as to not have breaking API changes.

Some people close and reopen the same connection, so this would be a good alternative to circumventing `createConnection` and creating connections manually.

**Comment by imnotjames** [comment]
> Is it on the roadmap to fix this leak in `createConnection`, or will it exist in perpetuity as a footgun and "bizarre feature?" We might consider documenting the behavior that in testing environments, use `new Connection` instead of `createConnection` due to memory leak potential.

Sort of!  It's on the roadmap to deprecate and remove `createConnection`.

**Comment by debrice** [comment]
@imnotjames there is something that confuses me, the reproduction I've provided does not use `createConnection` but `new Connection({...})`. 

I've updated the typeORM to the latest (0.2.34) and remove commented code from the test. It is still leaking and it now only contains the following code:

```ts
import { Connection } from "typeorm";

describe("typeorm conn leak detector", () => {
  it("test Connection leak", async () => {
    const conn: Connection | null = new Connection({
      name: "default",
      type: "sqlite",
      database: ":memory:",
      logging: false,
      entities: [],
    });

    await conn.close();
  });
});
```

when running it I get the following warning:

```sh
$ yarn test
yarn run v1.22.10
$ yarn node --expose-gc ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --detectLeaks src/leak.test.ts
 FAIL  src/leak.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:190:18)
      at node_modules/@jest/core/build/TestScheduler.js:316:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:258:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.658 s
Ran all test suites matching /src\/leak.test.ts/i.
error Command failed.
Exit signal: SIGSEGV
Command: /usr/local/Cellar/node/15.11.0/bin/node
Arguments: --expose-gc ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --detectLeaks src/leak.test.ts
Directory: /Users/briceleroy/Code/briga/typeorm-memoryleak
Output:

info Visit https://yarnpkg.com/en/docs/cli/node for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by imnotjames** [comment]
Do you see that when you run the test with just javascript & not typescript?

**Comment by imnotjames** [comment]
I ask because I ran a test checking the heap size changes over the course of creating, connecting to, and closing 10 million connections.

The heap size remained consistent & did not change more than +- 1mb throughout.

This was in just javascript, though.  Typescript was not involved in the process.  I'll re-test transpiling from typescript to see if that has an impact.

**Comment by imnotjames** [comment]
Actually - looking at your code, it should be failing.

```
import { Connection } from "typeorm";

describe("typeorm conn leak detector", () => {
  it("test Connection leak", async () => {
    const conn: Connection | null = new Connection({
      name: "default",
      type: "sqlite",
      database: ":memory:",
      logging: false,
      entities: [],
    });

    await conn.close();
  });
});
```

You don't `connect` the connection but you attempt to close it.  That should be throwing an error.

**Comment by debrice** [comment]
@imnotjames you are right  (I've noticed that and fixed it locally), but the bug persist with `connect()`. I'm attempting to track the memory leak right now.

**Comment by jlaustill** [comment]
@debrice have you had any luck finding the leak?  I'm dealing with the same bug right now :(

**Comment by debrice** [comment]
I've had to give up. I've stopped using typeorm and switch to Prisma. but today I'm pretty convinced that the issue is related to how jest maintain the connection (and objects) than typeorm itself.

The two solutions I had is either switch to Jasmine (I know it truly sucks but today I'm happy I did) or start mocking all typeorm calls in Jest. 

The only final way out I can imagine would be having a flag in typeorm to prevent the creation of a connection pool (which I suspect is the issue here). Because Jest creates a whole app for every test, there is hardly anything you can do beside mocking typeorm.

**Comment by podplatnikm** [comment]
BUMP. Any news?

**Comment by redefinered** [comment]
Bumping in 2025! Any update?

**Comment by mguida22** [comment]
@redefinered is this an issue for you on the latest version of TypeORM? If it is, a current reproduction would be very helpful.

**Comment by redefinered** [comment]
In version 0.2.45,

Sadly, switching to latest version will break my production app.

**Comment by mguida22** [comment]
> In version 0.2.45,
> 
> Sadly, switching to latest version will break my production app.

Sorry that's the case, but I don't think we'll be able to do anything for 0.2.45 right now. That release is over 3 years old at this point and we're currently focused on keeping the latest releases stable. If you do want to migrate to 0.3.x, there's [changelog notes here](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#030-2022-03-17) and you can join our [Discord for support](https://github.com/typeorm/typeorm/blob/master/docs/support.md).

I'm going to close this issue as I believe it's resolved in the 0.3.x versions.
