### ISSUE TITLE
stackoverflow, OrmUtils.deepmerge js joda

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#6181]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
```
> node --version                                                                                        # service-graph -> feature/RS2-1044 !
v12.16.3
> yarn list typeorm                                                                                     # service-graph -> feature/RS2-1044 !
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ typeorm@0.2.25
✨  Done in 1.19s.
> yarn list typescript                                                                                  # service-graph -> feature/RS2-1044 !
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ typescript@3.7.4
✨  Done in 1.23s.
```
error
```

  ● DeviceRepository › findDeviceProductByDeviceIdWithStatusIn › all new

    RangeError: Maximum call stack size exceeded
        at Array.shift (<anonymous>)

      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:73:32)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
```
firstly this error is terrible, at the very least it could tell me what field it's merging....

```ts
  @Column({
    name: 'date_joined',
    type: 'timestamp with time zone',
    transformer: zonedDateTimeTransformer(),
  })
  readonly dateJoined!: ZonedDateTime;
```

this is what I believe is  causing the issue, `ZonedDateTime` comes from `@js-joda/core`

this is my transformer

```ts
export function zonedDateTimeTransformer(): ValueTransformer {
  return {
    from(value: string): ZonedDateTime {
      return ZonedDateTime.parse(value);
    },
    to(value: ZonedDateTime): string {
      return value.toString();
    },
  };
}```

**Comment by xenoterracide** [comment]
note: I had this same problem with `deepmerge` on npmjs, but this algorithm seems to do what I want. https://www.npmjs.com/package/merge-anything maybe the code would help fix this.

**Comment by teddyteh** [comment]
It's weird that it works if you just hardcode like such:
`to(value: ZonedDateTime): string {
      return "2020-06-08 09:36:15.25+00";
    },`

**Comment by xenoterracide** [comment]
hmm... also had the same problem if I did to/from `Date`

**Comment by xenoterracide** [comment]
tried this as well

```
  @Column({
    type: 'timestamp with time zone',
    transformer: {
      from: (date: Date): ZonedDateTime => {
        const dt = ZonedDateTime.from(nativeJs(date));
        return dt;
      },
      to: (date: ZonedDateTime): Date => {
        return convert(date).toDate();
      },
    },
  })
  readonly created: ZonedDateTime = ZonedDateTime.now();
```

it's converting in the from correctly, and `to` is never called but I'd assume that would work too

but still

```
 RangeError: Maximum call stack size exceeded

      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:71:5)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
      at Function.Object.<anonymous>.OrmUtils.mergeDeep (src/util/OrmUtils.ts:90:26)
```

the problem is that these object can't simply be merged, they are immutable and have to have their reference copied, instead of attempting to merge them deeply.

**Comment by alecbignell** [comment]
I'm using postgres and have the following example:

```ts
@Entity()
export class MyEntity {
  @PrimaryColumn({ type: "varchar", length: 22 })
  id!: string;

  @Column({ type: "varchar", length: 128 })
  name: string;

  @Column({ default: 0 })
  myNumberValue: number;

  @Column({ type: "json", default: { } })
  settings: object;

  @Column({type: "boolean", default: true})
  isActive: boolean;
}
```
And all I'm doing is something like:
```ts
const myModelRepository = database.getRepository(MyModel);
myModelInstance.isActive = false;
await myModelRepository.save(myModelInstance);
```
The record already exists, so I'm expecting this to do an update, but it hits this mergeDeep stackoverflow:
```
 OrmUtils.mergeDeep = function (target) {
                                  ^
RangeError: Maximum call stack size exceeded
```

Not sure if this is the same issue or if I'm just missing something?

**Comment by pies** [comment]
Still a problem, unfortunately. Perhaps allowing to use a custom object merge tool would be an option?

**Comment by francescoferraioli** [comment]
I have opened a PR which adds an option for the consumer to configure custom object merging. https://github.com/typeorm/typeorm/pull/7756

**Comment by imnotjames** [comment]
Should we just not do a deep merge of non-plain objects or entities?

Why are we trying to do a deep-merge on these when all we care about is just plain objects?
