### ISSUE TITLE
ViewEntity Parameters not escaped

### ISSUE THREAD

**Issue by affeldt28** [typeorm/typeorm#6182]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.25`

I'm hoping someone of you can help me out. I'm trying to escape a parameter with the querrybuilder.

Some background information "Pavillon" is a enum class. I already tried to use toString() or put in the string by hand but sadly it doesn't like my parameter. Down below i put cutout of my code and the error

Any idea / feedback is greatly appreciated.
```
@ViewEntity("vw_Pavillon", {
	expression: (connection: Connection) =>
		connection
			.createQueryBuilder()
			.select("c.id", "id")
			.addSelect("c.uuid", "uuid")
			.addSelect("c.createdAt", "createdAt")
			.addSelect("c.updatedAt", "updatedAt")
			.addSelect("c.name", "name")
			.addSelect("c.department", "department")
			.addSelect("c.street", "street")
			.addSelect("c.place", "place")
			.addSelect("c.zip", "zip")
			.addSelect("e.pavillon", "pavillon")
			.from(Company, "c")
			.innerJoin(Extra, "e", "c.uuid = e.uuid")
			.where("e.pavillon = :pavillon", { pavillon: Pavillon.NONE })
			.andWhere("e.pavillon != ''"),
})
```
The Error Messages:
```
query: CREATE VIEW `vw_Pavillon` AS SELECT `c`.`id` AS `id`, `c`.`uuid` AS `uuid`, `c`.`createdAt` AS `createdAt`, `c`.`updatedAt` AS `updatedAt`, `c`.`name` AS `name`, `c`.`department` AS `department`, `c`.`street` AS `street`, `c`.`place` AS `place`, `c`.`zip` AS `zip`, `e`.`pavillon` AS `pavillon` FROM `Companies` `c` INNER JOIN `Extras` `e` ON `c`.`uuid` = `e`.`uuid` WHERE `e`.`pavillon` = :pavillon AND `e`.`pavillon` != ''
query failed: CREATE VIEW `vw_Pavillon` AS SELECT `c`.`id` AS `id`, `c`.`uuid` AS `uuid`, `c`.`createdAt` AS `createdAt`, `c`.`updatedAt` AS `updatedAt`, `c`.`name` AS `name`, `c`.`department` AS `department`, `c`.`street` AS `street`, `c`.`place` AS `place`, `c`.`zip` AS `zip`, `e`.`pavillon` AS `pavillon` FROM `Companies` `c` INNER JOIN `Extras` `e` ON `c`.`uuid` = `e`.`uuid` WHERE `e`.`pavillon` = :pavillon AND `e`.`pavillon` != ''
error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':pavillon AND `e`.`pavillon` != ''' at line 1    at Query.Sequence._packetToError (D:\project\em_ws\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\project\em_ws\api\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\project\em_ws\api\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (D:\project\em_ws\api\node_modules\mysql\lib\Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (D:\project\em_ws\api\src\driver\mysql\MysqlQueryRunner.ts:156:36)
    at step (D:\project\em_ws\api\node_modules\tslib\tslib.js:141:27)
    at Object.next (D:\project\em_ws\api\node_modules\tslib\tslib.js:122:57)
    at fulfilled (D:\project\em_ws\api\node_modules\tslib\tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':pavillon AND `e`.`pavillon` != ''' at line 1",
  sqlState: '42000',
  index: 0,
  sql: "CREATE VIEW `vw_Pavillon` AS SELECT `c`.`id` AS `id`, `c`.`uuid` AS `uuid`, `c`.`createdAt` AS `createdAt`, `c`.`updatedAt` AS `updatedAt`, `c`.`name` AS `name`, `c`.`department` AS `department`, `c`.`street` AS `street`, `c`.`place` AS `place`, `c`.`zip` AS `zip`, `e`.`pavillon` AS `pavillon` FROM `Companies` `c` INNER JOIN `Extras` `e` ON `c`.`uuid` = `e`.`uuid` WHERE `e`.`pavillon` = :pavillon AND `e`.`pavillon` != ''"
}
query: ROLLBACK
Unable to connect to the database: QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':pavillon AND `e`.`pavillon` != ''' at line 1
    at new QueryFailedError (D:\project\em_ws\api\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (D:\project\em_ws\api\src\driver\mysql\MysqlQueryRunner.ts:167:37)
    at Query.<anonymous> (D:\project\em_ws\api\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\project\em_ws\api\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (D:\project\em_ws\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\project\em_ws\api\node_modules\mysql\lib\protocol\Protocol.js:38:16) {
  message: "ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':pavillon AND `e`.`pavillon` != ''' at line 1",  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':pavillon AND `e`.`pavillon` != ''' at line 1",
  sqlState: '42000',
  index: 0,
  sql: "CREATE VIEW `vw_Pavillon` AS SELECT `c`.`id` AS `id`, `c`.`uuid` AS `uuid`, `c`.`createdAt` AS `createdAt`, `c`.`updatedAt` AS `updatedAt`, `c`.`name` AS `name`, `c`.`department` AS `department`, `c`.`street` AS `street`, `c`.`place` AS `place`, `c`.`zip` AS `zip`, `e`.`pavillon` AS `pavillon` FROM `Companies` `c` INNER JOIN `Extras` `e` ON `c`.`uuid` = `e`.`uuid` WHERE `e`.`pavillon` = :pavillon AND `e`.`pavillon` != ''",
  name: 'QueryFailedError',
  query: "CREATE VIEW `vw_Pavillon` AS SELECT `c`.`id` AS `id`, `c`.`uuid` AS `uuid`, `c`.`createdAt` AS `createdAt`, `c`.`updatedAt` AS `updatedAt`, `c`.`name` AS `name`, `c`.`department` AS `department`, `c`.`street` AS `street`, `c`.`place` AS `place`, `c`.`zip` AS `zip`, `e`.`pavillon` AS `pavillon` FROM `Companies` `c` INNER JOIN `Extras` `e` ON `c`.`uuid` = `e`.`uuid` WHERE `e`.`pavillon` = :pavillon AND `e`.`pavillon` != ''",
  parameters: []
}
```

**Comment by imnotjames** [comment]
Can you create a test case in the repo that exhibits this

**Comment by affeldt28** [comment]
Sorry if this is a stupid reqeust, but how can i do that?

**Comment by imnotjames** [comment]
Definitely not stupid. :)

In the typeorm repository there's the directory `test/github-issues` - there's a number of tests there.  Ideally you can make one for this issue as a PR or in a fork that you can link to from this issue.

**Comment by affeldt28** [comment]
Hope this help. I didnt know what to with the test-connection thing.

**Comment by mguida22** [comment]
Hi @affeldt28, hopefully you've been able to resolve this. If there's still a bug in the latest version of TypeORM feel free to open a new issue. https://github.com/typeorm/typeorm/blob/master/docs/support.md
