### ISSUE TITLE
migration run won't execute with ManyToMany relation

### ISSUE THREAD

**Issue by powlsn** [typeorm/typeorm#6186]
Issue type:

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[ ] latest
[ ] @next
[x] 0.2.24

__Steps to reproduce or a small repository showing the problem:__

I have created these two entities

```javascript
@Entity()
export class Category {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}
```

and

```javascript
@Entity()
export class Question {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  text: string;

  @ManyToMany(type => Category)
  @JoinTable()
  categories: Category[];
}
```

The migration is created correctly and looks good to me

```javascript
import { MigrationInterface, QueryRunner } from 'typeorm';

export class QuestionCategory1591194599336 implements MigrationInterface {
  name = 'QuestionCategory1591194599336';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "question" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "text" character varying NOT NULL, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`,
      undefined,
    );
    await queryRunner.query(
      `CREATE TABLE "category" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`,
      undefined,
    );
    await queryRunner.query(
      `CREATE TABLE "question_categories_category" ("questionId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_11044aadb95ef30daf7d1363d31" PRIMARY KEY ("questionId", "categoryId"))`,
      undefined,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_21433e6d9a0e7e79c36b4ae69f" ON "question_categories_category" ("questionId") `,
      undefined,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_9cf04f10454634f887ade56562" ON "question_categories_category" ("categoryId") `,
      undefined,
    );
    await queryRunner.query(
      `ALTER TABLE "question_categories_category" ADD CONSTRAINT "FK_21433e6d9a0e7e79c36b4ae69fd" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      undefined,
    );
    await queryRunner.query(
      `ALTER TABLE "question_categories_category" ADD CONSTRAINT "FK_9cf04f10454634f887ade565622" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      undefined,
    );
  }
}

```

but when execute migration run i get the following error

```
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: SELECT * FROM "question_categories_category" "migrations" ORDER BY "id" DESC
query failed: SELECT * FROM "question_categories_category" "migrations" ORDER BY "id" DESC
error: error: Relation »question_categories_category« does not exist
    at Connection.parseE (..\server\node_modules\pg\lib\connection.js:614:13)
    at Connection.parseMessage (..\server\node_modules\pg\lib\connection.js:413:19)
    at Socket.<anonymous> (..\server\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 191,
  severity: 'FEHLER',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable'
}
Error during migration run:
```

I have taken the example from the documentation and tried all possibilities, unfortunately without success. What goes wrong?

**Comment by powlsn** [comment]
Update to 0.2.25 solved this issue
