### ISSUE TITLE
QueryFailedError: Unknown database 'xx'

### ISSUE THREAD

**Issue by khanakia** [typeorm/typeorm#6204]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi,
I using the following script and getting an error PromiseRejectionWarning: QueryFailedError: Unknown database 'second'

example.ts
```
import { createConnections } from "typeorm";
import {Entity, BaseEntity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity({database: 'second'})
class Book extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}

const main = async () => {
  await createConnections([
    {
      name: "default",
      type: "postgres",
      host: 'localhost',
      port: 5432,
      username: "postgres",
      password: "root",
      database: "jeoga",
      synchronize: true,
      logging: false,
      entities: [Book] 
    },
    {
      name: "second",
      type: "mysql",
      host: 'localhost',
      port: 3306,
      username: "root",
      password: "root",
      database: "kookjs",
      synchronize: true,
      logging: false,
      entities: [Book]      
    }
  ]);

  const book = new Book()
  book.name = "Test"
  await book.save()
  console.log('Saved')
}

main()
```

ERROR
```
Lucians-MacBook-Pro:tsc_1 khanakia$ ts-node example.ts 
(node:84637) UnhandledPromiseRejectionWarning: QueryFailedError: Unknown database 'second'
    at new QueryFailedError (/Volumes/D/www/js/tsc_1/src/error/QueryFailedError.ts:9:9)
    at Query.onResult (/Volumes/D/www/js/tsc_1/src/driver/mysql/MysqlQueryRunner.ts:167:37)
    at Query.execute (/Volumes/D/www/js/tsc_1/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/Volumes/D/www/js/tsc_1/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/Volumes/D/www/js/tsc_1/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Volumes/D/www/js/tsc_1/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Volumes/D/www/js/tsc_1/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
(node:84637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by khanakia** [comment]
I just found it. It has to be a database name, not a connection name.
