### ISSUE TITLE
Cannot read property 'createQueryBuilder' of undefined

### ISSUE THREAD

**Issue by booradleys** [typeorm/typeorm#624]
Hi, i got this error when calling:
http://localhost:3000/photo/test/getitem?candidat_id=1&acces=1&ordre=1

TypeError: Cannot read property 'createQueryBuilder' of undefined
    at TestRepository.Repository.createQueryBuilder (\node_modules\typeorm\repository\Repository.js:76:28)
    at TestRepository.getItemNumber (\dist\repository\TestRepository.js:15:29)
    at TestService.getItem (\dist\modules\photo\services\TestService.js:16:36)
    at Photo_TestController.getitem (\dist\modules\photo\controllers\TestController.js:24:28)
    at ActionMetadata.callMethod (\node_modules\routing-controllers\metadata\ActionMetadata.js:101:62)
    at \server\node_modules\routing-controllers\RoutingControllers.js:92:140
    at process._tickCallback (internal/process/next_tick.js:103:7)

TestController.ts
````
import {Service, Container} from "typedi";
import {Request, Response} from "express";
import {JsonController, Req, Res, Param, QueryParams, Get, Post} from "routing-controllers";
import {TestService} from "../../../modules/photo/services/TestService";

@Service()
@JsonController("/photo/test")
export class Photo_TestController   
{   
    @Get("/getitem?:params")
    getitem(@QueryParams() params: any, @Req() request: Request, @Res() response: Response) {
    	let candidat_id = params['candidat_id'];
        let acces = params['acces'];
        let ordre = params['ordre'];
        
        const testService = Container.get(TestService);
        
    	return  testService.getItem(candidat_id,acces,ordre)
                .then(function(item) {
                    return item;
                });    	
    }
}
````

TestService.ts
````
import { Service, Container } from "typedi";
import { TestServiceFactory } from "./TestServiceFactory";
import { TestRepository } from "../../../repository/TestRepository";

@Service({ factory: [TestServiceFactory, "create"] })
export class TestService {
        request: Request;
        testRepository: TestRepository;
        
        setCandidatPhotoMapper(testRepository: TestRepository) {
            this.testRepository = testRepository   
        }
        getItem(candidat_id: number,acces: number,ordre: number) {
            return this.testRepository.getItemNumber(candidat_id,acces,ordre);
    }
}
````
TestServiceFactory.ts
````
import {Inject,Service} from "typedi";
import {Request} from "express";
import { TestService } from "./TestService";
import { TestRepository } from "../../../repository/TestRepository";

@Service()
export class TestServiceFactory
{
    @Inject()
    candidatPhotoMapper: TestRepository ;
    
    create()
    {
        let instance = new TestService();
        instance.setCandidatPhotoMapper(this.candidatPhotoMapper);      

        return instance;
    }
}
````

TestRepository.ts
````
import {Service} from "typedi";
import { Repository, EntityRepository } from "typeorm";
import {TCandidatPhoto} from "../entity/TCandidatPhoto";

// create custom Repository class
@Service()
@EntityRepository(TCandidatPhoto)
export class TestRepository extends Repository<TCandidatPhoto>
{
    getItemNumber(id_annonce: number,acces: number,ordre: number) {
        const result = this.createQueryBuilder('cp')  // ERROR IS HERE
                            .select('cp.id as id_photo,cp.ordre,cp.statut,cp.x1,cp.y1,cp.x2,cp.y2,cp.size')
                            .from(TCandidatPhoto,'cp')
                            .innerJoin('cp.candidatPhotoGalerie','cpg')
                            .where('cp.candidat = :candidat_id')
                            .andWhere('cp.ordre = :ordre')
                            .andWhere('cpg.acces = :acces')
                            .setParameter('candidat_id', id_annonce)
                            .setParameter('ordre', ordre)
                            .setParameter('acces', acces)
                            .getOne();
        return result;
    }	
}
````

I don't understand why TestRepository.Repository.createQueryBuilder is called instead of
TestRepository.createQueryBuilder
So TestRepository.Repository is undefined

Can anyone help me please?
David

**Comment by pleerock** [comment]
custom repositories defined by `@EntityRepository` cannot be services. You cannot use DI with them. They should be obtained using `connection.getCustomRepository(TestRepository)`

**Comment by booradleys** [comment]
@pleerock 
I removed @Service from my repository

````
import { Repository, EntityRepository } from "typeorm";
import {TCandidatPhoto} from "../entity/TCandidatPhoto";

// create custom Repository class
@EntityRepository(TCandidatPhoto)
export class TestRepository extends Repository<TCandidatPhoto>
{
    getItemNumber(id_annonce: number,acces: number,ordre: number) {
        const result = this.createQueryBuilder('cp') // ERROR IS HERE
                            .select('cp.id as id_photo,cp.ordre,cp.statut,cp.x1,cp.y1,cp.x2,cp.y2,cp.size')
                            .from(TCandidatPhoto,'cp')
                            .innerJoin('cp.candidatPhotoGalerie','cpg')
                            .where('cp.candidat = :candidat_id')
                            .andWhere('cp.ordre = :ordre')
                            .andWhere('cpg.acces = :acces')
                            .setParameter('candidat_id', id_annonce)
                            .setParameter('ordre', ordre)
                            .setParameter('acces', acces)
                            .getOne();
        return result;
    }	
}
````

I don't want to manage connections in each controller so i'd like that app.js do that work

app.js
````
"use strict";
exports.__esModule = true;
require("reflect-metadata");
var routing_controllers = require("routing-controllers");
var typedi = require("typedi");
var typeorm = require("typeorm");

routing_controllers.useContainer(typedi.Container);
typeorm.useContainer(typedi.Container);
    
typeorm.createConnection({
    name: "default",
    driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "",
        database: "db_exotica"
    },
    entities: [
        __dirname + "/dist/entity/*.js"
    ],
    autoSchemaSync: false,
}).then(connection => {
    // Here you can start to work with your entities
    // setup routing-controllers to use typedi container. You can use any container here
    // create express server
    var expressApp = routing_controllers.createExpressServer({
        // now import all our controllers. alternatively you can specify controllerDirs in routing-controller options
        controllers: [__dirname + "/dist/modules/**/controllers/*.js"],
    });

    expressApp.listen(3000);
    console.log("Server is up");
}).catch(error => console.log(error));
````

Is that the correct way ?

**Comment by pleerock** [comment]
yeah looks correct

**Comment by booradleys** [comment]
Issue stay the same:

TypeError: Cannot read property 'createQueryBuilder' of undefined
    at TestRepository.Repository.createQueryBuilder (\node_modules\typeorm\repository\Repository.js:76:28)
    at TestRepository.getItemNumber (\dist\repository\TestRepository.js:16:29)
    at TestService.getItem (\dist\modules\photo\services\TestService.js:16:36)
    at Photo_TestController.getitem (\dist\modules\photo\controllers\TestController.js:24:28)
    at ActionMetadata.callMethod (\node_modules\routing-controllers\metadata\ActionMetadata.js:101:62)
    at C:\Applications\Node\exotica\server\node_modules\routing-controllers\RoutingControllers.js:92:140
    at process._tickCallback (internal/process/next_tick.js:103:7)

I must have missed something...

**Comment by pleerock** [comment]
How do you get/obtain `TestRepository` ?

**Comment by booradleys** [comment]
It is injected into TestServiceFactory by @Inject()
````
import {Inject,Service} from "typedi";
import {Request} from "express";
import { TestService } from "./TestService";
import { TestRepository } from "../../../repository/TestRepository";

@Service()
export class TestServiceFactory
{
    @Inject()
    candidatPhotoMapper: TestRepository;
    
    create()
    {
        let instance = new TestService();
        instance.setCandidatPhotoMapper(this.candidatPhotoMapper);      

        return instance;
    }
}
````

**Comment by pleerock** [comment]
I told you, you cannot use DI with custom repositories. you should use: `connection.getCustomRepository(TestRepository)`

**Comment by marcosdipaolo** [comment]
hey @pleerock , also not posible in this way?  

**DB**
```typescript
import { createConnections, getConnection, ObjectType } from "typeorm";

export class DB {
  static nodeEnv = process.env.NODE_ENV;

  static async getDbConnection () {
    try {
      await createConnections();
      const connection = getConnection(DB.nodeEnv === "development" ? "default" : DB.nodeEnv);
      if(connection.isConnected) {
        console.log("db connected with", connection.name, "connection");
        return connection;
      }
      throw new Error("there was a problem connecting to the database...");
    } catch(err) {  
      console.log(err.message);
    }
  }

  static getRepository = <T>(repository: ObjectType<T>): T => {
    const connection = getConnection(DB.nodeEnv === "development" ? "default" : DB.nodeEnv);
    return connection.getCustomRepository<T>(repository);
  }
}
```
**Container definition**
```typescript
export const bindings = new AsyncContainerModule(async bind => {
  await DB.getDbConnection();
  bind<Repository<User>>(TYPES.userRepository).toDynamicValue(() => {
    return DB.getRepository(UserRepository);
  }).inRequestScope();
});
```
