### ISSUE TITLE
TS2339: Property 'detail' does not exist on type 'QueryFailedError'.

### ISSUE THREAD

**Issue by boskiv** [typeorm/typeorm#6299]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Trying to implement Exception Filter in NestJS.

```
import { ExceptionFilter, Catch, ArgumentsHost } from '@nestjs/common';
import { QueryFailedError } from 'typeorm';
import { Request, Response } from 'express';

@Catch(QueryFailedError)
export class QueryFailedErrorExceptionFilter implements ExceptionFilter {
  public catch(exception: QueryFailedError, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = 422;

    console.error(exception);
    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: request.url,
      message: exception.message,
      detail: exception.detail
    });
  }
}
```

Stack shows that detail attribute contain string
```
QueryFailedError: duplicate key value violates unique constraint "UQ_e12875dfb3b1d92d7d7c5377e22"
    at new QueryFailedError (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/pg/lib/query.js:146:19)
    at Connection.connectedErrorMessageHandler (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/pg/lib/client.js:233:17)
    at Connection.emit (events.js:315:20)
    at /Users/i_skiridomov/Projects/koko-nest-api/node_modules/pg/lib/connection.js:109:10
    at Parser.parse (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/pg-protocol/dist/parser.js:42:17)
    at Socket.<anonymous> (/Users/i_skiridomov/Projects/koko-nest-api/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12) {
  length: 235,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (email)=(some@email.com) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'user',
  column: undefined,
  dataType: undefined,
  constraint: 'UQ_e12875dfb3b1d92d7d7c5377e22',
  file: 'nbtinsert.c',
  line: '563',
  routine: '_bt_check_unique',
  query: 'INSERT INTO "user"("id", "name", "email", "password") VALUES (DEFAULT, DEFAULT, $1, $2) RETURNING "id"',
  parameters: [ 'some@email.com', 'string' ]
}
```
But typescript throw
TS2339: Property 'detail' does not exist on type 'QueryFailedError'.

**Comment by kwakueshun** [comment]
facing same issue

**Comment by imnotjames** [comment]
Is this still an issue as of 0.2.27?

**Comment by NuclleaR** [comment]
still faced with same issue.
"typeorm": "^0.2.34"

**Comment by lsw1164** [comment]
Any news?

**Comment by rebla** [comment]
Still facing it, any updates?

**Comment by alumni** [comment]
@rebla This issue is closed. You can open a new one with up-to-date replication steps if you encounter some unexpected behavior.

**Comment by alumni** [comment]
There is no `detail` property in `QueryFailedError`, probably it's what the Postgres client sets, but we don't get the types from the Postgres client.

It might help you to get any information you need from `QueryFailedError.driverError`:

```ts
import type { DatabaseError } from '@types/pg';

try {
  // do something
} catch (error: QueryFailedError<DatabaseError>) {
  console.log(error.driverError.details);
}
```
