### ISSUE TITLE
Proper reconnect to database after unexpected lost of connection

### ISSUE THREAD

**Issue by Mondei1** [typeorm/typeorm#6350]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22`

### Steps to reproduce or a small repository showing the problem:
Establish a connection to your database. Then do some inserts and selects, whatever. And while TypeORM does all that, cut the connection by stopping the MariaDB server. That should throw an error (when logging is turned on) that says either `PROTOCOL_CONNECTION_LOST` and/or `ER_SERVER_SHUTDOWN` in the code property of the error.

### Actual question
**How can I catch that?** How can I catch these errors to perform reconnect tries. I want to have access to the error object that looks like that in the console:
```
error: Error: ER_SERVER_SHUTDOWN: Server shutdown in progress
    [TRACE]
    --------------------
    [TRACE]
  code: 'ER_SERVER_SHUTDOWN',
  errno: 1053,
  sqlMessage: 'Server shutdown in progress',
  sqlState: '08S01',
  index: 0,
  sql: 'ALTER TABLE `invitations` ADD CONSTRAINT `FK_62c53a5b672adbef1ccb69f5a4b` FOREIGN KEY (`TABLE_NAME`) REFERENCES `countries`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION'

error: Error: Connection lost: The server closed the connection.
    [STACK]
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
```

My goal is to catch that event and the SQL query, so that when a new connection is established, I can execute these cached SQL queries, so no data is lost. Maybe TypeORM as an built-in way or event to detect such things.

#### Through unhandled rejection handler
```ts
process.on('unhandledRejection', listener => {
    if (listener!.toString().match(/ECONNREFUSED/) ||
        listener!.toString().match(/Connection is not established/)) {
        logger(`Connection to ${bold(target_database.database)} has been lost. Retry to connect ...`, _PRIORITY.CRITICAL, null, _MODULE.MAIN);
        conn?.close()
        conn?.connect()
    }

})
```
The problem is that I don't get enough data. I can manually close the connection (since TypeORM still thinks that the connection is there) and then I can try a reconnect. Problem is just that I'm not able to cache queries that were made while the database wasn't available. And another problem is that this might trigger on an other event which isn't related to the database at all.

#### Directly using the underlying MySQL driver
```ts
// I also tried to use the 'enqueue' event, which doesn't trigger either.
// @ts-ignore: Since `pool` doesn't exist in the type definition
conn.driver.pool.on('error', (error) => {
    logger(`Connection to ${bold(target_database.database)} has been lost. Retry to connect ...`, _PRIORITY.CRITICAL, null, _MODULE.MAIN);
})
```
Here I get the driver property of my TypeORM connection and of that the `pool` object. I don't get an runtime error, so I assume that this object exists. The problem is just that this never triggers.

### My config
```ts
{
    name: "development",
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "****-backend-dev",
    password: "*****",
    database: "****-backend-dev",
    synchronize: true,
    logging: true,
    entities: [
        "src/models/**/*.ts"
    ],
    migrations: [
        "src/migration/**/*.ts"
    ],
    subscribers: [
        "src/subscriber/**/*.ts"
    ],
    extra: {
        connectionTimeoutMillis: 1000,
        idleTimeoutMillis: 1500
    }
}

**Comment by Mondei1** [comment]
Update: I'm actually able to get queries **after** they got executed with a custom logger:
```ts
export class CustomTypeORMLogger implements Logger {

    logQueryError(error: string, query: string, parameters?: any[] | undefined, queryRunner?: QueryRunner | undefined) {
        if (this.isDown) {
            logger(`Query "${query}" ${chalk.grey(`-- [${parameters?.join(", ")}`)}] will be cached!`, _PRIORITY.NORMAL, null, _MODULE.DB)
        } else {
            this.isDown = true
            logger(`Query "${query}" ${chalk.grey(`-- [${parameters?.join(", ")}]`)} 
            failed because ${chalk.bold(error)}"
            
            === [DATABASE IS OFFLINE] ===
            
            `, _PRIORITY.ERROR, null, _MODULE.DB)
        }
    }
    logQuery(query: string, parameters?: any[] | undefined, queryRunner?: QueryRunner | undefined) {
        logger(`Query "${query}" ${chalk.grey(`-- [${parameters?.join(", ")}]`)} was ${chalk.bold("successful")}`, _PRIORITY.DEBUG, null, _MODULE.DB)
    }
    [...]
```
Which leads to that output:
```
[14:47:32,859] DEBG [DB   ]:    Query "SET FOREIGN_KEY_CHECKS = 1;" -- [undefined] was successful
```

So far, so good. But it's still weird. Every time TypeORM syncs the database (creating tables, sets up foreign keys) and it loses connection in that period, the logger receives a message that get's logged:
```
[14:53:39,319] # ERROR [DB   ]: Query "ALTER TABLE `password_reset` ADD CONSTRAINT `FK_e279a7b047bf32bc5dd17b43fdc` FOREIGN KEY (`user`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION" -- [undefined] 
            failed because Error: ER_SERVER_SHUTDOWN: Server shutdown in progress"
            
            === [DATABASE IS OFFLINE] ===
            
            
[14:53:39,320] DEBG [DB   ]:    Query "ROLLBACK" -- [undefined] was successful
[14:53:39,321] INFO [DB   ]:    Query "ROLLBACK" -- [undefined] will be cached!
```
Now I start the MariaDB server again and the backend and stop the database again after the backend finished syncing and proceeds with seeding the DB with dummy data *(after the connection was successful)* I get **ECONNREFUSED** errors:
```
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
    --------------------
    at Protocol._enqueue (.../node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (.../node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (.../node_modules/mysql/lib/Connection.js:119:18)
    [...]
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}
```
But `logQueryError(...)` doesn't get triggered. I assume it's a driver issue and not TypeORM (I'm not sure). Maybe TypeORM doesn't even notice that, since the driver throws that error. The thing is, I don't want that to be triggered. I want it to continue normally and to cache the finish constructed SQL-queries, so I can execute them later, when the database is back online.

### Another approach
I also tried using subscribers with the `beforeInsert(...)` event which works like expected but I haven't seen a way to get a SQL query out of that. I also tried to override the `.query(...)` function but that didn't helped really. *I'm lost, really :sob:*

Maybe this isn't really possible and I have to use Redis which takes care of that? I really don't know.

**Comment by dani3l** [comment]
hi guys
any update on this one?

**Comment by segovia-no** [comment]
I also have the same problem, i'm trying to repurpose the default connection to connect to another server (after closing it).

**Comment by Mondei1** [comment]
This seems to be a common problem if already 8 people showed interest.

As for myself: This issue is now more then a year old and I don't work on the project anymore where I required a solution to this problem. It would be great if someone could experiment on it's own to solve this issue but it would be much easier if the dev team could implement a exposed handler or internal mechanic to solve this. It's very important to not lose queries if the connection drops for e. g. 30secs.

**Comment by VarunBatraIT** [comment]
I am also facing the same problem:
So far I am thinking:

- Should there be a ping functionality and auto-reconnect? 
- What about an event on the loss of connection as well with ping to move to a different server as mentioned by @segovia-no

**Comment by alexey2baranov** [comment]
in my current project we use TypeORM to interact with Aurora AWS. Sometimes Aurora shutdowns server and instantiate another one. Previous team used Sequelize internal `retry` feature to handle this situation. It performed autoreconnect during specified period and everything wend well. So I believe it is possible to do in TypoORM. I have a few ideas which I will describe in next post.

**Comment by alexey2baranov** [comment]
TypeORM has internal custom logger feature which I guess may be utilized for this purpose. Currently we utilize it to collect SQL, start time, end time and parameters of each query to send to AWS XRay. It works perfect. And I believe we can utilize this logger for retrying as well. Perhaps all we need is to introduce a cache to store store all this data and perform broken query later after reconnect.

**Comment by alexey2baranov** [comment]
BTW: doesn't this canRetry do the job? https://typeorm.io/multiple-data-sources#replication
```
   /**
    * If true, PoolCluster will attempt to reconnect when connection fails. (Default: true)
    */
    canRetry: true,
```

**Comment by krisanalfa** [comment]
@alexey2baranov I've tried `canRetry`, it only retry the initial connection. Once your connection Pool established, then it's disconnected for any reason, TypeORM still won't be able to reconnect your broken connection - leaving all queries failed.

**Comment by mustard-mh** [comment]
Faced kind of the same problem
- Stop mysqld after ts server started
- Restart mysqld again
- It'll never reconnect. With error `Pool does Not exists` always 😨

**Comment by MedFBoudis** [comment]
Any updates on this ? kind of a deal breaker...

**Comment by yatishbalaji** [comment]
Any update on this. eagerly waiting since we get this issue in production

**Comment by gabrielcipriano** [comment]
> Faced kind of the same problem with `replication` configured
> 
> * Stop mysqld after ts server started
> * Restart mysqld again
> * It'll never reconnect. With error `Pool does Not exists` always 😨

I'm facing exactly the same problem

**Comment by LuckyArdhika** [comment]
i will migrate to other orm if nothing resolve here

**Comment by theocerutti** [comment]
Any solution ? I mean it's mandatory for production so...
Is typeorm only used for dev?

**Comment by Lacrimosica** [comment]
On the other hand, what I managed to implement yesterday was to handle this error.
of course, this is limited to my use case.
what I did was to implement a GlobalExceptionHandler which actually lets you catch the ECONNREFUSED exception, whereas in its absence Nest would not let you catch it.

DISCLAIMER:
this is not related to typeorm so and is rather just a workaround so excuse me if I'm posting it here, I just supposed it might help someone since at first i was perplexed by the fact that i couldn't catch this error and handle it, but then i discovered that implementing a gloablExceptionHandler gives you control over it (which seems obvious i know but whatever)

```
@Catch()
export class GlobalExceptionFilter implements ExceptionFilter {

  MAX_RETRIES = 10;
  RETRY_DELAY = 10000;
  FAILED_REQUEST_DELAY = 5000;
  private failedRequests: FailedRequest[] = [];
  
  async catch(exception: any, host: ArgumentsHost) {
      const ctx = host.switchToHttp();
      let response = ctx.getResponse<Response>();
      const request = ctx.getRequest<Request>();
  
      /*
        When the database is down and the connection is lost, the exception is not an instance of HttpException
        rather it has the exception code ECONNREFUSED
        We identify it and implement a strategy to restore the connection
        and retry the failed requests
       */
       
      if (exception && exception.code && exception.code.includes('ECONNREFUSED')) {
        console.error('Detected database connection issue! Trying to reconnect...');
        const connection: Connection = getConnection();
        return this.handleDatabaseConnectionIssue(connection, ctx, request, response);
      }
  
      /* rest of the default/generic exception handling code */
  
      ...
  
      response.status(status).json(GlobalResponseError(status, message, code, request));
    },
  ```

  **inside the handleDatabaseConnectionIssue:**
  
```
   async handleDatabaseConnectionIssue(connection: Connection, ctx: HttpArgumentsHost, request: any, response: any) {
    let retries = 0;
    let retrySuccessful = false;

    const failedRequest: FailedRequest = {
      method: request.method,
      endpoint: request.url,
      body: request.body,
      headers: request.headers,
    };

    this.failedRequests.push(failedRequest);

    /*
      I closed the connection because although the connection has been lost,
      the connection.isConnected() method returns true, and the connection.connect() method does not work.
    */

    await connection.close();
    while (retries < this.MAX_RETRIES && !retrySuccessful) {
      /* delay the execution of the loop */
      await new Promise(res => setTimeout(res, this.RETRY_DELAY));

      try {
        await connection.connect();
        console.log('Reconnected to the database successfully.');
        /* when the connection is restored, retry the failed requests */
        const result = await this.retryFailedRequests();
        /* if the request is retried successfully, send the response to the client */
        if (result) {
          response.status(result.status).send(result.data);
          response.headers = result.headers;
          retrySuccessful = true;
        }
        retries = 0;
      } catch (err) {
        console.log(`Failed to reconnect to the database on attempt ${retries + 1}.`, err.stack);
        retries++;
      }

      if (retries >= this.MAX_RETRIES) {
        console.log('Exceeded max retries. Giving up on database reconnection.');
      }
    }
  }
  ```
  
 **my use case was to redo the call to the database therefore i retried doing the http call that i had put inside the failedRequests array and then retry them using axios:**
  
  ```
  private async retryFailedRequests() {
    while (this.failedRequests.length) {
      const request = this.failedRequests.shift();
      await new Promise(res => setTimeout(res, this.FAILED_REQUEST_DELAY));
      const axiosRequest ={
        method: request.method,
        url: process.env.BASE_URL + request.endpoint,
        headers: request.headers,
        data: request.body
      }

      try {
        const response = await axios(axiosRequest);
        console.log('Request retried successfully:', response.data);
        return response;
      } catch (error) {
        console.error('Failed to retry the request:', error.message);
        this.failedRequests.push(request);
      }
    }
  }
  ```
  
it goes without saying that there are other workarounds such as using a queuing framework that could redo the http calls instead of doing them internally in your application. for example, configuring it to redo the http calls to your application in case of a certain error code, using master/slave replication options which I tried but really didn't get into since it was a pain and wasn't really my use case nor had I the possibility.
passing retryAttempts and retryDelay only serves when the application is restarted, instead, this use case is more directed towards databases that might break under certain conditions and there is the need to just wait it out for a minute or so and you want the user to not loose connection, of course, client-side timeouts should be considered.

**Comment by MickaelDjak** [comment]
Have the same problem
I expect to see 2 options:
1 set up reconnection logic true/false
2 specifing errorHandler or something like that 

but see nothing from that

There are any plan to add any solution to hanlde next errors:
- Connection terminated unexpectedly
- Connection terminated
?

**Comment by americano212** [comment]
I have the same problem.

I used docker for running mysql database. 
When I tried to connect immediately docker-up, it throw 'Connection lost' error.

**Comment by sirNugg3ts** [comment]
How is there still no way to fix this?

**Comment by geezer78** [comment]
Same here.
 we definitely need a way to reconnect on errors and handle the potential queue

**Comment by dberardo-com** [comment]
indeed i can't believe this feature was not implemented from day 1. 

on possible workaround could be to kill the nodejs process within poolErrorHandler(), but is there is such a possibility also at the very beginning, i.e. when the client cannot initialize the connection to the backend service ?

sure this is not ideal ...

**Comment by leonardocaylent** [comment]
`Any updates on this ? kind of a deal breaker...`
Totally agree, 4 years since the issue was opened. Anyone was able to find another ORM that doesn't have this issue?

**Comment by sirNugg3ts** [comment]
> `Any updates on this ? kind of a deal breaker...` Totally agree, 4 years since the issue was opened. Anyone was able to find another ORM that doesn't have this issue?

at this point I just switched to Prisma... doesnt seem to break like this

**Comment by dberardo-com** [comment]
hi there @leonardocaylent  and @sirNugg3ts  have you tried this weird workaround of mine ? 

https://github.com/brianc/node-postgres/issues/3220

--> this should be added to the typeorm datasource (or factory) configs
```js
      // https://github.com/typeorm/typeorm/issues/6350
      // @ts-ignore
      poolErrorHandler: async (err, client) => {
        Logger.error("Error here", err);
        const retryDelayMs = 10000;
        let reconnection
        const reconnect = async () => {
          try {
            // client.connection is of type: https://github.com/brianc/node-postgres/blob/master/packages/pg-protocol/src/serializer.ts
            client.connection.query("select 1;")
          } catch (error) {
            console.warn(error)
          }
        }
        reconnect()
        reconnection = setInterval(reconnect, retryDelayMs);
      },
    }
```

and then to deal with connection errors on init (in case you use durable providers): https://github.com/nestjs/nest/issues/13953#issuecomment-2431114834


both of them are must haves, so my workarounds still smell fishy to me, but they seem to work. let me know if you find the time to test them and if they work for your setup as well and whether that could be a reliable fix.

**Comment by Craig1f** [comment]
Here for this problem. The feature enhancement seems simple: 

- Allow an async function as a value for the password, instead of only a string
- If the password ever fails, run the function again to get a fresh password
- If the password fails immediately after a fresh value is retrieved, then we have a REAL failure and can throw an exception
  - Optional: Allow retries with a timeout, to deal with a race condition where a password rotation is happening, but the password on the DB has been updated before the password in Secrets Manager (or wherever else it is stored)

Right now, I'm trying to solve this. I'm thinking that I need to just do an instance refresh on my servers any time we do a password rotation in AWS. Which means downtime. that is super sloppy, but I don't know how else to handle it.

**Comment by BeihaiNorth** [comment]
Im facing `Pool does Not exists` after database failure and adding this option solves my problem! 
`restoreNodeTimeout: 60000` This will retry connection after 60 seconds.

Ref: https://typeorm.io/multiple-data-sources#supported-drivers

**Comment by clintonb** [comment]
We just had an incident related to this issue. We are rolling out a read replica behind PgBouncer. The replica isn't frequently used (since it's still being rolled out) so PgBouncer kills the idle connections after 10 minutes. This results in TypeORM being stuck until we restart the application.

Our hacky workaround was to add a replica "ping" (`SELECT 1`) to our health endpoint. Kubernetes probes this endpoint every 10 seconds, which helps ensure the connection remains live. This is a slowly ticking incident waiting to happen.

I believe this is the same problem described in https://github.com/typeorm/typeorm/issues/5112, but the fix doesn't work.

We are using TypeORM `0.3.22` with Postgres 17.

**Comment by alumni** [comment]
In SAP HANA, the pool client handles this by default (both the old client that hasn't been maintained for 5+ years and the new one that TypeORM will use in the next release).

Isn't there something similar in the Postgres client?

**Comment by clintonb** [comment]
I rolled out some new configuration yesterday after reading more of the node-postgres docs and open issues. It would be ideal if the TypeORM docs covered the concepts of TCP keep-alives and idle connections. These seem like somewhat advanced, yet pretty important, concepts needed for running an application in production.

```ts
{
    extra: {
      // Send TCP keepalives from the client within 10 seconds of a connection being idle.
      // This will alert the client to connections closed by the server,
      // and remove the closed connections.
      //
      // This feature exists in node-postgres but is not documented.
      // See https://github.com/brianc/node-postgres/issues/2362 for discussion
      // about the feature.
      // See https://www.postgresql.org/docs/17/libpq-connect.html#LIBPQ-KEEPALIVES
      // for docs from the underlying library, libpq.
      keepAlive: true,
      keepAliveInitialDelayMillis: 10_000,

      // Kill connections that have sat idle for more than 30 seconds
      idleTimeoutMillis: 30_000,

      // NOTE: pgbouncer does not support statement_timeout. See https://github.com/pgbouncer/pgbouncer/issues/525.
      // Maximum timeout for all queries and commands
      // statement_timeout: Number(process.env.DB_STATEMENT_TIMEOUT) || undefined,
    },
}
```

**Comment by alumni** [comment]
Hmm, seems `keepAlive` should be enabled by default? Or maybe it is only if the `pg-native` client is used instead of `pg`.

I'm preparing a PR to cleanup the docs a little bit, will only link the official `Pool` and `Client` docs.

For _MySQL_: the `mysql2` library has the `enableKeepAlive` option.

**Comment by clintonb** [comment]
Keep alives didn't help. `connectionTimeoutMillis` is set to 10 seconds, and all calls to my read replica are failing to connect after 10s.

**Comment by utibeabasi6** [comment]
> Keep alives didn't help. `connectionTimeoutMillis` is set to 10 seconds, and all calls to my read replica are failing to connect after 10s. 

Were you able to find a solution to this? I am trying to run pgbouncer behind a network load balancer on AWS and that has a connection timeout
So client side keep alive would help a ton

**Comment by alumni** [comment]
There's this thread on the node postgres repo: https://github.com/brianc/node-postgres/issues/2362

**Comment by clintonb** [comment]
@utibeabasi6 no, I don’t have a solution. This was only an issue for my read replica, which was infrequently used since it was being slowly rolled out. I opted to stop using the replica after a multi-day incident investigation and two production outages.
