### ISSUE TITLE
eager loading of Entities with @RelationId causes 'ER_BAD_NULL_ERROR'

### ISSUE THREAD

**Issue by yorickdevries** [typeorm/typeorm#6356]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have 2 classes `Review` and `QuestionAnswer` connected with a `@OneToMany` relationship, where `QuestionAnswer` is referencing `Review` with a `@RelationId` decorator which is used as `@PrimaryColumn` as well. In addition,  `Review` eagerly loads the answers as well.

```ts 
\\Review.ts
  @OneToMany(
    (_type) => QuestionAnswer,
    (questionAnswer) => questionAnswer.review,
    { eager: true }
  )
  questionAnswers!: QuestionAnswer[];
```

```ts 
\\QuestionAnswer.ts
  @PrimaryColumn()
  @RelationId((questionAnswer: QuestionAnswer) => questionAnswer.review)
  reviewId!: number;
  @ManyToOne((_type) => Review, (review) => review.questionAnswers, {
    nullable: false,
  })
  review?: Review;
```

However, when I load a `Review` entity from the database (including eagerly loaded `QuestionAnswer`). When I save the entity I get a `ER_BAD_NULL_ERROR` from the database:

Saving:

```ts
const review = await Review.findOne(req.params.id);
await review!.save();
```

```
QueryFailedError: Column 'reviewId' cannot be null
    at new QueryFailedError (C:\repositories\peer\server\src\error\QueryFailedError.ts:9:9)
    at Query.onResult (C:\repositories\peer\server\src\driver\mysql\MysqlQueryRunner.ts:167:37)
    at Query.execute (C:\repositories\peer\server\node_modules\mysql2\lib\commands\command.js:30:14)
    at PoolConnection.handlePacket (C:\repositories\peer\server\node_modules\mysql2\lib\connection.js:417:32) 
    at PacketParser.onPacket (C:\repositories\peer\server\node_modules\mysql2\lib\connection.js:75:12)        

    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  sqlMessage: "Column 'reviewId' cannot be null",
  query: 'UPDATE `question_answer` SET `reviewId` = ?, `updatedAt` = CURRENT_TIMESTAMP WHERE `questionId` = ? 
AND `reviewId` = ?',
  parameters: [ undefined, 5, 1 ]
}
```

Firstly, I do not udnerstand why typeorm is updating the `QuestionAnswer` table in the first place when I solely save the `Review`. I did not set `{cascade: true}` anywhere in my code. Disabling eager loading casues this error to not occur anymore, but casues quite some hassle as this relation needs to be loaded separately now. Any idea why this problem occurs ans how to mitigate it?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by Menci** [comment]
A workaround is -- nither use `eager` or `await entity.relatedEntity`. Only use `relatedEntity.find({ relation })` to obtain the related entity.

**Comment by Menci** [comment]
Also, I think this bug is not related to `eager`. Use `await` on a non-eager relation will also cause this bug. Could you change the title?
