### ISSUE TITLE
When trying to run the tests, connecting to PostgreSQL seems to fail

### ISSUE THREAD

**Issue by pupeno** [typeorm/typeorm#6386]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to run the TypeORM tests locally. I'm using the Docker images to run all the databases by simply running:

```
docker-compose up
```

I copied `ormconfig.json.dist` to `ormconfig.json` and then I run:

```
npm run compile ; npm run test
```

It crashes with this error:

```
> npm run compile ; npm run test

> typeorm@0.2.25 compile C:\Users\pupeno\Documents\Flexpoint Tech\js\typeorm
> rimraf ./build && tsc


> typeorm@0.2.25 test C:\Users\pupeno\Documents\Flexpoint Tech\js\typeorm
> rimraf ./build && tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 60000 ./build/compiled/test



  √ github issues > #3158 Cannot run sync a second time (475ms)
  √ github issues > #3588 Migration:generate issue with onUpdate using mysql 8.0 (116ms)
  benchmark > bulk-save > case1
connecting
    1) "before all" hook for "testing bulk save of 10.000 objects"
    2) "after all" hook for "testing bulk save of 10.000 objects"


  2 passing (1m)
  2 failing

  1) benchmark > bulk-save > case1
       "before all" hook for "testing bulk save of 10.000 objects":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\pupeno\Documents\Flexpoint Tech\js\typeorm\build\compiled\test\benchmark\bulk-save-case1\bulk-save-case1.js)
      at listOnTimeout (internal/timers.js:551:17)
      at processTimers (internal/timers.js:494:7)

  2) benchmark > bulk-save > case1
       "after all" hook for "testing bulk save of 10.000 objects":
     TypeError: Cannot read property 'map' of undefined
      at Object.closeTestingConnections (test\utils\test-utils.ts:285:36)
      at Context.<anonymous> (test\benchmark\bulk-save-case1\bulk-save-case1.ts:16:17)
      at processImmediate (internal/timers.js:458:21)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typeorm@0.2.25 test: `rimraf ./build && tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 60000 ./build/compiled/test`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the typeorm@0.2.25 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pupeno\scoop\persist\nodejs\cache\_logs\2020-07-11T09_15_28_115Z-debug.log
```

Trying to debug what's going on, as far as I can see, it times out when connecting to the PostgreSQL database, but the other databases seem to work and connecting with my PSQL client (DataGrip) using the same credentials as in `ormconfig.json` also works.

I'm not sure if this is a bug or a question. Any ideas what's going on here?

**Comment by pupeno** [comment]
I have also tried connecting to my locally running PostgreSQL, created a user with appropriate username and password and a database. My own project connects fine to that PostgreSQL, but I can't get the TypeORM tests to connect.

**Comment by imnotjames** [comment]
What version of Postgres is installed?

**Comment by imnotjames** [comment]
Usually this is because you're using an old version of postgres for the tests.
