### ISSUE TITLE
Combining ManyToOne, Cascade, & Composite Primary Key causes Unique Constraint issues

### ISSUE THREAD

**Issue by imnotjames** [typeorm/typeorm#6416]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

**Steps to reproduce or a small repository showing the problem:**

I've found that a relationship between two entities where one is `ManyToOne`, cascading, and the relationship is part of a composite primary key causes various problems when persisting the entities.

Generally, what happens is that during persistence when the [subject recomputes](https://github.com/typeorm/typeorm/blob/3227c0b7b9f79868f755eb40e72287bdb60d71b6/src/persistence/Subject.ts#L290-L294), the `ManyToOne` primary key field gets set with the entity on the other side of the relationship.

However, when `SubjectDatabaseEntityLoader.findByPersistEntityLike` gets called it can query the `Entity` from the database (because `{ where: { otherId: OtherEntity() } }` works but `subject.metadata.compareEntities` can't understand the relationship.

This means that the first time we save a record and the related entities it works & inserts everything as expected.  However, the second time it does not and tries to insert the related entities again - even with their primary keys - causing a unique constraint issue.

In my case, because we're using transformers on the primary keys, I am struggling to get the relationship to work at all without the field.

I'll be creating a test and digging into a few possible solutions for this.

---

Minimal Example Entities which exhibit the behavior below.  To note, `PostTag` has a custom generation because `sqlite` does not support composite primary key `AUTOINCREMENT`.

```
import { EntitySchema } from '../../../../src/entity-schema/EntitySchema';

import PostTag from './PostTag';

export default class Post {
    postId: number;

    title: string;

    tags: PostTag[];
}

export const PostSchema = new EntitySchema<Post>({
    name: 'Post',
    target: Post,
    columns: {
        postId: {
            generated: true,
            type: Number,
            primary: true
        }
    },
    relations: {
        tags: {
            target: () => PostTag,
            type: "one-to-many",
            inverseSide: (tag: PostTag) => tag.post,
            cascade: true
        }
    }
});
```

```
import { EntitySchema } from '../../../../src/entity-schema/EntitySchema';

import Post from './Post';

let id = 0;

export default class PostTag {
    postTagId: number;

    postId: string;

    name: string;

    post: Post;

    constructor () {
        this.postTagId = id++;
    }
}

export const PostTagSchema = new EntitySchema<PostTag>({
    name: 'PostTag',
    target: PostTag,
    columns: {
        postId: {
            type: Number,
            primary: true
        },
        postTagId: {
            type: Number,
            primary: true
        }
    },
    relations: {
        post: {
            nullable: false,
            target: () => Post,
            inverseSide: (post: Post) => post.tags,
            type: 'many-to-one',
            joinColumn: { name: 'postId' }
        }
    }
});
```

The error received on the second save of the Entity when using SQLite is:

```
QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: post_tag.otherId, post_tag.postId, post_tag.postTagId
    at new QueryFailedError (typeorm/src/error/QueryFailedError.ts:9:9)
    at Statement.handler (typeorm/src/driver/sqlite/SqliteQueryRunner.ts:53:26) {
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  query: 'INSERT INTO "post_tag"("otherId", "postId", "postTagId") VALUES (?, ?, ?)',
  parameters: [ 3, 2, 1 ]
}
```

**Comment by imnotjames** [comment]
Test case can be found in the draft pull request https://github.com/typeorm/typeorm/pull/6417

**Comment by imnotjames** [comment]
So the `Subject` code in question that's causing issues in `Subject.Recompute` -

```
            if (this.parentSubject) {
                this.metadata.primaryColumns.forEach(primaryColumn => {
                    if (primaryColumn.relationMetadata && primaryColumn.relationMetadata.inverseEntityMetadata === this.parentSubject!.metadata) {
                        primaryColumn.setEntityValue(this.entityWithFulfilledIds!, this.parentSubject!.entity);
                    }
                });
            }
```

Pretty much, if there's a `parent` relationship here (from cascades?) the entire parent entity gets written into the primary column. ):

Not what we want.

**Comment by imnotjames** [comment]
If we omit the `parentId` from the child entity everything _does_ work as expected - and that code path doesn't get called.

**Comment by imnotjames** [comment]
So- when the `parentId` is not explicitly added the virtual property is added in its stead - it's pointing at the `parentId` under the hood & is used to set the value in the database.

This means that if there's two parent IDs - such as `parentId` and `otherParentId` you end up with TWO virtual primary columns.

However, each of the columns that have `relationMetadata` also have the `referencedColumn` set on them.  There shouldn't be a case where it isn't set.

As such, we can rewrite the `Subject` recompute to be a bit more correct with:

```
                        primaryColumn.setEntityValue(
                            this.entityWithFulfilledIds!,
                            primaryColumn.referencedColumn!.getEntityValue(this.parentSubject!.entity!)
                        );
```

Thus setting the entity value on the child to the value on the parent.

**Comment by imnotjames** [comment]
One thing that would help with composite primary keys is that the generated column in the [RelationJoinColumnBuilder](https://github.com/typeorm/typeorm/blob/ee61c518d746139babbbeaa19b8f3d6e87e34f08/src/metadata-builder/RelationJoinColumnBuilder.ts#L137-L167) will have overlap in the name.

Giving it a unique property name will improve some of the identity retrieval.

**Comment by imnotjames** [comment]
Looks like - even with the explicitly defined fields - `Subject.createValueSetAndPopChangeMap` still sets everything as if it were setting the relationship - so the `updateMap` becomes `{ post: { postId: 2, otherId: 3 } }` - that's not quite right..

However, The second update is now trying to remove the child from the parent per [`OneToManySubjectBuilder`](https://github.com/typeorm/typeorm/blob/a9bdb37d3bc765933f16041622bc35073a98de09/src/persistence/subject-builder/OneToManySubjectBuilder.ts#L158-L160) - Could be related to the above.  Not sure what has it hitting this code path on the second save - going in, everything looks right.. except...

```
removedRelatedEntityRelationId = {
 otherId: {otherId: 3},
 postId: {postId: 2},
 postTagId: 1
}
```

Now.. How in the world is that happening? :thinking:
