### ISSUE TITLE
Naming strategy of embedded columns

### ISSUE THREAD

**Issue by Masterrg** [typeorm/typeorm#645]
Hello everyone,

I am currently trying to move my schema from mongoose to typeorm. Here's a small example of parts of a document in our MongoDB database:

```js
{
    "_id" : ObjectId("596380fc46fba40ee4d51ddc"),
    "name" : "Test",
    "contact" : {
        "general" : {
            "email" : "mymail@me.com",
            "fax" : "+4911111",
            "phone" : "+4922222",
        },
       "business" : {
            "email" : "mymail@me.com",
            "fax" : "+4911111",
            "phone" : "+4922222",
        }
    }
}
```
As you can see I got (at least) two fields in our "contact" field.

My current solution is to create the following entities:
```js
@Entity()
export class House {
    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    name: string;

    @Column(type => HouseContact)
    contact: HouseContact;
}
```

```js
@Entity()
export class HouseContact{
    @ObjectIdColumn()
    id?: string;

    @Column(type => Contact)
    general: Contact;

    @Column(type => Contact)
    business: Contact;
}
```

```js
@Entity()
export class Contact {
    @ObjectIdColumn()
    id?: string;

    @Column()
    email: string;

    @Column()
    fax: string;

    @Column()
    phone: string;
}
```
(Yeah I know, it's a bit tricky but unfortunately I can't change the Schema)

Everything works fine except the naming of the two fields "general" and "business", typeorm names those fields "contact_general" and "contact_business", here's an example:

```js
{
    "_id" : ObjectId("596380fc46fba40ee4d51ddc"),
    "name" : "Test",
    "contact" : {
        "contact_general" : {
            "email" : "mymail@me.com",
            "fax" : "+4911111",
            "phone" : "+4922222",
        },
       "contact_business" : {
            "email" : "mymail@me.com",
            "fax" : "+4911111",
            "phone" : "+4922222",
        }
    }
}
```

**My question is the following:** Can I somehow change those names to fit my (old) schema?

**Comment by pleerock** [comment]
probably its not correct behaviour specifically for mongodb database. So I'll mark it as bug and will fix in next versions.

**Comment by Masterrg** [comment]
Hey @pleerock ,

sorry to bother you: Is there any progress on this issue / an ETA for a fix?

**Comment by makislav** [comment]
We need it too. This is a huge blocker when trying to use typeorm on mongodb :/

**Comment by pleerock** [comment]
fix will be released in `0.1.0-alpha.33` on days

**Comment by makislav** [comment]
@pleerock sorry to trigger you again, but the issue kinda still exists. I have compile the stuff manually to test it. However, the problem changed a bit:

The data gets saved correctly, but the load now triggers an error:

```
[Nest] 7468   - 2017-7-26 11:41:24   [ExceptionsHandler] Cannot read property 'general' of undefined
TypeError: Cannot read property 'general' of undefined
    at D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:110:52
    at Array.forEach (native)
    at addEmbeddedValuesRecursively (D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:86:23)
    at D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:110:17
    at Array.forEach (native)
    at addEmbeddedValuesRecursively (D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:86:23)
    at DocumentToEntityTransformer.transform (D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:114:9)
    at D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:27:47
    at Array.map (native)
    at DocumentToEntityTransformer.transformAll (D:\location-finder\src\query-builder\transformer\DocumentToEntityTransformer.ts:27:26)
    at D:\location-finder\src\entity-manager\MongoEntityManager.ts:212:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

I am using the example of @Masterrg. As soon as I change the Contact entity to
```ts
@Entity()
export class Contact {
    @ObjectIdColumn()
    id?: string;

    @Column()
    contact_email: string;

    @Column()
    contact_fax: string;

    @Column()
    contact_phone: string;
}
```
.. the "find" query works again.

**Comment by Masterrg** [comment]
@pleerock 
@makislav 

Well it seems it's a bit more complex, here's an example which represents more or less our usecase (nested documents in nested documents [..]).

User.ts
```ts
@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    name: string;

    @Column(type => ContactContainer)
    contact: ContactContainer;
}
```

ContactContainer.ts
```ts
@Entity()
export class ContactContainer {

    @ObjectIdColumn()
    id?: string;

    @Column(type => Contact)
    general: Contact;

    @Column(type => Contact)
    otherstuff: Contact;

    @Column(type => Contact)
    moreotherstuff: Contact;
}
```

Contact.ts
```ts
@Entity()
export class Contact {

    @ObjectIdColumn()
    id?: string;

    @Column()
    email: string;

    @Column()
    fax: string;

    @Column()
    phone: string;
}
```

**This results in:** TypeError: Cannot read property 'general' of undefined
**Stacktrace:**
```
at extractEmbeddedColumnValue_3 (H:\typeormtesting\src\metadata\ColumnMetadata.ts:367:86)
      at extractEmbeddedColumnValue_3 (H:\typeormtesting\src\metadata\ColumnMetadata.ts:367:39)
      at ColumnMetadata.getEntityValue (H:\typeormtesting\src\metadata\ColumnMetadata.ts:371:36)
      at H:\typeormtesting\src\persistence\SubjectOperationExecutor.ts:967:56
      at Array.forEach (native)
      at H:\typeormtesting\src\persistence\SubjectOperationExecutor.ts:963:47
      at Array.forEach (native)
      at SubjectOperationExecutor.updateSpecialColumnsInPersistedEntities (H:\typeormtesting\src\persistence\SubjectOperationExecutor.ts:959:29)
      at SubjectOperationExecutor.<anonymous> (H:\typeormtesting\src\persistence\SubjectOperationExecutor.ts:114:20)
      at step (node_modules\typeorm\persistence\SubjectOperationExecutor.js:32:23)
      at Object.next (node_modules\typeorm\persistence\SubjectOperationExecutor.js:13:53)
      at fulfilled (node_modules\typeorm\persistence\SubjectOperationExecutor.js:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

The "simple" case like it is illustrated in the tests is working properly but as soon as you got several nested documents it seems to fail.

**Comment by pleerock** [comment]
@makislav @Masterrg sorry for delayed answer, I was on vacation.

So, looks like you have several issues in your code - first you should not use `@Entity()` decorator on embedded entities. Second, you should not have `@ObjectIdColumn()` columns inside embedded entity (because mongodb's object id is only in root of the document, right)

**Comment by pleerock** [comment]
report a separate issue and check on latest `@next`.

**Comment by netspencer** [comment]
Does anybody have a solution for this? I am having issues with nested documents inside of nested documents.

```typescript
import { Entity, Column, ObjectIdColumn, ObjectID } from 'typeorm'

export class Cell {
  @Column()
  duoPhoto1?: string

  @Column()
  duoPhoto2?: string

  @Column()
  smallSizeMedia?: string

  @Column()
  midSizeMedia?: string

  @Column()
  largeSizeMedia?: string

  @Column()
  description?: string

  @Column()
  title?: string

  @Column()
  subtitle?: string
}

export class Page {
  @Column(type => Cell)
  cells?: Cell[]
}

@Entity('mag')
export class MagEntity {
  @ObjectIdColumn()
  id: ObjectID

  @Column()
  description: string

  @Column(type => Page)
  cover: Page

  @Column(type => Page)
  pages?: Page[]
}

```

**Comment by jasperblues** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/embedded-entities.md 

^-- Until fixed, the above documentation is invalid.
