### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by CreeJee** [typeorm/typeorm#6464]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

package-lock.json : https://pastebin.com/gKnybUr9
OS: windows

```bash

> ts-node --project tsconfig.json -r tsconfig-paths/register --files index.ts

TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (C:\Users\000as\Desktop\외주\slockimplant 리뉴얼\server_legacy\node_modules\typeorm\node_modules\chalk\index.js:72:75)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\000as\Desktop\외주\slockimplant 리뉴얼\server_legacy\src\platform\PlatformTools.ts:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by imnotjames** [comment]
This is an issue with `chalk`, not `typeorm`.
