### ISSUE TITLE
CustomRepositoryDoesNotHaveEntityError: Custom repository DICTTimeZoneRepository does not have managed entity. Did you forget to specify entity for it @EntityRepository(MyEntity)? 

### ISSUE THREAD

**Issue by alucky4eg** [typeorm/typeorm#6521]
**Issue type:**

[x] question
[ ] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

Hi!
im using this stack on my backend: typeorm, tsoa, pg

this is my entity:
```ts
import { Column, Entity, PrimaryColumn, Index } from 'typeorm';
import { _BaseEntity } from './_BaseEntity';
import { IDICTTimeZone } from './IDICTTimeZone';

@Entity()
@Index(['name', 'country_code'], { unique: true })
export class DICTTimeZone extends _BaseEntity<DICTTimeZone> implements IDICTTimeZone {
  @PrimaryColumn()
  public name: string;

  @Column({ type: 'varchar', length: 2 })
  public country_code: string;

  @Column({ type: 'varchar', length: 7 })
  public latitude: string;

  @Column({ type: 'varchar', length: 7 })
  public longitude: string;

  @Column()
  public utc_dst_offset: number;

  @Column()
  public utc_offset: number;

  @Column('varchar', { length: 255, nullable: true })
  public note?: string;
}
```
`_BaseEntity` abstract class which implements few reusable attributes and methods.

this is my custom repository:
```ts
import { AbstractRepository } from 'typeorm';

export abstract class _BaseRepository<T> extends AbstractRepository<T> implements __IBaseRepository<T> {
  public listAll(): Promise<T[]> {
    return this.repository.find();
  }
}


...

import { EntityRepository } from 'typeorm';
import { DICTTimeZone } from '../models';
import { _BaseRepository } from './_BaseRepository';
import { IDICTTimeZoneRepository } from './IDICTTimeZoneRepository';

@EntityRepository(DICTTimeZone)
export class DICTTimeZoneRepository extends _BaseRepository<DICTTimeZone> implements IDICTTimeZoneRepository {
  // stub
}
```

this is my controller:
```ts
import { getCustomRepository } from 'typeorm';
import { Get, Response, Route, Security, Tags } from 'tsoa';
import { IDICTTimeZonesResponse, IErrorResponse } from '../models/responses';
import { _BaseController } from './_BaseController';
import { DICTTimeZoneRepository, IDICTTimeZoneRepository } from '../repositories';

@Route('dict')
@Security('JWT')
export class DICTController extends _BaseController {
  private readonly _dictTimeZoneRepository: IDICTTimeZoneRepository = getCustomRepository(DICTTimeZoneRepository);

  @Response<IDICTTimeZonesResponse>('200', 'Success')
  @Response<IErrorResponse>('default', 'Error Occurred')
  @Get('tz')
  public async listDictTimeZone(): Promise<IDICTTimeZonesResponse> {

    const dict = await this._dictTimeZoneRepository.listAll();

    const response: IDICTTimeZonesResponse = {
      success: true,
      payload: dict,
    };
    return response;
  }

}
```

im using same way to manage lots of entities like this, but now I got this error here:
```
CustomRepositoryDoesNotHaveEntityError: Custom repository DICTTimeZoneRepository does not have managed entity. Did you forget to specify entity for it @EntityRepository(MyEntity)? 
    at new CustomRepositoryDoesNotHaveEntityError (/Users/alucky/dev/project/src/error/CustomRepositoryDoesNotHaveEntityError.ts:8:9)
    at DICTTimeZoneRepository.get [as repository] (/Users/alucky/dev/project/src/repository/AbstractRepository.ts:41:19)
    at DICTTimeZoneRepository.listAll (/Users/alucky/dev/project/src/repositories/_BaseRepository.ts:126:17)
    at DICTTimeZoneRepository.listAll (/Users/alucky/dev/project/src/repositories/DICTTimeZoneRepository.ts:11:18)
    at DICTController.<anonymous> (/Users/alucky/dev/project/src/controllers/DICTController.ts:27:51)
    at Generator.next (<anonymous>)
    at /Users/alucky/dev/project/src/controllers/DICTController.ts:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alucky/dev/project/src/controllers/DICTController.ts:13:12)
    at DICController.listDictTimeZone (/Users/alucky/dev/project/src/controllers/DICTController.ts:38:16)
```

how it could be?
code is same as before, but now it doesn't works

**Comment by alucky4eg** [comment]
looks like some repositories loads BEFORE entities:
```md
debug: logger created. console: true, file: false, logstash: false {"pid":11627,"node_env":"development","process":"main","func":"LoggerModel:constructor","timestamp":"2020-08-05 21:24:51"}
Entity [class Entity1 extends _BaseEntity] /Users/alucky/dev/project/node_modules/typeorm/decorator/entity/Entity.js
Entity [class Entity2 extends _BaseUUIDEntity] /Users/alucky/dev/project/node_modules/typeorm/decorator/entity/Entity.js
...
Entity [class Entity15 extends _BaseUUIDEntity] /Users/alucky/dev/project/node_modules/typeorm/decorator/entity/Entity.js
EntityRepository Entity1 [class Entity1Repository extends _BaseRepository] /Users/alucky/dev/project/node_modules/typeorm/decorator/EntityRepository.js
... 22 items
**EntityRepository undefined [class DICTTimeZoneRepository extends _BaseRepository] /Users/alucky/dev/project/node_modules/typeorm/decorator/EntityRepository.js**

**Entity [class Entity16 extends _BaseUUIDEntity] /Users/alucky/dev/project/node_modules/typeorm/decorator/entity/Entity.js**
...
Entity [class DICTTimeZone extends _BaseEntity] /Users/alucky/dev/project/node_modules/typeorm/decorator/entity/Entity.js
```

so typeorm loader loads 15 entires, then start loading all repositories and only then load rest entities.

**Comment by kasec** [comment]
Currently, I have the same problem, did you solve it?

**Comment by Spolja** [comment]
Any ideas ?
