### ISSUE TITLE
 migration creation Error: Illegal characters in path.

### ISSUE THREAD

**Issue by archer747** [typeorm/typeorm#6529]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
config.ts:

```
const dbConfig = config.get('db');

const typeOrmConfig: TypeOrmModuleOptions = {
    type: dbConfig.type,
    host: process.env.GCR_host || dbConfig.host,
    port: process.env.GCR_port || dbConfig.port,
    username: process.env.GCR_username || dbConfig.username,
    password: process.env.GCR_password || dbConfig.password,
    database: process.env.GCR_database || dbConfig.database,
    entities: [__dirname + '/../**/*.entity.{js, ts}'],
    synchronize: process.env.TYPEORM_SYNC || dbConfig.synchronize,
    logging: true,
    migrationsRun: process.env.TYPEORM_MIGRATIONS || dbConfig.migrations,
    migrationsTableName: "migrations",
    migrations: ['/../migrations/*.{js, ts}'],
    cli: {
        migrationsDir: __dirname + '/../migrations'
    }
};
```

package.json

`"typeorm": "ts-node ./node_modules/typeorm/cli.js --config ./src/config/typeorm.config.ts"`

Command Prompt:

`C:\someFolder\someApp>npm run typeorm migration:create -- -n RoleSeed`

Error message:
```
Error during migration creation:
{ Error: Illegal characters in path.
    at pathArg (C:\someFolder\someApp\node_modules\typeorm\node_modules\mkdirp\lib\path-arg.js:20:27)
    at mkdirp (C:\someFolder\someApp\node_modules\typeorm\node_modules\mkdirp\index.js:10:10)
    at Function.CommandUtils.createDirectories (C:\someFolder\someApp\src\commands\CommandUtils.ts:14:16)
    at Function.<anonymous> (C:\someFolder\someApp\src\commands\CommandUtils.ts:21:28)
    at step (C:\someFolder\someApp\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\someFolder\someApp\node_modules\tslib\tslib.js:120:57)
    at C:\someFolder\someApp\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\someFolder\someApp\node_modules\tslib\tslib.js:109:16)
    at Function.CommandUtils.createFile (C:\someFolder\someApp\node_modules\typeorm\commands\CommandUtils.js:24:24)
  path:
  'C:\\someFolder\\someApp\\C:\\someFolder\\someApp\\src\\migrations',
  code: 'EINVAL' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! someApp@0.0.1 typeorm: `ts-node ./node_modules/typeorm/cli.js --config ./src/config/typeorm.config.ts "migration:create" "-n" "RoleSeed"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the someApp@0.0.1 typeorm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
It worked properly once and went nuts afterwards. 

TypeOrm CLI cannot process **__dirname** correctly, resulting in **C:\\someFolder\\someApp\\C:\\someFolder\\someApp\\src\\migrations**.

This error is driving me crazy! Any help is appreciated.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by archer747** [comment]
Issue was caused by line 62 in [typeorm](https://github.com/typeorm/typeorm/blob/21b51f3f0159c333c55bc2bb6e7b508d29182885/src/commands/MigrationCreateCommand.ts#L63)

`const path = process.cwd() + "/" + (directory ? (directory + "/") : "") + filename;`

As you can see, it calls **process.cwd()**. this causes the path repetition.

I solved by modifying my config file to:
```
import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import * as config from 'config';

// detecting running in ts-node/node
const isTsNode = process[Symbol.for('ts-node.register.instance')]

const dbConfig = config.get('db');

const typeOrmConfig: TypeOrmModuleOptions = {
    type: dbConfig.type,
    host: process.env.GCR_host || dbConfig.host,
    port: process.env.GCR_port || dbConfig.port,
    username: process.env.GCR_username || dbConfig.username,
    password: process.env.GCR_password || dbConfig.password,
    database: process.env.GCR_database || dbConfig.database,
    entities: [__dirname + '/../**/*.entity.{js, ts}'],
    synchronize: process.env.TYPEORM_SYNC || dbConfig.synchronize,
    logging: true,
    migrationsRun: process.env.TYPEORM_MIGRATIONS || dbConfig.migrations,
    migrationsTableName: "migrations",
    migrations: [isTsNode ? '/../migrations/*.ts' : '/../migrations/*.js'],
    cli: {
        migrationsDir: isTsNode ? '/src/migrations' : '/dist/migrations'
    }
};
```

**Comment by archer747** [comment]
Eventually figured out its better with the config this way for NestJs:

```
const typeOrmConfig: TypeOrmModuleOptions = {
    type: dbConfig.type,
    host: process.env.GCR_host || dbConfig.host,
    port: process.env.GCR_port || dbConfig.port,
    username: process.env.GCR_username || dbConfig.username,
    password: process.env.GCR_password || dbConfig.password,
    database: process.env.GCR_database || dbConfig.database,
    entities: [__dirname + '/../**/*.entity.{js, ts}'],
    synchronize: process.env.TYPEORM_SYNC || dbConfig.synchronize,
    logging: true,
    migrationsRun: process.env.TYPEORM_MIGRATIONS || dbConfig.migrations,
    migrationsTableName: "migrations",
    migrations: ['./dist/migrations/*.js'],
    cli: {
        migrationsDir: './src/migrations'
    }
};
```

The only thing I noticed is that I can generate migrations from the CLI but can not run it successfully with the CLI. To run it I set `migrationsRun = 'true'` and run `npm run start:dev` to run the application.
