### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by paul-thomas0** [typeorm/typeorm#6589]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ *] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [] `mysql`
    [x ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
RangeError: Maximum call stack size exceeded
    at DerivedLogger.<computed> [as verbose] (d:\exp_workspace\neutrinos-srm\server\node_modules\winston\lib\winston\create-logger.js:95:19)
    at LoggerTypeorm.logQuery (d:\exp_workspace\neutrinos-srm\server\build\utils\ndefault-sql\ExecuteSql\LoggerTypeorm.js:9:21)
    at PostgresQueryRunner.<anonymous> (d:\exp_workspace\neutrinos-srm\server\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:165:55)
    at step (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:141:27)
    at Object.next (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:122:57)
    at fulfilled (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by imnotjames** [comment]
Do you have a sample repo or code to replicate this

**Comment by imnotjames** [comment]
This looks like a bug in the logger you've created somehow - I don't see where the typeorm library is doing this.

**Comment by EliasTouil** [comment]
I have the same problem did you find a solution?
