### ISSUE TITLE
Using plain properties (not columns) in entity classes

### ISSUE THREAD

**Issue by cstapetrei** [typeorm/typeorm#6610]
Hello, my issue would be the same as https://github.com/typeorm/typeorm/issues/3569  

```
@Entity()
export class User extends Base{

    @Column('varchar', { length: 255, unique: true })
    @IsEmail({}, { message: "Invalid email." })
    @IsUnique()
    email: string;

    @Column('varchar', { length: 255 })
    @MinLength(6, { message: "Password must have at least 6 characters" })
    password: string;

    @Column('varchar', { length: 255 })
    salt: string;

    @Column('varchar', { length: 255 })
    role: string;

    password_changed: number = 0;

    @BeforeUpdate()
    setDataBeforeUpdate(){
        if (this.password_changed){
            this.password = PasswordHelper.hashString(this.password, this.salt);
        }
    }
}
```

Let's take the above piece of code... i want the password_changed field to not be a column...just a plain old property for this class. 
The problem is that on update 
```
const repo: Repository<User> = getRepository(User);
await repo.update(row.id, row).then().catch( (e) => { throw e; });
```
i get this error

```
EntityColumnNotFound: No entity column "password_changed" was found.
    at new EntityColumnNotFound (.../src/error/EntityColumnNotFound.ts:8:9)
    at .../src/query-builder/UpdateQueryBuilder.ts:403:27
    at Array.forEach (<anonymous>)
    at UpdateQueryBuilder.createUpdateExpression (.../src/query-builder/UpdateQueryBuilder.ts:398:68)
    at UpdateQueryBuilder.getQuery (.../src/query-builder/UpdateQueryBuilder.ts:50:24)
```

Thanks.

**Comment by RamyRais** [comment]
any update on this?

**Comment by RamyRais** [comment]
hey @cstapetrei, i have the same problem as yours, i fixed it by deleting the property before an update. In your case
```
const repo: Repository<User> = getRepository(User);
delete row. password_changed;
await repo.update(row.id, row).then().catch( (e) => { throw e; });
```

**Comment by cstapetrei** [comment]
> hey @cstapetrei, i have the same problem as yours, i fixed it by deleting the property before an update. In your case
> 
> ```
> const repo: Repository<User> = getRepository(User);
> delete row. password_changed;
> await repo.update(row.id, row).then().catch( (e) => { throw e; });
> ```

Hehe...nice hack 😄 

I'll give it a go...buuuut it would be nicer to be fixed ... even with a @NotColumn() decorator or smth like that 😄

**Comment by pauloprado** [comment]
Any updates?
Deleting the field is a nice hack, but it may affect the code once the property will no longer exists in the object.

The idea @cstapetrei of @NotCollumn() decorator seems pretty good

**Comment by alex-phillips** [comment]
One workaround I did for this is have the property on my entity and then create an entity method `getUpdatePayload` which returns only the valid column values in an object. Not ideal, but better than deleting properties before running queries against the entity.

**Comment by vixson** [comment]
> One workaround I did for this is have the property on my entity and then create an entity method `getUpdatePayload` which returns only the valid column values in an object. Not ideal, but better than deleting properties before running queries against the entity.

@alex-phillips Please can you share with us the `getUpdatePayload`, Thanks

**Comment by vixson** [comment]
Ok thanks, @alex-phillips 

@cstapetrei . You can check out #3469 if that works for you?

**Comment by RadBe** [comment]
Why don't developers want to make a proper fix for this issue? When using "find," an EntityPropertyNotFoundError occurs.
