### ISSUE TITLE
Data type "undefined" is not supported in "mysql" database

### ISSUE THREAD

**Issue by gatspy** [typeorm/typeorm#666]
please help
node :8.0
npm: 5.0.4
tsc: 2.4.1
os : mac osx 10.11.5

`entity`
```ts
import {Entity, Column} from "typeorm"
import {PrimaryColumn}from "typeorm"

@Entity()
export class Post{

  @PrimaryColumn("int", {generated:true})
  id:number;

  @Column()
  title:string;

  @Column()
  text: string;

  @Column("int", {nullable:false})
  linkscount: number;
}

```

`app.ts`
```ts
import "reflect-metadata";
import {createConnection, ConnectionOptions} from "typeorm";
import {Post} from "./entity/post";

const options:ConnectionOptions = {
  type:"mysql",
  name:"mysql",
  host:"localhost",
  username:"root",
  password:"*******",
  database:"app_test",
  logging: {
    logQueries:true,
    logFailedQueryError: false,
    logSchemaCreation: true
  },
  autoSchemaSync:true,
  entities:[Post]
}

createConnection(options).then(connection => {
  let post = new Post();
  post.text = "Hello how are you?";
  post.title = "jello";
  post.linkscount = 100;

  let postRepository= connection.getRepository(Post);

  postRepository.save(post)
    .then(post => console.log("Post has been saved", post))
    .catch(error => console.log("Cannot save. Error:", error));
}, error => console.log("Cannot connect: ", error));

```

```error
Cannot connect:  { DataTypeNotSupportedError: Data type "undefined" is not supported in "mysql" database.
    at new DataTypeNotSupportedError (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/error/DataTypeNotSupportedError.js:16:28)
    at /Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:65:27
    at Array.forEach (native)
    at EntityMetadataValidator.validate (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:62:36)
    at /Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:34:74
    at Array.forEach (native)
    at EntityMetadataValidator.validateMany (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:34:25)
    at Connection.buildMetadatas (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/connection/Connection.js:480:33)
    at Connection.<anonymous> (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/connection/Connection.js:133:30)
    at step (/Users/Gatspy/Desktop/survey/tstest/node_modules/typeorm/connection/Connection.js:32:23)
  name: 'DataTypeNotSupportedError',
  message: 'Data type "undefined" is not supported in "mysql" database.' }
```

**Comment by pleerock** [comment]
Thats strange. Can you remove columns one-by-one to determine which column is problematic and brings you such error?

**Comment by MrKartec** [comment]
I just ran into the same error and fixed it by explicitly setting the type to varchar in the decorator of strings columns :

```typescript
@Column({ type: 'varchar' })
title: string;
```


It might be the same here.

**Comment by gatspy** [comment]
@pleerock , in accordance with the `MrKartec` method, has solved the problem. 
`string` must be  mapped to database datatype in decorator. thanks all.

**Comment by pleerock** [comment]
its not required to do:

```ts
@Column({ type: 'varchar' })
title: string;
```

you can omit `varchar` and simply do:

```ts
@Column()
title: string;
```

Result should be same. I think you do something wrong. Are you sure you have enabled:

```json
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
```

these options in tsconfig?

**Comment by MrKartec** [comment]
Well, I tried to reproduce the issue on my home computer and the `@Column()` decorator is working as intended here.  
So maybe I did something wrong and I fixed it later without noticing, or it's coming from my dev environment at work.
  
Also my tsconfig is fine.

**Comment by gatspy** [comment]
@pleerock , I found the cause of the error,use tsc compiler, if you do not use the `-p` option does not directly use tsconfig.json file. 

> [Specify a tsconfig.json for use with `tsc` on the command line](https://github.com/Microsoft/TypeScript/issues/5858)

```shell
tsc -p .
tsc --emitDecoratorMetadata --experimentalDecorators app.ts
```

**Comment by pleerock** [comment]
Good. I guess this can be closed.

**Comment by nicohvi** [comment]
I'm currently getting the same error as reported here, and I can't really figure out how to solve it based on the approach mentioned.

**Entity**
```javascript
@Entity()
class Post {
@Column()
title: string;
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es6"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "sourceMap": true,
    "target": "es2016",
  },
  "include": [
    "**/*.ts"
  ],
}
```
I get the following error:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): DataTypeNotSupportedError: Data type "undefined" in "Post.title" is not supported by "postgres" database.
```

However, when I change to 
```js
@Entity()
class Post {
@Column('varchar')
title: string;
```

I have no problems.

**Comment by nicohvi** [comment]
@pleerock Thank you very much, guess I must've missed that part of the instructions!

**Comment by tinynumbers** [comment]
Thanks @pleerock.  For me, I am using `ts-node` in my test project, and needed to add `-r reflect-metadata` to the command line:

```
ts-node --project . --inspect -r reflect-metadata -r tsconfig-paths/register ./src/server.ts
```

**Comment by nectorosales** [comment]
for project nestjs - delete directory /dist and nest build
