### ISSUE TITLE
Unable to connect to the database on server when yarn start:prod

### ISSUE THREAD

**Issue by liudonghua123** [typeorm/typeorm#6664]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. generate ormconfig.json via `npx typeorm init --database oracle`
2. import the TypeOrmModule into the root AppModule using ormconfig.json configuration
3. test it ok when run `yarn start` or `yarn start:debug`
4. run failed with `yarn start:prod` with the following error messages.

```
D:\code\yx_statistics\server>yarn start
yarn run v1.22.5
$ nest start
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [NestFactory] Starting Nest application...
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [InstanceLoader] TypeOrmModule dependencies initialized +101ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [InstanceLoader] AppModule dependencies initialized +2ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +331ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [InstanceLoader] StatisticsModule dependencies initialized +2ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [RoutesResolver] AppController {}: +17ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [RouterExplorer] Mapped {, GET} route +4ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [RoutesResolver] StatisticsController {/statistics}: +1ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [RouterExplorer] Mapped {/statistics, GET} route +3ms
[Nest] 28160   - 09/03/2020, 3:51:41 PM   [NestApplication] Nest application successfully started +11ms

D:\code\yx_statistics\server>yarn start:prod
yarn run v1.22.5
$ node dist/main
[Nest] 30580   - 09/03/2020, 4:34:35 PM   [NestFactory] Starting Nest application...
[Nest] 30580   - 09/03/2020, 4:34:36 PM   [InstanceLoader] TypeOrmModule dependencies initialized +125ms
[Nest] 30580   - 09/03/2020, 4:34:36 PM   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 30580   - 09/03/2020, 4:34:36 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +300ms
D:\code\ynu\yx_statistics\server\src\entity\HJ.ts:1
import {Entity, PrimaryColumn, PrimaryGeneratedColumn, Column, BaseEntity} from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1167:16)
    at Module._compile (internal/modules/cjs/loader.js:1215:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Function.PlatformTools.load (D:\code\ynu\yx_statistics\server\node_modules\typeorm\platform\PlatformTools.js:114:28)
    at D:\code\ynu\yx_statistics\server\node_modules\typeorm\util\DirectoryExportedClassesLoader.js:39:69
    at Array.map (<anonymous>)
```

The contents of ormconfig.json is like 
```
{
   "type": "oracle",
   "host": "<oracle_host>",
   "username": "<oracle_username>",
   "password": "<oracle_password>",
   "port": 1521,
   "sid": "<oracle_sid>",
   "synchronize": false,
   "logging": false,
   "entities": [
      "src/entity/*.ts",
      "dist/entity/*.js"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
What's the contents of your `package.json`?  This looks like a problem with your tsconfig or however you're running the prod server - not anything to do with typeorm in particular.

**Comment by liudonghua123** [comment]
@imnotjames Here is my `package.json` and `tsconfig.json`.

<details>
<summary>`package.json` and `tsconfig.json`.</summary>

```json
{
   "name": "server",
   "version": "0.0.1",
   "description": "",
   "author": "",
   "private": true,
   "license": "UNLICENSED",
   "scripts": {
      "prebuild": "rimraf dist",
      "build": "nest build",
      "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
      "start": "nest start",
      "start:dev": "nest start --watch",
      "start:debug": "nest start --debug --watch",
      "start:prod": "node dist/main",
      "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
      "test": "jest",
      "test:watch": "jest --watch",
      "test:cov": "jest --coverage",
      "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
      "test:e2e": "jest --config ./test/jest-e2e.json"
   },
   "dependencies": {
      "@nestjs/common": "^7.0.0",
      "@nestjs/core": "^7.0.0",
      "@nestjs/graphql": "^7.6.0",
      "@nestjs/platform-express": "^7.0.0",
      "@nestjs/serve-static": "^2.1.3",
      "@nestjs/typeorm": "^7.1.3",
      "apollo-server-express": "^2.17.0",
      "cache-manager": "^3.4.0",
      "cache-manager-redis": "^0.6.0",
      "graphql": "^15.3.0",
      "graphql-tools": "^6.2.1",
      "oracledb": "^5.0.0",
      "reflect-metadata": "^0.1.10",
      "rimraf": "^3.0.2",
      "rxjs": "^6.5.4",
      "typeorm": "^0.2.26"
   },
   "devDependencies": {
      "@nestjs/cli": "^7.0.0",
      "@nestjs/schematics": "^7.0.0",
      "@nestjs/testing": "^7.0.0",
      "@types/express": "^4.17.3",
      "@types/jest": "26.0.10",
      "@types/node": "^13.9.1",
      "@types/supertest": "^2.0.8",
      "@typescript-eslint/eslint-plugin": "3.9.1",
      "@typescript-eslint/parser": "3.9.1",
      "eslint": "7.7.0",
      "eslint-config-prettier": "^6.10.0",
      "eslint-plugin-import": "^2.20.1",
      "jest": "26.4.2",
      "prettier": "^1.19.1",
      "supertest": "^4.0.2",
      "ts-jest": "26.2.0",
      "ts-loader": "^6.2.1",
      "ts-node": "9.0.0",
      "tsconfig-paths": "^3.9.0",
      "typeorm-model-generator": "^0.4.2-no-engines",
      "typescript": "^3.7.4"
   },
   "jest": {
      "moduleFileExtensions": [
         "js",
         "json",
         "ts"
      ],
      "rootDir": "src",
      "testRegex": ".spec.ts$",
      "transform": {
         "^.+\\.(t|j)s$": "ts-jest"
      },
      "coverageDirectory": "../coverage",
      "testEnvironment": "node"
   }
}

```

```json
{
   "compilerOptions": {
      "lib": [
         "es5",
         "es6"
      ],
      "target": "es5",
      "module": "commonjs",
      "moduleResolution": "node",
      "outDir": "./dist",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "sourceMap": true,
      "resolveJsonModule": true,
      "esModuleInterop": true
   }
}
```
</details>

**Comment by imnotjames** [comment]
Ok - looks like the repo in question is https://github.com/liudonghua123/yx_statistics - I'll clone it and try to replicate!

**Comment by imnotjames** [comment]
Looking at the repository - it seems like this is the problem:

To run `yarn:prod` you have to run `yarn:build` first to create the `dist` directory & compile all the typescript.  Once that's done your entities are raw javascript under `dist/entity`.

However, your `ormconfig` still points at `src/entity/*.ts` - so `yarn:prod` tries to import your typescript files as if they were regular javascript.  This doesn't work.

When you want to run production you'll need to have the `ormconfig.json` point at only the `dist` (production) code.

```json
{
   "type": "oracle",
   "host": "<oracle_host>",
   "username": "<oracle_username>",
   "password": "<oracle_password>",
   "port": 1521,
   "sid": "<oracle_sid>",
   "synchronize": false,
   "logging": false,
   "entities": [
      "dist/entity/**/*.js"
   ],
   "migrations": [
      "dist/migration/**/*.js"
   ],
   "subscribers": [
      "dist/subscriber/**/*.js"
   ]
}
```

**Comment by liudonghua123** [comment]
@imnotjames Thanks, the problem in https://github.com/liudonghua123/yx_statistics have been fixed, I tried to install the npm dependences via `npm` instead of `yarn`, and then I cleaned the `dist` directory. Maybe the problem is the incorrect build files.
