### ISSUE TITLE
I released queryRunner manually but get "QueryRunnerAlreadyReleasedError" 

### ISSUE THREAD

**Issue by EVINK** [typeorm/typeorm#6709]
**Issue type:**

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `^0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi there!

I was calling the queryRunner.release() manually and got "QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore" error.

Here is my code:

```ts

const qr = getConnection().createQueryRunner()
await qr.startTransaction()

const user = new User()  // User inherit from BaseEntity
user.name = 'test'
qr.manager.save(user)
await qr.commitTransaction()
await qr.release()  // If I comment this line, the error will be gone

```

Full error trace:

```error

(node:98701) UnhandledPromiseRejectionWarning: QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at new QueryRunnerAlreadyReleasedError (/Users/evink/workspace/chat-socket/node_modules/typeorm/error/QueryRunnerAlreadyReleasedError.js:9:28)
    at MysqlQueryRunner.query (/Users/evink/workspace/chat-socket/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:148:19)
    at SelectQueryBuilder.<anonymous> (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1552:62)
    at step (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:122:57)
    at /Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:111:16)
    at SelectQueryBuilder.loadRawResults (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1532:24)
    at SelectQueryBuilder.<anonymous> (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1460:55)

(node:98701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:98701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:98701) UnhandledPromiseRejectionWarning: QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at new QueryRunnerAlreadyReleasedError (/Users/evink/workspace/chat-socket/node_modules/typeorm/error/QueryRunnerAlreadyReleasedError.js:9:28)
    at MysqlQueryRunner.query (/Users/evink/workspace/chat-socket/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:148:19)
    at SelectQueryBuilder.<anonymous> (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1552:62)
    at step (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:122:57)
    at /Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/evink/workspace/chat-socket/node_modules/tslib/tslib.js:111:16)
    at SelectQueryBuilder.loadRawResults (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1532:24)
    at SelectQueryBuilder.<anonymous> (/Users/evink/workspace/chat-socket/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1460:55)
(node:98701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```

**Comment by EVINK** [comment]
Sorry, I forget add "await " before "qr.manager.save(user)".
