### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by snolangps** [typeorm/typeorm#6722]
**Issue type:**

[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.3.0-alpha.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm simply trying to run unit tests using `mocha-webpack` and I'm getting some strange warnings when `typeorm` is being imported into my `.ts` file...
So I have a simple TypeScript class, and I'm getting the following warnings when I try to import
`import {LessThanOrEqual} from 'typeorm'`, and my tests are unable to continue.

I also tried following this suggestion, but the warnings are still happening: https://github.com/typeorm/typeorm/blob/master/docs/faq.md#how-to-use-webpack-for-the-backend

**Here are the warnings ( i know it says 14 warnings, but one should suffice):**
` WEBPACK  Compiling...

 WEBPACK  Compiled with 14 warning(s)

Warning in ./stacks/rds/node_modules/.pnpm/registry.npmjs.org/typeorm/0.3.0-alpha.24/node_modules/typeorm/platform/PlatformTools.js

  107:27-40 Critical dependency: the request of a dependency is an expression`

**Here is the rest of the output after the warnings, not sure this helps or not:**
`MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

TypeError: chalk_1.default.Instance is not a constructor
    at eval (webpack-internal:///82:12:13)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:641:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///128:19:15)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:950:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///3:6:23)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:91:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///5:9:23)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:105:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///125:7:25)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:929:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///72:8:27)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:572:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///71:3:20)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:565:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///1:7:27)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:77:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///119:30:19)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:889:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at eval (webpack-internal:///109:39:24)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:827:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at run (webpack-internal:///108:3:20)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///108:10:24)
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:820:1)
    at __webpack_require__ (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:20:30)
    at /some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:63:18
    at Object.<anonymous> (/some/root/directory/.tmp/mocha-webpack/1600196505474/bundle.js:66:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/some/root/directory/node_modules/mocha-webpack/lib/util/registerRequireHook.js:147:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /some/root/directory/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/some/root/directory/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/some/root/directory/node_modules/mocha/lib/mocha.js:536:10)
    at /some/root/directory/node_modules/mocha-webpack/lib/runner/TestRunner.js:196:25
    at Compiler.<anonymous> (/some/root/directory/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7)
    at Compiler.applyPlugins (/some/root/directory/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/some/root/directory/node_modules/webpack/lib/Compiler.js:264:11)
    at Compiler.emitRecords (/some/root/directory/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/some/root/directory/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/some/root/directory/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/some/root/directory/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/some/root/directory/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/some/root/directory/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/some/root/directory/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/some/root/directory/node_modules/webpack/lib/Compiler.js:350:15)
    at /some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:1064:13)
    at /some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:969:16
    at MemoryFileSystem.writeFile (/some/root/directory/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/some/root/directory/node_modules/webpack/lib/Compiler.js:339:28)
    at require.forEach (/some/root/directory/node_modules/webpack/lib/Compiler.js:345:12)
    at /some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:1069:9)
    at eachOf (/some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/some/root/directory/node_modules/webpack/node_modules/async/dist/async.js:3172:5)
    at emitFiles (/some/root/directory/node_modules/webpack/lib/Compiler.js:315:21)
    at Immediate._onImmediate (/some/root/directory/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

Process finished with exit code 1`

**Comment by imnotjames** [comment]
Is this still an issue in 0.2.27?

**Comment by imnotjames** [comment]
Got it, you tried against 0.3.0

**Comment by MichaelSp** [comment]
still present in `    "typeorm": "^0.3.0-rc.21"`
BTW: This is not related to `mssql`

**Comment by khawajaumarfarooq** [comment]
> Is this still an issue in 0.2.27?

I am getting this error trying to use TypeORM v0.2.32 wth Next.js v10.2.0.

I have searched around but haven't really found any clues.

Regarding my solution structure, I have the main module (based on Next.js) `foo-bar` which is importing a data module (based on TypeORM) `foo-bar-typeorm-data`.

The `ormconfig.json` exists in the `foo-bar-typeorm-data` module.

```
warn  - /Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/connection/ConnectionOptionsReader.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/connection/ConnectionOptionsReader.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/app-root-path/lib/app-root-path.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/util/DirectoryExportedClassesLoader.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/util/DirectoryExportedClassesLoader.js
Critical dependency: the request of a dependency is an expression

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve '@sap/hana-client' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve 'hdb-pool' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve 'pg' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve 'pg-native' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve 'pg-query-stream' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'

/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform/PlatformTools.js
Module not found: Can't resolve 'typeorm-aurora-data-api-driver' in '/Sources/Azure/FooBar/Libraries/foo-bar-typeorm-data/node_modules/typeorm/platform'
```

**Comment by dandrei** [comment]
Same issue with:

| Library | Version |
| :--- | :--- |
| typeorm | 0.3.0-rc.21 |
| next | 11.0.1 |

**Comment by mikemcguire** [comment]
I'm having a similar issue as well building with webpack. My app is a backend api so has nothing to do with nextjs or building for the browser as mentioned previously. 

WARNING in ./node_modules/typeorm/util/DirectoryExportedClassesLoader.js 60:38-94
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (~/node_modules/webpack/lib/dependencies/ContextDependency.js:82:18)
    at Compilation.reportDependencyErrorsAndWarnings (~/node_modules/webpack/lib/Compilation.js:2584:24)
    at ~/node_modules/webpack/lib/Compilation.js:2202:10
    at eval (eval at create (~/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at ~/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:376:11
    at ~/node_modules/neo-async/async.js:2830:7
    at Object.each (~/node_modules/neo-async/async.js:2850:39)
    at ~/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:355:18
    at ~/node_modules/neo-async/async.js:2830:7
    at Object.each (~/node_modules/neo-async/async.js:2850:39)
 @ ./node_modules/typeorm/connection/ConnectionMetadataBuilder.js 5:39-88
 @ ./node_modules/typeorm/connection/Connection.js 16:34-72
 @ ./node_modules/typeorm/index.js 115:19-53
 @ ./src/base/database.ts 4:18-36

**Comment by imnotjames** [comment]
Isn't that a warning, though?

This is because webpack cannot during compile-time figure out what we're importing because it's an expression that is only known during runtime.

That's because we're using `require` to load our configuration files through that class.

**Comment by imnotjames** [comment]
As far as the problems described in the rest of the issue:

When building for the browser you can't really use an `ormconfig` because it won't get bundled up & often won't load correctly.  There are ways to make it work but in general... You need to manage the configuration yourself.

In <0.2.35 there was also a bug which caused us to not load the correct TypeORM browser modules for some drivers, and has been since fixed.

As such, I'll be closing this issue out as I believe it's been corrected.

**Comment by ayrtoneverton** [comment]
As this might be useful to someone, I'll share here how I did it to ignore these specific alerts and thus not disturb the console.

I used `ignoreWarnings` from `Webpack`: https://webpack.js.org/configuration/other-options/#ignorewarnings

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  // ...
  webpack(config) {
    config.ignoreWarnings = [{
      module: /typeorm/,
      message: /Module not found|dependency is an expression/,
    }];
    return config;
  }
};

export default nextConfig;
```
NOTE: In the example above I am using `next.config.mjs` from `NextJS`, but the same configuration can be used directly in `Webpack`.
