### ISSUE TITLE
TYPEORM_URL enviroment variable not working

### ISSUE THREAD

**Issue by mqwerty** [typeorm/typeorm#6726]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Use .env file for configuration.

This works:
```
TYPEORM_CONNECTION=postgres
TYPEORM_HOST=localhost
TYPEORM_USERNAME=postgres
TYPEORM_PASSWORD=postgres
TYPEORM_DATABASE=auth
```

This not works:
```
TYPEORM_CONNECTION=postgres
TYPEORM_URL=postgres://postgres:postgres@localhost/auth
```

Error:
```
error: password authentication failed for user "dima"
    at Parser.parseErrorMessage (D:\git\github.com\mqwerty\auth\node_modules\pg-protocol\src\parser.ts:357:11)
    at Parser.handlePacket (D:\git\github.com\mqwerty\auth\node_modules\pg-protocol\src\parser.ts:186:21)
    at Parser.parse (D:\git\github.com\mqwerty\auth\node_modules\pg-protocol\src\parser.ts:101:30)
    at Socket.<anonymous> (D:\git\github.com\mqwerty\auth\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 100,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '333',
  routine: 'auth_failed'
}
```

Script:
```ts
import 'dotenv/config'
import 'reflect-metadata'
import { createConnection } from 'typeorm'

createConnection()
  .then(() => {
    console.log('success')
  })
  .catch(e => {
    console.error(e)
  })
```

**Comment by imnotjames** [comment]
Is this bug still relevant in 0.2.27?  I believe it's been fixed.

**Comment by mqwerty** [comment]
Checked it, there is no bug in version 0.2.27

**Comment by judehunter** [comment]
@imnotjames broken again in `0.3.0-rc.21` (or earlier). Using `TYPEORM_URL` does not work, but using `TYPEORM_USERNAME`, `TYPEORM_PASSWORD`, etc. does seem to work.

Can we reopen this?

**Comment by mistahselectah** [comment]
+1

**Comment by oswaldojr** [comment]
+1

**Comment by ryanoboril** [comment]
+1 is this ever going to be fixed?
