### ISSUE TITLE
Using "in" operator with uuid types causes "invalid input syntax" error

### ISSUE THREAD

**Issue by Toub** [typeorm/typeorm#6727]
**Issue type:**

- [x] bug report

**Database system/driver:**

- [x] `postgres` v11

**TypeORM version:**

- [x] `latest` 0.2.26

With postgres, "in" operator is valid on UUID types:

```sql
SELECT x.* FROM my_table x WHERE x."_id" IN ('77dec6ee-8d39-4b73-825a-6190628d2953','7900b8c6-c239-45e1-9ca8-2d1a244eb881')
```

However, the following code throws an error:

```ts
repository.find({
    where: {
      _id: In(['77dec6ee-8d39-4b73-825a-6190628d2953', '7900b8c6-c239-45e1-9ca8-2d1a244eb881']),
    }
});
```

```log
QueryFailedError invalid input syntax for type uuid: "{"_type":"in","_value":["77dec6ee-8d39-4b73-825a-6190628d2953", "7900b8c6-c239-45e1-9ca8-2d1a244eb881"],"_useParameter":true,"_multipleParameters":true}"
```

**Comment by imnotjames** [comment]
Unfortunately, the code you pasted is not valid javascript - can you check your copy / paste again?  I think there must've been a problem when you were creating the issue.

**Comment by Toub** [comment]
My bad, I just fix it, sorry.

**Comment by Toub** [comment]
Hi @imnotjames, have you been able to reproduce it?

**Comment by imnotjames** [comment]
Unfortunately, I've not yet.  It does seem like we aren't detecting the `In` clause as a find operator.  Have you done anything exotic in your codebase that could cause that?

**Comment by Toub** [comment]
> It does seem like we aren't detecting the In clause as a find operator. Have you done anything exotic in your codebase that could cause that?

I don't think so. Here is my id declaration:

```ts
  @PrimaryGeneratedColumn('uuid')
  _id?: string;
```

You are right, here is the full error:

> You could also try debugging by seeing where the error is being emitted and if there's a code path in particular that could be causing it.

```ini
  message:
   'invalid input syntax for type uuid: "{"_type":"in","_value":["d7ddfa02-4781-4107-bd64-b41f4bcbc460","23cedd86-22ad-43cd-a7c0-d44522f5aa12","0fdee079-27c0-419d-b649-a408a94de1cf"],"_useParameter":true,"_multipleParameters":true}"',
  name: 'QueryFailedError',
  length: 285,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'uuid.c',
  line: '137',
  routine: 'string_to_uuid',
  query:
   'SELECT "x"."_id" FROM "my_table" "x" WHERE "x"."_id" = $1',
  parameters:
   [ FindOperator {
       _type: 'in',
       _value: [Array],
       _useParameter: true,
       _multipleParameters: true } ] }

```

Look at the generated query (I removed some select attributes and changed the table name here to simplify): `WHERE "x"."_id" = $1'`

The In operator has been skipped!

So the error is thrown by pg client:

```
    at new QueryFailedError (/app/sources/libs/app-node-typeorm/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/app/sources/libs/app-node-typeorm/src/driver/postgres/PostgresQueryRunner.ts:188:30)
    at Query.handleError (/app/sources/server-api-ts/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/app/sources/server-api-ts/node_modules/pg/lib/client.js:2
```

Could you please tell me where (file, function...) is the query generated, so I can try to debug what is wrong?

**Comment by imnotjames** [comment]
Looks like the pg-native module is getting passed the find operator 

Here's findOne for a start.

https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L753

**Comment by Toub** [comment]
Yes, looks like the FindOperator is processed as a string?

I tried to debug, but the SQL generation code is too complex for me.

Where exactly in `QueryBuilder` or `SelectQueryBuilder` should I look?

ps: juste upgraded to last version (`0.2.28`)

**Comment by imnotjames** [comment]
What's your entity definition?  Are you using a transformer?

**Comment by Toub** [comment]
I am not doing anything exotic: 

```ts
import { CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn, VersionColumn } from 'typeorm';

@Entity({ name: 'my_table' })
export class MyTable extends BaseTypeormTable {

    @PrimaryGeneratedColumn('uuid')
    _id?: string;
  
    @CreateDateColumn({ type: 'timestamptz' })
    _createdAt?: Date;
  
    @UpdateDateColumn({ type: 'timestamptz' })
    _updatedAt?: Date;
  
    @VersionColumn()
    _version?: number;
```

**Comment by ngraef** [comment]
This is happening for `Raw` as well.

```ts
manager.transaction(async (entityManager) => {
  const requests = await entityManager.find(Request, {
    select: ['id'],
    where: {
      tenantId: tenant,
      state: 'pending',
      createdAt: Raw((alias) => `EXTRACT(MINUTES FROM (NOW() - ${alias})) > :minutes`, {
        minutes,
      }),
    },
  });

  //...
});
```

Logs:
```
query failed: SELECT id FROM "request" "Request" WHERE "Request"."tenantId" = $1 AND "Request"."state" = $2 AND "Request"."createdAt" = $3 -- PARAMETERS: ["tenant1","pending",{"_type":"raw","_value":[],"_useParameter":true,"_multipleParameters":true,"_objectLiteralParameters":{"minutes":1}}]
error: error: invalid input syntax for type timestamp: "{"_type":"raw","_value":[],"_useParameter":true,"_multipleParameters":true,"_objectLiteralParameters":{"minutes":1}}"
```

I've tried using QueryBuilder instead, with the same result.
```ts
const consentRequests = await entityManager
  .createQueryBuilder()
  .select('id')
  .from(Request, 'Request')
  .where({
    tenantId: tenant,
    state: 'pending',
    createdAt: Raw((alias) => `EXTRACT(MINUTES FROM (NOW() - ${alias})) > :minutes`, {
      minutes,
    }),
  })
  .getMany();
```

#7247 suggests that using `entityManager.getRespository(Request).find` or `entityManager.getRespository(Request).createQueryBuilder` might work, but I got the same result with both.

**Comment by miedzikd** [comment]
Similar effect for inside query builder...
```js
qb.andWhere("v.customer IN (:customers)", { customers: ["548b47a3-61b9-48f4-b1f2-eb83011a20d5"]});
```
throwing this error:
```
UnhandledPromiseRejectionWarning: QueryFailedError: invalid input syntax for type uuid: "{"548b47a3-61b9-48f4-b1f2-eb83011a20d5"}"
app_1      |     at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
app_1      |     at Query.callback (/app/src/driver/postgres/PostgresQueryRunner.ts:178:30)
app_1      |     at Query.handleError (/app/node_modules/pg/lib/query.js:128:19)
app_1      |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:335:17)
app_1      |     at Connection.emit (events.js:314:20)
app_1      |     at Connection.EventEmitter.emit (domain.js:483:12)
app_1      |     at /app/node_modules/pg/lib/connection.js:115:12
app_1      |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:102:9)
app_1      |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
app_1      |     at Socket.emit (events.js:314:20)
```

Interestingly, the search will work if I add the parameter value inside the query, but **only if I use single quotes** like here:
```js
qb.andWhere("v.customer IN ('548b47a3-61b9-48f4-b1f2-eb83011a20d5')");
```

**Comment by francescoferraioli** [comment]
I have been able to solve this by following the instructions in [this issue](https://github.com/typeorm/typeorm/issues/1239).

Essentially just change your query to
```
qb.andWhere("v.customer IN (:...customers)", { customers: ["548b47a3-61b9-48f4-b1f2-eb83011a20d5"]});
```

**Comment by imnotjames** [comment]
> Similar effect for inside query builder...
> ```js
> qb.andWhere("v.customer IN (:customers)", { customers: ["548b47a3-61b9-48f4-b1f2-eb83011a20d5"]});
> ```
> throwing this error:
> ```
> UnhandledPromiseRejectionWarning: QueryFailedError: invalid input syntax for type uuid: "{"548b47a3-61b9-48f4-b1f2-eb83011a20d5"}"
> app_1      |     at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
> app_1      |     at Query.callback (/app/src/driver/postgres/PostgresQueryRunner.ts:178:30)
> app_1      |     at Query.handleError (/app/node_modules/pg/lib/query.js:128:19)
> app_1      |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:335:17)
> app_1      |     at Connection.emit (events.js:314:20)
> app_1      |     at Connection.EventEmitter.emit (domain.js:483:12)
> app_1      |     at /app/node_modules/pg/lib/connection.js:115:12
> app_1      |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:102:9)
> app_1      |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
> app_1      |     at Socket.emit (events.js:314:20)
> ```
> 
> Interestingly, the search will work if I add the parameter value inside the query, but **only if I use single quotes** like here:
> ```js
> qb.andWhere("v.customer IN ('548b47a3-61b9-48f4-b1f2-eb83011a20d5')");
> ```
> 

You need to use `:...customers`, this is unrelated.

**Comment by imnotjames** [comment]
I can't seem to replicate this.  Can you create a reproducible example?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by gpmarchi** [comment]
I believe the answer to this question is in this other issue: https://github.com/typeorm/typeorm/issues/1985

All you have to do is use the new '...' operator to spread the array inside the In clause of your query, like so:

```typescript
export const queryBatchFunction = <T extends { id: string }>(repository: Repository<T>) => async (
  keys: string[],
): Promise<(T | null)[]> => {
  const docs = await repository
    .createQueryBuilder("TableName")
    .where(`TableName.id IN (:...keys)`, { keys })
    .getMany();

  return keys.map(k => docs.find(d => d.id === k) || null);
};
```

Note the `:...key` thing, but I don't see this's being mentioned anywhere in the changelog... Am I missing anything?

_Originally posted by @lednhatkhanh in https://github.com/typeorm/typeorm/issues/1985#issuecomment-383270029_

**Comment by lucafaggianelli** [comment]
I'm facing a similar (probably the same) issue, take a look here https://github.com/typeorm/typeorm/issues/8579#issuecomment-1028219950

**Comment by Ombrelin** [comment]
Hello, I happen to face this problem with the following entity : 

```typescript
export class AppEvent {
  @PrimaryGeneratedColumn("uuid")
  public id!: string;

  @Column("text")
  public name!: string;

  @Column("timestamp")
  public date!: Date;

  @Column("text")
  public location!: string;

  @ManyToMany(() => User, {
    cascade: true
  })
  @JoinTable()
  @Field(_ => [User])
  hosts!: User[];

  @ManyToMany(() => User, {
    cascade: true
  })
  @JoinTable()
  guests!: User[];
}
```

and this query : 


```typescript
 const query = `
        SELECT *
        FROM "event"
        WHERE "event"."id" IN (
            SELECT "event_guests_user"."eventId" FROM "event_guests_user"
            WHERE "event_guests_user"."userId" = '?'
        )
           OR "event"."id" IN (
            SELECT "event_hosts_user"."eventId" FROM "event_hosts_user"
            WHERE "event_hosts_user"."userId" = '?'
        )
    `;
     const result = await super.query(query, [userId,userId])
```

**Comment by Ginden** [comment]
@Ombrelin Your SQL code use `'?'` - this is string literal for `?`. String `?` isn't UUID, so database throws an error.

**Comment by Ombrelin** [comment]
@Ginden thank you for your answer, I don't undestand how I should bind uuid parameters then, since postgres require quote in the query : if I remove the quotes, the query is not syntaxically valid

**Comment by Ginden** [comment]
@Ombrelin https://node-postgres.com/features/queries#parameterized-query

**Comment by kzamulin** [comment]
Faced the same error as in the description of this issue:

`
"driverError":{"length":140,"name":"error","severity":"ERROR","code":"22P02","file":"uuid.c","line":"137","routine":"string_to_uuid"},"length":140,"severity":"ERROR","code":"22P02","file":"uuid.c","line":"137","routine":"string_to_uuid"}
`

Code that caused error:

```javascript
await queryRunner.manager.find(
        MyJoinTableEntity,
        {
          where: {
            myEntityId: myEntity.id,
            anotherEntityId: In(anotherEntityIds)
          }
        }
      );
```

And that was my mistake, `anotherEntityIds` looked like:

```javascript
[{ 'id': '<uid>'}, {'id': '<anotherUid>'}]
```

I mean, it was a list of objects, instead of beeing just array of ids. The problem was in incorrect map function that was converting list of `AnotherEntity` objects into just array of it's ids:

```javascript
  const anotherEntityIds = anotherEntities.map((anotherEntity) => {
    return { id: anotherEntity.id };
  }); 
```

No issue after I fixed that part to :

```javascript
const anotherEntityIds = anotherEntities.map((anotherEntity) => anotherEntity.id); // ['<uid>', <anotherUid>']
```

**Comment by aphofstede** [comment]
`isNull()` has the same issue
