### ISSUE TITLE
RN - Unable to resolve module `fs` from `node_modules/dotenv/lib/main.js` in 0.2.26

### ISSUE THREAD

**Issue by neXorianus** [typeorm/typeorm#6758]
**Issue type:**

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.26` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

in a `react-native` app installing and using typeorm at version `0.2.26` results in a crash with metro:

```
[Tue Sep 22 2020 10:47:30.971]  BUNDLE  ./index.js 

error: Error: Unable to resolve module 'fs' from 'node_modules/dotenv/lib/main.js': fs could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/path/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/path/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/path/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/path/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /path/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/path/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /path/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/path/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

```
$ yarn why dotenv
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "dotenv"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "dotenv@6.2.0"
info Reasons this module exists
   - "typeorm" depends on it
   - Hoisted from "typeorm#dotenv"
info Disk size without dependencies: "68KB"
info Disk size with unique dependencies: "68KB"
info Disk size with transitive dependencies: "68KB"
info Number of shared dependencies: 0
✨  Done in 1.34s.
```

(in `typeorm@0.2.25` i get the error `Unable to resolve module `url` from `node_modules/typeorm/browser/util/OrmUtils.js`` wich i wont get in 0.2.26)

**I temporary switched back to 0.2.24 what resolves the issues.**

My guess is, that a new version of dotenv is requireing the fs moudle, what makes it uncompatible with react-native - what makes typeorm incompatible with RN itself.

**Comment by imnotjames** [comment]
This is related to #6739

**Comment by imnotjames** [comment]
@neXorianus has this been fixed in 0.2.27?

**Comment by imnotjames** [comment]
As far as we can tell - this should be fixed as of the latest release.

**Comment by neXorianus** [comment]
sry, didnt work on the app since.
will test tomorrow.
