### ISSUE TITLE
sqlite: insert cannot update entity because entity id is not set in the entity

### ISSUE THREAD

**Issue by sogehige** [typeorm/typeorm#6894]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I cannot insert new row into database

```
query: INSERT INTO "changelog"("id", "timestamp", "threadId", "namespace") VALUES (NULL, ?, ?, ?) -- PARAMETERS: [1602497652837,"e8dee20f-7bf5-4e57-bf20-6b405dc8698e","core.oauth.botId"]
2020-10-12T12:14:12.845 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> Error: Cannot update entity because entity id is not set in the entity.
      at /home/xxx/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:129:39
      at Array.map (<anonymous>)
      at ReturningResultsEntityUpdator.<anonymous> (/home/xxx/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:122:46)
      at step (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
      at Object.next (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
      at /home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
      at ReturningResultsEntityUpdator.insert (/home/xxx/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:87:24)
      at InsertQueryBuilder.<anonymous> (/home/xxx/node_modules/typeorm/query-builder/InsertQueryBuilder.js:102:76)
      at step (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
      at Object.next (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
      at fulfilled (/home/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
} reason: Error: Cannot update entity because entity id is not set in the entity.
```

Definition:
```
import { EntitySchema } from 'typeorm';
import { ColumnNumericTransformer } from './_transformer';

export interface ChangelogInterface {
  id: number; timestamp: number; threadId: string; namespace: string;
}

export const Changelog = new EntitySchema<Readonly<Required<ChangelogInterface>>>({
  name: 'changelog',
  columns: {
    id: { type: Number, primary: true, generated: 'increment' },
    timestamp: { type: 'bigint', transformer: new ColumnNumericTransformer(), default: 0 },
    threadId: { type: String },
    namespace: { type: String },
  },
});
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by sogehige** [comment]
Nevermind, I knew when I post this I couldn't reproduce anymore.
