### ISSUE TITLE
Please report a github issue if you face this error

### ISSUE THREAD

**Issue by baznzab** [typeorm/typeorm#6908]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.28`

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export class Customer {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}
```

```ts
@Entity()
export class Product {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  code: string;

  @Column()
  name: string;

  @ManyToOne(() => Manufacturer, (manufacturer: Manufacturer) => manufacturer.products)
  manufacturer: Manufacturer;
}
```

```ts
@Entity()
export class Manufacturer {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => Product, (product: Product) => product.manufacturer)
  products: Product[];
}
```

```ts
@Entity()
export class Order {
  @ManyToOne(() => Customer, { primary: true })
  @JoinColumn()
  customer: Customer;

  @ManyToOne(() => Product, { primary: true })
  @JoinColumn()
  product: Product;

  @Column()
  details: string;
}
```

```ts
const orderRepository = getRepository(Order);
const order = await orderRepository.findOne({ customer: { id: 1 }, product: { id: 1 } });
await orderRepository.remove(order);
```

```
[Nest] 43749   - 14/10/2020, 23:35:27   [ExceptionsHandler] Internal error. Subject Order must have an identifier to perform operation. Please report a github issue if you face this error. +1839ms
SubjectWithoutIdentifierError: Internal error. Subject Order must have an identifier to perform operation. Please report a github issue if you face this error.
    at new SubjectWithoutIdentifierError (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/error/SubjectWithoutIdentifierError.js:12:28)
    at /Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/persistence/SubjectExecutor.js:517:39
    at Array.map (<anonymous>)
    at SubjectExecutor.<anonymous> (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/persistence/SubjectExecutor.js:515:47)
    at step (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
    at SubjectExecutor.executeRemoveOperations (/Users/arthur/Projects/nestjs-rapid/node_modules/typeorm/persistence/SubjectExecutor.js:499:24)
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
Can you create a repository that replicates this issue?

You might want to set the inverse relation in the `@ManyToOne` decorators

**Comment by khachatrian1995** [comment]
https://github.com/khachatrian1995/typeorm-issue-6908
Also added inverse relations

**Comment by ArtemKolychev** [comment]
I have to same problem.
`@Entity({name: "users"})
export class User extends BaseEntity{

    @PrimaryGeneratedColumn("uuid")
    public id!: string;

    @OneToMany(() => Sessions, (sessions) => sessions.user)
    public tokens!: Sessions[] | null;

}`
`@Entity({name: "user_sessions"})
export class Sessions extends BaseEntity {

	@PrimaryGeneratedColumn("uuid")
	public id: string | undefined;

	@ManyToOne(() => User, user => user.tokens, {nullable: false})
	public user!: User;
}`
`	public static async deleteSession(session: Sessions, conName: string): Promise<Sessions | undefined> {
		return SessionsRepository.getRepository(conName).remove(session);
	}`
`    SubjectWithoutIdentifierError: Internal error. Subject Sessions must have an identifier to perform operation. Please report a github issue if you face this error.

      at new SubjectWithoutIdentifierError (src/error/SubjectWithoutIdentifierError.ts:12:9)
      at src/persistence/SubjectExecutor.ts:470:27
          at Array.map (<anonymous>)
      at SubjectExecutor.<anonymous> (src/persistence/SubjectExecutor.ts:468:41)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.next (node_modules/tslib/tslib.js:122:57)
      at node_modules/tslib/tslib.js:115:75
      at Object.__awaiter (node_modules/tslib/tslib.js:111:16)
      at SubjectExecutor.Object.<anonymous>.SubjectExecutor.executeRemoveOperations (node_modules/typeorm/persistence/SubjectExecutor.js:499:24)
`

**Comment by pleerock** [comment]
I'm strongly recommend to change the code to:

```ts
@Entity()
export class Order {
  @ManyToOne(() => Customer, { primary: true })
  @JoinColumn()
  customer: Customer;

  @Column()
  customerId: number;

  @ManyToOne(() => Product, { primary: true })
  @JoinColumn()
  product: Product;

  @Column({ nullable: true }) // or false depend on your needs
  productId: number;

  @Column()
  details: string;
}
```

```ts
const order = await orderRepository.findOne({ customerId: 1, productId: 1 });
```

Having primary columns as relations without have an id brings too many problems, and the syntax I suggested is already required in the `next` version of TypeORM. Consider applying changes right now to prevent this kind of issues.

**Comment by filipw01** [comment]
I think, that I've found a temporary workaround. Try to add queried entities to relations like below
```js
const order = await orderRepository.findOne(
    { customer: { id: 1 }, product: { id: 1 } },
    { relations: ["customer", "product"] }
);
```
This works for me on a joining table (Many to Many relation) using PostgreSQL
