### ISSUE TITLE
Support for --transpile-only

### ISSUE THREAD

**Issue by jsbroks** [typeorm/typeorm#6923]
**Issue type:**

[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Run any PostgreSQL typeorm project that uses enums with ts-node --transpile-only and you'll get this error:
```
DataTypeNotSupportedError: Data type "Object" in "{enum name here}" is not supported by "postgres" database.
    at new DataTypeNotSupportedError (/DataTypeNotSupportedError.ts:9:9)
    at /src/metadata-builder/EntityMetadataValidator.ts:84:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/src/metadata-builder/EntityMetadataValidator.ts:81:36)
    at /src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/src/connection/Connection.ts:527:33)
    at Connection.<anonymous> (/src/connection/Connection.ts:193:18)
    at step (/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
```

**Comment by imnotjames** [comment]
Can you create a Reproducible example as a repo

**Comment by moulinraphael** [comment]
@jsbroks How did you solve this issue ? I'm trying to use `--transpile-only` because Typeorm CLI is very slow during migrations and I want to limit memory usage and it seems this option could improve that

**Comment by jkrall** [comment]
@jsbroks I'm also interested in whether you resolved this issue — having the exact same problem when I attempt to use `--transpile-only`
