### ISSUE TITLE
better-sqlite3 syntax error

### ISSUE THREAD

**Issue by Floffah** [typeorm/typeorm#6965]
**Issue type:**

- [x] bug report
- [ ] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [ ] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [x] `better-sqlite3`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

create the following models:

```ts
export enum Permission {
    GUEST,
    ADMIN,
    LISTUERS,
    LISTEXTENDEDUSERS,
}

@Entity()
export class UserModel {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    username: string

    @Column()
    password: string

    @Column()
    email: string

    @Column({
        enum: Permission,
        array: true,
        default: [Permission.GUEST, Permission.LISTEXTENDEDUSERS]
    })
    permissions: Permission

    @Column({length: 512, nullable: true})
    access: string
}
```

connect to a better-sqlite3 database
with the options

```ts
createConnection({
            synchronize: true,
            entities: [UserModel],
            logger: "advanced-console",
            logging: "all",
            type: "better-sqlite3",
            database: "./path/to/database.sqlite"
});
```

create a record.

get the error

```
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user_model')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('user_model')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
creating a new table: user_model
query: CREATE TABLE "user_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "password" varchar NOT NULL, "email" varchar NOT NULL, "permissions" varchar CHECK( permissions
 IN ('0','1','2','3') ) NOT NULL DEFAULT (0,3), "access" varchar(512))
query: ROLLBACK

D:\projects\unfinished\mangium\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:44
                stmt = databaseConnection.prepare(query);
                                          ^
SqliteError: near ",": syntax error
    at BetterSqlite3QueryRunner.<anonymous> (D:\projects\unfinished\mangium\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:44:43)
    at step (D:\projects\unfinished\mangium\node_modules\tslib\tslib.js:141:27)
    at Object.next (D:\projects\unfinished\mangium\node_modules\tslib\tslib.js:122:57)
    at fulfilled (D:\projects\unfinished\mangium\node_modules\tslib\tslib.js:112:62)
```

**Comment by imnotjames** [comment]
I think that your definition for the permission column is incorrect - and not exactly an issue with TypeORM.  Sure, it's allowing you to do something nonsensical but I think that's not exactly a bug in TypeORM.

For general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
