### ISSUE TITLE
[BUG]: Junction table entity registration in connection breaks inserts.

### ISSUE THREAD

**Issue by luisgarciaalanis** [typeorm/typeorm#7004]
## Issue Description
Registering a custom junction table on the connection makes the inserts on the relations fail by trying to insert only DEFAULT values into the Junction table. This prevents us from having Junction tables with extra fields.

### Expected Behavior

1. Junction table entity should be register-able to be able to query its contents for extra fields.
2. Inserts should work if extra fields are nullable or have default values assigned when the custom junction table is registered.
### Actual Behavior

Registration does not fail but it breaks inserts of relational data.

```
        const org1 = new Organization();
        org1.name = 'Starwars inc';
        org1.users = [user1, user2]; <---- this is not possible if the junction entity is registered in the connection.
        await org1.save() <-- it throws here.
```
Here is the exception.
```
query: INSERT INTO `user_organization`(`user_id`, `organization_id`, `selected`) VALUES (DEFAULT, DEFAULT, DEFAULT), (DEFAULT, DEFAULT, DEFAULT)
query failed: INSERT INTO `user_organization`(`user_id`, `organization_id`, `selected`) VALUES (DEFAULT, DEFAULT, DEFAULT), (DEFAULT, DEFAULT, DEFAULT)
error: Error: Field 'user_id' doesn't have a default value
    at Packet.asError (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/commands/command.js:28:26)
    at PoolConnection.handlePacket (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/foo/repos/bugRepro/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'user_id' doesn't have a default value"
}
```
Notice on the error how the values are DEFAULT, DEFAULT, DEFAULT.

If I then turn sync off and remove the entity, the code works as expected and it uses the already entity previously recistered created table.

### Steps to Reproduce

I have created a repro app see below.
To make it fail:
1. configure the db connection on the code below.
2. npm run start
After failing you can:
1. Remove UserOrganization from the connection entities array.
2. turn off synchronize.
3. npm run start
It should work as it should have with synchronize turned on and with the entity on the array.

package.json:
```json
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "main.ts",
  "scripts": {
    "start": "ts-node main.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^14.14.6",
    "mysql2": "^2.2.5",
    "ts-node": "^9.0.0",
    "typeorm": "^0.2.29",
    "typescript": "^4.0.5"
  }
}
```
Repro code:

```typescript
import {
    Entity, PrimaryGeneratedColumn, Column, BaseEntity, JoinTable, ManyToMany, createConnection, PrimaryColumn,
} from 'typeorm';

@Entity('user')
export class User extends BaseEntity {
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    @Column()
    name!: string;

    @ManyToMany(() => Organization, (organization) => organization.id)
    @JoinTable({
        name: 'user_organization',
        joinColumn: {
            name: 'user_id',
            referencedColumnName: 'id',
        },
        inverseJoinColumn: {
            name: 'organization_id',
            referencedColumnName: 'id',
        },
    })
    organizations!: Organization[];
}


@Entity('organization')
export class Organization extends BaseEntity {
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    @Column()
    name!: string;

    @ManyToMany(() => User, (user) => user.id, { cascade: true })
    @JoinTable({
        name: 'user_organization',
        joinColumn: {
            name: 'organization_id',
            referencedColumnName: 'id',
        },
        inverseJoinColumn: {
            name: 'user_id',
            referencedColumnName: 'id',
        },
    })
    users!: User[];
}

@Entity('user_organization')
export class UserOrganization extends BaseEntity {
    @PrimaryColumn({name: 'user_id'})
    userID!: string;

    @PrimaryColumn({ name: 'organization_id' })
    organizationID!: string;

    @Column({default: false})
    selected!: boolean;
}


const main = async() => {
    try {
        const connection = await createConnection({
            host: 'localhost',
            type: 'mysql',
            port: 3306,
            username: 'dbUsername',
            password: 'dbPassword',
            database: 'dbSchemaName',
            entities: [
                User,
                Organization,
                UserOrganization,
            ],
            synchronize: true,
            logging: true,
        });

        const user1 = new User();
        user1.name = 'Luke';
        await user1.save();
        const user2 = new User();
        user2.name = 'Leia';
        await user2.save();

        const org1 = new Organization();
        org1.name = 'Starwars inc';
        org1.users = [user1, user2];
        await org1.save()

        const org2 = new Organization();
        org2.name = 'Starwars inc';
        await org2.save()

        await connection.close();
    } catch (err) {
        console.log(err);
        console.log('Unable to get database connection');
        return false;
    }
}

main().catch()
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.19.0 | 
| Typescript version  | v4.0.5  | 
| TypeORM version     | v0.2.29  | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by YES-Lee** [comment]
i have the same issue. have you solved it?

**Comment by luisgarciaalanis** [comment]
> i have the same issue. have you solved it?

no
