### ISSUE TITLE
Postgres: duplicate enum names lead to a unhelpful error message during migration generation

### ISSUE THREAD

**Issue by meldron** [typeorm/typeorm#7084]
## Issue Description

If you accidentally create two enums with the same name, the error thrown during `typeorm migration:generate -n`  return the following unhelpful error:
 ```
Error during migration generation:
TypeError: Cannot read property 'udt_schema' of undefined
    at PostgresQueryRunner.<anonymous> (/home/user/project/src/driver/postgres/PostgresQueryRunner.ts:2023:38)
    at step (/home/user/project/node_modules/tslib/tslib.js:139:27)
    at Object.next (/home/user/project/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/home/user/project/node_modules/tslib/tslib.js:110:62)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

### Expected Behavior
 ```
Error during migration generation:
Duplicate enum name: nameOfEnum
```

### Actual Behavior
Unhelpful error
 ```
Error during migration generation:
TypeError: Cannot read property 'udt_schema' of undefined
    at PostgresQueryRunner.<anonymous> (/home/user/project/src/driver/postgres/PostgresQueryRunner.ts:2023:38)
    at step (/home/user/project/node_modules/tslib/tslib.js:139:27)
    at Object.next (/home/user/project/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/home/user/project/node_modules/tslib/tslib.js:110:62)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
### Steps to Reproduce

1. Create enum1
2. Create enum2.
3. Create enitity
4. Add Column enum1 with name `Enum1`
5. Add Column enum2 with name `Enum2`
6. Run `typeorm migration:generate -n`

```typescript
enum Enum1 {
    test = "test"
}

enum Enum2 {
    test = "test"
}

@Entity("test")
export class Test {
    @PrimaryGeneratedColumn({
        name: "id",
        type: "int",
        unsigned: true,
    })
    public id!: number;

    @Column("enum", {
        enum: Enum1,
        name: "enum1",
        nullable: false,
    })
    public provider!: Enum1;

    @Column("enum", {
        enum: Enum2,
        name: "enum1",
        nullable: false,
    })
    public method!: Enum2;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Linux        |
| Node.js version     | v12.14.1 | 
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.25 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by nebkat** [comment]
Really this should be detected as a duplicate column? The postgres error is essentially just a side effect.

**Comment by meldron** [comment]
> Really this should be detected as a duplicate column in general?
Imo it should be detected and a detailed error should be printed.

> does it also happen with two non-enum columns
Did not try that one, but I guess this specific error only happens with enums because the error happens in `getEnumTypeName` method.

**Comment by nebkat** [comment]
> Imo it should be detected and a detailed error should be printed.

Agreed, I will take a look at this later.
