### ISSUE TITLE
“Right-hand side of 'instanceof' is not an object” when testing NestJS + TypeORM using Jest

### ISSUE THREAD

**Issue by Javarome** [typeorm/typeorm#7086]
## Issue Description

I have a working NestJS server that performs some TypeORM `repository.insert()` command. However when running the same operation from a Jest test (using `@nestjs/testing`'s `Test.createTestingModule(...)`, the infamous `Right-hand side of 'instanceof' is not an object` appears.

Looking in more details, it appears that this is due to some dynamic loading occurring in TypeORM's `QueryBuilder`:

    // loading it dynamically because of circular issue
    const InsertQueryBuilderCls = require("./InsertQueryBuilder").InsertQueryBuilder;

That line succeeds when running the NestJS server but fails when running the Jest test. More specifically:
- in the NestJS server: QueryBuilder `require("./InsertQueryBuilder")` returns an ES module with a `InsertQueryBuilder` in it. When setting a breakpoint here, strangely the debugged file appears located at `src/query-builder/QueryBuilder.ts` (which is non-existent, and should rather be `node_modules/typeorm/query-builder/QueryBuilder.js`), but this succeeds. 
- in the Jest test: `require("./InsertQueryBuilder")` return an empty object, and so `InsertQueryBuilder` is `undefined` which not an object indeed. The debugged file is as expected `node_modules/typeorm/query-builder/QueryBuilder.js`, but this fails.

### Expected Behavior

Same behavior when launching the server and the test.

### Actual Behavior

Exception is raised:
```
TypeError: Right-hand side of 'instanceof' is not an object
    at SelectQueryBuilder.Object.<anonymous>.QueryBuilder.insert (/xxx/src/query-builder/QueryBuilder.ts:173:17)
    at EntityManager.<anonymous> (/xxx/src/entity-manager/EntityManager.ts:466:14)
    at step (/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /xxx/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/xxx/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
    at EntityManager.Object.<anonymous>.EntityManager.insert (/xxx/node_modules/typeorm/entity-manager/EntityManager.js:286:24)
    at Repository.Object.<anonymous>.Repository.insert (/xxx/src/repository/Repository.ts:231:29)
    at MyCode.myMethod (/xxx/src/MyClass.ts)
```

### Steps to Reproduce

1. Define a NestJS test using a testing module with `TypeOrmModule.forRoot(options)` and `TypeOrmModule.forFeature([MyEntity])`
2. call your service that has `@InjectRepository(StoredPrediction) repository` constructor parameter, then attempts to `repository.insert(myEntity)`

### My Environment

My Jest configuration is as follows:

```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleDirectories: ['node_modules', 'src']
}
```

as my Typescript sources are under a src directory under the project root. Those path issues are also be related to my tsconfig.json, which contains:

```js
{
  "compilerOptions": {
  "module": "commonjs",
  "allowSyntheticDefaultImports": true,
  "target": "es2019",
  "baseUrl": "./src",
  "outDir": "./dist",
  "incremental": true,
  "lib": [
    "es2019"
  ]
}
}
```

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS Big Sur        |
| Node.js version     | v13.14.0 | 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.29 | 
| TS-Jest | v26.4.4 |
| Jest | v26.6.3 |

### Additional Context

My directory structure is:

- src
- node_modules
- jest.config.js
- tsconfig.json

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by tilfin** [comment]
I also have encountered this issue, but I don't use nestjs. It only happens on GitHub actions, not in my local WSL (Ubuntu 18.04).
It's caused by a pull request that adds a migration to create a new table.

Dependency | Version
-- | --
Operating System | Ubuntu 18.04
Node.js version | v14.13.0
Typescript version | v4.0.3
TypeORM version | v0.2.28
TS-Jest | v26.4.2
Jest | v26.6.1

**Comment by nebkat** [comment]
> in the NestJS server: QueryBuilder require("./InsertQueryBuilder") returns an ES module with a InsertQueryBuilder in it. When setting a breakpoint here, strangely the debugged file appears located at src/query-builder/QueryBuilder.ts (which is non-existent, and should rather be node_modules/typeorm/query-builder/QueryBuilder.js), but this succeeds.

Is this just as a result of a source map?

I wonder under which circumstances the circular issue would have occurred in the first place, the class is only used inside the method so surely that is ok? Could try replace this with a standard import and see if it causes any tests to fail.

**Comment by dschoeni** [comment]
I just encountered the same issue - downgrading to ts-jest `24.4.4` and jest `24.6.3` fixed this for me, so seems like a regression in one of those packages?

**Comment by subharb** [comment]
This happens to me randonmly and only when in debugging mode. If I run my tests without debugging all tests pass, and after all tests pass once, it also works on debug mode.

**Comment by spmsupun** [comment]
If anyone having this with mongo check your mongodb package version, type orm still uses 3.6 and in mongodb change id name 
ObjectID to ObjectId. so the  issue happens here:

 https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts#L175

**Comment by davidzwa** [comment]
@spmsupun you are 100% correct. This is a bug in general (not only Jest) as I run into it during normal operation.

This is the issue:
https://github.com/typeorm/typeorm/issues/7907#issuecomment-880518853

Basically comes down to: TypeORM requires Mongo v3 for now

**Comment by hkimani** [comment]
For those facing this issue on Mongo DB. 

The following worked for me (Downgraded my mongodb driver):
`npm install mongodb@3.5.7`

**Comment by soanvig** [comment]
I have exactly the same problem in exactly the place (but in query update part).
This is also somehow related to jest. Downgrading as @dschoeni suggested kindof fixed this problem

**Comment by adiwajshing** [comment]
updating jest & ts-jest to `^27.0.0` also fixed the issue🤷
