### ISSUE TITLE
[Bug] Invalid ColumnSchema max length checking

### ISSUE THREAD

**Issue by dinfer** [typeorm/typeorm#709]
In migration, creating table by `queryRunner.createTable`, `type: 'varchar', length: 5000,` causes an Error, showing max row size is 65535.

The sql `typeorm` outputed

```
CREATE TABLE `doctor` (
	`id` INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`referralDiseaseRange` varchar (5000)',
) ENGINE = INNODB
```

The error

```
Error: ER_TOO_BIG_ROWSIZE: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to chan
ge some columns to TEXT or BLOBs
    at Query.Sequence._packetToError (E:\work\crawler\spider\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\work\crawler\spider\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\work\crawler\spider\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\work\crawler\spider\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\work\crawler\spider\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\work\crawler\spider\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    --------------------
    at Protocol._enqueue (E:\work\crawler\spider\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (E:\work\crawler\spider\node_modules\mysql\lib\Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (E:\work\crawler\spider\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:180:44)
    at step (E:\work\crawler\spider\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:32:23)
    at Object.next (E:\work\crawler\spider\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:13:53)
    at fulfilled (E:\work\crawler\spider\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by pleerock** [comment]
It does not check length. Length is checked by your database, and as you can see it did that and showed you an error
