### ISSUE TITLE
Embedded Columns only get recognized on first level (MongoDB)

### ISSUE THREAD

**Issue by makislav** [typeorm/typeorm#714]
As the title states: Embedded Columns only get recognized on "the first level". As soon as you got an embedded document within an embedded document, TypeORM fails to save/loaded the Entity.

Seems like it doesn't move through the document recursively. I think this is the last big blocker for a usage in a production environment.

Example:
https://github.com/typeorm/typeorm/issues/645#issuecomment-318044077

**Comment by pleerock** [comment]
can you please check if in latest `0.1.0-alpha.33` you still have this issue.

**Comment by makislav** [comment]
Issue still exists in the latest version `0.1.0-alpha.33`.

We got up to five or six levels regarding the embedded documents, the following error gets thrown:
```
TypeError: Cannot read property 'general' of undefined
      at extractEmbeddedColumnValue_3 (src\metadata\ColumnMetadata.ts:381:86)
      at extractEmbeddedColumnValue_3 (src\metadata\ColumnMetadata.ts:381:39)
      at ColumnMetadata.getEntityValue (src\metadata\ColumnMetadata.ts:385:36)
      at src\persistence\SubjectOperationExecutor.ts:967:56
      at Array.forEach (native)
      at src\persistence\SubjectOperationExecutor.ts:963:47
      at Array.forEach (native)
      at SubjectOperationExecutor.updateSpecialColumnsInPersistedEntities (src\persistence\SubjectOperationExecutor.ts:959:29)
      at SubjectOperationExecutor.<anonymous> (src\persistence\SubjectOperationExecutor.ts:114:20)
      at step (node_modules\typeorm\persistence\SubjectOperationExecutor.js:32:23)
      at Object.next (node_modules\typeorm\persistence\SubjectOperationExecutor.js:13:53)
      at fulfilled (node_modules\typeorm\persistence\SubjectOperationExecutor.js:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by pleerock** [comment]
I'll close this issue and lets continue discussion in #645
