### ISSUE TITLE
Not able to generate migrations for a changed relation

### ISSUE THREAD

**Issue by aedelkhanday** [typeorm/typeorm#7143]
I am trying to update the relations between two tables:

Previous Table definitions:

**Table Resource:**
`export class Resource extends ExternalEntity {
  @Column({ type: 'text', nullable: true })
  @Expose()
  url: string;

  @ManyToOne(() => CourseGroup, (courseGroup) => courseGroup.resource)
  groupCourse?: CourseGroup;

  @OneToOne(() => CourseGroup, (courseGroup) => courseGroup.additionalImage)
  additionalImage: CourseGroup;
}
`

**Table CourseGroup**
`
export class CourseGroup extends ExternalEntity {
  
    @Column({ length: 100 })
    @Index()
    @Expose()
    slug: string;
  
    @BeforeUpdate()
    @BeforeInsert()
    setSlug(): void {
      if (this.title) {
        this.slug = this.title
          .trim()
          .toLowerCase()
          .replace(/ +/g, '-')
          .replace(/(-)\1+/g, '$1');
      }
    }
  
    @OneToMany(() => Resource, (resource) => resource.groupCourse, { cascade: true, eager: true })
    @Expose()
    resource: Resource[];
  
    @OneToOne(() => Resource, (resource) => resource.additionalImage, { cascade: true })
    @Expose()
    additionalImage?: Resource;
  
    @OneToMany(() => CourseGroupInterests, (courseGroupInterests) => courseGroupInterests.courseGroup, {
      cascade: true,
    })
    @Expose()
    courseGroupInterests: CourseGroupInterests[];
  
    @ManyToOne(() => SubCategory, (subCategory) => subCategory.courseGroup)
    @Expose()
    subCategory?: SubCategory;
  
    @OneToMany(() => Course, (course) => course.courseGroup)
    @Expose()
    course?: Course[];
    
    constructor(partialData?: Partial<CourseGroup>) {
      super();
  
      partialData && Object.assign(this, partialData);
    }
  }
`

As you can see above the CourseGroup has a OneToOne relationship with Resource entity. I want to have a OneToMany relationship with the Resource table and I updated the entities as below:

`
export class Resource extends ExternalEntity {
  @Column({ type: 'text', nullable: true })
  @Expose()
  url: string;

  @ManyToOne(() => CourseGroup, (courseGroup) => courseGroup.resource)
  groupCourse?: CourseGroup;

  @ManyToOne(() => CourseGroup, (courseGroup) => courseGroup.additionalImage)
  additionalImage: CourseGroup;
}
` 

and for the CourseGroup entuity as below:

`
export class CourseGroup extends ExternalEntity {
  
    @Column({ length: 100 })
    @Index()
    @Expose()
    slug: string;
  
    @BeforeUpdate()
    @BeforeInsert()
    setSlug(): void {
      if (this.title) {
        this.slug = this.title
          .trim()
          .toLowerCase()
          .replace(/ +/g, '-')
          .replace(/(-)\1+/g, '$1');
      }
    }
  
    @OneToMany(() => Resource, (resource) => resource.groupCourse, { cascade: true, eager: true })
    @Expose()
    resource: Resource[];
  
    @ManyToOne(() => Resource, (resource) => resource.additionalImage, { cascade: true })
    @Expose()
    additionalImage?: Resource[];
  
    @OneToMany(() => CourseGroupInterests, (courseGroupInterests) => courseGroupInterests.courseGroup, {
      cascade: true,
    })
    @Expose()
    courseGroupInterests: CourseGroupInterests[];
  
    @ManyToOne(() => SubCategory, (subCategory) => subCategory.courseGroup)
    @Expose()
    subCategory?: SubCategory;
  
    @OneToMany(() => Course, (course) => course.courseGroup)
    @Expose()
    course?: Course[];
    
    constructor(partialData?: Partial<CourseGroup>) {
      super();
  
      partialData && Object.assign(this, partialData);
    }
  }
`

The problem is when I try to generate the migration for this change, I get an error as below:

`
> @kyt/course-management-server@0.1.0 migration:generate /Users/adil/work/kyt-academy/course-management-server
> npm run typeorm:cli -- migration:generate -n "AddRel"

> @kyt/course-management-server@0.1.0 typeorm:cli /Users/adil/work/kyt-academy/course-management-server
> ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli -f ./src/database/ormconfig.ts "migration:generate" "-n" "AddRel"

Dirname:  /Users/adil/work/kyt-academy/course-management-server/src/database
Error during migration generation:
TypeError: Cannot read property 'name' of undefined
    at PostgresQueryRunner.<anonymous> (/Users/adil/work/kyt-academy/course-management-server/src/driver/postgres/PostgresQueryRunner.ts:824:122)
    at step (/Users/adil/work/kyt-academy/course-management-server/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/adil/work/kyt-academy/course-management-server/node_modules/tslib/tslib.js:120:57)
    at /Users/adil/work/kyt-academy/course-management-server/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/adil/work/kyt-academy/course-management-server/node_modules/tslib/tslib.js:109:16)
    at PostgresQueryRunner.changeColumn (/Users/adil/work/kyt-academy/course-management-server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:792:24)
    at /Users/adil/work/kyt-academy/course-management-server/src/driver/postgres/PostgresQueryRunner.ts:877:80
    at /Users/adil/work/kyt-academy/course-management-server/src/util/PromiseUtils.ts:34:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kyt/course-management-server@0.1.0 typeorm:cli: `ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli -f ./src/database/ormconfig.ts "migration:generate" "-n" "AddRel"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @kyt/course-management-server@0.1.0 typeorm:cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adil/.npm/_logs/2020-12-02T16_56_12_302Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kyt/course-management-server@0.1.0 migration:generate: `npm run typeorm:cli -- migration:generate -n "AddRel"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @kyt/course-management-server@0.1.0 migration:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adil/.npm/_logs/2020-12-02T16_56_12_395Z-debug.log
`

**Comment by aedelkhanday** [comment]
This is happening whenever I try to update the relations between entities and I try top generate the migration for it

**Comment by PatrickNLT** [comment]
Same here. I am migrating from a @OneToOne() relation to a @ManyToOne relation.

The crash is happening in the following code:

```ts
const uniqueConstraint = clonedTable.uniques.find(
  (unique) => {
    return (
      unique.columnNames.length === 1 &&
      !!unique.columnNames.find(
        (columnName) =>
          columnName === newColumn.name,
      )
    )
  },
)
clonedTable.uniques.splice(
  clonedTable.uniques.indexOf(uniqueConstraint!),
  1,
)
upQueries.push(
  new Query(
    `ALTER TABLE ${this.escapePath(
      table,
    )} DROP CONSTRAINT "${uniqueConstraint!.name}"`,
  ),
)
downQueries.push(
  new Query(
    `ALTER TABLE ${this.escapePath(
      table,
    )} ADD CONSTRAINT "${uniqueConstraint!.name
    }" UNIQUE ("${newColumn.name}")`,
  ),
)
```

For some reason, the `changeColumn` function is called twice for the same column.
The first time, `clonedTable.uniques` contains the constraint, so the code runs ok.
The second time, `clonedTable.uniques` is empty, resulting in a crash since `uniqueConstraint` is undefined as a result.

A quick workaround would be to ignore this code if `uniqueConstraint` is undefined, but this is probably not the right fix.
