### ISSUE TITLE
Migration create table. Getting this error: TypeError: tableName.split is not a function

### ISSUE THREAD

**Issue by ramifi** [typeorm/typeorm#7170]
## Issue Description
When I am trying to create a table with migrations. I am getting this error: TypeError: tableName.split is not a function
I have found the bug in your code.
In file: `/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js`
Replace line 2681 from this: 
```javascript
        var name =  target instanceof Table_1.Table || target instanceof View_1.View ? target.name : target;
```
to this:
```javascript
        var name = target['name'] || target;
```

### Expected Behavior

I expect it to create the table with no errors

### Actual Behavior

```
TypeError: name.split is not a function
    at SqlServerQueryRunner.escapePath (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js:2695:21)
    at SqlServerQueryRunner.createTableSql (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js:2483:42)
    at SqlServerQueryRunner.<anonymous> (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js:656:45)
    at step (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/tslib/tslib.js:122:57)
    at /Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/tslib/tslib.js:111:16)
    at SqlServerQueryRunner.createTable (/Users/rami/JibeDev/J2_API/J2Infra_API/node_modules/j2utils/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js:640:24)
    at v2101InfMigrationLog1607240010864.<anonymous> (/Users/rami/JibeDev/J2_API/J2Infra_API/build/migration/common/1607240010864-v2101-inf-migration_log.js:61:58) {stack: 'TypeError: name.split is not a function
    a…07240010864-v2101-inf-migration_log.js:61:58)', message: 'name.split is not a function'}
```

### Steps to Reproduce

```typescript
                await queryRunner.createTable(new Table({
                    name: "migrations_log",
                    columns: [
                        {
                            name: "uid",
                            type: "uniqueidentifier",
                            default: "newid()",
                            isPrimary: true
                        },
                        {
                            name: "vessel_id",
                            type: "int",
                        },
                        {
                            name: "name",
                            type: "varchar",
                            length: "250"
                        },
                        {
                            name: "module_code",
                            type: "varchar",
                            length: "50"
                        },
                        {
                            name: "function_code",
                            type: "varchar",
                            length: "50"
                        },
                        {
                            name: "status",
                            type: "char",
                            length: "1"
                        },
                        {
                            name: "log",
                            type: "varchar",
                            length: "8000"
                        }
                    ]
                }));
            } 
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS         |
| Node.js version     | v14.15.1 | 
| Typescript version  | v4.1.2 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Fix:
In file: `/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js`
Replace line 2681 from this: 
```javascript
        var name =  target instanceof Table_1.Table || target instanceof View_1.View ? target.name : target;
```
to this:
```javascript
        var name = target['name'] || target;
```

**Comment by bryopsida** [comment]
I'm seeing a similar issue when using Postgres.

```
Error during migration run:
TypeError: target.split is not a function
    at PostgresDriver.parseTableName (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/driver/postgres/PostgresDriver.js:720:28)
    at PostgresQueryRunner.escapePath (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:3095:30)
    at PostgresQueryRunner.createTableSql (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:2702:42)
    at PostgresQueryRunner.<anonymous> (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:602:45)
    at step (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at ~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
    at PostgresQueryRunner.createTable (~/.nvm/versions/node/v16.9.1/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:549:24)
   ```
  
  ## My Env 
Dependency | Version
-- | --
Operating System | macOS
Node.js version | v16.9.1
Typescript version | v4.4.3
TypeORM version | 0.2.37


I've been using this as a workaround 
``` typescript
import { Table } from "typeorm";

/**
 * 
 */
export class TablePatch extends Table {

    /**
     * Hacky patch
     * @param {string} delim
     * @return {string[]}
     */
    split(delim: string): string[] {
      return [this.name]  
    }
}
```

**Comment by NomadXD** [comment]
Getting the same error. Any fix for this ?

**Comment by bryopsida** [comment]
@NomadXD I don't have a fix but when I was looking at the issue it appeared to be caused by several instanceof checks failing which leads to the default case of assuming the passed in object is a string and calling split on it.

This is the case I would expect its intended to enter (grabbed from node_modules)

``` javascript
        if (target instanceof Table_1.Table || target instanceof View_1.View) {
            var parsed = this.parseTableName(target.name);
            return {
                database: target.database || parsed.database || driverDatabase,
                schema: target.schema || parsed.schema || driverSchema,
                tableName: parsed.tableName
            };
        }
```

but when using the Table class in migrations it's falling through to the string split case instead.

My workaround was to extend the Table class and add a split method 
``` typescript
import { Table } from "typeorm";

/**
 * 
 */
export class TablePatch extends Table {

    /**
     * Hacky patch
     * @param {string} delim
     * @return {string[]}
     */
    split(delim: string): string[] {
      return [this.name]
    }
}
```

And I use it in my migrations like this

``` typescript
  // create general record table
  await queryRunner.createTable(new TablePatch({
      name: "record",
      columns: [
          {
              name: "id",
              type: this.getUuidType(queryRunner.connection.driver.options.type),
              default: this.getDefaultForUUID(queryRunner.connection.driver.options.type),
              isPrimary: true
          },
          {
              name: "data",
              type: this.getJsonType(queryRunner.connection.driver.options.type)
          },
          {
              name: "created_at",
              type: this.getTimeStamptype(queryRunner.connection.driver.options.type),
              default: this.getNowFunc(queryRunner.connection.driver.options.type)
          },
          {
              name: "updated_at",
              type: this.getTimeStamptype(queryRunner.connection.driver.options.type),
              default: this.getNowFunc(queryRunner.connection.driver.options.type)
          }
      ]
  }));
```

**Comment by NomadXD** [comment]
@bryopsida Thanks a lot for the info. But it's crazy to see that a basic feature like migrations is broken and the issue is stale for almost 10 months. Specially with the typeorm when it's used by so many people.

**Comment by NomadXD** [comment]
@bryopsida Instead of installing the typeorm cli globally and using that, use npx to call the locally installed typeorm. Instead of `typeorm migration:run`, use `npx typeorm migration:run` and it works. I checked the versions and both are `0.2.37` but the local works and the global doesn't work. Strange issue.

**Comment by bryopsida** [comment]
@NomadXD that worked on my end as well.

**Comment by imnotjames** [comment]
This is because the global and local classes aren't the same so it's failing to hit the correct code paths.

A good solution for this is to make the global typeorm CLI load and use the local version instead of itself.

**Comment by ufhy** [comment]
Any update of this??

**Comment by asheba** [comment]
@NomadXD's solution helped us find the culprit for this issue - multiple typeorm version installed.

In case you're using a monorepo of some sort, you need to make sure you don't have conflicting versions installed (even double installations may cause the issue). The problematic code uses `instanceof` to determine the type, and two different installed versions of typeorm might make it fail. 
In our setup, the versions existed in the root dir and inside a package - but this can happen with any two locations which are imported by the code.
