### ISSUE TITLE
Another one Maximum call stack size exceeded, but  with TranformOperatorExecutor

### ISSUE THREAD

**Issue by olegorelwork** [typeorm/typeorm#7173]
There is no cycles in populate, but when i populate and trying send converted JSON array in response it throws a range error.
In my case all entities already have custom toJSON method and properties serialization, so i don't know what  the problem
here is my models:
```
import { Collection, Entity, EntityRepositoryType, OneToMany, PrimaryKey, Property, Unique, wrap } from "@mikro-orm/core";

import { CrimeRepository } from "../repositories";
import { CriticalLoot, Loot, RequiredItems } from './index'

@Entity()
export class Crime {

  [EntityRepositoryType]?: CrimeRepository;

  @PrimaryKey()
  id: number;

  @Property()
  @Unique()
  type: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
    default: "0"
  })
  criticalSuccessChance: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
  })
  successChance: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
    default: "0"
  })
  partialSuccessChance: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
  })
  failureChance: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
    default: "0"
  })
  criticalFailureChance: string;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
    default: "0"
  })
  partialFailureChance: string;

  @Property({
    comment: 'Stored in milliseconds',
  })
  timeToComplete: number;

  @Property()
  experienceReward: number;

  @Property()
  moneyReward: number;

  @Property({ default: 0 })
  experiencePenalty: number;

  @Property({ default: 1 })
  criticalMultiplier: number;

  @Property({ default: 0.5 })
  partialMultiplier: number;

  @OneToMany(() => CriticalLoot, item => item.crime, { hidden: false })
  criticalLoot = new Collection<CriticalLoot>(this);

  @OneToMany(() => Loot, item => item.crime, { hidden: false })
  loot = new Collection<Loot>(this);

  @OneToMany( () => RequiredItems, item => item.crime, { hidden: false })
  requiredItems = new Collection<RequiredItems>(this);

  @Property()
  requiredRank: number;

  toJSON() {
    const ret = wrap(this).toObject(['requiredItems', 'loot']);
    ret.requiredItems = this.requiredItems.toArray();
    ret.loot = this.loot.toArray()
    return ret;
  }
}
```

```
import {
  Entity,
  EntityRepositoryType,
  ManyToOne,
  PrimaryKey,
  Property,
  wrap,
} from '@mikro-orm/core';

import { LootRepository } from '../repositories';
import { GiItemType } from '../../game-inventory/entities/gi-item-type.entity';
import { Crime } from './crime.entity';

@Entity()
export class Loot {
  [EntityRepositoryType]?: LootRepository;

  @PrimaryKey()
  id: number;

  @ManyToOne()
  itemType: GiItemType;

  @ManyToOne({ })
  crime: Crime;

  @Property({
    columnType: 'decimal(5,2)',
    comment: 'Stored in percents (0..100) with decimal part.',
  })
  chance: string;

  toJSON() {
    return wrap(this).toObject(['crime']);
  }
}

```

```
import { Collection, Entity, EntityRepositoryType, ManyToMany, PrimaryKey, Property, wrap } from "@mikro-orm/core";

import { GiInventoryTypeRepository } from "../repositories";
import { GiItemTypeGroup } from "./gi-item-type-group.entity";

@Entity()
export class GiInventoryType {

  [EntityRepositoryType]?: GiInventoryTypeRepository;

  @PrimaryKey()
  id!: number;

  // TODO make unique
  @Property({ length: 100 })
  alias!: string;

  @Property({ length: 100 })
  purposeTitle!: string;

  @Property({ length: 100 })
  ownerTypeAlias!: string;

  @ManyToMany(() => GiItemTypeGroup)
  iTypeGroups: Collection<GiItemTypeGroup> = new Collection<GiItemTypeGroup>(this);

  @Property()
  defaultSize?: number;

  toJSON() {
    return wrap(this).toObject();
  }
}

```

Here is a controller function: 
```
async findAll(@Query() query): Promise<Crime[]> {
    const CrimeRepository = this.em.getRepository(Crime);
    this.em.clear()
    const crimes = await CrimeRepository.find({ }, { populate: ['loot.itemType']});
    this.em.clear()
    this.logger.info(crimes);
    this.em.clear()
    return crimes;
  }
```

Array logs: 
```
0: {
      "id": 1,
      "type": "Pickpocket on a train",
      "criticalSuccessChance": "0.00",
      "successChance": "70.00",
      "partialSuccessChance": "0.00",
      "failureChance": "30.00",
      "criticalFailureChance": "0.00",
      "partialFailureChance": "0.00",
      "timeToComplete": 20000,
      "experienceReward": 4,
      "moneyReward": 40,
      "experiencePenalty": 0,
      "criticalMultiplier": 1,
      "partialMultiplier": 1,
      "requiredRank": 0,
      "requiredItems": [],
      "loot": [
        {
          "id": 1,
          "itemType": {
            "id": 2,
            "typeGroup": 1,
            "alias": "balaclava",
            "titleSingle": "balaclava",
            "titleMany": "balaclavas",
            "image": null,
            "description": null,
            "isActive": true
          },
          "chance": "20.00"
        }
      ]
    }
```

stack trace logs: 
```
RangeError: Maximum call stack size exceeded\n    at TransformOperationExecutor.getKeys (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:341:12)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:130:31)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)\n    at TransformOperationExecutor.transform (/opt/app/node_modules/class-transformer/TransformOperationExecutor.js:270:43)
```

**Comment by haritonstefan** [comment]
@olegorelwork Looks like you opened the issue in the wrong repository.
In your code sample you're using [mikro-orm](https://github.com/mikro-orm/mikro-orm)
