### ISSUE TITLE
[Error] Schema:sync attempts to add foreign key that already exists

### ISSUE THREAD

**Issue by Banashek** [typeorm/typeorm#719]
## Version Info
typeorm version: `0.0.11`
database: `postgres`

## Model
```typescript
import {Table, PrimaryGeneratedColumn, Column } from "typeorm";
import { IsEmail } from "class-validator";

@Table()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({unique: true})
    @IsEmail()
    email: string;

    @Column({length: 20})
    username: string;

    @Column()
    firstname: string;

    @Column()
    lastname: string;

    @Column()
    password: string;

    @Column()
    image: string;

    @Column({nullable: true})
    token: string;

    constructor(id: number,
                email: string,
                username: string,
                firstname: string,
                lastname: string,
                password: string,
                image: string,
                token: string) {
        this.id = id;
        this.email = email;
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.image = image;
        this.token = token;
    }

}
```

## Command Run
`node_modules/.bin/typeorm schema:sync`

## Command Output / Error
```ShellSession
executing query: SELECT * FROM information_schema.tables WHERE table_catalog = 'myproj' AND table_schema = 'public' AND table_name IN ('user')
executing query: SELECT * FROM information_schema.columns WHERE table_catalog = 'myproj' AND table_schema = 'public'
executing query: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name  FROM pg_class t, pg_class i, pg_index ix, pg_attribute a
WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ('user') ORDER BY t.relname, i.relname
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_catalog = 'myproj' AND constraint_type = 'FOREIGN KEY'
executing query: SELECT * FROM information_schema.table_constraints WHERE table_catalog = 'myproj' AND constraint_type = 'UNIQUE'
executing query: SELECT c.column_name, tc.table_name, tc.constraint_name FROM information_schema.table_constraints tc
JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name)
JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema AND tc.table_name = c.table_name AND ccu.column_name = c.column_name
where constraint_type = 'PRIMARY KEY' and tc.table_catalog = 'myproj'
executing query: START TRANSACTION
columns changed in user. updating: email, username
executing query: ALTER TABLE "user" ADD CONSTRAINT "uk_email" UNIQUE ("email")
executing query: ALTER TABLE "user" ALTER COLUMN "username" TYPE character varying(20)
query failed: ALTER TABLE "user" ADD CONSTRAINT "uk_email" UNIQUE ("email")
error during executing query:error: relation "uk_email" already exists
executing query: ROLLBACK
query failed: ALTER TABLE "user" ALTER COLUMN "username" TYPE character varying(20)
error during executing query:error: current transaction is aborted, commands ignored until end of transaction block
{ error: relation "uk_email" already exists
    at Connection.parseE (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '779',
  routine: 'index_create' }
(node:47136) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: relation "uk_email" already exists
(node:47136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exitcode.
```

**Comment by pleerock** [comment]
can you please check this issue on the latest 0.1.0-alpha versions?

**Comment by mdziekon** [comment]
Same error happens in both ``0.1.0-alpha.32`` & ``0.1.0-alpha.33``.

**Comment by Banashek** [comment]
I've hit #724 right now during the upgrade, but I'll update this issue once I get around that one. Upgrade + changes makes it difficult to pull this one out into isolation at the moment.

**Comment by avbentem** [comment]
Are you sure this is about a foreign key, not about a unique key? I see `ALTER TABLE "user" ADD CONSTRAINT "uk_email" UNIQUE ("email")` failing in your logs.

And am I right to assume that you added `unique: true` in `@Column({unique: true})` at a later time, after that column already existed in the database? Then see #721.

**Comment by pleerock** [comment]
@Banashek  can you please answer @avbentem question and if you have same issues as he is describing and check the latest version and provide more info if you still have this issue?

**Comment by iz-iznogood** [comment]
I believe this should be fixed.
There is a test for that in test/functional/database-schema/unique-constraints

**Comment by pleerock** [comment]
Lets close it then. Authors please feel free to reopen this if you still have issues.
