### ISSUE TITLE
Entity loader is loading unwanted files that are in the same directory when using globs

### ISSUE THREAD

**Issue by MatthewDownsNR** [typeorm/typeorm#7198]
## Issue Description

When attempting to let TypeORM connect to my database using the ConnectionOptions configuration, it appears to be loading additional files, even though I specifically write in that it should only load entity files that end in _\*.entity.\*_

### Expected Behavior

The TypeORM entity loader should only be grabbing files that match the glob I provide.

### Actual Behavior

The TypeORM entity loader is trying to load other files in the directory, specifically I have one called _Organizaiton.resolver.ts_ which is loading in a utility file (that's what's causing the error). But, the true error is that it's trying to load the resolver file when it should not be, it should only be loading files that match the glob I provided, which is _\*.entity.\*_

```
[REDACTED]/src/objects/**/*.entity.*
Error: Cannot find module '~utilities/isNumeric'
Require stack:
- [REDACTED]/src/objects/Organization/Organization.resolver.ts
- [REDACTED]/src/objects/Organization/index.ts
- [REDACTED]/src/objects/Project/Project.entity.ts
- [REDACTED]/src/objects/Project/index.ts
- [REDACTED]/src/objects/Asset/Asset.entity.ts
- [REDACTED]/node_modules/typeorm/util/DirectoryExportedClassesLoader.js
- [REDACTED]/node_modules/typeorm/connection/ConnectionMetadataBuilder.js
- [REDACTED]/node_modules/typeorm/connection/Connection.js
- [REDACTED]/node_modules/typeorm/connection/ConnectionManager.js
- [REDACTED]/node_modules/typeorm/index.js
- [REDACTED]/scripts/db-init.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> ([REDACTED]/src/objects/Organization/Organization.resolver.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module.m._compile ([REDACTED]/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.require.extensions.<computed> [as .ts] ([REDACTED]/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:967:32)
```

### Steps to Reproduce

1. Create an entity file called _Something.entity.ts_ in a directory called _objects_
2. Create a resolver file called _Something.resolver.ts_ in the same directory, perhaps even with an import that's using a typescript alias (such as shown in my error log above) so that you know it's trying to load the resolver file
3. Update your ConnectionOptions `entities` section to:

```typescript
const connectionOptions: ConnectionOptions = {
    ...
    entities: [resolve(__dirname, '../src/objects/**/*.entity.*')],
    ...
};
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS Big Sur 11.1 (M1 Chip) |
| Node.js version     | v15.3.0 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by MatthewDownsNR** [comment]
I tried using an "everything except" glob, but still no avail.
`entities: [resolve(__dirname, '../src/objects/**/*.!(resolver).ts')],`
