### ISSUE TITLE
`.save()` not updating composite key with Postgres

### ISSUE THREAD

**Issue by nickcoury** [typeorm/typeorm#720]
This may be related to #477 

When operating on a table with a composite key, `.save()` only seems to insert instead of updating when a row already exists.  I can insert a set of rows the first time, but get an error when attempting the same data that the primary key constraint is violated.

If I combine the two values into a concatenated string and use that as the index, `.save()` inserts/updates as expected.  I will use this as a workaround for the time being.

typeorm@0.1.0-alpha.33
Postgres@9.6.2 on AWS RDS

```
@Entity('participants')
class Participant{
  @PrimaryColumn('int') order_id: number;
  @PrimaryColumn('text') distance: string;
  @Column('money') price?: string;
  ...
}

const participants = [...];

try {
  const result = await connection.manager.save(participants);
} catch (err) {
  console.log(err);
}
```

This code works when running the first time, and rows are created in the database as expected.  Upon running the second time, I get the following error:

```
{
  "name": "QueryFailedError",
  "length": 249,
  "severity": "ERROR",
  "code": "23505",
  "detail": "Key (order_id, distance)=(1026904, 52K) already exists.",
  "schema": "public",
  "table": "participants",
  "constraint": "participants_pkey",
  "file": "nbtinsert.c",
  "line": "433",
  "routine": "_bt_check_unique",
  "query": "INSERT INTO \"participants\"(\"order_id\", \"registration_date\", \"distance\", \"quantity\", \"price\", \"price_option\", \"order_type\", \"coupon\", \"first_name\", \"last_name\", \"gender\", \"age\", \"age_group\", \"dob\", \"email\", \"address\", \"city\", \"state\", \"zip\", \"country\", \"phone\", \"removed\", \"bib\", \"team_name\", \"emergency_name\", \"emergency_phone\", \"statement_id\") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27) ",
  "parameters": [
    "1026904",
    "2017-01-28T23:30:15.000Z",
    "52K",
    "1",
    "63.78",
    "52K",
    "Credit Card",
    "0",
    "Test",
    "User",
    "M",
    "47",
    "",
    "01/01/1970",
    "testuser@gmail.com",
    "1234 Test Street",
    "Scottsdale",
    "AZ",
    "85260",
    "USA",
    "6025555555",
    "False",
    "",
    "",
    "Emergency User",
    "4805555555",
    "32341"
  ]
}
```

**Comment by michaelonubogugauge** [comment]
+1 this

**Comment by pleerock** [comment]
Cannot be reproduced, added tests to confirm it

**Comment by voodooattack** [comment]
Experiencing the same issue with PostgreSQL. Here is my setup after cleaning up the GraphQL stuff:

```ts
@Entity()
@Index(['locale', 'message'], { unique: true })
export class Translation {
  @ManyToOne(() => Locale, { primary: true, nullable: false })
  @JoinColumn()
  locale: Locale;
  @ManyToOne(() => Message, { primary: true, nullable: false })
  @JoinColumn()
  message: Message;
  @Column('text')
  text: string;
}

@Entity()
export class Message {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' })
  id: number;
}

@Entity()
export class Locale {
  @PrimaryColumn('char', { length: 5 })
  code: string;

  @Column('varchar', { length: 50 })
  englishName: string;

  @OneToOne(() => Message, { cascadeAll: true, onDelete: 'SET NULL' })
  @JoinColumn()
  name: Message;
}

export async function updateTranslation(manager: EntityManager,
                                        locale: string,
                                        text: string,
                                        message?: number)
{
  if (!message)
    message = (await manager.getRepository(Message).save(new Message())).id;
  const repo = manager.getRepository(Translation);
  const translation = await repo.create({
    locale: { code: locale },
    message: { id: message },
    text
  });
  const result = await repo.save(translation);
  return result.message.id;
}

```
This is the error message I get when I try to update an existing translation:
```
{ QueryFailedError: duplicate key value violates unique constraint "translation_pkey"
    at new QueryFailedError (/dist/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/dist/src/driver/postgres/PostgresQueryRunner.ts:216:26)
    at Query.handleError (/dist/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/dist/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/dist/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
  name: 'QueryFailedError',
  length: 231,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("localeCode", "messageId")=(en-US, 1427) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'translation',
  column: undefined,
  dataType: undefined,
  constraint: 'translation_pkey',
  file: 'nbtinsert.c',
  line: '433',
  routine: '_bt_check_unique',
  query: 'INSERT INTO "translation"("text", "localeCode", "messageId") VALUES ($1,$2,$3) ',
  parameters: [ 'test-slug', 'en-US', 1427 ] }
```

**Comment by pleerock** [comment]
@voodooattack there are both issues in ORM and in your code.

I've fixed ORM issues and made a new release with those changes.

Your issues are:

First, since you have used "bigint" you must use strings instead of numbers, because regular number does not support bigint values. So,

```ts
    @PrimaryGeneratedColumn("increment", { type: "bigint" })
    id: number;
```

must be:

```ts
    @PrimaryGeneratedColumn("increment", { type: "bigint" })
    id: string;
```

second, be careful with `char` usage. Char with length: 5 for `"US"` entry will be saved in database this way: `"US     "`. And this can bring you problems, because when you save entity next time you must provide exactly same value `"US     "`. I really recommend not to use "char" and use "varchar" instead to avoid such issues.

**Comment by simplenotezy** [comment]
Related issue: https://github.com/typeorm/typeorm/issues/8532

**Comment by simplenotezy** [comment]
@pleerock Your apporach does not seem to work, at least with cockroachdb.

Does not work
```ts
@PrimaryGeneratedColumn('increment', { type: 'bigint' })

@PrimaryGeneratedColumn('rowid', { type: 'bigint' }) // does not work either - the parser will complain: Argument of type '"rowid"' is not assignable to parameter of type '"identity"'
````

**Comment by simplenotezy** [comment]
Whoops, this done did the trick:

```ts
@PrimaryGeneratedColumn('rowid')
```
