### ISSUE TITLE
[Error] Upgrading version attempts to drop composite key

### ISSUE THREAD

**Issue by Banashek** [typeorm/typeorm#724]
Bit of a strange one here, and might just be an edge case, so I'd be happy with a workaround to get autoschemasync to be happy.

The model is essentially a join table with extra properties on it.

## Version Info
version `0.0.11` updated to `0.1.0-alpha.33`
database: `postgres`

## Model as of `0.0.11`
```typescript
@Table()
export class GroupUser {

    @PrimaryColumn("int")
    @ManyToOne(type => Group, group => group.groupUsers)
    group: Group;

    @PrimaryColumn("int")
    @ManyToOne(type => User, user => user.groupUsers)
    user: User;

    @Column({default: GroupUserRole.User})
    role: GroupUserRole;

    @Column({default: GroupUserStatus.InvitePending})
    status: GroupUserStatus;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
```

At this point the database has columns `user int` and `group int` which act as the primary composite key.

## Model as of `0.1.0-alpha.33`
```typescript
@Entity()
export class GroupUser {

    @ManyToOne(type => Group, group => group.groupUsers, {primary: true})
    group: Group;

    @ManyToOne(type => User, user => user.groupUsers, {primary: true})
    user: User;

    @Column({default: GroupUserRole.User})
    role: GroupUserRole;

    @Column({default: GroupUserStatus.InvitePending})
    status: GroupUserStatus;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
```

Now the database names the foreign key fields `userId int` and `groupId int` which act as the primary composite key.

After this change, the following autoschemasync migration error occurs:

## Error
```ShellSession
Error:  { QueryFailedError: column "groupId" is in a primary key
    at new QueryFailedError (/Users/jonbanashek/Projects/typescript/myproj/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.callback (/Users/jonbanashek/Projects/typescript/myproj/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:214:38)
    at Query.handleError (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/client.js:135:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/Users/jonbanashek/Projects/typescript/myproj/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
  name: 'QueryFailedError',
  length: 95,
  severity: 'ERROR',
  code: '42P16',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4985',
  routine: 'ATExecDropNotNull',
  query: 'ALTER TABLE "group_user" ALTER COLUMN "groupId" DROP NOT NULL',
  parameters: [] }
```

So it appears to be trying to drop not null columns of a primary key.

If I turn off schema sync the program works fine, so again I'd be ok with just a workaround to tell typeorm to skip this update. Right now I've just turned off autoschemasync and have been doing manual migrations to unblock myself.

Let me know if you'd like more info.

**Comment by pleerock** [comment]
If you have existing database 0.0.11 and you updated to 0.1.0-alpha.33 you must make changes to the database manually (or drop database and fill with data again) - there are too much breaking changes, schema sync can't make them for you.

**Comment by Banashek** [comment]
I figured as much. Thanks!
