### ISSUE TITLE
Sporadic null value in column "Parent" violates not-null constraint when inserting child relation

### ISSUE THREAD

**Issue by papaspiridis** [typeorm/typeorm#7291]
## Issue Description
Part of our model has Shipments and TrackingDetails (ManyToOne).
Each time the service receives an event (package picked up, delivered, etc), it inserts a new row to the the TrackingDetails table.

Reviewing our logs, we noticed that a tiny percentage (<0.3%) of requests fail with the "null value in column "shipmentId" violates not-null constraint" when inserting a new TrackingDetail. To be more precise, the query that sets the shipmentId and the updatedAt field.

The strange thing is that nearly all events are saved without issues, and also it does not make a difference whether it's the first event for a specific shipment or not.  To further complicate things, the event generation service retries these failed requests and they are saved correctly.

### Expected Behavior
Every tracking detail (child relation) to be created in the database without errors

### Actual Behavior
Around 0.33% (10 in 3000) of requests fail to get created because of a null value in the foreign-key column (Parent) 

```
Error:  QueryFailedError: null value in column "shipmentId" violates not-null constraint
    at new QueryFailedError (/project/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/project/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/project/node_modules/pg/lib/query.js:146:19)
    at Connection.connectedErrorMessageHandler (/project/node_modules/pg/lib/client.js:233:17)
    at Connection.emit (events.js:310:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at /project/node_modules/pg/lib/connection.js:109:10
    at Parser.parse (/project/node_modules/pg-protocol/src/parser.ts:107:9)
    at Socket.<anonymous> (/project/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 313,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (52090, null, Shipment was picked up, null, 2020-11-06 12:46:00.836399, 2020-11-06 12:46:00.866415, null, 2020-11-06 13:01:05).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'tracking_details',
  column: 'shipmentId',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1965',
  routine: 'ExecConstraints',
  query: 'UPDATE "tracking_details" SET "shipmentId" = $2, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1',
  parameters: [ 52090, null ],
  status: 500
}

```

### Steps to Reproduce

This issue is really hard to reproduce because the code works 99%+ of the time.
Webhooks that fail because of this error, succeed when they are retried.
Our code is pretty simple.  In the function that saves the TrackingDetail, the shipment always exists because it is created long before tracking events start arriving.

```typescript
//entity/Shipment.ts
@Entity({ name: 'shipments' })
export class Shipment {
  @PrimaryGeneratedColumn()
  id?: number;

  @ManyToOne((type) => ShippingOrder, (shippingOrder) => shippingOrder.shipments, {
    nullable: false,
    onDelete: 'CASCADE',
  })
  shippingOrder?: ShippingOrder;
  ...
}

//entity/TrackingDetail.js
@Entity({ name: 'tracking_details' })
export class TrackingDetail {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne((type) => Shipment, (shipment) => shipment.trackingDetails, {
    nullable: false,
    onDelete: 'CASCADE',
  })
  shipment: Shipment;
  ...
  @CreateDateColumn({ type: 'timestamp' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt: Date;
}

//services/trackingDetails.js
  add(
    shipment: Shipment,
    description: TrackingStatus,
    notes: string = null,
    eta: Date | null = null,
  ) {
    let newDetail = this.trackingDetailRepository.create();
    newDetail.shipment = shipment;
    newDetail.description = description;
    newDetail.notes = notes;
    newDetail.latestEta = eta;
    return this.trackingDetailRepository.save(newDetail);
  }
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 16.04.3 LTS |
| Node.js version     | v12.16.3 | 
| Typescript version  | v3.9.3 | 
| TypeORM version     | v0.2.25 | 
Our database is running on AWS, RDS Postgresql flavor

### Additional Context

This seems related to https://github.com/typeorm/typeorm/issues/6356 and https://github.com/typeorm/typeorm/issues/6858
The problem is that it does not seem to be consistent

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by AlteaDown** [comment]
We are seeing this as well on the following setup:
> react-native: "0.63.4"
> typeorm: "0.2.30"
> typescript: "4.1.2",
> Hermes Runtime enabled

The issue does not seem to happen with Hermes Runtime disabled, (using JSCore), and typeorm: "0.2.24" (however other issues happen when using that version of TypeORM)

It is sporadic for us as well, but seems to happen in one table, 25% of the time (same rows every time).

**Comment by ofekrom** [comment]
similar behavior happens to me as well

**Comment by 592da** [comment]
having similar issue,
any thoughts on how to fix it?

**Comment by MrCheater** [comment]
Same problem :'(

**Comment by CamMcRae** [comment]
Still encountering this with postgres. I have 2 almost identical save calls, but one fails and one does not. I would be willing to work on it, but I fall in the camp of "Yes, I have the time, but I don't know how to start. I would need guidance."
