### ISSUE TITLE
Repository not found after tsc ran

### ISSUE THREAD

**Issue by kr1x** [typeorm/typeorm#7306]
## Issue Description

I am trying to setup `apollo-graphql` in combination with `typeorm` and `type-graphql` (in a typescript + mysql environment). The combination of those libraries is purely awesome and I really enjoy working with it :) It works perfectly fine in the dev-environment, where I created my entities with decorators and everything just works. 

However, when I try to transpile the typescript code to javascript with tsc and try to run it, the server starts without any issues, but it can't find any repository.

### Expected Behavior

The repositories should be found.

### Actual Behavior

The repositories are not found.

```
{
  "errors": [
    {
      "message": "No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "RepositoryNotFoundError",
          "message": "No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?",
          "stacktrace": [
            "RepositoryNotFoundError: No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?",
            "    at new RepositoryNotFoundError (/path/node_modules/typeorm/error/RepositoryNotFoundError.js:11:28)",
            "    at EntityManager.getRepository (/pathnode_modules/typeorm/entity-manager/EntityManager.js:649:19)",
            "    at Connection.getRepository (/path/node_modules/typeorm/connection/Connection.js:367:29)",
            "    at Function.BaseEntity.getRepository (/path/node_modules/typeorm/repository/BaseEntity.js:80:27)",
            "    at Function.BaseEntity.find (/path/node_modules/typeorm/repository/BaseEntity.js:198:21)",
            "    at UserResolver.users (/path/dist/resolvers/UserResolver.js:22:28)",
            "    at /path/node_modules/type-graphql/dist/resolvers/create.js:34:68",
            "    at Object.applyMiddlewares (/path/node_modules/type-graphql/dist/resolvers/helpers.js:58:16)",
            "    at /path/node_modules/type-graphql/dist/resolvers/create.js:27:26",
            "    at field.resolve (/path/node_modules/graphql-extensions/dist/index.js:134:26)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### Steps to Reproduce

I created an example repository to reproduce the error:
https://github.com/kr1x/apollo-graphql-typeorm

In dev environment:
```
npm run start
```

In production environment (with transpiling)
```
./node_modules/.bin/tsc .
TYPEORM_CONNECTION=mysql TYPEORM_HOST=localhost TYPEORM_USERNAME=root TYPEORM_PASSWORD=root TYPEORM_DATABASE=anex TYPEORM_PORT=3306 TYPEORM_SYNCHRONIZE=true TYPEORM_LOGGING=false TYPEORM_ENTITIES=dist/entity/*.js node dist/index.js
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 18.04  |
| Node.js version     | v12.4.0 |
| Typescript version  | v4.1.3 |
| TypeORM version     | v0.2.30 |

### Additional Context

I checked the `ConnectionMetadataBuilder`, because I am pretty sure that the entities are found. And I put some logging in there, where it iterates all the entities and checks for the instance of the EntitySchema:

```
    /**
     * Builds entity metadatas for the given classes or directories.
     */
    ConnectionMetadataBuilder.prototype.buildEntityMetadatas = function (entities) {
        // todo: instead we need to merge multiple metadata args storages
        var _a = tslib_1.__read(OrmUtils_1.OrmUtils.splitClassesAndStrings(entities || []), 2), entityClassesOrSchemas = _a[0], entityDirectories = _a[1];
        var entityClasses = entityClassesOrSchemas.filter(function (entityClass) { return (entityClass instanceof EntitySchema_1.EntitySchema) === false; });
        var entitySchemas = entityClassesOrSchemas.filter(function (entityClass) { return entityClass instanceof EntitySchema_1.EntitySchema; });
        var allEntityClasses = tslib_1.__spread(entityClasses, DirectoryExportedClassesLoader_1.importClassesFromDirectories(this.connection.logger, entityDirectories));
        allEntityClasses.forEach(function (entityClass) {
>>            console.log('looping entity', entityClass, entityClass instanceof EntitySchema_1.EntitySchema);
                if (entityClass instanceof EntitySchema_1.EntitySchema) {
                entitySchemas.push(entityClass);
                allEntityClasses.slice(allEntityClasses.indexOf(entityClass), 1);
            }
        });
        // ...
```

The output is like this:
```
looping entity [Function: User] false
Server has started!
```

So this seems that it could totally find the entities but it ignores it, since it's not instanceof the EntitySchema. However, I used the `@Entity()` decorator in the entity. So I am a bit confused right now 🤔 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kr1x** [comment]
I'm trying to resolve this issue for two days now and after a short walk outside, I finally noticed that the server which returned the error-stacktrace (the production server behind Passenger NodeApp) is not the one that I am debugging and changing (it's on the production server, but not executed by the Passenger NodeApp). 

So the issue was unfortunately, that the Passenger NodeApp did not restart with the correct env params and could simply not find my entities. 

Everything works perfectly fine now. Sorry for the inconvenience.
