### ISSUE TITLE
Many To Many with custom properties not working.

### ISSUE THREAD

**Issue by telpochyaotl** [typeorm/typeorm#7315]
## Issue Description

Many To Many with custom properties not working as documented in https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md#many-to-many-relations-with-custom-properties 

The documentation is missing to explain that you have to define the custom table using @JoinTable decorator .

However even when the @JoinTable decorator is used, if the join table has itself an auto generated primary key as the example suggests, the sync process fails.

### Expected Behavior

Issuing a `schema:sync` command should create the schema with no errors, the join table's primary key should be left intact and if necessary a unque compound index be created for the fields specified in the JoinTable.

### Actual Behavior
 Schema creation fails with the following error.

```
query: CREATE TABLE `post_to_category` (`postToCategoryId` int NOT NULL AUTO_INCREMENT, `postId` int NOT NULL, `categoryId` int NOT NULL, `order` int NOT NULL, PRIMARY KEY (`postToCategoryId`)) ENGINE=InnoDB
query: CREATE TABLE `post` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL, `text` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
query: CREATE TABLE `category` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
query: ALTER TABLE `post_to_category` CHANGE `postToCategoryId` `postToCategoryId` int NOT NULL
query: ALTER TABLE `post_to_category` DROP PRIMARY KEY
query: ALTER TABLE `post_to_category` DROP COLUMN `postToCategoryId`
query: ALTER TABLE `post_to_category` DROP COLUMN `order`
query: ALTER TABLE `post_to_category` ADD `postToCategoryId` int NOT NULL PRIMARY KEY AUTO_INCREMENT
query: ALTER TABLE `post_to_category` ADD `order` int NOT NULL
query: ALTER TABLE `post_to_category` CHANGE `postToCategoryId` `postToCategoryId` int NOT NULL
query: ALTER TABLE `post_to_category` DROP PRIMARY KEY
query: ALTER TABLE `post_to_category` ADD PRIMARY KEY (`postId`, `categoryId`)
query: ALTER TABLE `post_to_category` CHANGE `postToCategoryId` `postToCategoryId` int NOT NULL AUTO_INCREMENT
BadRequestException: Database error code: 1075. Message: Incorrect table definition; there can be only one auto column and it must be defined as a key
    at Object.extractError (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/private/tmp/TypeOrmM2M/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'BadRequestException',
  time: 2021-01-25T23:21:27.565Z,
  requestId: '690d034d-4356-4826-8266-c554a15d9870',
  statusCode: 400,
  retryable: false,
  retryDelay: 71.45281467157103
}
```

### Steps to Reproduce

1. create a typeorm app with `npx typeorm --init --name TypeORMmanyToMany --database mysql
2. add the entities specified below to src/entity
3.  run `npm start`

```typescript
// src/entity/Post.ts: 
import {Entity, PrimaryGeneratedColumn, Column, ManyToMany, JoinTable, OneToMany} from "typeorm";
import {Category} from "./Category";
import {PostToCategory} from "./PostToCategory";

@Entity()
export class Post {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  text: string;

  @OneToMany(() => PostToCategory, postToCategory => postToCategory.post)
  postToCategories!: PostToCategory[];

  @ManyToMany(() => Category, category => category.posts)
  @JoinTable({
    name: "post_to_category",
    joinColumn: {
      name: "postId",
      referencedColumnName: "id"
    },
    inverseJoinColumn: {
      name: "categoryId",
      referencedColumnName: "id"
    }
  })
  categories: Category[];
}

// src/entity/Category.ts
import {Entity, PrimaryGeneratedColumn, Column, ManyToMany, OneToMany} from "typeorm";
import {Post} from "./Post";
import {PostToCategory} from "./PostToCategory";

@Entity()
export class Category {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => PostToCategory, postToCategory => postToCategory.category)
  postToCategories!: PostToCategory[];

  @ManyToMany(() => Post, post => post.categories)
  posts: Post[];
}

// src/entity/PostToCategory.ts
import { Entity, Column, ManyToOne, PrimaryGeneratedColumn, Index } from "typeorm";
import { Post } from "./Post";
import { Category } from "./Category";

@Entity()
export class PostToCategory {
    @PrimaryGeneratedColumn()
    public postToCategoryId!: number;

  @Column({ primary: false})
    public postId!: number;

  @Column({ primary: false })
    public categoryId!: number;

    @Column()
    public order!: number;

    @ManyToOne(() => Post, post => post.postToCategories)
    public post!: Post;

    @ManyToOne(() => Category, category => category.postToCategories)
    public category!: Category;
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Mac OSX Big Sur or Any Linux      |
| Node.js version     | v12.19.0 | 
| Typescript version  | v3.3.3333 | 
| TypeORM version     | v0.2.30 | 

### Relevant Database Driver(s)

- [x] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I don't have the time right now, but if we come up with correct behavior and though I have some idea of where to make the changes, with some guidance to make sure the implementation is correct, I could work on it in the next couple of months as time permits. I need to understand the underlying purpose of modifying the custom join table when one is used. Ideally, I believe, if a custom join table is used, it should be totally up to the implementer to make that entity and TypeORM should not modify it, just use the relationship.... 

Thank you so much!

**Comment by nebkat** [comment]
If you are adding custom properties you don't use `@ManyToMany` at all. The new custom entity just replicates the many-to-many junction table where you have a many-to-one relation to both of the entities - think how you would implement a many-to-many table without any ORM. Unfortunately it's not possible combine the auto created junction table with the custom one.

Please try ask around on the community [Slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) first in future if you are unsure of what the documentation is suggesting. There may well need to be an improvement in how it's described but it's better to at least save you time writing up the issue.

**Comment by telpochyaotl** [comment]
@nebkat thank you for your response. I did post this issue in Slack first. While I have found several ways to work around this by not even declaring the relationship in the entities and using the `QueryBuilder`, `innerJoin` and `innerJoinAndMapMany`, the documentation is not clear that it's not possible to use a `ManyToMany` in that case. Just to be clear, you are stating that it is not possible to have this relationship declared in the entities, correct?

If so, It's not entirely accurate as it is possible to define the ManyToMany and have the 'Sync' process not create that TypeORM made table,  if your custom join table doesn't have an auto-increment primary key and you add `primary: true` to each of the fields that link to both side tables.

**Comment by nebkat** [comment]
- It's not possible to have the relationship declared using `@ManyToMany`, if you are using custom properties.

- It is possible to describe a many-to-many relationship by declaring the junction table manually. The only thing lost with that setup is that you have to more manually describe the joins, i.e. "join junction" and "join junction.relation" vs "join manytomany", but presumably that is how you would want it to be anyway since you care about the custom properties of each relation.

- You could in theory prevent the `@ManyToMany` generated junction table from syncing and try to place your own one in it's place, but it would very much be a hack and I would strongly recommend against that.

**Comment by telpochyaotl** [comment]
thank you @nebkat for your help!

**Comment by nebkat** [comment]
Apologies I thought I had mentioned it in my first comment but I see now that I did not: the documentation may indeed need some improvement as I can see how you might have got confused by the description, and re Slack the issues are pretty overloaded so just making sure everyone is using it 😃 Feel free to submit a PR with a better description for that section in the docs if you have a better idea now!
