### ISSUE TITLE
TypeOrm Generates Invalid SQL with Advanced Find Options

### ISSUE THREAD

**Issue by rrdlpl** [typeorm/typeorm#7324]
## Issue Description
I'm following the documentation described in https://github.com/typeorm/typeorm/blob/master/docs/find-options.md to use this Advanced Options to query the DB with my Repository. However, this is not working because is generating an invalid SQL

### Expected Behavior
- The query generated with this Advanced Find Options should be valid. 

### Actual Behavior
- The code generates an invalid SQL

```
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `_value` = 'test', `_useParameter` = true, `_multipleParameters` = false, `useP' at line 1
    at new QueryFailedError (/Users/r/workspace/services/node_modules/@nestjs/typeorm/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/r/workspace/services/node_modules/@nestjs/typeorm/src/driver/mysql/MysqlQueryRunner.ts:166:37)
    at Query.<anonymous> (/Users/r/workspace/services/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/r/workspace/services/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/r/workspace/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/r/workspace/services/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/r/workspace/services/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/r/workspace/services/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/r/workspace/services/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/r/workspace/services/node_modules/mysql/lib/protocol/Protocol.js:38:16) {
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check ' +
    'the manual that corresponds to your MySQL server version for ' +
    "the right syntax to use near ' `_value` = 'test', " +
    "`_useParameter` = true, `_multipleParameters` = false, `useP' " +
    'at line 1',
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: 'You have an error in your SQL syntax; check the manual ' +
    'that corresponds to your MySQL server version for the ' +
    "right syntax to use near ' `_value` = 'test', " +
    '`_useParameter` = true, `_multipleParameters` = false, ' +
    "`useP' at line 1",
  sqlState: '42000',
  index: 0,
  sql: 'SELECT `CampaignChannelEntity`.`id` AS `CampaignChannelEntity_id`, ' +
    '`CampaignChannelEntity`.`name` AS `CampaignChannelEntity_name`, ' +
    '`CampaignChannelEntity`.`createdAt` AS ' +
    '`CampaignChannelEntity_createdAt`, ' +
    '`CampaignChannelEntity`.`updatedAt` AS ' +
    '`CampaignChannelEntity_updatedAt` FROM `campaign_channel` ' +
    '`CampaignChannelEntity` WHERE `CampaignChannelEntity`.`name` = ' +
    "`_type` = 'equal', `_value` = 'test', `_useParameter` = true, " +
    '`_multipleParameters` = false, `useParameter` = true, ' +
    "`multipleParameters` = false, `value` = 'test'",
  name: 'QueryFailedError',
  query: 'SELECT `CampaignChannelEntity`.`id` AS `CampaignChannelEntity_id`, ' +
    '`CampaignChannelEntity`.`name` AS `CampaignChannelEntity_name`, ' +
    '`CampaignChannelEntity`.`createdAt` AS `CampaignChannelEntity_createdAt`, ' +
    '`CampaignChannelEntity`.`updatedAt` AS `CampaignChannelEntity_updatedAt` ' +
    'FROM `campaign_channel` `CampaignChannelEntity` WHERE ' +
    '`CampaignChannelEntity`.`name` = ?',
  parameters: [
    FindOperator {
      _type: 'equal',
      _value: 'test',
      _useParameter: true,
      _multipleParameters: false
    }
  ]
}
```

### Steps to Reproduce

1. Entity class
```
import { Column, CreateDateColumn, Entity, PrimaryColumn } from 'typeorm';

@Entity({
  name: 'campaign_channel'
})
export class CampaignChannelEntity {
  @Column({
    type: 'varchar',
    nullable: false,
    length: 36,
  })
  @PrimaryColumn()
  public id: string;

  @Column({
    type: 'varchar',
    nullable: false,
    length: 100
  })
  public name: string;

  @CreateDateColumn()
  public createdAt: string;

  @CreateDateColumn()
  public updatedAt: string;

  constructor(partial: Partial<CampaignChannelEntity>) {
    Object.assign(this, partial);
  }
}

```
2. Call the repository
```
 const result = await this.repository.find({
       name:  Equal('test')
  });
```

I know that I could call the code in this case without the `Equal` Option but I need to call the repository with other Advanced Find options such as `Like`, `GreaterThan`, etc and with those ones is also failing. 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System   | macOS BigSur 11.1    |
| Node.js version     | v12.0.0
| Typescript version  | 4.1.2 | 
| TypeORM version     | 0.2.18  |
| @nestjs/typeorm | 7.0.0 |
| nestjs | 7.0.9 |

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
You appear to be using an old version of TypeORM? The latest is 0.2.30.

**Comment by biancazzurri** [comment]
this is still happening in 0.2.41
