### ISSUE TITLE
Throw an error when I try to do a leftJoinAndSelect. "QueryFailedError: argument of AND must be type boolean, not type uuid"

### ISSUE THREAD

**Issue by alexandredev3** [typeorm/typeorm#7355]
## Issue Description
I'm trying to do a leftJoin on a posts table, the posts table is related to the likes table and this likes table is related to the users table, but it returns "QueryFailedError: argument of AND must be type boolean, not type uuid" , I'm using NestJS and GraphQL.

### Expected Behavior
returns in this format 
```"data": {
  "getPosts": [
    {
      "id": "60353bc1-7b8f-4eff-bcd2-048927fe93eb",
      "title": "Node.JS GraphQL",
      "description": "building a GraphQL API in NodeJS",
      "likes_count": 1,
      "likes": [
        "user": {
          "id": "95be0001-9937-4f66-ac35-c287efb7d817",
          "name": "Alexandre"
        }
      ],
      "user": {
        "id": "95be0001-9937-4f66-ac35-c287efb7d817",
        "name": "Alexandre"
      }
    }
  ]
}
```

### Actual Behavior

```
"errors": [
    {
      "message": "argument of AND must be type boolean, not type uuid",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getPosts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "argument of AND must be type boolean, not type uuid",
          "length": 125,
          "name": "QueryFailedError",
          "severity": "ERROR",
          "code": "42804",
          "position": "828",
          "file": "parse_coerce.c",
          "line": "1156",
          "routine": "coerce_to_boolean",
          "query": "SELECT \"posts\".\"id\" AS \"posts_id\", \"posts\".\"title\" AS \"posts_title\", \"posts\".\"description\" AS \"posts_description\", \"posts\".\"likes_count\" AS \"posts_likes_count\", \"posts\".\"author_id\" AS \"posts_author_id\", \"posts\".\"created_at\" AS \"posts_created_at\", \"posts\".\"updated_at\" AS \"posts_updated_at\", \"user\".\"id\" AS \"user_id\", \"user\".\"name\" AS \"user_name\", \"user\".\"email\" AS \"user_email\", \"user\".\"password\" AS \"user_password\", \"user\".\"created_at\" AS \"user_created_at\", \"user\".\"updated_at\" AS \"user_updated_at\", \"like\".\"id\" AS \"like_id\", \"like\".\"post_id\" AS \"like_post_id\", \"like\".\"user_id\" AS \"like_user_id\", \"like\".\"created_at\" AS \"like_created_at\", \"like\".\"updated_at\" AS \"like_updated_at\" FROM \"posts\" \"posts\" LEFT JOIN \"users\" \"user\" ON \"user\".\"id\"=\"posts\".\"author_id\"  LEFT JOIN \"likes\" \"like\" ON \"like\".\"post_id\"=\"posts\".\"id\" AND (\"like\".\"user_id\")",
          "parameters": [],
          "stacktrace": [
            "QueryFailedError: argument of AND must be type boolean, not type uuid",
            "    at new QueryFailedError (/home/alexandre/www/started-nestjs/backend/node_modules/typeorm/error/QueryFailedError.js:11:28)",
            "    at PostgresQueryRunner.<anonymous> (/home/alexandre/www/started-nestjs/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)",
            "    at step (/home/alexandre/www/started-nestjs/backend/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)",
            "    at Object.throw (/home/alexandre/www/started-nestjs/backend/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)",
            "    at rejected (/home/alexandre/www/started-nestjs/backend/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### Steps to Reproduce

``` typescript
// User Entity

@ObjectType()
@Entity('likes')
export default class Like {
  @Field()
  @PrimaryGeneratedColumn()
  id: string;

  @Field()
  @Column('uuid')
  post_id: string;

  @Field()
  @Column('uuid')
  user_id: string;

  @Field(() => User)
  @ManyToOne(() => User, (user) => user.like, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Field(() => Post)
  @ManyToOne(() => Post, (post) => post.likes, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'post_id' })
  @JoinTable()
  posts: Post;

  @Field()
  @CreateDateColumn()
  created_at: Date;

  @Field()
  @UpdateDateColumn()
  updated_at: Date;
}
```
```typescript
// Post Entity

@Entity('posts')
@ObjectType()
export default class Post {
  @Field()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Field()
  @Column('varchar')
  title: string;

  @Field()
  @Column('varchar')
  description: string;

  @Field()
  @Column('decimal', { default: 0 })
  likes_count: number;

  @Field(() => User)
  @ManyToOne(() => User, (user) => user.posts, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'author_id' })
  user: User;

  @Field(() => [Like])
  @OneToMany(() => Like, (like) => like.posts, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'post_id' })
  @JoinTable()
  likes: Like[];

  @Field()
  @Column('uuid')
  author_id: string;

  @Field()
  @CreateDateColumn()
  created_at: Date;

  @Field()
  @UpdateDateColumn()
  updated_at: Date;
}
```

```typescript
// Like Entity

@ObjectType()
@Entity('likes')
export default class Like {
  @Field()
  @PrimaryGeneratedColumn()
  id: string;

  @Field()
  @Column('uuid')
  post_id: string;

  @Field()
  @Column('uuid')
  user_id: string;

  @Field(() => User)
  @ManyToOne(() => User, (user) => user.like, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Field(() => Post)
  @ManyToOne(() => Post, (post) => post.likes, {
    cascade: ['insert', 'update'],
  })
  @JoinColumn({ name: 'post_id' })
  @JoinTable()
  posts: Post;

  @Field()
  @CreateDateColumn()
  created_at: Date;

  @Field()
  @UpdateDateColumn()
  updated_at: Date;
}
```

```typescript
// Post Service

class PostService {
  constructor(
    @InjectRepository(Post) private postRepository: Repository<Post>
  ) {}

  public async getPosts(): Promise<Post[]> {
    const posts = await this.postRepository
      .createQueryBuilder('posts')
      .leftJoinAndSelect('posts.user', 'user')
      .leftJoinAndSelect('posts.likes', 'like', 'like.user')
      .loadRelationCountAndMap('posts.likes_count', 'posts.likes')
      .getMany();

    console.log(classToClass(posts[0].likes));

    return posts;
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Xubuntu  20.04    |
| Node.js version     | v14.15.4 | 
| Typescript version  | ^4.0.5 | 
| TypeORM version     |^0.2.30 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by alexandredev3** [comment]
I solved this problem in another way, making a query in the likes table and returning the posts that make relationship with the likes.

```
const likes = await this.likeRepository.find({
  where: {
    post_id,
  },
  relations: ['user'],
});

return likes;
```
