### ISSUE TITLE
Custom extended Repository<T> is always giving "Cannot read property 'find' of undefined."  this.manager is undefined in typeorm's base Repository class...

### ISSUE THREAD

**Issue by rw3iss** [typeorm/typeorm#7370]
## Issue Description

When extending the base Repository<Model> class, and using the extended class in other files, it always gives:

```TypeError: Cannot read property 'find' of undefined.```

With simple class extension:
```
export class TestRepository extends Repository<Test> {}
```

I'm using NestJS, and following their custom Repository examples to extend the traditional typeorm Repository<Model>:
https://docs.nestjs.com/techniques/database#custom-repository

### Expected Behavior

The call to .find() (or any other base method) should just delegate to the base/regular Repository<Model> methods, and not give the undefined error.

### Actual Behavior

When extending the class and calling .find([]), it gives this undefined error.

Error:
```
TypeError: Cannot read property 'find' of undefined
    at TestRepository.Repository.find (/home/rw3iss/Sites/timeline/api/node_modules/typeorm/repository/Repository.js:154:29)
    at TestService.search (/home/rw3iss/Sites/timeline/api/dist/modules/test/test.service.js:44:42)
    at TestController.search (/home/rw3iss/Sites/timeline/api/dist/modules/test/test.controller.js:46:39)
    at /home/rw3iss/Sites/timeline/api/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/rw3iss/Sites/timeline/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /home/rw3iss/Sites/timeline/api/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

The extended class seems to be defined according the correct rules, and it does not override the base methods (yet). 

I took a look within the node_modules/typeorm/repository/Repositoryjs: 154 file... and see that it's property "this.manager" is always undefined. 

### Steps to Reproduce

1. Create a new ModelRepository class, and extend from typeorm's Repository<Model>

```typescript
import { EntityRepository, Repository } from 'typeorm';
import { Test } from './test.model';
import { Injectable } from '@nestjs/common';

@EntityRepository(Test)
export class TestRepository extends Repository<Test> {
}
```

2. Use the class in any other file:
```typescript
import { Request } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { TestRepository } from './test.repository';
import { Test } from './test.model';

export class TestService {

    testRepository: TestRepository;

    public constructor() {
        this.testRepository = new TestRepository();
    }

    // injection this way also gives the same error:
    //public constructor(@InjectRepository(TestRepository) private testRepository: TestRepository) {
    //}

    public async search(@Request() req): Promise<Array<Test>> {
        return await this.testRepository.find({  // throws undefined here <===========
        });
    }
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 20.10 |
| Node.js version     | vX14.15.4 |
| Typescript version  | v4.1.5 | 
| TypeORM version     | v0.2.31 |
| NestJS version      | v7.5.1 |

### Additional Context

Some other have reported this error on the NestJS github, and were told to report it here instead.
https://github.com/nestjs/typeorm/issues/317

I took a look at the base Repository.js file, and 'this.manager' is the property that is undefined. It seems the RepositoryFactory is not setting this in it's create() call. Furthermore, I searched the typeorm library for a call to 'RepositoryFactory.create', but do not see anything.
I also took a look at the Typeorm custom repositories page:
https://typeorm.io/#/custom-repository
... and it seems perhaps the injection logic isn't properly instantiating the extended repository using getCustomRepository(CustomRepository) (just a guess), within NestJS, perhaps...

### Relevant Database Driver(s)

- [x] `mysql`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by rw3iss** [comment]
Seems the issue was that I was including the custom repository in my @Module exports, which is supposed to be delegated to typeorm and not handled by Nest so much.
