### ISSUE TITLE
Saving with Many-to-Many relation and { cascade: true } causes duplicate key error

### ISSUE THREAD

**Issue by EkiGui** [typeorm/typeorm#7395]
## Issue Description

Hi, I'm encountering a problem on a fairly simple use case, but I'm still not sure if it's a bug, a misunderstanding on my part, or just the expected behavior. If it's not a bug, maybe some details are missing in the documentation because I've gone through it in detail.

I have 2 entities (_Game_ and _Category_) linked with a Many-to-Many relation :

```ts
@Entity()
export class Game {
  @PrimaryColumn()
  id: number;

  @PrimaryColumn()
  name: string;

  @ManyToMany(
    () => Category,
    category => category.games,
    { eager: true, cascade: true } // Notice de cascade: true option
  )
  @JoinTable()
  categories: Category[];
}
```

```ts
@Entity()
export class Category {
  @PrimaryColumn()
  id: number;

  @PrimaryColumn()
  name: string;

  @ManyToMany(
    () => Game,
    game => game.categories
  )
  games: Game[];
}
```

I load my initial data by scraping some information on a website, which is like doing the following sequence:

```ts
// This is the data i am scraping around (in real life, I get one game at a time)
const games = [
  {
    id: 1,
    name: 'Game 1',
    categories: [
      {
        id: 1,
        name: 'Category 1'
      },
      {
        id: 2,
        name: 'Category 2'
      }
    ]
  },
  {
    id: 2,
    name: 'Game 2',
    categories: [
      {
        id: 1,
        name: 'Category 1'
      }
    ]
  }
]

// And I try to save them in the database as follows (simplified syntax):
games.forEach(g => {

  const game = new Game()
  game.id = g.id;
  game.name = g.name

  item.categories.forEach(c => {

    const category = new Category()
    category.id = c.id
    category.name = c.name

    game.categories.push(category)
  })

  gamesRepository.save(game)
})
```

With this approach, _Game 1_ is saved in db with its 2 relations and _Category 1_ and _Category 2_ are created because they did not exist in the categories table (according to `cascade: true` option), but when it comes to saving _Game 2_, the cascading process tries to re-create _Category 1_, although it already exists, which leads to a duplicate key error.

Shouldn't TypeORM see that _Category 1_ already exists and not try to insert it ?

### Expected Behavior

When saving _Game 2_, I expect the `save` operation to save both game and relation, but not to try to insert an other _Category 1_, as it already exists.

### Actual Behavior

When saving _Game 2_, the `save` operation tries to insert _Category 1_ again, resulting in a duplicate key error:

```
error: error: duplicate key value violates unique constraint "PK_7e79a17df5fe348e5f8868a75ae"
    at Connection.parseE (/Users/guillaumemartin/Projects/GM/boardgameblink/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/Users/guillaumemartin/Projects/GM/boardgameblink/node_modules/pg/lib/connection.js:380:19)
    at TLSSocket.<anonymous> (/Users/guillaumemartin/Projects/GM/boardgameblink/node_modules/pg/lib/connection.js:116:22)
```

### My Environment

| Dependency          | Version       |
| ---                 | ---           |
| Operating System    | MacOS 10.13.6 |
| Node.js version     | v12.13.0      | 
| Typescript version  | v3.8.3        | 
| TypeORM version     | v0.2.24       | 
| NestJS version      | v7.0.0        | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by robertmain** [comment]
Yeah, I'm finding this too. It looks to be because TypeORM creates a unique constraint each individual column of the join table. That is to say, given the following example:

### Recipes:
| id  | name  |
|---|---|
| 1  | Chocolate cake  |
| 2  | Carrot cake  |
|  3 |  Red velvet cake |


### Ingredients
| id  | name  |
|---|---|
| 1  | Flour  |
| 2  | Eggs  |
|  3 |  Sugar |

### Join Table
| recipeId  | ingredientId  | comment |
|---|---|---|
|  1|  1 | This will work because these values are unique to the column |
|  2|  1 | This will not work because the row above already has 1. That means that only one recipe could ever contain flour(or this specific version of flour anyway |

**Comment by EkiGui** [comment]
Thank you for sharing your feedback on this error, but I'm still not completely sure that the origin of the problem has been identified.

Indeed, in my case the error does not occur in the Join table, but when TypeORM tries to insert category 2 again in the Category table (which would correspond to an Ingredient in your example), even though this last one already exists.

I figured the error could be due to the use of composite Primary Keys, so I tried with simple Primary Keys, but it didn't change anything...

I turn to the QueryBuilder in the meantime!

**Comment by robertmain** [comment]
Ah, my apologies. I think I must've misunderstood your issue in that case. Out of interest, can you tell me how you switched the join table key type? I wasn't aware that this was an option

**Comment by EkiGui** [comment]
> Out of interest, can you tell me how you switched the join table key type?

In fact I did not modify the join table key type, what I meant is that instead of having 2 `@PrimaryColumn`s in my models I kept only one (the `id`). The `name` attribute becoming a regular `@Column`. I thought that might be what prevented TypeORM from finding the already existing Category.

**Comment by Alfagun74** [comment]
I have the same problem. [I'll explain it using the simple Example in TypeOrm Documentation](https://orkhan.gitbook.io/typeorm/docs/many-to-many-relations#saving-many-to-many-relations)

(Assuming that Category.name is {unique: true})

```ts
const category1 = new Category()
category1.name = "animals"

const question = new Question()
question.title = "dogs"
question.text = "who let the dogs out?"
question.categories = [category1]
await dataSource.manager.save(question)
```

so now we created a question and a category with one call right? Great, lets create another question that is also in the animals category:
```ts
const category1 = new Category()
category1.name = "animals"

const question = new Question()
question.title = "cats"
question.text = "who let the cats in?"
question.categories = [category1]
await dataSource.manager.save(question)
```

Result:
`ERROR:  duplicate key value violates unique constraint "UQ_66df34da7fb037e24fc7fee642b"`

What is the problem here? why does it create a new category again?

**Comment by ffastym** [comment]
Any updates? faced with the same issue

**Comment by derSoerrn95** [comment]
+1

**Comment by akash-pixel** [comment]
+1

**Comment by esafaraliyev-plusde** [comment]
+1

**Comment by yosemiteyss** [comment]
Having the same issue. Any updates?

**Comment by mortezakarimi** [comment]
+1

**Comment by owl-app** [comment]
+1

**Comment by ali-zali-dev** [comment]
+1

**Comment by clintonb** [comment]
@ali-zali-dev it seems you're working on a fix. Any plans to open a pull request?
