### ISSUE TITLE
Inserted record in MySQL not being returned when using a custom primary key column

### ISSUE THREAD

**Issue by mnengwa** [typeorm/typeorm#7470]
### A new record is inserted successfully into the database, but TypeORM throws an error when attempting to retrieve the inserted record.

```
[Nest] 9084   - 15/03/2021, 11:17:47   [ExceptionsHandler] Cannot update entity because entity id is not set in the entity. +331142ms
Error: Cannot update entity because entity id is not set in the entity.
    at C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\query-builder\ReturningResultsEntityUpdator.js:128:39
    at Array.map (<anonymous>)
    at ReturningResultsEntityUpdator.<anonymous> (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\query-builder\ReturningResultsEntityUpdator.js:122:46)
    at step (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at ReturningResultsEntityUpdator.insert (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\query-builder\ReturningResultsEntityUpdator.js:87:24)
    at InsertQueryBuilder.<anonymous> (C:\Users\Mnengwa\workspace\kodisha\kodisha-web-api\node_modules\typeorm\query-builder\InsertQueryBuilder.js:105:76)
```

### Steps to Reproduce
1. Define an entity
```typescript
@Entity({ name: 'users' })
export class User {
  @Column({
    type: 'binary',
    length: 16,
    select: false,
    primary: true,
    default: () => `(UUID_TO_BIN(UUID(), 1))`,
  })

  id: string;
  @Index()
  @Column({ type: 'varchar', length: 225, nullable: false })
  name: string;

  @Column({ type: 'varchar', length: 15, unique: true, nullable: false })
  MSISDN: string;

  @Column({ type: 'varchar', length: 225, unique: true, nullable: false })
  email_address: string;

  @Column({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP' })
  created_at: Date;

  @Column({ type: 'datetime', nullable: true, onUpdate: 'CURRENT_TIMESTAMP' })
  updated_at: Date;
}
```

2. Define a service for the entity
```typescript
@Injectable()
export class UserService {
  constructor(
    @InjectRepository(User)
    private usersRepository: Repository<User>,
  ) {}

  create(user: DeepPartial<User>): Promise<User> {
    return this.usersRepository
      .createQueryBuilder()
      .insert()
      .values({ ...user})
      .execute();
  }
}
```

3. Attempt to insert a record

4. An error is thrown as shown above

5. Check the database using ```SELECT * FROM users;```

6. Observe that a record is inserted but TypeORM was unable to retrieve the record

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 10 pro     |
| Node.js version     | v14.15.4 |
| Typescript version  | v4.2.3| 
| TypeORM version     |  v0.2.31 | 

### Additional Context
The same issue arises when the ```..save()``` method is used

When I insert a record with a raw SQL query:
```typescript
create(account: CreateAccountDto): Promise<Account> {
    const values = Object.values(account);
    const columns = Object.keys(account).join(', ');
    const params = Object.keys(account)
      .map((x) => '?')
      .join(', ');

    const result = this.usersRepository.query(
      `INSERT INTO accounts (${columns}) VALUES (${params});`,
      values,
    );

    console.log(result);
    return result;
```

This is what gets returned:
```JSON
{
        "fieldCount": 0,
        "affectedRows": 1,
        "insertId": 0,
        "info": "",
        "serverStatus": 2,
        "warningStatus": 0
    }
```

Lastly are we able to define some sort of getter for such a primary key, in the column decorator?

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tonytoth** [comment]
Does not work either if you try this way:
```
@PrimaryColumn({
        type: 'binary',
        length: 16,
        default: () => `(UUID_TO_BIN(UUID(), 1))`,
    })
    id: string;
```
But this migth be related to this issue: https://github.com/typeorm/typeorm/issues/3187

**Comment by juliengbt** [comment]
@tonytoth Did you find a workaround ?

**Comment by tonytoth** [comment]
Unfortunately, no. I had to drop the idea of uuid.

**Comment by HakamaObi** [comment]
Hi.
i have writen some helper functions that transforms the uuid to the same byte format as mysql 8 does, so you can use a transformer in the entity.
currently it's in develop but working fine until now


helper functions
`export function parseBytes2UUID(bytes: Buffer) {
  if (bytes.length !== 16) {
    throw new Error('no se puede convertir ese tipo de dato a un uuid');
  }

  return bytes.reduce((acum, curr, idx) => {
    acum += ('00' + curr.toString(16)).slice(-2);
    if (idx === 3 || idx === 5 || idx === 7 || idx === 9) {
      acum += '-';
    }
    return acum;
  }, '');
}

export function parseUUID2Bytes(uuid: string) {
  const buffer = Buffer.alloc(16);
  const hexUUID = uuid.replace(/-/g, '');
  for (let i = 0; i < 16; i++) {
    const idx = 2 * i;
    const hexbyte = hexUUID.substring(idx, idx + 2);
    buffer.writeUInt8(parseInt(hexbyte, 16), i);
  }
  return buffer;
}

export function rearrangeBytes4Storage(bytes: Buffer) {
  if (bytes.length !== 16) {
    throw new Error('El byteArray es incorrecto');
  }
  const rearranged = Buffer.alloc(bytes.length);
  rearranged[0] = bytes[6];
  rearranged[1] = bytes[7];
  rearranged[2] = bytes[4];
  rearranged[3] = bytes[5];
  rearranged[4] = bytes[0];
  rearranged[5] = bytes[1];
  rearranged[6] = bytes[2];
  rearranged[7] = bytes[3];
  for (let i = 8; i < bytes.length; i++) {
    rearranged[i] = bytes[i];
  }
  return rearranged;
}

export function rearrangeBytes4Dispĺay(bytes: Buffer) {
  if (bytes.length !== 16) {
    throw new Error('El byteArray es incorrecto');
  }
  const rearranged = Buffer.alloc(bytes.length);
  rearranged[0] = bytes[4];
  rearranged[1] = bytes[5];
  rearranged[2] = bytes[6];
  rearranged[3] = bytes[7];
  rearranged[4] = bytes[2];
  rearranged[5] = bytes[3];
  rearranged[6] = bytes[0];
  rearranged[7] = bytes[1];
  for (let i = 8; i < bytes.length; i++) {
    rearranged[i] = bytes[i];
  }
  return rearranged;
}

export function extractTimestamp(uuid: string) {
  const time_low = parseInt(uuid.substring(0, 8), 16);
  const time_mid = parseInt(uuid.substring(9, 13), 16);
  const time_hig = parseInt(uuid.substring(15, 18), 16);
  const big_timestamp = (time_hig * 2 ** 16 + time_mid) * 2 ** 32 + time_low;
  const epoch = big_timestamp / 10000 - 12219292800000;
  return epoch;
}
`

transformer
`import {
  parseBytes2UUID,
  parseUUID2Bytes,
  rearrangeBytes4Dispĺay,
  rearrangeBytes4Storage
} from './uuid-typeorm.helper';

interface Transformer<BASE, STORAGE = BASE> {
  to: (value: BASE) => STORAGE;
  from: (value: STORAGE) => BASE;
}

export const UUIDTransformer: Transformer<string, Buffer> = {
  to(value: string) {
    const bytes = parseUUID2Bytes(value);
    const rearranged = rearrangeBytes4Storage(bytes);
    return rearranged;
  },
  from: (value: Buffer) => {
    const rearranged = rearrangeBytes4Dispĺay(value);
    const uuid = parseBytes2UUID(rearranged);
    return uuid;
  }
};
`
