### ISSUE TITLE
syncronize:true throws QueryFailedError: column "user_alias" of relation "users" contains null values

### ISSUE THREAD

**Issue by mirajehossain** [typeorm/typeorm#7475]
## Issue Description
I have got QueryFailedError: column "user_alias" of relation "users" contains null values when I set `syncronize:true` in `ormconfig.js`

I set synchronize true because I have write @BeforeInsert() subscriber it does not work after migration, so that I  set to synchronize to sync database entities, but after set sync true it thorws error.
Here is my entities below
```
import {Entity, Column, ManyToMany, JoinTable, BeforeInsert} from 'typeorm';
import {BaseEntity} from './Base';
import {AuthGroup} from './AuthGroup';

export enum Status {
	ACTIVE = 'active',
	INACTIVE = 'inactive',
	SUSPENDED = 'suspended',
	ARCHIVED = 'archived'
}


@Entity('users')
export class User extends BaseEntity {

	@Column({
		unique: true,
	})
	user_alias: string;

	@Column({
		type: 'enum',
		enum: Status,
		default: Status.ACTIVE
	})
	status: Status;

	@Column({
		nullable: false
	})
	first_name: string;

	@Column()
	last_name: string;

	@Column()
	email: string;

	@Column()
	password: string;

	@Column()
	mobile: string;

	@Column({ type: 'jsonb', nullable: true})
	address: {};

	@Column({ nullable: true })
	blood_group: string;

	@Column({ nullable: true })
	nid: string;

	@Column({ nullable: true })
	birth_certificate: string;

	@Column({ nullable: true })
	profile_picture: string;

	@Column({ nullable: true, type: 'jsonb' })
	parents: {};

	@Column({ nullable: true, type: 'jsonb' })
	education: {};

	@ManyToMany(() => AuthGroup)
	@JoinTable({
		name: 'user_groups',
		joinColumn: {
			referencedColumnName: 'id',
			name: 'user_id'
		},
		inverseJoinColumn: {
			referencedColumnName: 'id',
			name: 'auth_group_id'
		}
	})
	groups: AuthGroup[];

	@BeforeInsert()
	private generateAlias() {
		console.log('executing before insert');
		this.user_alias = new Date().valueOf().toString();
		console.log(this.user_alias);
	}
}
```

### Expected Behavior

The expected behavior is in development when I set syncronize true, it should be sync successfully.

### Actual Behavior
throw QueryFailedError: column "user_alias" of relation "users" contains null values after syncronize true.

this is actual output in the console
```
 QueryFailedError: column "user_alias" of relation "users" contains null values
    at new QueryFailedError (/Users/mdalamin/Desktop/projects/my/smart-health-backend/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/mdalamin/Desktop/projects/my/smart-health-backend/src/driver/postgres/PostgresQueryRunner.ts:228:19)
    at step (/Users/mdalamin/Desktop/projects/my/smart-health-backend/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/Users/mdalamin/Desktop/projects/my/smart-health-backend/node_modules/tslib/tslib.js:122:57)
    at rejected (/Users/mdalamin/Desktop/projects/my/smart-health-backend/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      MacOS    |
| Node.js version     | v12.14.1 | 
| Typescript version  | v3.3.3333 | 
| TypeORM version     | v0.2.30 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nibravo** [comment]
Same issue here.

I try to create this simple entity:

`
@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn("uuid")
    id: string

    @Column({nullable: false,length: 200})
    name: string
}
`

but I get the same error

`
QueryFailedError: column "name" of relation "user" contains null values
    at PostgresQueryRunner.query (/<PROJECT_FOLDER>/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryRunner.executeQueries (/<PROJECT_FOLDER>/node_modules/src/query-runner/BaseQueryRunner.ts:659:13)
    at async PostgresQueryRunner.addColumn (/<PROJECT_FOLDER>/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:1115:9)
    at async PostgresQueryRunner.addColumns (/<PROJECT_FOLDER>/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:1129:13)
    at async RdbmsSchemaBuilder.addNewColumns (/<PROJECT_FOLDER>/node_modules/src/schema-builder/RdbmsSchemaBuilder.ts:823:13)
    at async RdbmsSchemaBuilder.executeSchemaSyncOperationsInProperOrder (/<PROJECT_FOLDER>/node_modules/src/schema-builder/RdbmsSchemaBuilder.ts:226:9)
    at async RdbmsSchemaBuilder.build (/<PROJECT_FOLDER>/node_modules/src/schema-builder/RdbmsSchemaBuilder.ts:95:13)
    at async DataSource.synchronize (/<PROJECT_FOLDER>/node_modules/src/data-source/DataSource.ts:335:9)
    at async DataSource.initialize (/<PROJECT_FOLDER>/node_modules/src/data-source/DataSource.ts:273:43) {
  query: 'ALTER TABLE "user" ADD "name" character varying(200) NOT NULL',
  parameters: undefined,
`

I'm running the project with `npx ts-node index.ts`, without building to `dist` folder (no dist/build folder exists), and I deleted all npm and npx cache.

OS: MacOS Ventura
nodejs: 16.19.1
typeorm: 0.3.16 (I also failed with 0.3.15)
Postgresql: 14.2

Issue #4498 its similar but it says this was solved, but didn't...

I read the _patch solution_ is to not use `nullable: false` columns and set a default value for it, which I think its a deal breaker...

Any clues on how can I have NOT NULL columns without the _patch solution_?
Thank you in advance
