### ISSUE TITLE
Unable to index a TEXT column

### ISSUE THREAD

**Issue by as-com** [typeorm/typeorm#749]
```typescript
@Entity({
	engine: "TokuDB"
})
export class [redacted] {
	@PrimaryColumn("int", { generated: true })
	id: number;

	@Column("text", { unique: true })
	source: string;
}
```

```
{ QueryFailedError: BLOB/TEXT column 'source' used in key specification without a key length
    at new QueryFailedError ([redacted]/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.onResult ([redacted]/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:197:45)
    at Query.Command.execute ([redacted]/node_modules/mysql2/lib/commands/command.js:30:12)
    at PoolConnection.Connection.handlePacket ([redacted]/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket ([redacted]/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart ([redacted]/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> ([redacted]/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
  code: 'ER_BLOB_KEY_WITHOUT_LENGTH',
  errno: 1170,
  sqlState: '#42000',
  name: 'QueryFailedError',
  query: 'CREATE TABLE `[redacted]` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `source` text NOT NULL UNIQUE) ENGINE=InnoDB',
  parameters: [] }
```

How can I specify a length for the index for a TEXT column?

(also, it appears it's creating the table with the wrong engine...)

**Comment by pleerock** [comment]
Something like this must work:

```ts
	@Column("text", { length: 1000, unique: true })
	source: string;
```

**Comment by pleerock** [comment]
I hope I answered your question.

**Comment by alfaproject** [comment]
This should be reopened. That's not the index length

**Comment by pleerock** [comment]
I guess this is a feature request for the following index signature?:

`ALTER TABLE products ADD INDEX `product_name_idx` (name(512));`

**Comment by alfaproject** [comment]
Yes, that would be the index length ^_^

**Comment by pleerock** [comment]
mm okay lets reopen this issue then. As usual, feel free to contribute :)

**Comment by galek** [comment]
Yep, the problem is actually in 2021.
```
  @Column( { type:'longtext',nullable: true, unique:true })
  canonicalUrl: string;
  ```
  Not work on MySQL 8, but is works on maria

**Comment by galek** [comment]
description of the problem: https://sc.link/50X

Solution:
```
  @Column({ type: 'varchar', nullable: true, unique: true, length: 768 })
```

**Comment by naorpeled** [comment]
Hey,
we're closing this issue as it's stale, 
feel free to ping if this issue still occurs
