### ISSUE TITLE
"useNewUrlParser": true . this options parse have some problem .

### ISSUE THREAD

**Issue by huaqingyi** [typeorm/typeorm#7542]
## my configuration .
```javascript
{ 
    type: 'mongodb',
    url: 'mongodb://username:password@host:port/?ssl=xxx&replicaSet=xxx&readPreference=xxx&retryWrites=xxx',
    useUnifiedTopology: true,
    useNewUrlParser: true,
    database: 'tags_pre',
    logging: false,
    synchronize: true,
    sslCA: [ <Buffer  ... > ],
    entities: [ 'app/**/entity/**/*.js' ],
}
```

## runtime output error message .
```javascript
entities: [ 'app/**/entity/**/*.js' ] }
atags   | [2021-04-07T07:36:38.035] [16] [ERROR] - { MongoServerSelectionError: connection <monitor> to ip:port timed out
atags   |     at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (/opt/tftags/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
atags   |     at ontimeout (timers.js:436:11)
atags   |     at tryOnTimeout (timers.js:300:5)
atags   |     at listOnTimeout (timers.js:263:5)
atags   |     at Timer.processTimers (timers.js:223:10)
atags   |   name: 'MongoServerSelectionError',
atags   |   reason:
atags   |    { type: 'Single',
atags   |      setName: null,
atags   |      maxSetVersion: null,
atags   |      maxElectionId: null,
atags   |      servers: {},
atags   |      stale: false,
atags   |      compatible: true,
atags   |      compatibilityError: null,
atags   |      logicalSessionTimeoutMinutes: null,
atags   |      heartbeatFrequencyMS: 10000,
atags   |      localThresholdMS: 15,
atags   |      commonWireVersion: null } }
```

## but i use this options don't error .
```javascript
{
    type: "mongodb",
    host: "XXX",
    username: "XXX",
    password: "XXX",
    port: number,
    ssl: true,
    replicaSet: "xxx",
    readPreference: "xxxx",
    sslValidate: true,
    logging: true,
    useUnifiedTopology: true,
    database: "xxx",
    sslCA: [ <Buffer  ... > ],
    entities: [ 'app/**/entity/**/*.js' ],
  }
```

**Comment by kevin-lindsay-1** [comment]
What is the problem?

**Comment by huaqingyi** [comment]
> What is the problem?

the configuration you used before will caused infinite timeout, the below configuration is right .
i think 'useNewUrlParser' cause this problem .

**Comment by tehdb** [comment]
I have the same issue with latest typeorm version 0.2.32, I downgraded to `"typeorm": "0.2.28"` and it seems to work

**Comment by alminde** [comment]
i'm also seeing this.

downgrading to 0.2.28 fixed it, but that's no fun.

anyone know what the underlying issue is?

**Comment by imnotjames** [comment]
So the issue exhibits in 0.2.29?

**Comment by imnotjames** [comment]
Potentially related - https://github.com/typeorm/typeorm/commit/6fa2df5ade71a3fee550e3c8fb7bcd7cd02080a8#diff-815ba40c56c4edb31c2cd63e2a75d0bf046d93831b4c2e7ea8f3c861d0cbb593

**Comment by ivanbajalovic** [comment]
Seems that the problem is present on `0.2.41`. After downgrading to `0.2.28` everything works fine.

**Comment by mohd-akram** [comment]
This option isn't supported anymore by MongoDB.
