### ISSUE TITLE
mysql orUpdate error

### ISSUE THREAD

**Issue by Skazakstan** [typeorm/typeorm#7585]
## Issue Description
Method orUpdate() with MySql driver ends with an error

### Expected Behavior
Insert a new Product entity or update some fields if already existing

### Actual Behavior
The output of the sql query generated is good (works in raw sql) but an error is triggered : 

```
  Error: Cannot update entity because entity id is not set in the entity.
      at .../src/query-builder/ReturningResultsEntityUpdator.ts:127:27
```

### Steps to Reproduce

1. Using insert()..orUpdate() with my entity
NB: insert() only throw an error 'ER_DUP_ENTRY' as expected

```typescript
import { Product } from '@entities'
import { Connection } from 'typeorm'

const product = await getProduct()

await connection
  .getRepository()
  .createQueryBuilder()
  .insert()
  .into(Product)
  .values(product)
  .orUpdate({
    overwrite: ['description']
  })
  .execute()
```
2. Raw sql generated is good
```sql
INSERT INTO `products`(`id`, `original_id`, `partner_id`, `warehouse_id`, `stock_quantity`, `sku`, `code`, `name`, `label`, `type`, `description`, `category`, `effective_start_date`, `effective_end_date`, `dluo`, `updated_at`, `created_at`, `deleted_at`) 
VALUES (DEFAULT, ?, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
ON DUPLICATE KEY UPDATE description = VALUES(description) 
-- PARAMETERS: [...]
```

3. But an error is triggered nonetheless
```error
  Error: Cannot update entity because entity id is not set in the entity.
      at .../src/query-builder/ReturningResultsEntityUpdator.ts:127:27
```

4. As a workaround, i was able to use the raw query (same as generated sql) which works fine
```typescript
...
await connection.query(`
  INSERT INTO products(id, original_id, partner_id, warehouse_id, stock_quantity, sku, code, name, label, type, description, category, effective_start_date, effective_end_date, dluo, updated_at, created_at, deleted_at)
  VALUES (DEFAULT, ?, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT)
  ON DUPLICATE KEY UPDATE 
    description = VALUES (description), 
    updated_at = NOW()
`, [...parameters...])
```

I am not 100% sure it is an actual bug ... (maybe I am doing something wrong ?)
Thanks for your time!

### My Environment

Serverless, Lambda
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macOs Big Sur v11.2.3     |
| Node.js version     | v12.17.0 | 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by alvaro-octal** [comment]
Had the same error, setting `id` to `null` seems to solve the issue

**Comment by HexMox** [comment]
Also meeting this problem.

The problem is caused by MySQL returns when orUpdate query ends:

```js
{
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  info: "",
  serverStatus: 3,
  warningStatus: 1,
}
```

And then, TypeORM will call `ReturningResultsEntityUpdator.prototype.insert` method to select just inserted entities. But it seems updated `entries` which merged MySQL returns（insertId is 0 above） still don't have  primary ID, so it throw an error.

![image](https://user-images.githubusercontent.com/5358537/124412648-91b4d880-dd81-11eb-97fb-f8c89a1a9ab7.png)

if u don't need use the primary id of inserted rows, u can try:

```js
await connection
  .getRepository()
  .createQueryBuilder()
  .insert()
  .into(Product)
  .values(product)
  .orUpdate({
    overwrite: ['description']
  })
  .updateEntity(false) // tell typeorm not to re-select data (maybe other things I don't know)
  .execute()
```
