### ISSUE TITLE
problem wirh many to many

### ISSUE THREAD

**Issue by misaku** [typeorm/typeorm#7613]
### Actual Behavior

I try to save one relation many to many if i dont create entity of table users_gas_stations it works
but if i use has this error:
```json
{
  "timestamp": "2021-05-04T01:10:08.332Z",
  "path": "/user",
  "error": {
    "message": "null value in column \"user_id\" of relation \"users_gas_stations\" violates not-null constraint",
    "length": 284,
    "name": "QueryFailedError",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (null, null, 2021-05-04 01:10:08.317232, 2021-05-04 01:10:08.317232).",
    "schema": "public",
    "table": "users_gas_stations",
    "column": "user_id",
    "file": "execMain.c",
    "line": "1965",
    "routine": "ExecConstraints",
    "query": "INSERT INTO \"users_gas_stations\"(\"user_id\", \"gas_station_id\", \"created_at\", \"updated_at\") VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING \"created_at\", \"updated_at\"",
    "parameters": []
  }
}
```

### Steps to Reproduce

```typescript
// USER ENTITY ------------------------------------------------------------------------------------

  @ManyToMany<GasStation>(() => GasStation, (gastation) => gastation.users)
  @JoinTable({
    name: 'users_gas_stations',
    joinColumn: {
      name: 'user_id',
      referencedColumnName: 'id',
    },
    inverseJoinColumn: {
      name: 'gas_station_id',
      referencedColumnName: 'id',
    },
  })
  
// GASTATION ENTITY------------------------------------------------------------------------------------
  @ManyToMany<User>(() => User, (user) => user.gasStations)
  public users: User[];

// ENTITY USERS GAS STATIONS------------------------------------------------------------------------------------
@Entity('users_gas_stations')
export class UserGasStation extends BaseEntity {
  @PrimaryColumn({ type: 'uuid', name: 'user_id' })
  public userId: string;

  @PrimaryColumn({ type: 'uuid', name: 'gas_station_id' })
  public gasStationId: string;

  @CreateDateColumn({ name: 'created_at' })
  public createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  public updatedAt: Date;
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.16.1 | 
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nikelborm** [comment]
My problem is exactly the same

I have postgres too
My versions:
```
typeorm: 0.3.6 
@nestjs/typeorm: 8.0.3
node: v16.16.0
```
I described it [here](https://github.com/typeorm/typeorm/issues/3801#issuecomment-1272355289)

---

I have user model like this:
```typescript
@Entity({ name: 'user' })
export class User {
  @PrimaryGeneratedColumn({ name: 'user_id' })
  id!: number;

  @ManyToMany(
    () => AccessScope,
    (accessScope) => accessScope.usersWithThatAccessScope,
  )
  @JoinTable({
    name: 'user_to_access_scope',
    joinColumn: { name: 'user_id' },
    inverseJoinColumn: { name: 'access_scope_id' },
  })
  accessScopes!: AccessScope[];

  @OneToMany(
    () => UserToAccessScope,
    (userToAccessScope) => userToAccessScope.user,
  )
  userToAccessScopeRelations!: UserToAccessScope[];
  
    // other fields
}
```

and access scope model:
```typescript
@Entity({ name: 'access_scope' })
export class AccessScope {
  @PrimaryGeneratedColumn({ name: 'access_scope_id' })
  id!: number;

  @ManyToMany(() => User, (user) => user.accessScopes)
  usersWithThatAccessScope!: User[];

  @OneToMany(
    () => UserToAccessScope,
    (userToAccessScope) => userToAccessScope.accessScope,
  )
  userToAccessScopeRelations!: UserToAccessScope[];

  // other fields
}
```

And model that connect both: 

```typescript
@Entity({ name: 'user_to_access_scope' })
export class UserToAccessScope {
  @ManyToOne(() => User, (user) => user.userToAccessScopeRelations, {
    nullable: false,
  })
  @JoinColumn({ name: 'user_id' })
  user!: User;

  @Column({
    name: 'user_id',
    primary: true,
    nullable: false,
  })
  userId!: number;

  @ManyToOne(
    () => AccessScope,
    (accessScope) => accessScope.userToAccessScopeRelations,
    { nullable: false },
  )
  @JoinColumn({ name: 'access_scope_id' })
  accessScope!: AccessScope;

  @Column({
    name: 'access_scope_id',
    primary: true,
    nullable: false,
  })
  accessScopeId!: number;
}
```

My code tries to insert accessScope, then user, then updates accessScope's field `usersWithThatAccessScope`.
Third step, as you can guess, fails. 

```typescript
const systemAdminScope = await this.accessScopeRepo.save({
  type: AccessScopeType.SYSTEM_ADMIN,
});
console.log('systemAdminScope: ', systemAdminScope);

const defaultUser = await this.userRepo.save({
  email: 'asd@asd.asd',
  lastName: 'Такой-тов',
  firstName: 'Такой-то',
  patronymic: 'Такой-тович',
  gender: 'male',
  password: 'asdasdasd',
});
console.log('defaultUser: ', defaultUser);

await this.accessScopeRepo.save({
  id: systemAdminScope.id,
  usersWithThatAccessScope: [defaultUser],
});
```

[solution in this example](https://github.com/typeorm/typeorm/issues/2121#issuecomment-788152519) does not help, because there mentioned not many-to-many, but many-to-one relation. I tried anyway, and it didn't help

output I get:

```
backend  | newEntity:  { type: 'superAdmin' }
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "access_scope"("type", "created_at", "updated_at") VALUES ($1, DEFAULT, DEFAULT) RETURNING "access_scope_id", "created_at", "updated_at" -- PARAMETERS: ["superAdmin"]
backend  | query: COMMIT
backend  | systemAdminScope:  {
backend  |   type: 'superAdmin',
backend  |   id: 26,
backend  |   createdAt: 2022-10-08T16:28:26.865Z,
backend  |   updatedAt: 2022-10-08T16:28:26.865Z
backend  | }
backend  | newEntity:  {
backend  |   email: 'asd@asd.asd',
backend  |   lastName: 'Такой-тов',
backend  |   firstName: 'Такой-то',
backend  |   patronymic: 'Такой-тович',
backend  |   gender: 'male',
backend  | }
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "user"("first_name", "last_name", "email", "salt", "password_hash", "patronymic", "gender", "phone", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, DEFAULT, DEFAULT, DEFAULT) RETURNING "user_id", "created_at", "updated_at" -- PARAMETERS: ["Такой-то","Такой-тов","asd@asd.asd","eaedd02b7a0b4e4505c35bcf92b8db2372e99b3e55324e481c2514ee49e46b2c575fa937d4fa4d06b0ed1cf8226f822fda277108a7d8859be2ecb477e5d8d180","74227546f2147f15953a47ef09688ced62a95d287bb563ecfd70ab949eec0008","Такой-тович","male"]
backend  | query: COMMIT
backend  | defaultUser:  {
backend  |   email: 'asd@asd.asd',
backend  |   lastName: 'Такой-тов',
backend  |   firstName: 'Такой-то',
backend  |   patronymic: 'Такой-тович',
backend  |   gender: 'male',
backend  |   phone: null,
backend  |   id: 12,
backend  |   createdAt: 2022-10-08T16:28:26.888Z,
backend  |   updatedAt: 2022-10-08T16:28:26.888Z
backend  | }
backend  | before repo.save UpdateEntity: {
backend  |   id: 26,
backend  |   usersWithThatAccessScope: [
backend  |     {
backend  |       email: 'asd@asd.asd',
backend  |       lastName: 'Такой-тов',
backend  |       firstName: 'Такой-то',
backend  |       patronymic: 'Такой-тович',
backend  |       gender: 'male',
backend  |       phone: null,
backend  |       id: 12,
backend  |       createdAt: 2022-10-08T16:28:26.888Z,
backend  |       updatedAt: 2022-10-08T16:28:26.888Z
backend  |     }
backend  |   ]
backend  | }
backend  | query: SELECT "AccessScope"."access_scope_id" AS "AccessScope_access_scope_id", "AccessScope"."type" AS "AccessScope_type", "AccessScope"."created_at" AS "AccessScope_created_at", "AccessScope"."updated_at" AS "AccessScope_updated_at" FROM "access_scope" "AccessScope" WHERE "AccessScope"."access_scope_id" IN ($1) -- PARAMETERS: [26]
backend  | query: SELECT "AccessScope_usersWithThatAccessScope_rid"."user_id" AS "user_id", "AccessScope_usersWithThatAccessScope_rid"."access_scope_id" AS "access_scope_id" FROM "user" "user" INNER JOIN "user_to_access_scope" "AccessScope_usersWithThatAccessScope_rid" ON ("AccessScope_usersWithThatAccessScope_rid"."access_scope_id" = $1 AND "AccessScope_usersWithThatAccessScope_rid"."user_id" = "user"."user_id") ORDER BY "AccessScope_usersWithThatAccessScope_rid"."user_id" ASC, "AccessScope_usersWithThatAccessScope_rid"."access_scope_id" ASC -- PARAMETERS: [26]
backend  | query: START TRANSACTION
backend  | query: INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
postgres | 2022-10-08 19:28:26.915 MSK [133] ERROR:  null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
postgres | 2022-10-08 19:28:26.915 MSK [133] DETAIL:  Failing row contains (null, null).
postgres | 2022-10-08 19:28:26.915 MSK [133] STATEMENT:  INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
backend  | query failed: INSERT INTO "user_to_access_scope"("user_id", "access_scope_id") VALUES (DEFAULT, DEFAULT)
backend  | error: error: null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
backend  |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
backend  |     at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
backend  |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
backend  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
backend  |     at Socket.emit (node:events:527:28)
backend  |     at addChunk (node:internal/streams/readable:315:12)
backend  |     at readableAddChunk (node:internal/streams/readable:289:9)
backend  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
backend  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
backend  |   length: 232,
backend  |   severity: 'ERROR',
backend  |   code: '23502',
backend  |   detail: 'Failing row contains (null, null).',
backend  |   hint: undefined,
backend  |   position: undefined,
backend  |   internalPosition: undefined,
backend  |   internalQuery: undefined,
backend  |   where: undefined,
backend  |   schema: 'public',
backend  |   table: 'user_to_access_scope',
backend  |   column: 'user_id',
backend  |   dataType: undefined,
backend  |   constraint: undefined,
backend  |   file: 'execMain.c',
backend  |   line: '1883',
backend  |   routine: 'ExecConstraints'
backend  | }
backend  | query: ROLLBACK
backend  | 
backend  | /app/src/driver/postgres/PostgresQueryRunner.ts:299
backend  |             throw new QueryFailedError(query, parameters, err)
backend  |                   ^
backend  | QueryFailedError: null value in column "user_id" of relation "user_to_access_scope" violates not-null constraint
backend  |     at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
backend  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
backend  |     at InsertQueryBuilder.execute (/app/src/query-builder/InsertQueryBuilder.ts:161:33)
backend  |     at SubjectExecutor.executeInsertOperations (/app/src/persistence/SubjectExecutor.ts:428:42)
backend  |     at SubjectExecutor.execute (/app/src/persistence/SubjectExecutor.ts:137:9)
backend  |     at EntityPersistExecutor.execute (/app/src/persistence/EntityPersistExecutor.ts:194:21)
backend  |     at updateOneWithRelations (/app/src/tools/repo/updateOneWithRelations.ts:16:16)
backend  |     at AccessScopeRepo.updateOneWithRelations (/app/src/modules/infrastructure/repo/accessScope.repo.ts:33:12)
backend  |     at MockDataUseCase.fillDBScript (/app/src/mock/mockData.useCase.ts:50:5)
backend  |     at MockDataUseCase.executeMock (/app/src/mock/mockData.useCase.ts:27:5)
```

**Comment by nikelborm** [comment]
@misaku I wonder if you found a solution for this?

**Comment by nikelborm** [comment]
BTW, I have repo that reproduce this problem

**Comment by nikelborm** [comment]
```typescript
await this.accessScopeRepo.save({
  id: systemAdminScope.id,
  userToAccessScopeRelations: [
    {
      userId: defaultUser.id,
    },
  ],
});
```

It works, but only with updating OneToMany property userToAccessScopeRelations

**Comment by misaku** [comment]
> @misaku I wonder if you found a solution for this?

yeah i change to prisma =)
and no more problem.

its sad but its true
