### ISSUE TITLE
Migration generation is failing due to missing SHIM function `looksLikeNumber`

### ISSUE THREAD

**Issue by JCaraballo113** [typeorm/typeorm#7678]
## Issue Description
Migration creation seems to be broken due to missing SHIM function
### Expected Behavior
Migration creation should work

### Actual Behavior
Migrations are not being created due to missing SHIM function

```
/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:2804
            if (shim$1.Parser.looksLikeNumber(arg) &&
                              ^
TypeError: shim$1.Parser.looksLikeNumber is not a function
    at Object.Yargs.self._parsePositionalNumbers (/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:2804:31)
    at Object.Yargs.self._postProcess (/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:2787:25)
    at Object.runCommand (/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:439:19)
    at Object.parseArgs [as _parseArgs] (/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/app/node_modules/typeorm/node_modules/yargs/build/index.cjs:2651:25)
    at Object.<anonymous> (/app/node_modules/typeorm/cli.js:43:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```
### Steps to Reproduce

1. Try to generate a migration using `npm run typeorm:migration:create` or whatever you use

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows | Mac  |
| Node.js version     | vX14.17.0| 
| Typescript version  | v4.23 | 
| TypeORM version     | v0.2.32| 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by naziks** [comment]
Same here
