### ISSUE TITLE
Left join on clause is different in the count query when calling Query Builder getManyAndCount() (after 0.2.33 upgrade)

### ISSUE THREAD

**Issue by ebelyaev** [typeorm/typeorm#7707]
## Issue Description

After upgrading to 0.2.33, the count query for one of our queries is no longer working when calling Query Builder getManyAndCount().  One of the left join on clause is different in the count query.  Here is the select query:
```
 select
	"scripts"."id" as "scripts_id",
	"scripts"."hcl" as "scripts_hcl",
	"scripts"."dateCreated" as "scripts_dateCreated",
	"scripts"."dateUpdated" as "scripts_dateUpdated",
	"scripts"."rootHcl" as "scripts_rootHcl",
	"scripts"."parentHcl" as "scripts_parentHcl",
	"scripts"."min" as "scripts_min",
	"scripts"."max" as "scripts_max",
	"scripts"."aliasHcl" as "scripts_aliasHcl",
	"scripts"."ordinal" as "scripts_ordinal",
	"scriptPrompts"."scriptHcl" as "scriptPrompts_scriptHcl",
	"scriptPrompts"."promptHcl" as "scriptPrompts_promptHcl",
	"scriptPrompts"."inherited" as "scriptPrompts_inherited",
	"scriptPrompts"."readOnly" as "scriptPrompts_readOnly",
	"scriptPrompts"."hidden" as "scriptPrompts_hidden",
	"scriptPrompts"."inheritedScriptHcl" as "scriptPrompts_inheritedScriptHcl",
	"scriptPrompts"."ordinal" as "scriptPrompts_ordinal",
	"scriptPrompts"."min" as "scriptPrompts_min",
	"scriptPrompts"."max" as "scriptPrompts_max",
	"prompt"."hcl" as "prompt_hcl",
	"prompt"."inputType" as "prompt_inputType",
	"prompt"."importanceType" as "prompt_importanceType",
	"prompt"."minValue" as "prompt_minValue",
	"prompt"."maxValue" as "prompt_maxValue",
	"prompt"."units" as "prompt_units",
	"prompt"."category" as "prompt_category",
	"prompt"."ordinal" as "prompt_ordinal",
	"prompt"."id" as "prompt_id",
	"promptOptions"."hcl" as "promptOptions_hcl",
	"promptOptions"."ordinal" as "promptOptions_ordinal",
	"promptOptions"."halt" as "promptOptions_halt",
	"promptOptions"."id" as "promptOptions_id",
	"promptAccounts"."accountHcl" as "promptAccounts_accountHcl",
	"promptAccounts"."promptHcl" as "promptAccounts_promptHcl",
	"promptOptionsPrompt"."hcl" as "promptOptionsPrompt_hcl",
	"promptOptionsPrompt"."id" as "promptOptionsPrompt_id",
	"parents"."hcl" as "parents_hcl",
	"parents"."id" as "parents_id",
	"promptOptionAccounts"."accountHcl" as "promptOptionAccounts_accountHcl",
	"promptOptionAccounts"."promptOptionHcl" as "promptOptionAccounts_promptOptionHcl",
	"scriptAccounts"."accountHcl" as "scriptAccounts_accountHcl",
	"scriptAccounts"."scriptHcl" as "scriptAccounts_scriptHcl",
	"children"."id" as "children_id",
	"children"."hcl" as "children_hcl",
	"children"."dateCreated" as "children_dateCreated",
	"children"."dateUpdated" as "children_dateUpdated",
	"children"."rootHcl" as "children_rootHcl",
	"children"."parentHcl" as "children_parentHcl",
	"children"."min" as "children_min",
	"children"."max" as "children_max",
	"children"."aliasHcl" as "children_aliasHcl",
	"children"."ordinal" as "children_ordinal"
from
	"scripts" "scripts"
left join "script_prompts" "scriptPrompts" on
	"scriptPrompts"."scriptHcl" = "scripts"."hcl"
left join "prompts" "prompt" on
	"prompt"."hcl" = "scriptPrompts"."promptHcl"
left join "prompt_options" "promptOptions" on
	"promptOptions"."promptHcl" = "prompt"."hcl"
left join "account_prompts" "promptAccounts" on
	"promptAccounts"."promptHcl" = "prompt"."hcl"
	and ("promptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "prompts" "promptOptionsPrompt" on
	"promptOptionsPrompt"."hcl" = "promptOptions"."promptHcl"
left join "prompt_option_parents" "promptOptions_parents" on
	"promptOptions_parents"."promptOptionHcl" = "promptOptions"."hcl"
left join "prompt_options" "parents" on
	"parents"."hcl" = "promptOptions_parents"."parentPromptOptionHcl"
left join "account_prompt_options" "promptOptionAccounts" on
	"promptOptionAccounts"."promptOptionHcl" = "promptOptions"."hcl"
	and ("promptOptionAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "account_scripts" "scriptAccounts" on
	"scriptAccounts"."scriptHcl" = "scripts"."hcl"
	and ("scriptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "scripts" "children" on
	"children"."parentHcl" = "scripts"."hcl"
where
	"scripts"."rootHcl" = 'APPLICATION'
	and (("scriptAccounts"."accountHcl" is not null
		and "promptAccounts"."accountHcl" is null
		and "promptOptionAccounts"."accountHcl" is null)
	or ("scriptAccounts"."accountHcl" is not null
		and "promptAccounts"."accountHcl" is not null
		and "promptOptionAccounts"."accountHcl" is not null))
order by
	"scripts"."ordinal" asc,
	"children"."ordinal" asc,
	"scriptPrompts"."ordinal" asc,
	"promptOptions"."ordinal" asc
```

Here is the count query:
```
 select
	COUNT(distinct("scripts"."id")) as "cnt"
from
	"scripts" "scripts"
left join "script_prompts" "scriptPrompts" on
	"scriptPrompts"."scriptHcl" = "scripts"."hcl"
left join "prompts" "prompt" on
	"prompt"."hcl" = "scriptPrompts"."promptHcl"
left join "prompt_options" "promptOptions" on
	"promptOptions"."promptHcl" = "prompt"."hcl"
left join "account_prompts" "promptAccounts" on
	promptAccounts.prompt.hcl = "prompt"."hcl"
	and ("promptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "prompts" "promptOptionsPrompt" on
	"promptOptionsPrompt"."hcl" = "promptOptions"."promptHcl"
left join "prompt_option_parents" "promptOptions_parents" on
	"promptOptions_parents"."promptOptionHcl" = "promptOptions"."hcl"
left join "prompt_options" "parents" on
	"parents"."hcl" = "promptOptions_parents"."parentPromptOptionHcl"
left join "account_prompt_options" "promptOptionAccounts" on
	promptOptionAccounts.promptOption.hcl = "promptOptions"."hcl"
	and ("promptOptionAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "account_scripts" "scriptAccounts" on
	"scriptAccounts"."scriptHcl" = "scripts"."hcl"
	and ("scriptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
left join "scripts" "children" on
	"children"."parentHcl" = "scripts"."hcl"
where
	"scripts"."rootHcl" = 'APPLICATION'
	and (("scriptAccounts"."accountHcl" is not null
		and "promptAccounts"."accountHcl" is null
		and "promptOptionAccounts"."accountHcl" is null)
	or ("scriptAccounts"."accountHcl" is not null
		and "promptAccounts"."accountHcl" is not null
		and "promptOptionAccounts"."accountHcl" is not null))
```

The issue is with `left join "account_prompts" "promptAccounts" on`.  In the select query it is:
```
left join "account_prompts" "promptAccounts" on
	"promptAccounts"."promptHcl" = "prompt"."hcl"
	and ("promptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
```
In the count query it is:
```
left join "account_prompts" "promptAccounts" on
	promptAccounts.prompt.hcl = "prompt"."hcl"
	and ("promptAccounts"."accountHcl" = 'ACCOUNT.CAFFEINE')
```
The select query works, but the count query does not work.  

The same issue is happening with `left join "account_prompt_options" "promptOptionAccounts" on` join as well.

### Expected Behavior

The count query to work.

### Actual Behavior

The count query fails with the following error:

```
 QueryFailedError: invalid reference to FROM-clause entry for table "prompt"
        at new QueryFailedError (/node_modules/typeorm/error/QueryFailedError.js:12:28)
        at PostgresQueryRunner.<anonymous> (node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:248:31)
        at step (/node_modules/tslib/tslib.js:143:27)
        at Object.throw (/node_modules/tslib/tslib.js:124:57)
        at rejected (/node_modules/tslib/tslib.js:115:69)
        at processTicksAndRejections (internal/process/task_queues.js:95:5) {
      length: 227,
      severity: 'ERROR',
      code: '42P01',
      detail: undefined,
      hint: 'There is an entry for table "prompt", but it cannot be referenced from this part of the query.',
      position: '379',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '3299',
      routine: 'errorMissingRTE',
      query: 'SELECT COUNT(DISTINCT("scripts"."id")) AS "cnt" FROM "scripts" "scripts" LEFT JOIN "script_prompts" "scriptPrompts" ON "scriptPrompts"."scriptHcl"="scripts"."hcl"  LEFT JOIN "prompts" "prompt" ON "prompt"."hcl"="scriptPrompts"."promptHcl"  LEFT JOIN "prompt_options" "promptOptions" ON "promptOptions"."promptHcl"="prompt"."hcl"  LEFT JOIN "account_prompts" "promptAccounts" ON promptAccounts.prompt.hcl="prompt"."hcl" AND ("promptAccounts"."accountHcl" = $1)  LEFT JOIN "prompts" "promptOptionsPrompt" ON "promptOptionsPrompt"."hcl"="promptOptions"."promptHcl"  LEFT JOIN "prompt_option_parents" "promptOptions_parents" ON "promptOptions_parents"."promptOptionHcl"="promptOptions"."hcl" LEFT JOIN "prompt_options" "parents" ON "parents"."hcl"="promptOptions_parents"."parentPromptOptionHcl"  LEFT JOIN "account_prompt_options" "promptOptionAccounts" ON promptOptionAccounts.promptOption.hcl="promptOptions"."hcl" AND ("promptOptionAccounts"."accountHcl" = $2)  LEFT JOIN "account_scripts" "scriptAccounts" ON "scriptAccounts"."scriptHcl"="scripts"."hcl" AND ("scriptAccounts"."accountHcl" = $3)  LEFT JOIN "scripts" "children" ON "children"."parentHcl"="scripts"."hcl" WHERE "scripts"."rootHcl" = $4 AND (("scriptAccounts"."accountHcl" is not null and "promptAccounts"."accountHcl" is null and "promptOptionAccounts"."accountHcl" is null) or ("scriptAccounts"."accountHcl" is not null and "promptAccounts"."accountHcl" is not null and "promptOptionAccounts"."accountHcl" is not null))',
      parameters: [Array]
    }
```

### Steps to Reproduce

I can provide the relevant entity classes if that is needed.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macos catalina      |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.33 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [X] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by wayoalamos** [comment]
it also happened to me!

**Comment by mcorreaiz** [comment]
Same happened to me on MySQL driver.

The generated SQL for the `count` query contained `commentRecord.comment.id` instead of `` `commentRecord`.`commentId` `` (as it did for the `getMany` query) after doing 

```
const qry = this.createQueryBuilder('post');
qry.leftJoinAndSelect('post.comments', 'comment');
qry.leftJoinAndSelect('comment.records', 'commentRecord');

qry.getManyAndCount();
```

**Comment by jafio** [comment]
I have the problem too with mariadb driver and typeorm 0.2.34.

I think the problem is only with `OneToMany` relations. My entity has both `OneToMany` and `ManyToOne` relations and the problem doesn't occur if I don't join the `OneToMany` relation

**Comment by michaelbromley** [comment]
Ran into then when attempting to upgrade Vendure from 0.2.31 to 0.2.34. I get the error:

`ER_BAD_FIELD_ERROR: Unknown column 'productvariant__assets.productVariant.id' in 'on clause'",`

Looking at the generated query, this is the offending line:
```
 LEFT JOIN `product_variant_asset` `productvariant__assets` ON productvariant__assets.productVariant.id = `productvariant`.`id`
```

The correct version would be:
```
 LEFT JOIN `product_variant_asset` `productvariant__assets` ON productvariant__assets.productVariantId = `productvariant`.`id`
```

so the exact same error in transforming the column name as reported above by @mcorreaiz.

This is occurring for me also when using **sql.js** and **mariadb** drivers, so I suspect it is not an issue with a particular driver.

**Comment by joemaidman** [comment]
We are also experiencing this issue after upgrading from 0.2.32 to 0.2.34. In our case with a OneToMany and ManyToOne entity relationship.

Similar to @mcorreaiz , the generated SQL contains e.g. LEFT JOIN "post" "posts" ON posts.user.id="user"."id" instead of LEFT JOIN "post" "posts" ON posts.user_id ="user"."id"

**Comment by ebelyaev** [comment]
Any updates on this?  We cannot upgrade because of this issue.

**Comment by michaelbromley** [comment]
I decided to try to resolve this, and just spent a while attempting to create a failing unit test which recreates the behaviour described above. I'm working on the current master (v0.2.41) and was unable to reproduce it.

So I went back to my real-world project which had been manifesting this issue, and upgraded it from 0.2.31 -> 0.2.41. Strangely, now all my unit tests are passing and the issue does not seem to showing up anymore 🤔 

Can anyone else here try 0.2.41 and let me know whether you still see the issue?

If so, I'd love it if you can share a minimal reproduction that I could use to make a failing unit test.

**Comment by jafio** [comment]
@michaelbromley I tried the version 0.2.41 in my real-world project and it's working. My project was using version 0.2.32 because it had this bug with versions 0.2.33 and 0.2.34. I suppose someone fixed it. This could have been fixed by commit bd9e767 and the bug seems to be fixed in 0.2.36 as well.

**Comment by michaelbromley** [comment]
@ebelyaev it is looking like this might be fixed. Do you want to try it out on your project? If it is also resolved for you, I guess we can call this done.
