### ISSUE TITLE
QueryRunnerAlreadyReleasedError on async BeforeInsert and BeforeUpdate

### ISSUE THREAD

**Issue by phaalonso** [typeorm/typeorm#7718]
## Issue Description
When using async BeforeInsert and BeforeUpdate, typeorm execute the function and after that gives an error `QueryRunnerAlreadyReleasedError`

### Expected Behavior

Before inserting User in the database encrypt it's password.

### Actual Behavior

Trow an error and crash the application

```ts
[nodemon] starting `ts-node src/index.ts`
Server is running on port 3333
Entrei
Sai

/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/src/error/QueryRunnerAlreadyReleasedError.ts:7
        super();
        ^
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at new QueryRunnerAlreadyReleasedError (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/src/error/QueryRunnerAlreadyReleasedError.ts:7:9)
    at PostgresQueryRunner.<anonymous> (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/src/driver/postgres/PostgresQueryRunner.ts:202:19)
    at step (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/tslib/tslib.js:124:57)
    at /home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/tslib/tslib.js:113:16)
    at PostgresQueryRunner.query (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:212:24)
    at InsertQueryBuilder.<anonymous> (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/src/query-builder/InsertQueryBuilder.ts:107:50)
    at step (/home/pedro/programacao/faculdade/PI1C7/gerenciador-eventos/backend/node_modules/tslib/tslib.js:143:27)
[nodemon] app crashed - waiting for file changes before starting...

```

### Steps to Reproduce
1. Use Before* with async
2. Try to insert/update something

```ts
import { Column, ChildEntity, BeforeInsert, BeforeUpdate } from 'typeorm';
import { UserLevel } from './UserLevel';
import { People } from './People';
import bcrypt from 'bcrypt';

@ChildEntity()
export class User extends People {
    @Column('varchar', { select: false, unique: true })
    login?: string;

    @Column('varchar', { select: false })
    password?: string;

    @Column({
        type: 'enum',
        enum: UserLevel,
        default: UserLevel.DEFAULT,
    })
    level?: UserLevel; // nivel de acesso

    @BeforeInsert() 
    @BeforeUpdate()
    async hashPassword() {
        console.log('Entrei');
        if(this.password) {
            this.password = await bcrypt.hash(this.password, 8);
        }
        console.log('Sai');
    }
}
```

```ts
import { DeleteResult, FindOneOptions, DeepPartial } from 'typeorm';
import { connection } from '../database/connection';
import { User } from '../model/User';
import bcrypt from 'bcrypt';

interface PartialUser {
    id: number;
    email: string;
    name: string;
    level: number;
}

export default {
    getInstance(entityLikeArray: DeepPartial<User>) {
        const repo = connection.getRepository(User);

        return repo.create(entityLikeArray);
    },

    create(user: User): Promise<User> {
        return new Promise((resolve, reject) => {
            connection.transaction(async manager => {
                const repo = manager.getRepository(User);
                repo.save(user).then(user => {
                    resolve(user);
                });
            }).catch(err => {
                reject(err);
            });
        });
    },
};

```

```ts
userRoutes.post(
    '/',
    celebrate({
        [Segments.BODY]: Joi.object().keys({
            name: Joi.string().required(),
            email: Joi.string().required().trim().email(),
            password: Joi.string().required().trim().min(6),
            cpf: Joi.string().required().trim().length(11),
            cellphone: Joi.string().required().min(9).max(14),
            birthDate: Joi.date().required().max(new Date(new Date().getTime() - tenYearsInMs)),
            cep: Joi.string().required().trim().replace('-', '').length(8),
            city: Joi.string().required().max(100),
            uf: Joi.string().required().length(2),
            address: Joi.string().required().max(100),
        })
    }),
    async (req, res) => {

        const user = UserController.getInstance(req.body);

        try {
            const createdUser = await UserController.create(user);

            console.log(createdUser);
            return res.status(201).json(createdUser);
        } catch (err) {
            console.log(err);
            return res.status(400).json({ message: 'Error in creating the user' });
        }
    }
);

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  PopOs 20.04 and Windows 10 |
| Node.js version   | v15.14.0 |
| Typescript version  | v3.3.3333 and  v4.3.2|
| TypeORM version     | v0.2.34 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [X] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by phaalonso** [comment]
Update:

My friend discovered that when removing the transaction on UserController.create. It works normally 

```ts
create(user: User): Promise<User> {
    return new Promise((resolve, reject) => {
        const repo = connection.getRepository(User);
        repo.save(user).then(user => {
            resolve(user);
        });
    });
},
```

**Comment by imnotjames** [comment]
This seems to be an issue with your code.

```

    create(user: User): Promise<User> {
        return new Promise((resolve, reject) => {
            connection.transaction(async manager => {
                const repo = manager.getRepository(User);
                repo.save(user).then(user => {
                    resolve(user);
                });
            }).catch(err => {
                reject(err);
            });
        });
    },
```

`repo.save` is async and you're using an async function in the transaction but then not waiting for `repo` to save.  By the time the save can complete, the transaction has already completed because you never waited for it.


`await` your `repo.save` if you're using async or you end up with a race condition.

**Comment by imnotjames** [comment]
please feel free to re-open if you believe this is an actual issue.
