### ISSUE TITLE
Duplicate key constrains on .save() with bigint as primary key

### ISSUE THREAD

**Issue by aliaksei-yarmash** [typeorm/typeorm#7833]
## Issue Description
I am creating an entity with bigint as primary key.
```ts
@Entity()
export class User {
    @PrimaryColumn({
        name: 'id',
        type: 'bigint'
      })
    id!: number;
}
```
Than saving two items with the same id.
```ts
const user = new User();
user.id = 5637239627;
await connection.getRepository(User).save([user]);
const user2 = new User();
user2.id = 5637239627;
await connection.getRepository(User).save([user2]);
```

### Expected Behavior
The second item should overwrite the first one.

### Actual Behavior
```
QueryFailedError: duplicate key value violates unique constraint "PK_cace4a159ff9f2512dd42373760"
    at new QueryFailedError (/Users/baderfall/Documents/web/testing/typeorm/src/error/QueryFailedError.ts:11:9)
    at PostgresQueryRunner.<anonymous> (/Users/baderfall/Documents/web/testing/typeorm/src/driver/postgres/PostgresQueryRunner.ts:228:19)
    at step (/Users/baderfall/Documents/web/testing/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/baderfall/Documents/web/testing/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/baderfall/Documents/web/testing/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  length: 229,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(5.63724e+09) already exists.',
```

### Steps to Reproduce

You can reproduce inside that repository:
https://github.com/aliaksei-yarmash/typeorm

```
npm run start
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     mac OS     |
| Node.js version     | v12.18.2 | 
| Typescript version  | v3.9.9 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by andreasrueedlinger** [comment]
Note that this is not really a bug in typeorm but a problem with the usage of `bigint` datatype. By default, database drivers serialize bigint values as string values, so the equality check of typeorm will fail and thus an insert statement is triggered.
I had a similar problem using mysql. There you could set `supportBigNumbers: true` and `bigNumberStrings: false` in `connectionOptions` to make your example working (but there might be problems for bigger numbers). In postgres, however, it does not seem to be supported (https://github.com/brianc/node-pg-types/issues/78).

So a solution to your problem would be to use a string type for your id property which I guess should not be a problem as you normally don't use arithmetic operations in id values.
