### ISSUE TITLE
mongoDB updateOne / findOneAndUpdate requires atomic operators

### ISSUE THREAD

**Issue by jackykwandesign** [typeorm/typeorm#7847]
## Issue Description
When i use  updateOne / findOneAndUpdate,
it will show an error like this

this is the code to find the object by findOne
```
        const found = await this.FindByObjectId(_objectID)
        if(!found) return false
        console.log("found",found)
```
give me result
```
found Pet {
  id: 60e41131e973ebe601ab8dde,
  name: 'tes22313123',
  animalType: 'test23',
  birthDate: '2020-02-06',
  createAt: 2021-07-06T08:15:45.636Z,
  updateAt: 2021-07-06T08:15:45.636Z
}
```

update object by this
```

            const result = await this.petRepository.updateOne({
                id:found.id
            },found)
```

then it will give me error requires atomic operators, but the normal update method is fine, just updateOne / findOneAndUpdate  is not working
```
TypeError: Update document requires atomic operators
    at new UpdateOneOperation (/home/jacky/question-bank-backend/node_modules/mongodb/lib/operations/update_one.js:14:13)
    at Collection.updateOne (/home/jacky/question-bank-backend/node_modules/mongodb/lib/collection.js:765:5)
    at MongoQueryRunner.<anonymous> (/home/jacky/question-bank-backend/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:446:85)
    at step (/home/jacky/question-bank-backend/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/jacky/question-bank-backend/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /home/jacky/question-bank-backend/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/jacky/question-bank-backend/node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
    at MongoQueryRunner.updateOne (/home/jacky/question-bank-backend/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:443:24)
    at MongoEntityManager.updateOne (/home/jacky/question-bank-backend/node_modules/typeorm/entity-manager/MongoEntityManager.js:537:38)

```
### Expected Behavior
run in atomic operation

### Actual Behavior
fail into error

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

entity
```typescript
import { Entity, ObjectID, ObjectIdColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity()
export class Pet {
  @ObjectIdColumn() id: ObjectID;
  @Column() name: string;
  @Column() animalType: string;
  @Column() pictureUrl?: string;
  @Column() birthDate?: Date;
  @CreateDateColumn()
  createAt: Date;

  @UpdateDateColumn()
  updateAt: Date;
  
  constructor(pet?: Partial<Pet>) {
    Object.assign(this, pet);
  }
}
```

service
```typescript
import { Injectable, InternalServerErrorException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { MongoRepository } from 'typeorm';
import { ObjectID } from 'mongodb';
import { CreatePetDto } from './dto/create-pet.dto';
import { Pet } from './pet.entity';
import { UpdatePetDto } from './dto/update-pet.dto';

@Injectable()
export class PetService {
    constructor(
        @InjectRepository(Pet)
        private readonly petRepository: MongoRepository<Pet>,
    ){}
    private logger = new Logger(PetService.name)

    async FindAllAndCount(){
        const [pets,count] = await this.petRepository.findAndCount()
        return {
            pets,
            count
        }
    }

    async FindByObjectId(_objectID:string | ObjectID){
        const found = ObjectID.isValid(_objectID) && await this.petRepository.findOne(_objectID)
        return found ? found :false
    }

    async Create(petDto: CreatePetDto){
        const {
            name,
            animalType,
            birthDate
        } = petDto

        try {
            const pet = new Pet()
            pet.animalType = animalType
            pet.birthDate = birthDate,
            pet.name = name
            const result = await this.petRepository.save(pet)
            return result
        } catch (error) {
            this.logger.error(`Create-Pet failed. Data:${petDto}. `, error.stack)
            return false
        }

    }

    async UpdateByObjectID(_objectID:ObjectID, _updatePetDto:UpdatePetDto){
        const found = await this.FindByObjectId(_objectID)
        if(!found) return false

        console.log("found",found)
        if(_updatePetDto.name)found.name = _updatePetDto.name
        if(_updatePetDto.birthDate)found.birthDate = _updatePetDto.birthDate
        if(_updatePetDto.animalType)found.animalType = _updatePetDto.animalType

        try {

            await this.petRepository.update({
                id:found.id
            },found)
            // const result =  await this.petRepository.findOneAndUpdate({
            //     id:ObjectID(_objectID)
            // },found)

            // if(reuslt.ok){
            //     return reuslt.value
            // }else{
            //     this.logger.error(`Update-Pet failed in update query. Data:${JSON.stringify(_updatePetDto)}. ErrorObj: ${JSON.stringify(reuslt.lastErrorObject)}`)
            //     return false
            // }
            return await this.FindByObjectId(_objectID)
        } catch (error) {
            this.logger.error(`Update-Pet failed. Data:${JSON.stringify(_updatePetDto)}. `, error.stack)
            return false
        }
        
    }

    async DeleteByObjectID(_objectID:ObjectID){

        try {
            if(!ObjectID.isValid(_objectID)){
                this.logger.error(`Delete-Pet failed. ObjectId:${_objectID} is invalid. `)
                return false 
            }
            const result = await this.petRepository.findOneAndDelete({
                id:ObjectID(_objectID)
            })
            // return result
            if(result.value === null || !result.ok){
                this.logger.error(`Delete-Pet failed in findOneAndDelete query. ObjectId:${_objectID}. ErrorObj: ${JSON.stringify(result.lastErrorObject)}`)
                return false
            }else{
                return
            }
        } catch (error) {
            this.logger.error(`Delete-Pet failed. ObjectId:${_objectID}. `, error.stack)
            return false
        }
        
    }
}

```

controller
```typescript
import { Body, Controller, Delete, Get, HttpCode, InternalServerErrorException, NotFoundException, Param, Patch, Post } from '@nestjs/common';
import { ResponseFormat } from 'src/utils/responseFormat';
import { CreatePetDto } from './dto/create-pet.dto';
import { UpdatePetDto } from './dto/update-pet.dto';
import { Pet } from './pet.entity';
import { PetService } from './pet.service';

@Controller('pet')
export class PetController {

    constructor(
        private _petService: PetService
    ){}

    @Get('/')
    async FindAll(){
        const {pets, count} = await this._petService.FindAllAndCount()
        let res:ResponseFormat<Pet[]> = {
            data:pets,
            total:count,
            success:true,
        }
        return res
    }

    @Get('/:id')
    async FindByObjectId(
        @Param('id') id,
    ){
        const result = await this._petService.FindByObjectId(id)
        if(!result) throw new NotFoundException()
        return result
    }

    @Post('/')
    // @Roles(UserRole.ADMIN, UserRole.ORGANIZATION_OWNER)
    async Create(
        @Body()_createPetDto:CreatePetDto
    ){
        const result = await this._petService.Create(_createPetDto)
        if(!result) throw new InternalServerErrorException()
        return result
    }

    @Patch('/:id')
    async Update(
        @Param('id') id,
        @Body()_updatePetDto:UpdatePetDto
    ){
        const result =  await this._petService.UpdateByObjectID(id,_updatePetDto)
        if(!result) throw new InternalServerErrorException()
        return result
    }

    @Delete('/:id')
    // @HttpCode(204)
    async Delete(
        @Param('id') id,
    ){
        const result =  await this._petService.DeleteByObjectID(id)
        if(!result) throw new InternalServerErrorException()
        return result
    }
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.22.2 | 
| Typescript version  | v4.3.5 | 
| TypeORM version     | v0.2.34  | 
| MongoDB version     | v4.4.6  | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
`updateOne` is specific to mongo.  It requires the `update` be `{ $set: { foo: "bar" } }`.
