### ISSUE TITLE
Using enum as column type results in successful migration but results in error at runtime

### ISSUE THREAD

**Issue by IRCraziestTaxi** [typeorm/typeorm#7902]
## Issue Description

When using an enum containing integer values as a column's type, a migration can be successfully created with the column having type `int`.

However, at runtime, an error occurs:

```
DataTypeNotSupportedError: Data type "Object" in "StaffMember.staffMemberType" is not supported by "mysql" database.
    at new DataTypeNotSupportedError (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/error/DataTypeNotSupportedError.ts:9:9)
    at /Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/metadata-builder/EntityMetadataValidator.ts:87:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/metadata-builder/EntityMetadataValidator.ts:84:36)
    at /Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/connection/Connection.ts:527:33)
    at Connection.<anonymous> (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/src/connection/Connection.ts:193:18)
    at step (/Users/xxx/IRCraziestTaxi/typeorm-enum-as-column-type/node_modules/tslib/tslib.js:143:27)
```

### Expected Behavior

I would expect TypeORM to be able to infer the `int` type at runtime the same as it does when creating the migration.

### Actual Behavior

See the runtime error above.

```
// include the output in code tags like these!
```

### Steps to Reproduce

See the README and code at [this repository](https://github.com/IRCraziestTaxi/typeorm-enum-as-column-type).

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     macOS Big Sur     |
| Node.js version     | v14.16.0 | 
| Typescript version  | v4.3.5 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

The issue can easily be worked around by changing the column's type to `number`, but I believe context and understanding is lost by doing so, and since the migration correctly infers the type, I figure a fix is possible for TypeORM to do so at runtime.

**Comment by pleerock** [comment]
I don't think migration works properly. I guess the fact that you have "int" in there is a side effect. Try to change your enum to:

```ts
export enum StaffMemberType {
    Manager = "Manager",
    Supervisor = "Supervisor",
    Minion = "Minion"
}
```

Will it still generate "int"?

Also, I'm not sure so much magic over explicitness is better. Because:

* there is no separate type for "enum" in the runtime. There is no difference of enum with let's say following object:

```ts
const StaffMemberType = {
    Manager = "Manager",
    Supervisor = "Supervisor",
    Minion = "Minion"
}
```

or maybe even with:

```ts
export class StaffMemberType {
    static Manager = "Manager"
    static Supervisor = "Supervisor"
    static Minion = "Minion"
}
```

can we treat such signatures as "enum" too?

* in postgres when we use "enums" we need to define a database type as "enum". Behavior can be different for different databases. 

Not really sure.

**Comment by IRCraziestTaxi** [comment]
That is a good point about enums at runtime... I keep forgetting typescript doesn't *really* have a concept of enums and that they are just objects.

Interesting, I tried adding:

```ts
enum StringEnum {
    First = "First",
    Second = "Second",
    Third = "Third"
}

// in entity
@Column({ nullable: false })
public stringEnum: StringEnum;
```

and the migration actually made the column `varchar` type.

```ts
await queryRunner.query("ALTER TABLE `staff_member` ADD `stringEnum` varchar(255) NOT NULL");
```

So... I'm not sure what is going on during migration generation that seems to correctly treat enums with number values as `int` columns and enums with string values as `varchar` columns, but given the fact that some databases can use actual enum types, I suppose it would just be messy to try to treat enums differently for different database engines. As a matter of fact, I would say it is worth looking into to make migrations give the same error about enum columns since there is something very inconsistent going on there. For that reason, I'll leave this open, but you can close it in favor of opening a separate issue if you want.

**Comment by pleerock** [comment]
Looks like this is unintended migration behavior. Let's keep it and open and let's ask @AlexMesser to check it out if he has available time.
