### ISSUE TITLE
Cannot find alias for relation at user

### ISSUE THREAD

**Issue by botre** [typeorm/typeorm#8016]
## Issue Description

```
Cannot find alias for relation at user
      at _loop_3 (src/query-builder/QueryBuilder.ts:944:27)
      at UpdateQueryBuilder.Object.<anonymous>.QueryBuilder.findColumnsForPropertyPath (node_modules/typeorm/query-builder/QueryBuilder.js:817:27)
      at UpdateQueryBuilder.<anonymous> (src/query-builder/QueryBuilder.ts:1059:68)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at UpdateQueryBuilder.Object.<anonymous>.QueryBuilder.getWhereCondition (src/query-builder/QueryBuilder.ts:1195:80)
      at UpdateQueryBuilder.Object.<anonymous>.UpdateQueryBuilder.where (src/query-builder/UpdateQueryBuilder.ts:176:32)
      at EntityManager.Object.<anonymous>.EntityManager.update (src/entity-manager/EntityManager.ts:514
```

PR with test case: https://github.com/typeorm/typeorm/pull/8024

### Expected Behavior

```typescript
      await getRepository(WorkspaceMemberEntity).update(
        {
          user: {
            id: createdWorkspace.createdById!,
          },
          workspace: {
            id: createdWorkspace.id,
          },
        },
        {
          role: WorkspaceMemberRole.MEMBER,
        }
      );
````

It should update the table.

### Actual Behavior

Error: Cannot find alias for relation at user.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows     |
| Node.js version     | 14.16  |
| Typescript version  | 4.3.5  |
| TypeORM version     | ^0.2.36  |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by botre** [comment]
I encounter this issue on 0.2.35 and 0.2.36.
0.2.34 is fine.

Looks like it could be related to this: https://github.com/typeorm/typeorm/pull/7821

**Comment by botre** [comment]
I have enabled logging and I don't see an UPDATE query generated anywhere, I'm assuming this error is thrown before  :/

Stacktrace:

```
Cannot find alias for relation at user

      at _loop_3 (src/query-builder/QueryBuilder.ts:944:27)
      at UpdateQueryBuilder.Object.<anonymous>.QueryBuilder.findColumnsForPropertyPath (node_modules/typeorm/query-builder/QueryBuilder.js:817:27)
      at UpdateQueryBuilder.<anonymous> (src/query-builder/QueryBuilder.ts:1059:68)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at UpdateQueryBuilder.Object.<anonymous>.QueryBuilder.getWhereCondition (src/query-builder/QueryBuilder.ts:1195:80)
      at UpdateQueryBuilder.Object.<anonymous>.UpdateQueryBuilder.where (src/query-builder/UpdateQueryBuilder.ts:176:32)
      at EntityManager.Object.<anonymous>.EntityManager.update (src/entity-manager/EntityManager.ts:514
```

**Comment by imnotjames** [comment]
Can you include your entity definitions?  As it stands, I cannot replicate your problem with the information provided.

**Comment by botre** [comment]
Here you go:

```typescript
import { Column, Entity, ManyToOne } from "typeorm";
import BaseEntity from "./BaseEntity";
import UserEntity from "./UserEntity";
import WorkspaceEntity from "./WorkspaceEntity";

export enum WorkspaceMemberRole {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

@Entity({ name: "workspace_member" })
export default class WorkspaceMemberEntity extends BaseEntity {
  @ManyToOne(() => WorkspaceEntity, (workspace) => workspace.members, {
    nullable: false,
    onDelete: "CASCADE",
    onUpdate: "CASCADE",
    primary: true,
  })
  workspace: WorkspaceEntity;

  @ManyToOne(() => UserEntity, (user) => user.workspaceMembers, {
    nullable: false,
    onDelete: "CASCADE",
    onUpdate: "CASCADE",
    primary: true,
  })
  user: UserEntity;

  @Column({ length: 64, default: WorkspaceMemberRole.MEMBER })
  role: WorkspaceMemberRole;
}
```

**Comment by imnotjames** [comment]
I still need `WorkspaceEntity`, `UserEntity`, and `BaseEntity` to replicate this.

Alternatively, a test case that's minimal & still exhibits this issue would be more helpful.

**Comment by botre** [comment]
> I still need `WorkspaceEntity`, `UserEntity`, and `BaseEntity` to replicate this.
> 
> Alternatively, a test case that's minimal & still exhibits this issue would be more helpful.

Is there a repository I can clone to easily set this up?

**Comment by botre** [comment]
PR with test case: https://github.com/typeorm/typeorm/pull/8024

**Comment by imnotjames** [comment]
Looks like the tests passed in #8024 after I fixed the way the test cases handle connections?

**Comment by botre** [comment]
Hi,

I will be able to continue my investigation / tweak the test case to hopefully reproduce the issue starting next Tuesday.

**Comment by benjaminhera** [comment]
@botre Can you tell us how you fixed it?
