### ISSUE TITLE
TypeORMError: Driver not Connected

### ISSUE THREAD

**Issue by gcherem** [typeorm/typeorm#8079]
## Issue Description

I'm getting this error **TypeORMError: Driver not Connected** and no clue about what is causing it. I also searched this error here and in Stackoverflow but found nothing. Could someone explain what cause it?

### Expected Behavior

To connect to the database, or more info in the stack error. It doesn't refer to **any source of mine**, so I suppose my code is OK and should be a problem with Typeorm.

### Actual Behavior

```
[Nest] 16199   - 13/08/2021 17:00:36   🚀 Server is running in "dev" mode on: http://[::1]:8080 +1ms
[Nest] 16199   - 13/08/2021 17:01:03   Account rASlDXuishwym58wCxlrU sucessfully created from ::1 by gfcherem@gmail.com +27539ms
[Nest] 16199   - 13/08/2021 17:01:03   User gfcherem@gmail.com selected account rASlDXuishwym58wCxlrU from IP ::1 +22ms
[Nest] 16199   - 13/08/2021 17:01:04   User gfcherem@gmail.com selected account rASlDXuishwym58wCxlrU from IP ::1 +50ms
[Nest] 16199   - 13/08/2021 17:01:04   TagTrigger on srASlDXuishwym58wCxlrU +411ms
[Nest] 16199   - 13/08/2021 17:01:04   SetupLowerCaseIndices on srASlDXuishwym58wCxlrU +13ms
[Nest] 16199   - 13/08/2021 17:01:04   ResponseTrigger on srASlDXuishwym58wCxlrU +18ms
[Nest] 16199   - 13/08/2021 17:01:04   [ExceptionsHandler] Driver not Connected +20ms
TypeORMError: Driver not Connected
    at new TypeORMError (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/error/TypeORMError.js:9:28)
    at /Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/driver/postgres/PostgresDriver.js:896:22
    at new Promise (<anonymous>)
    at PostgresDriver.obtainMasterConnection (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/driver/postgres/PostgresDriver.js:894:16)
    at PostgresQueryRunner.connect (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:69:58)
    at PostgresQueryRunner.<anonymous> (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:238:51)
    at step (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /Users/gcherem/Source/usermetrics/usermetrics-backend/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

### Steps to Reproduce

Since the error log does not refer to any source of mine, I have no clue what causes this error.

### My Environment

    "@nestjs/bull": "^0.2.2",
    "@nestjs/common": "^7.6.13",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.6.13",
    "@nestjs/graphql": "^7.6.0",
    "@nestjs/jwt": "^7.1.0",
    "@nestjs/passport": "^7.1.0",
    "@nestjs/platform-express": "^7.6.13",
    "@nestjs/typeorm": "^8.0.2",
    "@types/bcrypt": "^3.0.0",
    "apollo-server-express": "^2.17.0",
    "apollo-server-fastify": "^3.0.0-alpha.3",
    "bcrypt": "^5.0.0",
    "bull": "^3.18.1",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.5",
    "dotenv-flow": "^3.2.0",
    "graphql": "^15.5.0",
    "graphql-subscriptions": "^1.2.1",
    "graphql-tools": "^6.2.0",
    "ms": "^2.1.3",
    "nanoid": "^3.1.12",
    "nestjs-config": "^1.4.7",
    "nestjs-redis": "^1.2.8",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "pg": "^8.3.3",
    "pg-hstore": "^2.3.3",
    "reflect-metadata": "^0.1.13",
    "request-ip": "^2.1.3",
    "rimraf": "^3.0.2",
    "rxjs": "^7.3.0",
    "typeorm": "^0.2.37",
    "typeorm-transactional-cls-hooked": "^0.1.12",
    "typescript": "^4.3.5"

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `postgres`           |yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
This means that the driver has not been connected.

Do you have example code which can be used to exhibit this? 

Did you call `connect` on the connection?

**Comment by andrewfeng2021** [comment]
Have the same issue here, did some investigation and seems this method is not considering released connection when get new query runner:
https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L2186

will provide more details later.

**Comment by Ymirke** [comment]
Hey, don't have a minimal repro as I'm not sure what the issue is. And couldn't find where this error message is being emitted.

However I was also getting this error, but only in GCP, and only on 0.2.45 - downgrading back to 0.2.41 worked fine again.

**Comment by Kampfmoehre** [comment]
We see this problem in of our projects but strangely only when it is running in CI. We use GitLab CI which provides a postgres sidecar container. This works in a couple of other projects (some of them using typeorm too) but in one it fails most of the time when running API tests. Since it randomly succeeds this seems like a race condition or timing issue.
This is the most common stack trace
```js
{
  "type": "QueryFailedError",
  "message": "Connection terminated",
  "stack":
    QueryFailedError: Connection terminated
      at PostgresQueryRunner.query (/builds/<project>/src/driver/postgres/PostgresQueryRunner.ts:299:19)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at <customRepo>.loadRawResults (/builds/<project>/src/query-builder/SelectQueryBuilder.ts:3601:25)
      at <customRepo>.executeEntitiesAndRawResults (/builds/<project>/src/query-builder/SelectQueryBuilder.ts:3366:26)
      at <customRepo>.getRawAndEntities (/builds/<project>/src/query-builder/SelectQueryBuilder.ts:1617:29)
      at <customRepo>.getOne (/builds/<project>/src/query-builder/SelectQueryBuilder.ts:1644:25)
      at <api-controller>.<api-method> (/builds/<project>/src/controllers/<api-controller>.ts:62:19)
  "query": "<not relevant select query>",
  "parameters": [
    "[REDACTED]"
  ],
  "driverError": {
    "type": "Error",
    "message": "Connection terminated",
    "stack":
      Error: Connection terminated
        at Connection.<anonymous> (/builds/<project>/node_modules/pg/lib/client.js:132:36)
        at Object.onceWrapper (node:events:627:28)
        at Connection.emit (node:events:525:35)
        at Connection.emit (node:domain:489:12)
        at Socket.<anonymous> (/builds/<project>/node_modules/pg/lib/connection.js:57:12)
        at Socket.emit (node:events:513:28)
        at Socket.emit (node:domain:489:12)
        at TCP.<anonymous> (node:net:757:14)
        at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
  }
}
```

**Comment by renemroger** [comment]
I had the same issue and stumbled on this thread. My issue was that I was missing `.initialize()` on my dataSource.

**Comment by mgohin** [comment]
In my case I add this problem while running my e2e tests.

There was in fact a service class initialised by my app, which use a `setTimeout` with 10s delay, starting a method using TypeORM.

I did manage to find it by starting in debug mode and placing a breakpoint where TypeORM was raising the exception, and looking at the callstack.

**Comment by ww-daniel-mora** [comment]
My issue was a missing await on a query. The code proceeded to destroy the connection before the query got to execute.

**Comment by sbleon** [comment]
We get this error intermittently in local dev with an app using TypeORM 0.3.17, run with `pm2-runtime` and `ts-node-dev`, and connecting to an MSSQL 2022 database running in Docker. Restarting the app with `pm2 reload all` makes the error go away.

**Comment by mayanksinghal-git** [comment]
I had building a project using single Database. Later when we had connected our project with multiple database. I started facing this issue.
Strange part is all my entity are still not moved to new database connection, but now when i try to insert a data, it throws me error even when fetching data works fine. Not sure what exactly the issue.

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/9740ab02-ed6e-4023-9aaf-137342834d92" />

Below is how we are connecting with multiple database, my NODE_ENV is production, so it always should return the else statement.

``` 
TypeOrmModule.forRootAsync({
      useFactory: async () => {
          if (process.env.NODE_ENV !== CONSTANTS.ENV.PRODUCTION) {
              console.log('Using in-memory DB for default');
              const ds = await setupDataSource();
              return {
                  type: 'postgres',
                  dataSource: ds,
              };
          } else {
              const realDS = new DataSource(config);
              return {
                  ...config,
                  dataSource: realDS,
              };
          }
      },
  }),
  TypeOrmModule.forRootAsync({
      name: 'DB2',
      useFactory: async () => {
          if (process.env.NODE_ENV !== CONSTANTS.ENV.PRODUCTION) {
              console.log('Using in-memory DB for DB2');
              const ds2 = await setupDataSource2();
              return {
                  name: 'DB2',
                  type: 'postgres',
                  dataSource: ds2,
              };
          } else {
              const realDS2 = new DataSource(config2);
              return {
                  ...config2,
                  name: 'DB2',
                  dataSource: realDS2,
              };
          }
      },
  }),
```
