### ISSUE TITLE
Typeorm and Jest are throwing 'No metadata for "User" was found.' for unknown reason

### ISSUE THREAD

**Issue by joaocasarin** [typeorm/typeorm#8092]
Issue type:

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[ ] latest
[ ] @next
[x] 0.2.34 (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So, I got [this 'project'](https://github.com/joaocasarin/gittin) and it works when in production or development. In `ormconfig.js` I've set the entities/migrations folder to follow the environment, if it's production, it will get from dist/ folder, otherwise, it's from src/ folder. Checking the repository, you will see a docker-compose file for db-only, and that's fine when in prod/dev, but when I try to run [THIS](https://github.com/joaocasarin/gittin/blob/main/src/routes/CreateUser.test.ts) test, it doesn't throw error when connecting, but it's not able to find the entities, I guess and then I get this error: 
<details>
    <summary>Error 'No metadata for "User" was found.'</summary>
    ![unknown](https://user-images.githubusercontent.com/48847394/129618673-04451921-5043-4570-bec3-cdb9cc59d763.png)
</details>

It doesn't matter whether I set the env to `test` or not, I get the same error.

**Comment by imnotjames** [comment]
I suggest managing the connections yourself and passing the entities as classes to typeorm instead of globs.

**Comment by joaocasarin** [comment]
> I suggest managing the connections yourself and passing the entities as classes to typeorm instead of globs.
> 
> This bypasses the cross-environment weirdness and might help with whatever jest is doing.

Well, that's a good way to go, but I can't realize how I could do that for multiple environments.. You mean to import the entities im the `ormconfig.js`, and put them in the array instead of the path?
In production mode there's no src/folder, so if I import the classes in the ormconfig, it won't reach the entities..

**Comment by imnotjames** [comment]
I am saying don't use an `ormconfig.js` that magically gets loaded through the global helpers in TypeORM.

This is because you're running into the limitations of such a solution.

If you create your own connections you don't have a non-compiled ormconfig around.

If you DO need an `ormconfig` you can always create one that's typescript.

`Database.ts`

```
import { ExampleEntity } from "../models/Wherever/Example";

const connection = createConnection({ entities: [ ExampleEntity ] });

export {
    connection
}
```

**Comment by joaocasarin** [comment]
> I am saying don't use an `ormconfig.js` that magically gets loaded through the global helpers in TypeORM.
> 
> This is because you're running into the limitations of such a solution.
> 
> If you create your own connections you don't have a non-compiled ormconfig around.
> 
> If you DO need an `ormconfig` then it'd be for development if you're using the TypeORM cli.
> 
> `Database.ts`
> 
> ```
> import { ExampleEntity } from "../models/Wherever/Example";
> 
> const connection = createConnection({ url: process.env.DATABASE_URL, entities: [ ExampleEntity ] });
> 
> export {
>     connection
> }
> ```

Ok, I admit I have already thought creating the connection that way, but didn't try. Now that I've tried, I found some errors the way I implemented it. First, the way I did it, in prod and dev it still works. On test environment, now I get this error:

<details>
    <summary>Error on terminal</summary>

    PS C:\Users\joaov\Documents\gittin> yarn test
    yarn run v1.22.10
    $ jest
     PASS  src/app.test.ts
     FAIL  src/routes/CreateUser.test.ts
      ● POST /api/user › should return 200

        error: password authentication failed for user "joaov"

          at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
          at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
          at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
          at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)


      ● Test suite failed to run

        error: password authentication failed for user "joaov"

          at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
          at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
          at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
          at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)

    Test Suites: 1 failed, 1 passed, 2 total
    Tests:       1 failed, 2 passed, 3 total
    Snapshots:   0 total
    Time:        5.051 s
    Ran all test suites.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    PS C:\Users\joaov\Documents\gittin>
</details>


With the new modification, where I tried to put all the `createConnection` options directly inside it, instead of in the ormconfig. Doing that, I can't run `typeorm migration:run` anymore, typeorm says I have not added the database type, so I add it to ormconfig. Then it shows the same error from the test I showed above.

PS.: The github repo is updated with the new code if you want to see it clearer.

<details>
<summary>These are the new codes:</summary>

`ormconfig.js`
```javascript
module.exports = {
    "cli": {
        "migrationsDir": "src/database/migrations", // typeorm creates migrations in this directory
        "entitiesDir": "src/entities" // typeorm creates entities in this directory
    }
}
```

`databaseConfigs.ts`
```typescript
import { ConnectionOptions } from "typeorm";
import AllMigrations from "../database/migrations";
import AllEntities from "../entities";

export const databaseConfigs = {
    type: "postgres",
    ssl: process.env.NODE_ENV === 'production'
        && process.env.DATABASE_URL !== 'postgres://postgres:docker@localhost:5432/gittin'
        && process.env.DATABASE_URL !== 'postgres://postgres:docker@db:5432/gittin' ? { rejectUnauthorized: false } : false,
    url: process.env.DATABASE_URL,
    entities: AllEntities,
    migrations: AllMigrations,
    dropSchema: process.env.NODE_ENV === 'test' ? false : false,
    migrationsRun: process.env.NODE_ENV !== 'production' ? true : false

} as ConnectionOptions;
```

`database/index.ts`
```typescript
import { createConnection } from "typeorm";
import { databaseConfigs } from "../configs/databaseConfigs";

const connection = createConnection(databaseConfigs);

export {
    connection
}
```

`entities/index.ts`
```typescript
import User from './User';

export default [
    User
];
```

`migrations/index.ts`
```typescript
import { CreateUsers1623957922252 } from "./1626667841903-CreateUsers";

export default [
    CreateUsers1623957922252
];
```

`main index.ts`
```typescript
import dotenv from "dotenv";
dotenv.config();
import app from "./app";
import { connection } from './database';

const port = process.env.PORT || 3000;

(async () => {
    try {
        (await connection).connect;
        app.listen(port, () => {
            console.log(`Server running on port ${port}`);
        });
    } catch (error) {
        console.log(error);
    }
})();
```

`CreateUser.test.ts`
```typescript
import st from "supertest";
import app from "../app";

import { connection } from '../database';


beforeAll(async () => {
    (await connection).connect;
});

afterAll(async () => {
    (await connection).close;
});

describe('POST /api/user', () => {
    it('should return 200', async () => {
        const response = await st(app).post('/api/users').send({
            "name": "123",
            "password": "123",
            "email": "docker@123.com",
            "admin": true
        });
        expect(response.body).toContain('"admin": true');
    });
})
```
</details>

**Comment by harshrawat66** [comment]
I am using Nestjs and the following solution works.
Modify the files as shown below

tasks.repository.ts
```
import { Injectable } from '@nestjs/common';
import { DataSource, Repository } from 'typeorm';
import { CreateTaskDto } from './create-task.dto';
import { TaskStatus } from './task-status.enum';
import { Task } from './task.entity';

@Injectable()
export class TaskRepository extends Repository<Task> {
  constructor(private dataSource: DataSource) {
    super(Task, dataSource.createEntityManager());
  }

  async createTask({ title, description }: CreateTaskDto): Promise<Task> {
    const task = this.create({
      title,
      description,
      status: TaskStatus.OPEN,
    });

    await this.save(task);
    return task;
  }
}

```

tasks.module.ts
```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Task } from './task.entity';
import { TasksController } from './tasks.controller';
import { TaskRepository } from './tasks.repository';
import { TasksService } from './tasks.service';

@Module({
  imports: [TypeOrmModule.forFeature([Task])],
  controllers: [TasksController],
  providers: [TasksService, TaskRepository],
})
export class TasksModule {}

```

tasks.service.ts
```
import { Injectable, NotFoundException } from '@nestjs/common';
import { TaskStatus } from './task-status.enum';
import { CreateTaskDto } from './create-task.dto';
import { GetTaskFilterDto } from './get-task-filter.dto';
import { TaskRepository } from './tasks.repository';
import { InjectRepository } from '@nestjs/typeorm';
import { Task } from './task.entity';

@Injectable()
export class TasksService {
  constructor(private readonly tasksRepository: TaskRepository) {}

  async getTaskById(id: string): Promise<Task> {
    const record = this.tasksRepository.findOne({ where: { id } });
    if (!record) {
      throw new NotFoundException();
    }
    return record;
  }

  createTask(createTaskDto: CreateTaskDto): Promise<Task> {
    return this.tasksRepository.createTask(createTaskDto);
  }
}
```

**Comment by aniket-kale** [comment]
Thanks [harshrawat66](https://github.com/harshrawat66).

**Comment by vietkieubui** [comment]
> I am using Nestjs and the following solution works. Modify the files as shown below
> 
> tasks.repository.ts
> 
> ```
> import { Injectable } from '@nestjs/common';
> import { DataSource, Repository } from 'typeorm';
> import { CreateTaskDto } from './create-task.dto';
> import { TaskStatus } from './task-status.enum';
> import { Task } from './task.entity';
> 
> @Injectable()
> export class TaskRepository extends Repository<Task> {
>   constructor(private dataSource: DataSource) {
>     super(Task, dataSource.createEntityManager());
>   }
> 
>   async createTask({ title, description }: CreateTaskDto): Promise<Task> {
>     const task = this.create({
>       title,
>       description,
>       status: TaskStatus.OPEN,
>     });
> 
>     await this.save(task);
>     return task;
>   }
> }
> ```
> 
> tasks.module.ts
> 
> ```
> import { Module } from '@nestjs/common';
> import { TypeOrmModule } from '@nestjs/typeorm';
> import { Task } from './task.entity';
> import { TasksController } from './tasks.controller';
> import { TaskRepository } from './tasks.repository';
> import { TasksService } from './tasks.service';
> 
> @Module({
>   imports: [TypeOrmModule.forFeature([Task])],
>   controllers: [TasksController],
>   providers: [TasksService, TaskRepository],
> })
> export class TasksModule {}
> ```
> 
> tasks.service.ts
> 
> ```
> import { Injectable, NotFoundException } from '@nestjs/common';
> import { TaskStatus } from './task-status.enum';
> import { CreateTaskDto } from './create-task.dto';
> import { GetTaskFilterDto } from './get-task-filter.dto';
> import { TaskRepository } from './tasks.repository';
> import { InjectRepository } from '@nestjs/typeorm';
> import { Task } from './task.entity';
> 
> @Injectable()
> export class TasksService {
>   constructor(private readonly tasksRepository: TaskRepository) {}
> 
>   async getTaskById(id: string): Promise<Task> {
>     const record = this.tasksRepository.findOne({ where: { id } });
>     if (!record) {
>       throw new NotFoundException();
>     }
>     return record;
>   }
> 
>   createTask(createTaskDto: CreateTaskDto): Promise<Task> {
>     return this.tasksRepository.createTask(createTaskDto);
>   }
> }
> ```

this worked
