### ISSUE TITLE
UnhandledPromiseRejectionWarning: QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore. 

### ISSUE THREAD

**Issue by 2604150210** [typeorm/typeorm#8166]
## I used twice `transactionalEntityManager.save()`, only`transactionalEntityManager.save(newAttr)` is successful，`transactionalEntityManager.save(finallyExtraList)` is fail and throw error,

I have spend 1.5 days to try resolve this problem, please help me >_<

Error is:
>(node:65357) UnhandledPromiseRejectionWarning: QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
    at new QueryRunnerAlreadyReleasedError (/Users/jal/JalProject/boss/enum-platform-service/node_modules/typeorm/error/QueryRunnerAlreadyReleasedError.js:9:28)
    at MysqlQueryRunner.query (/Users/jal/JalProject/boss/enum-platform-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:148:19)
    at MysqlQueryRunner.<anonymous> (/Users/jal/JalProject/boss/enum-platform-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:93:55)
    at step (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:120:57)
    at /Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:109:16)
    at MysqlQueryRunner.startTransaction (/Users/jal/JalProject/boss/enum-platform-service/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:78:24)
    at EntityPersistExecutor.<anonymous> (/Users/jal/JalProject/boss/enum-platform-service/node_modules/typeorm/persistence/EntityPersistExecutor.js:132:58)
    at step (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/Users/jal/JalProject/boss/enum-platform-service/node_modules/tslib/tslib.js:110:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:65357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:65357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

this is my code:

```js
return await getManager().transaction(async (transactionalEntityManager) => {
      // 使用事务方式插入枚举属性
      const insertAttribute = async (attrInfo, pushAttrInfo) => {
        const newAttr = new Attribute()
        const initData = {
          en: attrInfo.en,
          zh: attrInfo.zh,
          name: attrInfo.name,
          value: attrInfo.value,
          level: attrInfo.level,
          sequence: attrInfo.sequence,
          status: attrInfo.status,
          parentId: pushAttrInfo.parentId,
          enumId: pushAttrInfo.enumId,
        }
        Object.assign(newAttr, initData)
        const result = await transactionalEntityManager.save(newAttr)
        const finallyExtraList: ExtraAttribute[] = attrInfo.extraList.map(extra => {
          const e = {
            enumAttributeKey: extra.enumAttributeKey,
            name: extra.name,
            zh: extra.zh,
            en: extra.en,
  
            creator: staffId,
            gmtCreate: nowDate,
            gmtModified: nowDate,
            modifier: staffId,
  
            isDelete: 0,
            enumAttributeId: result.id,
          }
          const data = new ExtraAttribute()
          Object.assign(data, e)
          return data
        })

        const extraResult = await transactionalEntityManager.save(finallyExtraList)
        console.log('extraResult', extraResult)
        return {
          ...result,
          extraResult
        };
      }

// ........
await insertAttribute(attrInfo, pushAttrInfo);

// ........
  }).catch(e => {
    console.log('e', e)
    throw new Error(e)
  })
```

## Current environment
- nodejs: 16.14
- mysql: 5.7

## Current Dependencies
- "@nestjs/common": "^7.4.2",
- "@nestjs/core": "^7.4.2",
- "@nestjs/typeorm": "^7.1.0",

## Current behavior
throw QueryRunnerAlreadyReleasedError

## Expected behavior
`transactionalEntityManager.save(finallyExtraList)` could run successfully

**Comment by neos1803** [comment]
I have encountered the same issue and fixed by mapping my looping of an array in Promise.all. In your case, you might need to change and wrap your .map as a Promise. AFAIK map, forEach or traditional for loop is a synchrounous operation, so using it as a non-promise dependable unit in an async function might cause a problem.

Maybe, this answer from stackoverflow will be much help, because i solve my problem by using it as a reference.
https://stackoverflow.com/questions/67554794/queryrunneralreadyreleasederror-when-executing-a-series-of-queries-in-a-single-t
