### ISSUE TITLE
In PostgreSQL Driver, "Cannot read property 'toUpperCase' of null" while generating a migration

### ISSUE THREAD

**Issue by sylvainar** [typeorm/typeorm#8172]
### Expected Behavior

Migration generation should work.

### Actual Behavior

I just upgraded from 0.2.31 to 0.2.37, everything was working fine, but now, when I try to generate a migration, I have the following error.
```
 ✘  ~/Workspace/api   2153-typeorm-generate-cleanup ±✚  yarn typeorm migration:generate -n Cleanup
yarn run v1.22.10
$ cross-env NODE_PATH=src/ ts-node --transpile-only ./node_modules/typeorm/cli.js migration:generate -n Cleanup
Error during migration generation:
TypeError: Cannot read property 'toUpperCase' of null
    at PostgresDriver.normalizeDatetimeFunction (/home/sylvain/Workspace/api/src/driver/postgres/PostgresDriver.ts:1173:38)
    at PostgresDriver.normalizeDefault (/home/sylvain/Workspace/api/src/driver/postgres/PostgresDriver.ts:814:25)
    at PostgresDriver.defaultEqual (/home/sylvain/Workspace/api/src/driver/postgres/PostgresDriver.ts:844:70)
    at /home/sylvain/Workspace/api/src/driver/postgres/PostgresDriver.ts:975:55
    at Array.filter (<anonymous>)
    at PostgresDriver.findChangedColumns (/home/sylvain/Workspace/api/src/driver/postgres/PostgresDriver.ts:963:32)
    at /home/sylvain/Workspace/api/src/schema-builder/RdbmsSchemaBuilder.ts:546:59
    at step (/home/sylvain/Workspace/api/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/sylvain/Workspace/api/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at step (/home/sylvain/Workspace/api/node_modules/typeorm/node_modules/tslib/tslib.js:128:143)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have a pretty massive codebase and I don't know where to start in order to give a minimum example that reproduce, so any help is appreciated.

### Steps to Reproduce

I don't know, I seek advice for this part.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Kubuntu 20.04    |
| Node.js version     | 12.18.3  | 
| Typescript version  | 4.2.3  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by usualdesigner** [comment]
> I'm not entirely sure but it may be because in some `default` keys I put `default: ()=> something` instead of `something`.

I can confirm that it's definitely it

**Comment by sylvainar** [comment]
Great!
