### ISSUE TITLE
Cannot read property 'joinColumns' of undefined (EntitySchema)

### ISSUE THREAD

**Issue by Hiroki111** [typeorm/typeorm#8199]
## Issue Description

An `Entity` is throwing a following error when I use `find` method with it.

```
TypeError: Cannot read property 'joinColumns' of undefined
      at /Users/myapp/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1098:58
```

I've found similar issues on Github ([2587](https://github.com/typeorm/typeorm/issues/2587) and [2603](https://github.com/typeorm/typeorm/issues/2603)), but both are concerning `@Entity`, while I'm using `EntitySchema`.

Here are snippets of the entities.
```
export const ServiceEntity = new EntitySchema<Service>({
    name: 'services',
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true,
        },
        serviceTypeId: {
            name: 'service_type_id',
            type: Number,
        },
    // other fields
    },
    relations: {
        serviceType: {
            type: 'many-to-one',
            target: 'service_types',
        },
    },
});

export const ServiceTypeEntity = new EntitySchema<ServiceType>({
    name: 'service_types',
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true,
        },
    // other fields
    },
    relations: {
        services: {
            type: 'one-to-many',
            target: 'services',
            eager: true,
        },
    },
});
```
As you can imagine, one service type has many services.

I'm trying to get service types with their relevant services with

```
import { getRepository } from 'typeorm';

const getServiceTypes = () => {
  return getRepository(ServiceTypeEntity).find();
}
```

This result in the error that was mentioned at the beginning. It says joinColumn"**s**" of undefined, but I don't see what it is on the doc (I can see some explanations of "joinColumn", not "joinColumn**s**").

### Expected Behavior

`getRepository(ServiceTypeEntity).find()` in the above example returns all the records in the DB table (if there are records there) without any error.

### Actual Behavior

```
TypeError: Cannot read property 'joinColumns' of undefined
      at /Users/myapp/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1098:58
      at Array.map (<anonymous>)
      at SelectQueryBuilder.createJoinExpression (/Users/myapp/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1074:55)
      at SelectQueryBuilder.getQuery (/Users/myapp/node_modules/typeorm/query-builder/SelectQueryBuilder.js:49:21)
      at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (/Users/myapp/node_modules/typeorm/query-builder/QueryBuilder.js:244:26)
      at SelectQueryBuilder.<anonymous> (/Users/myapp/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1615:50)
      at step (/Users/myapp/node_modules/tslib/tslib.js:143:27)
      at Object.next (/Users/myapp/node_modules/tslib/tslib.js:124:57)
      at /Users/myapp/node_modules/tslib/tslib.js:117:75
      at new Promise (<anonymous>)
```

### Steps to Reproduce

1.
2.

```typescript
export interface ServiceType {
    id: number;
    name: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    // relations
    services: Service[]; 
}

export interface Service {
    id: number;
    serviceTypeId: number;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    serviceType?: ServiceType;
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Mac OS     |
| Node.js version     | 12.21.0  |
| Typescript version  | 4.3.4  | 
| TypeORM version     | ^0.2.32  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| `postgres`           | yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Hiroki111** [comment]
PS

```
export const ServiceTypeEntity = new EntitySchema<ServiceType>({
    name: 'service_types',
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true,
        },
    // other fields
    },
    relations: {
        services: {
            type: 'one-to-many',
            target: 'services',
            // eager: true, // Removed
        },
    },
});
```

After removing `eager: true`, the error was gone. It seems `EntitySchema` can't do eager-loading.
Is this an error or the expected behaviour?

**Comment by ericaskari** [comment]
I have the same issue

```
  @OneToOne(() => StravaSummaryActivity, { eager: true, nullable: true })
  strava: StravaSummaryActivity | null = null;

  @OneToOne(() => GarminDetailedActivity, { eager: true, nullable: true })
  garmin: GarminDetailedActivity | null = null;

```

and removing eager will resolve the issue.

`"typeorm": "^0.2.9"`

**Comment by carlosdaniiel07** [comment]
I have the same issue too. I tried to replace `eager: true` by including the relations name on `repository.find()` method and the error was back. This [solution](https://github.com/typeorm/typeorm/issues/3073#issuecomment-522279347]) worked for me!
