### ISSUE TITLE
Using `leftJoinAndSelect`, `orderBy`, and `take` / `skip` at the same time will cause "TypeError: Cannot read property 'databaseName' of undefined".

### ISSUE THREAD

**Issue by chrg1001** [typeorm/typeorm#8213]
## Issue Description

Using `leftJoinAndSelect`, `orderBy`, and `take` / `skip` at the same time will cause "TypeError: Cannot read property 'databaseName' of undefined".

I think this problem is related to #4270 and #3356.

### Expected Behavior

No errors.

### Actual Behavior

```bash
 TypeError: Cannot read property 'databaseName' of undefined
      at src/query-builder/SelectQueryBuilder.ts:2057:139
          at Array.map (<anonymous>)
      at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.createOrderByCombinedWithSelectExpression (src/query-builder/SelectQueryBuilder.ts:2050:14)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:1954:46)       
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at node_modules/typeorm/node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
      at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.executeEntitiesAndRawResults (node_modules/typeorm/query-builder/SelectQueryBuilder.js:1460:24)
```

#### Query

See the simple query example below. Please, refer to the code below for `CompanyEntity` and `UserEntity`.

This will work properly.

```typescript
await typeorm.getManager()
	.createQueryBuilder()
	.select('user')
	.from(UserEntity, 'user')
	.leftJoinAndSelect('user.company', 'company')
	.orderBy('company.created_at', 'ASC')
	.getManyAndCount();
```

All of the following codes will give the above error. (Any code will work correctly if you use `getSql()` instead of `getManyAndCount()`.)

```typescript
await typeorm.getManager()
	.createQueryBuilder()
	.select('user')
	.from(UserEntity, 'user')
	.leftJoinAndSelect('user.company', 'company')
	.orderBy('company.created_at', 'ASC')
	.take(10)
	.skip(1)
	.getManyAndCount();
```

```typescript
await typeorm.getManager()
	.createQueryBuilder()
	.select('user')
	.from(UserEntity, 'user')
	.leftJoinAndSelect('user.company', 'company')
	.orderBy('company.created_at', 'ASC')
	.take(10)
	// .skip(1)
	.getManyAndCount();
```

```typescript
await typeorm.getManager()
	.createQueryBuilder()
	.select('user')
	.from(UserEntity, 'user')
	.leftJoinAndSelect('user.company', 'company')
	.orderBy('company.created_at', 'ASC')
	// .take(10)
	.skip(1)
	.getManyAndCount();
```

#### CompanyEntity

```typescript
@Entity('company')
export class CompanyEntity {
  @PrimaryGeneratedColumn({ type: 'int', unsigned: true })
  readonly id!: number;

  @CreateDateColumn({ type: 'datetime' })
  createdAt!: Date;
}
```

#### UserEntity

```typescript
@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn({ type: 'int', unsigned: true })
  readonly id!: number;

  @ManyToOne(() => CompanyEntity, (company) => company.id)
  @JoinColumn({ referencedColumnName: 'id' })
  company?: CompanyEntity | null;
  @Column({ type: 'int', unsigned: true })
  companyId!: number;
}
```

### Possible causes

As the error shows, there is a problem with this line. `column` in line 2056 is `undefined`.

https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/query-builder/SelectQueryBuilder.ts#L2045-L2058

If the `orderCriteria` is `'company.created_at'`, then the `propertyPath` will be `'created_at'`. In other words, it is still a snake case, as specified in the QueryBuilder.

Now, if you look at the definition of `findColumnWithPropertyPath` on line 2056, you will see this.

https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/metadata/EntityMetadata.ts#L656-L668

However, the `column.propertyPath` in line 657 is the same as the variable name in the Entity definition, so it is `'createdAt'`, which is a camel case. So the expression `column.propertyPath` === `propertyPath` will never be true.

This is why `column` is `undefined` in line 2056.

So, despite using `skip` / `take`, `orderBy` and `leftJoinAndSelect` at the same time, the following code works correctly. However, I don't think this is a fundamental solution.

```typescript
await typeorm.getManager()
	.createQueryBuilder()
	.select('user')
	.from(UserEntity, 'user')
	.leftJoinAndSelect('user.company', 'company')
	// Convert 'created_at' into camel case according to column definition
	.orderBy('company.createdAt', 'ASC')
	.take(10)
	.skip(1)
	.getManyAndCount();
```

Probably the problem is that the `propertyPath` passed to `findColumnWithPropertyPath` is not handled correctly, unlike for example `.leftJoinAndSelect()`, which works correctly whether you specify column name as snake case or camel case.

A possible solution would be to convert the `propertyPath` correctly to match the Entity definition as described above, but I don't know what function to use to do this.

https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/query-builder/SelectQueryBuilder.ts#L2049-L2065

However, I'm not sure if this method will solve #4270 or #3356.

### My Environment

| Dependency         | Version |
| ------------------ | ------- |
| Operating System   |         |
| Node.js version    | 12.22.1 |              |
| Typescript version | 4.4.2   |  |
| TypeORM version    | 0.2.37  |     |

### Relevant Database Driver(s)

| DB Type              | Reproducible |
| -------------------- | ------------ |
| `aurora-data-api`    | no           |
| `aurora-data-api-pg` | no           |
| `better-sqlite3`     | no           |
| `cockroachdb`        | no           |
| `cordova`            | no           |
| `expo`               | no           |
| `mongodb`            | no           |
| `mysql`              | yes          |
| `nativescript`       | no           |
| `oracle`             | no           |
| `postgres`           | no           |
| `react-native`       | no           |
| `sap`                | no           |
| `sqlite`             | no           |
| `sqlite-abstract`    | no           |
| `sqljs`              | no           |
| `sqlserver`          | no           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by akshaysasidrn** [comment]
Is there any workaround for this until this is fixed? If I make use of raw SQL query, is there an internal API to convert it to an entity?

**Comment by skanygin** [comment]
Possible solution - remove double quotes https://github.com/typeorm/typeorm/issues/747#issuecomment-491585082

**Comment by pahan35** [comment]
@pleerock is it possible to fix this problem? Are there any possible pitfalls?

Please share some info from your side.

If it's possible to fix it and you will welcome the fix and merge it into a master, and can take a look and try to figure out what's wrong here and fix it.

**Comment by devangpatel21** [comment]
@chrg1001 @pleerock your issue is because of the wrong name passed for in orderBy 
instead of .orderBy('company.created_at', 'ASC') it should be .orderBy('company.createdAt', 'ASC')
as you have declared entity in camelCase "createdAt!: Date;"

**Comment by eduardobdamacena** [comment]
@devangpatel21 worked for me! I have declared entity in camelCase.

**Comment by jackykwan-eventx** [comment]
this case is valid, we just faced same bug

**Comment by grgward108** [comment]
I am also having trouble with this exact bug.
