### ISSUE TITLE
PostgreSQL migrations not working 

### ISSUE THREAD

**Issue by NomadXD** [typeorm/typeorm#8230]
## Issue Description

When I try to run migrations with `typeorm migration:run` for a project which is generated using NestJS and which uses postgresql, I get the following error.

```
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: ROLLBACK
Error during migration run:
TypeError: target.split is not a function
    at PostgresDriver.parseTableName (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresDriver.js:720:28)
    at PostgresQueryRunner.<anonymous> (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:411:55)
    at step (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
    at PostgresQueryRunner.hasTable (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:406:24)
    at PostgresQueryRunner.<anonymous> (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:557:51)
    at step (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
``` 

### Expected Behavior

Run the migration properly without giving errors.

### Actual Behavior

`typeorm migration:run` fails giving the above mentioned error. However in NestJS, they have the option to run the migrations automatically using `synchronize: true` and it works without any issue. Only the manual run with `typeorm migration:run` fails. (That being said I don't know whether during startup NestJS uses typeorm or directly use the pg driver). 

```
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: ROLLBACK
Error during migration run:
TypeError: target.split is not a function
    at PostgresDriver.parseTableName (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresDriver.js:720:28)
    at PostgresQueryRunner.<anonymous> (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:411:55)
    at step (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
    at PostgresQueryRunner.hasTable (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:406:24)
    at PostgresQueryRunner.<anonymous> (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:557:51)
    at step (/home/nomadxd/.nvm/versions/node/v12.22.6/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
```

### Steps to Reproduce

1. Generate a project using NestJS cli or any nodejs simple project.
2. Add the `ormconfig.json` file with the required configuration.
Eg: 
```json
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "abc",
  "password": "qwerty123",
  "database": "nestjs",
  "entities": [
    "dist/**/*.entity{.ts,.js}"
  ],
  "migrations": [
    "dist/migrations/*.js"
  ],
  "cli": {
    "migrationsDir": "src/migrations"
  }
}
```
3.  Create a migration with `typeorm migration:create -n TestMigration`
4. Add some SQL or Migration API code to up/down functions.
5. Run the migrations using `typeorm migration:run`. 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Ubuntu 20.04 LTS     |
| Node.js version     | v14.16.1  | 
| Typescript version  | typescript@4.4.2  | 
| TypeORM version     | typeorm@0.2.37  | 

### Additional Context

The same issue is there in #7170 but the issue is stale for **nearly 10 months now.**

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by NomadXD** [comment]
**For anyone having the same issue,**

Instead of installing the typeorm cli globally and using that, use npx to call the locally installed typeorm. Instead of typeorm migration:run, use npx typeorm migration:run and it works. I checked the versions and both are 0.2.37 but the local works and the global doesn't work. Strange issue.

**Comment by leoBarrosDev** [comment]
Olá! Estou com o mesmo problema, e mesmo executando com o npx chamando o typeorm local continua dando erro
