### ISSUE TITLE
TypeError: Cannot read property 'createValueMap' of undefined at EntityMetadata.ensureEntityIdMap()

### ISSUE THREAD

**Issue by maka-io** [typeorm/typeorm#8257]
## Issue Description
When using a @ViewEntity instead of an @Entity as a Repository, accessing certain instance methods of a Repository instance causes a TypeError to be thrown:

Specifically, the instance method: `.findOne()`

TypeError: Cannot read property 'createValueMap' of undefined

https://github.com/typeorm/typeorm/blob/861573377bb33b73232399c21b1b3a5c07b58036/src/metadata/EntityMetadata.ts#L579
### Expected Behavior
@ViewEntity as a Repository to behave the same as @Entity when accessing various instance methods, as their signatures pass type checking.

### Actual Behavior
A TypeError exception is thrown:

```
TypeError: Cannot read property 'createValueMap' of undefined
     at EntityMetadata.ensureEntityIdMap (/.../node_modules/typeorm/metadata/EntityMetadata.js:298:39)
     at EntityManager.<anonymous> (/.../EntityManager.js:536:47)
```

### Steps to Reproduce
1. Create a ViewEntity:
```
import {ViewEntity, ViewColumn, Connection} from "typeorm";
@ViewEntity({
  name: 'v_user',
  expression: `
    SELECT
      "id",
      "name",
      "email"
  `
})
export class UserView {
    @ViewColumn()
    id: number;
    @ViewColumn()
    name: string;
    @ViewColumn()
    email: string;
}
```

2. Create a class that accepts the ViewEntity as a Repository:
```
import {Injectable} from '@nestjs/common';
import {InjectRepository} from "@nestjs/typeorm";
import {Connection, createQueryBuilder, InsertResult, Repository} from "typeorm";

import {UserView} from "../userViewEntity";

@Injectable()
export class UserService {
    constructor(
        @InjectRepository(UserView)
        readonly userRepository: Repository<UserView>
    ) {
    }

    async getUserName(id: number) {
        const user: UserView = await this.userRepository.findOne(id);
        return user.name;
    }
}
```
3. Instantiate the class and attempt to get a user by id.
```
const userService = new UserService();
const userName = userService.getUserName(1);
console.log(userName);
```

4. Error:
```
TypeError: Cannot read property 'createValueMap' of undefined
     at EntityMetadata.ensureEntityIdMap (/.../node_modules/typeorm/metadata/EntityMetadata.js:298:39)
     at EntityManager.<anonymous> (/.../EntityManager.js:536:47)
```

5. Replace getUserName:
```
    async getUserName(id: number) {
            const user: UserView = await this.userRepository.createQueryBuilder()
              .where('id = :id', { id }).getOne();
        return user.name;
    }
```

6. This works !

### My Environment

| Dependency          | Version  |
| NestJs                 |  7.6.18      |
| Operating System    | MacOS 11.6 (Bug Sur)  |
| Node.js version     | v14.17.5  | 
| Typescript version  | v3.9.18  | 
| TypeORM version     | v0.2.37  | 

### Relevant Database Driver(s)
| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by devx-opensource** [comment]
Hi, 

For your information, I have the exact same behavior with the lastest Typeform version (0.2.45).

**Comment by leite08** [comment]
Same here. Using `findOneOrFail()` results in `Cannot read property 'createValueMap' of undefined`.

Using `find()` works - but it requires additional code to keep type safety.
