### ISSUE TITLE
Intermediate table with two primary key make parent entity to fail when save due conflict

### ISSUE THREAD

**Issue by alanszp** [typeorm/typeorm#8272]
## Issue Description
The problem start on v0.2.32, when you want to save an Entity which has a ManyToOne relation with other entity with 2 primary keys. It breaks with a conflict error on the DB-side, but the problem is from typeorm, making UPDATE statements to the second relation when it shouldn't.

I created a repo to reproduce the problem: https://github.com/alanszp/typeorm-bug-report

In my case, I want to create an intermediate entity in a Many to Many relation to add custom attributes to the relation. Ej: ordered lists.

In the main branch you will see that there are 3 entities: `List` ---> `OrderedItem` <--- `Item`

In a normal Many to Many relation, I would just do `List` <---> `Item` without creating `OrderedItem`. but, as in my domain, Items in lists should be ordered, I need to add a param `order` in the intermediate table.

In OrderedItem, I want to use `listId` & `itemId` to be the primary keys as a common intermediate table.
And here the problems begins.

I can create the objects without problem.
But when I eager fetch again the List (with it's relations), and then try to save it (no matter if I made a change on the entity or the relations), the save operation will fail:

### Expected Behavior

Just save the entity without modifying the related ones.
In fact, this is a bug introduced on version v0.2.32, because on version v0.2.31 it works. I made also an example, only changing the version: https://github.com/alanszp/typeorm-bug-report/tree/past-version-works-ok

As stated in this issue: https://github.com/typeorm/typeorm/issues/7736#issuecomment-908249092

The problem might be in this commit: 7fe723b#diff-d7ca1d76c1ec2ccba6afd5a97313e55e8c1cb0dcb8ce2cadc927fc9a6891c521L549-R549

### Actual Behavior

Here is a dump of the operationts it tries to make:

``` 
query: SELECT "List"."id" AS "List_id", "List"."name" AS "List_name" FROM "lists" "List" WHERE "List"."id" IN (?) -- PARAMETERS: [1]
query: SELECT "ordered_items"."listId" AS "listId", "ordered_items"."itemId" AS "itemId" FROM "ordered_items" "ordered_items" WHERE (("ordered_items"."listId" = ?)) -- PARAMETERS: [1]
query: BEGIN TRANSACTION
query: UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?) -- PARAMETERS: [1,1,2]
query: UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?) -- PARAMETERS: [1,1,1]
query: UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?) -- PARAMETERS: [null,1,1]
query: UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?) -- PARAMETERS: [null,1,2]
query failed: UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?) -- PARAMETERS: [null,1,1]
error: Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: ordered_items.listId
--> in Database#all('UPDATE "ordered_items" SET "listId" = ? WHERE ("listId" = ? AND "itemId" = ?)', [ undefined, 1, 1 ], [Function: handler])
    at SqliteQueryRunner.<anonymous> (/Users/alan/dev/meetlara/test/src/driver/sqlite/SqliteQueryRunner.ts:60:40)
    at step (/Users/alan/dev/meetlara/test/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/alan/dev/meetlara/test/node_modules/tslib/tslib.js:124:57)
    at /Users/alan/dev/meetlara/test/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/alan/dev/meetlara/test/node_modules/tslib/tslib.js:113:16)
    at execute (/Users/alan/dev/meetlara/test/src/driver/sqlite/SqliteQueryRunner.ts:56:29)
    at SqliteQueryRunner.<anonymous> (/Users/alan/dev/meetlara/test/src/driver/sqlite/SqliteQueryRunner.ts:105:19)
    at step (/Users/alan/dev/meetlara/test/node_modules/tslib/tslib.js:143:27) {
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  __augmented: true
}
query: ROLLBACK
``` 

### Steps to Reproduce

I created a repo to reproduce the problem: https://github.com/alanszp/typeorm-bug-report

### My Environment

I created a repo to reproduce the problem: https://github.com/alanszp/typeorm-bug-report

### Additional Context

Nop

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by alanszp** [comment]
Hi! Wanted to check out if you could see this, because this is a breaking change since version 0.2.32

**Comment by fxvits** [comment]
Hey there,

I'm using version 0.2.41 over sqlite 3.2.1 and the issue persist. Any progress on it or a workaround ?
This is quite major issue

**Comment by alanszp** [comment]
Hi Team!

I just created a new branch using the latest version: 0.3.0: https://github.com/alanszp/typeorm-bug-report/tree/v0.3

It's still happening and it's a big bug for ManyToMany relations

**Comment by alanszp** [comment]
@fxvits @mojodna @drnic @dpickett @pleerock  this is a mayor bug. I coded  a working reproduction of the error and  still its present on the last release  https://github.com/alanszp/typeorm-bug-report/tree/v0.3
