### ISSUE TITLE
"Duplicate entry" error when trying to update entity using "save()"

### ISSUE THREAD

**Issue by mapokapo** [typeorm/typeorm#8336]
## Issue Description
TypeORM throws a "Duplicate entry ... for key 'PRIMARY'" error when trying to update an entity by using the `save()` method.

### Expected Behavior
If we supply the `save()` method with a partial DTO of the entity (including the id of the entity), it should update the row in the database with that id, instead of trying to insert a new row (which would obviously cause an error).

### Actual Behavior
TypeORM tries inserting a new row in the database instead of updating an existing row.

```
QueryFailedError: Duplicate entry '7' for key 'PRIMARY'
    at QueryFailedError.TypeORMError [as constructor] (...\src\error\TypeORMError.ts:7:9)
    at new QueryFailedError (...\src\error\QueryFailedError.ts:9:9)
    at Query.onResult (...\src\driver\mysql\MysqlQueryRunner.ts:195:37)
    at Query.execute (...\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (...\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket ...\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (...\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (...\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
```

### Steps to Reproduce
1. Get the entity in the database using the `find()` method
2. Change some properties on the entity (using eg. `Object.assign()`)
3. Save the entity in the database by using the `save()` method

```typescript
let entity = this.repository.findOne(dto.id);
Object.assign(entity, dto);
this.repository.save(entity);
```

### My Environment
My project was made in NestJS and I am using `class-validator` and `class-transformer` libraries for the entity and DTO classes.
| Dependency | Version |
| --- | --- |
| Operating System | Microsoft Windows 10 Enterprise LTSC Version 10.0.17763 Build 17763 |
| Node.js version | 16.7.0  |
| Typescript version | 4.3.5 |
| TypeORM version | 0.2.38 |
| NestJS version | 8.0.0 |
| class-validator version | 0.13.1 |
| class-transformer version | 0.4.0 |

### Additional Context
This is what my **entity class** looks like (user entity):
```
@Entity()
export class User {
	@PrimaryGeneratedColumn()
	id: number;

	@Column({ unique: true })
	username: string;

	@Column({ unique: true })
	email: string;

	@Exclude()
	@Column()
	password: string;

	@BeforeInsert()
	async hashPassword() {
		this.password = await bcrypt.hash(this.password, 10);
	}

	@BeforeUpdate()
	async hashPasswordBeforeUpdate() {
		if (this.password) this.password = await bcrypt.hash(this.password, 10);
	}

	@Exclude()
	@Column({ nullable: true })
	refreshToken?: string;

	@BeforeInsert()
	async hashRefreshToken() {
		if (this.refreshToken)
			this.refreshToken = await bcrypt.hash(this.refreshToken, 10);
	}

	@BeforeUpdate()
	async hashRefreshTokenBeforeUpdate() {
		if (this.refreshToken)
			this.refreshToken = await bcrypt.hash(this.refreshToken, 10);
	}

	@OneToMany(() => Todo, todo => todo.user)
	todos: Todo[];

	@Exclude()
	@Column("bool")
	blocked = false;
}
```

and my **entity update DTO**:
```
export class UpdateUserDto extends PartialType(RegisterUserDto) {
	@IsNumber()
	id: number;
}
```
which extends from the RegisterUserDto (**entity create DTO**):
```
export class RegisterUserDto {
	@IsAlphanumeric()
	readonly username: string;

	@IsString()
	@MinLength(8)
	readonly password: string;

	@IsEmail()
	readonly email: string;

	@IsArray({
		each: true,
	})
	readonly todos?: Todo[] = [];
}
```

Note: I need to use the `save()` method to update the entity in the database because using the `update()` method does not trigger the `@BeforeUpdate()` methods in the entity which are required for hashing sensitive data before it is inserted into the database.

### Relevant Database Driver(s)
| DB Type | Reproducible |
| --- | --- |
| `mariadb` | yes |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by mapokapo** [comment]
Update: it seems as if using update() does actually trigger the @BeforeUpdate() method when trying to update the entity in the database.

```
const entity = this.repository.find(dto.id);
await this.repository.update({ id: dto.id }, Object.assign(entity, dto));
return entity;
```
