### ISSUE TITLE
Regression using built-in SQL functions in queries

### ISSUE THREAD

**Issue by andrewda** [typeorm/typeorm#8337]
## Issue Description

I am using the following query to find the 20 least-recently updated rows in my table with a `startTime` in the past.

```ts
this.eventRepository
  .find({
    where: {
      startTime: LessThan(() => 'NOW()'),
      state: In([State.Upcoming, State.Live]),
    },
    order: { updatedAt: 'ASC' },
    select: ['id'],
    take: 20,
  });
```

In version `0.2.34` this query works as expected and returns the correct response. However, I just upgraded to `0.2.38` and began receiving the following error.

```
TypeORMError: Function parameter isn't supported in the parameters. Please check "orm_param_0" parameter.
    at new TypeORMError (/home/node/src/error/TypeORMError.ts:7:9)
    at SelectQueryBuilder.QueryBuilder.setParameter (/home/node/src/query-builder/QueryBuilder.ts:347:19)
    at SelectQueryBuilder.QueryBuilder.createParameter (/home/node/src/query-builder/QueryBuilder.ts:380:14)
    at SelectQueryBuilder.QueryBuilder.getWherePredicateCondition (/home/node/src/query-builder/QueryBuilder.ts:1114:42)
    at SelectQueryBuilder.QueryBuilder.getWhereCondition (/home/node/src/query-builder/QueryBuilder.ts:1211:37)
    at SelectQueryBuilder.where (/home/node/src/query-builder/SelectQueryBuilder.ts:721:32)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (/home/node/src/find-options/FindOptionsUtils.ts:184:16)
    at Function.FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder (/home/node/src/find-options/FindOptionsUtils.ts:72:25)
    at EntityManager.<anonymous> (/home/node/src/entity-manager/EntityManager.ts:677:26)
    at step (/home/node/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/node/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /home/node/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/node/node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
    at EntityManager.find (/home/node/node_modules/typeorm/entity-manager/EntityManager.js:448:24)
    at Repository.find (/home/node/src/repository/Repository.ts:305:29)
```

It seems that this is a result of `LessThan(() => 'NOW()')`, which _should_ equate to `< NOW()` in Postgres. As a temporary fix, `LessThan(new Date().toISOString())` can be used for a nearly equivalent result, although I would much prefer going back to using built-in SQL functions.

### Expected Behavior

The query should complete successfully, substituting `LessThan(() => 'NOW()')` for `< NOW()` in SQL.

### Actual Behavior

As mentioned, a "Function parameter isn't supported in the parameters" error is thrown.

### Steps to Reproduce

Consider the following example entity:

```typescript
export enum State {
  Upcoming = 'upcoming',
  Live = 'live',
  Complete = 'complete',
}

@Entity()
export class Event {
  @PrimaryColumn()
  id: string;

  @Column('timestamptz', { nullable: true })
  startTime?: Date;

  @Column({ default: State.Upcoming })
  @Index()
  state: State;

  @UpdateDateColumn()
  updatedAt: Date;
}
```

The following query will cause a "Function parameter isn't supported in the parameters" error:

```ts
this.eventRepository
  .find({
    where: {
      startTime: LessThan(() => 'NOW()'),
      state: In([State.Upcoming, State.Live]),
    },
    order: { updatedAt: 'ASC' },
    select: ['id'],
    take: 20,
  });
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Amazon Linux |
| Node.js version     | `14.18.1` | 
| Typescript version  | `4.2.4`  | 
| TypeORM version     | `0.2.38`  | 

### Relevant Database Driver(s)

(only confirmed in Postgres, although I believe this will apply to all SQL database drivers)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by andrewda** [comment]
After digging around a little more, I came across the `Raw()` function. Unfortunately, the following query still fails, albeit with a different error: `QueryFailedError: column "undefined" does not exist`

```ts
this.eventRepository
  .find({
    where: {
      startTime: LessThan(Raw('NOW()')),
      state: In([State.Upcoming, State.Live]),
    },
    order: { updatedAt: 'ASC' },
    select: ['id'],
    take: 20,
  });
```

The raw SQL returned from the error message:

```sql
SELECT "Event"."id" AS "Event_id" FROM "event" "Event" WHERE ("Event"."startTime" < undefined AND "Event"."state" IN ($1, $2)) ORDER BY "Event"."updatedAt" ASC LIMIT 20
```

**Comment by mickaelmesdocteurs** [comment]
You can't use a function as parameter for LessThan.
That's why `LessThan(() => 'NOW()')` will result in `TypeORMError: Function parameter isn't supported in the parameters.`
Why don't you use a js date like this : 
```js
this.eventRepository
  .find({
    where: {
      startTime: LessThan(new Date()),
      state: In([State.Upcoming, State.Live]),
    },
    order: { updatedAt: 'ASC' },
    select: ['id'],
    take: 20,
  });
```

**Comment by andrewda** [comment]
@mickaelmesdocteurs I definitely _can_ do it that way in this specific use case, but it's less than ideal. SQL has built-in time/date functions for a reason, and I'd like to use them when they're available. Although not crucial in this specific instance, there are many cases where I would want to use the date at query-time on the SQL server, rather than at request-time. The latency could, at times, be in the order of 10s of ms, which could be the difference between returning a result or not.

**Comment by mohd-akram** [comment]
I came across this issue as well. I'm trying to use `LessThan(Raw("datetime('now')"))`. Is this supposed to work? If not, why?
