### ISSUE TITLE
Error 'SQLitePlugin: java.lang.NullPointerException' on cordova connection

### ISSUE THREAD

**Issue by capkverna** [typeorm/typeorm#8344]
## Issue Description

When trying to create connection with createConnection using cordova on Android 11 devices. The app was running normally before, but when i changed the targetSdkVersion to 30 the problem started. When i run in debug mode on my emulator never happens, but when i generate the release and update the app on some devices the bug starts.

### Expected Behavior

createConnection executes and return the connection object.

```
	let options = {
	  type: 'cordova',
	  database: '_exemplo.db',
	  location: 'default',
	  logging: ['error'],
	  synchronize: true,
	  entities: [...]	  
	}
	createConnection(options)
	...
```

### Actual Behavior

createConnection crashes with error 'Could not open database' and the android log as seen below:

```
11-09 14:49:31.715  1877  2142 V SQLitePlugin: Android db implementation: built-in android.database.sqlite package
11-09 14:49:31.716  1877  2143 V info    : Open sqlite db: /data/user/0/br.com.exemplo.exmeplomobile/databases/_exemplo.db
11-09 14:49:31.716  1877  2143 E SQLitePlugin: unexpected error, stopping db thread
11-09 14:49:31.716  1877  2143 E SQLitePlugin: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String io.liteglue.SQLDatabaseHandle.getLastErrorMessage()' on a null object reference
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.liteglue.SQLiteGlueConnection.<init>(SQLiteGlueConnection.java:12)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.liteglue.SQLiteConnector.newSQLiteConnection(SQLiteConnector.java:20)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.sqlc.SQLiteConnectorDatabase.open(SQLiteConnectorDatabase.java:55)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.sqlc.SQLitePlugin.openDatabase(SQLitePlugin.java:213)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.sqlc.SQLitePlugin.access$000(SQLitePlugin.java:28)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:328)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-09 14:49:31.716  1877  2143 E SQLitePlugin: 	at java.lang.Thread.run(Thread.java:923)
11-09 14:49:31.729  1877  1877 D SystemWebChromeClient: http://localhost/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 175 : OPEN database: _exemplo.db
```

### Steps to Reproduce

1. Using the targetSdkVersion 28 create a connection and populate the database.
2. After that, change the targetSdkVersion to 30 and try to connect in the same database.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Android 11 |
| Node.js version     | 10.15.2  |
| Typescript version  | 2.6.2  |
| TypeORM version     | 0.2.24  |
| ionic-angular       | 3.9.2  |
| cordova-android     | 8.1.0  |
| @ionic/app-scripts  | 3.2.3  |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | yes            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by bitiodev** [comment]
same problem.
Help me!!
