### ISSUE TITLE
Postgres: migration:generate creating SQL that doesn't run on Postgres

### ISSUE THREAD

**Issue by scottlovegrove** [typeorm/typeorm#8384]
### Expected Behavior

When running the `migration:generate` command, it should create SQL that correctly works on the specified database type.

### Actual Behavior

This is the output I get after trying to run the migration

```
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: CREATE TABLE "migrations" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id"))
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: CREATE TABLE "user" ("id" NOT NULL, "emailAddress" character varying NOT NULL, "name" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "googleId" character varying NOT NULL, "avatarUrl" character varying, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))
query failed: CREATE TABLE "user" ("id" NOT NULL, "emailAddress" character varying NOT NULL, "name" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "googleId" character varying NOT NULL, "avatarUrl" character varying, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))
error: error: syntax error at or near "NOT"
    at Parser.parseErrorMessage (/home/scott/postgres-repro/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/scott/postgres-repro/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/scott/postgres-repro/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/scott/postgres-repro/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '27',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
Migration "Initial1636494066750" has been failed, error: syntax error at or near "NOT"
```

### Steps to Reproduce
[postgres-repro.zip](https://github.com/typeorm/typeorm/files/7565694/postgres-repro.zip)

1. Run `docker-compose -f docker-compose.db.yml up`, this will create a new postgres db container
2. Run `npm i`
3. Run `npm run build` to build the code
4. Run `npm run typeorm migration:run`, at this point, you will get a failure.

This migration file was created by running `npm run typeorm migration:generate -- -n Initial`. I've tried this in my main project and in the repro project, both result in the same SQL output in the migration files. 

If you wanted to create the migration file to see for yourself, just delete it from `src/migrations` and create using `npm run typeorm migration:generate -- -n Initial`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    WSL2 (Ubuntu 20.04)      |
| Node.js version     | 16.6.2  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.39  | 
| NestJS version | 8.0.1 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by scottlovegrove** [comment]
Ugh, having spent days trying to figure this out, I found the problem minutes after raising this issue 😫 

The problem was with my entities, I needed to use `@PrimaryGeneratedColumn('increment')` and not `@PrimaryGeneratedColumn({type: 'numeric'})`.

Now the SQL that's generated runs just fine.
