### ISSUE TITLE
Cannot Parse Entity

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#84]
I'm trying to create a typescript project useing type orm, i get the following error when running createConnection for the first time:

```
/usr/local/bin/node --debug-brk=64082 --expose_debug_as=v8debug /Users/jmurphy/projects/abc/api/node_modules/mocha/bin/_mocha --require ts-node/register --timeout 0 --ui bdd --reporter "/Applications/WebStorm 2016.3 EAP.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js" /Users/jmurphy/projects/abc/api/test/postgres.spec.ts --grep "The process of connecting to a database should create a source$"
Debugger listening on [::]:64082

/Users/jmurphy/projects/abc/api/node_modules/typeorm/metadata/types/metadata/types/ColumnTypes.ts:155
        return (type as any).name.toLowerCase();
                            ^
TypeError: Cannot read property 'name' of undefined
    at Function.typeToString (/Users/jmurphy/projects/abc/api/node_modules/typeorm/metadata/types/metadata/types/ColumnTypes.ts:155:29)
    at /Users/jmurphy/projects/abc/api/node_modules/typeorm/decorator/columns/decorator/columns/PrimaryGeneratedColumn.ts:16:43
    at DecoratePropertyWithoutDescriptor (/Users/jmurphy/projects/abc/api/node_modules/reflect-metadata/Reflect.ts:1061:13)
    at Object.decorate (/Users/jmurphy/projects/abc/api/node_modules/reflect-metadata/Reflect.ts:246:20)
    at __decorate (/Users/jmurphy/projects/abc/api/src/abc/dtos/source.dto.js:4:92)
```

Source File:

```
import {Table, Column, PrimaryColumn, PrimaryGeneratedColumn} from "typeorm";
import {autoserialize} from "cerialize";
import "reflect-metadata";

@Table()
export class DTOSourceFile {
  @PrimaryGeneratedColumn()
  id: number;
  
  @Column()
  locationURL: string;
  
  @Column()
  url: string;
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6"],
    "module": "commonjs",
    "noResolve": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": true,
    "noImplicitAny": true,
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "outDir": "build/",
    "moduleResolution": "node"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "build",
    "node_modules"
  ]
}

**Comment by rightisleft** [comment]
This is a mismatch between my webstorm compiler and tsconfig.json 

ensure compiled with:
--emitDecoratorMetadata true
