### ISSUE TITLE
QueryFailedError: Incorrect table definition; there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by xiaoqiao112** [typeorm/typeorm#8406]
import {
  Entity,
  Column,
  PrimaryGeneratedColumn
} from 'typeorm';

@Entity()
export class Role {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}

how to resolve?

**Comment by andyslack** [comment]
I have the same error, it would be helpful if the error message indicated which Entity or module was kicking out the issue to help debug.

`[Nest] 30009  - 12/21/2021, 9:43:56 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
QueryFailedError: Incorrect table definition; there can be only one auto column and it must be defined as a key
    at QueryFailedError.TypeORMError [as constructor] (/Users/andrewslack/Sites/BUQ-API/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/andrewslack/Sites/BUQ-API/src/error/QueryFailedError.ts:9:9)
    at Query.onResult (/Users/andrewslack/Sites/BUQ-API/src/driver/mysql/MysqlQueryRunner.ts:183:37)
    at Query.execute (/Users/andrewslack/Sites/BUQ-API/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/andrewslack/Sites/BUQ-API/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/andrewslack/Sites/BUQ-API/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/andrewslack/Sites/BUQ-API/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/andrewslack/Sites/BUQ-API/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
`

**Comment by andyslack** [comment]
I fixed my error, I had two entities both called the same name.

**Comment by Arijeet04** [comment]
for me it is showing this error can you please help me out with this?

QueryFailedError: schema "pokedex-backend" does not exist
    at new QueryFailedError (C:\Users\arije\Downloads\pokedex-server\src\error\QueryFailedError.ts:9:9)
    at Query.callback (C:\Users\arije\Downloads\pokedex-server\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (C:\Users\arije\Downloads\pokedex-server\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (C:\Users\arije\Downloads\pokedex-server\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (node:events:513:28)
    at Connection.emit (node:domain:489:12)
    at C:\Users\arije\Downloads\pokedex-server\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (C:\Users\arije\Downloads\pokedex-server\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (C:\Users\arije\Downloads\pokedex-server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:513:28) {
  length: 109,
  severity: 'ERROR',
  code: '3F000',
  detail: undefined,
  hint: undefined,
  position: '14',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '3098',
  routine: 'get_namespace_oid',
  query: 'CREATE TABLE "pokedex-backend"."pokemon_sprites" ("id" SERIAL NOT NULL, "front" character varying, "back" character varying, "frontShiny" character varying, "backShiny" character varying, CONSTRAINT "PK_f977d9b208bab72ec46cf1f9b26" PRIMARY KEY ("id"))',
  parameters: []
}
