### ISSUE TITLE
Complex query builder leftJoinAndMapOne() on MSSQL does not work

### ISSUE THREAD

**Issue by AlvinStefanus** [typeorm/typeorm#8434]
## Issue Description

The generated SQL is incorrect. There is no bracket on `leftJoinAndMapOne()`.

### Expected Behavior

There should be bracket wrapping the `Left Join`.

Expected generated query:

```
SELECT "chatRoom"."id" as id, 
"chatRoom"."name" as name, 
"chatRoom"."type" as type, 
"chatRoom"."description" as description, 
"chatRoom"."thumbnail" as thumbnail, 
"chatRoom"."status" as status, 
chats.[ unreadCount] as unreadCount FROM "chat_room" "chatRoom" 
LEFT JOIN "chat_room_participant" "participants" ON "participants"."chatRoomId"="chatRoom"."id"  
LEFT JOIN (SELECT "chatRoom"."id" AS "chatRoomId", COUNT("chat"."id") AS " unreadCount" FROM "chat" "chat" 
LEFT JOIN "chat_room" "chatRoom" ON "chatRoom"."id"="chat"."chatRoomId"  
LEFT JOIN "chat_read_by_chat_room_participant" "chat_readBy" ON "chat_readBy"."chatId"="chat"."id" 
LEFT JOIN "chat_room_participant" "readBy" ON "readBy"."id"="chat_readBy"."chatRoomParticipantId" 
WHERE NOT(readBy.UserId IN (@0)) OR "readBy"."id" IS NULL GROUP BY "chatRoom"."id") "chats" ON chats.chatRoomId = "chatRoom"."id" 
WHERE (@1 = @2 OR "chatRoom"."status" = @3) AND "chatRoom"."applicationId" = @4 AND "participants"."userId" = @5 ORDER BY "chatRoom"."lastUpdate" DESC
```

### Actual Behavior

Syntax error on generated SQL.

### Steps to Reproduce

These are the queries:

```typescript

    let joinQuery = db!.getRepository(Chat).createQueryBuilder("chat")
      .leftJoinAndSelect("chat.chatRoom", "chatRoom")
      .leftJoinAndSelect("chat.readBy", "readBy")
      .select("COUNT(chat.id)"," unreadCount")
      .addSelect("chatRoom.id", "chatRoomId")
      .where(
        "NOT(readBy.UserId IN (:userId)) OR readBy.id IS NULL",
        { userId: [userId]}
      )
      .groupBy("chatRoom.id");

    this.createQueryBuilder("chatRoom")
        .leftJoinAndSelect("chatRoom.participants", "participants")
        .leftJoinAndMapOne("chatRoom.unread", qb => joinQuery, "chats", "chats.chatRoomId = chatRoom.id")
        .where(
          "(:status = :all OR chatRoom.status = :status) AND chatRoom.applicationId = :applicationId AND participants.userId = :userId"
        )
        .select([
          "chatRoom.id as id",
          "chatRoom.name as name",
          "chatRoom.type as type",
          "chatRoom.description as description",
          "chatRoom.thumbnail as thumbnail",
          "chatRoom.status as status",
          "chats.unreadCount as unreadCount"
        ])
        .setParameters({
          userId: userId,
          applicationId: applicationId,
          status: status,
          all: "ALL",
        })
        .orderBy("chatRoom.lastUpdate", "DESC")
        .getRawMany()


```

Here is the generated query:

```
SELECT "chatRoom"."id" as id, 
"chatRoom"."name" as name, 
"chatRoom"."type" as type, 
"chatRoom"."description" as description, 
"chatRoom"."thumbnail" as thumbnail, 
"chatRoom"."status" as status, 
chats.unreadCount as unreadCount FROM "chat_room" "chatRoom" 
LEFT JOIN "chat_room_participant" "participants" ON "participants"."chatRoomId"="chatRoom"."id"  
LEFT JOIN SELECT "chatRoom"."id" AS "chatRoomId", COUNT("chat"."id") AS " unreadCount" FROM "chat" "chat" 
LEFT JOIN "chat_room" "chatRoom" ON "chatRoom"."id"="chat"."chatRoomId"  
LEFT JOIN "chat_read_by_chat_room_participant" "chat_readBy" ON "chat_readBy"."chatId"="chat"."id" 
LEFT JOIN "chat_room_participant" "readBy" ON "readBy"."id"="chat_readBy"."chatRoomParticipantId" 
WHERE NOT(readBy.UserId IN (@0)) OR "readBy"."id" IS NULL GROUP BY "chatRoom"."id" "chats" ON chats.chatRoomId = "chatRoom"."id" 
WHERE (@1 = @2 OR "chatRoom"."status" = @3) AND "chatRoom"."applicationId" = @4 AND "participants"."userId" = @5 ORDER BY "chatRoom"."lastUpdate" DESC
```

There should be bracket on:

```
LEFT JOIN (SELECT "chatRoom" ....
```
and close bracket
```
IS NULL GROUP BY "chatRoom"."id") "chats" ON chats.chatRoomId = ....
```

Also the

```
chats.unreadCount as unreadCount
```

should be:

```
chats.[ unreadCount] as unreadCount
```

Otherwise it produces error.

Here is the error:

```
QueryFailedError: Error: Incorrect syntax near 'chats'.
    at QueryFailedError.TypeORMError [as constructor] (D:\Projects\Node JS\DigiChat\src\error\TypeORMError.ts:7:9)
    at new QueryFailedError (D:\Projects\Node JS\DigiChat\src\error\QueryFailedError.ts:9:9)
    at D:\Projects\Node JS\DigiChat\src\driver\sqlserver\SqlServerQueryRunner.ts:218:30
    at D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\base\request.js:438:25
    at Request.userCallback (D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\tedious\request.js:493:15)
    at Request.callback (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\request.js:205:14)
    at Parser.onEndOfMessage (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:3078:22)
    at Object.onceWrapper (node:events:509:28)
    at Parser.emit (node:events:390:28)
    at Parser.emit (node:domain:475:12) {
  query: 'SELECT "chatRoom"."id" as id, "chatRoom"."name" as name, "chatRoom"."type" as type, "chatRoom"."description" as description, "chatRoom"."thumbnail" as thumbnail, "chatRoom"."status" as status, chats.unreadCount as unreadCount FROM "chat_room" "chatRoom" LEFT JOIN "chat_room_participant" "participants" ON "participants"."chatRoomId"="chatRoom"."id"  LEFT JOIN SELECT "chatRoom"."id" AS "chatRoomId", COUNT("chat"."id") AS " unreadCount" FROM "chat" "chat" LEFT JOIN "chat_room" "chatRoom" ON "chatRoom"."id"="chat"."chatRoomId"  LEFT JOIN "chat_read_by_chat_room_participant" "chat_readBy" ON "chat_readBy"."chatId"="chat"."id" LEFT JOIN "chat_room_participant" "readBy" ON "readBy"."id"="chat_readBy"."chatRoomParticipantId" WHERE NOT(readBy.UserId IN (@0)) OR "readBy"."id" IS NULL GROUP BY "chatRoom"."id" "chats" ON chats.chatRoomId = "chatRoom"."id" WHERE (@1 = @2 OR "chatRoom"."status" = @3) AND "chatRoom"."applicationId" = @4 AND "participants"."userId" = @5 ORDER BY "chatRoom"."lastUpdate" DESC',
  parameters: [
    'A97D66C4-014C-EC11-AE53-74D83E04F9D3',
    'ALL',
    'ALL',
    'ALL',
    '4AC752E9-004C-EC11-AE53-74D83E04F9D3',
    'A97D66C4-014C-EC11-AE53-74D83E04F9D3'
  ],
  driverError: RequestError: Incorrect syntax near 'chats'.
      at handleError (D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\tedious\request.js:388:15)
      at Connection.emit (node:events:390:28)
      at Connection.emit (node:domain:475:12)
      at Connection.emit (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1071:18)
      at Parser.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1176:12)
      at Parser.emit (node:events:390:28)
      at Parser.emit (node:domain:475:12)
      at Readable.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
      at Readable.emit (node:events:390:28)
      at Readable.emit (node:domain:475:12) {
    code: 'EREQUEST',
    originalError: Error: Incorrect syntax near 'chats'.
        at handleError (D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\tedious\request.js:386:19)
        at Connection.emit (node:events:390:28)
        at Connection.emit (node:domain:475:12)
        at Connection.emit (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1071:18)
        at Parser.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1176:12)
        at Parser.emit (node:events:390:28)
        at Parser.emit (node:domain:475:12)
        at Readable.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
        at Readable.emit (node:events:390:28)
        at Readable.emit (node:domain:475:12) {
      info: [ErrorMessageToken]
    },
    number: 102,
    lineNumber: 1,
    state: 1,
    class: 15,
    serverName: 'ALVIN-LENOVO',
    procName: '',
    precedingErrors: [ [RequestError] ]
  },
  code: 'EREQUEST',
  originalError: Error: Incorrect syntax near 'chats'.
      at handleError (D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\tedious\request.js:386:19)
      at Connection.emit (node:events:390:28)
      at Connection.emit (node:domain:475:12)
      at Connection.emit (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1071:18)
      at Parser.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1176:12)
      at Parser.emit (node:events:390:28)
      at Parser.emit (node:domain:475:12)
      at Readable.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
      at Readable.emit (node:events:390:28)
      at Readable.emit (node:domain:475:12) {
    info: ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 102,
      state: 1,
      class: 15,
      message: "Incorrect syntax near 'chats'.",
      serverName: 'ALVIN-LENOVO',
      procName: '',
      lineNumber: 1
    }
  },
  number: 102,
  lineNumber: 1,
  state: 1,
  class: 15,
  serverName: 'ALVIN-LENOVO',
  procName: '',
  precedingErrors: [
    RequestError: Incorrect syntax near the keyword 'SELECT'.
        at handleError (D:\Projects\Node JS\DigiChat\node_modules\mssql\lib\tedious\request.js:388:15)
        at Connection.emit (node:events:390:28)
        at Connection.emit (node:domain:475:12)
        at Connection.emit (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1071:18)
        at Parser.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\connection.js:1176:12)
        at Parser.emit (node:events:390:28)
        at Parser.emit (node:domain:475:12)
        at Readable.<anonymous> (D:\Projects\Node JS\DigiChat\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
        at Readable.emit (node:events:390:28)
        at Readable.emit (node:domain:475:12) {
      code: 'EREQUEST',
      originalError: [Error],
      number: 156,
      lineNumber: 1,
      state: 1,
      class: 15,
      serverName: 'ALVIN-LENOVO',
      procName: ''
    }
  ]
}
```

### My Environment

| Dependency          | Version  |
| MSSQL 2019 | Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) - 15.0.4178.1 (X64)   Sep 23 2021 16:47:49   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22000: ) (Hypervisor) |
| Operating System    | Windows 11 |
| Node.js version     | v16.13.0  | 
| Typescript version  | Version 4.2.4 | 
| TypeORM version     | 0.2.40 | 

### Additional Context

As I described above, aliases property should be wrapped in [ ] bracket. Like the above example (chats.[unreadCount] as unreadCount)

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlvinStefanus** [comment]
Here are the entities:

```

@Entity()
export class ChatRoom {

    @PrimaryGeneratedColumn("uuid")
    id: string;

    @Column({nullable: true})
    name?: string;

    @Column()
    type: string;

    @Column({type: "nvarchar", length: "MAX", nullable: true})
    thumbnail?: string | null;

    @Column({type: "nvarchar", length: "MAX", nullable: true})
    description: string | null;

    @Column()
    status: string;

    @OneToMany(type => ChatRoomParticipant, participant => participant.chatRoom)
    participants: ChatRoomParticipant[];

    @ManyToOne(type => Application, application => application.chatRooms)
    @JoinColumn({name: "applicationId"})
    application: Application;

    @Column()
    applicationId: string;

    @Column("bigint", {transformer: [numberTransformer], nullable: true})
    lastUpdate?: number;

    @OneToMany(type => Chat, chat => chat.chatRoom)
    chats: Chat[]

}

@Entity()
export class Chat {
  
      @PrimaryGeneratedColumn("uuid")
      id: string;
         
      @Column("bigint", {transformer: [numberTransformer]})
      sentAt: number;
      
      @Column()
      type: string;

      @Column()
      status: string;

      @Column({type: "nvarchar", length: "MAX"})
      message: string;

      @Column({type: "nvarchar", length: "MAX", nullable: true})
      filePath: string;
      
      @ManyToOne(type => ChatRoom, chatRoom => chatRoom.chats)
      @JoinColumn({name: "chatRoomId"})
      chatRoom: ChatRoom;

      @Column()
      chatRoomId: string;

      @ManyToOne(type => ChatRoomParticipant, sender => sender.chats)
      @JoinColumn({name: "userId"})
      sender: ChatRoomParticipant;

      @Column()
      senderId: string;

      @ManyToMany(type => ChatRoomParticipant)
      @JoinTable()
      readBy: ChatRoomParticipant[];
}

@Entity()
@Unique(["chatRoomId", "userId"])
export class ChatRoomParticipant {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("bigint", { transformer: [numberTransformer] })
  joinedAt: number;

  @Column()
  privilege: string;

  @ManyToOne((type) => ChatRoom, (chatRoom) => chatRoom.participants)
  @JoinColumn({ name: "chatRoomId" })
  chatRoom: ChatRoom;

  @Column()
  chatRoomId: string;

  @ManyToOne((type) => User, (user) => user.participants)
  @JoinColumn({ name: "userId" })
  user: User;

  @Column()
  userId: string;

  @OneToMany((type) => Chat, (chat) => chat.sender)
  chats: Chat[];
}


```

**Comment by kmordan24** [comment]
This worked for me on Postgres: https://github.com/typeorm/typeorm/issues/747#issuecomment-519553920

For some reason the combination of JOIN + ORDERBY + TAKE/SKIP 
1.) fails when you use the column name instead of entity property name. For example, firstName is property name, first_name is column name.
2.) fails when you use what you would think would be the alias that typeorm creates for you (for example: table_name_column_name).

Try changing orderBy to "table_name.attributeName" - hopefully it works for MSSQL!

**Comment by kzamulin** [comment]
faced with same issue
