### ISSUE TITLE
Error instead of TypeError: this.givenColumnNames is not a function

### ISSUE THREAD

**Issue by michaelzangl** [typeorm/typeorm#8440]
## Feature Description

More descriptive error message

### The Problem

```
TypeError: this.givenColumnNames is not a function
    at IndexMetadata.build (node_modules/typeorm/metadata/IndexMetadata.js:87:46)
    at node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:193:76
    at Array.forEach (<anonymous>)
```

### The Solution

Descriptive error message like "Hey, you forgot to specify fields in <index name> for <entity type>"

### Considered Alternatives

This is just a note to my future me googleing this error:
You forgot to add the columns in a @Index somewhere - check all of them. If you ever have a `@Index('name', {...options...})`, replace with `@Index('name', [fields], {...options...})`

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start, but I would just add a descriptive "if (!this.givenColumnNames) { throw new Error() }" at that place instead of writing a complex validator that will miss the next corner case.
 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Wintereise** [comment]
Thanks! This just saved me hours of pulling my hair out
