### ISSUE TITLE
BaseEntity.reload() throws on soft deleted objects

### ISSUE THREAD

**Issue by matheusbn** [typeorm/typeorm#8455]
## Issue Description

Calling `entity.reload()` throws if entity has been soft deleted.

### Expected Behavior

`entity.reload()` should reload even if soft deleted.

### Actual Behavior
```javascript
await invitation.softRemove();
await invitation.reload();
```
```
EntityNotFoundError: Could not find any entity of type "Invitation" matching: 1
    at EntityNotFoundError.TypeORMError [as constructor] (/.../backend/src/error/TypeORMError.ts:7:9)
    at new EntityNotFoundError (/.../backend/src/error/EntityNotFoundError.ts:10:9)
    at /.../backend/src/entity-manager/EntityManager.ts:889:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

  at Object.removeInvitation (src/services/invitationService.ts:87:15)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 10   |
| Node.js version     | v14.16.0 | 
| Typescript version  | 4.5.2 | 
| TypeORM version     | 0.2.41 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes           |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Why reload should load soft-deleted record? I don't see a clear motivation. Other can argue that reload shouldn't load soft-deleted record, since its... soft-deleted.

**Comment by osvaguillen** [comment]
@pleerock 
> Why reload should load soft-deleted record? I don't see a clear motivation. Other can argue that reload shouldn't load soft-deleted record, since its... soft-deleted.

What if, in a test, I am checking that after calling a function, my entity got soft deleted, I am trying to call `reload()` to get the latest state of the entity but it throws, as a workaround, I will have to get the id of this entity, refetch with `.withDeleted()` to just be able to check that soft delete column got set to something different than null.
