### ISSUE TITLE
Can't get relation from db - QueryFailedError: syntax error at or near "."

### ISSUE THREAD

**Issue by rluvaton** [typeorm/typeorm#8477]
## Issue Description
Let's say I have the following entities:
```ts

// user.entity.ts
import { Column, Entity, JoinTable, ManyToMany } from 'typeorm';
import { Place } from './place.entity';

@Entity()
export class User {
  @Column({ unique: true, primary: true })
  id: string;

  @ManyToMany(() => Place)
  @JoinTable()
  rootPlaces: Place[];
}


// place.entity.ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Place {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}

```

and I try to get the user id and his root places like this:
```ts
await connection.manager.findOne(User, 'user1', {
  select: ['id', 'rootPlaces'],
  relations: ['rootPlaces'],
}),
```

### Expected Behavior

I should get the user with that id and the root places property

### Actual Behavior

`QueryFailedError` happen

<details>
  <summary> <b>Thrown error</b></summary>

```
$ npm start

> new-typeorm-project@0.0.1 start
> ts-node src/index.ts

QueryFailedError: syntax error at or near "."
    at QueryFailedError.TypeORMError [as constructor] (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\src\error\TypeORMError.ts:7:9)
    at new QueryFailedError (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\src\error\QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\src\driver\postgres\PostgresQueryRunner.ts:247:19)
    at step (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:143:27)
    at Object.throw (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:124:57)
    at rejected (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'SELECT "User"."id" AS "User_id", "User__rootPlaces"."id" AS "User__rootPlaces_id", "User__rootPlaces"."name" AS "User__rootPlaces_name", User.userId FROM "user" "User" LEFT JOIN "user_root_places_place" "User_User__rootPlaces" ON "User_User__rootPlaces"."userId"="User"."id" LEFT JOIN "place" "User__rootPlaces" ON "User__rootPlaces"."id"="User_User__rootPlaces"."placeId" WHERE "User"."id" IN ($1)',
  parameters: [ 'user1' ],
  driverError: error: syntax error at or near "."
      at Parser.parseErrorMessage (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\pg-protocol\src\parser.ts:369:69)
      at Parser.handlePacket (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\pg-protocol\src\parser.ts:188:21)
      at Parser.parse (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
    length: 91,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '142',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'scan.l',
    line: '1176',
    routine: 'scanner_yyerror'
  },
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '142',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
```

</details>

As you can see from the query in the logged error there is `User.userId` in the `SELECT`, while there is no such property in `User` (although it exists in the Join Table created automatically)

After debugging the code I found out that here:
https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/find-options/FindOptionsUtils.ts#L113

the `qb.alias` is equal `User` and the `column.propertyPath` equal `userId`

### Steps to Reproduce

[Reproduction Repo](https://github.com/rluvaton/typeorm-repro-8477), It contains `docker-compose.yml` and the minimal code that is required to create this issue.

Just run `npm i && npm start` and it will start the DB and the "test" (after the script will finish I remove the docker container)

### My Environment

Plain TS

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11 |
| Node.js version     | `v16.13.1` | 
| Typescript version  | `v4.4.2`  | 
| TypeORM version     | `v0.2.41`  | 

This is also happening in TypeORM version `v0.2.35` (when the line below is introduced)
https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/find-options/FindOptionsUtils.ts#L113

and in `v0.2.34` (before that change) it failing with **different** error (column `User.userId` does not exist):
<details>
  <summary>Error in <code>v0.2.34</code></summary>

```
  QueryFailedError: column User.userId does not exist
    at new QueryFailedError (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\src\error\QueryFailedError.ts:11:9)
    at PostgresQueryRunner.<anonymous> (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\src\driver\postgres\PostgresQueryRunner.ts:228:19)
    at step (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:143:27)
    at Object.throw (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:124:57)
    at rejected (C:\Users\rluva\Programming\bugs-repro\typeorm\cant-find-with-relation\node_modules\typeorm\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  length: 110,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '138',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3589',
  routine: 'errorMissingColumn',
  query: 'SELECT "User"."id" AS "User_id", "User__rootPlaces"."id" AS "User__rootPlaces_id", "User__rootPlaces"."name" AS "User__rootPlaces_name", "User"."userId" FROM "user" "User" LEFT JOIN "user_root_places_place" "User_User__rootPlaces" ON "User_User__rootPlaces"."userId"="User"."id" LEFT JOIN "place" "User__rootPlaces" ON "User__rootPlaces"."id"="User_User__rootPlaces"."placeId" WHERE "User"."id" IN ($1)',
  parameters: [ 'user1' ]
}
```

</details>

### Relevant Database Driver(s)

I think this bug affects all DBs

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by rluvaton** [comment]
Is there anything I can do to help?

**Comment by mike-pinchuk** [comment]
I have the same issue

**Comment by Midstackdev** [comment]
I have the same issue too

**Comment by piyush97** [comment]
Any resolution for this?
