### ISSUE TITLE
TypeError: tableOrName.split is not a function

### ISSUE THREAD

**Issue by renehauck** [typeorm/typeorm#8481]
## Issue Description
I have tried to apply an initial migration to a database and get the error message `TypeError: tableOrName.split is not a function`

### Expected Behavior
A successful migration :-)

### Actual Behavior

When I try to create a migration to an empty database, I get the error:
```
TypeError: tableOrName.split is not a function
    at SnakeNamingRemoveEntityStrategy.DefaultNamingStrategy.getTableName (/home/rene/projects/gifbo/node_modules/.pnpm/typeorm@0.2.41/src/naming-strategy/DefaultNamingStrategy.ts:15:28)
    at SnakeNamingRemoveEntityStrategy.DefaultNamingStrategy.primaryKeyName (/home/rene/projects/gifbo/node_modules/.pnpm/typeorm@0.2.41/src/naming-strategy/DefaultNamingStrategy.ts:53:32)
    at PostgresQueryRunner.createTableSql (/home/rene/projects/gifbo/node_modules/.pnpm/typeorm@0.2.41_pg@8.7.1/src/driver/postgres/PostgresQueryRunner.ts:2138:67)
    at PostgresQueryRunner.<anonymous> (/home/rene/projects/gifbo/node_modules/.pnpm/typeorm@0.2.41_pg@8.7.1/src/driver/postgres/PostgresQueryRunner.ts:450:29)
    at step (/home/rene/projects/gifbo/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/rene/projects/gifbo/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:124:57)
    at /home/rene/projects/gifbo/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/rene/projects/gifbo/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:113:16)
    at PostgresQueryRunner.createTable (/home/rene/projects/gifbo/node_modules/.pnpm/typeorm@0.2.41_pg@8.7.1/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:514:38)
```

I tried debugging the whole thing and came up with the following:

```js
 DefaultNamingStrategy.prototype.getTableName = function (tableOrName) {
        // 
        if (tableOrName instanceof Table_1.Table) {
            tableOrName = tableOrName.name;
        }
        return tableOrName.split(".").pop();
    };
```

It seems that the check on instanceof is not working properly. Would a direct check on the property name be a better approach?
Something like: 
```js
 DefaultNamingStrategy.prototype.getTableName = function (tableOrName) {
        // 
        if (tableOrName.name) {
            tableOrName = tableOrName.name;
        }
        return tableOrName.split(".").pop();
    };
```

### Steps to Reproduce

1. create a nestjs project including typeorm.
1. create an entity
1. start a migration

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     ubuntu     |
| Node.js version     | v14.17.0  | 
| Typescript version  | v4.3.5  | 
| TypeORM version     | ^0.2.41  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AntonKornus** [comment]
https://github.com/typeorm/typeorm/issues/7170#issuecomment-932807445
Try this. I've faced with the same problem and it helped me.

**Comment by caed1s-d** [comment]
Try changing the import point:
from
`import { ... } from 'typeorm';`
to
`import { ... } from 'typeorm/browser';`

and use `npx typeorm migration:run` as suggested in the comment above 

> [#7170 (comment)](https://github.com/typeorm/typeorm/issues/7170#issuecomment-932807445) Try this. I've faced with the same problem and it helped me.
