### ISSUE TITLE
Reference top parent from far most child in relation tree

### ISSUE THREAD

**Issue by omattman** [typeorm/typeorm#8492]
Hi, does anyone know how to reference top parent id from a child relation tree?

I want to construct a `url` field on `CateringMenuItemImage` for my GraphQL resolver that would look similar to

`https://URL_TO_BUCKET/CateringMenu.id/menu/CateringMenuItem.id/CateringMenuItemImage.extension`

Such that when I query my image it already has the generated URL for usage.

The issue is that from `CateringMenuItemImage` I can't get access to the `id` of the top level parent `Catering` which I need to properly construct the field. I can access the `id` of `CateringMenu` fine, but I need a way to go one level higher.

Do you have any suggestions?

Relations starting from far most child: CateringMenuItemImage -> CateringMenuItem -> CateringMenu

These are my entities:
```js
export class Catering {
	@Field()
	@PrimaryGeneratedColumn("uuid")
	id: string;

	@Field()
	@Column()
	@Index({ unique: true })
	slug: string;

	@Field()
	@Column()
	title: string;

	@OneToMany(type => CateringMenu, cateringMenu => cateringMenu.catering)
	menus: CateringMenu[];
}

export class CateringMenu {
	@Field()
	@PrimaryGeneratedColumn("uuid")
	id: string;

	@Field()
	@Column()
	name: string;

	@Field(type => [CateringMenuItem])
	@OneToMany(
		type => CateringMenuItem,
		cateringMenuItem => cateringMenuItem.cateringMenu
	)
	items: CateringMenuItem[];

	@ManyToOne(type => Catering, catering => catering.menus)
	catering: Catering;
}

export class CateringMenuItemImage {
	@Field(type => ID)
	@PrimaryGeneratedColumn("uuid")
	id: string;

	@Field()
	@Column()
	mime: string;

    // THIS IS WHERE I NEED TO GET ACCESS TO THE DIFFERENT IDS
	@Field({ nullable: true })
	get url(): string {
		const baseUrl = "URL_TO_BUCKET";

		return `${baseUrl}/${this.cateringMenuItem.cateringMenu.id}/menu/${
			this.cateringMenuItemId
		}/${this.id}.${mime.extension(this.mime)}`;
	}

	@OneToOne(
		type => CateringMenuItem,
		cateringMenuItem => cateringMenuItem.image
	)
	@JoinColumn()
	cateringMenuItem: CateringMenuItem;

	@RelationId(
		(cateringMenuItemImage: CateringMenuItemImage) =>
			cateringMenuItemImage.cateringMenuItem
	)
	cateringMenuItemId: string;
}
```

This is the GraphQL query
```gql
{
  caterings {
    menus {
      order
      name
      items {
        name
        image {
          id
          url
        }
      }
    }
  }
}
``` 

But when adding `image` to the query I get the following error when trying to make my way to the top parent id of `Catering`

```json
{
  "errors": [
    {
      "message": "Cannot read property 'cateringMenu' of undefined",
      "locations": [
        {
          "line": 10,
          "column": 11
        }
      ],
      "path": [
        "caterings",
        0,
        "menus",
        0,
        "items",
        0,
        "image",
        "url"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'cateringMenu' of undefined",
            "    at CateringMenuItemImage.get url [as url] (C:\\nuento\\backend\\src\\services\\catering\\CateringMenuItemImage.ts:36:46)",
            "    at C:\\nuento\\backend\\node_modules\\type-graphql\\dist\\resolvers\\create.js:52:56",
            "    at Object.applyMiddlewares (C:\\nuento\\backend\\node_modules\\type-graphql\\dist\\resolvers\\helpers.js:58:16)",
            "    at C:\\nuento\\backend\\node_modules\\type-graphql\\dist\\resolvers\\create.js:51:26",
            "    at field.resolve (C:\\nuento\\backend\\node_modules\\apollo-server-core\\src\\utils\\schemaInstrumentation.ts:103:18)",
            "    at resolveField (C:\\nuento\\backend\\node_modules\\graphql\\execution\\execute.js:464:18)",
            "    at executeFields (C:\\nuento\\backend\\node_modules\\graphql\\execution\\execute.js:292:18)",
            "    at collectAndExecuteSubfields (C:\\nuento\\backend\\node_modules\\graphql\\execution\\execute.js:748:10)",
            "    at completeObjectValue (C:\\nuento\\backend\\node_modules\\graphql\\execution\\execute.js:738:10)",
            "    at completeValue (C:\\nuento\\backend\\node_modules\\graphql\\execution\\execute.js:590:12)"
          ]
        }
      }
    }
  ],
  "data": {
    "caterings": [
      {
        "menus": [
          {
            "name": "Menu 1",
            "items": [
              {
                "name": "Menu Item 1",
                "image": {
                  "id": "3f61ca09-fd50-4268-b77f-6c5c7ad7b9df",
                  "url": null
                }
              },
            ]
          },
        ]
      }
    ]
  }
}
```

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
