### ISSUE TITLE
turning `synchronize` option to `true` causes a connection error

### ISSUE THREAD

**Issue by Mnigos** [typeorm/typeorm#8560]
### Expected Behavior

Application should connect to database with `synchronize` option set to `true`

### Actual Behavior

Applications crashes cause connection error

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 10     |
| Node.js version     | 16.10.0  | 
| Typescript version  | 4.3.5  |
| TypeORM version     | 0.2.41  | 
| Nestjs version | 8.2.5 |
| Nestjs TypeORM version | 8.0.3 |

### Additional Context

Without `synchronize` option application is able to connect with database and it's causes no error.

But when i send request to any endpoint that using some entity i got that error

```
relation "user" does not exist
QueryFailedError: relation "user" does not exist
    at QueryFailedError.TypeORMError [as constructor] (C:\Users\makow\Documents\Projects\rigtch-music-api\src\error\TypeORMError.ts:7:9)
    at new QueryFailedError (C:\Users\makow\Documents\Projects\rigtch-music-api\src\error\QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (C:\Users\makow\Documents\Projects\rigtch-music-api\src\driver\postgres\PostgresQueryRunner.ts:247:19)
    at step (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:143:27)
    at Object.throw (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:124:57)
    at rejected (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

When i set `synchronize` option to `true`, I got a connection error

```
Unable to connect to the database. Retrying (1)...
TypeError: value.toUpperCase is not a function
    at PostgresDriver.normalizeDatetimeFunction (C:\Users\makow\Documents\Projects\rigtch-music-api\src\driver\postgres\PostgresDriver.ts:1216:38)
    at PostgresDriver.normalizeDefault (C:\Users\makow\Documents\Projects\rigtch-music-api\src\driver\postgres\PostgresDriver.ts:856:25)
    at Function.TableUtils.createTableColumnOptions (C:\Users\makow\Documents\Projects\rigtch-music-api\src\schema-builder\util\TableUtils.ts:20:29)
    at C:\Users\makow\Documents\Projects\rigtch-music-api\src\schema-builder\table\Table.ts:336:43
    at Array.map (<anonymous>)
    at Function.Table.create (C:\Users\makow\Documents\Projects\rigtch-music-api\src\schema-builder\table\Table.ts:336:18)
    at C:\Users\makow\Documents\Projects\rigtch-music-api\src\schema-builder\RdbmsSchemaBuilder.ts:406:33
    at step (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:124:57)
    at step (C:\Users\makow\Documents\Projects\rigtch-music-api\node_modules\tslib\tslib.js:128:143)
```

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  ✖️Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ahmad-RW** [comment]
please share ormconfig

**Comment by rhinodavid** [comment]
I think I've figured this out.

In one of my entities we have a column whose `default` is `() =>`:
<img width="743" alt="Screen Shot 2022-04-15 at 4 27 49 PM" src="https://user-images.githubusercontent.com/5778036/163649473-231d797f-1e83-456c-bb46-58834d95cc17.png">

`default` is typed as an optional `any`. However, in the [documentation](https://typeorm.io/entities#column-options), `default` is specified to be a `string`:

<img width="623" alt="Screen Shot 2022-04-15 at 4 31 12 PM" src="https://user-images.githubusercontent.com/5778036/163649638-fedc92e3-49f3-4a6a-90ae-346f38442ffe.png">

When `synchronize` gets called, it eventually invokes [`normalizeDefault`](https://github.com/typeorm/typeorm/blob/0.3.6/src/driver/postgres/PostgresDriver.ts#L981) in `PostgresDriver`. When the default is a function, it runs:

```
if (typeof defaultValue === "function") {
            const value = defaultValue()
            return this.normalizeDatetimeFunction(value)
        }
```

Note that now `defaultValue` is expected to have the following type (this should probably be on the column type definition):

<img width="809" alt="Screen Shot 2022-04-15 at 4 35 35 PM" src="https://user-images.githubusercontent.com/5778036/163649820-2f94f2c1-415a-4314-9573-2295e784708a.png">

So in my case, `value` ends up being `false`. This gets sent to `normalizeDatetimeFunction` which expects a string, `toUppercase` gets called on `false`, and we get `TypeError: value.toUpperCase is not a function`.

A fix is to change `default: () => false` to `"false"`. I'm going to create a PR to make sure `default` is typed appropriately, but hopefully this should fix it before a new version is rolled out.
