### ISSUE TITLE
tslib ->  tslib_1.__spreadArray) is not a function

### ISSUE THREAD

**Issue by pdashford** [typeorm/typeorm#8590]
## Issue Description

After upgrading to the latest version, it all works ok locally but when I deploy to AWS Lambda I receive the following error;

```

3eae064e-9734-4d0c-8351-dafbafc27971	TRACE	TypeError: (0 , tslib_1.__spreadArray) is not a function    at 

ConnectionMetadataBuilder.buildSubscribers (/opt/nodejs/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:38:89)    at Connection.buildMetadatas (/opt/nodejs/node_modules/typeorm/connection/Connection.js:510:53)    at Connection.<anonymous> (/opt/nodejs/node_modules/typeorm/connection/Connection.js:126:30)    at step (/opt/nodejs/node_modules/tslib/tslib.js:139:27)    at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:120:57)    at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:110:62)    at processTicksAndRejections (internal/process/task_queues.js:97:5) | 2022-01-31T13:42:39.784Z 3eae064e-9734-4d0c-8351-dafbafc27971 TRACE TypeError: (0 , tslib_1.__spreadArray) is not a function at ConnectionMetadataBuilder.buildSubscribers (/opt/nodejs/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:38:89) at Connection.buildMetadatas (/opt/nodejs/node_modules/typeorm/connection/Connection.js:510:53) at Connection.<anonymous> (/opt/nodejs/node_modules/typeorm/connection/Connection.js:126:30) at step (/opt/nodejs/node_modules/tslib/tslib.js:139:27) at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:120:57) at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:110:62) at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | --
```

I have checked and manually added tslib to the package file but still receive the same error.

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

**Comment by pdashford** [comment]
Was due to some other dep's using an older tslib and the load order of the lambda layers
