### ISSUE TITLE
typeorm leftJoinAndSelect fail with camel case foreign key generated

### ISSUE THREAD

**Issue by jamm3e3333** [typeorm/typeorm#8599]
## Issue Description

Hello, so I started to work with `tyepeorm` using `typescript` and all of the queries works fine for me, it's a great library, but I have an issue when I want to perform a `leftJoinAndSelect` method.

I think I have the right setup, right entities, but somehow it creates a different foreign key name and that's why the join cannot be performed because obviously the name of the foreign key is just different. 

I'm using postgresql so pg driver.

Here is how my tables look in a database:
```sql
CREATE TABLE drivers (
  id serial PRIMARY KEY,
  username varchar(255) NOT NULL,
  firstname varchar(255) DEFAULT NULL,
  surname varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  app_language varchar(255) DEFAULT NULL,
  last_active_at timestamp DEFAULT NULL,
  state varchar(255) DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp DEFAULT NULL,
  deleted_at timestamp DEFAULT NULL,
  restored_at timestamp DEFAULT NULL,
  is_external integer DEFAULT null,
  CONSTRAINT drivers_username_unique UNIQUE(username)
);
```

```sql
CREATE TABLE trip_drivers (
  id serial primary key,
  driver_id integer not NULL,
  last_active_at timestamp DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remaining_drive_time float DEFAULT NULL,
  dirty_sync integer DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp DEFAULT NULL,
  deleted_at timestamp DEFAULT NULL,
  restored_at timestamp DEFAULT NULL,
  CONSTRAINT trip_drivers_driver_id_foreign foreign key(driver_id) REFERENCES drivers(id) ON DELETE CASCADE ON UPDATE CASCADE
);
```
Here are my entities:

DriverEntity.ts:
```typescript
import { Entity, PrimaryGeneratedColumn, Column, OneToMany, JoinColumn } from 'typeorm'
import { TripDriversEntity } from './TripDrivers'
@Entity('drivers')
export class DriverEntity {
    @PrimaryGeneratedColumn() 
    id: number

    @Column()
    username: string

    @Column({nullable: true})
    firstname: string

    @Column({nullable: true})
    surname: string

    @Column({nullable: true})
    phone: string

    @Column({nullable: true})
    app_language: string

    @Column({nullable: true})
    last_active_at: string
    
    @Column({nullable: true})
    state: string

    @Column({nullable: true})
    created_at: Date

    @Column({nullable: true})
    updated_at: Date

    @Column({nullable: true})
    deleted_at: Date

    @Column({nullable: true})
    restored_at: Date

    @Column({nullable: true})
    is_external: number

    @OneToMany(() => TripDriversEntity, (trip: TripDriversEntity) => trip.driver)
    trips: TripDriversEntity[]
}
```
TripDrivers.ts
```typescript
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn } from 'typeorm'
import { DriverEntity } from './Driver'

@Entity('trip_drivers')
export class TripDriversEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column({ nullable: true,  })
  driver_id: number

  @Column({ nullable: true })
  last_active_at: Date

  @Column({ nullable: true })
  state: string

  @Column({ nullable: true })
  remaining_drive_time: number

  @Column({ nullable: true })
  dirty_sync: number

  @Column({ nullable: true })
  created_at: Date

  @Column({ nullable: true })
  updated_at: Date

  @Column({ nullable: true })
  deleted_at: Date

  @Column({ nullable: true })
  restored_at: Date

  @ManyToOne(() => DriverEntity, (driver: DriverEntity) => driver.trips)
  driver: DriverEntity
}
```
As you can see so far I defined the relations between those two tables, so this should be alright, I followed the steps here [typeorm docs](https://typeorm.io/#/many-to-one-one-to-many-relations)

This is my root `index.ts` file:
```typescript
import 'reflect-metadata'
```

This is how I define the connection to a postgresql database:
```typescript
export const connectTypeOrm = async () => {
  try {
    return await createConnection({
      host: config.database.dbHost,
      password: config.database.password,
      port: +config.database.port,
      database: config.database.dbName,
      username: config.database.user,
      type: 'postgres',
      entities: [
        DriverEntity,
        TripDriversEntity,
        'dist/src/app/entity/**/*.js',
      ],
    })
  } catch (error) {
    logger.error({ error })
    throw error
  }
}
```

I'm refering to the `.js` files for entities because i'm transpiling the typescript code into js into dist folder.

Here are my imports to the same file to where I'm defining the connection:
```typescript
import {
  createConnection,
  Connection,
  EntityTarget,
  getManager,
  getRepository,
  createQueryBuilder,
} from 'typeorm'
import config from '../../config'
import { DriverEntity } from '../entity/Driver'
import { TripDriversEntity } from '../entity/TripDrivers'
```
Here i'm calling the join:

```typescript
;(async () => {
  try {
    const connection = await connectTypeOrm()
    const joins = await  getRepository(TripDriversEntity)
      .createQueryBuilder('trip_drivers')
      .leftJoinAndSelect('trip_drivers.driver', 'driver')
      .getMany()

    console.log(joins)
    await connection.close()
  } catch (error) {
     console.error(error)
  }
})()
```

I've heard that it could be because of the configuration in tsconig.json but I tried to change it with no success.

Here is my tsconfig.json:
```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "target": "ES2019",
    "module": "CommonJS",
    "lib": ["ES2019", "DOM", "ES6"],
    "allowJs": true,
    "incremental": true,
    "checkJs": true,
    "sourceMap": true,
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "moduleResolution": "node",
    "useUnknownInCatchVariables": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false
  }
}
```
My package.json file:
```json
{
  "name": "postgresql-orms",
  "description": "Do the research about ORMs for postgreSQL database.",
  "version": "1.0.0",
  "author": "Jakub Vala <jakub.vala@ackee.cz>",
  "contributors": [],
  "engines": {
    "node": "^14.18.3"
  },
  "scripts": {
    "build": "rm -f -- tsconfig.tsbuildinfo && tsc",
    "start": "node -r source-map-support/register dist/index.js",
    "start-lr": "rm tsconfig.tsbuildinfo && tsc-watch --onSuccess \"npm run start\"",
    "lint": "npm run cs:eslint:check",
    "cs:prettier:check": "prettier --check '**/*.{ts,js,json,md}'",
    "cs:prettier:fix": "npm run cs:prettier:check -- --write '**/*.{ts,js,json,md}'",
    "cs:eslint:check": "eslint '**/*.ts' -f codeframe",
    "cs:eslint:fix": "npm run cs:eslint:check -- --fix",
    "typeorm:delete:tables": "./node_modules/.bin/ts-node ./node_modules/.bin/typeorm query \"DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT USAGE ON SCHEMA public to PUBLIC; GRANT CREATE ON SCHEMA public to PUBLIC; COMMENT ON SCHEMA public IS 'standard public schema';\" --config ormconfig.ts",
    "typeorm:create:migrations": "./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:create --config ormconfig.ts -n DriversMigration",
    "typeorm:generate:migrations": "./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:generate --config ormconfig.ts -n DriversMigration",
    "typeorm:run:migrations": "./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run --config ormconfig.ts",
    "typeorm:revert:migrations": "./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:revert --config ormconfig.ts"
  },
  "dependencies": {
    "configuru": "^0.6.1",
    "cosmas": "^3.0.10",
    "date-fns": "^2.28.0",
    "lodash": "^4.17.21",
    "pg": "^8.7.1",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.21",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^3.12.0",
    "typeorm": "^0.2.41"
  },
  "devDependencies": {
    "@ackee/styleguide-backend-config": "^0.2.2",
    "@types/date-fns": "^2.6.0",
    "@types/lodash": "^4.14.178",
    "@types/node": "^17.0.12",
    "lint-staged": "^12.3.1",
    "prettier": "^2.5.1",
    "tsc-watch": "^4.6.0",
    "typescript": "^4.4.4"
  }
}
```
docker-compose.yml
```yml
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: ${CONTAINER_NAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

Here is the error that I'm getting:

```json
error: {
    code: '42703',
    message: 'column trip_drivers.driverId does not exist',
    stack: 'QueryFailedError: column trip_drivers.driverId does not exist\n' +
      '    at QueryFailedError.TypeORMError [as constructor] (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/typeorm/error/TypeORMError.js:9:28)\n' +
      '    at new QueryFailedError (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/typeorm/error/QueryFailedError.js:13:28)\n' +
      '    at PostgresQueryRunner.<anonymous> (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)\n' +
      '    at step (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/tslib/tslib.js:143:27)\n' +
      '    at Object.throw (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/tslib/tslib.js:124:57)\n' +
      '    at rejected (/Users/ackee/Desktop/repoos/AckeeHub/internal/orms/postgresql-orms/node_modules/tslib/tslib.js:115:69)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)'
  }
```

I'm willing to share the repo so you can help, of course only if you're willing to help me.
### Expected Behavior

I expect the method to perform a left join so to every `trip_drivers` it assigns `driver` and the query to be like this when it generates:

```sql
SELECT "trip_drivers"."id" AS "trip_drivers_id",
"trip_drivers"."driver_id" AS "trip_drivers_driver_id",
"trip_drivers"."last_active_at" AS "trip_drivers_last_active_at",
"trip_drivers"."state" AS "trip_drivers_state",
"trip_drivers"."remaining_drive_time" AS "trip_drivers_remaining_drive_time",
"trip_drivers"."dirty_sync" AS "trip_drivers_dirty_sync",
"trip_drivers"."created_at" AS "trip_drivers_created_at",
"trip_drivers"."updated_at" AS "trip_drivers_updated_at",
"trip_drivers"."deleted_at" AS "trip_drivers_deleted_at",
"trip_drivers"."restored_at" AS "trip_drivers_restored_at",
"trip_drivers"."driver_id" AS "trip_drivers_driverId",
"driver"."id" AS "driver_id",
"driver"."username" AS "driver_username",
"driver"."firstname" AS "driver_firstname",
"driver"."surname" AS "driver_surname",
"driver"."phone" AS "driver_phone",
"driver"."app_language" AS "driver_app_language",
"driver"."last_active_at" AS "driver_last_active_at",
"driver"."state" AS "driver_state",
"driver"."created_at" AS "driver_created_at",
"driver"."updated_at" AS "driver_updated_at",
"driver"."deleted_at" AS "driver_deleted_at",
"driver"."restored_at" AS "driver_restored_at",
"driver"."is_external" AS "driver_is_external" FROM "trip_drivers" "trip_drivers" LEFT JOIN "drivers" "driver" ON "driver"."id"="trip_drivers"."driver_id"
```

### Actual Behavior

Instead I got that error and the query that is generated:

```sql
SELECT "trip_drivers"."id" AS "trip_drivers_id",
"trip_drivers"."driver_id" AS "trip_drivers_driver_id",
"trip_drivers"."last_active_at" AS "trip_drivers_last_active_at",
"trip_drivers"."state" AS "trip_drivers_state",
"trip_drivers"."remaining_drive_time" AS "trip_drivers_remaining_drive_time",
"trip_drivers"."dirty_sync" AS "trip_drivers_dirty_sync",
"trip_drivers"."created_at" AS "trip_drivers_created_at",
"trip_drivers"."updated_at" AS "trip_drivers_updated_at",
"trip_drivers"."deleted_at" AS "trip_drivers_deleted_at",
"trip_drivers"."restored_at" AS "trip_drivers_restored_at",
"trip_drivers"."driverId" AS "trip_drivers_driverId",
"driver"."id" AS "driver_id",
"driver"."username" AS "driver_username",
"driver"."firstname" AS "driver_firstname",
"driver"."surname" AS "driver_surname",
"driver"."phone" AS "driver_phone",
"driver"."app_language" AS "driver_app_language",
"driver"."last_active_at" AS "driver_last_active_at",
"driver"."state" AS "driver_state",
"driver"."created_at" AS "driver_created_at",
"driver"."updated_at" AS "driver_updated_at",
"driver"."deleted_at" AS "driver_deleted_at",
"driver"."restored_at" AS "driver_restored_at",
"driver"."is_external" AS "driver_is_external" FROM "trip_drivers" "trip_drivers" LEFT JOIN "drivers" "driver" ON "driver"."id"="trip_drivers"."driverId"
```

### Steps to Reproduce

1. Create the same structure of the tables in postgres.
2. Run the database
2. Create the same entity classes.
3. Create a same tsconfig.json
4. Create the same package.json
5. run `npm i`
6. create `env` variables
7. transpile running `npm run build`
8. run `npm run start`

### My Environment
```env
export DB_PORT=5432
export MIGRATE_DB=false
export POSTGRES_PASSWORD=postgres
export POSTGRES_USER=postgres
export POSTGRES_DB=orm_test
export CONTAINER_NAME=postgres_orm
export DB_HOST=localhost
```

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS    |
| Node.js version     | v14.18.3  | 
| Typescript version  | 4.4.4 | 
| TypeORM version     | ^0.2.41 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by jamm3e3333** [comment]
I got an answer here on [stackoverflow](https://stackoverflow.com/questions/71015061/typeorm-leftjoinandselect-fail-with-camel-case-foreign-key-generated/71020410#71020410).

Basically I needed to specify `@JoinColumn` decorator for `TripDriversEntity`.
