### ISSUE TITLE
DataTypeNotSupportedError: Data type "Array" in "ReqResLogXImportPackageEntity.rrl_id" is not supported by "oracle" database.

### ISSUE THREAD

**Issue by davidyem** [typeorm/typeorm#8632]
### Expected Behavior

 OnyToMany relation between two entites

### Actual Behavior

DataTypeNotSupportedError: Data type "Array" in "ReqResLogXImportPackageEntity.rrl_id" is not supported by "oracle" database.

```
[Nest] 17424  - 13.02.2022, 18:09:54   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
DataTypeNotSupportedError: Data type "Array" in "ReqResLogXImportPackageEntity.rrl_id" is not supported by "oracle" database.
    at DataTypeNotSupportedError.TypeORMError [as constructor] (H:\OpenServer\domains\etele-integration-log-importer\src\error\TypeORMError.ts:7:9)
    at new DataTypeNotSupportedError (H:\OpenServer\domains\etele-integration-log-importer\src\error\DataTypeNotSupportedError.ts:8:9)
    at H:\OpenServer\domains\etele-integration-log-importer\src\metadata-builder\EntityMetadataValidator.ts:88:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (H:\OpenServer\domains\etele-integration-log-importer\src\metadata-builder\EntityMetadataValidator.ts:85:36)
    at H:\OpenServer\domains\etele-integration-log-importer\src\metadata-builder\EntityMetadataValidator.ts:46:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (H:\OpenServer\domains\etele-integration-log-importer\src\metadata-builder\EntityMetadataValidator.ts:46:25)
    at Connection.buildMetadatas (H:\OpenServer\domains\etele-integration-log-importer\src\connection\Connection.ts:518:33)
    at Connection.<anonymous> (H:\OpenServer\domains\etele-integration-log-importer\src\connection\Connection.ts:186:18)

```

### Steps to Reproduce

```typescript
@Entity({ name: 'REQ_RES_LOG_X_IMPORT_PACKAGE', schema: process.env.DB_SCHEMA })
export class ReqResLogXImportPackageEntity {
  @OneToMany(() => ReqResLogEntity, (req_res_log) => req_res_log.id)
  @PrimaryColumn()
  rrl_id: ReqResLogEntity[];

  @OneToOne(() => ImportPackageEntity)
  @JoinColumn({ name: 'ip_id' })
  @PrimaryColumn()
  ip_id: ImportPackageEntity;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | x.y.zzz  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | yes            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
I'm not sure if it's even possible in any database. How can `@OneToMany` be a primary key? How should generated table DDL look like?

**Comment by davidyem** [comment]
@Ginden it is a pivot table. I have used such a construction to create unique index from 2 columns. But the main problem, as I understand, is that I can’t use entity ad a data type, when I am using oracle

**Comment by davidyem** [comment]
@Ginden DDL 

```
CREATE TABLE "c##developer"."req_res_log_x_import_package" 
(
  "rrl_id" NUMBER(19, 0) NOT NULL 
, "ip_id" NUMBER(9, 0) NOT NULL 
, CONSTRAINT "pk_req_res_log_1" PRIMARY KEY 
  (
    "ip_id" 
  , "rrl_id" 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX "c##developer"."pk_req_res_log_1" ON "c##developer"."req_res_log_x_import_package" ("ip_id" ASC, "rrl_id" ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE "c##developer"."req_res_log_x_import_package"
ADD CONSTRAINT "fk_req_res_log_x_import_package_import_package" FOREIGN KEY
(
  "ip_id" 
)
REFERENCES "c##developer"."import_package"
(
  "id" 
)
ENABLE;

ALTER TABLE "c##developer"."req_res_log_x_import_package"
ADD CONSTRAINT "fk_req_res_log_x_import_package_req_res_log" FOREIGN KEY
(
  "rrl_id" 
)
REFERENCES "c##developer"."req_res_log"
(
  "id" 
)
ENABLE;
```
