### ISSUE TITLE
Allow explicit collation in ORDER BY clause

### ISSUE THREAD

**Issue by jktf** [typeorm/typeorm#8648]
### The Problem

In an internationalized application, I want to sort text columns using the collation corresponding to the user's prefered locale. For example, users speaking Czech should see results sorted using Czech rules, whereas users speaking English should see results sorted using English rules.

This is supported by PostgreSQL:

```sql
SELECT * FROM test1 ORDER BY name COLLATE "cs-CZ-x-icu";
```

However, TypeORM's `SelectQueryBuilder` only supports `ORDER BY` conditions containing a column name, optionally followed by `ASC` or `DESC`, optionally followed by `NULLS FIRST` or `NULLS LAST`.

### The Solution

Add a "collation" option to every column used in an `ORDER BY` condition for PostgreSQL and possibly other RDBMS's that support it.

Alternatively, allow arbitrary expressions, not just single column names, to be used in `ORDER BY` conditions.

### Considered Alternatives

I tried using the expression `'changedBy.firstName COLLATE "cs-CZ-x-icu"'` as the column name, but TypeORM internally assumes that this is just a single column name made of identifiers separated by dots, and behaves unpredictably when this assumption is broken, for example by throwing this:

```
TypeError: Cannot read properties of undefined (reading 'databaseName')
    at node_modules/typeorm/query-builder/SelectQueryBuilder.js:1598:151
```

(It tries to find a column named `'firstName COLLATE "cs-CZ-x-icu"'`, which obviously does not exist.)

Using the parenthesized expression `'(changedBy.firstName COLLATE "cs-CZ-x-icu")'` as the column name makes the error somewhat more readable:

```
TypeORMError: "(changedBy" alias was not found. Maybe you forgot to join it?
    at new TypeORMError (node_modules/typeorm/error/TypeORMError.js:9:28)
```

### Additional Context

I found other issues dealing with TypeORM's assumptions about the `ORDER BY` conditions:
- https://github.com/typeorm/typeorm/issues/7280
- https://github.com/typeorm/typeorm/pull/7282
- https://github.com/typeorm/typeorm/issues/6640
- https://github.com/typeorm/typeorm/issues/3356
- https://github.com/typeorm/typeorm/issues/2817
- https://github.com/typeorm/typeorm/issues/2591

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Does `COLLATE` relate to `ORDER BY` expression? Because I don't see in the ORDER BY section of the [postgres docs](https://www.postgresql.org/docs/14/queries-order.html)

**Comment by jktf** [comment]
> Does `COLLATE` relate to `ORDER BY` expression? Because I don't see in the ORDER BY section of the [postgres docs](https://www.postgresql.org/docs/14/queries-order.html)

It's not related explicitly. `COLLATE` can be used to explicitly change the collation of any expression, even though it only makes sense in contexts that involve comparison, like the `ORDER BY` clause does.

The [documentation on collations](https://www.postgresql.org/docs/14/collation.html) says "every expression of a collatable data type has a collation" and uses `ORDER BY` with `COLLATE` in some examples.

So there are essentially two ways to implement this feature:

1. By making `SelectQueryBuilder` handle ordering by any kind of expression. This would allow expressions using `COLLATE` as well as many other useful expressions, solving a lot of issues at once, but it would probably take more effort.
2. By adding a "collation" option to columns used for ordering. This would only cover my specific case but should be easy to implement.

**Comment by ovitaliw** [comment]
I think adding Raw() support to the ORDER BY clause can solve this and https://github.com/typeorm/typeorm/issues/8786.

I'm using Postgres and I need case insensitive Order By, with Raw() support it will be easy to solve this kind of issue

**Comment by wodka** [comment]
For me I am using a "workaround":

```
qb.addSelect('alias.column COLLATE "en-u-kn-true"', 'column_for_sort')
qb.orderBy('column_for_sort', 'ASC')
```

this way there is an additional selected column, but with it I can set custom collations for order by
