### ISSUE TITLE
Error: Cannot find module ormconfig.js

### ISSUE THREAD

**Issue by kyledecot** [typeorm/typeorm#8650]
## Issue Description

After bundling my application w/ webpack (5.25.0) and attempting to run the bundle w/ `node ./app.js` an error is raised declaring that `ormconfig.js` cannot be found despite existing.

### Expected Behavior

Application should start without issue.

### Actual Behavior

```
/Users/tabulous-xyz/Code/content/api.js:260548
	var e = new Error("Cannot find module '" + req + "'");
	        ^

Error: Cannot find module '/Users/tabulous-xyz/Code/content/ormconfig.js'
    at webpackEmptyContext (/Users/tabulous-xyz/Code/content/api.js:260548:10)
    at /Users/tabulous-xyz/Code/content/api.js:340347:117
    at step (/Users/tabulous-xyz/Code/content/api.js:252608:23)
    at Object.next (/Users/tabulous-xyz/Code/content/api.js:252589:53)
    at /Users/tabulous-xyz/Code/content/api.js:252582:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tabulous-xyz/Code/content/api.js:252578:12)
    at tryToRequire (/Users/tabulous-xyz/Code/content/api.js:340345:79)
    at /Users/tabulous-xyz/Code/content/api.js:340366:51
    at step (/Users/tabulous-xyz/Code/content/api.js:252608:23) {
  code: 'MODULE_NOT_FOUND'
}
```

### Steps to Reproduce

1. node ./app.js

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS  12.2      |
| Node.js version     |  v16.11.1  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.42  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by kyledecot** [comment]
The error seems to be coming from https://github.com/typeorm/typeorm/blob/3a694dd3e99699e7284709c53967a5dfcb1e1806/src/util/ImportUtils.ts which was recently changed however I'm too unfamiliar w/ the codebase to know if something is amiss.
