### ISSUE TITLE
Reposiotry.softRemove() throws `QueryFailedError: column "<join_column>" does not exist` error

### ISSUE THREAD

**Issue by fabian-grajko** [typeorm/typeorm#8653]
## Issue Description

After bumping TypeORM version from `0.2.41` to `0.2.42` the `softRemove()` method started to throw exceptions.

### Expected Behavior

Records are soft-removed. No error is thrown.

### Actual Behavior

Records are not soft-removed. The QueryFailedError is thrown.

```
QueryFailedError: column "employee" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/src/driver/postgres/PostgresQueryRunner.ts:247:19)
    at step (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/fabiangrajko/Workspace/cyclops/looking-glass/api/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'UPDATE "users" SET "deleted_at" = CURRENT_TIMESTAMP WHERE employee in ($1) RETURNING "id"',
  parameters: [ { id: 10 } ],
```

### Steps to Reproduce

1. Create 2 entities with relation (tested with `OneToOne` and `ManyToOne`) and set `{ cascade: true }`

```typescript
@Entity({ name: "employees" })
export class EmployeeEntity {
  @Column({ primary: true, generated: false })
  id: Id;

  @OneToOne(() => UserEntity, (user) => user.employee, { cascade: true })
  @JoinColumn({ name: "id" })
  user: UserEntity;

  @DeleteDateColumn({ name: "deleted_at" })
  deletedAt: Date | null;
}

@Entity({ name: "users" })
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: Id;

  @OneToOne(() => EmployeeEntity, (employee) => employee.user)
  employee: EmployeeEntity;

  @DeleteDateColumn({ name: "deleted_at" })
  deletedAt: Date | null;
}
```

2. Fetch one or more records with `relations`

```typescript
const employeeId = 10;
const repository = getRepository(EmployeeEntity);
const employeeToRemove = await repository.findOneOrFail(employeeId, { relations: ["user"] });
```

3. Use `softRemove()` on newly fetched record

```typescript
await repository.softRemove(employeeToRemove);
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS 12.1 |
| Node.js version     | 16.13.1  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.42  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by fabian-grajko** [comment]
Reverting #8436 solved the issue. Thanks
