### ISSUE TITLE
Cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by sogehige** [typeorm/typeorm#8668]
## Issue Description

When logging queries, there are two `BEGIN TRANSACTIONS` executing at once and save fails.

### Expected Behavior

No transaction errors. Driver should properly wait for commit from previous in progress transaction as you cannot make each call sync with Promise use.

### Actual Behavior
```
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('user')
query: PRAGMA table_info("user")
query: PRAGMA index_list("user")
query: PRAGMA foreign_key_list("user")
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
query: COMMIT
query: BEGIN TRANSACTION
query: BEGIN TRANSACTION
query failed: BEGIN TRANSACTION
error: SqliteError: cannot start a transaction within a transaction
    at BetterSqlite3QueryRunner.<anonymous> (E:\_GIT\typeorm_8668\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:95:38)
    at step (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:143:27)
    at Object.next (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:124:57)
    at fulfilled (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:114:62) {
  code: 'SQLITE_ERROR'
}
query: INSERT INTO "user"("id", "name") VALUES (NULL, ?) -- PARAMETERS: [0]
query: ROLLBACK
E:\_GIT\typeorm_8668\src\error\TypeORMError.ts:7
        super(message);
        ^
QueryFailedError: SqliteError: cannot start a transaction within a transaction
    at QueryFailedError.TypeORMError [as constructor] (E:\_GIT\typeorm_8668\src\error\TypeORMError.ts:7:9)
    at new QueryFailedError (E:\_GIT\typeorm_8668\src\error\QueryFailedError.ts:9:9)
    at BetterSqlite3QueryRunner.<anonymous> (E:\_GIT\typeorm_8668\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:114:19)
    at step (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:143:27)
    at Object.next (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:124:57)
    at fulfilled (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:114:62) {
  query: 'BEGIN TRANSACTION',
  parameters: [],
  driverError: SqliteError: cannot start a transaction within a transaction
      at BetterSqlite3QueryRunner.<anonymous> (E:\_GIT\typeorm_8668\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:95:38)
      at step (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:143:27)
      at Object.next (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:124:57)
      at fulfilled (E:\_GIT\typeorm_8668\node_modules\tslib\tslib.js:114:62) {
    code: 'SQLITE_ERROR'
  },
  code: 'SQLITE_ERROR'
}
```

### Steps to Reproduce

1. Save into database without await
2. After this call do another save

Repository: https://github.com/sogehige/typeorm_8668

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows 11, Ubuntu, Debian      |
| Node.js version     | v16.13.1  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.43  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | yes            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Every `.save` method call creates a `TRANSACTION`

If we call `save` method two times without `await`:

```ts
repository.save(post1);
repository.save(post2);
```

It will create two `TRANSACTION`s. However sqlite doesn't support [multiple transactions](https://www.sqlite.org/faq.html#q5).

So, I guess you need to design your code the way your transactions executed in sequence.

**Comment by sogehige** [comment]
> So, I guess you need to design your code the way your transactions executed in sequence.

Ok, I get it, but how can I handle these errors? How can I repeat transaction if it failed in general? It doesn't seems OK to me that driver don't handle this for me, because if I have more complicated app with promises, then those `.save` may clash. Or I just need to try/catch -> retry every `.save` calls?

**Comment by sogehige** [comment]
Monkeypatch from https://github.com/typeorm/typeorm/issues/1884 solved my issue

**Comment by bozkayaSalihX** [comment]
that for advice its worked with me

**Comment by jimOnAir** [comment]
Hello. Is there a solulion for current version of Typeorm? Nested transcations are not working as needed.

**Comment by pluveto** [comment]
Any solution?
