### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MartinToews** [typeorm/typeorm#8699]
## Issue Description

Getting RangeError: Maximum call stack size exceeded by saving data into db

### Expected Behavior

I want to use typeorm to insert data with a many-many Relation into my mssql db.

this is the actual Entity I want to insert:
![image](https://user-images.githubusercontent.com/84084389/155519849-77954461-e79f-4b2d-bf8d-40cc80ab4561.png)

I have big data with over 10000 documents per importRun.

### Actual Behavior

on this way i try to save my data.
![image](https://user-images.githubusercontent.com/84084389/155521944-74f66652-7133-4983-8124-5f167a0d3313.png)

when I run my application with limited documents like 10 or 100 my application runs without problems.
But when ich run my application with whole documents (10000+) this error appears:
![image](https://user-images.githubusercontent.com/84084389/155521827-c62b71e5-cb9e-4fd7-929b-07f2e35192e2.png)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.16.0  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.2.43  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mssql`              | yes             |
| `mysql`              | no             |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by od-cyera** [comment]
Any updates?

**Comment by tim1uphealth** [comment]
hoping this gets addressed soon

**Comment by dagenius007** [comment]
No update yet.

**Comment by salihteampify** [comment]
I have the same error on repository "create" method using. 
`RangeError: Maximum call stack size exceeded
    at EntityMetadata.create (/app/node_modules/typeorm/metadata/EntityMetadata.js:268:11)
    at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:76:60
    at Array.forEach (<anonymous>)
    at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32)
    at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:81:26
    at Array.forEach (<anonymous>)
    at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32)
    at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:81:26
    at Array.forEach (<anonymous>)
    at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32)`

**Comment by robinelvin** [comment]
> I have the same error on repository "create" method using. `RangeError: Maximum call stack size exceeded at EntityMetadata.create (/app/node_modules/typeorm/metadata/EntityMetadata.js:268:11) at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:76:60 at Array.forEach (<anonymous>) at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32) at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:81:26 at Array.forEach (<anonymous>) at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32) at /app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:81:26 at Array.forEach (<anonymous>) at PlainObjectToNewEntityTransformer.groupAndTransform (/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:38:32)`

Same issue just cropped up here. It would be useful to understand exactly what is causing the recursion. I am attempting to debug this now.
