### ISSUE TITLE
MissingDeleteDateColumnError is thrown even when DeleteDateColumn() is set for an entity.

### ISSUE THREAD

**Issue by pritammobisoft** [typeorm/typeorm#8718]
## Issue Description

MissingDeleteDateColumnError is thrown even when DeleteDateColumn() is set for an entity.

Given the following entity: 

```typescript
@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @DeleteDateColumn()
    @Column({ name: 'deleted_at', nullable: true })
    public deletedAt?: Date

    @CreateDateColumn({ type: 'timestamp' })
    @Column({ name: 'created_at' })
    public createdAt!: Date

    @UpdateDateColumn({ type: 'timestamp' })
    @Column({ name: 'updated_at' })
    public updatedAt!: Date
}
```

Calling the following code throws exception: `MissingDeleteDateColumnError: Entity "Photo" does not have delete date columns.`

```
connection.transaction(async (manager) => {
        await manager
            .createQueryBuilder()
            .softDelete()
            .from(Photo, 'p')
            .where("p.name = :name", { name: 'test1' })
            .execute();
    })
```

### Expected Behavior

The soft delete should work properly.

### Actual Behavior

It throws exception 

```
MissingDeleteDateColumnError: Entity "Photo" does not have delete date columns.
    at MissingDeleteDateColumnError.TypeORMError [as constructor] (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/error/TypeORMError.ts:7:9)
    at new MissingDeleteDateColumnError (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/error/MissingDeleteDateColumnError.ts:6:9)
    at SoftDeleteQueryBuilder.createUpdateExpression (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/query-builder/SoftDeleteQueryBuilder.ts:360:19)
    at SoftDeleteQueryBuilder.getQuery (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/query-builder/SoftDeleteQueryBuilder.ts:42:24)
    at SoftDeleteQueryBuilder.QueryBuilder.getQueryAndParameters (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/query-builder/QueryBuilder.ts:448:28)
    at SoftDeleteQueryBuilder.<anonymous> (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/src/query-builder/SoftDeleteQueryBuilder.ts:80:44)
    at step (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/pritambarhate/data/code/nodejs/typeorm/softdelete/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to Reproduce

1. Clone this repo: https://github.com/pritammobisoft/TypeORM-DeleteDateColumn-Issue
2. Update the `ormconfig.json` file
3. Run `npm install`
4. Run `npm run start`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     macOS 12.2.1    |
| Node.js version     | 16.14.0  | 
| Typescript version  | 4.6.2  | 
| TypeORM version     | 0.2.44  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 -  ✅"No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
you can just remove the @Column and set "name" in @DeleteDateColumn, like:
`@DeleteDateColumn({ name: 'deleted_at' })`

it's happen because the @Column definition is overriding @DeleteDateColumn. You cannot have two column definitions in the same property.

**Comment by pritammobisoft** [comment]
@iJhefe Your solution works! Thanks.

**Comment by trangchongcheng** [comment]
I have same isue,
`import {
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
} from 'typeorm';

export abstract class IdentityEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;
}

export abstract class BaseEntity extends IdentityEntity {
  @CreateDateColumn({ select: false })
  createdAt!: Date;

  @UpdateDateColumn({ select: false })
  updatedAt!: Date;

  @DeleteDateColumn()
  @Column({ nullable: true, name: 'deleted_at' })
  deletedAt?: Date;

  // @Column({ type: 'boolean', default: false, select: false })
  // isDeleted!: boolean;
}
`

` async remove(id: string) {
    try {
      const deleteResponse = await this.userRepository.softDelete(id);
      if (!deleteResponse.affected) {
        throw new NotFoundException(
          `${this.userRepository.metadata.targetName} with id ${id} not found`,
        );
      }
    } catch (error: any) {
      throw new NotFoundException(error.message);
    }
    return true;
  }`


And

`{"customInformation":{"message":"Entity \"User\" does not have delete date columns.","statusCode":404},"level":"error","message":"Entity \"User\" does not have delete date columns.","name":"NotFoundException","response":"Entity \"User\" does not have delete date columns.","stack":"NotFoundException: Entity \"User\" does not have delete date columns.\n    at UserService.remove (/Users/cheng/Workspace/company/codelight/blox3/user-service/src/modules/user/user.service.ts:95:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /Users/cheng/Workspace/company/codelight/blox3/user-service/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at /Users/cheng/Workspace/company/codelight/blox3/user-service/node_modules/@nestjs/core/router/router-proxy.js:9:17","status":404}`
