### ISSUE TITLE
Cannot set property metadata of #<Repository> which has only a getter

### ISSUE THREAD

**Issue by sm1le404** [typeorm/typeorm#8789]
### Expected Behavior

App has started without errors

### Actual Behavior

When i start app, get next exception:

[Nest] 79074  - 03/23/2022, 10:53:54 PM   ERROR [ExceptionHandler] Cannot set property metadata of #<Repository> which has only a getter
TypeError: Cannot set property metadata of #\<Repository\> which has only a getter
    at EntityManager.getCustomRepository (/task-manager/src/entity-manager/EntityManager.ts:1398:59)
    at DataSource.getCustomRepository (/task-manager/src/data-source/DataSource.ts:463:29)
    at InstanceWrapper.useFactory [as metatype] (/task-manager/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:13:35)
    at Injector.instantiateClass (/task-manager/node_modules/@nestjs/core/injector/injector.js:333:55)
    at callback (/task-manager/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Injector.resolveConstructorParams (/task-manager/node_modules/@nestjs/core/injector/injector.js:122:24)
    at Injector.loadInstance (/task-manager/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/task-manager/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)

### Steps to Reproduce

just use  "typeorm": "^0.3.3",

Repository example

```typescript
import { EntityRepository, Repository } from 'typeorm';
import { Task } from './task.entity';

@EntityRepository(Task)
export class TasksRepository extends Repository<Task> {}
```

### My Environment

 "typeorm": "^0.3.3",

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Version 0.3 isn't compatible with `@nestjs/typeorm` yet.

Please check their repository for details.

**Comment by can019** [comment]
> Version 0.3 isn't compatible with `@nestjs/typeorm` yet.
> 
> Please check their repository for details.

@Ginden 
Hi I'm using with typedi with express framework, and I have problem with above when using Container.get()
What I need is using transaction with custom repository.

Is there any method to make it work ^0.3.0?

**Comment by davidsandoz** [comment]
Since [v8.1.0](https://github.com/nestjs/typeorm/releases/tag/8.1.0), `@nestjs/typeorm` is compatible with TypeORM 0.3.
