### ISSUE TITLE
Error on Postgres coneection

### ISSUE THREAD

**Issue by hkarimpoor** [typeorm/typeorm#88]
During Compiling it always raise error below : 

node_modules\typeorm\index.js:106
function getConnection(connectionName = "default") {
                                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (F:\Money-Transfer-Manager\money-transfer-manager\build\models\DbContext.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by hkarimpoor** [comment]
It worked,Thanks a lot ,You saved me !!!
