### ISSUE TITLE
Exporting an ES6 entity which extends BaseEntity breaks the application.

### ISSUE THREAD

**Issue by codeninja** [typeorm/typeorm#8826]
## Issue Description
When exporting to ES6 any entity which extends BaseEntity causes an error. I think this is a webpack issue but I'm uncertain that it could be a bug in TypeORM.

```
@Entity({ schema: 'public' })
export class Business extends BaseEntity { ... }
                                                    ^^^ This breaks.
```

### Expected Behavior

If I remove the `extends BaseEntity` 
![image](https://user-images.githubusercontent.com/14914/160680324-4d7812d7-bf26-45b5-8e6c-c2b867537824.png)

You can see that I'm able to access and interact with the object. But all my tests will fail as I no longer have access to save the object. (As expected since I haven't extended my class with base entity functions....)
![image](https://user-images.githubusercontent.com/14914/160680663-70081227-9d96-4ae0-aff6-7aa0f908cf45.png)

### Actual Behavior
The actual behavior observed here 
![image](https://user-images.githubusercontent.com/14914/160681274-6726e4ce-55d6-4e3d-8f37-b8a7269daaa3.png)

When the class is extended properly, errors are thown.

### Steps to Reproduce

Storybook Webpack Config
```
{
  name: 'preview',
  mode: 'development',
  bail: false,
  devtool: 'cheap-module-source-map',
  entry: [
    '/home/codeninja/microventures/mv-nx/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js',
    '/home/codeninja/microventures/mv-nx/node_modules/@storybook/core-client/dist/esm/globals/globals.js',
    '/home/codeninja/microventures/mv-nx/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true',
    '/home/codeninja/microventures/mv-nx/storybook-config-entry.js'
  ],
  output: {
    path: '/home/codeninja/microventures/mv-nx/node_modules/.cache/storybook/public',
    filename: '[name].iframe.bundle.js',
    publicPath: ''
  },
  stats: { preset: 'none', logging: 'error' },
  watchOptions: { ignored: /node_modules/ },
  ignoreWarnings: [ { message: /export '\S+' was not found in 'global'/ } ],
  plugins: [
    VirtualModulesPlugin {
      _compiler: null,
      _watcher: null,
      _staticModules: [Object]
    },
    HtmlWebpackPlugin { userOptions: [Object], version: 5 },
    DefinePlugin { definitions: [Object] },
    ProvidePlugin { definitions: [Object] },
    HotModuleReplacementPlugin { options: {} },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: Map(0) {},
      fsOperations: 0,
      primed: false
    },
    ForkTsCheckerWebpackPlugin { options: [Object] },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    },
    RemoveEmptyScriptsPlugin {
      options: [Object],
      apply: [Function: bound apply]
    },
    DocgenPlugin {
      name: 'React Docgen Typescript Plugin',
      options: [Object]
    }
  ],
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  resolve: {
    extensions: [
      '.mjs', '.js',
      '.jsx', '.ts',
      '.tsx', '.json',
      '.cjs'
    ],
    modules: [ 'node_modules' ],
    mainFields: [ 'browser', 'module', 'main' ],
    alias: {
      '@emotion/core': '/home/codeninja/microventures/mv-nx/node_modules/@emotion/core',
      '@emotion/styled': '/home/codeninja/microventures/mv-nx/node_modules/@emotion/styled',
      'emotion-theming': '/home/codeninja/microventures/mv-nx/node_modules/emotion-theming',
      '@storybook/addons': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/builder-webpack5/node_modules/@storybook/addons',
      '@storybook/api': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/builder-webpack5/node_modules/@storybook/api',
      '@storybook/channels': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/channels',
      '@storybook/channel-postmessage': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/channel-postmessage',
      '@storybook/components': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components',
      '@storybook/core-events': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/builder-webpack5/node_modules/@storybook/core-events',
      '@storybook/router': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/router',
      '@storybook/theming': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/builder-webpack5/node_modules/@storybook/theming',
      '@storybook/semver': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/semver',
      '@storybook/client-api': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/client-api',
      '@storybook/client-logger': '/home/codeninja/microventures/mv-nx/node_modules/@storybook/client-logger',
      react: '/home/codeninja/microventures/mv-nx/node_modules/react',
      'react-dom': '/home/codeninja/microventures/mv-nx/node_modules/react-dom'
    },
    fallback: {
      path: '/home/codeninja/microventures/mv-nx/node_modules/path-browserify/index.js'
    },
    plugins: [ [TsconfigPathsPlugin] ]
  },
  optimization: {
    splitChunks: { chunks: 'all' },
    runtimeChunk: true,
    sideEffects: true,
    usedExports: true,
    moduleIds: 'named',
    minimizer: []
  },
  performance: { hints: false }
} [
  {
    test: /\.(mjs|tsx?|jsx?)$/,
    use: [ [Object] ],
    include: [ '/home/codeninja/microventures/mv-nx' ],
    exclude: /node_modules/
  },
  { test: /\.js$/, use: [ [Object] ], include: [Function: include] },
  { test: /\.md$/, type: 'asset/source' },
  {
    test: /\.js$/,
    include: /node_modules\/acorn-jsx/,
    use: [ [Object] ]
  },
  { test: /(stories|story)\.mdx$/, use: [ [Object], [Object] ] },
  {
    test: /\.mdx$/,
    exclude: /(stories|story)\.mdx$/,
    use: [ [Object], [Object] ]
  },
  {
    test: /\.(stories|story)\.[tj]sx?$/,
    loader: '/home/codeninja/microventures/mv-nx/node_modules/@storybook/source-loader/dist/cjs/index.js',
    options: { injectStoryParameters: true, inspectLocalDependencies: true },
    enforce: 'pre'
  },
  {
    test: /\.(bmp|png|jpe?g|gif|webp|avif)$/,
    type: 'asset',
    parser: { dataUrlCondition: [Object] }
  },
  { test: /\.m?jsx?$/, resolve: { fullySpecified: false } },
  {
    test: /\.css$|\.scss$|\.sass$|\.less$|\.styl$/,
    oneOf: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  { test: /\.svg$/, oneOf: [ [Object], [Object] ] }
]
info => Using default Webpack5 setup
```

```typescript
// insert code here

// this is the business entity for the public schema containing the public business information
@Entity({ schema: 'public' })
export class Business {
  @PrimaryGeneratedColumn()
  id: number;
}

new Business();
```

Again, this seems to work perfectly fine when compiled by ts-node. So I'm thinking maybe this is a webpack thing? I'm mostly looking for fresh eyes on this.

### My Environment

NX + Storybook & NextJS

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | x.y.zzz  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by codeninja** [comment]
FYI: I'd be happy to connect 1:1 with anyone to triage this in my specific environment. Just ping me and I'll setup a room with screen share.

**Comment by dumbasPL** [comment]
NOTE: this can also be easily reproduced using the `typeorm init` example project
```shell
npx typeorm init --name MyProject --database postgres
```
then add `extends BaseEntity` to the example User entity and try to generate a migration
```shell
$ npm run typeorm migration:generate -- -d src/data-source.ts --dr Initial
> MyProject@0.0.1 typeorm
> typeorm-ts-node-commonjs "migration:generate" "-d" "src/data-source.ts" "--dr" "Initial"

Error during migration generation:
TypeError: Class constructor BaseEntity cannot be invoked without 'new'
    at new User (/home/nezu/MyProject/src/entity/User.ts:32:42)
    at EntityMetadata.create (/home/nezu/MyProject/src/metadata/EntityMetadata.ts:563:23)
    at EntityMetadataValidator.validate (/home/nezu/MyProject/src/metadata-builder/EntityMetadataValidator.ts:172:47)
    at /home/nezu/MyProject/src/metadata-builder/EntityMetadataValidator.ts:43:18
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/nezu/MyProject/src/metadata-builder/EntityMetadataValidator.ts:42:25)
    at DataSource.buildMetadatas (/home/nezu/MyProject/src/data-source/DataSource.ts:682:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DataSource.initialize (/home/nezu/MyProject/src/data-source/DataSource.ts:241:13)
    at async Object.handler (/home/nezu/MyProject/src/commands/MigrationGenerateCommand.ts:82:13)
```
