### ISSUE TITLE
DataTypeNotSupportedError: Data type "Object" in "Schedules.data" is not supported by "sqlite" database.

### ISSUE THREAD

**Issue by oqammx86** [typeorm/typeorm#8851]
```
/home/container/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:78
                    throw new DataTypeNotSupportedError_1.DataTypeNotSupportedError(column, normalizedColumn, driver.options.type);
                          ^
DataTypeNotSupportedError: Data type "Object" in "Schedules.data" is not supported by "sqlite" database.
    at /home/container/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:78:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/home/container/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:75:36)
    at /home/container/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:38:58
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/container/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:38:25)
    at DataSource.buildMetadatas (/home/container/node_modules/typeorm/data-source/DataSource.js:447:33)
    at async DataSource.initialize (/home/container/node_modules/typeorm/data-source/DataSource.js:133:13)
    at async file:///home/container/dist/index.js:14:1
Node.js v17.8.0

```

index.ts
```
await createConnection({
    type: "sqlite",
    database: "database",
    entities: [Schedules]
}).then(() => console.log("Successfully connected to database!"));
```

schedules.ts
```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm'

@Entity()
export default class Schedules extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: string;

    @Column()
	type: string;
    
    @Column()
    data: ChannelCreate | BanMember | KickMember | AddRole | CreateRole | DeleteRole | CreateChannel | DeleteChannel | SendMessage | DeleteMessage | ChangeRolePermissions | ChangeChannelPermissions
}
```

**Comment by Ginden** [comment]
Use `simple-json`: https://orkhan.gitbook.io/typeorm/docs/entities#simple-json-column-type
