### ISSUE TITLE
EntityMetaDataNotFoundError: No MetaData for "Profile" was found

### ISSUE THREAD

**Issue by ZachHandley** [typeorm/typeorm#8863]
Hey!

So I recently updated to TypeORM 0.35 and after updating on run I am getting this error

```
/Users/zachhandley/Documents/GitHub/Billboard_500Artists/bb-api/node_modules/typeorm/data-source/DataSource.js:286
            throw new error_1.EntityMetadataNotFoundError(target);
                  ^

EntityMetadataNotFoundError: No metadata for "Profile" was found.
    at DataSource.getMetadata (/Users/zachhandley/Documents/GitHub/Billboard_500Artists/bb-api/node_modules/typeorm/data-source/DataSource.js:286:19)
    at EntityManager.find (/Users/zachhandley/Documents/GitHub/Billboard_500Artists/bb-api/node_modules/typeorm/entity-manager/EntityManager.js:470:42)
    at DBConnection.<anonymous> (/Users/zachhandley/Documents/GitHub/Billboard_500Artists/bb-api/dist/components/database.js:85:49)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zachhandley/Documents/GitHub/Billboard_500Artists/bb-api/dist/components/database.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.8.0
```

I definitely have the Profile built and the entities setup via DataSource (data-source.ts)
```typescript
import { DataSource } from "typeorm";
export const AppDataSource = new DataSource({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "username",
    password: "password",
    database: "database",
    synchronize: true,
    logging: false,
    entities: [
        "../dist/entity/**/*.js"
    ],
    migrations: [
        "../dist/migration/**/*.js"
    ],
    subscribers: [
        "../dist/subscriber/**/*.js"
    ]
})
```

my Profile.ts file
```typescript
import { 
    Entity, 
    PrimaryGeneratedColumn, 
    Column, 
    CreateDateColumn, 
    UpdateDateColumn,
    ManyToMany,
    JoinTable
} from "typeorm";
import * as bcrypt from "bcryptjs";
import { Conversation } from "./Conversation";

@Entity()
export class Profile {
    @PrimaryGeneratedColumn()
    id!: number;

    @Column('text')
    name!: string;

    @Column({nullable: true})
    artistname: string;

    @Column({
        length: 100,
        unique: true
    })
    email!: string;

    @Column("float8")
    lat!: number;

    @Column("float8")
    lng!: number;

    @Column({
        length: 255
    })
    address!: string;

    @Column({
        type: 'text',
    })
    about!: string;

    @Column({
        length: 255
    })
    password!: string; //HASHED PASSWORD!

    @Column("text", {
        array: true
    })
    categories!: Array<String>;

    @Column('boolean')
    available!: boolean;

    @Column('datetime')
    @CreateDateColumn()
    createdAt!: Date;

    @Column('datetime')
    @UpdateDateColumn()
    updatedAt!: Date;

    @ManyToMany(() => Conversation, (conversation) => conversation.users, {
        cascade: true
    })
    @JoinTable()
    conversations: Conversation[];

    hashPassword() {
        this.password = bcrypt.hashSync(this.password, 8);
    }

    checkIfUnencryptedPasswordIsValid(unencryptedPassword: string) {
        return bcrypt.compareSync(unencryptedPassword, this.password);
    }
}
```

unless I need to use the entity that's in my `./entity/**/*.ts`

I'm confused as to why this is happening, any advice on how to fix it is appreciated

Thanks for all your time <3
- Zach

**Comment by ZachHandley** [comment]
Had to use absolute paths for some reason with the DataSource
