### ISSUE TITLE
[v0.3.5] [postgres 12.4] Using the .orUpdate option is no longer working in an insert query. 

### ISSUE THREAD

**Issue by juansaav** [typeorm/typeorm#8876]
## Issue Description
I've this entity
```
@Entity({ name: "offloads" })
export class Offload {
  @PrimaryColumn({ type: "uuid", name: "object_id" })
  objectID!: string;

  @Index()
  @Column({ type: "uuid", name: "event_id", nullable: true })
  eventID?: string;

  ....
}
```

And I want to run this query:
```
await offloadRepo
    .createQueryBuilder()
    .insert()
    .values({
      objectID: uuid(),
      eventID: uuid(),
      ...
    })
    .orUpdate(["event_id"], ["object_id"], {
      skipUpdateIfNoValuesChanged: true,
    })
    .execute();
```
It should work fine, but it throws a postgres error.

### Expected Behavior
Insert the row if it doesn't exist. Update the given columns in case it already exists.
### Actual Behavior
It throws this postgres error:
```
QueryFailedError: invalid reference to FROM-clause entry for table "offloads"
    at PostgresQueryRunner.query (pathTo//driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at InsertQueryBuilder.execute (pathTo//query-builder/InsertQueryBuilder.ts:161:33)
    at x (pathTo/repl.ts:104:3) {
  query: 'INSERT INTO "offloads" AS "Offload"("object_id", "upload_id", "event_id", …) VALUES ($1, $2, …) ON CONFLICT ( "object_id" ) DO UPDATE SET "event_id" = EXCLUDED."event_id"  WHERE ("offloads"."event_id" IS DISTINCT FROM EXCLUDED."event_id" )',
  parameters: [
    'd3a1e03b-4377-4f17-bc36-918c31b5461a',
    '36787523-56cd-4a79-b2cb-9fc79e5d1e7d',
    …
  ],
  driverError: error: invalid reference to FROM-clause entry for table "offloads"
      at Parser.parseErrorMessage (pathTo/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (pathTo/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (pathTo/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (pathTo/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 192,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Offload".',
    position: '349',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3299',
    routine: 'errorMissingRTE'
  },
  length: 192,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: 'Perhaps you meant to reference the table alias "Offload".',
  position: '349',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3299',
  routine: 'errorMissingRTE'
}
```
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     |16.14.2  | 
| Typescript version  | 4.2.2  | 
| TypeORM version     | 0.3.5  | 
| Postgres version     | 12.4  | 

### Additional Context
Investigating I found that the problem is this parameter:
`{
      skipUpdateIfNoValuesChanged: true,
  },
`
If I remove it, it works.
### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 -  ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by mrtpdv** [comment]
any updates here?

**Comment by emretepedev** [comment]
any updates here?

**Comment by taylorhakes** [comment]
I am also seeing this error. It's related to aliases not working in `skipUpdateIfNoValuesChanged`
