### ISSUE TITLE
Cannot set property metadata of #<Repository> which has only a getter

### ISSUE THREAD

**Issue by feather-jmalone** [typeorm/typeorm#8883]
## Issue Description

The type file for `Repository` (`src/repository/Repository.ts` line 51) contains a `get metadata()` definition, but no `set()` definition. Depending on your settings and dependency versions, this can result in the following error from the TypeScript compiler:

```
Cannot set property metadata of #<Repository> which has only a getter
```

**NOTE:** I discovered this issue while using TypeORM in a NestJS application, but it is not a NestJS specific issue, really; it's more a typedef / compilation issue.

When the NestJS application loads, NestJS shows the error above, with the following stack trace:

```
TypeError: Cannot set property metadata of #<Repository> which has only a getter
    at EntityManager.getCustomRepository (/Users/githubperson/nestjs-project/node_modules/typeorm/entity-manager/EntityManager.js:756:50)
    at DataSource.getCustomRepository (/Users/githubperson/nestjs-project/node_modules/typeorm/data-source/DataSource.js:320:29)
    at InstanceWrapper.useFactory [as metatype] (/Users/githubperson/nestjs-project/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:13:35)
    at Injector.instantiateClass (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/injector.js:289:55)
    at callback (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/injector.js:42:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/injector.js:114:24)
    at async Injector.loadInstance (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/injector.js:46:9)
    at async Injector.loadProvider (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/injector.js:68:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
    at async /Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/instance-loader.js:28:13
    at async Promise.all (index 55)
    at async InstanceLoader.createInstances (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/instance-loader.js:27:9)
    at async InstanceLoader.createInstancesOfDependencies (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/injector/instance-loader.js:17:9)
    at async /Users/githubperson/nestjs-project/node_modules/@nestjs/core/nest-factory.js:90:17
    at async Function.asyncRun (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/errors/exceptions-zone.js:18:13)
    at async NestFactoryStatic.initialize (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/nest-factory.js:88:13)
    at async NestFactoryStatic.create (/Users/githubperson/nestjs-project/node_modules/@nestjs/core/nest-factory.js:34:9)
    at async bootstrap (/Users/githubperson/nestjs-project/dist/src/main.js:45:17)
```

### Expected Behavior

Expected to be able to compile the latest `typeorm` with the latest `@nestjs/core` and `@nestjs/typeorm`

### Actual Behavior

Compilation fails due to the error about the `metadata` property of `Repository`:

```
Cannot set property metadata of #<Repository> which has only a getter
```

### Steps to Reproduce

- Install TypeORM and NestJS: `npm install typeorm @nestjs/core @nestjs/common @nestjs/typeorm`
- Configure data source and entities
- Run NestJS application

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | osx Big Sur 11.5.2 (20G95)  |
| Node.js version     | v16.14.2  |
| Typescript version  | v4.6.3  |
| TypeORM version     | v0.3.5  |
| NestJS version     | v7.6.18  |

### Additional Context

N/A

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | Unknown       |
| `aurora-postgres` | Unknown       |
| `better-sqlite3`  | Unknown       |
| `cockroachdb`     | Unknown       |
| `cordova`         | Unknown       |
| `expo`            | Unknown       |
| `mongodb`         | Unknown       |
| `mysql`           | YES           |
| `nativescript`    | Unknown       |
| `oracle`          | Unknown       |
| `postgres`        | Unknown       |
| `react-native`    | Unknown       |
| `sap`             | Unknown       |
| `sqlite`          | Unknown       |
| `sqlite-abstract` | Unknown       |
| `sqljs`           | Unknown       |
| `sqlserver`       | Unknown       |

**NOTE:** While this was discovered using the `mysql` driver, it is not a driver-specific issue.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
@feather-jmalone This reproduction won't work - `@nestjs/typeorm` wasn't updated to support TypeORM 0.3 yet.

https://github.com/nestjs/typeorm/pull/1233

**Comment by davidsandoz** [comment]
Since [v8.1.0](https://github.com/nestjs/typeorm/releases/tag/8.1.0), `@nestjs/typeorm` is compatible with TypeORM 0.3.

I was able to make the necessary changes by following [this article](https://tech.durgadas.in/creating-and-using-custom-repositories-in-nestjs-with-typeorm-0-3-c7ac9548ad99).
