### ISSUE TITLE
Add insert support for BLOB data types

### ISSUE THREAD

**Issue by zzinx58** [typeorm/typeorm#8899]
When i try to insert a Blob data types, here is the error report:

Argument of type '{ username: string; password_Blob: Blob; }' is not assignable to parameter of type 'QueryDeepPartialEntity<User> | QueryDeepPartialEntity<User>[]'.
  Object literal may only specify known properties, and 'password_Blob' does not exist in type 'QueryDeepPartialEntity<User> | QueryDeepPartialEntity<User>[]'.

**Comment by q1095568627** [comment]
After i append Blob data types to the correspondent property in my entity and dto in order to unify the data types. An error appeared: could it be a bug?

DataTypeNotSupportedError: Data type "Object" in "User.password" is not supported by "mariadb" database.

at DataTypeNotSupportedError.TypeORMError [as constructor] (/back-end-workbench/punch-in5/src/error/TypeORMError.ts:7:9)
    at new DataTypeNotSupportedError (/back-end-workbench/punch-in5/src/error/DataTypeNotSupportedError.ts:8:9)
    at /back-end-workbench/punch-in5/src/metadata-builder/EntityMetadataValidator.ts:89:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/back-end-workbench/punch-in5/src/metadata-builder/EntityMetadataValidator.ts:86:36)
    at /back-end-workbench/punch-in5/src/metadata-builder/EntityMetadataValidator.ts:46:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/back-end-workbench/punch-in5/src/metadata-builder/EntityMetadataValidator.ts:46:25)
    at Connection.<anonymous> (/back-end-workbench/punch-in5/src/connection/Connection.ts:533:33)
    at step (/back-end-workbench/punch-in5/node_modules/tslib/tslib.js:143:27)

**Comment by Ginden** [comment]
Needs code, env etc.

Please format your code using triple backtick.

Did you intend to use `Buffer` type?
