### ISSUE TITLE
OneToOne with option eager:true trows error 'Relation with property path ** in entity was not found'

### ISSUE THREAD

**Issue by NenadJovicic** [typeorm/typeorm#8907]
## Issue Description
I have an issue when using `Repository.find({})` on Entity that has `@OneToOne({eager: true})` relation

My model looks like this

```typescript
@Entity({ name: 'a' })
@TableInheritance({ column: { type: 'enum', name: 'type', enum: SomeType } })
export class AParent {
  @PrimaryGeneratedColumn()
  id?: number;

  @Column({ type: 'enum', enum: SomeType })
  type: SomeType;
}

@ChildEntity(SomeType.typeB)
export class AChild extends AParent {
  @Column({ nullable: false, length: 250, type: 'varchar' })
  someExtraField: string;
}

@Entity({ name: 'b' })
export class B {
  @PrimaryGeneratedColumn()
  id?: number;

  @OneToOne(() => AChild, { nullable: true, eager: true })
  @JoinColumn()
  aChild: AChild;

  @OneToOne(() => AParent, { nullable: true, eager: false })
  @JoinColumn()
  aParent?: AParent;
}
```

When I want to query all rows from table `b` like this
```typescript
const bRepository: Repository<B>;
const result = await bRepository.find({});
```
I get the following error
`TypeORMError: Relation with property path aChild in entity was not found.`

It does not throw an error when I set `eager: false` for `aChild` property
Same is happening when I put `eager: true` for `aParent` and `eager: false` for `aChild`, just will get an error `path aParent in entity was not found.`

### Expected Behavior

Expected behavior is that I get populated `aChild` and `aParent` when I query class B with `find()`

### Actual Behavior

```console
TypeORMError: Relation with property path aChild in entity was not found.
at new TypeORMError (/home/app/src/error/TypeORMError.ts:7:9)
at JoinAttribute.getValue (/home/app/src/query-builder/JoinAttribute.ts:161:23)
at JoinAttribute.get (/home/app/src/query-builder/JoinAttribute.ts:163:53)
at JoinAttribute.get (/home/app/src/query-builder/JoinAttribute.ts:176:18)
at SelectQueryBuilder.join (/home/app/src/query-builder/SelectQueryBuilder.ts:1343:27)
at SelectQueryBuilder.leftJoin (/home/app/src/query-builder/SelectQueryBuilder.ts:315:14)
at /home/app/src/find-options/FindOptionsUtils.ts:289:20
at Array.forEach (<anonymous>)
at Function.joinEagerRelations (/home/app/src/find-options/FindOptionsUtils.ts:265:33)
at /home/app/src/find-options/FindOptionsUtils.ts:308:18

```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Using docker containers      |
| Node.js version     | node:16.13.0-alpine3.14  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.38  | 
| NestJS | 8.1.2 |
| Postgres image | postgres:14 |

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by altschuler** [comment]
I have the same issue. I tried using `loadEagerRelations: false` but it doesn't help.
