### ISSUE TITLE
EntityMetadataNotFoundError: No metadata for x was found.

### ISSUE THREAD

**Issue by AaronMcCloskey** [typeorm/typeorm#8920]
## Issue Description

My project has 2 seperate connection datasources. One is to a readonly `mysql` database, the other is a `postgres` database.

Everything on the `mysql` database works fine. But I'm having issues with the `postgres` database.

In my `index.ts` file where I spin up my server, I initialize the `postgres` db datasouce

```
pgDataSource.initialize();
```

And here is `pgDataSource`

```
import 'reflect-metadata';
import 'dotenv-safe/config';
import { DataSource } from 'typeorm';
import path from 'path';
import Score from '../entities/Score';

const pgDataSource = new DataSource({
  name: 'favourites',
  type: 'postgres',
  url: process.env.DATABASE_URL,
  logging: true,
  synchronize: true,
  migrations: [path.join(__dirname, './migrations/*')],
  entities: [Score],
});

export const Manager = pgDataSource.manager;
export const ScoreRepository = pgDataSource.getRepository(Score);

export default pgDataSource;
```

At this point, everything seems fine, it creates a table in my database with the `Score` entity, so the connection exists and it acknowledges that there is an Entity as it creates the corresponding table.

Here is my `Score` entity

```
import { ObjectType, Field, Int } from 'type-graphql';
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm';

@ObjectType()
@Entity({ database: 'pp_favourites', name: 'score' })
class Score extends BaseEntity {
  @Field()
  @PrimaryGeneratedColumn()
  id!: number;

  @Field(() => Int)
  @Column()
  propertyId!: number;
}

export default Score;
```

### Actual Behavior

When I run this query

```
await ScoreRepository.createQueryBuilder().getMany()
```

In a `Query` decorator function, I get the `No metadata for \"Score\" was found.` error

Although, if I run it through a `useMiddleware` decorator, it strangely works?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS Catalina        |
| Node.js version     | v16.13.0  | 
| Typescript version  | 4.5.4  | 
| TypeORM version     | 0.3.6  | 

### Additional Context

I've tried

 1. Adding `@Resolver(Score)` as a decorator to the `ShortlistResolver`
 2. Removing the `dist` folder
 3. creating a new database and new connection
 4. Logged `Manager.connection.entityMetadatas` from `pgDataSource` which shows there are no entity's, despite being defined.

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AaronMcCloskey** [comment]
FWIW, irregardless of having 2 datasoures. Just trying this with one `postgres` datasource, still getting the same issue.

Also, another weird thing is that running the following works fine???

```
await Score.find()
```

But running `pgDataSource.getRepository(Score).createQueryBuilder().getMany()` doesn't?

**Comment by XXXL3J** [comment]
Similar issue while running[ the code of Using with Javascript](https://typeorm.io/usage-with-javascript) with ` "typeorm": "^0.3.6".`  

It worked well with the original code, but for the custom code like this

````
// typeorm config
const typeorm = require("typeorm")
const mysqlConf = require('./database');

const dataSource = new typeorm.DataSource({
    type: "mysql",
    host: mysqlConf.host,
    port: mysqlConf.port,
    username: mysqlConf.user,
    password: mysqlConf.password,
    database: mysqlConf.database,
    synchronize: true,
    logging: false,
     entities: [
        require("../core/post/entity"),  
    ]
})
module.exports = {
    dataSource,
}
````

````
//entity.js
const EntitySchema = require("typeorm").EntitySchema;

module.exports = new EntitySchema({
    name: "Post", // Will use table name `post` as default behaviour.
    tableName: "post", // Optional: Provide `tableName` property to override the default behaviour for table name.
    columns: {  
        id: {
            primary: true,
            type: "int",
            generated: true,
        },
        title: {
            type: "varchar",
        },
        text: {
            type: "text",
        }, 

    }, 
})
````

````
// router.js
const express = require('express'); 
const router = express.Router(); 
const Typeorm = require('../../config/typeorm.js').dataSource;
const PostEntity = Typeorm.getRepository(require('./entity.js')); 

router.get('/', async function (req, res) {
    const results = await PostEntity.find();
    res.send(results)
});
````

``
// terminal throw ``
`` throw new error_1.EntityMetadataNotFoundError(target); 
EntityMetadataNotFoundError: No metadata for "Post" was found.``


Many stackoverflow solutions focus on the path of  `entities` when define `new typeorm.DataSource({})` but not work for mine situation.

**Comment by AaronMcCloskey** [comment]
@XXXL3J So I did eventually fix this, not sure if this will work in your case, but if I deleted the datasource file and used the same code in a new file (i did use a new filename, but may well work with the previous filename), it started to work.

**Comment by harshrawat66** [comment]
The following solution works.
Modify the files as shown below

tasks.repository.ts
```
import { Injectable } from '@nestjs/common';
import { DataSource, Repository } from 'typeorm';
import { CreateTaskDto } from './create-task.dto';
import { TaskStatus } from './task-status.enum';
import { Task } from './task.entity';

@Injectable()
export class TaskRepository extends Repository<Task> {
  constructor(private dataSource: DataSource) {
    super(Task, dataSource.createEntityManager());
  }

  async createTask({ title, description }: CreateTaskDto): Promise<Task> {
    const task = this.create({
      title,
      description,
      status: TaskStatus.OPEN,
    });

    await this.save(task);
    return task;
  }
}

```

tasks.module.ts
```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Task } from './task.entity';
import { TasksController } from './tasks.controller';
import { TaskRepository } from './tasks.repository';
import { TasksService } from './tasks.service';

@Module({
  imports: [TypeOrmModule.forFeature([Task])],
  controllers: [TasksController],
  providers: [TasksService, TaskRepository],
})
export class TasksModule {}

```

tasks.service.ts
```
import { Injectable, NotFoundException } from '@nestjs/common';
import { TaskStatus } from './task-status.enum';
import { CreateTaskDto } from './create-task.dto';
import { GetTaskFilterDto } from './get-task-filter.dto';
import { TaskRepository } from './tasks.repository';
import { InjectRepository } from '@nestjs/typeorm';
import { Task } from './task.entity';

@Injectable()
export class TasksService {
  constructor(private readonly tasksRepository: TaskRepository) {}

  async getTaskById(id: string): Promise<Task> {
    const record = this.tasksRepository.findOne({ where: { id } });
    if (!record) {
      throw new NotFoundException();
    }
    return record;
  }

  createTask(createTaskDto: CreateTaskDto): Promise<Task> {
    return this.tasksRepository.createTask(createTaskDto);
  }
}
```

**Comment by DanMoulton** [comment]
I'm seeing the same error, but it's frustrating since it only happens when trying to write to a remote MySQL database that has the exact same schema as my local MySQL database:

```
NotFoundException: No metadata for "Role" was found.
    at /home/dan/Disk/Development/maa-ml-esg-monorepo/modules/api/src/auth/role/role.service.ts:74:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

`Role` is already present in my entites array so I don't know what's going on...

**Comment by wallace-sf** [comment]
> I'm seeing the same error, but it's frustrating since it only happens when trying to write to a remote MySQL database that has the exact same schema as my local MySQL database:
> 
> ```
> NotFoundException: No metadata for "Role" was found.
>     at /home/dan/Disk/Development/maa-ml-esg-monorepo/modules/api/src/auth/role/role.service.ts:74:28
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> `Role` is already present in my entites array so I don't know what's going on...
> 
> **Edit:** It turns out I was getting this error since the write operation was happening on startup, and I wasn't awaiting for my datasources to initialize. Adding `await` fixed it:
> 
> ```
> await ReadDataSource.initialize();
> await WriteDataSource.initialize();
> ```

It worked to me as well. Thanks!

**Comment by JohnnyClutch** [comment]
I'm getting this error with a Schema / Entity separated approach, and as I haven't seen anyone address that configuration here..

Error text from exception: "No metadata for "OrganizationUserEntity" was found."

Here are my relevant sources:

entity definition
```
export class OrganizationUserEntity extends TenantBaseEntity {

	private _jobTitle: string;
	set jobTitle(newVal: string) {
		this._jobTitle = newVal;
	}
	get jobTitle(): string {
		return this._jobTitle;
	}

	private _username: string;
	set username(newVal: string) {
		this._username = newVal;
	}
	get username(): string {
		return this._username;
	}
}
```

schema definition
```
import { EntitySchema } from 'typeorm';
import { TenantBaseColumns } from '../core/tenantBase.schema';
import { OrganizationUserEntity } from '@packName/typeorm-entities';

export const OrganizationUserSchema = new EntitySchema<OrganizationUserEntity>({
	name: 'OrganizationUser',
	tableName: 'organization_users',
	columns: {
		...TenantBaseColumns,
		jobTitle: { name: 'job_title', type: String, },
		username: { name: 'username', type: String, },
	},
});
```

connection factory service:
```
@Injectable()
export class TypeOrmConfigService implements TypeOrmOptionsFactory {
	createTypeOrmOptions(): Promise<TypeOrmModuleOptions> {
		const deferred = new Promise<TypeOrmModuleOptions>(
			(resolve) => {
				const compileParams = (): any => {
					const connectionOptions: TypeOrmModuleOptions = {
						type: 'postgres',
						port: 5432,
						logger: 'advanced-console',
						logging: [	'error', 'schema',],
						host: 'localhost',
						username: 'username',
						database: 'dbname',
						password: 'password',
						namingStrategy: new NamingStrategy(),
						keepConnectionAlive: true,
						autoLoadEntities: true,
						verboseRetryLog: true,
						entities: [ OrganizationUserSchema ], (among others)
					};
					return connectionOptions;
				};
				resolve(compileParams());
			}
		);
		return deferred;
	}
}
```

nest shared module
```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TypeOrmConfigService } from './services/typeOrmConfig.service';

@Module({
	imports: [
		TypeOrmModule.forRootAsync(
		{
			useClass: TypeOrmConfigService,
                 }),
	],
})
export class NestSharedModule {
}
```

app.module.ts
``` 
import { Module } from '@nestjs/common';
import { NestSharedModule, } from '@packName/nest-shared';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrganizationUserEntity } from '@packName/typeorm-entities';

@Module({
	imports: [
		NestSharedModule,
		TypeOrmModule.forFeature([ OrganizationUserEntity ]),
	],
})
export class AppModule {
}
```

service:
```
import { Observable } from 'rxjs';
import { Injectable } from '@nestjs/common';
import { Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { OrganizationUserEntity, }  from '@packName/typeorm-entities';

@Injectable()
export class AuthService {
	constructor(
		@InjectRepository(OrganizationUserEntity)
		private userRepo: Repository<OrganizationUserEntity>,
	) {
	}

 	pullUser(username: string): Observable<OrganizationUserEntity> {
		const servable = new Observable<OrganizationUserEntity>(
			(resolver) => {
				const searchParams: any = {
					where: {
						username,
						isDeleted: false,
					},
				}
				this.userRepo.findOne(searchParams).then(
					(user: any) => {
						resolver.next(user);
						resolver.complete();
					},
					(err) => {
						console.log(JSON.stringify(err));
						resolver.error('error pulling user info');
					}
				);
			}
		);
		return servable;
	}
}
```

console output
```
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [NestFactory] Starting Nest application...
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +38ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] LoggerModule dependencies initialized +0ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 71312  - 02/08/2024, 11:46:20 AM     LOG [InstanceLoader] NestSharedModule dependencies initialized +1ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +251ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [InstanceLoader] AppModule dependencies initialized +8ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [RoutesResolver] AuthController {/api/auth}: +31ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [RouterExplorer] Mapped ... multiple routes ...
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG [NestApplication] Nest application successfully started +4ms
[Nest] 71312  - 02/08/2024, 11:46:21 AM     LOG Listening at http://localhost:3333/api
```

- using nx webpack implementation
- I'm trying to upgrade to 0.3.20 from 0.2.32, so all the schemas were working with getConnection().getRepository etc.
- The userRepo in AuthService is injecting (seemingly) properly.
- It's not a timing issue -- forRootAsync finishes before query runs as I don't try to pullUser until a request comes in.
- I tried setting an invalid name for the database name in the connection params, and it swore at me as it should (error: database "dklfajd" does not exist)


Any hints?

**Comment by rosehsu47** [comment]
same problem here, any hints to fix EntityMetadataNotFoundError error?

**Comment by jkeczan** [comment]
I have the same issue as well from nx webpack implementation as well. Everything is being bundled into the main.js file. I used 
```
 getMetadataArgsStorage().tables.map(table => table.target)

``` and all of my entities are registering correctly. It is just the metadata that is missing
