### ISSUE TITLE
Migrations don't wait for connection

### ISSUE THREAD

**Issue by lucasgama335** [typeorm/typeorm#8928]
## Issue Description
The cli command to run the migrations doesn't work. It always says: "CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established."

### Expected Behavior
Migrations are performed and tables are created in the database

### Actual Behavior
My datasource file is in ./src/core/database/typeorm/index.ts:
```
import { DataSource } from 'typeorm';

export const AppDataSource = new DataSource({
    type: 'postgres',
    host: process.env.DOCKER_MODE === 'local' ? 'localhost' : 'database',
    port: 5432,
    username: 'docker',
    password: 'root',
    database: process.env.NODE_ENV === 'test' ? 'api_base_test' : 'api_base',
    synchronize: false,
    logging: process.env.NODE_ENV !== 'production' ? ['error'] : false,
    entities: ['./src/modules/**/entities/typeorm/*.ts'],
    migrations: ['./src/core/database/typeorm/migrations/*.ts'],
});

```
(I already tried to export the dataSource file without the function it contains, just with the variable, but the same problem occurs)

I start my appDataSource in the file that runs the server
```
import 'reflect-metadata';
import 'dotenv/config';
import colors from 'colors';
import cors from 'cors';
import express from 'express';
import 'express-async-errors';

import CorsConfig from '@config/cors';
import upload from '@config/upload';
import { AppDataSource } from '@core/database/typeorm';
import '@core/container';

import { ExceptionHandler } from './errors/ExceptionHandler';
import { RateLimiter } from './middlewares/RateLimiter';
import { routes } from './routes';

const app = express();

/**
 * Middlewares
 */
app.use(express.json()); // Enables express to use json objects in API communication
app.use(RateLimiter);
app.use('/avatar', express.static(`${upload.storageFolder}/users/avatars`)); // Static Route to access local files
app.use(cors(CorsConfig)); // Server access settings.
app.use(routes); // Import routes from the application.
app.use(ExceptionHandler); // Handles application errors

// no need to start the server for jest to do the tests, it takes care of it itself
if (process.env.NODE_ENV !== 'test') {
    AppDataSource.initialize()
        .then(() => {
            console.log(`${colors.cyan('[DATABASE]:')} Connection established with the database.`);
            app.listen(process.env.APP_API_PORT, () =>
                console.log(`${colors.green('[SERVER]:')} Server started: ${process.env.APP_API_URL}.`),
            );
        })
        .catch(err => {
            console.log(`${colors.red('[DATABASE]:')} Error during Data Source initialization.`);
            console.log(`${colors.red('[SERVER]:')} Server closed.`);
            console.log(err);
        });
}

export { app };


```

I run the command: "npx typeorm-ts-node-commonjs -d ./src/core/database/typeorm/index.ts  migration:run" and the following error ocurr.
```
Runs all pending migrations.

Options:
  -h, --help         Show help                                         [boolean]
  -d, --dataSource   Path to the file where your DataSource instance is defined.
                                                                      [required]
  -t, --transaction  Indicates if transaction should be used or not for
                     migration run. Enabled by default.     [default: "default"]
  -v, --version      Show version number                               [boolean]

CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (C:\Users\lucas\Documents\Programação\Dashboard\server\src\data-source\DataSource.ts:284:19)
    at Object.handler (C:\Users\lucas\Documents\Programação\Dashboard\server\src\commands\MigrationRunCommand.ts:73:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\Users\lucas\Documents\Programação\Dashboard\server>
```

if a run the cli command: "npx typeorm -d ./src/core/database/typeorm/index.ts  migration:run" without "typeorm-ts-node-commonjs" the following error occur:
```
Error during migration run:
Error: Unable to open file: "C:\Users\lucas\Documents\Programação\Dashboard\server\src\core\database\typeorm\index.ts". Cannot use import statement outside a module
    at Function.loadDataSource (C:\Users\lucas\Documents\Programação\Dashboard\server\node_modules\typeorm\commands\CommandUtils.js:22:19)
    at async Object.handler (C:\Users\lucas\Documents\Programação\Dashboard\server\node_modules\typeorm\commands\MigrationRunCommand.js:34:26)
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 11    |
| Node.js version     | 16.14.2  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by lucasgama335** [comment]
after debugging the typeorm cli, i identified that the error was mine.
in my datasource I check some environment variables, only they were returning null. I managed to make the correction by importing dotenv before dataSource.
```
import 'dotenv/config';
import { DataSource } from 'typeorm';

export const AppDataSource = new DataSource({
    type: 'postgres',
    host: process.env.DOCKER_MODE === 'local' ? 'localhost' : 'database',
    port: 5432,
    username: 'docker',
    password: 'root',
    database: process.env.NODE_ENV === 'test' ? 'api_base_test' : 'api_base',
    synchronize: false,
    logging: process.env.NODE_ENV !== 'production' ? ['error'] : false,
    entities: ['./src/modules/**/entities/typeorm/*.ts'],
    migrations: ['./src/core/database/typeorm/migrations/*.ts'],
});
```
