### ISSUE TITLE
"Syntax error at or near *" after `queryRunner.addColumn()` with default value calling.

### ISSUE THREAD

**Issue by DES-Destry** [typeorm/typeorm#8943]
## Issue Description
SQL query builded not correctly with `queryRunner.addColumn()` with DEFAULT value for column.

### Expected Behavior
`queryRunner.addColumn()` must generate correct SQL query and execute it.
Code example:
```ts
    await queryRunner.addColumn(
      'users',
      new TableColumn({
        default: id,
        name: 'role_id',
        type: 'uuid',
      }),
    );
```

### Actual Behavior

Error message:
```
query failed: ALTER TABLE "users" ADD "role_id" uuid NOT NULL DEFAULT bdce3a70-3262-4a8f-936c-1fe962a7bf0b
error: error: syntax error at or near "a8f"
    at Parser.parseErrorMessage (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
Migration * failed, error: syntax error at or near "a8f"
query: ROLLBACK
Error during migration run:
QueryFailedError: syntax error at or near "a8f"
    at QueryFailedError.TypeORMError [as constructor] (/Users/destry.unimaster/Develop/javascript/backend/*/*/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/destry.unimaster/Develop/javascript/backend/*/*/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/destry.unimaster/Develop/javascript/backend/*/*/src/driver/postgres/PostgresQueryRunner.ts:263:19)
    at step (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'ALTER TABLE "users" ADD "role_id" uuid NOT NULL DEFAULT bdce3a70-3262-4a8f-936c-1fe962a7bf0b',
  parameters: undefined,
  driverError: error: syntax error at or near "a8f"
      at Parser.parseErrorMessage (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (/Users/destry.unimaster/Develop/javascript/backend/*/*/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
    length: 92,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '72',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'scan.l',
    line: '1176',
    routine: 'scanner_yyerror'
  },
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
error Command failed with exit code 1.
```

### Steps to Reproduce

1. Create migration.
2. In `up(QueryRunner)` method create table.
3. Create new column for this table with _default_ value.
4. Launch migration and catch an error.

```typescript
import { MigrationInterface, QueryRunner, Table, TableColumn } from 'typeorm';
import { v4 as uuid } from 'uuid';

export class DebugMigration implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const id = uuid();

    await queryRunner.createTable(
      new Table({
        name: 'users',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'uuid',
          },
          { name: 'nickname', type: 'varchar', isNullable: true },
          { name: 'created_at', type: 'timestamp', default: 'now()' },
          { name: 'updated_at', type: 'timestamp', default: 'now()' },
        ],
      }),
    );

    await queryRunner.addColumn(
      'users',
      new TableColumn({
        default: id, // It's important part
        name: 'role_id',
        type: 'uuid',
      }),
    );
  }

  public async down(): Promise<void> {
    throw new Error('Method not implemented.');
  }
}

```

### My Environment

@nestjs/common@8.0.0
@nestjs/core@8.0.0
@nestjs/typeorm@8.0.3

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macos Monterey 12.3.1         |
| Node.js version     | 16.13.2  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.2.45  | 

### Additional Context
The reason of this error - incorrect SQL query generation. It looks like this in error message: `ALTER TABLE "users" ADD "role_id" uuid NOT NULL DEFAULT bdce3a70-3262-4a8f-936c-1fe962a7bf0b`.

But correct SQL query must looks like: `ALTER TABLE "users" ADD "role_id" uuid NOT NULL DEFAULT 'bdce3a70-3262-4a8f-936c-1fe962a7bf0b'`.  QueryRunner forgot quotes for default value.

```typescript
    // Correctly executed
    await queryRunner.query(
      `alter table public.users add role_id uuid not null default '${id}';`,
    );

    // Execution failed
    await queryRunner.addColumn(
      'users',
      new TableColumn({
        default: id,
        name: 'role_id',
        type: 'uuid',
      }),
    );

    // Second example in raw SQL behavior looks like this
    await queryRunner.query(
      `alter table public.users add role_id uuid not null default ${id};`,
    );
```

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Working as expected - in this case, `default: id,` result in pasting string as-is. This is unsolvable in general case.
