### ISSUE TITLE
Connection pooling apparently not queuing new connections

### ISSUE THREAD

**Issue by gpmarchi** [typeorm/typeorm#8948]
## Issue Description

I've been using typeorm in my project and now I'm starting to do some performance tests on some endpoints. I've also enabled clustering of my api to allow all cpu cores to be used (my machine has 12 cores with 16 GB RAM).

After I enabled the usage of cluster in my application I started to observe errors related to database connections when executing performance tests with autocannon.

As I went through typeorm docs, I realized that connection pooling is the default behavior but that doesn't seem to be true in my case. I'm using PostgreSQL and `max_connections` parameter is set to the default of 100.

So whenever I run autocannon to test an endpoint of my API with 100 concurrent connections, everything works fine:

```bash
❯ autocannon -m "GET" -c 100 -d 10 --renderStatusCodes http://localhost:3333/users                       
Running 10s test @ http://localhost:3333/users
100 connections

┌─────────┬──────┬───────┬───────┬───────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max    │
├─────────┼──────┼───────┼───────┼───────┼──────────┼──────────┼────────┤
│ Latency │ 4 ms │ 12 ms │ 40 ms │ 51 ms │ 15.79 ms │ 25.27 ms │ 763 ms │
└─────────┴──────┴───────┴───────┴───────┴──────────┴──────────┴────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Req/Sec   │ 1891   │ 1891   │ 5759    │ 8607    │ 6144.3  │ 1873.02 │ 1891   │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Bytes/Sec │ 819 kB │ 819 kB │ 2.49 MB │ 3.73 MB │ 2.66 MB │ 811 kB  │ 819 kB │
└───────────┴────────┴────────┴─────────┴─────────┴─────────┴─────────┴────────┘
┌──────┬───────┐
│ Code │ Count │
├──────┼───────┤
│ 200  │ 61446 │
└──────┴───────┘

Req/Bytes counts sampled once per second.

62k requests in 10.04s, 26.6 MB read
```

But if I increase the concurrent connections to 105, then I start running into internal server errors (connection problems) :

```bash
❯ autocannon -m "GET" -c 105 -d 10 --renderStatusCodes http://localhost:3333/users                      
Running 10s test @ http://localhost:3333/users
105 connections

┌─────────┬──────┬───────┬───────┬───────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max    │
├─────────┼──────┼───────┼───────┼───────┼──────────┼──────────┼────────┤
│ Latency │ 4 ms │ 14 ms │ 42 ms │ 52 ms │ 16.83 ms │ 22.52 ms │ 717 ms │
└─────────┴──────┴───────┴───────┴───────┴──────────┴──────────┴────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 2841    │ 2841    │ 6175    │ 7119    │ 6063.9  │ 1176.17 │ 2840    │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Bytes/Sec │ 1.23 MB │ 1.23 MB │ 2.67 MB │ 3.08 MB │ 2.62 MB │ 508 kB  │ 1.23 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
┌──────┬───────┐
│ Code │ Count │
├──────┼───────┤
│ 200  │ 60422 │
├──────┼───────┤
│ 500  │ 212   │
└──────┴───────┘

Req/Bytes counts sampled once per second.

60422 2xx responses, 212 non 2xx responses
61k requests in 10.05s, 26.2 MB read
```

### Expected Behavior

Since connection pooling is the default behavior, I'd expect the connections to be handled properly and if all the connections are taken, then some of the queries should be queued until a connection is available again in the pool.

### Actual Behavior

Apparently when I exceed the number of connections made available by the database/pool, I start getting connection related errors:

```bash
error: sorry, too many clients already
    at Parser.parseErrorMessage (/mnt/sda1/www/typeorm-conection-pool/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/mnt/sda1/www/typeorm-conection-pool/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/mnt/sda1/www/typeorm-conection-pool/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/mnt/sda1/www/typeorm-conection-pool/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 85,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'proc.c',
  line: '359',
  routine: 'InitProcess'
}
```

### Steps to Reproduce

1. clone repo: https://github.com/gpmarchi/typeorm-conection-pool
2. install dependencies: `yarn`
3. have an instance of PostgreSQL running
4. create database named `database`
5. run migrations: `yarn typeorm migration:run`
6. start server: `yarn dev:server`
7. insert user: `curl -X POST -H "Content-Type: application/json" -d '{"email": "test@email", "password": "123456", "name": "Test", "phone": "1234"}' http://localhost:3333/users`
8. install autocannon: `yarn global add autocannon`
9. run perf test: `autocannon -m "GET" -c 105 -d 10 --renderStatusCodes http://localhost:3333/users`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 20.04.4 LTS         |
| Node.js version     | 16.15.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.34  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by TxGVNN** [comment]
I meet the same issue. And today, by config `ormconfig.json` as a patch below. I saw the pool is using correctly. Seems the `typeorm` doesn't use pool for connections by default.

```diff
   "password": "postgres",
   "database": "database",
+  "extra": {
+    "max": 10
+  },
   "entities": [
     "./src/modules/**/infra/typeorm/entities/*.ts"
   ],
```

**Comment by tienvv1234** [comment]
Great, thank you for your awesome answer, you saved my day

**Comment by renemroger** [comment]
I am using dataSource and I am facing the same issue. I tried adding poolSize but it didn't fix the issue.

**Comment by albjeremias** [comment]
I am having this issue, even after settings 
https://github.com/helpbuttons/helpbuttons/issues/105

+  "extra": {
+    "max": 10
+  },

I wonder if there is another workaround? 

in here: https://dev.to/noclat/fixing-too-many-connections-errors-with-database-clients-stacking-in-dev-mode-with-next-js-3kpm 
they mention that is only happening in dev mode? cause the api endpoints are re-created everytime you save a file from the api code? I can't confirm this yet. but i would really like to solve this issue before taking my code into production. any ideas?

**Comment by Pieros** [comment]
I am having this issue and it's turn out that postgres connection pool max limit at 100 connection. Try to checkout the config of postgres. maybe it is the same to me.

**Comment by namhong2001** [comment]
Because you have a cluster.

You have 12 cpu and you made a cluster with each cpu, so you have max 120 connections total by max 10 connections(default) for each.

> error: sorry, too many clients already

This error came from postgres itself and postgres limit max 100 connections(default) for user account.

**Comment by carloseduardodb** [comment]
Based on TxGVNN’s response, I believe they have solved the problem, but I have a doubt about this limitation. Has anyone tested how the application’s RAM behaves with this limitation? I’m afraid of facing problems with back pressure or something like that, but I don’t know very well how this pool works.

**Comment by bala-techguy** [comment]
Today I was stuck with this problem. I'm new to Postgres and typeORM. With the suggestions mentioned above I added the below lines to my Datasource file and resolved it temporarily. 

+  "extra": {
+    "max": 100
+  },

What I still don't understand is why every query creates a connection and the connection is not closed after the query is executed. If I run 100 API calls from the frontend, I will start getting timeouts and `sorry, too many clients already` error in the backend. 

Th typeorm documentation has also not mentioned anything about the above value and I still don't know how to close a connection after a query execution.

**Comment by carloseduardodb** [comment]
> Today I was stuck with this problem. I'm new to Postgres and typeORM. With the suggestions mentioned above I added the below lines to my Datasource file and resolved it temporarily.
> 
> ```
> +  "extra": {
> +    "max": 100
> +  },
> ```
> 
> What I still don't understand is why every query creates a connection and the connection is not closed after the query is executed. If I run 100 API calls from the frontend, I will start getting timeouts and `sorry, too many clients already` error in the backend.
> 
> Th typeorm documentation has also not mentioned anything about the above value and I still don't know how to close a connection after a query execution.

It will depend on how you are using TypeORM. Generally, it closes connections automatically, but there are some specific situations where it does not close them. One of these is when you use the connection directly to perform queries.
