### ISSUE TITLE
Entity metadata for UploadInfo#uploader was not found.

### ISSUE THREAD

**Issue by dstampher** [typeorm/typeorm#8998]
Account.ts

```
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  OneToMany,
  JoinColumn,
} from "typeorm";
import UploadInfo from "./UploadInfo";

@Entity()
export default class Account {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @Column()
  age: number;

  @OneToMany((type) => UploadInfo, (uploadInfo) => uploadInfo.user, {
    cascade: true,
  })
  uploads: UploadInfo[];
}
```

YoutubeAccount.ts

import { Entity } from "typeorm";
import Account from "./Account";

@Entity()
export default class YoutubeAccount extends Account {
  channelId: string;
}

UploadInfo.ts

```
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import YoutubeAccount from "./YoutubeAccount";

@Entity()
export default class UploadInfo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  url: string;

  @ManyToOne((type) => YoutubeAccount, (user) => user.uploads)
  user: YoutubeAccount;
}

```

index.ts

```
imports...

export async function main() {
  await AppDataSource.initialize();

  let account = new YoutubeAccount();
  account.username = "david123";
  account.password = "password123";
  account.recoveryEmail = "david@test.com";
  account.phoneNumber = "1234567890";
  account.profilePath = "profile/hi123";
  account.proxy = "123.123.123.123";

  let upload = new UploadInfo();
  upload.url = "youtube.com/test";

  account.uploads = [upload];
  await AppDataSource.manager.save(account);
}

main().catch((e) => console.log(e));
```

package.json

```
{
  "devDependencies": {
    "@types/node": "^16.11.10",
    "reflect-metadata": "^0.1.13",
    "ts-node": "^10.7.0",
    "typeorm": "^0.3.6",
    "typescript": "^4.8.0-dev.20220512"
  },
  "dependencies": {
    "axios": "^0.27.2",
    "reflect-metadata": "^0.1.13",
    "sqlite3": "^4.0.3"
  },
  "scripts": {}
}
```

tsconfig.json

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "sourceMap": true
  }
}

```
Command yarn ts-node src/index.ts

```
TypeORMError: Entity metadata for UploadInfo#uploader was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at C:\Users\david\source\repos\abot-node\src\metadata-builder\EntityMetadataBuilder.ts:1089:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (C:\Users\david\source\repos\abot-node\src\metadata-builder\EntityMetadataBuilder.ts:1079:34)
    at C:\Users\david\source\repos\abot-node\src\metadata-builder\EntityMetadataBuilder.ts:158:18
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (C:\Users\david\source\repos\abot-node\src\metadata-builder\EntityMetadataBuilder.ts:157:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (C:\Users\david\source\repos\abot-node\src\connection\ConnectionMetadataBuilder.ts:106:11)
    at async DataSource.buildMetadatas (C:\Users\david\source\repos\abot-node\src\data-source\DataSource.ts:667:13)       
    at async DataSource.initialize (C:\Users\david\source\repos\abot-node\src\data-source\DataSource.ts:241:13)
    at async main (C:\Users\david\source\repos\abot-node\src\index.ts:12:3)
```

**Comment by serg06** [comment]
I'm upgrading from 0.2.x to 0.3.x and having the exact same issue with `ManyToOne`. Any help would be appreciated.

**Comment by dstampher** [comment]
@serg06 Are you also deriving from a base class, like I was here?

**Comment by serg06** [comment]
@dstampher I'm not, and I just figured out the issue I was having. It's a circular dependency caused by TypeORM 0.3.0, and I've been scratching my head trying to work around it for the past hour. No progress yet but I can confirm things work when I remove the circular dependency.
