### ISSUE TITLE
`ArrayContains` SQLite error

### ISSUE THREAD

**Issue by marchellodev** [typeorm/typeorm#9001]
Example code:

```typescript
import { ArrayContains } from "typeorm"

const loadedPosts = await dataSource.getRepository(Post).findBy({
    categories: ArrayContains(["TypeScript"]),
})
```

`categories` is of type `simple-enum` with `array: true`

Error:
```
SQLITE_ERROR: unrecognized token: "@"
QueryFailedError: SQLITE_ERROR: unrecognized token: "@"
    at handler (/home/mark/Work/pathfinder/tailor-service/src/driver/sqlite/SqliteQueryRunner.ts:113:26)
    at replacement (/home/mark/Work/pathfinder/tailor-service/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/home/mark/Work/pathfinder/tailor-service/node_modules/sqlite3/lib/sqlite3.js:15:21)
```

I believe `ArrayContains` generates something like `SELECT * FROM "post" WHERE "categories" @> '{TypeScript}'`. However, `@>` is not supported in SQLite

**Comment by marchellodev** [comment]
As far as I understand, SQLite does not support arrays altogether, and having something like `type: simple-enum, array: true` in the model field produces a simple `varchar` column. Therefore, I think it would be reasonable to use `Like(%el%)` to mimic `ArrayContains`

**Comment by Enkratia** [comment]
You can write like this: 
```
    @Column("text", { array: true, default: {} })
    tags: string[];
```

Then you can use it as array.
