### ISSUE TITLE
Error: Invalid column name 'roleRoleId'. QueryFailedError: Error: Invalid column name 'roleRoleId'.

### ISSUE THREAD

**Issue by wmsundown** [typeorm/typeorm#9054]
## Issue Description
Hello Team,

I am getting the following error when trying to run the nestjs api using typeorm. This is a joined query using the queryBuilder to join two tables.

### Expected Behavior

The expected behavior is for the query to execute successful with the joined data.

### Actual Behavior

I am getting this error:

```
Error: Invalid column name 'roleRoleId'. QueryFailedError: Error: Invalid column name 'roleRoleId'.
    at /Users/programmer/poc_project/src/driver/sqlserver/SqlServerQueryRunner.ts:261:30
    at /Users/programmer/poc_project/node_modules/mssql/lib/base/request.js:440:25
    at Request.userCallback (/Users/programmer/poc_project/node_modules/mssql/lib/tedious/request.js:493:15)
    at Request.callback (/Users/programmer/poc_project/node_modules/tedious/lib/request.js:205:14)
    at Parser.onEndOfMessage (/Users/programmer/poc_project/node_modules/tedious/lib/connection.js:3078:22)
    at Object.onceWrapper (node:events:645:28)
    at Parser.emit (node:events:526:28)
    at Readable.<anonymous> (/Users/programmer/poc_project/node_modules/tedious/lib/token/token-stream-parser.js:34:12)
    at Readable.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12) ExceptionsHandler
```

### Steps to Reproduce

These are my entities (Using typeorm) with relationships in each of the entities.

```typescript
import { Column, Entity, OneToMany, PrimaryColumn } from 'typeorm';
import { Request } from './request.entity';

@Entity('role')
export class Role {
  @PrimaryColumn()
  role_id: number;

  @Column()
  description: string;

  @OneToMany(() => Request, (request) => request.role)
  requests: Request[];
}

import { Column, Entity, ManyToOne, PrimaryColumn, RelationId } from 'typeorm';
import { Role } from './role.entity';

@Entity('request')
export class Request {
  @PrimaryColumn()
  id: number;

  @Column()
  role_id: number;

  @Column()
  description: string;

  @ManyToOne(() => Role, (role) => role.requests)
  role: Role;
}

//The functions below in my nestjs service is the one throwing the error...

async getRoles(): Promise<Roles[]> {
    return await this.rolesRepository
      .createQueryBuilder('role')
      .leftJoinAndSelect('role.requests', 'requests')
      .where('role.role_id = :id', { id: 1 })
      .getRawMany();
  }
```

### My Environment
node v16.14.2

"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/jwt": "^8.0.0",
"@nestjs/passport": "^8.2.1",
"@nestjs/platform-express": "^8.0.0",
"@nestjs/schedule": "^1.0.2",
"@nestjs/typeorm": "^8.0.3",
"@types/passport-jwt": "^3.0.6",
"@types/passport-local": "^1.0.34",
"class-transformer": "^0.5.1",
"class-validator": "^0.13.2",
"mssql": "^7.3.4",
"reflect-metadata": "^0.1.13",
 "typescript": "^4.3.5"

"@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/cron": "^1.7.3",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.14.2  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.3.0  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
You are using incompatible versions of `@nestjs/typeorm` and `typeorm`.

You need at least [8.1.0 `@nestjs/typeorm`](https://github.com/nestjs/typeorm/releases/tag/8.1.0) to use `typeorm` `0.3`.
