### ISSUE TITLE
migration cli commands: migration:show, migration:run not working

### ISSUE THREAD

**Issue by StefanZivkovic** [typeorm/typeorm#9104]
## Issue Description
I don't know if it is more implementation issue or docs issue, or both.

### Expected Behavior

Migration cli commands are finished without errors.

### Actual Behavior

Executing this `npm run mg:create migrations/User` creates new migration file under migrations folder.

But `show` and `run` throw error when pointing to `typescript` version of dataSource (`npm run mg:show:ts`, `npm run mg:run:ts`).

```
Error: Unable to open file: "D:\typeorm\typeorm0.3-cli\ormconfig.ts". Cannot use import statement outside a module
at Function.loadDataSource (D:\typeorm\typeorm0.3-cli\node_modules\typeorm\commands\CommandUtils.js:22:19)  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typeorm0.3-cli@1.0.0 mg:show:ts: `typeorm migration:show --dataSource=./ormconfig.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typeorm0.3-cli@1.0.0 mg:show script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Or different error when pointing to `javascript` dataSource file (`npm run mg:show:js`, `npm run mg:run:js`).
```
> typeorm0.3-cli@1.0.0 mg:run D:\typeorm\typeorm0.3-cli
> typeorm migration:run --dataSource=./ormconfig.js

query: SELECT * FROM current_schema()
cli.js migration:run

Runs all pending migrations.

Options:
  -h, --help         Show help                                         [boolean]
  -d, --dataSource   Path to the file where your DataSource instance is defined.
                                                                      [required]
  -t, --transaction  Indicates if transaction should be used or not for
                     migration run. Enabled by default.     [default: "default"]
  -v, --version      Show version number                               [boolean]

CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established. 
    at DataSource.destroy (D:\typeorm\typeorm0.3-cli\node_modules\typeorm\data-source\DataSource.js:169:19)
    at Object.handler (D:\typeorm\typeorm0.3-cli\node_modules\typeorm\commands\MigrationRunCommand.js:67:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typeorm0.3-cli@1.0.0 mg:run: `typeorm migration:run --dataSource=./ormconfig.js`
npm ERR! Exit status 1
```

### Steps to Reproduce

Repo https://github.com/StefanZivkovic/typeorm0.3, run commands for `show`/`run`

```typescript
    "typeorm": "typeorm-ts-node-commonjs",
    "mg:create": "typeorm migration:create",
    "mg:show:js": "typeorm migration:show -d ormconfig.js",
    "mg:run:js": "typeorm migration:run --dataSource=./ormconfig.js",
    "mg:show:ts": "typeorm migration:show -d ormconfig.ts",
    "mg:run:ts": "typeorm migration:run --dataSource=./ormconfig.ts"
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      WIndows 10    |
| Node.js version     | v14.16.0  | 
| Typescript version  | 4.7.3  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes           |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by sleep-written** [comment]
Probably this error could be related with [this another one.](https://github.com/typeorm/typeorm/issues/9117)

**Comment by StefanZivkovic** [comment]
just to add few updates:
when using this command directly in terminal - `npx typeorm-ts-node-commonjs migration:show -d ormconfig.ts ` - then it is working.
![image](https://user-images.githubusercontent.com/44195291/174248390-b99a4e17-ce0a-4b6f-a104-fdac3762305b.png)

Note: i have npm version `6.14.11`

But, after build, `.js` files are generated for migrations as well, and i get this kind of error `Error: Duplicate migrations: User1655123435373`
![image](https://user-images.githubusercontent.com/44195291/174248775-efa7544f-eaad-41ff-82e9-1bc0b1e69cf0.png)

Run command is working and revert is working as well, using upper command, just switching `migration:run` and `migration:revert`.

**Comment by Soltanov-Anar** [comment]
Hi!
I have the same problem in version 0.3.7, hope they fix it soon.

**Comment by Soltanov-Anar** [comment]
https://stackoverflow.com/questions/72682474/typeorm-migrationgenerate-failure-not-enough-non-option-arguments-got-0-need

**Comment by Soltanov-Anar** [comment]
Example project:
https://github.com/sramocki/nestjs-typeorm-example-migrations

**Comment by nilskj** [comment]
Found a work-around by adding a separate build step for compiling the migration files in a separate command to `.js`, but this feels a bit silly since typeORM should be able to read .ts files hence its name. Yet this works for now after a full day of struggle . package.json:
```
    "typeorm": "env-cmd typeorm-ts-node-commonjs",
    "schema:sync": "pnpm typeorm -- schema:sync -d src/server/ormconfig.ts",
    "migration:build": "tsc migrations/*.ts",
    "migration:create": "pnpm typeorm -- migration:create migrations/M",
    "migration:gen": "pnpm typeorm -- migration:generate migrations/M -d src/server/ormconfig.ts && pnpm migration:build",
    "migration:run": "pnpm migration:build && pnpm typeorm -- migration:run -d src/server/ormconfig.ts",
    "migration:revert": "pnpm migration:build && pnpm typeorm -- migration:revert -d src/server/ormconfig.ts",
    "migration:show": "pnpm migration:build && pnpm typeorm -- migration:show -d src/server/ormconfig.ts"
 ```

**Comment by sedzd** [comment]
> ```json
> typeorm-ts-node-commonjs
> ```

not sure what's the issue but when I replaced the `typeorm-ts-node-commonjs` with `ts-node` in `typeorm` script it works:
```ts
 "typeorm": "ts-node -r ./src/module-alias.ts ./node_modules/typeorm/cli"
```

**Comment by felipedeboni** [comment]
> I got the same problem running this through a NextJS app `Cannot use import statement outside a module`. Either the migrations work if I include them as .ts files in config, but then app crashes at runtime, or else if I remove them the ORM functions and the app works but then I can't sync or run migrations.
> 
> Found a work-around by adding a separate build step for compiling the migration files in a separate command to `.js`, but this feels a bit silly since typeORM should be able to read .ts files??. Yet this works for now after a full day of struggles. package.json:
> 
> ```json
>     "typeorm": "env-cmd typeorm-ts-node-commonjs",
>     "schema:sync": "pnpm typeorm -- schema:sync -d src/server/ormconfig.ts",
>     "migration:build": "tsc migrations/*.ts",
>     "migration:create": "pnpm typeorm -- migration:create migrations/M",
>     "migration:gen": "pnpm typeorm -- migration:generate migrations/M -d src/server/ormconfig.ts && pnpm migration:build",
>     "migration:run": "pnpm migration:build && pnpm typeorm -- migration:run -d src/server/ormconfig.ts",
>     "migration:revert": "pnpm migration:build && pnpm typeorm -- migration:revert -d src/server/ormconfig.ts",
>     "migration:show": "pnpm migration:build && pnpm typeorm -- migration:show -d src/server/ormconfig.ts"
> ```
> 
> using this config file `ormconfig.ts`
> 
> ```ts
> import { DataSource, DataSourceOptions } from 'typeorm';
> import { env } from '../config/env';
> import { User } from './entity/user.entity';
> 
> const options: DataSourceOptions = {
>   type: env.DB_CONNECTION_TYPE,
>   host: env.DB_HOST,
>   port: env.DB_PORT,
>   username: env.DB_USERNAME,
>   password: env.DB_PASSWORD,
>   synchronize: env.DB_SYNCHRONIZE,
>   subscribers: [],
>   entities: [User],
>   migrations: [`./migrations/*.js`],
>   migrationsRun: true,
>   migrationsTableName: 'history'
> };
> 
> const AppDataSource = new DataSource(options);
> 
> export default AppDataSource;
> ```

Thanks, it was really helpful! If you still need to build it first, here's an updated version you can use that removes the build step:

package.json
```json
"typeorm": "CLI=typeorm typeorm-ts-node-commonjs",
"migration:show": "pnpm typeorm migration:show --dataSource src/config/data-source.ts",
"migration:generate": "pnpm typeorm --dataSource src/config/data-source.ts migration:generate",
"migration:create": "pnpm typeorm migration:create",
"migration:run": "pnpm typeorm migration:run --dataSource src/config/data-source.ts",
"migration:revert": "pnpm typeorm --dataSource src/config/data-source.ts migration:revert"
```

ormconfig.ts

```ts
const baseDir = process.env.CLI === 'typeorm' ? 'src' : 'dist';

export const dataSourceOptions: DataSourceOptions = {
  entities: [`${baseDir}/**/*.entity.ts`],
  migrations: [`${baseDir}/migrations/*.ts`]
};
```

**Comment by nmgix** [comment]
i had **Cannot use import statement outside a module**
in my case issue was referencing to wrong tsconfig, as ts-node uses tsconfig.json by default
because i use nx, my "main" config is **tsconfig.app.json**, so
package.json
`"typeorm": "ts-node --project tsconfig.app.json ./node_modules/typeorm/cli -d ./src/db/db.config.ts"`

**Comment by kgkg** [comment]
> i had `Cannot use import statement outside a module` in my case issue was referencing to wrong tsconfig, as ts-node uses tsconfig.json by default because i use nx, my "main" config is **tsconfig.app.json**, so
> 
> package.json (inside nx workspace/apps/app-name)
> 
> ```json
> "typeorm": "ts-node --project tsconfig.app.json ./node_modules/typeorm/cli -d ./src/db/db.config.ts"
> ```

Actually your reply is the only one that helped me solve this. When I used pnpm with workspaces it turns out it was using root tsconfig instead of the one from subrepo. Adding `--project tsconfig.json` apparently fixed this.
