### ISSUE TITLE
Query builder not working with subquery 

### ISSUE THREAD

**Issue by restuwahyu13** [typeorm/typeorm#9132]
Why query builder not working with subquery, because if i execute my query and then i get response back like this `error: error: syntax error at or near ":"` anyone can help me ?
`

## My Query

```ts
	const subQuery: string = await this.projectModel
		.createQueryBuilder('projects')
		.select([
			'projects.id',
			'projects.latest_status',
			'project_journeys',
			'project_journeys.id as journey_id',
			'project_journeys.status as journey_status',
			'project_journeys.is_read as journey_read'
		])
		.leftJoin('projects.projectJourneys', 'project_journeys')
		.where('project_journeys.is_read = :isRead AND project_journeys.is_read IS NOT NULL', {
			isRead: false
		})
		.getQuery()

	const results: Projects[] = await this.projectModel
		.createQueryBuilder('projects')
		.select(`(${subQuery})`)
		.addSelect('COUNT(project_journeys) as count_notification')
		.getMany()

	console.log(results)
```

## My Error

```sh
error: error: syntax error at or near ":"
    at Parser.parseErrorMessage (/home/x/Desktop/real-project/x-api/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/x/Desktop/real-project/x-api/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/x/Desktop/real-project/x-api/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/x/Desktop/real-project/x-api/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1208',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1180',
  routine: 'scanner_yyerror'
}
```

**Comment by AlexMesser** [comment]
closing as answered.
