### ISSUE TITLE
Missing dep app-root-path for alpha 44

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#915]
Upon creating a new TypeORM alpha 44 project, I hit the following error:

```
TypeORM connection error:  { Error: Cannot find module 'C:\Users\crutc\git\Rucksack\test\node_modules\app-root-path'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.PlatformTools.load (C:\Users\crutc\git\Rucksack\test\node_modules\typeorm\platform\PlatformTools.js:37:24)
    at ConnectionOptionsReader.get [as baseDirectory] (C:\Users\crutc\git\Rucksack\test\node_modules\typeorm\connection\ConnectionOptionsReader.js:194:50)
    at ConnectionOptionsReader.get [as baseFilePath] (C:\Users\crutc\git\Rucksack\test\node_modules\typeorm\connection\ConnectionOptionsReader.js:182:24)
    at C:\Users\crutc\git\Rucksack\test\node_modules\typeorm\connection\ConnectionOptionsReader.js:102:81
    at Array.find (native)
    at ConnectionOptionsReader.<anonymous> (C:\Users\crutc\git\Rucksack\test\node_modules\typeorm\connection\ConnectionOptionsReader.js:101:87) code: 'MODULE_NOT_FOUND' }
```

Manually `npm install`ing `app-root-path` fixed the problem

**Comment by pleerock** [comment]
Thank you for the report, fixed in `typeorm@0.1.0-alpha.45`
