### ISSUE TITLE
Class constructor BaseEntity cannot be invoked without 'new'

### ISSUE THREAD

**Issue by dustinlacewell** [typeorm/typeorm#9154]
## Issue Description

Entities extending `BaseEntity` cause TypeORM to throw when calling `DataSource.initialize`

### Expected Behavior

The database is initialized without issue.

### Actual Behavior

TypeORM throws:

```
TypeError: Class constructor BaseEntity cannot be invoked without 'new'
    at new YoutubeFeed (/Users/dustinlacewell/ext/yt-playground/src/services/FeedService/models/YoutubeFeed.ts:33:42)
    at EntityMetadata.create (/Users/dustinlacewell/ext/yt-playground/src/metadata/EntityMetadata.ts:563:23)
    at EntityMetadataValidator.validate (/Users/dustinlacewell/ext/yt-playground/src/metadata-builder/EntityMetadataValidator.ts:172:47)
    at /Users/dustinlacewell/ext/yt-playground/src/metadata-builder/EntityMetadataValidator.ts:43:18
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/dustinlacewell/ext/yt-playground/src/metadata-builder/EntityMetadataValidator.ts:42:25)
    at DataSource.buildMetadatas (/Users/dustinlacewell/ext/yt-playground/src/data-source/DataSource.ts:682:33)
    at DataSource.initialize (/Users/dustinlacewell/ext/yt-playground/src/data-source/DataSource.ts:241:13)
```

### Steps to Reproduce

1. Use `DataSource`
2. Add entities extending `BaseEntity`
3. Call `.initialize` on the `DataSource` instance

```typescript
    let db = new DataSource({
        type: "sqlite",
        synchronize: true,
        database: "test.sqlite",
        entities: [ YoutubeFeed, YoutubeChannel]
    })
    db = await db.initialize()
```

Entities:

````typescript
@Entity()
export class YoutubeFeed extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number

    @Column()
    guildId!: string

    @Column()
    channelId!: string

    @ManyToOne(to => YoutubeChannel, info => info.feeds)
    info!: YoutubeChannel
}

@Entity()
@Unique(["id"])
export class YoutubeChannel extends BaseEntity {

    @PrimaryColumn()
    id!: string

    @Column()
    name!: string

    @Column()
    thumbnail!: string

    @Column()
    description!: string

    @OneToMany(to => YoutubeFeed, feed => feed.info)    
    feeds!: YoutubeFeed[]
}
```

### My Environment

<!--
  Please add any other relevant dependencies to this table at the end.
  For example: Electron, React Native, or NestJS.
-->

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     OSX     |
| Node.js version     | v18.3.0  | <!-- run `node -v` to obtain this -->
| Typescript version  | 4.7.4  | <!-- run `npm list typescript` to obtain this -->
| TypeORM version     | 0.3.6  | <!-- run `npm list typeorm` to obtain this -->

### Relevant Database Driver(s)

<!-- Put "yes" instead of "no" to your issue's relevant databases -->

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |


### Are you willing to resolve this issue by submitting a Pull Request?

<!-- Put "✅" (:white_check_mark:) to one of these options, left "✖️" (:heavy_multiplication_x:) others: -->

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.


<!--
  Remember that first-time contributors are welcome! 🙌
  👋 Have a great day and thank you for the bug report!
-->

**Comment by jakubtomas108** [comment]
same issue here, also sqlite

**Comment by RomainThi** [comment]
Same issue, but on postgresql

**Comment by metanas** [comment]
If you are using typescript make sure to have `compilerOptions.target` is `es6` or newer 

on `tsconfig.json`
```json 
"compilerOptions": {
    "target": "es6",
     ...
```

**Comment by samsquareed** [comment]
changed it from es5 to es6 and it worked

**Comment by davidjmstewart** [comment]
@dustinlacewell 

Did you ever solve this? I am experiencing [a similar issue](https://github.com/typeorm/typeorm/issues/9692).

**Comment by stefanolaterrainghilterra** [comment]
Setting compilation target to ES6 does nothing for me, any help? For those who managed to make it work, what's your DataSource configuration? Are you using .ts files or the compiled .js files?

**Comment by 92sajid110** [comment]
> If you are using typescript make sure to have `compilerOptions.target` is `es6` or newer
> 
> on `tsconfig.json`
> 
> ```json
> "compilerOptions": {
>     "target": "es6",
>      ...
> ```

thanks saved me
can you tell me config file for build also that select entity from build file on live server

**Comment by jimOnAir** [comment]
Hello.
I have the same error. But I have `"target": "ES2022",` in compiler options. Are there any other solutions for this issue?

**Comment by ankitbtanna** [comment]
the boilerplate code that is generated for commonjs must be updated. BaseEntity is required.

**Comment by peralva** [comment]
> If you are using typescript make sure to have `compilerOptions.target` is `es6` or newer
> 
> on `tsconfig.json`
> 
> ```json
> "compilerOptions": {
>     "target": "es6",
>      ...
> ```

This change worked for me. Thanks.

**Comment by alumni** [comment]
One of the issues is here:

https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L679-L681

Probably we need to look in the repo an check if there are others similar.

**Comment by rafaelrpinto** [comment]
@alumni Thank, man. 🥇 💯 
Here we created the entity class but we did not add to the datasource initialization.

**Comment by ashokdey** [comment]
This also happens when you do not register the entity class with the `TypeOrmModule`, something like this we do in Nest.js module:

```
    TypeOrmModule.forFeature([
      Users,
      UserProfiles,
    ])
```
