### ISSUE TITLE
QueryBuilder insert error - this.subQuery is not a function

### ISSUE THREAD

**Issue by JakeSidSmith** [typeorm/typeorm#9165]
## Issue Description

Running a simple insert with query builder (as [documented here](https://typeorm.io/insert-query-builder)) throws an error.

Seems that [this line](https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L690) assumes that `this` is a `SelectQueryBuilder`, but this is being run for inserts?

### Expected Behavior

Should not error, and should successfully insert the values.

### Actual Behavior

Outputs:

```shell
/Users/username/code/projectname/packages/server/node_modules/src/query-builder/QueryBuilder.ts:689
            )((this as any as SelectQueryBuilder<any>).subQuery())
                                                       ^
TypeError: this.subQuery is not a function
    at InsertQueryBuilder.createFromAlias (/Users/username/code/projectname/packages/server/node_modules/src/query-builder/QueryBuilder.ts:689:56)
    at InsertQueryBuilder.into (/Users/username/code/projectname/packages/server/node_modules/src/query-builder/InsertQueryBuilder.ts:237:32)
    at signupCompany (/Users/username/code/projectname/packages/server/src/app/auth/signup/company.ts:22:8)
    at Object.<anonymous> (/Users/username/code/projectname/packages/server/src/manage/create-database-data.ts:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/username/code/projectname/packages/server/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/username/code/projectname/packages/server/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

Please note that the trace paths are also wrong. This may have something to do with my repo being a monorepo, but I wouldn't have thought so. 🤷  More likely running my query with `ts-node` is causing issues.

The actual line is here: https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L690

### Steps to Reproduce

1. Create a basic entity

```ts
import {BaseEntity, Column, Entity, PrimaryGeneratedColumn} from 'typeorm';

@Entity()
export class Example extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  @Column({type: 'text', nullable: false})
  public name!: string;
}
```

2. Create a script to insert some data

```ts
AppDataSource.createQueryBuilder()
  .insert()
  .into(Example)
   .values({
    name: 'whatever',
  })
.execute();
```

3. Run the script

```
ts-node ./path-to-script.ts
```

Note: I receive the same error when inserting an empty values object, or putting the values into an array.

I'm not sure this is relevant as my config is so simple, but here's my data source (that works fine for other queries, migrations, etc):

```ts
const AppDataSource = new DataSource({
  type: 'postgres',
  url: process.env.DATABASE_URL,
  entities,
  migrations,
});

export default AppDataSource;
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      MacOS Monterey 12.4 (M1)    |
| Node.js version     | 16.14.2  | 
| TSNode version     | 10.8.1  | **
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by brian-philip-dwyer** [comment]
Any update on this?

**Comment by evshiron** [comment]
I met this issue when I forgot to add the entity class to the datasource arguments.

**Comment by robinelvin** [comment]
Same issue here

```
/Users/rob/Projects/Elixir/core-develop/node_modules/src/query-builder/QueryBuilder.ts:690
            )((this as any as SelectQueryBuilder<any>).subQuery())
                                                       ^
TypeError: this.subQuery is not a function
    at InsertQueryBuilder.createFromAlias (/Users/rob/Projects/Elixir/core-develop/node_modules/src/query-builder/QueryBuilder.ts:690:56)
    at InsertQueryBuilder.into (/Users/rob/Projects/Elixir/core-develop/node_modules/src/query-builder/InsertQueryBuilder.ts:239:32)
    at Interface.<anonymous> (file:///Users/rob/Projects/Elixir/core-develop/packages/dal/src/contexts/mysql/Import.ts:88:34)
    at Interface.emit (node:events:513:28)
    at Interface.emit (node:domain:489:12)
    at Interface._onLine (node:readline:491:10)
    at Interface._normalWrite (node:readline:665:12)
    at ReadStream.ondata (node:readline:272:10)
    at ReadStream.emit (node:events:513:28)
    at ReadStream.emit (node:domain:489:12)
    ```
