### ISSUE TITLE
Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by edrorr** [typeorm/typeorm#9181]
## Issue Description

I got this error after installing the latest version.

calling **initialize()** Promise returns this in catch:
```
TypeError: Cannot read properties of null (reading '0')
    at SqlServerQueryRunner.getCurrentSchema (C:\Projects\VoltaServer\node_modules\typeorm\src\driver\sqlserver\SqlServerQueryRunner.ts:427:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SqlServerDriver.connect (C:\Projects\VoltaServer\node_modules\typeorm\src\driver\sqlserver\SqlServerDriver.ts:299:37)
    at async DataSource.initialize (C:\Projects\VoltaServer\node_modules\src\data-source\DataSource.ts:232:9)
```

Apparently it's running this query when I use 'advanced-console':
```
query: SELECT SCHEMA_NAME() AS "schema_name"
```

Sometimes I get this when trying to switch to other versions:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: nomination-server@0.0.0
npm WARN Found: mssql@7.3.5
npm WARN node_modules/mssql
npm WARN   peerOptional mssql@"^7.3.0" from typeorm@0.3.7
npm WARN   node_modules/typeorm
npm WARN     typeorm@"^0.3.7" from the root project
npm WARN   1 more (the root project)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional mssql@"^7.3.0" from typeorm@0.3.7
npm WARN node_modules/typeorm
npm WARN   typeorm@"^0.3.7" from the root project
```

### My Environment

| Operating System:  Windows 10
| Node.js version: 16.15.1
| Typescript version: 4.7.4
| TypeORM version: 0.3.7
| Mssql version: 8.1.2

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | yes            |

**Comment by cs-maciej** [comment]
@edrorr Were you able to fix this issue? I have a similar problem after upgrading to `typeorm 0.3.7` (same libs versions). It was working with `typeorm 0.2` and `mssql 6`.

**Comment by edrorr** [comment]
@cs-maciej Unfortunately not. I did try a lot of things and changing versions but none of them fixed the issue so far. Mine is working with `typeorm 0.2.29` and `mssql 4.3.9`

**Comment by coder-pm** [comment]
It's connected with that change: https://github.com/tediousjs/node-mssql/pull/1338.

Setting `stream: false` in your ORM config will fix the issue.
