### ISSUE TITLE
Can't use CLI commands with an Expo data source

### ISSUE THREAD

**Issue by duraz0rz** [typeorm/typeorm#9294]
## Issue Description
In short, I'm trying to add migrations to our Expo app so we can remove `synchronize: true` from our data source before we go live, but I'm having a hard time generating them via the CLI. It is a React Native-based app in Typescript, and I followed the instructions on how to set up using `ts-node` on the CLI page, but it's not working when the data source type is `expo`.

To be sure, I set up a sample app via `typeorm init` and made changes to get it close to how our app is configured, then change the data source type to `expo.

### Expected Behavior

Running `typeorm migration:generate -d src/data-source.ts src/migration/meow`when the data source type is `expo` should create a migration.

### Actual Behavior

```
[I] me@me ~/C/typeorm-sample (with-expo-sqlite)> yarn typeorm migration:generate -d src/data-source.ts src/migration/with-expo-sqlite
$ typeorm-ts-node-esm migration:generate -d src/data-source.ts src/migration/with-expo-sqlite
Error during migration generation:
Error: Unable to open file: "/Users/marc.vertido/Code/typeorm-sample/src/data-source.ts". Unexpected token 'export'
    at Function.loadDataSource (/Users/marc.vertido/Code/typeorm-sample/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (/Users/marc.vertido/Code/typeorm-sample/src/commands/MigrationGenerateCommand.ts:73:26)
```

### Steps to Reproduce

Sample code - https://github.com/duraz0rz/typeorm-expo-sqlite-weirdness

1. Check out repo above. The `main` branch contains what's generated by `typeorm init`. This works with `yarn typeorm migration:generate -d src/data-source.ts src/migration/meow`
2. Check out the `esm` branch. I converted the repo to use ESModules instead of CommonJS modules since that's what our project is based on. This also works with `yarn typeorm migration:generate -d src/data-source.ts src/migration/meow`
3. Check out the `with-expo-sqlite` branch. This branch changes the type on the data source from `sqlite` to `expo` and adds the `expo-sqlite` driver. This does _not_ work with `yarn typeorm migration:generate -d src/data-source.ts src/migration/meow`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16.15.0  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | yes            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by WalissonPires** [comment]
I'm facing the same problem. :c

**Comment by duraz0rz** [comment]
> I'm facing the same problem. :c

I worked around it by using a different `sqlite` data source: https://github.com/duraz0rz/typeorm-expo-sqlite-weirdness/tree/workaround . It should generate the same migration statements, but you need to maintain a SQLite database in your repo so `migration:generate` can generate the correct migrations for you.

**Comment by WalissonPires** [comment]
> > I'm facing the same problem. :c
> 
> I worked around it by using a different `sqlite` data source: https://github.com/duraz0rz/typeorm-expo-sqlite-weirdness/tree/workaround . It should generate the same migration statements, but you need to maintain a SQLite database in your repo so `migration:generate` can generate the correct migrations for you.

It works fine that way. Thank you very much. :)

**Comment by brodie-g** [comment]
I had been working on this same issue for hours, assuming it was an issue with my Typescript/Node environment. Good to know others are having this issue with an expo datasource and that there's a workaround. Would be interested in seeing a fix for this or what the root cause is - it's a bit of an annoyance now having to manage one datasource for the app, and one for migrations. Thanks for putting together the reproduction/workaround repo, very helpful.
