### ISSUE TITLE
Many-to-Many relation with both owners bumps into "(plugin dts) Error: Syntax not yet supported" error.

### ISSUE THREAD

**Issue by khteh** [typeorm/typeorm#9296]
## Issue Description
I declare 2 entities: `Teacher` and `Student`. I am trying to create a one many-to-many relationship table. `Teacher` can have many students registered to it and `Student` can subscribe to more than one teacher.

`EntityBase` class:
```
import { PrimaryGeneratedColumn, Column } from "typeorm"
/*
* Use Data Mapper pattern: https://typeorm.io/active-record-data-mapper
*/
export abstract class EntityBase {
    @PrimaryGeneratedColumn()
    public id: number
    @Column()
    public created: Date
    @Column()
    public modified: Date
}
```
And I would like to create a many-to-many relationships table between `Student` and `Teacher` table. However, when I define the following classes in 2 `.ts` files:
```
import { Entity, Column, ManyToMany, JoinTable } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Teacher } from "./Teacher"
@Entity()
export class Student extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @Column()
    public isSuspended: boolean

    @ManyToMany(() => Teacher, (teacher) => teacher.students)
    @JoinTable()
    public teachers: Teacher[]

    constructor(first: string, last: string, email: string, isSuspended?: boolean) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.isSuspended = isSuspended ?? false;
        this.teachers = [];
    }
}
```
```
import { Entity, Column, JoinTable, ManyToMany } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Student } from "./Student"
@Entity()
export class Teacher extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @ManyToMany(() => Student, (student) => student.teachers)
    @JoinTable()
    public students: Student[]

    constructor(first: string, last: string, email: string) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.students = [];
    }
}
```
It result in the following error:
```
build/index.d.ts → build/index.d.ts...
[!] (plugin dts) Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
Domain/Entities/Teacher.ts
Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
    at Transformer.convertStatement (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1248:19)
    at new Transformer (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1177:18)
    at convert (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1168:25)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1484:31)
    at transformFile (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1588:50)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1601:24)
    at /usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:22840:40

npm ERR! Lifecycle script `rollup` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
```

### Expected Behavior
No error.

### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 22.04  |
| Node.js version     | v18.7.0 | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.7  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by khteh** [comment]
[rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts) error! Switching over to https://github.com/wessberg/rollup-plugin-ts resolves the problem.
