### ISSUE TITLE
Using embedded entities produces Oracle error ORA-00904

### ISSUE THREAD

**Issue by franzcatch** [typeorm/typeorm#9304]
## Issue Description

I have a very large flat Oracle table that I would like to have typeorm automatically format the output into nested properties.  All works fine until I try to implement embedded entities by following this guide:
https://typeorm.io/embedded-entities

Here is a small example of the entity.

![Screen Shot 2022-08-19 at 5 04 55 PM](https://user-images.githubusercontent.com/4729235/185713427-e68cbfa5-9f62-4622-a0fe-86f0b1faa675.png)

If I leave the `EndCustomer` properties/columns in the main object, CustomerOrderLine, everything works fine.  But when I try put the columns into the EndCustomer class and use the class as an embedded entity, I get the following error:
![Screen Shot 2022-08-19 at 5 05 39 PM](https://user-images.githubusercontent.com/4729235/185713438-0e9974a8-3c83-4e9d-8727-85a4c68be802.png)

### Expected Behavior

I expect the `select` statement to select `"ol"."customer_party_id"`.

### Actual Behavior

The `select` used is `"ol"."endCustomerEnd_customer_party_id"` - which Oracle does not recognize.

```
l"."endCustomerEnd_customer_name" AS "da34a0df07afc7898f794268f0bcf", "ol"."endCustomerEnd_customer_order_number" AS "2130d299b0f67b6ed32adf85fad03", "ol"."endCustomerEnd_customer_party_id" AS "b9daeb255485904b669669ad63096" FROM "ORDER_MGMT"."CUSTOMER_ORDER_LINE" "ol" WHERE HEADER_ID IN (27593198)
error: [Error: ORA-00904: "ol"."endCustomerEnd_customer_party_id": invalid identifier] {
  errorNum: 904,
  offset: 8352
}
error: INDEX_REBUILD: Error getting serial data for header: 27593198 QueryFailedError: ORA-00904: "ol"."endCustomerEnd_customer_party_id": invalid identifier
    at OracleQueryRunner.query (/Users/franzena/Documents/Projects/order-search-manager/node_modules/typeorm/driver/oracle/OracleQueryRunner.js:190:19)
    at async SelectQueryBuilder.loadRawResults (/Users/franzena/Documents/Projects/order-search-manager/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:25)
    at async SelectQueryBuilder.getRawMany (/Users/franzena/Documents/Projects/order-search-manager/node_modules/typeorm/query-builder/SelectQueryBuilder.js:600:29)
[5:04:59 PM] File change detected. Starting incremental compilation...

```

### Steps to Reproduce

```typescript
        .createQueryBuilder("ol")
        .select()
        .where(`HEADER_ID IN (${headerIds})`)
        .getMany();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     macOS Monterey     |
| Node.js version     | "^14.x"  | 
| Typescript version  | "^4.2.2"  | 
| TypeORM version     | "^0.3.7"  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | yes            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

"oracledb": "^5.3.0",

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by franzcatch** [comment]
Ok I fixed this by stipulating a `prefix` as shown in the following screenshot.
![Screen Shot 2022-08-23 at 10 22 23 AM](https://user-images.githubusercontent.com/4729235/186197813-d9cb8db8-b3ba-4cbb-afac-7398b41a5045.png)

Where it used to generate the embedded entity column as `"ol"."endCustomerEnd_customer_party_id"`, it now generates it as `"ol".end_customer_party_id"`.

Hope this helps someone in the future.

**Comment by hinogi** [comment]
Until this, id didn't even knew embedded entities are possible with oracledb, now that will come in handy for such things like apollo graphql federation.
