### ISSUE TITLE
How to use custom repository with class in typeorm 3

### ISSUE THREAD

**Issue by EndyKaufman** [typeorm/typeorm#9310]
### Expected Behavior

Everthing ok :)

### Actual Behavior

I have errors :(
![image](https://user-images.githubusercontent.com/4127109/185899806-b34513b3-b09a-4db5-bd6f-c45a4c5f04c8.png)

```sh
TypeError: Class constructor Repository cannot be invoked without 'new'
    at new CustomRep (/home/endy/Projects/current/typeorm3-test/MyProject/src/index.ts:61:42)
    at Object.<anonymous> (/home/endy/Projects/current/typeorm3-test/MyProject/src/index.ts:16:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/endy/Projects/current/typeorm3-test/MyProject/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/endy/Projects/current/typeorm3-test/MyProject/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/endy/Projects/current/typeorm3-test/MyProject/node_modules/ts-node/src/bin.ts:567:12)
```

### Steps to Reproduce

1. git clone https://github.com/EndyKaufman/typeorm3-test
2. npm i
3. npm run start

```typescript
import { Repository } from "typeorm";
import { AppDataSource } from "./data-source";
import { User } from "./entity/User";

export class CustomRep extends Repository<User> {
  findByName(firstName: string, lastName: string) {
    // this.createQueryBuilder34333;
    return this.createQueryBuilder("user")
      .where("user.firstName = :firstName", { firstName })
      .andWhere("user.lastName = :lastName", { lastName })
      .getMany();
  }
}

export const userRepository = AppDataSource.getRepository(User).extend(
  new CustomRep(User, AppDataSource.manager, AppDataSource.manager.queryRunner)
);

AppDataSource.initialize()
  .then(async () => {
    console.log("Inserting a new user into the database...");
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;
    await AppDataSource.manager.save(user);
    console.log("Saved a new user with id: " + user.id);

    console.log("Loading users from the database...");
    const users = await AppDataSource.manager.find(User);
    console.log("Loaded users: ", users);

    console.log(
      "Here you can setup and run express / fastify / any other framework."
    );
    console.log(await userRepository.findByName("Timber", "Saw"));
  })
  .catch((error) => console.log(error));

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 20.04.3 LTS        |
| Node.js version     | v16.13.1  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.7  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by xDivisionByZerox** [comment]
I'm just curious. What do you need the `CustomRep` class for? You could directly add your `findByName` function as a parameter in the `extend` function [as described in the docs](https://typeorm.io/custom-repository#how-to-create-custom-repository). 

```ts
export const userRepository = AppDataSource.getRepository(User).extend(
  findByName(firstName: string, lastName: string) {
    return this.createQueryBuilder("user")
      .where("user.firstName = :firstName", { firstName })
      .andWhere("user.lastName = :lastName", { lastName })
      .getMany();
  },
);
```

And if you don't want to do that, why do you need just initializing `CustomRep` should be enough or not?
```
export const userRepository = new CustomRep(User, AppDataSource.manager, AppDataSource.manager.queryRunner);
```

**Comment by EndyKaufman** [comment]
I want create custom repository from class, not from js object

**Comment by ruscon** [comment]
@EndyKaufman for nestjs

```typescript
export class FooRepository extends Repository<Foo> {
 // ...
}

export const fooRepositoryProvider = {
    provide: FooRepository,
    inject: [getRepositoryToken(Foo)],
    useFactory: (repository: MongoRepository<Foo>) => {
        return new FooRepository(repository.target, repository.manager, repository.queryRunner);
    },
}
```

**Comment by alex-kovalchuk** [comment]
@ruscon, thanks. My example for typedi:

```typescript
@Service()
export class FooRepositoryFactory {
  constructor(private databaseProvider: DbProvider) {
  }

  create(): FooRepository {
    const repo = this.databaseProvider.getManager().getRepository(Foo);
    return new FooRepository(repo.target, repo.manager, repo.queryRunner);
  }
}

// ...

@Service({ factory: [UserRepositoryFactory, 'create'] })
export class FooRepository extends Repository<Foo> {
  // ...
}
```

**Comment by sergeyjsg** [comment]
This question is still actual. I have methods that I want to add to all repositories. So previously I had a generic base class. How can I do it now?
