### ISSUE TITLE
ConnectionNotFoundError occurs when Quick Start with express

### ISSUE THREAD

**Issue by gibeoom** [typeorm/typeorm#9337]
## Issue Description
I did a quick start with express through the command below.
(I am a typeorm newbie. I didn't modify anything in the existing code, I followed the guide documentation and it didn't work.)
```
npx typeorm init --name MyProject --database mysql --express
cd MyProject 
npm start
```

After the express server is started, if I connect to localhost:3000/users, a ConnectionNotFoundError error occurs.

I changed the part of  getRepository in the src/controller/UserController.ts file and it worked correctly.
```
import { AppDataSource } from "../data-source"
...
// private userRepository = getRepository(User) 
private userRepository = AppDataSource.getRepository(User)
```

### Expected Behavior
The data should be output as shown below.
```
[{"id":1,"firstName":"Timber","lastName":"Saw","age":27},{"id":2,"firstName":"Phantom","lastName":"Assassin","age":24},{"id":3,"firstName":"Timber","lastName":"Saw","age":27},{"id":4,"firstName":"Phantom","lastName":"Assassin","age":24},{"id":5,"firstName":"Timber","lastName":"Saw","age":25},{"id":6,"firstName":"Timber","lastName":"Saw","age":25},{"id":7,"firstName":"Timber","lastName":"Saw","age":27},{"id":8,"firstName":"Phantom","lastName":"Assassin","age":24},{"id":9,"firstName":"Timber","lastName":"Saw","age":27},{"id":10,"firstName":"Phantom","lastName":"Assassin","age":24},{"id":11,"firstName":"Timber","lastName":"Saw","age":27},{"id":12,"firstName":"Phantom","lastName":"Assassin","age":24},{"id":13,"firstName":"Timber","lastName":"Saw","age":27},{"id":14,"firstName":"Phantom","lastName":"Assassin","age":24}]
```

### Actual Behavior
**ConnectionNotFoundError** error occurred
```
ConnectionNotFoundError: Connection "default" was not found.
```

### Steps to Reproduce

```
npx typeorm init --name MyProject --database mysql --express
cd MyProject 
npm start
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 11 / WSL2       |
| Node.js version     | 16.15.1  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.9  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by rasyhad** [comment]
Hi,

Tested your steps to reproduce the error and the quick start works just fine.

Tested with both `mysql` and `mssql` (just wanted to be sure) and both work just fine.

**Comment by ComputerCarl** [comment]
If I run `npx typeorm init --name MyProject --database postgres --express`, then modify `data-source.ts` with the proper credentials, and navigate to `http://localhost:3000/users`,  I get the error:
```
ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionManager.get (Q:\Libraries\Desktop\MyProject\src\connection\ConnectionManager.ts:43:32)
    at getRepository (Q:\Libraries\Desktop\MyProject\src\globals.ts:183:10)
    at new UserController (Q:\Libraries\Desktop\MyProject\src\controller\UserController.ts:7:43)
    at Q:\Libraries\Desktop\MyProject\src\index.ts:17:29
    at Layer.handle [as handle_request] (Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\layer.js:95:5)
    at next (Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\layer.js:95:5)
    at Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (Q:\Libraries\Desktop\MyProject\node_modules\express\lib\router\index.js:346:12)
```

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CM
```

**Comment by rasyhad** [comment]
Hi @ComputerCarl ,

Can you share a screenshot of your project directory when you run the command `npx typeorm init --name MyProject --database postgres --express` ? Maybe also share this `data-source.ts` as well.

Because these are the steps that I did and the app runs perfectly.
1. Run `npx typeorm init --name MyProject --database postgres --express`.
2. Then, `cd MyProject`  =>  `npm i`
3. Go to `ormconfig.json` and change the database credentials accordingly.
4. `npm start` => `http://localhost:3200/users` => I can see the json data without any issue.

**Comment by rasyhad** [comment]
Hi @gibeoom,

Looks like a bug to me when creating a fresh app using the `typeorm init` command. They switched over from using `ormconfig.json` to using `data-source.ts` a while back.

The latest way of using `repository` is through the `DataSource` just like you did.

**Comment by rasyhad** [comment]
Hi @ComputerCarl ,

Re-tried the steps to reproduce the issue.

1. Run `npx typeorm init --name MyProject --database postgres --express` or simply run `typeorm init --name MyProject --database postgres --express`. Make sure you have install the latest `typeorm` globally.
2. Then, `cd MyProject` => you may have to run `npm i` as well.
3. Change your database credentials in `data-source.ts` accordingly.
4. Run `npm start` to start `Express` server => `http://localhost:3000/users` => Error

You will get the `ConnectionNotFoundError: Connection "default" was not found.` This is mainly because the `getRepository(entity)` method is already deprecated. 

To fix, import the `AppDataSource` and modified the controller like so.

```
...
import { AppDataSource } from "../data-source"

export class UserController {

    private userRepository = AppDataSource.getRepository(User)

   ...

}

```
