### ISSUE TITLE
Connection Error after version update

### ISSUE THREAD

**Issue by ajvorobiev** [typeorm/typeorm#938]
Dear devs,

I have a strange issue after updating to **0.1.0-alpha.47**.

The `ormconfig.json` that was working with 0.0.9 :

```
[
  {
    "name": "default",
    "driver": {
      "type": "postgres",
      "host": "localhost",
      "port": 5432,
      "username": "bla",
      "password": "**********",
      "database": "bla"
    },
    "autoSchemaSync": true,
    "entities": [
      "src/entities/*.js"
    ],
    "subscribers": [
      "src/subscribers/*.js,"
    ],
    "migrations": [
      "src/migrations/*.js"
    ],
    "cli": {
      "entitiesDir": "src/entities",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
    }
  }
]
```
And the startup:
```
createConnection().then(async connection => {

    const instance = express();
    instance.use(bodyParser.json());

    const app = await NestFactory.create(ApplicationModule, instance);

    let serverInfoService = new ServerInfoService();
    await serverInfoService.updateServerInfo();

    await app.listen(3001, () => console.log('Application is listening on port 3001.'));  
}).catch(error => console.log("TypeORM connection error: # ", error));
```

And now with every start up I am getting the following issue:
```
TypeORM connection error: #  { Error
    at new MissingDriverError (C:\alex\qask-api\src\error\MissingDriverError.ts:10:22)
    at DriverFactory.create (C:\alex\qask-api\src\driver\DriverFactory.ts:43:23)
    at new Connection (C:\alex\qask-api\src\connection\Connection.ts:105:43)
    at ConnectionManager.create (C:\alex\qask-api\src\connection\ConnectionManager.ts:64:28)
    at Object.<anonymous> (C:\alex\qask-api\src\index.ts:184:35)
    at step (C:\alex\qask-api\node_modules\typeorm\index.js:32:23)
    at Object.next (C:\alex\qask-api\node_modules\typeorm\index.js:13:53)
    at fulfilled (C:\alex\qask-api\node_modules\typeorm\index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
  name: 'MissingDriverError',
  message: 'Wrong driver undefined given. Supported drivers are: "cordova", "mysql", "postgres", "mssql", "oracle", "mariadb", "sqlite".' }
```
Has something changes in 0.1.0 with the structure of the ormconfig or the way that the connection is established?

**Comment by pleerock** [comment]
yeah differences between 0.0.9 and 0.1.0-alpha.47 are terrific. There is no more "driver" section in connection options anymore, change your configuration to:

```ts
[
  {
    "name": "default",
      "type": "postgres",
      "host": "localhost",
      "port": 5432,
      "username": "bla",
      "password": "**********",
      "database": "bla",
    "autoSchemaSync": true,
    "entities": [
      "src/entities/*.js"
    ],
    "subscribers": [
      "src/subscribers/*.js,"
    ],
    "migrations": [
      "src/migrations/*.js"
    ],
    "cli": {
      "entitiesDir": "src/entities",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
    }
  }
]
```

**Comment by ajvorobiev** [comment]
Many thanks @pleerock ! This indeed was the issue.
