### ISSUE TITLE
Transpiling for use on AWS Lambda/Node 4.3.2

### ISSUE THREAD

**Issue by djabry** [typeorm/typeorm#94]
Thanks so much for this beautifully written library.

I'm trying to get it to work in a project running on AWS Lambda (Node 4.3.2) and my babel configuration results in the error below. Any suggestions on which polyfills, babel presets and/or plugins I could use?

`/Users/djabry/WebstormProjects/r3z-campaigns-service/node_modules/reflect-metadata/Reflect.ts:1061
            decorator(target, propertyKey);
            ^
TypeError: index_1.getMetadataArgsStorage(...).columns.add is not a function
    at /Users/djabry/WebstormProjects/r3z-campaigns-service/node_modules/typeorm/decorator/columns/PrimaryGeneratedColumn.js:33:50
    at DecoratePropertyWithoutDescriptor (/Users/djabry/WebstormProjects/r3z-campaigns-service/node_modules/reflect-metadata/Reflect.ts:1061:13)
    at Object.decorate (/Users/djabry/WebstormProjects/r3z-campaigns-service/node_modules/reflect-metadata/Reflect.ts:246:20)
    at __decorate (/Users/djabry/WebstormProjects/r3z-campaigns-service/src/entities/entity.table.js:4:92)
    at /Users/djabry/WebstormProjects/r3z-campaigns-service/src/entities/entity.table.ts:13:5
    at Object.<anonymous> (/Users/djabry/WebstormProjects/r3z-campaigns-service/src/entities/entity.table.ts:11:1)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/djabry/WebstormProjects/r3z-campaigns-service/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:490:32)
`

**Comment by djabry** [comment]
I've managed to get it working by using this preset in my babel config:

`{
  "presets": [
    "es2015-node4"
  ]
}`
