### ISSUE TITLE
composite key + eager loading 'not-null constraint' issue on update

### ISSUE THREAD

**Issue by flamewow** [typeorm/typeorm#9413]
## Issue Description

When an entity has composite PK (which are as well foreign keys).
The relations are like: 
A <-- M
B <-- M
and M has eager load of B
A has cascade for B relation

When A is loaded and some modifications are done to A and then it's saved - you will get an error that one of the PKs of the mediator entity violates not-null constraints. However, that column is set (checked with debugger).

### Expected Behavior

I expect no error in that case.

### Actual Behavior

An error is thrown.

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. clone https://github.com/flamewow/typeorm-demo
2. npm install
3. docker-compose up -d
4. npm run start demo
5. observe the error

```
QueryFailedError: null value in column "itemId" of relation "label_entity" violates not-null constraint
    at PostgresQueryRunner.query (/Users/ilya/Dev/typeorm-demo/src/driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UpdateQueryBuilder.execute (/Users/ilya/Dev/typeorm-demo/src/query-builder/UpdateQueryBuilder.ts:145:33)
    at updateSubject (/Users/ilya/Dev/typeorm-demo/src/persistence/SubjectExecutor.ts:611:38)
    at async Promise.all (index 2)
    at SubjectExecutor.executeUpdateOperations (/Users/ilya/Dev/typeorm-demo/src/persistence/SubjectExecutor.ts:662:9)
    at SubjectExecutor.execute (/Users/ilya/Dev/typeorm-demo/src/persistence/SubjectExecutor.ts:148:9)
    at EntityPersistExecutor.execute (/Users/ilya/Dev/typeorm-demo/src/persistence/EntityPersistExecutor.ts:194:21)
    at ItemsService.onModuleInit (/Users/ilya/Dev/typeorm-demo/dist/apps/demo/main.js:238:9)
    at async Promise.all (index 0)
```

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | yes            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by GP4cK** [comment]
I think you may need to use `orphanedRowAction` in your `@ManyToOne` relation. See this [comment](https://github.com/typeorm/typeorm/issues/9492#issuecomment-1484637549)

**Comment by khaelys** [comment]
@GP4cK if you remove the composite key and add a new key which is the concatenation of the composite key and add that orphanedRowAction it works even for updates. But there's a problem with TypeORM not recognizing composite keys which leads to this unexpected behaviour

**Comment by khaelys** [comment]
The problem verify every time you have a many to many relationship with custom attributes, because you usually create a new entity with foreign keys as the composite primary key, but it won't work.
