### ISSUE TITLE
TypeOrm Enum error

### ISSUE THREAD

**Issue by usamasaif** [typeorm/typeorm#9440]
//error
error: error: type "public.roles_access_for_enum" does not exist
  length: 116,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: '223',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '274',
  routine: 'typenameType'
}
Error during migration run:
QueryFailedError: type "public.roles_access_for_enum" does not exist
parameters: undefined,
  driverError: error: type "public.roles_access_for_enum" does not exist
      at Parser.parseErrorMessage (C:\Users\Usama\Desktop\quick-NEW\quick-grocerries\node_modules\pg-protocol\src\parser.ts:369:69) 
      at Parser.handlePacket (C:\Users\Usama\Desktop\quick-NEW\quick-grocerries\node_modules\pg-protocol\src\parser.ts:188:21)      
      at Parser.parse (C:\Users\Usama\Desktop\quick-NEW\quick-grocerries\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (C:\Users\Usama\Desktop\quick-NEW\quick-grocerries\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 116,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: '223',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_type.c',
    line: '274',
    routine: 'typenameType'
  },
  length: 116,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: '223',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '274',
  routine: 'typenameType'
}

**Comment by AlexMesser** [comment]
Please use the issue template and provide more details about your issue.
