### ISSUE TITLE
QueryFailedError: we cannot push output columns into *physical.Union

### ISSUE THREAD

**Issue by jeffminsungkim** [typeorm/typeorm#9537]
## Issue Description

Getting the following error when I use typeorm synchronize option in NestJS with [PlanetScale](https://planetscale.com/).

```
QueryFailedError: we cannot push output columns into *physical.Union
    at Query.onResult (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.execute (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at TLSSocket.<anonymous> (/Users/jeffminsungkim/Projects/workspace/sinjoer/backend/node_modules/mysql2/lib/connection.js:360:25)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
```

The question is if this is an expected behavior or not the problem with typeorm library itself, then why does it work when there are no tables in the database? 

config.ts

```typescript
{
  type: 'mysql',
  host: process.env.MYSQL_HOST,
  port: parseInt(process.env.MYSQL_PORT),
  username: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
  autoLoadEntities: true,
  synchronize: NotInProduction,
  timezone: 'Z',
  ssl: {
    rejectUnauthorized: true,
  },
};
```

### Expected Behavior

The app should start every time I make an update the code. 

### Actual Behavior

The app starts normally  only if I drop all my tables from database. 

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. Create an app from PlatnetScale
2. Start NestJS app
3. Check tables have successfully created in db, then re-run the app.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS Monterey 12.6        |
| Node.js version     | 18.12 | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.10 latest  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by daviesesiro** [comment]
@jeffminsungkim were you able to fix this?

**Comment by jeffminsungkim** [comment]
@daviesesiro I have to delete all the tables manually beforehand in order to restart the server.
