### ISSUE TITLE
QueryFailedError: syntax error at or near "WHERE"

### ISSUE THREAD

**Issue by Ezzedini-Yassine** [typeorm/typeorm#9541]
## Issue Description
I have 2 Entities, User entity and Task entity, the User has a one to many relationship with task, and task has many to one relationship with user, and eager is set to true from the User entity, when I try to sign in with a user, I should check if he exist in the database through his user name.

### Expected Behavior

I'm using findOne so when the user exists through his username it should return me the user object, if not it should return null

### Actual Behavior

Instead it returns QueryFailedError: syntax error at or near "WHERE"
the exact error 
```
QueryFailedError: syntax error at or near "WHERE"
    at PostgresQueryRunner.query (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\driver\postgres\PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SelectQueryBuilder.loadRawResults (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\query-builder\SelectQueryBuilder.ts:3601:25)
    at SelectQueryBuilder.getRawMany (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\query-builder\SelectQueryBuilder.ts:1573:29)
    at SelectQueryBuilder.executeEntitiesAndRawResults (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\query-builder\SelectQueryBuilder.ts:3295:26)
    at SelectQueryBuilder.getRawAndEntities (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\query-builder\SelectQueryBuilder.ts:1617:29)
    at SelectQueryBuilder.getOne (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\query-builder\SelectQueryBuilder.ts:1644:25)
    at UsersRepository.findByUsername (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\auth\users.repository.ts:32:21)
    at AuthService.signIn (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\src\auth\auth.service.ts:20:22)
    at C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\node_modules\@nestjs\core\router\router-execution-context.js:46:28 {
  query: 'SELECT DISTINCT "distinctAlias"."User_id" AS "ids_User_id" FROM (SELECT "User"."id" AS "User_id", "User"."username" AS "User_username", "User"."password" AS "User_password", "User_tasks"."id" AS "User_tasks_id", "User_tasks"."title" AS "User_tasks_title", "User_tasks"."description" AS "User_tasks_description", "User_tasks"."status" AS "User_tasks_status" FROM "user" "User" LEFT JOIN "task" "User_tasks" ON  WHERE ("User"."username" = $1)) "distinctAlias" ORDER BY "User_id" ASC LIMIT 1',
  parameters: [ 'toutou' ],
  driverError: error: syntax error at or near "WHERE"
      at Parser.parseErrorMessage (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\node_modules\pg-protocol\src\parser.ts:369:69)
      at Parser.handlePacket (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\node_modules\pg-protocol\src\parser.ts:188:21)
      at Parser.parse (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (C:\Users\Yassine\Desktop\nesttraining\nestjs-task-management\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:390:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
    length: 95,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '411',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
```

User entity
```
import { Task } from "src/tasks/task.entity";
import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({unique: true})
    username: string;

    @Column()
    password: string;

    @OneToMany((_type) => Task, (task) => task.user, { eager: true})
    tasks: Task[];
}
```

Task entity
```
import { TaskStatus } from './task-status.enum';
import { Column, Entity, ManyToMany, PrimaryGeneratedColumn } from "typeorm";
import { User } from 'src/auth/user.entity';

@Entity()
export class Task {

    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column()
    title: string;

    @Column()
    description: string;

    @Column()
    status: TaskStatus;

    @ManyToMany((_type) => User, (user) => user.tasks, { eager: false})
    user: User
}
```

Users repository
```
import { AuthCredentialsDTO } from './dto/auth-credentials.dto';
import { Repository } from 'typeorm';
import { User } from './user.entity';
import { InjectRepository } from "@nestjs/typeorm";
import { ConflictException, InternalServerErrorException, Param } from '@nestjs/common';
import * as bcrypt from 'bcrypt';

export class UsersRepository {
    constructor(@InjectRepository(User) readonly repo: Repository<User>){
        console.log("users repository");
    }

    async createUser(authCredentialsDTO: AuthCredentialsDTO): Promise<void>{
        const {username, password} = authCredentialsDTO;

        const salt = await bcrypt.genSalt();
        const hashedPassword = await bcrypt.hash(password, salt);

        const user = this.repo.create({username, password: hashedPassword});
        try{
            await this.repo.save(user);
        }catch(error){
            if(error.code === '23505'){ // duplicate username
                throw new ConflictException('Username already exists')
            } else {
                throw new InternalServerErrorException();
            }
        }
    }

    async findByUsername(username: string): Promise<any>{
        try {return await this.repo.findOne({where: {username}})
    } catch (error){
        console.log(error);
    }
    }
}
```

My auth service

```
import { AuthCredentialsDTO } from './dto/auth-credentials.dto';
import { UsersRepository } from './users.repository';
import { Injectable, NotFoundException, Post, UnauthorizedException } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import { JwtService } from '@nestjs/jwt';
import { JwtPayload } from './jwt-payload.interface';

@Injectable()
export class AuthService {
    constructor( private usersRepository: UsersRepository,
        private jwtService: JwtService){}

    signUp(authCredentialsDTO: AuthCredentialsDTO): Promise<void>{
        return this.usersRepository.createUser(authCredentialsDTO);
    }

    async signIn(authCredentialsDTO: AuthCredentialsDTO): Promise<{accessToken: string}>{
        const {username, password} = authCredentialsDTO;
        console.log('my username in  auth ', username, ' my pass word in auth: ', password)
        const user = await this.usersRepository.findByUsername(username);
        console.log('my user: ', user);

        if(user && (await bcrypt.compare(password, user.password))){
            const payload: JwtPayload = { username};
            const accessToken: string = await this.jwtService.sign(payload);
            return {accessToken};
        } else {
             throw new UnauthorizedException('Please check your credentials');
        }
    }
}
```
My auth controller

```
import { User } from './user.entity';
import { AuthCredentialsDTO } from './dto/auth-credentials.dto';
import { AuthService } from './auth.service';
import { Body, Controller, Get, Post, Req, UseGuards } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';

@Controller('auth')
export class AuthController {
    constructor(private authService: AuthService){}

    @Get()
    getUsers(){
        return "hello world";
    }

    @Post('/signup')
    signUp(@Body() authCredentialsDTO: AuthCredentialsDTO): Promise<void>{
        return this.authService.signUp(authCredentialsDTO);    
    }

    @Post('/signin')
    signIn(@Body() authCredentialsDTO: AuthCredentialsDTO): Promise<{accessToken: string}>{
        return this.authService.signIn(authCredentialsDTO);    
    }

    @Post('/test')
    @UseGuards(AuthGuard())
    test(@Req() req){
        console.log('>'.repeat(20), req.user);
    }
}

```

### Steps to Reproduce

When I set eager to false in the user entity it works fine, but when it is true that where problem starts

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 10         |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.7.4| 
| TypeORM version     | 0.3.10  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by luca-nardelli** [comment]
:+1: The same is happening to me as well. In my case though it's happening on a OneToOne relation which I am accessing through the query builder. The owning side is the `Customer` entity

Example call
```
const ITEM = await this.em.createQueryBuilder(BillingAccountEntity,'o')
      .leftJoinAndSelect('o.customer','customer').getOne();
```

Generated query

```
"SELECT \"o\".\"id\" AS \"o_id\", \"o\".\"created_at\" AS \"o_created_at\", \"o\".\"updated_at\" AS \"o_updated_at\", \"o\".\"type\" AS \"o_type\", \"o\".\"address\" AS \"o_address\", \"o\".\"external_id\" AS \"o_external_id\", \"o\".\"tax_code\" AS \"o_tax_code\", \"o\".\"vat_code\" AS \"o_vat_code\", \"o\".\"sdi_code\" AS \"o_sdi_code\", \"o\".\"pec\" AS \"o_pec\", \"o\".\"balance\" AS \"o_balance\", \"customer\".\"id\" AS \"customer_id\", \"customer\".\"created_at\" AS \"customer_created_at\", \"customer\".\"updated_at\" AS \"customer_updated_at\", \"customer\".\"first_name\" AS \"customer_first_name\", \"customer\".\"last_name\" AS \"customer_last_name\", \"customer\".\"billing_account_id\" AS \"customer_billing_account_id\" FROM \"billing_account_entity\" \"o\" LEFT JOIN \"customer_entity\" \"customer\" ON"
```

**Comment by luca-nardelli** [comment]
Actually, scratch that. In my case I had a typo in the `@OneToOne` decorator and I put the wrong inverse side on one of the two sides, which means I broke the metadata basically.

@Ezzedini-Yassine in your example I also see something weird. On the User side you have OneToMany, whereas on the Task side you have ManyToMany, shouldn't it be `ManyToOne`?

**Comment by Ezzedini-Yassine** [comment]
@luca-nardelli you are right, wow my bad.

**Comment by voho** [comment]
Encountered something similar. More useful error message would be nice, I was scratching my head about what "distinctAlias" is.
