### ISSUE TITLE
Typeorm CLI migration command fail silently 

### ISSUE THREAD

**Issue by sorakrisc** [typeorm/typeorm#9568]
## Issue Description
Running `yarn typeorm migration:run -d unexist_patch.ts` logs error but does not actually exit the process with exit code 1

### Expected Behavior
should command failed with exit code 1.
```
❯ yarn typeorm migration:run -d unexit_file.ts && echo "should not see this"
yarn run v1.22.18
$ typeorm-ts-node-esm migration:run -d unexit_file.ts
Error during migration run:
Error: Unable to open file: ".../unexit_file.ts". Cannot find module '.../unexit_file.ts'
Require stack:
- .../node_modules/typeorm/util/ImportUtils.js
- .../node_modules/typeorm/commands/CommandUtils.js
- .../node_modules/typeorm/commands/SchemaSyncCommand.js
- .../node_modules/typeorm/cli.js
- .../node_modules/typeorm/cli-ts-node-esm.js
    at Function.loadDataSource (.../node_modules/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (.../node_modules/src/commands/MigrationRunCommand.ts:42:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Actual Behavior
```
❯ yarn typeorm migration:run -d unexit_file.ts && echo "should not see this"
yarn run v1.22.18
$ typeorm-ts-node-esm migration:run -d unexit_file.ts
Error during migration run:
Error: Unable to open file: ".../unexit_file.ts". Cannot find module '.../unexit_file.ts'
Require stack:
- .../node_modules/typeorm/util/ImportUtils.js
- .../node_modules/typeorm/commands/CommandUtils.js
- .../node_modules/typeorm/commands/SchemaSyncCommand.js
- .../node_modules/typeorm/cli.js
- .../node_modules/typeorm/cli-ts-node-esm.js
    at Function.loadDataSource (.../node_modules/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (.../node_modules/src/commands/MigrationRunCommand.ts:42:26)
✨  Done in 1.15s.
should not see this
```

### Steps to Reproduce

1. Run migration run command with unexisted file path && echo "should not see this"
`typeorm-ts-node-esm migration:run -d unexit_file.ts`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 12.5.1   |
| Node.js version     | 16.13.1 |
| Typescript version  | 4.8.2  | 
| TypeORM version     | 0.3.10 | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by sorakrisc** [comment]
will close this for now fixed this by using `typeorm-ts-node-commonjs` instead

**Comment by sorakrisc** [comment]
thinking about it again should ems be exiting with exit code 1?

**Comment by Rayyan98** [comment]
> thinking about this again should ems be exiting with exit code 1?

Is there any reason for them not to ? I was relying on them for my CI CD pipelines and they were failing silently even when unable to connect to database and i only knew something was wrong after code deployment completed.
