### ISSUE TITLE
Don't require constructor

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#9569]
## Feature Description

I'd like for Typeorm not to call my constructor when loading from the database.

### The Problem

If Typeorm uses my constructor it requires things to be optional, which may not be when we need to create a new instance. Part of this problem is that I noticed for metadata loading, it was calling the constructor even without there being any data to load. Froma. type perspective it makes it difficult to say X field is non nullish/required without bypassing typesafety with `!`.

### Additional Context

```
[Nest] 86980  - 11/23/2022, 6:39:06 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
TypeError: Cannot read properties of undefined (reading 'storefrontId')
    at new StorefrontProductAggregate (/Users/xeno/IdeaProjects/services-cloud/dist/apps/product/webpack:/services-core/apps/product/src/core/storefront-menu/storefront-product.aggregate-root.ts:67:33)
    at EntityMetadata.create (/Users/xeno/IdeaProjects/services-cloud/src/metadata/EntityMetadata.ts:563:23)
    at EntityMetadataValidator.validate (/Users/xeno/IdeaProjects/services-cloud/src/metadata-builder/EntityMetadataValidator.ts:201:47)
    at /Users/xeno/IdeaProjects/services-cloud/src/metadata-builder/EntityMetadataValidator.ts:43:18
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/xeno/IdeaProjects/services-cloud/src/metadata-builder/EntityMetadataValidator.ts:42:25)
    at DataSource.buildMetadatas (/Users/xeno/IdeaProjects/services-cloud/src/data-source/DataSource.ts:689:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DataSource.initialize (/Users/xeno/IdeaProjects/services-cloud/src/data-source/DataSource.ts:242:13)
 ```

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         |yes            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

```
   └─ typeorm@npm:0.3.10 [8316d] (via npm:^0.3.10 [8316d])
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.
 - ✅ Maybe, I might be able to arrange the time, but I have no idea where to start

**Comment by OSA413** [comment]
Hi, can you please provide a minimal reproducible example repository of the error?

**Comment by xenoterracide** [comment]
no, this request is so old I don't work for that company anymore.
