### ISSUE TITLE
Error generating migrations after serializing a class-transformer class into a json field

### ISSUE THREAD

**Issue by gmenih** [typeorm/typeorm#9571]
## Issue Description

I'm trying to serialize a `class-transformer` decorated class into a `json` field in PostgreSQL. To do that, I use this block of code:

```ts
 @Column({
    type: 'json',
    transformer: {
      to: (value: BuilderTemplate): any => instanceToPlain(value),
      from: (value: any): BuilderTemplate => plainToInstance(BuilderTemplate, value),
    },
  })
  builderTemplate!: BuilderTemplate;
```

This works as expected, and the class is properly serialized, and deserialized. However, this for some reason completely breaks generating migrations. Attempting to generate it will produce this error (full dump below)

```
Error: failed to handle: Bad type for decoration: TsLitType
```

### Expected Behavior

I would expect the migrations would still be able to generate.

### Actual Behavior

The migrations error out, and I can't generate any migrations after this. The full error is:

```
yarn migration:gen schedule-3
STAGE=local yarn node -r tsconfig-paths/register $(yarn bin typeorm-ts-node-commonjs) migration:generate src/database/migrations/schedule-3 -d ./src/modules/app/app.data-source.ts 
thread '<unnamed>' panicked at 'Bad type for decoration: TsLitType { span: Span { lo: BytePos(71164), hi: BytePos(71203), ctxt: #0 }, lit: Tpl(TsTplLitType { span: Span { lo: BytePos(71164), hi: BytePos(71203), ctxt: #0 }, types: [TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71167), hi: BytePos(71173), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71176), hi: BytePos(71182), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71186), hi: BytePos(71192), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71195), hi: BytePos(71201), ctxt: #0 }, kind: TsNumberKeyword })], quasis: [TplElement { span: Span { lo: BytePos(71165), hi: BytePos(71165), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71174), hi: BytePos(71174), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71183), hi: BytePos(71184), ctxt: #0 }, tail: false, cooked: Some(Atom(':' type=inline)), raw: Atom(':' type=inline) }, TplElement { span: Span { lo: BytePos(71193), hi: BytePos(71193), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71202), hi: BytePos(71202), ctxt: #0 }, tail: true, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }] }) }', crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs:423:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error during migration generation:
Error: failed to handle: Bad type for decoration: TsLitType { span: Span { lo: BytePos(71164), hi: BytePos(71203), ctxt: #0 }, lit: Tpl(TsTplLitType { span: Span { lo: BytePos(71164), hi: BytePos(71203), ctxt: #0 }, types: [TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71167), hi: BytePos(71173), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71176), hi: BytePos(71182), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71186), hi: BytePos(71192), ctxt: #0 }, kind: TsNumberKeyword }), TsKeywordType(TsKeywordType { span: Span { lo: BytePos(71195), hi: BytePos(71201), ctxt: #0 }, kind: TsNumberKeyword })], quasis: [TplElement { span: Span { lo: BytePos(71165), hi: BytePos(71165), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71174), hi: BytePos(71174), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71183), hi: BytePos(71184), ctxt: #0 }, tail: false, cooked: Some(Atom(':' type=inline)), raw: Atom(':' type=inline) }, TplElement { span: Span { lo: BytePos(71193), hi: BytePos(71193), ctxt: #0 }, tail: false, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }, TplElement { span: Span { lo: BytePos(71202), hi: BytePos(71202), ctxt: #0 }, tail: true, cooked: Some(Atom('' type=static)), raw: Atom('' type=static) }] }) }
    at Compiler.transformSync (/home/user/projects/test/.yarn/unplugged/@swc-core-npm-1.2.218-ab87518b3f/node_modules/@swc/core/index.js:222:29)
    at Object.transformSync (/home/user/projects/test/.yarn/unplugged/@swc-core-npm-1.2.218-ab87518b3f/node_modules/@swc/core/index.js:325:21)
    at Object.transpile (/home/user/projects/test/.yarn/__virtual__/ts-node-virtual-b6084a69c5/0/cache/ts-node-npm-10.8.2-f3c0c9eaee-1eede939be.zip/node_modules/ts-node/src/transpilers/swc.ts:157:39)
    at /home/user/projects/test/.yarn/__virtual__/ts-node-virtual-b6084a69c5/0/cache/ts-node-npm-10.8.2-f3c0c9eaee-1eede939be.zip/node_modules/ts-node/src/index.ts:1333:35
    at Object.compile (/home/user/projects/test/.yarn/__virtual__/ts-node-virtual-b6084a69c5/0/cache/ts-node-npm-10.8.2-f3c0c9eaee-1eede939be.zip/node_modules/ts-node/src/index.ts:1436:13)
    at Module.m._compile (/home/user/projects/test/.yarn/__virtual__/ts-node-virtual-b6084a69c5/0/cache/ts-node-npm-10.8.2-f3c0c9eaee-1eede939be.zip/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require$$0.Module._extensions..js (/home/user/projects/test/.pnp.cjs:21435:33)
    at Object.require.extensions.<computed> [as .ts] (/home/user/projects/test/.yarn/__virtual__/ts-node-virtual-b6084a69c5/0/cache/ts-node-npm-10.8.2-f3c0c9eaee-1eede939be.zip/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'GenericFailure'
}
```

### Steps to Reproduce

1. Create a class that you want to serialize
2. Attempt to store it into a column with a `json` type, with a `transformer` option
3. Attempt to generate a migration

### My Environment

We are using SWC as our compilerm, the project is in NestJS, and running the migrations via `yarn bin typeorm-ts-node-commonjs`.

We're also using Yarn PnP

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.17.0  | 
| Typescript version  | 4.7.4    | 
| TypeORM version     | 0.3.7    | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `postgres`        | yes           |

**Comment by gmenih** [comment]
Looks like the issue is related to SWC. After disabling it, the migrations are correctly generated again.

**Comment by Sailiy** [comment]
Hello, I customized the converter on a column and the migration failed.

timestamp.transformer.ts：
```
import { ValueTransformer } from 'typeorm';

export class TimestampTransformer implements ValueTransformer {
  from(value: Date): number {
    return value.getTime(); //Convert to timestamp
  }

  to(value: number): Date {
    return new Date(value); // Converts a timestamp to a date object
  }
}
```
device.dto.ts
```
import { TimestampTransformer } from './timestamp.transformer';
@Entity()
export class Device {
  //.....
  @Column({ type: 'datetime', transformer: new TimestampTransformer() })
  exptime: number;
}

```
package.json
```
"scripts": {
    "typeorm": "typeorm-ts-node-esm -d ormconfig.ts",
    "migration:generate": "npm run typeorm -- migration:generate ./migrations/test",
}
```
With transformer removed from the dto column, the migration worked fine. Adding 'transformer: new TimestampTransformer()' causes the following error：
```
Error during migration generation:
Error: Cannot find module 'src/global/transformer/timestamp.transformer'
Require stack:
- D:\xxx\src\device\entities\device.entity.ts
- D:\xxx\node_modules\typeorm\util\ImportUtils.js
- D:\xxx\node_modules\typeorm\commands\CommandUtils.js
- D:\xxx\node_modules\typeorm\commands\SchemaSyncCommand.js
- D:\xxx\node_modules\typeorm\cli.js
- D:\xxx\node_modules\typeorm\cli-ts-node-esm.js
```
