### ISSUE TITLE
Postgres OneToOne

### ISSUE THREAD

**Issue by 11000100111000** [typeorm/typeorm#962]
When using the following entities

```js
@Entity()
export class Token {
    @PrimaryGeneratedColumn()
    public id: number;
    @OneToOne(type => User, user => user.email)
    public email: string;
    @Column()
    public token: string;
}

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    public id: number;
    @OneToOne(type => Token, token => token.email)
    @Column({unique: true})
    public email: string;
}
```

trying to get the token (find and findOne) yields the following error
```
error:  QueryFailedError: invalid reference to FROM-clause entry for table "token"
    at Connection.parseE (C:\server\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\server\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\server\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```
and in the database log the following errors appear
```
ERROR:  invalid reference to FROM-clause entry for table "token" at character 96
HINT:  Perhaps you meant to reference the table alias "Token".
STATEMENT:  SELECT "Token"."id" AS "Token_id", "Token"."token" AS "Token_token" FROM "token" "Token" WHERE Token.email=$1
```
otherwise typeorm is awesome so far, keep up the good work   :heart:

**Comment by pleerock** [comment]
You have a wrong entity. First, you forgot to use `@JoinColumn` - its required for use on one side of one-to-one relation. Second, you don't need a `@Column` decorator on a relation. Third, relations are OBJECTS, not "email".

```ts
@Entity()
export class Token {
    @PrimaryGeneratedColumn()
    public id: number;
    @OneToOne(type => User, user => user.token)
    @JoinColumn()
    public user: User;
    @Column()
    public token: string;
}

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    public id: number;
    @Column({ unique: true })
    public email: string;
    @OneToOne(type => Token, token => token.user)
    public token: Token;
}
```

If you want to bind them via `email` instead of `id` use following code:


```ts
    @OneToOne(type => User, user => user.token)
    @JoinColumn({ referencedColumnName: "email" })
    public user: User;
}
```

**Comment by pleerock** [comment]
Okay, I see in #968 you already found a solution
