### ISSUE TITLE
[BUG]: QueryFailedError when importing AppDataSource.getRepository in multiple places

### ISSUE THREAD

**Issue by rolandm2017** [typeorm/typeorm#9637]
### Issue description

Importing the repository into multiple DAO objects causes a bug.

### Expected Behavior

Expected behavior: I can import the following line and use it in multiple files.

` export const taskRepository = AppDataSource.getRepository(Task);`

and then later

`
import {
    committeeRepository,
    taskRepository,
    memberRepository,
} from "./db/data-source";

const committeeDAO = new CommitteeDAO(committeeRepository);
const memberDAO = new MemberDAO(memberRepository);
const taskDAO = new TaskDAO(taskRepository, memberDAO, memberRepository);
`

example of memberDAO (i think the team knows what this is)

`
class MemberDAO {
    private memberRepository: Repository<Member>;
    constructor(memberRepository: Repository<Member>) {
        this.memberRepository = memberRepository;
    }
  // do data access layer stuff
`

Problem is I was also importing and doing similar in another file:

`
import {  committeeRepository, memberRepository, taskRepository } from "../../src/db/data-source";

const memberDAO = new MemberDAO(memberRepository);
const taskDAO = new TaskDAO(taskRepository, memberDAO, memberRepository);
`

### Actual Behavior

I get the following error while trying to import it into two different places: (1) the server.ts where i initialize controllers,services, and data access (2) the unit tests. It's not nice to get an error, but worse, it's misleading!

`  QueryFailedError: null value in column "memberUserId" of relation "tasks_for_member" violates not-null constraint

      at PostgresQueryRunner.query (src/driver/postgres/PostgresQueryRunner.ts:299:19)
      at InsertQueryBuilder.execute (src/query-builder/InsertQueryBuilder.ts:163:33)
      at SubjectExecutor.executeInsertOperations (src/persistence/SubjectExecutor.ts:428:42)
      at SubjectExecutor.execute (src/persistence/SubjectExecutor.ts:137:9)
      at EntityPersistExecutor.execute (src/persistence/EntityPersistExecutor.ts:197:21)
      at TaskDAO.createTask (src/db/dao/task.dao.ts:49:13)
      at Object.<anonymous> (tests/dbUtil/purgeDb.test.ts:132:9)`

### Steps to reproduce

To reproduce this bug:

1. go to https://github.com/plutownium/typeORMbug
2. git pull the `3/mkBug` branch.
3. checkout the 2nd to last commit, `bb830372489f072437498bdb3f68344a3ee5ba3f`, which is commented as "bug shows"
4. npm install
5. run `npm run test:d` which runs the /tests/dao folder's tests.

You will get the following output:

` task DAO › create a task

    QueryFailedError: null value in column "memberUserId" of relation "tasks_for_member" violates not-null constraint

      at PostgresQueryRunner.query (src/driver/postgres/PostgresQueryRunner.ts:299:19)
      at InsertQueryBuilder.execute (src/query-builder/InsertQueryBuilder.ts:163:33)
      at SubjectExecutor.executeInsertOperations (src/persistence/SubjectExecutor.ts:428:42)
      at SubjectExecutor.execute (src/persistence/SubjectExecutor.ts:137:9)
      at EntityPersistExecutor.execute (src/persistence/EntityPersistExecutor.ts:197:21)
`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     ubuntu 22.04    |
| Node.js version     | v18.12.1  |
| Typescript version  | "ts-node":"^10.9.1","typescript":"^4.9.4"  |
| TypeORM version     | "^0.3.11"  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by plutownium** [comment]
I figured out why there was a bug. my fault, should've read the docs closer.

Solution was to have `@JoinTable` in the ManyToMany relationship side that would have the other side "attached" to it just like in these docs https://typeorm.io/ where it says `@ManyToMany(() => Photo, (photo) => photo.albums)` and then `  @JoinTable()` indicating that later the association is formed like `photo.albums = [album1, album2]` BUT NOT `album.photos = [photo1, photo2]`
