### ISSUE TITLE
[BUG]: Using typeorm migrations in nuxt 3 does not work

### ISSUE THREAD

**Issue by djschilling** [typeorm/typeorm#9645]
### Expected Behavior

I want to use typeorm in my nuxt 3 project.
In general it works but i cannot get the migrations to work.

I tried these different command lines to make it work:

```
npx typeorm-ts-node-esm migration:run -d server/db/connection.ts
node --require ts-node/register ./node_modules/typeorm/cli.js migration:run -d server/db/connection.ts
npx typeorm-ts-node-commonjs migration:run -d server/db/connection.ts
npx vite-node ./node_modules/typeorm/cli.js -- migration:run -d server/db/connection.ts
```

Every one of them resulted in this error:

```
Error during migration run:
Error: Unable to open file: "/Users/david/projects/work/finder/churchtools-finder/server/db/connection.ts". Cannot use import statement outside a module
    at Function.loadDataSource (/Users/david/projects/work/finder/churchtools-finder/node_modules/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (/Users/david/projects/work/finder/churchtools-finder/node_modules/src/commands/MigrationRunCommand.ts:42:26)
```

This is how my datasource looks:

```
import { DataSource } from 'typeorm'
import { Association } from '~~/src/entity/association'



const AppDataSource = new DataSource({
  type: 'mysql',
  synchronize: false,
  logging: false,
  host: process.env.TYPEORM_HOST,
  port: Number(process.env.TYPEORM_PORT),
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
  entities: [Association],
})

const initialize = async () => {
  console.log('DB: Initializing DB connection')

  if (AppDataSource.isInitialized) {
    console.log('DB: Already initialized')
    return
  }

  try {
    await AppDataSource.initialize()
  } catch (error) {
    console.trace('DB: Failed to initialized database', error)
    throw error
  }

  console.log('DB: Successfully initialized database connection')
}

export { AppDataSource, initialize }
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |        MacOs  |
| Node.js version     | v17.9.1  |
| Typescript version  | 4.5.5  |
| TypeORM version     | 0.3.11  |

**Comment by damgem** [comment]
The following `package.json` scripts are currently working for me as a workaround:
```json
"prepare-migration-datasource": "esbuild server/database/index.ts --external:'pg-native' --platform=node --bundle --log-level=warning --outfile=server/database/migration/_dataSource.js",
"create-migration": "typeorm migration:create server/database/migration/$npm_config_name",
"generate-migration": "npm run prepare-migration-datasource && typeorm migration:generate -d server/database/migration/_dataSource.js server/database/migration/$npm_config_name",
"run-migrations": "npm run prepare-migration-datasource && typeorm migration:run -d server/database/migration/_dataSource.js",
"revert-migration": "npm run prepare-migration-datasource && typeorm migration:revert -d server/database/migration/_dataSource.js"
```

```
npm run create-migration --name=HelloMigration
npm run generate-migration --name=HelloMigration
npm run run-migrations
npm run revert-migration
```

Depending on the database you're using you might something different than `--external:'pg-native'`.
