### ISSUE TITLE
Problem importing DataSource on Lambda 

### ISSUE THREAD

**Issue by diogoviannaaraujo** [typeorm/typeorm#9721]
### Issue description

Creating a DataSource trows TypeError in AWS lambda deployed with Pulumi

### Expected Behavior

Expected Client to be created and connection to happen

### Actual Behavior

A error is generated:
```
2023-01-19T19:15:33.188Z	fb29fe61-e0ff-43b2-adb0-aaa7e6147c50	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Class extends value undefined is not a constructor or null",
    "stack": [
        "TypeError: Class extends value undefined is not a constructor or null",
        "    at Object.<anonymous> (/var/task/node_modules/typeorm/connection/Connection.js:12:39)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at Object.<anonymous> (/var/task/node_modules/typeorm/index.js:139:20)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)"
    ]
}
```

### Steps to reproduce

Created a stack with Pulumi, created a AWS Lambda function, imported my configured DataSource and called initialize.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS      |
| Node.js version     | 16.18.1  |
| Typescript version  | 4.9.4  |
| TypeORM version     | 0.3.11  |

### Additional Context

Pulumi serialize the lambda function and dependencies before compressing and uploading to AWS, seems that something in that serialization process is not going well, but I'm unsure exactly since I've used a lot of other modules and have not seen that before. Have read the Connection.ts file but can't seem to understand why it would export undefined.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by iJhefe** [comment]
can you give a sample repository ?

**Comment by diogoviannaaraujo** [comment]
Actually trying to isolate the problem made that one disappeared, but I'm facing a different issue but also related to TS compiling/serializing.
When creating the dataSource using pulumi function serialization the entity does not seem to be loaded.
Something like:
```
"use strict";
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");

const typeorm = require("typeorm");
import { Entity, PrimaryColumn, Column } from 'typeorm'

@Entity()
export class User {
    @PrimaryColumn()
    id!: number

    @Column()
    key!: string
}

const lambda = new aws.lambda.CallbackFunction("pulumi-aws-issue2329", {
    callback: async e => {
        var dataSource = new typeorm.DataSource({
            type: "postgres",
            host: "localhost",
            port: 5432,
            username: "test",
            password: "admin",
            database: "test",
            synchronize: true,
            entities: [User]
        });
        await dataSource.initialize()
        const userRepository = dataSource.getRepository(User)
        const allUsers = await userRepository()
        
        return "OK";
    }
});
```
Gives an error like:
```
EntityMetadataNotFoundError: No metadata for "__f30" was found
```
Also checking dataSource.entityMetadatas that code returns an empty array.

Here's a repository replicating the error:
https://github.com/diogoviannaaraujo/pulumi-lambda-typeorm
