### ISSUE TITLE
Mongo: problem renaming field _id (@ObjectIdColumn)

### ISSUE THREAD

**Issue by mrddter** [typeorm/typeorm#9727]
### Issue description

Mongo: problem renaming field _id (@ObjectIdColumn)

### Expected Behavior

Using an entity like this (where is used `id` field and not `_id`):

```js
@Entity()
export class User {
   @ObjectIdColumn() // { name: '_id' }
   id: ObjectID

   @Index()
   @Column()
   email: string
}
```

I expected to load an entity in this way:

```js
userRepository.preload({ id: id })
userRepository.findOne({ id: id })
userRepository.find({ where: { id: id } })
User.findOne({ id: id })
User.find({ where: { id: id } })
```

### Actual Behavior

Actually, the find doesn't return anything even if on DB everything is correct. 
Other methods also fail, such as `remove(entity)` as evidenced by the example repo.

All works well for these finds:

```js
User.find({ where: { email: 'test@test.it' } })
User.findOneById(id)
userRepository.findOneById(id)
```

The create() / save() adds correctly a record like this:

```json
{
"_id":{"$oid":"63caa1adde907b687dfa8a65"},
"email":"test@test.it"
}
```

But if you run the example (below) use see in the collection something like this:

```json
{"_id":{"$oid":"63ce9be9d7fe09a6b790d9de"},"email":"test@test.it"}

{"_id":{"$oid":"63ce9be9d7fe09a6b790d9df"},"email":"test@test.it","id":null}

{"_id":{"$oid":"63ce9bead7fe09a6b790d9e0"},"email":"another@test.it","id":{"$oid":"63ce9be9d7fe09a6b790d9df"}}

{"_id":{"$oid":"63ce9bead7fe09a6b790d9e1"},"email":"another@test.it","id":null}
```
Console output:

```
User has been saved. Lets insert a new one to update it later
Second entity has been inserted. Lets update it
Entity has been updated. Persist once again to make find and remove then
Entity is loaded:  User { email: 'another@test.it' }
Now remove it by entity {"email":"another@test.it"}
Cannot save. Error:  SubjectWithoutIdentifierError: Internal error. Subject User must have an identifier to perform operation.
    at /Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:682:27
    at Array.map (<anonymous>)
    at SubjectExecutor.executeRemoveOperations (/Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:680:41)
    at SubjectExecutor.execute (/Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:156:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EntityPersistExecutor.execute (/Users/dev/typeorm-mongo/node_modules/src/persistence/EntityPersistExecutor.ts:197:21) SubjectWithoutIdentifierError: Internal error. Subject User must have an identifier to perform operation.
    at /Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:682:27
    at Array.map (<anonymous>)
    at SubjectExecutor.executeRemoveOperations (/Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:680:41)
    at SubjectExecutor.execute (/Users/dev/typeorm-mongo/node_modules/src/persistence/SubjectExecutor.ts:156:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EntityPersistExecutor.execute (/Users/dev/typeorm-mongo/node_modules/src/persistence/EntityPersistExecutor.ts:197:21)
```

### Steps to reproduce

You can use this repo

https://github.com/mrddter/typeorm-mongo.git

Thanks

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS 13.1  |
| Node.js version     | 18.12.0  |
| Typescript version  | 4.9.4 |
| TypeORM version     | 0.3.11  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by l337quez** [comment]
You cannot do a search with objectId of type string. you must transform it into mongo objectId... I say it because of what I see

{
"_id":{"$oid":"63caa1adde907b687dfa8a65"},
"email":"test@test.it"
}

here I explain how to do it

[](https://ronaldl337.wordpress.com/2023/01/17/tutorial-de-typeorm-with-mongo-and-nestjs/)

**Comment by mrddter** [comment]
@l337quez thanks for the reply, I tried but without a success

unfortunately the link is broken ("¡Vaya! Esa página no se puede encontrar."). 
Is it possible have a new one?

And, if you have time / possibility, do you see any errors in the code provided under "Steps to reproduce"?
Thanks in advance

**Comment by ougarte** [comment]
Here is a similar behavior. `findOneBy`

I think the `MongoEntityManager` needs to be updated based on new `findIOneBy` implementation. The function `findOneBy` uses `executeFindOne`, so that the parameter `optionsOrConditions` is expecting to be either a `string` or `ObjectId`;  otherwise it propagates the `where` as IS. I recommend replicate `findByIds` implementation.
