### ISSUE TITLE
EntityMetadataNotFoundError BUG

### ISSUE THREAD

**Issue by omar-contreras-mayasoft** [typeorm/typeorm#9860]
### Issue description

When an entity is consulted, it throws the following error: EntityMetadataNotFoundError

### Expected Behavior

Entities can be consulted without problem. Without modifying anything in the project configuration when installing the dependencies again, I find that the problem is in the typeorm version 0.3.12, if I change the version to 0.3.11 it works correctly.

### Actual Behavior

When an entity is consulted, it throws the following error:

D:\projects\test\backend\node_modules\src\data-source\DataSource.ts:438
        if (!metadata) throw new EntityMetadataNotFoundError(target)
                             ^
EntityMetadataNotFoundError: No metadata for "TaskFunction" was found.
    at DataSource.getMetadata (D:\projects\test\backend\node_modules\src\data-source\DataSource.ts:438:30)
    at TaskFunctionRepository.get metadata [as metadata] (D:\projects\test\backend\node_modules\src\repository\Repository.ts:53:40)
    at TaskFunctionRepository.find (D:\projects\test\backend\node_modules\src\repository\Repository.ts:524:39)
    at TaskService.getAllTaskFunctions (D:\projects\test\backend\src\modules\task\task.service.ts:70:77)
    at TaskService.synchronizeTaskFunctions (D:\projects\test\backend\src\modules\task\task.service.ts:97:43)
    at TaskService.synchronize (D:\projects\test\backend\src\modules\task\task.service.ts:77:16)
    at new TaskService (D:\projects\test\backend\src\modules\task\task.service.ts:28:10)
    at Injector.instantiateClass (D:\projects\test\backend\node_modules\@nestjs\core\injector\injector.js:330:19)
    at callback (D:\projects\test\backend\node_modules\@nestjs\core\injector\injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Steps to reproduce

No steps

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows       |
| Node.js version     | 16.13.0  |
| Typescript version  | 4.3.5  |
| TypeORM version     | 0.312  |

### Additional Context

{
      ssl: false,
      extra: {
        ssl: null,
        insecureAuth: true,
      },
      entities: [path.join(__dirname, '../entities/*.entity{.ts,.js}'), path.join(__dirname, '../../modules/*/entities/*.entity{.ts,.js}'), path.join(__dirname, '../../customers/*/modules/*/entities/*.entity{.ts,.js}')],
      type: 'postgres',
      host: configService.get('DB_HOST'),
      port: configService.get('DB_PORT'),
      username: configService.get('DB_USERNAME'),
      password: configService.get('DB_PASSWORD'),
      database: configService.get('DB_DATABASE'),
      schema: configService.get('DB_SCHEMA'),
      synchronize: false,
      retryAttempts: 3,
      retryDelay: 2000,
      logging: configService.get('LOGGING'),
    }

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by tabernha** [comment]
I'm having the same issue with a similar Windows environment (Typescript version 4.9.5 and Node version 16.19.0) and Postgres. Additionally, TypeORM doesn't find the migrations anymore, even thought the resolved path looks correct in the console output. It worked correctly with version 0.3.11. 
My DataSourceOptions:
```
{
 ...,
  entities: [
    path.join(__dirname, "dist/backend/**/model/*.js"),
    path.join(__dirname, "backend/**/model/*.js"),
  ],
  migrations: [path.join(__dirname, "migrations/*.js")],
...
}
```

**Comment by omar-contreras-mayasoft** [comment]
> 

I found a solution to avoid having to change the version of typeorm:
`import { getMetadataArgsStorage } from 'typeorm';
{
...,
      entities: getMetadataArgsStorage().tables.map(tbl => tbl.target),
      type: 'postgres',
.....
}`

**Comment by MBogdan18** [comment]
Seems to be related to https://github.com/typeorm/typeorm/issues/9766 which indicates to be a pathing issues and how it works in the latest version. The solution, as mentioned there, is to downgrade to 0.3.11 and wait for the problem to be fixed.

**Comment by OutsideNerd** [comment]
I encountered the exact same error message when using `v0.3.12`. This issue goes away for me when doing one of the following:

1. Downgrading to `v0.3.11` 
2. Running the code with `v0.3.12` on MacOS

Definitely specific to this patch increment and to Windows OS.

**Comment by stancillous** [comment]
I kid you not, I've struggled with this for over 3 hours. Finally found a solution that works for me.

Add this code in your file just before you try to 'interact' with the database: query, save, etc

if (!AppDataSource.isInitialized) {
    await AppDataSource.initialize()
}
this'll basically wait until there's a connection to your database before you interact with it.

**Comment by django102** [comment]
> if (!AppDataSource.isInitialized) {
> await AppDataSource.initialize()
> }

Hi. This also just worked for me. Any idea why this happened? I already have a loader that should initialize the datasource...and it does.

**Comment by abdeljalil09** [comment]
doesnt work in a forked process when you import the datasource it ouputs the error EntityMetadataNotFoundError: No metadata for , works in the main thread where it is initialized at app boot

**Comment by matyas-gubis** [comment]
For anyone coming arriving to this post, maybe my solution will help. I am using NestJS and problem for me came from the fact, that I accidentally wrote UserModule to the TypOrmModule.forFeature() inside the UserModule. Which is a nobrainer, but sometime a simple typo like this can cause headaches 😄 
Before:
```ts
@Module({
  imports: [TypeOrmModule.forFeature([UserModule])],
  controllers: [UserController],
  providers: [UserService],
})
export class UserModule {}
```

After:
```ts
@Module({
  imports: [TypeOrmModule.forFeature([User])],
  controllers: [UserController],
  providers: [UserService],
})
export class UserModule {}
```

**Comment by titi0001** [comment]
Guys, I got here because of what I thought was a bug that was similar to this same return in the console, but looking at the documentation I arrived at this method below:
autoLoadEntities: true,
my typeorm configuration looked like this:

```
@Injectable()
export class PostgresConfigService implements TypeOrmOptionsFactory {
  constructor(private configService: ConfigService) {}

  createTypeOrmOptions(): TypeOrmModuleOptions {
    return {
      type: 'postgres',
      host: this.configService.get<string>('DB_HOST'),
      port: this.configService.get<number>('DB_PORT'),
      username: this.configService.get<string>('DB_USER'),
      password: this.configService.get<string>('DB_PASS'),
      database: this.configService.get<string>('DB_NAME'),
      entities: [__dirname + '/**/*.entity{.ts,.js}'],
      synchronize: true,
      autoLoadEntities: true,  // insert this
    };
  }
}
```

I hope I can help!!!

**Comment by oliverlockwood** [comment]
This issue can also occur because the `entities` value in the `TypeOrmModuleOptions` doesn't include the entity files.
In my case, I hit this because I had renamed the folder containing the entity classes, and hadn't yet updated this value.

Hope this helps someone else.
