### ISSUE TITLE
Unable to generate migration with React Native and React-Native-Sqlite-Storage

### ISSUE THREAD

**Issue by AndersonCosta28** [typeorm/typeorm#9904]
### Issue description

Module and commonjs type conflict

### Expected Behavior

That the migration is normally generated as if using a sqlite in the database type

### Actual Behavior

I have a project that I need to synchronize changes to entities in the database using migrations that generates an error from the moment I install the React-native and React-native-sqlite-storage package: ```
$ yarn typeorm migration:generate ./src/migration/migration -d ./src/data-source.ts
yarn run v1.22.19
warning package.json: No license field
$ typeorm-ts-node-commonjs migration:generate ./src/migration/migration -d ./src/data-source.ts
Error during migration generation:
Error: Unable to open file: "C:\Users\Anderson\Desktop\Projetos_JavaScript\typeorm-reactnative\src\data-source.ts". Cannot use import statement outside a module
     at Function.loadDataSource (C:\Users\Anderson\Desktop\Projetos_JavaScript\typeorm-reactnative\node_modules\src\commands\CommandUtils.ts:22:19)
     at async Object.handler (C:\Users\Anderson\Desktop\Projetos_JavaScript\typeorm-reactnative\node_modules\src\commands\MigrationGenerateCommand.ts:73:26)```

Note:
* I've used several alternatives: `typeorm-ts-node-commonjs`, `typeorm-ts-node-esm`, transpiling to javascript at the end gives the same error

* This [issue](https://github.com/typeorm/typeorm/issues/9760) recommends using `npx ts-node ./node_modules/.bin/typeorm` but gives the following error:
```
$ npx ts-node ./node_modules/.bin/typeorm migration:generate ./src/migration/migration -d ./src/data-source.ts
C:\Users\Anderson\Desktop\JavaScript_Projects\typeorm-reactnative\node_modules\.bin\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
           ^^^^^^^

SyntaxError: missing ) after argument list
     at internalCompileFunction (node:internal/vm:73:18)
     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
     at Module._compile (node:internal/modules/cjs/loader:1218:27)
     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
     at Object.require.extensions.<computed> [as .js] (C:\Users\Anderson\Desktop\JavaScript_Projects\typeorm-reactnative\node_modules\ts-node\src\index.ts:1608:43)
     at Module.load (node:internal/modules/cjs/loader:1117:32)
     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     at phase4 (C:\Users\Anderson\Desktop\JavaScript_Projects\typeorm-reactnative\node_modules\ts-node\src\bin.ts:649:14)
     at bootstrap (C:\Users\Anderson\Desktop\JavaScript_Projects\typeorm-reactnative\node_modules\ts-node\src\bin.ts:95:10)
```

### Steps to reproduce

Create an new project with typeorm cli:
* typeorm init --database sqlite
* install react-native and react-native-sqlite-storage
* change data-source.ts to:
```
import "reflect-metadata"
import "react-native-sqlite-storage"
import { DataSource } from "typeorm"
import { User } from "./entity/User"

export const AppDataSource = new DataSource({
    type: "react-native",
    database: "database",
    synchronize: true,
    logging: false,
    entities: [User],
    location: "default"
})

```
* run in cli ```yarn typeorm migration:generate ./src/migration/migration -d ./src/data-source.ts```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows11       |
| Node.js version     | 18.15.0  |
| Typescript version  | 5.0.2  |
| TypeORM version     | 0.3.12  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [X] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by L-U-C-K-Y** [comment]
I am facing the same issue, where you able to find a solution @AndersonCosta28 ?

**Comment by scerdal** [comment]
The script `./node_modules/.bin/typeorm` that your command `npx ts-node ./node_modules/.bin/typeorm` is trying to run is a bash script, which you're trying to run on Windows. Try changing your command to call the underlying script directly by:
```npx ts-node ./node_modules/typeorm/cli.js```

**Comment by kpotter-m2** [comment]
> The script `./node_modules/.bin/typeorm` that your command `npx ts-node ./node_modules/.bin/typeorm` is trying to run is a bash script, which you're trying to run on Windows. Try changing your command to call the underlying script directly by: `npx ts-node ./node_modules/typeorm/cli.js`

a year later and this is the only solution that worked for me. thank you!
