### ISSUE TITLE
EntityPropertyNotFound when using getters and setters in an Entity with column alias

### ISSUE THREAD

**Issue by nrdennis** [typeorm/typeorm#9931]
### Issue description

Encountering an EntityPropertyNotFound error when using getters and setters with the @Column attribute with the column name specified in an Entity class using the Active Record style on where, orderBy, and select clauses

### Expected Behavior

The query should succeed when the correct name is given to the select, where, or order clauses when querying with an Active Record

### Actual Behavior

An error is encountered:

```
EntityPropertyNotFoundError: Property "createdAt" was not found in "User". Make sure your query is correct.
    at SelectQueryBuilder.buildOrder (/workspaces/template/node_modules/src/query-builder/SelectQueryBuilder.ts:4057:23)
    at SelectQueryBuilder.applyFindOptions (/workspaces/template/node_modules/src/query-builder/SelectQueryBuilder.ts:3113:22)
    at SelectQueryBuilder.setFindOptions (/workspaces/template/node_modules/src/query-builder/SelectQueryBuilder.ts:104:14)
    at EntityManager.find (/workspaces/template/node_modules/src/entity-manager/EntityManager.ts:1081:14)
    at Repository.find (/workspaces/template/node_modules/src/repository/Repository.ts:524:29)
    at Function.find (/workspaces/template/node_modules/src/repository/BaseEntity.ts:463:40)
    at UserController.getAllUsers (/workspaces/template/server_src/api/controllers/user.controller.ts:23:17)
    at ActionMetadata.callMethod (/workspaces/template/node_modules/src/metadata/ActionMetadata.ts:252:44)
    at /workspaces/template/node_modules/src/RoutingControllers.ts:123:28
```

### Steps to reproduce

```
import { Entity, Column, PrimaryColumn, BaseEntity, DataSource } from 'typeorm';

@Entity()
export class User extends BaseEntity {
  @PrimaryColumn({ name: 'orderColumn' })
  private _orderColumn: number;

  @Column()
  name: string;

  get orderColumn() {
    return this._orderColumn;
  }

  set orderColumn(value: number) {
    this._orderColumn = value;
  }
}

async function run() {
  const MysqlDataSource = new DataSource({
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'mariadb',
    password: 'mariadb',
    database: 'mariadb',
    synchronize: true,
    logging: ['error'],
    entities: [User],
  });

  await MysqlDataSource.initialize();

  await User.find({
    order: { orderColumn: 'ASC' },
  });
}

run();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS 13.2.1 |
| Node.js version     | 18.14.0  |
| Typescript version  | 5.0.3  |
| TypeORM version     | 0.3.13  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by nrdennis** [comment]
I do think it would still be a nice feature to be able to use getters and setters to transform data using built-in syntax of ECMAScript. Now that typeorm is under new leadership, would this be valid for consideration (see pleerock's comment in PR)? If so I can check the PR to see what changes are needed.
