### ISSUE TITLE
References between materialized views in migrations result in unresolved transaction state

### ISSUE THREAD

**Issue by joachimbulow** [typeorm/typeorm#9933]
### Issue description

When we have any references between materialized views in our migrations, we are unable to reobtain a valid connection instead getting error

### Expected Behavior

We are often running tests and local development using the `dropSchema`. option for typeOrm.
Our `database/migrations` folder essentially holds 2 files, `tables.sql` and `views.sql`. These contain the entire schema to recreate with ease.
We have recently started utilizing materialized views, and want to utilize the pre-computation capabilities to compute some expensive data.
We expect there to be a seamless integration when we have one materialized view depending on another - given they would be created in the correct order.

### Actual Behavior

Any reference to one materialized view from another in the migration transaction seems to leave us in a state where the next connection fails with the following error:

```
error: error: current transaction is committed, commands ignored until end of transaction block
    at Parser.parseErrorMessage (.../node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (.../pg-protocol/src/parser.ts:188:21)
    at Parser.parse .../pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (.../node_modules/pg-protocol/src/index.ts:7:48)
```

Resulting in `QueryFailedError: current transaction is committed, commands ignored until end of transaction block` as soon as any new connection is attempted to be established

### Steps to reproduce

1. Add a file my_migration.ts like this

```
import { Logger } from '@nestjs/common';
import fs from 'fs';
import path from 'path';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class my_schema_migration implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    Logger.log('Creating base database schema...', 'migrate');

     const tables = fs.readFileSync(path.join(__dirname, './tables.sql'), 'utf-8');
    // const views = fs.readFileSync(path.join(__dirname, './views.sql'), 'utf-8');
    const myMatViews = fs.readFileSync(path.join(__dirname, './my_materialized_views.sql'), 'utf-8');

    await queryRunner.query(tables);
    await queryRunner.query(myMatViews);

    Logger.log('Done creating base database schema!', 'migrate');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
  // Removed for brevity
  }
}
```

Feel free to add the absolute simplest schema for tables and views. Just make sure you reference one materialized view from another. An example could be something like:

tables.sql:
```
CREATE TYPE language_enum AS ENUM ('DA', 'EN');
CREATE TYPE region_enum AS ENUM ('EUROPE_WEST', 'US_WEST', 'US_EAST');
CREATE TABLE "user"
(
    region          region_enum   NOT NULL DEFAULT 'EUROPE_WEST',
    id              uuid          NOT NULL DEFAULT uuid_generate_v4(),
    "language"      language_enum NULL     DEFAULT 'DA',
    PRIMARY KEY (region, id)
);
```

my_materialized_views.sql:
```

CREATE MATERIALIZED VIEW en_users AS
 SELECT id
 FROM "user"
 WHERE language = 'EN';

CREATE MATERIALIZED VIEW my_favourite_en_users AS
 SELECT id
 FROM en_users;
```

- Run migration by using the `dropSchema` and `migrationsRun` options set to true for typeOrm. 
- Interact with system.
In our case we use `NestJs` and save some default entities in an `onModuleInit` call, immediately throwing a fatal exception.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS 12.6.2      |
| Node.js version     | 17.8.0  |
| Typescript version  | 4.7.4  |
| TypeORM version     | 0.3.74  |

### Additional Context

We use cockroachdb 

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [X] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by joachimbulow** [comment]
Might just be a cockroach limitation issue for materialized views:
https://www.cockroachlabs.com/docs/stable/known-limitations.html

Workaround:
Pass `migrationsTransactionMode: ''none`, separate the depending materialized views into their own migration file, and use explicit transactions instead.
