### ISSUE TITLE
 No metadata for "SetsEntity" was found using a generic repository

### ISSUE THREAD

**Issue by Hiomma** [typeorm/typeorm#9952]
### Issue description

 No metadata for "SetsEntity" was found using a generic repository

### Expected Behavior

When using the repository, the function returns with the respective object.

### Actual Behavior

For example, I was trying to pass a repository through the super function and when the line is executed I got this error:

`EntityMetadataNotFoundError: No metadata for "SetsEntity" was found.
    at DataSource.getMetadata (D:\Projetos\Interno\NestJS\flash-learn-backend\src\data-source\DataSource.ts:444:30)
    at Repository.get metadata [as metadata] (D:\Projetos\Interno\NestJS\flash-learn-backend\src\repository\Repository.ts:53:40)
`

### Steps to reproduce

To reproduce this error is simple, I made this code:

sets.repository.ts
```
@Injectable()
export class SetsRepository
  extends BaseRepository<SetsEntity>
  implements ISetsRepository
{
  constructor() {
    super(dataSource.getRepository(SetsEntity));
  }
}
```

base.repository.ts

```
export class BaseRepository<Entity> {
  repository: Repository<Entity>;

  constructor(repository: Repository<Entity>) {
    this.repository = repository;
  }

  find(options?: FindManyOptions): Promise<Entity[]> {
    return this.repository.find(options);
  }
}
```

database.provider.ts
```
export const databaseSourceOptions: DataSourceOptions = {
  type: 'mysql',
  host: '127.0.0.1',
  port: 3307,
  username: 'root',
  password: '1234',
  database: 'flash_learn',
  entities: [
    'dist/domain/entities/*.js',
  ],
  migrations: ['dist/infrastructure/database/migrations/*.js'],
  synchronize: false,
};

const dataSource: DataSource = new DataSource(databaseSourceOptions);
export default dataSource;
```

Then, when I request to find a Set (function find in sets.repository.ts extended with base.repository.ts), the referred error happens.
I've already tried to downgrade my typeorm to 0.3.11, and it didn't work, unfortunately. 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows      |
| Node.js version     | 18.12.0  |
| Typescript version  | 4.7.4 |
| TypeORM version     | 0.3.15  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Hiomma** [comment]
Hello guys, after 2 months I got to find my mistake. Maybe many of us can come across one day with this problem.

Check if you forgot to add an await or the whole life in your main.ts:

await dataSource.initialize();
