### ISSUE TITLE
Cannot connect to MySQL (from AWS RDS) while mysql2 package and local connection can connect to DB (with NestJS)

### ISSUE THREAD

**Issue by prunusnira** [typeorm/typeorm#9982]
### Issue description

I keep getting 'Access denied for user ~ ' error message

### Expected Behavior

I expected to connect well with TypeOrmModule.forRoot / forRootAsync. tried both.

options i used

          type: 'mysql',
          host: process.env.MYSQL_DBHOST,
          port: parseInt(process.env.MYSQL_DBPORT),
          username: process.env.MYSQL_DBUSER,
          password: process.env.MYSQL_DBPWD,
          database: process.env.MYSQL_DBNAME,
          logging: process.env.NODE_ENV !== 'prod' ? true : false,
          synchronize: false,

They are all correct values, and please note that
I can connect to RDS from local terminal or within EC2 environment.
Also I was simply able to connect with mysql2 package, without TypeOrm.

### Actual Behavior

[Nest] 15880  - 04/25/2023, 7:44:40 PM   ERROR [ExceptionHandler] Access denied for user '[db user]'@'?.?.fios.verizon.net' (using password: YES)
Error: Access denied for user '[db user]'@'?.?.fios.verizon.net' (using password: YES)
    at Packet.asError (/Users/project/admin-backend/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/Users/project/admin-backend/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/project/admin-backend/node_modules/mysql2/lib/connection.js:489:32)
    at PacketParser.onPacket (/Users/project/admin-backend/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (/Users/project/admin-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/project/admin-backend/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)

### Steps to reproduce

Simply using TypeOrmModule at app.module.ts

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Local = Mac 13 (Arm) / Remote = AmazonLinux 2        |
| Node.js version     | 18.15.0  |
| Typescript version  | 4.7.4  |
| TypeORM version     | I tried 0.3.15, 0.3.12, 0.3.11  |

even I tried both mysql2 and mysql package

### Additional Context

AWS RDS is connected via AWS bastion host

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by prunusnira** [comment]
after further investigation, it is concluded as server setting issue. closing issue
